### PR TITLE
fix vs2019 warnings: conversion from 'bit' to 'bool'

### PR DESCRIPTION
**Pull request by gvollant**
when use a bit variable to call function which need a bool, Visual Studio 2019 display:
warning C4244:  'function': conversion from 'bit' to 'bool', possible loss of data

This simple PR just add a (bool) cast

### CODE REVIEW

**Comment by bagder** [comment]
~~~
./ftp.c:3609:81: warning: Longer than 79 columns (LONGLINE)
         result = ftp_nb_type(conn, (bool)data->set.prefer_ascii, FTP_RETR_TYPE);

**Comment by bagder** [comment]
See also #4189 which is basically a duplicate. Can we first figure out how we can get these warnings to show up in the existing CI builds?

**Comment by gvollant** [comment]
It seem there is no VS2019 build on the appveyor build. PEhaps you can add a VS2019 build, or migrate one from VS2017 to 2019

 

De : Daniel Stenberg [mailto:notifications@github.com] 
Envoyé : jeudi 19 septembre 2019 14:08
À : curl/curl
Cc : gvollant; Author
Objet : Re: [curl/curl] fix warning vs2019 (#4379)

 

See also #4189 <https://github.com/curl/curl/pull/4189>  which is basically a duplicate. Can we first figure out how we can get these warnings to show up in the existing CI builds?

**Comment by gvollant** [comment]
I'm surprised that checks are not sucessful with only cast

**Comment by bagder** [comment]
Looks like the regular false positives we get...

**Comment by bagder** [comment]
The coming VS2019 builds in #4383 show the problems this PR aims to fix.

**Comment by jay** [comment]
try using _Bool for bit type

**Comment by bagder** [comment]
That's a good idea!

**Pull request closed without merging**
