### PR TITLE
CI/GHA: merge bearssl and hyper into initial linux workflow

### PR DESCRIPTION
**Pull request by mback2k**
Begin work on merging all Linux workflows into one file.

[skip azp]

### CODE REVIEW

**Comment by mback2k** [comment]
I will have to rethink this as GitHub unfortunately does not seem to support YAML anchors at the moment:
> The workflow is not valid. .github/workflows/linux.yml: Anchors are not currently supported. Remove the anchor 'bearssl_install_script'
image

My goal is still to reduce YAML duplication and also get rid of this redundancy and convolution in the Checks tab of PRs:
image

**Comment by pheiduck** [comment]
I would appreciate it if we remove / hide workflows that have not been running for a while. What only the owner of the repo can do.

**Comment by mback2k** [comment]
> I would appreciate it if we remove / hide workflows that have not been running for a while. What only the owner of the repo can do.

Good idea, I will try to do that.

**Comment by mback2k** [comment]
bearssl and hyper builds looking good merged together:
image image 

@bagder @pheiduck what do you think about this approach (including install_steps)? Should I continue with more workflows?

**Comment by bagder** [comment]
It looks good! shouldn't this PR also remove `.github/workflows/linux-hyper.yml`  ?

**Comment by mback2k** [comment]
It does, but GitHub renders it as a rename instead.

**Pull request closed without merging**
