### PR TITLE
configure: check for the capath by default

### PR DESCRIPTION
**Pull request by bagder**
... and adapt how wolfSSL uses it.

### CODE REVIEW

**Comment by michael-o** [comment]
Is this an extract of my open PR? Why not merge the PR then?

**Comment by bagder** [comment]
How so? I did not read anything about this in your PR?

**Comment by michael-o** [comment]
> How so? I did not read anything about this in your PR?

My PR introduces CA path support for wolfSSL for the detection, lib and the CLI tool. I have also supplied test case (output) for this.

**Comment by bagder** [comment]
Ah yes, now I see that you did a partial of this indeed. Sorry, it was not intended. I just fell over this when double-checking how the capath is (not) used when I merged your #11985

**Comment by michael-o** [comment]
> Ah yes, now I see that you did a partial of this indeed. Sorry, it was not intended. I just fell over this when double-checking how the capath is (not) used when I merged your #11985

Maybe we can conclude my PR first and then you can do additional improvements?

**Comment by bagder** [comment]
> Maybe we can conclude my PR first and then you can do additional improvements?

I believe my fix is a little different and the more complete ca path (check by default) fix, whilst yours is a partial.

**Comment by michael-o** [comment]
> > Maybe we can conclude my PR first and then you can do additional improvements?
> 
> I believe my fix is a little different and the more complete ca path (check by default) fix, whilst yours is a partial.

They intersect, but your does not cover:
* https://github.com/curl/curl/pull/11934/files#diff-b781fde347898f87c1814ea8961b8e39c2615374b2811e7fc91047e7517d9b57R1472
* https://github.com/curl/curl/pull/11934/files#diff-3af1bbcce847e53c6bda3ab22d961a2cffc8e35dc00ce478c3caed9b96e23245R64
* https://github.com/curl/curl/pull/11934/files#diff-95b5a6b3c748c28e68f06da950e20527969b2d64391c6e21c731b4823827b65cR1390

**Comment by bagder** [comment]
your wolfssl.c change is not the correct one though, see my change

**Comment by michael-o** [comment]
> your wolfssl.c change is not the correct one though, see my change

You mean `wolfSSL_CTX_load_verify_locations()`? I intentionally did not touch for `wolfSSL_CTX_load_verify_locations_ex(()` because this changes behavior and didn't move to an rc variable to keep the diff small.

**Comment by bagder** [comment]
> You mean `wolfSSL_CTX_load_verify_locations()`? I intentionally did not touch for `wolfSSL_CTX_load_verify_locations_ex(()` because this changes behavior and didn't move to an rc variable to keep the diff small.

It is actually necessary for **not** changing the behavior. Without that change, wolfSSL can't run on a vanilla Debian that has a capath.

**Review by michael-o — COMMENTED** [review]
This looks reasonable now for me. I can rebase my PR on top of this when merged into master.

**Comment by michael-o** [comment]
> > You mean `wolfSSL_CTX_load_verify_locations()`? I intentionally did not touch for `wolfSSL_CTX_load_verify_locations_ex(()` because this changes behavior and didn't move to an rc variable to keep the diff small.
> 
> It is actually necessary for **not** changing the behavior. Without that change, wolfSSL can't run on a vanilla Debian that has a capath.

Not only on Debian, but everywhere where you have expired or invalid CA cers. Noticed this one as well.

**Comment by bagder** [comment]
> Not only on Debian, but everywhere where you have expired or invalid CA cers. Noticed this one as well.

Sure, I meant "in widely used setups". I just happened to test on Debian.

**Comment by vszakats** [comment]
Patch to sync this with CMake (if I understand correctly):
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 0ad4081fc..5eb6e94d6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1011,9 +1011,13 @@ elseif(CURL_CA_PATH_AUTODETECT OR CURL_CA_BUNDLE_AUTODETECT)
   endif()
 endif()
 
-if(CURL_CA_PATH_SET AND NOT USE_OPENSSL AND NOT USE_MBEDTLS)
+if(CURL_CA_PATH_SET AND
+   NOT USE_OPENSSL AND
+   NOT USE_WOLFSSL AND
+   NOT USE_GNUTLS AND
+   NOT USE_MBEDTLS)
   message(STATUS
-          "CA path only supported by OpenSSL, GnuTLS or mbed TLS. "
+          "CA path only supported by OpenSSL, wolfSSL, GnuTLS or mbedTLS. "
           "Set CURL_CA_PATH=none or enable one of those TLS backends.")
 endif()
```

**Comment by bagder** [comment]
Thanks @vszakats and @michael-o for your help on this, I have you both credited in the commits as well as @julek-wolfssl.

**Comment by michael-o** [comment]
> Thanks @vszakats and @michael-o for your help on this, I have you both credited in the commits as well as @julek-wolfssl.

Thanks, I will rebase and rephrase my PR.

**Pull request closed without merging**
