### PR TITLE
workflows/macos: install impacket

### PR DESCRIPTION
**Pull request by pheiduck**
needed Python Package for SMB tests (on macos ci as well)

### CODE REVIEW

**Comment by pheiduck** [comment]
I think we sholud add this at least to macos CI's otherwise the SMB tests are failing

**Comment by bagder** [comment]
Where do they fail? The CI builds on macos are green...

**Comment by pheiduck** [comment]
`== Contents of files in the log/ dir after test 1451
RUN: failed to start the SMB server
test 1451 SKIPPED: failed starting SMB server
 `
but could maybe a error inside the test 1451?

**Comment by pheiduck** [comment]
the installation makes no difference to her, so anyway it still reports the package is not installed

**Pull request closed without merging**
