### PR TITLE
runtest.pl: add expected fourth return value

### PR DESCRIPTION
**Pull request by scrtt**
Fixes warning in autobild log: "Use of uninitialized value $HTTP2TLSPORT in substitution iterator at /tests/runtests.pl line 3516"

### CODE REVIEW

**Review by bagder — APPROVED** [review]

**Review by MarcelRaad — APPROVED** [review]
Thanks!

**Comment by bagder** [comment]
Thanks!

**Comment by MarcelRaad** [comment]
This is a regression from commit https://github.com/curl/curl/commit/c7fb341c0eec9adf0bbb1da27622449bf5db45e8. Is there anything we could do to make this visible in the PRs instead of the autobuilds? I remember similar warnings like this in the past.

**Comment by bagder** [comment]
Yeah, they are however "just" warnings so the tests still work fine. A quick googling showed me a trick on how we can "promote" these warnings to errors, which should make them more noticeable. I'll try it in a PR!

**Pull request closed without merging**
