### PR TITLE
GHA: prepare workflow merge by aligning structure again

### PR DESCRIPTION
**Pull request by mback2k**
My long-term plan is still to merge at least all the Linux builds into a single workflow-file for easier management and reduced duplication (like the macOS one, although bigger). Staying aligned with the matrix build structure will make that merge easier.

### CODE REVIEW

**Comment by bagder** [comment]
So what's the idea behind the separation of the install packages in the separate places?

**Comment by mback2k** [comment]
The idea is to have common packages which are always required for all Linux CIs on the apt step line, but those that are variant specific in the matrix build config. Of course there can still be a small duplication then there for similar variants, but with YAML anchors there is also a solution for that.

**Comment by bagder** [comment]
Oh right, you mean if you would merge those matrix builds into a unified file?

**Comment by mback2k** [comment]
Yes, exactly.

**Comment by mback2k** [comment]
Any objections against merging this @bagder ?

**Comment by bagder** [comment]
No objections, but I don't see the point in this change unless you also merge the files.

**Comment by mback2k** [comment]
Thanks. That will be my next endeavor.

**Pull request closed without merging**
