### PR TITLE
lib3028: check CURLOPT_CERTINFO certificate chain contains leaf first.

### PR DESCRIPTION
**Pull request by nmoinvaz**
This lib test checks that the certificate chain returned from `curl_easy_getinfo(curl, CURLINFO_CERTINFO, &cert_info)` is in the correct order: leaf first, root last. 

This was inspired by the fact that on recent versions of Windows 11 22H2, the certificates returned from SChannel are in reverse order.  See #9706.

I have named it `lib3028` but I can rename to whatever you want, because I didn't see anywhere what each range of tests targeted.

### CODE REVIEW

**Comment by nmoinvaz** [comment]
On my second commit I realized that we can just compare the entire distinguished name since curl is the one constructing both in the exact same way with ASN1 class. I can squash if needed.

**Comment by nmoinvaz** [comment]
Output looks like this on failure:
```
cert 0
  subject: C=US, O=DigiCert Inc, CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
  issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
cert 1
  subject: C=US, ST=California, L=San Francisco, O=GitHub, Inc., CN=github.com
  issuer: C=US, O=DigiCert Inc, CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
cert 0 issuer does not match cert 1 subject
certificate chain is not in order
```
Output looks like this on success:
```
cert 0
  subject: C=US, ST=California, L=San Francisco, O=GitHub, Inc., CN=github.com
  issuer: C=US, O=DigiCert Inc, CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
cert 1
  subject: C=US, O=DigiCert Inc, CN=DigiCert TLS Hybrid ECC SHA384 2020 CA1
  issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert Global Root CA
certificate chain is in order
```

**Comment by dfandrich** [comment]
> I have named it lib3028 but I can rename to whatever you want, because I didn't
> see anywhere what each range of tests targeted.

There used to be a specified ranges for tests but that was removed in commit
a8ac1be7 because people were ignoring it anyway.

**Comment by nmoinvaz** [comment]
Squashed commits.

**Comment by bagder** [comment]
It looks good.

This is doesn't actually *run* the test though, you need a `tests/data/test3028` file for that.

**Comment by nmoinvaz** [comment]
I'm not exactly sure what I should do for a `test3028`, so I just copied `test300` which is a simple HTTPS GET. When I tested `lib3028` I just would pass it https://example.com/ or https://github.com/.

**Comment by nmoinvaz** [comment]
Looks like that didn't work. I'm not exactly sure what I'm doing wrong.

**Comment by nmoinvaz** [comment]
@bagder do you have any hints about what I might be doing wrong with this test data? 🙏🏻

**Comment by nmoinvaz** [comment]
Nevermind. I figured it out.

**Pull request closed without merging**
