### PR TITLE
gsasl: fix errors/warnings building against libgsasl

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://github.com/curl/curl/pull/6372#issuecomment-776118711

### CODE REVIEW

**Comment by jay** [comment]
> Known issue: Unused `chlg64len` still needs to be fixed.

Is there any reason you can't just remove it

**Comment by vszakats** [comment]
I used that locally for testing the build, but haven't looked into the logic to tell if this was the original intent. Hopefully @jas4711 can jump in.

**Comment by bagder** [comment]
Additionally, I still got this error (presumably because I got a libgsasl version triggering the "right" ifdef combo):
~~~
vauth/gsasl.c: In function ‘Curl_auth_gsasl_start’:
vauth/gsasl.c:63:50: error: unused parameter ‘data’ [-Werror=unused-parameter]
   63 | CURLcode Curl_auth_gsasl_start(struct Curl_easy *data,
      |                                ~~~~~~~~~~~~~~~~~~^~~~
~~~
I could silence that with:
~~~diff
diff --git a/lib/vauth/gsasl.c b/lib/vauth/gsasl.c
index abc3f3a6a..9a697b29b 100644
--- a/lib/vauth/gsasl.c
+++ b/lib/vauth/gsasl.c
@@ -68,10 +68,11 @@ CURLcode Curl_auth_gsasl_start(struct Curl_easy *data,
 #if GSASL_VERSION_NUMBER >= 0x010a01
   int res;
   res =
 #endif
   gsasl_property_set(gsasl->client, GSASL_AUTHID, userp);
+  (void)data;
 #if GSASL_VERSION_NUMBER >= 0x010a01
   if(res != GSASL_OK) {
     failf(data, "setting AUTHID failed: %s\n", gsasl_strerror(res));
     return CURLE_OUT_OF_MEMORY;
   }

**Comment by vszakats** [comment]
@jay I think you're right and that line must just go. It's possibly a leftover from an earlier iteration that did not yet use `Curl_base64_decode()`. I've committed it.

A review or even a manual functional test is much appreciated here.

**Comment by jay** [comment]
Though I'm not building or familiar with GSASL the changes look fine to me.

**Comment by bagder** [comment]
I think `Curl_auth_gsasl_token()` would benefit from a) using `CURLcode` and b) return proper error code. Here's my proposed additional patch:
~~~diff
diff --git a/lib/vauth/gsasl.c b/lib/vauth/gsasl.c
index 910b9b85f..c924e1be0 100644
--- a/lib/vauth/gsasl.c
+++ b/lib/vauth/gsasl.c
@@ -98,36 +98,40 @@ CURLcode Curl_auth_gsasl_token(struct Curl_easy *data,
                                struct gsasldata *gsasl,
                                char **outptr, size_t *outlen)
 {
   unsigned char *chlg = NULL;
   size_t chlglen = 0;
-  int result;
+  CURLcode result = CURLE_OK;
+  int res;
   char *response;
 
   if(chlg64) {
     result = Curl_base64_decode(chlg64, &chlg, &chlglen);
     if(result)
       return result;
   }
 
-  result = gsasl_step(gsasl->client,
-                      (const char *)chlg, chlglen, &response, outlen);
-  if(result != GSASL_OK && result != GSASL_NEEDS_MORE) {
+  res = gsasl_step(gsasl->client,
+                   (const char *)chlg, chlglen, &response, outlen);
+  if(res != GSASL_OK && res != GSASL_NEEDS_MORE) {
     if(chlg64)
       free(chlg);
-    failf(data, "GSASL step: %s\n", gsasl_strerror(result));
+    failf(data, "GSASL step: %s\n", gsasl_strerror(res));
     return CURLE_BAD_CONTENT_ENCODING;
   }
 
   if(*outlen > 0) {
     result = Curl_base64_encode(data, response, 0, outptr, outlen);
     gsasl_free(response);
   }
-  else
+  else {
     *outptr = strdup("");
+    if(!*outptr)
+      result = CURLE_OUT_OF_MEMORY;
+  }
 
-  return CURLE_OK;
+  return result;
 }
 
 void Curl_auth_gsasl_cleanup(struct gsasldata *gsasl)
 {
   gsasl_finish(gsasl->client);

**Comment by jas4711** [comment]
> I think `Curl_auth_gsasl_token()` would benefit from a) using `CURLcode` and b) return proper error code. Here's my proposed additional patch:
> 
> ```diff
> diff --git a/lib/vauth/gsasl.c b/lib/vauth/gsasl.c
> index 910b9b85f..c924e1be0 100644
> --- a/lib/vauth/gsasl.c
> +++ b/lib/vauth/gsasl.c
> @@ -98,36 +98,40 @@ CURLcode Curl_auth_gsasl_token(struct Curl_easy *data,
>                                 struct gsasldata *gsasl,
>                                 char **outptr, size_t *outlen)
>  {
>    unsigned char *chlg = NULL;
>    size_t chlglen = 0;
> -  int result;
> +  CURLcode result = CURLE_OK;
> +  int res;
>    char *response;
>  
>    if(chlg64) {
>      result = Curl_base64_decode(chlg64, &chlg, &chlglen);
>      if(result)
>        return result;
>    }
>  
> -  result = gsasl_step(gsasl->client,
> -                      (const char *)chlg, chlglen, &response, outlen);
> -  if(result != GSASL_OK && result != GSASL_NEEDS_MORE) {
> +  res = gsasl_step(gsasl->client,
> +                   (const char *)chlg, chlglen, &response, outlen);
> +  if(res != GSASL_OK && res != GSASL_NEEDS_MORE) {
>      if(chlg64)
>        free(chlg);
> -    failf(data, "GSASL step: %s\n", gsasl_strerror(result));
> +    failf(data, "GSASL step: %s\n", gsasl_strerror(res));
>      return CURLE_BAD_CONTENT_ENCODING;
>    }
>  
>    if(*outlen > 0) {
>      result = Curl_base64_encode(data, response, 0, outptr, outlen);
>      gsasl_free(response);
>    }
> -  else
> +  else {
>      *outptr = strdup("");
> +    if(!*outptr)
> +      result = CURLE_OUT_OF_MEMORY;
> +  }
>  
> -  return CURLE_OK;
> +  return result;
>  }
>  
>  void Curl_auth_gsasl_cleanup(struct gsasldata *gsasl)
>  {
>    gsasl_finish(gsasl->client);
> ```

Yes this looks nicer!

**Comment by bagder** [comment]
@vszakats if you get https://github.com/curl/curl/pull/6587#issuecomment-776495568 into here as well, I think this PR is a winner!

**Comment by vszakats** [comment]
Applied all suggestions. Thanks to all for the inputs!

**Comment by Neustradamus** [comment]
@vszakats, @jay, @bagder, @jas4711: Thanks to all! :)

**Pull request closed without merging**
