### PR TITLE
CI/azure: shorten names of Windows CI jobs

### PR DESCRIPTION
**Pull request by mback2k**
Removes redundant information and strips "_debug" from job names.

Suggested-by: Daniel Stenberg

### CODE REVIEW

**Review by bagder — APPROVED** [review]
:+1: I wish there was a way to improve that "curl.curl" part...

**Comment by mback2k** [comment]
hm, it seems like this is the Azure CI pipeline name with the `.` having been replaced with a `_`. I don't know how rename affects currently running jobs, but I could give it a try and shorten it to just `curl`:
image

**Comment by bagder** [comment]
> I could give it a try and shorten it to just `curl`:

Or just "c", we know the project is curl... Or maybe "azure" ?

**Comment by mback2k** [comment]
> > I could give it a try and shorten it to just `curl`:
> 
> Or just "c", we know the project is curl... Or maybe "azure" ?

hm, what if you ever run more than the curl pipeline in Azure? e.g. if we ever move over my docker build env pipeline?

**Comment by bagder** [comment]
> hm, what if you ever run more than the curl pipeline in Azure? e.g. if we ever move over my docker build env pipeline?

I don't understand the question. A) We could change the name then and B) surely such new jobs can have other names?

**Comment by mback2k** [comment]
> > hm, what if you ever run more than the curl pipeline in Azure? e.g. if we ever move over my docker build env pipeline?
> 
> I don't understand the question. A) We could change the name then and B) surely such new jobs can have other names?

Ok, that is right. So which one would you prefer? I will try to change it then during a time there no Azure job is running.

**Comment by bagder** [comment]
Maybe start with just plain "curl".

**Pull request closed without merging**
