### PR TITLE
multibyte: turn the unicodefree macro into uppercase

### PR DESCRIPTION
**Pull request by bagder**
CURLX_UNICODEFREE() is the name now to make it more obvious to users
that this is a macro and not a plain or pretend-to-be function call.

Suggested-by: Gisle Vanem
Ref: #6457

### CODE REVIEW

**Comment by jay** [comment]
There are other function-like macros like Curl_foo_lowercase why do we need this one all uppercase?

/cc @gvanem

**Comment by bagder** [comment]
We have many function-like macros in lowercase, but for a reader of the code we don't usually need to know the difference between the real function and the macro replacements (as that's probably the most common use for it). This macro is different, as the leak @gvanem just fixed I think showed. It benefits from being a little more noticeable that it is indeed a macro.

**Comment by jay** [comment]
How is it any different from, say, Curl_safefree? I don't think changing the casing would make it any more likely to catch a mistake like that.

**Comment by bagder** [comment]
Curl_safefree() I think works fine because it is always used the same on the same input and as it if was a function.

**Comment by bagder** [comment]
I guess this isn't necessarily a step forward. I'll drop it.

**Pull request closed without merging**
