### PR TITLE
projects: remove directory with Visual Studio project files

### PR DESCRIPTION
**Pull request by bagder**
For building on Windows we encourage use of:
 - winbuild/
 - cmake
 - configure

Proposal sent to the mailing list: https://curl.haxx.se/mail/lib-2020-09/0016.html

Marked as **DRAFT** to signal that this will not be merged until given time for people ample time to respond and comment.

### CODE REVIEW

**Comment by jay** [comment]
Against it. Also I think a proposal like this to remove a build system should have more time. As I just said on the mailing list I'm using these project files. It is the way I build curl for development and debugging.

**Comment by emilengler** [comment]
~0

I'm absolutely not into development on Windows so I won't judge this but I have the feeling that VS is being used heavily for C(++) development on that platform

**Comment by mback2k** [comment]
cc @captain-caveman2k

**Comment by bagder** [comment]
@jay I disagree. If nobody speaks up within a week, experience from many previous discussions says it doesn't help to give more time.

@emilengler we're not ditching Visual Studio builds. `winbuild/` is exactly that

**Comment by mback2k** [comment]
> @jay I disagree. If nobody speaks up within a week, experience from many previous discussions says it doesn't help to give more time.

I would recommend giving a minimum of 2 weeks notice to also give people on vacation a chance to react.

**Review by mback2k — APPROVED** [review]

**Comment by bagder** [comment]
Feedback from users say:

- These files *are* being used
- I've not heard any convincing argument why existing users couldn't switch to use winbuild or cmake instead

**Comment by mback2k** [comment]
_Sad side note:_ @captain-caveman2k and I prepared such a set of project files for the testsuite during FOSDEM 2015, but were never able to finish and land them.

**Comment by bagder** [comment]
I don't feel a lot of love or support for moving forward with this PR. I'll close it now and keep these files around. Maybe open up the discussion again the future. Until then. Closed.

**Comment by dfandrich** [comment]
Would it work to run CMake in the maketgz script to generate the Visual Studio
project files from the CMake files, then ship those?

**Comment by bagder** [comment]
> run CMake in the maketgz script to generate the Visual Studio project files

That's a great idea! It would be great to hear from any visual studio users about the feasibility of doing tht!

**Pull request closed without merging**
