### PR TITLE
(lib)curl.rc: fixup for minor bugs

### PR DESCRIPTION
**Pull request by bagder**
All resources defined in lib/libcurl.rc and curl.rc are language neutral

winbuild/MakefileBuild.vc ALWAYS defines the macro DEBUGBUILD, so the ifdef's in line 33 of lib/libcurl.rc and src/curl.rc are wrong

replace the hard-coded constants in both *.rc files with #define'd
values

URL: https://curl.haxx.se/mail/lib-2018-11/0000.html

(This is from an old email from Stefan Kanthak that seems to not have been addressed...)

### CODE REVIEW

**Comment by bagder** [comment]
This is a patch provided by Stefan. I have no way to judge these changes so I'll appreciate a :+1: or :-1: from someone who do know...

**Comment by rodwiddowson** [comment]
Looks OK but I don't feel qualified to +1 this...

**Comment by dscho** [comment]
>  ifdef's in line 33 of lib/libcurl.rc and src/curl.rc are wrong

This part is missing from the commit message. Otherwise, this PR looks good to me.

**Comment by bagder** [comment]
Thank you!

**Pull request closed without merging**
