### PR TITLE
tests: remove all valgrind disable instructions

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
Let's see how much these still are needed...

**Comment by vszakats** [comment]
Confusing result: with valgrind finally unlocked, the test pass!
https://github.com/curl/curl/actions/runs/10961377146/job/30438158068#step:7:43
```
***************************************** 
test 0605...[SCP retrieval of nonexistent file]
 206 functions found, but only fail 25 (12.14%)
torture OK
TESTDONE: 1 tests were considered during 5 seconds.
TESTDONE: 1 tests out of 1 reported OK: 100%
```
🤔

**Comment by dfandrich** [comment]
Analysis of PR #14983 at [c13da0d7](https://github.com/curl/curl/commit/c13da0d7e9a15bb7880b56b13a935a8730391142):

[Test 705 failed](https://github.com/curl/curl/actions/runs/10961132329/job/30437370519#check-step-25), which has NOT been flaky recently, so **there could be a real issue in the PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by bagder** [comment]
Not a single valgrind problem detected!

**Comment by vszakats** [comment]
Nice!

**Pull request closed without merging**
