### PR TITLE
tests: use a set for several of the curl_props

### PR DESCRIPTION
**Pull request by dfandrich**
These are used for member-of testing, so a set is more appropriate and
efficient. Also, fix a couple cases of bad exceptions.

Closes #15462

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15462 at [610fe738](https://github.com/curl/curl/commit/610fe738d3fbac3e80275cfa8d48eb53fb30e80f):

[Test 1193 failed](https://github.com/curl/curl/actions/runs/11603884227/job/32311695574#check-step-3), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 1917 failed](https://github.com/curl/curl/actions/runs/11603884227/job/32311695574#check-step-3), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 2202 failed](https://github.com/curl/curl/actions/runs/11603884227/job/32311695574#check-step-3), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 2205 failed](https://github.com/curl/curl/actions/runs/11603884227/job/32311695574#check-step-3), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by dfandrich** [comment]
Test comment

**Comment by testclutch** [comment]
Test comment 2

**Comment by testclutch** [comment]
Test comment 3

**Comment by testclutch** [comment]
Test comment 4

**Comment by testclutch** [comment]
Test comment 5

**Pull request closed without merging**
