### PR TITLE
Update CURLOPT_QUOTE.3

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
Added sentence about quotes in the quote.

### CODE REVIEW

**Comment by MonkeybreadSoftware** [comment]
Every time I have to write a quote, I need to lookup what quotes I can use. Now I wrote it into the documentation. I hope it helps me and others.

**Review by bagder — APPROVED** [review]

**Comment by MonkeybreadSoftware** [comment]
Thanks.

**Comment by bagder** [comment]
@MonkeybreadSoftware as I am in the middle of a pretty big refactor of how we do libcurl documentation, I took the liberty and merged this patch into #12730

**Comment by bagder** [comment]
Thanks, fixed in eefcc1bda4bccd

**Pull request closed without merging**
