### PR TITLE
CI: log platform info in pytest

### PR DESCRIPTION
**Pull request by dfandrich**
Use the pytest-astropy-header package to log information about the
running platform in pytest invocations so Test Clutch can include it in
the test run metadata.  This also logs some things less relevant to
curl, but it's small and simple and provides the information we want and
since it's only running in the CI build it won't generally be seen by
humans.

Closes #15256

### CODE REVIEW

**Comment by vszakats** [comment]
Would it make sense to dump the same `buildinfo.txt` we already dump for `runtests`?
This would not need a new dependency, just finding a place where to print it from pytest.

**Comment by dfandrich** [comment]
That would be better, but it means writing our own pytest plug-in somehow. This solution uses existing tools, but doesn't give as much information.

**Comment by vszakats** [comment]
I tried doing this a little while ago, but did not look trivial indeed for some reason.

But, since then, pytests got hooked up into the build systems and started from 
there, so perhaps we could dump `buildinfo.txt` from cmake/autotools directly?

**Comment by dfandrich** [comment]
That would work, but the result would be outside what pytest logs so Test Clutch would currently ignore it. Since pytest is a standard log format that's widely used, I'm trying to avoid adding curl-specific code in there, so doing it within pytest would be much better from that perspective.

**Comment by dfandrich** [comment]
Since this improves the metadata situation today, I'll submit it. If someone figures out a clean way to get more environment info into the logs, we can always switch later.

**Comment by vszakats** [comment]
Is there any reason why a `cat buildinfo.txt` wouldn't work from the pytest CI step instead?

It would add the same metadata in the logs as TestClutch is already parsimg for runtests.

(If it works, it can be moved inside the build scripts.)

**Comment by dfandrich** [comment]
See my "That would work" comment.

**Comment by vszakats** [comment]
> See my "That would work" comment.

Am I understanding correctly that TestClutch is looking for the pytest log output headers to recognize where the step begins?

Would TestClutch find the buildinfo if the `cat` would be at the end of the step, after pytest finished?

**Comment by dfandrich** [comment]
It ignores everything outside the pytest log, so once the log ends, it
considers its job done and stops looking for more. It could be changed, of
course, but when parsing arbitrary logs I want it to be conservative to avoid
false triggering, especially since these log formats aren't designed to be
machine readable.

**Comment by vszakats** [comment]
> It ignores everything outside the pytest log, so once the log ends, it considers its job done and stops looking for more. It could be changed, of course, but when parsing arbitrary logs I want it to be conservative to avoid false triggering, especially since these log formats aren't designed to be machine readable.

Got it. Pytest already puts out there some custom output
via `pytest_report_header`, with server versions, etc. Would
it work to read `buildinfo.txt` there and add it to the string
returned from it?

**Comment by vszakats** [comment]
Something like?:
```diff
--- a/tests/http/conftest.py
+++ b/tests/http/conftest.py
@@ -53,7 +53,10 @@ def pytest_report_header(config):
         report.extend([
             f'  VsFTPD: {env.vsftpd_version()}, ftp:{env.ftp_port}, ftps:{env.ftps_port}'
         ])
-    return '\n'.join(report)
+    out = '\n'.join(report)
+    with open(os.path.join(env.build_dir, 'buildinfo.txt'), 'r') as file_in:
+        out += '\n' + file_in.read()
+    return out
 
 # TODO: remove this and repeat argument everywhere, pytest-repeat can be used to repeat tests
 def pytest_generate_tests(metafunc):
```

Needs #15257, and untested.

**Comment by vszakats** [comment]
Can confirm that after PR #15257, and this patch:
```diff
--- a/tests/http/conftest.py
+++ b/tests/http/conftest.py
@@ -53,7 +53,10 @@ def pytest_report_header(config):
         report.extend([
             f'  VsFTPD: {env.vsftpd_version()}, ftp:{env.ftp_port}, ftps:{env.ftps_port}'
         ])
-    return '\n'.join(report)
+    out = '\n'.join(report)
+    with open(os.path.join(env.build_dir, 'buildinfo.txt'), 'r') as file_in:
+        out += '\n' + file_in.read()
+    return out
 
 # TODO: remove this and repeat argument everywhere, pytest-repeat can be used to repeat tests
 def pytest_generate_tests(metafunc):

```
`buildinfo.txt` is correctly logged as part of the pytest custom info header:
```
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.3.3, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
Testing curl 8.11.0-DEV
  httpd: 2.4.52, http:42605 https:51967
  httpd-proxy: 2.4.52, http:46473 https:58963
  VsFTPD: unknown, ftp:36469, ftps:40551
# This is a generated file.  Do not edit.
buildinfo.configure.tool: configure
buildinfo.configure.args:  '--disable-dependency-tracking' '--enable-unity' '--enable-test-bundles' '--enable-warnings' '--enable-werror' 'LDFLAGS=-Wl,-rpath,/home/runner/bearssl/lib' '--with-bearssl=/home/runner/bearssl' '--enable-debug'
buildinfo.host: x86_64-pc-linux-gnu
buildinfo.host.cpu: x86_64
buildinfo.host.os: linux-gnu
buildinfo.target: x86_64-pc-linux-gnu
buildinfo.target.cpu: x86_64
buildinfo.target.os: linux-gnu
buildinfo.target.flags: UNIX GCC
buildinfo.compiler: GNU_C
buildinfo.compiler.version: 11
buildinfo.sysroot: 

rootdir: /home/runner/work/curl/curl/tests
collecting ... collected 640 items
```
https://github.com/curl/curl/actions/runs/11305837851/job/31445757150?pr=15273#step:47:67

Would this be a solution?

**Comment by vszakats** [comment]
Made a PR with the above → #15279.

**Comment by dfandrich** [comment]
This is now obsolete since the information is now available from our pytest harness directly: #15470

**Pull request closed without merging**
