### PR TITLE
TCP Fast Open support

### PR DESCRIPTION
**Pull request by ghedo**
This adds support for TFO (RFC7413) to libcurl and curl. Right now it only supports recent OS X versions (>= El Capitan), but I plan to add Linux support as well (it's a bit trickier though). Still need to write documentation as well.

### CODE REVIEW

**Comment by ghedo** [comment]
Added documentation.

**Comment by bagder** [comment]
Lovely!

But where does the `CONNECT_DATA_IDEMPOTENT` symbol come from?

**Comment by ghedo** [comment]
Looks like it's defined in `sys/socket.h`, no idea how it gets into `lib/uril.c` though.

**Comment by ghedo** [comment]
Hmm, the Travis test failure seems unrelated.

**Comment by ghedo** [comment]
Rebased and pushed. Looks like everything's ok now :)

**Comment by ghedo** [comment]
I guess maybe it's too early, but as far as I'm concerned this is ready to be merged. I'll open a different PR for the Linux support if this gets merged before I can push the patch.

**Comment by bagder** [comment]
I wouldn't mind having the Linux version in its own separate PR anyway so I don't think they need to be very tightly associated. I just feel that by waiting for the Linux version too before merging we can get them in for the same release (probably the next one then since we close the feature window in two days) and get a bigger momentum for users to actually try it out and get it used.

**Comment by bagder** [comment]
Hey @ghedo, do you think we're ripe to merge this?

**Comment by ghedo** [comment]
I rebased on master and finally added support for Linux, though it seems that newer Linux versions (on the client side) are not compatible with older versions (on the server side) so keep that in mind while testing.

**Comment by ghedo** [comment]
One thing missing from the Linux support is making this work with SSL, but I'll leave that for another time.

**Comment by ghedo** [comment]
@bagder ping?

**Comment by bagder** [comment]
Not forgotten, I promise! Just a busy week here in my end.

**Comment by bagder** [comment]
`error: lib/url.c: patch does not apply`

Can you please rebase this?

**Comment by ghedo** [comment]
Done.

**Comment by ghedo** [comment]
Rebased again (there was a conflict in `include/curl/curl.h`).

**Comment by bagder** [comment]
thanks a lot!

**Pull request closed without merging**
