### PR TITLE
Fix PKCS#12 loading not working under macOSX

### PR DESCRIPTION
**Pull request by ElMostafaIdrassi**
The method `CopyIdentityFromPKCS12File` is responsible for creating a `SecIdentityRef` from a PKCS#12
certificate file path and its password.

Under macOSX 10.7+, the old code was using `SecItemImport` with `importKeychain` set to `NULL`.
This leads to the identity in the PKCS#12 file not being imported to the keychain.
`SecItemImport` returns a `SecCertificateRef`.

Later on, in order to get a `SecIdentityRef` from the `SecCertificateRef`, the function
`SecIdentityCreateWithCertificate` is used. However, because the PKCS#12 private key
was not imported to the keychain, the function fails with `errSecItemNotFound`.
This behaviour is documented [here](https://developer.apple.com/documentation/security/1401160-secidentitycreatewithcertificate?language=objc).

Therefore, in order to avoid `SecIdentityCreateWithCertificate` failure, we need to import
the identity to the keychain : this commit fixes this by using the function `SecPKCS12Import`
instead of `SecItemImport` as it is done under iOS.

Signed-off-by: El Mostafa IDRASSI <el-mostafa.idrassi@prestalab.net>

### CODE REVIEW

**Comment by ElMostafaIdrassi** [comment]
I am providing some source code that shows the failure and how the commit fixes the issue.

[curl_p12.cpp](https://gist.github.com/ElMostafaIdrassi/053904908d2e63ab73c1486c199c69bb) 
Attemps to connect to github using a PKCS#12 file by calling curl. Make sure to replace `/PATH/TO/P12` with your own P12 Path and `P12PASSWORD` with your own P12 Password.
To be built as follows : 
`g++ -O2 -I/PATH/TO/CURL/include -L/PATH/TO/CURL/lib -lcurl curl_p12.cpp -o curl_p12`

[CopyIdentityFromPKCS12File_current_test.mm](https://gist.github.com/ElMostafaIdrassi/5416b2b8d6c81252e69f0e0f4f274a1a)
Attempts to create an indentity from a PKCS#12 file by calling `CopyIdentityFromPKCS12File` as it is from master branch in `lib/vtls/sectransp.c`
To be built as follows : 
`clang++ -O2 -framework Security -framework Foundation -framework CoreFoundation CopyIdentityFromPKCS12File_current_test.mm -o CopyIdentityFromPKCS12File_current_test`

[CopyIdentityFromPKCS12File_after_test.mm](https://gist.github.com/ElMostafaIdrassi/460cf14e6ad5cf4092bdac45a0e470c1)
Attempts to create an indentity from a PKCS#12 file by calling `CopyIdentityFromPKCS12File` as it is from my commit.
To be built as follows : 
`clang++ -O2 -framework Security -framework Foundation -framework CoreFoundation CopyIdentityFromPKCS12File_after_test.mm -o CopyIdentityFromPKCS12File_after_test`

**Comment by nickzman** [comment]
Not a failure. We intentionally don't use `SecPKCS12Import` because that function imports the certificate & key in the P12 file into the user's keychain, and some users had a problem with that. `SecItemImport` with `kSecItemTypeCertificate` does the same thing as `SecPKCS12Import`, but does not import the P12 file into the user's keychain. Because this PR reverts P12 handling back to the old behavior, I'm against merging this.

And I tested the ticket you filed, #4801, and could not reproduce the problem. The error "Can't find the certificate" occurs if you didn't type a path to the P12 item, so curl falls back on searching the Keychain for the item. If you type it as a path, then it will load the P12 item correctly. That means it must start with a ./ if it's inside the CWD.

**Comment by ElMostafaIdrassi** [comment]
@nickzman I am ALWAYS providing the full path (not a relative one), and the issue always occurs.

I provided [CopyIdentityFromPKCS12File_current_test.mm](https://gist.github.com/ElMostafaIdrassi/5416b2b8d6c81252e69f0e0f4f274a1a) for this reason : it reproduces what the current implementation of `CopyIdentityFromPKCS12File` function does, and it fails on my machine **while providing it with the full path of the P12**. 

Can you please build the sample and test on your end ? Because this is quite weird.

**Comment by nickzman** [comment]
Your sample code worked fine for me once I plugged in the absolute path to the P12 file and its password.

**Comment by ElMostafaIdrassi** [comment]
Okay, fair enough. 

But for the record, I am getting the error on two 10.15 machines and one 10.12 machine. 

Also, logically speaking, using `SecItemImport` with `kSecItemTypeCertificate` does not import the PKCS#12 content to the keychain, therefore the later call to `SecIdentityCreateWithCertificate` will always fail because the corresponging private key is not found in the keychain since, again, it was not imported by `SecItemImport` (see this [link](https://developer.apple.com/documentation/security/1401160-secidentitycreatewithcertificate?language=objc)). 

I am suspecting that the private key is still present in the keychain and therefore it is falsifying the tests, that's why I provided my binaries and the PKCS#12 I am using on my most recent comment [here](https://github.com/curl/curl/issues/4801#issuecomment-573043950). 

Anyway, if somebody can test using my binaries and my PKCS#12 certificate that would be cool.

**Pull request closed without merging**
