### PR TITLE
travis: remove the libssh run

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Review by emilengler — APPROVED** [review]
I suggest putting a re-adding of travis libssh into docs/TODO so we don't forget about it. Maybe it will work in the future again.

**Review by BigGuy573 — COMMENTED** [review]
Libssh run passed

**Review by BigGuy573 — COMMENTED** [review]
Libssh run bring back

**Comment by bagder** [comment]
See #7105

**Comment by bagder** [comment]
Nope, still fails!

**Pull request closed without merging**
