### PR TITLE
tests: add Schannel-specific tests or disable unsupported ones

### PR DESCRIPTION
**Pull request by mback2k**
Adds Schannel variants of SSLpinning tests that include the option
--ssl-revoke-best-effort to ignore certificate revocation check
failures which is required due to our custom test CA certificate.

Disable the original variants if the Schannel backend is enabled.

Also skip all IDN tests which are broken while using an msys shell.

This is a step to simplify test exclusions for Windows and MinGW.

### CODE REVIEW

**Comment by jay** [comment]
Works for me. Why did you add quotes to the tests field?

**Comment by mback2k** [comment]
Because a leading ! without " is an anchor in YAML.

**Review by jay — APPROVED** [review]

**Review by MarcelRaad — APPROVED** [review]

**Comment by mback2k** [comment]
Thanks guys. @bagder Do you think this can go in before the release or should I rather wait with this?

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
I think they can go in before the release.

**Comment by mback2k** [comment]
@bagder unfortunately it seems like I am no longer allowed to push to master, not sure what changed though:
image
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: You're not authorized to push to this branch. Visit https://docs.github.com/articles/about-protected-branches/ for more information.
To git@github.com:curl/curl.git
 ! [remote rejected] master -> master (protected branch hook declined)
```

**Comment by bagder** [comment]
Sorry, that was me experimenting with a feature that I shouldn't have. Hopefully fixed now.

**Pull request closed without merging**
