### PR TITLE
curl: add --pass-file and --proxy-pass-file options

### PR DESCRIPTION
**Pull request by vszakats**
These two options have the same purpose as existing `--pass` and `--proxy-pass` options, but instead of expecting the secret string on the command-line, they allow them to be passed via a filename. This filename can point to an on-disk file, to STDIN, etc. This makes it possible to pass key passphrases securely to curl, without them appearing in the `ps` listing, command history, etc.

The passphrase is read from the filename as-is, up to the first zero byte or CR, LF characters.

Examples:
```shell
echo 'secret' | curl --user my-user: sftp://example.net/ \
  --key id_ed25519 --pubkey id_ed25519.pub --pass-file /dev/stdin

echo 'secret' | curl https://example.net/ \
  --cert-type P12 --cert client.p12 --pass-file /dev/stdin
```

### CODE REVIEW

**Comment by dfandrich** [comment]
What the matter with using -K for this?

**Comment by vszakats** [comment]
`-K` can technically resolve this, but it's quite unpractical: First you need to convert the complete command-line into a `.curlrc`-style config file with different syntax and other suble differences, then you lose the ability to use the default `.curlrc` file (unless manually merging it into the custom config.)

These two options are lightweight and resolve this problem without friction for key passphrases. Just like `--netrc-file` does already for login credentials.

**Comment by vszakats** [comment]
After some experimenting it turns out `-K` is much more convenient than the help text suggests. First, it doesn't override `.curlrc` which wasn't readily obvious, second, it can be combined with the rest of the command-line in a flexible way, and can even be specified multiple times.

So the above examples translate to these:
```shell
echo '--pass "secret"' | curl --user my-user: sftp://example.net/ \
  --key id_ed25519 --pubkey id_ed25519.pub --config /dev/stdin

echo '--pass "secret"' | curl https://example.net/ \
  --cert-type P12 --cert client.p12 --config /dev/stdin
```

It is also useful to pass a secret as part of the URL.

I'm fine with the above, and thanks for pointing it out @dfandrich! (Though it's not easiest to discover feature, even by having read its manual entry.)

**Comment by dfandrich** [comment]
You don't need to convert the complete command-line into a file; you only need
to put the password in there. curl loads the default .curlrc file even with -K.
The options may each be lightweight, but once added, they'll be there forever,
along with the other 243 options.  For something that can already be done
another way, you haven't sold me yet.

**Comment by vszakats** [comment]
Thanks again for the `-K` tip, closing this in favour of it.

**Pull request closed without merging**
