### PR TITLE
CMake: Require Perl only when it's needed

### PR DESCRIPTION
**Pull request by dpull**

### CODE REVIEW

**Comment by snikulov** [comment]
@dpull 
Not sure that it is a good change. 
Perl required not only when ENABLE_MANUAL set to ON, but also for tests and checksrc command.

@Lekensteyn what do you think?

**Comment by bagder** [comment]
Very good point @snikulov. It is a much better solution to always check for perl and if absent, disable/don't run the parts of the build that depend on it.

**Comment by jzakrzewski** [comment]
@bagder Of course unless user specifically requested that part to be run - in which case a config error must occur.

**Comment by Lekensteyn** [comment]
@dpull What is the use case for making Perl optional? Normally you really want to run the tests to ensure that your curl is working. On Linux/macOS/BSD, perl is widely available. On Windows you can install something like StrawberryPerl.

As for the patch, the HTML docs do not depend on perl (it depends on roffit), so you can keep `add_subdirectory(docs)` and modify the CMakeLists.txt inside docs/. OTOH, if you do not have perl available you probably do not care about such docs either.

**Comment by snikulov** [comment]
@bagder Could you please close this PR? As we already discussed this one was wrong.

**Pull request closed without merging**
