### PR TITLE
travis: test building with trusty

### PR DESCRIPTION
**Pull request by MarcelRaad**
... and XCode 9 Beta. Trusty will become the default dist soon.

### CODE REVIEW

**Comment by MarcelRaad** [comment]
Everything is fine except the coverage build, which fails with some "Cannot open source file" I don't understand :-(

**Comment by frenche** [comment]
FYI, I had a similar failure on my PR (tests 600 601 failed in coverage build) with no apparent reason (i just squashed a commit), so I'm trying to restart it now by pushing a little diff.

**Comment by MarcelRaad** [comment]
@frenche Thanks! I had already tried with "restart job" in Travis, which made no difference. Trying rebasing and removing everything but the coverage change now to get a different commit.

**Comment by MarcelRaad** [comment]
@frenche Now I also get the 600 and 601 torture test failures in the coverage Travis job.

**Comment by frenche** [comment]
They seem flaky I'm afraid, the test ended up passing on my PR after resetting. Looks like ssh/scp related.

**Comment by MarcelRaad** [comment]
They're passing here too now and we're back to the original error. Looks like we just got switched to Trusty, so all coverage checks are failing now.

**Pull request closed without merging**
