### PR TITLE
cmake: soname for output .so file

### PR DESCRIPTION
**Pull request by jainvishal**
Originally the output .so file lacked the soname number under CMake.
It was available in makefile. The change collects the libcurl version
from libcurl.soname and then uses it for generated .so file.

### CODE REVIEW

**Comment by bagder** [comment]
Does this also make `make install` work correctly ?

Further, does it setup the symlinks for .so and .so.4 ? When I build curl with configure (and if I check my Linux distro installation) the libs look like this:
~~~
$ ls -l libcurl.so*
lrwxrwxrwx 1 daniel daniel     16 Sep  8 07:58 libcurl.so -> libcurl.so.4.7.0
lrwxrwxrwx 1 daniel daniel     16 Sep  8 07:58 libcurl.so.4 -> libcurl.so.4.7.0
-rwxr-xr-x 1 daniel daniel 632216 Sep  8 07:58 libcurl.so.4.7.0

**Comment by jzakrzewski** [comment]
Yeah, I've tried to do that once already. You haven't taken into account other platforms. This seems to be correct for linux but will diverge from what autotools produce on other supported platforms. See my failed try here: https://github.com/jzakrzewski/curl/commits/soname
Unfortunately, I haven't got time to get back to it to fix all the review issues...

**Comment by bagder** [comment]
@jzakrzewski do you think it would work as a first step if @jainvishal restricted this particular new logic to just Linux?

I'm thinking it could be worth taking it step by step and fixing this one platform at a time.

**Comment by jzakrzewski** [comment]
@bagder yes, absolutely. It has to be restricted to platforms where it's actually true. Would probably also be nice to be able to turn it off completely. Even if it's not a complete solution, it's progress.

**Comment by jainvishal** [comment]
Another change is needed in src/CMakefile.txt for RPATH for curl binary to find the right libcurl.so after installation otherwise LD_LIBRARY_PATH has to be used to run properly. I have locally fixed this by adding the RPATH within the binary. @bagder, @jzakrzewski, do you guys think it will impose any issues for the other users. See below dump from my local binary. If you guys like to see the code, I can push it.

```
readelf -d bin/curl

Dynamic section at offset 0x2f9b0 contains 30 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libcurl.so.4]
 0x0000000000000001 (NEEDED)             Shared library: [libpthread.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
```
So ldd shows

```
ldd bin/curl
        linux-vdso.so.1 (0x00007ffcdcf36000)
        libcurl.so.4 => /home/vishalj/release/test/bin/../lib/libcurl.so.4 (0x00007f2f78013000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f2f77fdb000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f2f77dea000)
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f2f77d58000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f2f77a83000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f2f77a67000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2f780d5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f2f77a5f000)
```
And two more questions:

1. cmake has the standard way for naming the shared objects which was the first question @bagder had asked. So is this acceptable?
2. Finally about restricting the change to only Linux. For now, I have restricted for the "NOT WIN32" platform. Since many people are using this software, I can look into limiting it exclusively for Linux for now and slowly add more platforms. Is that what you guys have in mind?

**Comment by bagder** [comment]
First, rpath would be a separate change and a separate discussion. In my personal opinion, curl itself should not set it unless asked for, but I would object to an option that explicit enables the use of it.

There are many ways for users to make sure the right lib is found at run-time, rpath is just one.

**Comment by jainvishal** [comment]
Hello @bagder, I compared output of make with cmake and found that make is also setting up RUNPATH and it is fully qualified. Please see below comparision. My cmake method can add the fully qualified RPATH or set the relative one using $ORIGIN. Latter ($ORIGIN) allows users to relocate compiled curl binary as long as libcurl remains in the relative path.

```
~/release > readelf -d make/bin/curl | grep RUNPATH
 0x000000000000001d (RUNPATH)            Library runpath: [/home/vishalj/release/make/lib]
 ~/release > readelf -d cmake/bin/curl | grep RUNPATH                                                                                                                              
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../lib]
```
This allows ldd to find libcurl as below:
```
~/release > ldd make/bin/curl | grep curl
        libcurl.so.4 => /home/vishalj/release/make/lib/libcurl.so.4 (0x00007fd09a59e000)
~/release > ldd cmake/bin/curl | grep curl
        libcurl.so.4 => /home/vishalj/release/cmake/bin/../lib/libcurl.so.4 (0x00007f3a8e8e9000)
```

**Comment by bagder** [comment]
1. this has nothing to do with the SONAME, why are we discussing this in this PR?
2. rpath != runpath. You mentioned rpath before and now runpath.

**Comment by jainvishal** [comment]
Point taken. So the change that I had submitted in PR, does it make sense?
Or you want to limit that to LINUX only. I have tested the change on Linux
and Solaris which I have access to.

**Comment by jzakrzewski** [comment]
If my old PR is any good, the "linux scheme" can be used for "AIX", "Linux", "GNU/kFreeBSD", "FreeBSD" (version 3.x and above), "Haiku", and "SunOS" (version 5 and 6).
I think restricting this to those platforms will be an improvement without hurting people that build on, for example, "NetBSD".

**Comment by bagder** [comment]
Now this flaw is mentioned specifically in the known bugs document: https://curl.haxx.se/docs/knownbugs.html#cmake_use_correct_SONAME_for_sh

Any progress?

**Comment by jainvishal** [comment]
I am sorry I lost track with day to day work. Will get back to this by end of October.

**Comment by bagder** [comment]
@jzakrzewski, do you think this is an improvement enough limited to just Linux like this? It introduces *yet another* platform difference, which is bad, but it could also be seen as a first step towards actually making this work properly in more places... and I'm not sure we can expect that we can fix "all platforms" in one go anyway.

**Pull request closed without merging**
