### PR TITLE
cmake: allow manual configuration for LDAP

### PR DESCRIPTION
**Pull request by vszakats**
Via these configuration values:
- `LDAP_LIBRARY`
- `LDAP_LBER_LIBRARY`
- `LDAP_INCLUDE_DIR`

Following the naming scheme used in `Find` modules.

Cherry-picked from #15157

---

- [ ] move [Open]LDAP detection into a Find module.

### CODE REVIEW

**Comment by dg0yt** [comment]
Consider an update of the Release Notes:

This change didn't *enable* manual configuration, but it *changed the name* of the configuration variables. 

Noticed in preparing the update of the vcpkg port updated which made use of the old variables.
Reminder: CMake cache variables are input variables. Patterns like
~~~cmake
    if(NOT DEFINED LDAP_LIBRARY)
      set(LDAP_LIBRARY "ldap" CACHE STRING "Name or full path to ldap library")
    endif()
~~~
don't provide added value unless you want to ensure plain CMake variables precedence over cache variables.

FTR vcpkg had
~~~cmake
if(NOT CURL_DISABLE_LDAP AND NOT WIN32)
    find_package(PkgConfig REQUIRED)
    pkg_check_modules(LDAP REQUIRED ldap)
    set(HAVE_LIBLDAP 1)
    set(CMAKE_LDAP_INCLUDE_DIR "${LDAP_INCLUDE_DIRS}")
    set(CMAKE_LDAP_LIB "${LDAP_LINK_LIBRARIES}" CACHE STRING "")
    pkg_check_modules(LBER REQUIRED lber)
    set(HAVE_LIBLBER 1)
    set(CMAKE_LBER_LIB "${LBER_LINK_LIBRARIES}" CACHE STRING ""
endif()
~~~
not as a patch but as `CMAKE_PROJECT_INCLUDE`.

**Comment by vszakats** [comment]
Thanks. That's unexpected. A Set(VAR "") does not actually set VAR to "".
Luckily this construct was seldom used in the code elsewhere.

I'd not have renamed knowing that, but a planned PR to convert to a Find
module also needs it for consistency: https://github.com/curl/curl/pull/15273/files?w=1
It would sync behaviour of these variables with all the others.

Updates this PR message/title and the entry in RELEASE-NOTES. I hope
it's an improvement: 1b4897f3c8e16413b96499f7e8dd55a3c9ace54a

> Consider an update of the Release Notes:
> 
> This change didn't _enable_ manual configuration, but it _changed the name_ of the configuration variables.
> 
> Noticed in preparing the update of the vcpkg port which made use of the old variables. Reminder: CMake cache variables are input variables. Patterns like
> 
> ```cmake
>     if(NOT DEFINED LDAP_LIBRARY)
>       set(LDAP_LIBRARY "ldap" CACHE STRING "Name or full path to ldap library")
>     endif()
> ```
> 
> don't provide added value unless you want to ensure plain CMake variables precedence over cache variables.
> 
> FTR vcpkg had
> 
> ```cmake
> if(NOT CURL_DISABLE_LDAP AND NOT WIN32)
>     find_package(PkgConfig REQUIRED)
>     pkg_check_modules(LDAP REQUIRED ldap)
>     set(HAVE_LIBLDAP 1)
>     set(CMAKE_LDAP_INCLUDE_DIR "${LDAP_INCLUDE_DIRS}")
>     set(CMAKE_LDAP_LIB "${LDAP_LINK_LIBRARIES}" CACHE STRING "")
>     pkg_check_modules(LBER REQUIRED lber)
>     set(HAVE_LIBLBER 1)
>     set(CMAKE_LBER_LIB "${LBER_LINK_LIBRARIES}" CACHE STRING "")
> endif()
> ```
> 
> not as a patch but as `CMAKE_PROJECT_INCLUDE`.

**Comment by dg0yt** [comment]
> A Set(VAR "") does not actually set VAR to "".

It is important to realize the difference between cache variables (global, cached, input) and normal variables (scoped), and what takes precedence.

A `set(VAR "")` *does* set the normal variable `VAR` in the current scope to `""`. That's even the easy part, and it is good. But...

An `unset(VAR)` or `set(VAR )` doesn't just unset the *normal* variable `VAR` in the current scope. It removes that idenifier's specialization from the current scope. Now `${VAR}` may expand to another definition (cache or parent scope)!

That's why `set(VAR )` is the wrong way to initialize variables. What is needed is `set(VAR "")`. (Unsetting is something which can be usetful at the end of a macro or find modules.) CURL examples which I consider wrong (noticed yesterday):
https://github.com/curl/curl/blob/380790b2449ec5337142fdcb8ac51365ffd86bae/CMakeLists.txt#L2087-L2090

**Comment by dg0yt** [comment]
> Updated this PR's message/title and the entry in RELEASE-NOTES. I hope
it's an improvement: https://github.com/curl/curl/commit/1b4897f3c8e16413b96499f7e8dd55a3c9ace54a

LGTM.

**Pull request closed without merging**
