### PR TITLE
GHA: on macOS remove $HOME/.curlrc

### PR DESCRIPTION
**Pull request by bagder**
Ref: https://github.com/actions/runner-images/pull/9586
Ref: #13284

### CODE REVIEW

**Comment by jay** [comment]
it's going to be reversed actions/runner-images#9626

**Comment by vszakats** [comment]
Would it be possible to ignore `.curlrc` for all tests?

The same can happen with any image anytime, and even more so on a local system with `.curlrc` customized for daily use.

**Comment by bagder** [comment]
> Would it be possible to ignore .curlrc for all tests?

This certainly shows a use case for exactly that. I imagine the only sensible way to do what is to use an environment variable as a signal.

Slightly related to my "debugging config file options" ideas: https://curl.se/mail/archive-2024-04/0000.html

**Comment by bagder** [comment]
Removing the file is harmless and fixes the issue short-term so I merge this now.

**Comment by vszakats** [comment]
> Slightly related to my "debugging config file options" ideas: https://curl.se/mail/archive-2024-04/0000.html

Is there any downside in introducing an env to override the default config filename?

E.g. `CURL_CONFIG_FILE=~/my-curlrc` or `CURLRC=~/my-curlrc`?

This could also have other uses, and such feature isn't unprecedented with other
tools. This also allows testing the feature itself by pointing it to a test config file.

We could limit it to debug builds, in case there is any concern for production use.

**Comment by dfandrich** [comment]
Regarding the possibility of ignoring .curlrc for all tests, we could just
unconditionally add -q to all curl commands before they're run in runtests.pl.
We're adding a lot of other arguments to each curl command already, so one more
isn't an issue. That is already overridden by a subsequent -K so tests that
need a config file will still work fine.

**Pull request closed without merging**
