### PR TITLE
tests: Temporarily disabled UTF-8 tests on Windows

### PR DESCRIPTION
**Pull request by captain-caveman2k**

### CODE REVIEW

**Comment by jay** [comment]
No explanation?

**Comment by bagder** [comment]
I also don't think "temporarily" needs to be there, as the commit is not "temporary" and you can prove that it actually was "temporarily" by doing a follow-up PR later that repairs the problem.

I agree with @jay that it should be mentioned that this disables the tests since they fail on Windows. And since the tests fail, can we be sure the code actually works as it should on Windows?

**Comment by captain-caveman2k** [comment]
Closing as early indications[1] show that PR #4999 fixes the issue properly.

[1] https://ci.appveyor.com/project/curlorg/curl/builds/31136821

**Comment by bagder** [comment]
#4999 is still a WIP, can we disable the tests first *now* to make the CI jobs go green again, and then work more long term to fix them proper?

**Comment by bagder** [comment]
Reopened. We **must** fix the windows builds asap!

**Comment by bagder** [comment]
@captain-caveman2k so can we land this now and get green windows builds again? There's a release in 48 hours, we cannot assume you'll get #4999 landed in time for that and we need green builds before  that happens.

**Comment by bagder** [comment]
Fixing the build and tests have to be top priority and I decided to merge asap.

**Pull request closed without merging**
