### PR TITLE
fix zlib library link error

### PR DESCRIPTION
**Pull request by wkwspirit**

### CODE REVIEW

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/issues/3133

**Comment by MarcelRaad** [comment]
This define should probably be added conditionally.

I think from the (semi-)official DLLs, only zlibwapi.dll is compiled with `ZLIB_WINAPI`. That would be this block:
https://github.com/curl/curl/blob/b801b453af6de75838c3298137628f05e94ffb48/winbuild/MakefileBuild.vc#L241
See also https://zlib.net/DLL_FAQ.txt.

From the self-built libraries, the nmake files don't define `ZLIB_WINAPI`:
https://github.com/madler/zlib/blob/v1.2.11/win32/Makefile.msc (static zlib.lib, dynamic zlib1.dll/zdll.lib)
but the Visual Studio projects do:
https://github.com/madler/zlib/blob/v1.2.11/contrib/vstudio/vc14/zlibvc.vcxproj#L211 (dynamic, zlibwapi.dll/zlibwapi.lib)
https://github.com/madler/zlib/blob/v1.2.11/contrib/vstudio/vc14/zlibstat.vcxproj#L174 (static, zlibstat.lib)

So it should probably also be added to the zlibstat.lib block.

**Comment by wkwspirit** [comment]
@bagder  Whether add ZLIB_WINAPI depends on how you compile zlib by yourself.If you compile zlib with ZLIB_WINAPI,you should add it in curl.I don't have a good solution.Maybe you can add it in README.

**Comment by bagder** [comment]
This issue has not gotten sufficient attention for a while and will therefore be closed.

If you still experience problems and can bring more information or data to this issue, we can certainly open it again and continue from here. (Or just open a new issue.)

Thanks!

**Pull request closed without merging**
