### PR TITLE
Typo fix : "yout" ➤ "your"

### PR DESCRIPTION
**Pull request by Levure**

### CODE REVIEW

**Comment by bagder** [comment]
If you have more typo fixes, please put them in the same PR...

**Review by bagder — APPROVED** [review]

**Comment by Levure** [comment]
Mea culpa. I thought the previous one was the only one. Sorry ! 😖

I have an endless meetings day in 16 minutes, so rest assured : there will be no other PRs. 😅

**Comment by bagder** [comment]
Haha, no worries, thanks!

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
