### PR TITLE
build: drop support for building with Watcom

### PR DESCRIPTION
**Pull request by bagder**
These files are not maintained, they seem to have no users, Watcom
compilers look like not having users nor releases anymore.

### CODE REVIEW

**Comment by jmalak** [comment]
Hi,

It looks like you are searching maintainer for Watcom compilers.
I able to stay Watcom support maintaner if necessary.

Please, note me if you are interested in my involvement.

Regards

Jiri

**Comment by bagder** [comment]
@jmalak have you built curl with Watcom compilers recently?

**Comment by jmalak** [comment]
No, I can prepare build environment and test it and fix if any problems.
I have appropriate Watcom compilers knowledge I am working on Open Watcom V2.0.

**Comment by bagder** [comment]
But why? I just removed these files because virtually *nobody* builds curl with Watcom so I just don't see the point in providing the makefiles anymore - when not updated in years they most likely also broken by now.

The fact that there doesn't seem to have been a Watcom release in ten years also helped me make the decision. It doesn't seem like a compiler to recommend to users. And the web site hasn't been updated in three years.

If you really want to use the Watcom compiler to build curl, shouldn't we rather make sure that you can build curl using the Watcom compilers with cmake or similar?

**Comment by jmalak** [comment]
If I understand properly then your build system is GNU-tools based, Am I right?

**Comment by bagder** [comment]
Yes, and various others as you should be able to see.

**Comment by jmalak** [comment]
You are right last Open Watcom 1.9 is realy old and no much changes.
Anyway Watcom toolchain interface is long term stable that if some makefiles exists then it will still works.
I understand that for Windows and Linux Wantcom is not interresting.
But for DOS, OS/2, old Netware can be still interresing.
I don't know what is your guide for future.

**Comment by bagder** [comment]
Future: I aim at supporting curl decades to come.

Build systems and platform support that don't get maintenance might be dropped at any point when they lag behind too much.

Build systems and platform support that are maintained/working remains.

**Comment by jmalak** [comment]
If build is CMake based then it is OK. I added cross-compile support for Open Watcom to CMake that from 3.18 it should be available.

**Comment by jmalak** [comment]
I will try to build it by CMake and GNU-tools to see how it is going with Open Watcom.

**Pull request closed without merging**
