### PR TITLE
writeout_json: use curl_off_t printf() option for the time output

### PR DESCRIPTION
**Pull request by bagder**
Follow-up to: 04c03416e68fd635a15

### CODE REVIEW

**Comment by jay** [comment]
Is this why I've seen random `"time_total":0.000000` in the [CI](https://ci.appveyor.com/project/curlorg/curl/builds/31536155/job/a8dapt4wey2ya18n#L2817) or is that something different

**Comment by bagder** [comment]
Yes, I hope that's the mistake that explains the time total test fails.

**Comment by bagder** [comment]
#5117 happened so the Azure msys builds are broken. I'll let this PR wait a bit until @mback2k has had some time to look at that.

**Comment by mback2k** [comment]
As you can see in the following two jobs the AppVeyor builds were also showing the issue:
- https://ci.appveyor.com/project/curlorg/curl/builds/31556660/job/xs1qp40x7wxrnfuc/tests
- https://ci.appveyor.com/project/curlorg/curl/builds/31556660/job/oq7iuj578j8g4b7m/tests

Since the issue did not appear in the AppVeyor builds for this PR, I think it is good to go. 👍

**Comment by jay** [comment]
While this is worthwhile to fix IMO the test is still going to be flaky because how can we be certain that it's going to be the same number every time? "time_total":0.000013 or maybe "time_total":0.000015 etc, depending on the speed of the CI.

**Comment by bagder** [comment]
Because the test only works for debug builds, and for those libcurl checks an environment variable for what to return and return the value in that environment variable. Not the actual time. So yes, we can be sure that the value will always be 13 if the test says so.

**Pull request closed without merging**
