### PR TITLE
Fix NTLMv2

### PR DESCRIPTION
**Pull request by huaraz**
Sorry I broke my branch :-(  I hope this is back to the latest

Markus

### CODE REVIEW

**Comment by huaraz** [comment]
Failure seems unrelated i.e. test 1556. 

TESTDONE: 478 tests out of 479 reported OK: 99%
TESTFAIL: These test cases failed: 1556

Markus

**Comment by MarcelRaad** [comment]
If there are no objections, I'll merge this for the next release soon.

**Comment by danielgustafsson** [comment]
I don't know NTLM so I can't comment on the specifics, but it seems to make sense on the face of it. +1 for merging in this window.

**Comment by MarcelRaad** [comment]
Thanks again!

**Pull request closed without merging**
