### PR TITLE
vauth: add digest authentication support with SSPI when stale=true

### LINKED ISSUE #928: Http digest authentication doesn't support 'stale=true'
### I did this

Build using cmake with default options under windows (so using windows SSPI). Loop on a GET request to reach a digest authenticated resource. Reuse easy handle between requests.
### I expected the following

Keep working after 401 ... "stale=true".  
First authentication works well but after that first nonce expire, curl doesn't handle any further authentication. It keep using the initial nonce. 
### curl/libcurl version

7.50.0
### operating system

Windows

I think I've found were the issue comes from and I should provide a pull request soon.

### PR DESCRIPTION
**Pull request by tarek112**
Bug: https://github.com/curl/curl/issues/928
Closes #928

### CODE REVIEW

**Comment by jay** [comment]
Unfortunately we can't do it like that. We need assurance that we have a separate directive, in other words that stale is actually a separate token and then compare case insensitive because stale=TRUE is also ok. We already have a function that can extract the tokens, [`Curl_auth_digest_get_pair`](https://github.com/curl/curl/blob/curl-7_50_0/lib/vauth/digest.c#L69-L70) in digest.c. Also we must free the existing `input_token` if we're replacing it.

Please try https://github.com/curl/curl/compare/master...jay:fix_sspi_stale_digest?expand=1 I'm not sure if it is entirely right, since I didn't bother to dig in to the windows functions. We pass the old digest to win api and for all I know it needs to be kept around after being passed. @captain-caveman2k could use a review

**Comment by tarek112** [comment]
Thank you for your comments, sorry for my ugly patch I'll to take more time
on any next submission.

**Comment by tarek112** [comment]
Btw your version is working fine

**Comment by jay** [comment]
Thanks for your report and contributing. As discussed we aren't going to use this PR. Further discussion should take place in #928

**Pull request closed without merging**
