### PR TITLE
windows: add .rc support to autotools builds

### PR DESCRIPTION
**Pull request by vszakats**
After this update autotools builds will compile and link `.rc` resources
to Windows executables. Bringing this feature on par with CMake
and Makefile.m32 builds. And also making it unnecessary to improvise
these steps manually, while monkey patching build files, e.g. [0].

You can customize the resource compiler via the `RC` envvar, and its
options via `RCFLAGS`.

This harmless warning may appear throughout the build, even though the
autotools manual documents [1] `RC` as a valid tag:
`libtool:   error: ignoring unknown tag RC`

[0] https://github.com/curl/curl-for-win/blob/535f19060d4b708f72e75dd849409ce50baa1b84/curl-autotools.sh#L376-L382
[1] https://www.gnu.org/software/libtool/manual/html_node/Tags.html

Closes #9521

### CODE REVIEW

**Comment by vszakats** [comment]
Pending issues:
- handling non-windres environments (= MSVC). If this is a valid use-case with curl autotools builds.
- what happens if `RC` isn't set?

**Comment by vszakats** [comment]
CI seems fine now, with two unrelated (flaky?) single-test failures @ AppVeyor, and `curl/check` (@ Zuul) failing, which does fail with mostly all commits these days.

**Comment by vszakats** [comment]
FWIW, tried removing `--tag=RC` to avoid the nonsense libtool warning `error: ignoring unknown tag RC`, which resulted in this:
```
libtool: compile: unable to infer tagged configuration
libtool:   error: specify a tag with '--tag'
```

¯\_(ツ)_/¯

**Comment by monnerat** [comment]
A side effect of this commit is new warning messages from `autoreconf -fi`:
```
configure.ac:125: warning: AC_PROG_CC was called before XC_CHECK_PROG_CC
m4/xc-cc-check.m4:86: XC_CHECK_PROG_CC is expanded from...
configure.ac:125: the top level
configure.ac:352: warning: LT_LANG was called before LT_INIT
/usr/share/aclocal/libtool.m4:61: LT_INIT is expanded from...
m4/xc-lt-iface.m4:442: XC_LIBTOOL is expanded from...
configure.ac:352: the top level
configure.ac:125: warning: AC_PROG_CC was called before XC_CHECK_PROG_CC
m4/xc-cc-check.m4:86: XC_CHECK_PROG_CC is expanded from...
configure.ac:125: the top level
configure.ac:352: warning: LT_LANG was called before LT_INIT
/usr/share/aclocal/libtool.m4:61: LT_INIT is expanded from...
m4/xc-lt-iface.m4:442: XC_LIBTOOL is expanded from...
configure.ac:352: the top level
configure.ac:125: warning: AC_PROG_CC was called before XC_CHECK_PROG_CC
m4/xc-cc-check.m4:86: XC_CHECK_PROG_CC is expanded from...
configure.ac:125: the top level
configure.ac:352: warning: LT_LANG was called before LT_INIT
aclocal.m4:83: LT_INIT is expanded from...
m4/xc-lt-iface.m4:442: XC_LIBTOOL is expanded from...
configure.ac:352: the top level
```
I tried locally to move the `LT_LANG([Windows Resource])` after the `XC_LIBTOOL` and it does suppress the warnings. However I am not sure it doesn't break your commit. Can you investigate? Thanks.

**Comment by vszakats** [comment]
@monnerat: Great find! This also fixes the odd warning noted here earlier, and in my tests the .rc files continue to compile and link fine.

Do you want to commit the fix?

**Comment by monnerat** [comment]
> Do you want to commit the fix?

No, I let you care of your baby !
> Strangely, I'm not getting those autoreconf -fi warnings on my system.

libtool or autotools version dependent ? OS dependent ? who knows !

**Comment by vszakats** [comment]
Sure, I've opened a [PR](https://github.com/curl/curl/pull/9582).

> libtool or autotools version dependent ? OS dependent ? who knows !

The perfect motto for autotools :) (to be fair: for build systems in general)

**Comment by monnerat** [comment]
Thanks for fix.

**Comment by lazka** [comment]
The latest release fails to build, could this be related? (missing make dependency?)

```
  /bin/sh ../libtool --tag=RC --mode=compile windres -I../../curl-7.86.0/include -DCURL_EMBED_MANIFEST  -i ../../curl-7.86.0/src/curl.rc -o curl.o
    CC       tool_hugehelp.o
    CC       ../lib/strtoofft.o
    CC       ../lib/timediff.o
  libtool: compile:  windres -I../../curl-7.86.0/include -DCURL_EMBED_MANIFEST -i ../../curl-7.86.0/src/curl.rc  -o .libs/curl.o
    CC       ../lib/nonblock.o
    CC       ../lib/warnless.o
    CC       ../lib/curl_multibyte.o
    CC       ../lib/version_win32.o
    CC       ../lib/dynbuf.o
    CCLD     curl.exe
  clang: error: no such file or directory: 'curl.o'
  make[2]: *** [Makefile:1011: curl.exe] Error 1
```

**Comment by lazka** [comment]
I've reduced it to `./configure --enable-shared --disable-static --with-schannel` on current master, if that helps

I can also create a new issue if wanted.

**Comment by bagder** [comment]
> I can also create a new issue if wanted.

Please do, I think we track it better that way

**Comment by vszakats** [comment]
@lazka: Thanks! A separate Issue would be helpful indeed. `--enable-shared --disable-static` is the exact combination where in curl-for-win I explicitly _skip_ building `curl.exe` (due to fatal `ltwrapper` issues post-link, and we also happen to not need this binary). This explains why this escaped my local tests. We also miss it from CI tests apparently. I could reproduce it now.

Do you have any suggestion for a fix?

**Comment by lazka** [comment]
I've filed an issue at https://github.com/curl/curl/issues/9803

**Pull request closed without merging**
