### PR TITLE
add SNI ServerName option (openssl)

### PR DESCRIPTION
**Pull request by dimatto**
Add CURLOPT_TLSSNI_NAME

Add curl --sniname

It implements openssl s_client --servername and --noservername

--noservername equivalent to --sniname ""

### CODE REVIEW

**Comment by jay** [comment]
I think this has come up before and there was some reason why we decided not to do it but I don't remember.

**Comment by bagder** [comment]
@dimatto, what's the use case for this that you can't already fulfill with existing options?

**Comment by dimatto** [comment]
@bagder clear text sni name will be censored(such as wikipedia), and the connection will be cut. Before esni fully deployed, I need --sniname to test which domain is censored, and use --sniname "" to remove sni in clienthello thus I can access those web pages, because you can't disable sni in popular browser such as chrome, so I use curl.

**Comment by bagder** [comment]
If you need this option to primarily disable SNI, shouldn't this then rather be just a boolean asking for that? We can already set the SNI to basically anything you want by using `--resolve` and I'm not convinced adding more ways is better. Can't you even "fix" your original problem by simply providing a made up SNI name with that?

**Comment by bagder** [comment]
BTW, test 1119 and 1139 fail.

**Comment by dimatto** [comment]
—resolve only map hostname to ip, but sni name still same as hostname, so a fake sni name means fake hostname, make web site inaccessible . sometimes, you need a fake sni and real hostname to visit web site, for example, zh.wikipedia.org in sni name blocked but en.wikipedia.org passed, so you need sni name en.wikipedia.org and hostname zh.wikipedia.org to access correct content, both name get *.wikipedia.org certificate, so verify passed. you can remove sni in clienthello, but it can block either zh.wikipedia.org or no sni , only pass en.wikipedia.org .

**Comment by bagder** [comment]
You mean host name as in `Host:` header?

> zh.wikipedia.org in sni name blocked but en.wikipedia.org passed, so you need sni name en.wikipedia.org and hostname zh.wikipedia.org to access correct content, both name get *.wikipedia.org certificate, so verify passed.

Doesn't this mean you rather want to connect to the en one with its SNI and then pass on the Host header to the zh one?
~~~shell
curl -H 'Host: zh.wikipedia.org' https://en.wikipedia.org
~~~

I'm proposing that curl can already do "fake" SNI in several different ways so I'm resisting yet another way unless it is really needed.

**Comment by dimatto** [comment]
@bagder you are right, it’s complicated than —sniname but it works. it's up to you adopt it or not, I’ll keep it for my personal version.😁

**Comment by jschauma** [comment]
I'd like to ask to revisit adding support for an option to explicitly specify the SNI.

Using "--resolve", I can change what IP address I talk to; using "-H", I can specify the HTTP Host header, but the TLS SNI sits in between here.  Suppose I have "cname.example.com" with CNAME "www.example.com", and I'd like to be able to connect to "cname.example.com" with a TLS SNI of "www.example.com" (for example, because the certificate in use there does not include "cname.example.com"), and set the HTTP Host header to "www.example.com".

"--resolve" doesn't help me here, as "cname.example.com" already resolves to the correct IP address via www.example.com; "-H www.example.com" sets the application layer Host header, but the SNI remains "cname.example.com".

```
curl --sni www.example.com -H www.example.com https://cname.example.com
```

would then allow me to do that.

**Comment by jay** [comment]
> `curl --sni www.example.com -H www.example.com https://cname.example.com`

`curl --connect-to www.example.com:443:cname.example.com:443 https://www.example.com`

https://curl.se/docs/manpage.html#--connect-to

**Comment by jschauma** [comment]
Ah, I see. Thanks. (Seems less intuitive to me, but gets the job done, I suppose. :-)

**Pull request closed without merging**
