### PR TITLE
unit1612: Fixed the compilation of the new unit test

### PR DESCRIPTION
**Pull request by captain-caveman2k**
Follow on from 3f74e5e6. Due to a typo in Makefile.inc unit1611 was used as test1612. Once corrected there were a few minor compilation issues to fix.

### CODE REVIEW

**Comment by jay** [comment]
`unit1612: Fix the compilation of the new unit test`

**Comment by bagder** [comment]
if we'll be very strict, I would also prefer if we dropped the initial uppercasing of the first letter and when possible rather spell out the actual fix rather than saying "fix". Perhaps:

`unit1612: compile the correct source file for the test`

**Comment by jay** [comment]
I think as a requirement it's probably too strict. Keywords like fix/add/remove or whatever may help communicate an overall effect (which is then fully spelled out in the commit message), and the initial uppercase style can be found in the history occasionally. I have some bias. Take for example
~~~
curl_getenv.3: Fix the memory handling description

- Tell the user to call curl_free() to free the pointer returned by
  curl_getenv().
~~~
It could be done with some limitation in the subject as
~~~
curl_getenv.3: tell the user to call curl_free() to free the pointer
~~~
I think the first one communicates better. I'm not sure if everyone shares that view.

**Comment by bagder** [comment]
I didn't mean it as a requirement. I just offered my take on what would make the commit message even better in my view.

**Pull request closed without merging**
