### PR TITLE
tests/server/tftpd.c: close upload file after transfer

### PR DESCRIPTION
**Pull request by mback2k**
Make sure uploaded file is not locked after transfer.

Bug: #6058

### CODE REVIEW

**Comment by jay** [comment]
This PR and commit message needs an explanation as to what's happening why you're doing it. It should already be covered in cleanup I don't know why it would need to be closed immediately like that.

**Comment by bagder** [comment]
I agree. If this fix helps, then the problem is that the regular cleanup of the file doesn't work - but *why* doesn't that work? It feels we're just painting over the problem instead of understanding it, which I think is fine once we've drained all other alternatives but I don't think we're there yet.

For example, we can try to extend `$defserverlogslocktimeout` in runtests.pl so it seems that's often what makes it kill the tftpd server instead of letting it exit by itself and maybe that is related? If so, it could be that the signal handling (is there such a thing?) on windows is the reason.

**Comment by mback2k** [comment]
> This PR and commit message needs an explanation as to what's happening why you're doing it. It should already be covered in cleanup I don't know why it would need to be closed immediately like that.

Cleanup is only done on tftpd server closing, but it stays running for multiple tests. In order to allow cleardir to delete logs between individual tests, it must be closed after each upload.

**Comment by mback2k** [comment]
> I agree. If this fix helps, then the problem is that the regular cleanup of the file doesn't work - but _why_ doesn't that work? It feels we're just painting over the problem instead of understanding it, which I think is fine once we've drained all other alternatives but I don't think we're there yet.

I don't understand why the following pre-existing code section is not being executed in time between individual tests, it seems like it is not reached in all test cases:
https://github.com/curl/curl/blob/24f909cebd8b79abf7b7368b649f5dace1a2449f/tests/server/tftpd.c#L824-L827

> For example, we can try to extend `$defserverlogslocktimeout` in runtests.pl as it seems that's often what makes it kill the tftpd server instead of letting it exit by itself and maybe that is related? If so, it could be that the signal handling (is there such a thing?) on windows is the reason.

The killing is only done as part of #6179 which is not yet merged, so I don't see how signal handling could be the issue here, especially between individual tests.

**Comment by bagder** [comment]
Closing it there is not inherently wrong, but it *is* already being closed after a single transfer here:

https://github.com/curl/curl/blob/24f909cebd8b79abf7b7368b649f5dace1a2449f/tests/server/tftpd.c#L824-L827

If your new fix helps, then it suggests that the above close is not enough which then begs the question: why?

**Comment by mback2k** [comment]
> Closing it there is not inherently wrong, but it _is_ already being closed after a single transfer here:
> 
> https://github.com/curl/curl/blob/24f909cebd8b79abf7b7368b649f5dace1a2449f/tests/server/tftpd.c#L824-L827
> 
> If your new fix helps, then it suggests that the above close is not enough which then begs the question: why?

That is what I wrote above, I don't understand _why_ the pre-existing code is not enough / not timely executed.

**Comment by mback2k** [comment]
@bagder would you be able to explain the background / expected flow of the server logs lock timeout/advisor functionality? I don't really get it's purpose and don't really understand at which points which state is expected.

**Comment by bagder** [comment]
I think that "log locking" concept in the test suite is broken. I believe it was originally introduced (10+ years ago) to fix the problem of the main script trying to check log files for correctness before the test servers deemed everything completely done.

The concept is broken because there's just one single "lock file" for runtests.pl and as long as it is present (during the timeout period) runtests.pl will just wait. The test servers are designed to create the file at the start of a test and then remove the file again when everything is complete, so that when the lock file is removed it signals that the test is "done".

runtests.pl only waits for 2 seconds for the lock file to vanish, and if it doesn't it kills the server as it considers that a sign of error. In the tftpd case, when I run test 285 stand-alone I always see runtests,pl kill the tftp server because it is too slow to remove the lock (tftpd.c hangs on the "normally times out and quits" swrite() which itself typically times out on 5 seconds).

Since many test cases invoke multiple test servers and yet there's only a single lock file, I suppose it'll be a race for the deletion.

**Comment by mback2k** [comment]
I guess the main issue is that closing the output file after the timeout/final ACK handling is too late. The log of tftpd server shows that it is actually receiving the kill signal and is closing:
```
19:36:03.796000 Wrote pid 73732 to .tftp_server.pid
19:36:03.796000 Wrote port 59062 to .tftp_server.port
19:36:03.812000 Running IPv4 version on port UDP/59062
19:36:04.656000 trying to get file: verifiedserver mode 1
19:36:04.656000 Are-we-friendly question received
19:36:04.656000 write
19:36:04.671000 read
19:36:04.671000 read: 4
19:36:04.671000 end of one transfer
19:36:04.781000 trying to get file: /test285.txt mode 2
19:36:04.781000 requested test number 285 part 0
19:36:04.781000 file opened and all is good
19:36:04.796000 write
19:36:04.796000 read
19:36:04.796000 read: 36
19:36:04.796000 reading final ack
19:36:09.812000 read final ack
19:36:09.828000 end of one transfer
19:36:14.203000 main_window_proc: 16 -> 15
19:36:14.218000 exit_signal_handler: 15
```

With some small modifications for additional log messages:
```
  rap->th_opcode = htons((unsigned short)opcode_ACK);  /* send the "final"
                                                          ack */
  rap->th_block = htons(recvblock);
  (void) swrite(peer, &ackbuf.storage[0], 4);
#if defined(HAVE_ALARM) && defined(SIGALRM)
  mysignal(SIGALRM, justtimeout);        /* just abort read on timeout */
  alarm(rexmtval);
#endif
  /* normally times out and quits */
  logmsg("reading final ack");
  n = sread(peer, &buf.storage[0], sizeof(buf.storage));
  logmsg("read final ack");
#ifdef HAVE_ALARM
  alarm(0);
#endif
  if(got_exit_signal)
    goto abort;
  if(n >= 4 &&                               /* if read some data */
     rdp->th_opcode == opcode_DATA &&        /* and got a data block */
     recvblock == rdp->th_block) {           /* then my last ack was lost */
  logmsg("sending final ack");
    (void) swrite(peer, &ackbuf.storage[0], 4);  /* resend final ack */
  logmsg("send final ack");
  }
abort:
  return;
```

**Comment by mback2k** [comment]
> untests.pl only waits for 2 seconds for the lock file to vanish, and if it doesn't it kills the server as it considers that a sign of error. In the tftpd case, when I run test 285 stand-alone I always see runtests,pl kill the tftp server because it is too slow to remove the lock (tftpd.c hangs on the "normally times out and quits" swrite() which itself typically times out on 5 seconds).

Thanks for the additional explanation @bagder. Do you think it would make sense to increase the timeout to 5 or 10 seconds to cover these longer running tests? The log I posted above clearly shows the 5 second delay due to handling the final ACK.

**Comment by mback2k** [comment]
BTW-- I still think this patch makes sense in order to close the uploaded file right away, but should I also remove the pre-existing closing referenced above that is currently happening after `do_tftp`?

**Comment by bagder** [comment]
Yeah, closing it at the earliest moment makes sense and I think you can then remove the later close to make the code clear.

**Comment by mback2k** [comment]
Travis CI is still pending, but GitHub macOS, Azure Ubuntu and FreeBSD builds completed successful. Other CI failures are not related. Merging this now.

**Pull request closed without merging**
