### PR TITLE
select: align poll emulation to return all relevant events

### PR DESCRIPTION
**Pull request by mback2k**
The poll emulation via select already consumes POLLRDNORM,
POLLWRNORM and POLLRDBAND as input events. Therefore it
should also return them as output events if signaled.

Also fix indentation in input event handling block.

Assisted-by: Daniel Stenberg

Replaces #5852

### CODE REVIEW

**Comment by mback2k** [comment]
> I don't know if this is right. For example you are always setting POLLRDNORM on POLLIN afterwards but afaics that flag was not necessarily set beforehand. My understanding of poll is it is only supposed to write bits that were passed in, with the exceptions noted below. 

I don't think this is something that I am changing with this PR. The current code also sets POLLIN if that itself was not set, but instead POLLRDNORM was set. So I am basically extending it to be also the case the other way around. Of course, I can extend this PR to make sure to check for *both* flags being requested before setting them. Please see how the code already handles both types of flags on the pre-poll code path which I just want to reflect in the post-poll code path as well:
https://github.com/curl/curl/blob/147eca8ba4ff78bf496cc1b59997ab4a24364b71/lib/select.c#L400-L405

> I think I agree with @bagder maybe it's best to take a if it ain't broke don't fix it approach here.

I somewhat agree on this, but I think the current code is partially broken, because it is not following the spec you referenced either. I will update this PR to reflect the spec even better.

**Comment by mback2k** [comment]
I updated the PR to be in line with the POSIX specification. This should also make sure there are no side effects, because we won't return the "new" flags `POLLRDNORM`, `POLLWRNORM` and `POLLRDBAND` if they were not requested by the caller beforehand.

**Comment by jay** [comment]
Fair enough, looks better now.

**Comment by mback2k** [comment]
@jay thank you very much! @bagder what do you think of this new variant?

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
