### PR TITLE
openssl: enable PKCS12 support for !BoringSSL

### PR DESCRIPTION
**Pull request by bagder**
Enable PKCS12 for all non-boringssl builds without relying on configure
or cmake checks.

Bug: https://curl.haxx.se/mail/lib-2017-10/0007.html
Reported-by: Christian Schmitz

### CODE REVIEW

**Comment by bagder** [comment]
No feedback on this take but I merged anyway as I believe this is the right way forward.

**Comment by gvanem** [comment]
What about the case with multiple *SSL backends*; both `-DUSE_OPENSSL` (meaning true OpenSSL) and 
`-DOPENSSL_IS_BORINGSSL`? 

Is it possible to detect that at compile time? No `#error don't do that!` for that in the code now AFAICS..

**Comment by jay** [comment]
> What about the case with multiple SSL backends; both -DUSE_OPENSSL (meaning true OpenSSL) and
> -DOPENSSL_IS_BORINGSSL?

I don't think it's possible to use both of those at the same time

**Comment by gvanem** [comment]
I know; I got and error for a missing `<pkcs12.h>` in BoringSSL. Hence the question.

**Comment by jay** [comment]
I'm lost. If you are building with BoringSSL then the pkcs stuff should not be included. In other words `-DUSE_OPENSSL -DOPENSSL_IS_BORINGSSL` then no pkcs

**Pull request closed without merging**
