### PR TITLE
add support for CMAKE_OSX_ARCHITECTURES when detecting SIZEOF variables

### PR DESCRIPTION
**Pull request by JonasVautherin**
When cross-compiling for iOS, toolchains set [`CMAKE_OSX_ARCHITECTURES`](https://cmake.org/cmake/help/v3.0/module/CheckTypeSize.html). As per the doc:

> The variable “${VARIABLE}” may be “0” when CMAKE_OSX_ARCHITECTURES has multiple architectures for building OS X universal binaries. This indicates that the type size varies across architectures.

In this case, e.g. ${SIZEOF_LONG} gets set to "0", and therefore `#cmakedefine SIZEOF_LONG ${SIZEOF_LONG}` becomes "/* #undef SIZEOF_LONG */" in [`curl_config.h`](https://github.com/curl/curl/blob/master/lib/curl_config.h.cmake#L901), resulting in a broken build.

However, and still described in the docs, when ${SIZEOF_LONG} is "0", CMake also defines other values, including ${SIZEOF_LONG_CODE}, which gives, e.g. for `CMAKE_OSX_ARCHITECTURES=armv7;armv7s;arm64`:

    #if defined(__ARM_ARCH_7A__)
    # define SIZEOF_LONG 4
    #elif defined(__ARM_ARCH_7S__)
    # define SIZEOF_LONG 4
    #elif defined(__aarch64__)
    # define SIZEOF_LONG 8
    #else
    # error SIZEOF_LONG unknown
    #endif

Instead of using `#cmakedefine` and `${SIZEOF_LONG}`, I believe it always works to use `${SIZEOF_LONG_CODE}` directly, while enabling support for multiple architectures in `CMAKE_OSX_ARCHITECTURES`.

It is working for me on Linux, and on macos when cross-compiling for iOS (`armv7;armv7s;arm64`).

### CODE REVIEW

**Comment by JonasVautherin** [comment]
I don't get how my changes could reduce the coverage by 8%. And the other error seems to be a timeout in the CI.

**Comment by bagder** [comment]
@JonasVautherin no, you're right. The coveralls service acts up like this every now and then, so in this particular case we'll just ignore it. And the cirrus-ci freebsd test sometimes times out and that's another one to ignore...

**Comment by snikulov** [comment]
@JonasVautherin pardon me... But why `#cmakedefine` directive was removed?
Was it some syntax change in CMake?
Could you please explain how it works now according to [documentation](https://cmake.org/cmake/help/latest/command/configure_file.html)?

**Comment by snikulov** [comment]
@JonasVautherin After some investigation, I've discovered your point.
While it seems to be working, it's not clear for understanding.
No any direct references from configure_file to CheckTypeSize provided.

Perhaps it's better to add some platform logic in CMakeLists.txt with `unset` or in curl_config.h.cmake with `#ifdef` for clarity? What do you think?

**Comment by jzakrzewski** [comment]
@snikulov surprised me also but [CheckTypeSize documentation](https://cmake.org/cmake/help/latest/module/CheckTypeSize.html) makes it clear now. Nevertheless, it feels pretty disconnected but I don't know if there's a way to make it easier to read.

**Comment by snikulov** [comment]
@jzakrzewski perhaps @bradking could shed some light on this.
@bradking Is it correct to use `${SIZEOF_LONG_CODE}` instead of `#cmakedefine`?

**Comment by jzakrzewski** [comment]
Judging from the documentation I''d say it is correct. But there's this "Where the heck is that coming from?" moment. I guess for an expert it may be obvious. I haven't written (yet) enough CMake to know it from the first glance.
Maybe a reminder-comment somewhere would suffice? Because this seems quite elegant once you know why it works.

**Comment by bagder** [comment]
Maybe an added comment with the link to the documentation for it is enough?

**Comment by JonasVautherin** [comment]
I updated with a description before the `SIZEOF_` section, I hope it makes it clearer. There is again a timeout in the CI, and I don't get why appveyor fails.

**Comment by jzakrzewski** [comment]
For me personally that'd be enough.

**Comment by snikulov** [comment]
LGTM.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
