### PR TITLE
Travis build optimization (longest job first)

### PR DESCRIPTION
**Pull request by duelle**
In order to reduce the overall build duration, I rearranged the order of the jobs based on data from the previous successful build. This means that the jobs are ordered from longest to shortest duration. This PR is intended as an initial validation of the effectiveness of this approach in the curl-specific TravisCI environment.
Due to current technical limitations, the YAML format deviates from the original (e.g., in terms of comments, anchors, references).  The `.travis.yml` will need some rework in terms of formatting before it can be merged. Therefor, I set it as a draft pull request.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks @duelle, this is pretty clever. I like it!

**Comment by bagder** [comment]
Any news on this @duelle? This is still marked 'draft' but seems like a clever thing to merge, for this and other CI configs too.

**Comment by duelle** [comment]
My initial intention was to prove the advantage over the original version by comparing the performance of the builds. But first, due to the huge backlog at TravisCI and second, due to the recent changes of TravisCI's plans, it wasn't as easy as I thought.
Of course, if you think this is worth a try to merge, I am definitely open for that!
The only thing that got lost due to the automatic conversion are the comments, which I could re-add manually to make this not having a negative impact documentation-wise.
What do you think @bagder?

**Comment by duelle** [comment]
I fixed the `.travis.yml` by replacing the IDs with the original variable names again and re-added the comments that had been removed during the automated conversion process. 
As one can see in the TravisCI build [1], the ordering seems to be successful, apart from minor discrepancies of a few minutes in starting up the instances.
Unfortunately, one of the builds was canceled out by Travis's maximum build length constraint of 50 minutes.

@bagder: I removed the WIP flag from the pull request to allow merging now that I fixed the remaining 'issues'.

[1] https://travis-ci.org/github/curl/curl/builds/760568632

**Comment by bagder** [comment]
We've given up on Travis. This same approach can be taken to other services. Let's see how we go from now and see where this might make sense going forward.

**Pull request closed without merging**
