### PR TITLE
polarssl: fix multissl breakage

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: @dfandrich 
Bug: https://curl.haxx.se/mail/lib-2017-08/0121.html

cc @dscho

### CODE REVIEW

**Comment by gvanem** [comment]
Shouldn't libcurl put emphasis on the new names?
 * polarssl -> mbedTLS
 * CyaSSL -> WolfSSL

**Comment by bagder** [comment]
For polarssl and mbedTLS, we have them both supported separately.

For CyaSSL -> WolfSSL, do you mean that the enum should rather say wolfssl and the alias should be cyassl? I would probably agree that `lib/vtls/cyassl.c` should rather say "wolfssl" than "cyassl" for the name but that's not what this change is about...

**Comment by gvanem** [comment]
> we have them both supported separately.

I see that (in `configure.ac` etc.). But I see no `Cmake/FindPolarSSL.cmake`. Maybe that's on the *to-do* list?

> .. enum should rather say wolfssl and the alias should be cyassl? 

Yes.

**Comment by bagder** [comment]
> But I see no Cmake/FindPolarSSL.cmake. Maybe that's on the to-do list?

As PolarSSL is sort of end of life, I don't think there's a lot of attention to that. The cmake build also lacks support for several other of the SSL backends the configure build supports. In fact, multi-ssl itself is not even enabled for the cmake build (yet)...

**Comment by bagder** [comment]
filed #1844 separately

**Comment by dscho** [comment]
Uh oh. I guess I should have tried harder to get PolarSSL to compile here so that I could have compile-tested... Sorry for that breakage! Changes look good...

**Comment by bagder** [comment]
Thanks all!

**Pull request closed without merging**
