### PR TITLE
Make default EXPECT_100_THRESHOLD 1Mb

### PR DESCRIPTION
**Pull request by rodwiddowson**
Back in July 2017 there was conversation [1] about disabling
"Expect: 100-continue" by default.

The upshot was [2] which has multiple suggestions with the least impact
one being to update the threashold from 1k to 1M.

This change does just that.  I'm punting on the other suggestions since
I don't feel I have enough background at this time to do more than this.

[1] https://curl.haxx.se/mail/lib-2017-07/0013.html
[2] https://curl.haxx.se/mail/lib-2017-07/0021.html

### CODE REVIEW

**Comment by bagder** [comment]
I'm in favor of raising the limit. I think you also may need to adjust a test or two though.

**Comment by rodwiddowson** [comment]
Tnx I'll see what tests break.. (

**Comment by rodwiddowson** [comment]
This is what to worry about ?
> These test cases failed: 39 304 552 651 1070 1129 1133 

If so I'll take a look.  Some of them look like simple ones to fix.

**Comment by bagder** [comment]
Yes, those are probably the tests that previously issued that header and no longer do due to the raised limit.

**Comment by jay** [comment]
Are there any metrics on this, is 1M an arbitrary point? @dfandrich seems to be assuming broadband networks. How does Firefox behave, does it have a limit?

**Comment by rodwiddowson** [comment]
@jay The 1Mb is arbitrary inasmuch as it's what Daniel suggested.  I haven't done any more due diligence on what should happen since its out of my comfort zone.  I am aiming to get a clewean integration and leave the discussion to those that know.

I only fell into it because of a customer who complained that a one of their customer's was saying "Our webserver doesn't support `Expect-continue 100`"  which feels weird anyway.

**Comment by bagder** [comment]
Very few HTTP clients even use this header by default due to the common problems. I don't think any of the popular browsers use it. This is the single header that is frequently causing grief and timeouts to users all over and have kept doing so over many years. Raising the limit reduces the amount of people who will suffer from slow operations due to curl unnecessarily waiting a full second. This, because very few servers actually respond correctly and swiftly to tell curl to go on. It's even very common for curl to timeout after than second and then get a 40x response back *anyway*, just delayed.

1MB is an entirely arbitrary limit, but so is the existing one. The reasoning to up the limit would be that very few use cases would have a problem with it, and the real penalty for possibly sending data more than once starts to show when the bandwidth or time loss is notable. Perhaps that is at 1MB. Users can still also force the header to be used no matter what limit, and it remains used for the cases where the amount of upload data is unknown.

**Comment by rodwiddowson** [comment]
Latest push fails in test 564 (an FTP test) for exacrly one Windows build

`Environment: PRJ_GEN=Visual Studio 12 2013 Win64, PRJ_CFG=Debug, OPENSSL=OFF, WINSSL=OFF, HTTP_ONLY=OFF, TESTING=ON, SHARED=OFF`

I have difficulty believing that this could break an FTP test.  Also if you look at the log AFAICS the `check-expected` isn't what is in the test file, whilst the `check-expected` is.

**Comment by rodwiddowson** [comment]
@bagder , you said
> Users can still also force the header to be used no matter what limit
We looked for an API to control that in libcurl but couldn't.  Did we miss it?  Thanks /Rod

**Comment by bagder** [comment]
@rodwiddowson, by setting `Expect: 100-continue` as a custom header curl will detect that and act accordingly.

**Comment by dfandrich** [comment]
@jay I pulled the 1MB figure out of the air as a gut feeling of something
reasonable. But, the intent of this header is to avoid wasting time sending
data that's just going to thrown out, so we can calculate a reasonable figure.
Google tells me the average worldwide Internet speed these days is 9.1 Mbps and
curl has a 1 sec timeout on this header. At 9 Mbps, you can transfer about
1.2 MB MB of application data in one second, so it doesn't make sense to wait 1
sec. for less than this amount. So, my gut was pretty accurate!

**Comment by bagder** [comment]
Still interested in pursuing this PR? Those test failures on macOS seems to be real.

**Comment by bagder** [comment]
Worked stopped and no response for many months.

**Pull request closed without merging**
