### PR TITLE
Makefile.mk: drop in favour of autotools and cmake (MS-DOS, AmigaOS3)

### LINKED ISSUE #15537: Cross Compiling for Amiga OS - Error implicit declaration of function 'ioctl'
### I did this

using GCC = m68k-amigaos-gcc version 13.2.0
AmigaSSL v5 (Latest Oct 24)
Zlib 1.3.1 (Cross Compiled with soft-float by me)
In hopes of - Building curl 8.11.1-DEV (m68k-unknown-amigaos) OpenSSL/3.4.0 zlib/1.3.1

The configure command was as follows (this was based on a older forum post and added to make it compile)
`./buildconf && PKG_CONFIG=true ./configure --host=m68k-amigaos --build=$(uname -m)-pc-linux-gnu CC=m68k-amigaos-gcc AR=m68k-amigaos-ar --disable-shared --disable-ipv6 --prefix=/opt/amiga13 --disable-netrc --without-libpsl --with-amissl --disable-threaded-resolver CFLAGS="-fomit-frame-pointer -msoft-float -Wno-system-headers -mcrt=clib2" CPPFLAGS="-D__AMIGA__ -DHAVE_IOCTLSOCKET_CAMEL_FIONBIO=1" LIBS="-lnet -lm -lc -lz -lunix -latomic" `

When trying to cross compile anything above 8.4.0 the cross compile fails with

` CC       libcurl_la-nonblock.lo
nonblock.c: In function 'curlx_nonblock':
nonblock.c:70:10: error: implicit declaration of function 'ioctl' [-Werror=implicit-function-declaration]
   70 |   return ioctl(sockfd, FIONBIO, &flags);
      |          ^~~~~`

this seems to coming from #elif defined(HAVE_IOCTL_FIONBIO) which has comments older unix - there is an Amiga elif further down - If I swap the order in nonblock.c as below - the compile completes (it doesn't work on the amiga correctly however)

```
#elif defined(HAVE_IOCTLSOCKET_CAMEL_FIONBIO) 
    /* Amiga */
    long flags = nonblock ? 1L : 0L;
    return IoctlSocket(sockfd, FIONBIO, (char*)&flags); 

#elif defined(HAVE_IOCTL_FIONBIO)

  /* older Unix versions */
  int flags = nonblock ? 1 : 0;
  return ioctl(sockfd, FIONBIO, &flags);
```

On the Amiga - typing any CURL URL gives the error message

> curl: (3) URL using bad/illegal format or missing URL

I'm not a C programmer or an expert at compiling with GCC  - just thought I'll give this all a try to see if I could make the latest CURL work on the AmigaOS (test system is latest classic AmigaOS 3.2.2.1)

so not sure if there are two bugs here - or my configuration statement is causing this issue.

### I expected the following

Compilation works first try and the Amiga program runs and works as intended.

### curl/libcurl version

curl 8.11.1-DEV (m68k-unknown-amigaos) libcurl/8.11.1-DEV OpenSSL/3.4.0 zlib/1.3.1

### operating system

Linux 5.15.153.1-microsoft-standard-WSL2 #1 SMP Fri Mar 29 23:14:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
Amiga OS 3.2.2.1

### PR DESCRIPTION
**Pull request by vszakats**
`Makefile.mk` supported MS-DOS and Amiga, but `./configure` also
supported them in a better tested and more flexible way.

This patch also adds CMake support for MS-DOS/DJGPP and Amiga OS 3.

`Makefile.mk` was not maintained. Delete it in favour of first-tier
build methods.

Also include some non-MS-DOS/AmigaOS-specific tidy-up, see details at
the end of this message.

Details:

- fix/silence all MS-DOS/DJGPP build warnings and issues.
- add MS-DOS support to cmake.
  - default to `ENABLE_THREADED_RESOLVER=OFF` for MS-DOS.
  - add support for `WATT_ROOT`.
  - use static libcurl with MS-DOS.
  - fixup default CMake suffixes/prefixes for DJGPP.
  - disable hidden symbols for MS-DOS. Not supported on MS-DOS.
  - opt-in MS-DOS into `USE_UNIX_SOCKETS`.
- improve MS-DOS support in autotools.
  - default to `--disable-threaded-resolver` for MS-DOS.
- make sure to use `close_s()` (from Watt-32) with autotools and cmake.
  `Makefile.mk` used it before this patch.
- GHA: add DJGPP cmake (~30s) and autotools (~60s) build jobs.
  Also build tests and examples with cmake.
- improve AmigaOS support in autotools:
  - configure: detect `CloseSocket()` when it's a macro.
  - configure: fix `IoctlSocket` detection on AmigaOS.
  - curl-amissl.m4: pass AmiSSL libs to tests/servers.
- add AmigaOS3 support to cmake:
  - cmake: fix `HAVE_IOCTLSOCKET_CAMEL` and
    `HAVE_IOCTLSOCKET_CAMEL_FIONBIO` detections.
  - set necessary system libs.
  - add AmiSSL support.
  - inet_ntop, inet_pton: fix using it for AmigaOS. cmake detects them,
    and they did not compile with AmigaOS.
  - cmake: better sync `gethostname` detection with autotools.
    Fixes detection for AmigaOS, where `gethostname` is a macro.
  - cmake: fix `sys/utime.h` detection on AmigaOS.
  - cmake: force-disable `getaddrinfo` for AmigaOS.
  - cmake: tweak threading and static/shared default for AmigaOS.
  - cmake: rely on manual variable `AMIGA` to enable the platform.
- GHA: add AmigaOS cmake and autotools (~45s) jobs.
  Also build tests and examples with cmake.
- INSTALL: update MS-DOS and AmigaOS build instructions.
- amigaos: fix `-Wpointer-sign` and
  `zero or negative size array '_args'` in `Printf()`.
- amigaos: fix `-Wpointer-sign`
- amigaos: fix `-Wredundant-decls` `errno` and `h_errno`.
- amigaos: brute-force silence `lseek()` size warnings.
- amigaos: server/resolve: silence `-Wdiscarded-qualifiers`.
- amigaos: server/resolve: fix `-Wpointer-sign`.
- amigaos: fix `CURL_SA_FAMILY_T` type.
- nonblock: prefer `HAVE_IOCTLSOCKET_CAMEL_FIONBIO` for AmigaOS.
  `ioctl` is also detected, but fails when used. Make the above override
  it for a successful build.
  Authored-by: Darren Banfi
  Fixes #15537
  Closes #15603
- tftpd: prefer `HAVE_IOCTLSOCKET_CAMEL_FIONBIO` for AmigaOS.
- tftpd: tidy-up conditional code.
- curl: set stack size to 16384 for AmigaOS3/4
  Overriding the default 4096.
  Suggested-by: Darren Banfi
  Ref: https://github.com/curl/curl/pull/15543#issuecomment-2498783123
  Ref: https://wiki.amigaos.net/wiki/Controlling_Application_Stack
- functypes.h: fix `SEND_QUAL_ARG2` for AmigaOS.
- tftp: add missing cast in sendto() call for AmigaOS.
- getinfo: fix warning with AmigaOS.
- tool_operate: silence warning with AmigaOS
- amigaos: fix building libtests due to missing `RLIMIT_NOFILE`.
- curl_gethostname: silence warning for AmigaOS.
- ftp: silence `-Wtype-limits` for AmigaOS.
- libtest: fix timeval initialization for AmigaOS.
- examples: fix `timeval` initialization for AmigaOS.
- examples: silence warning for AmigaOS.
- configure: fix IPv6 detection for cross-builds.
- netrc: fix to build with AmigaOS cleanly.
- buildinfo: detect and add `DOS` tag for MS-DOS builds.
- buildinfo: add `AMIGA` to buildinfo.txt in auttools.
- build: move `USE_WATT32` macro definition to cmake/configure.

Non-MS-DOS/AmigeOS-specific tidy-ups:

- configure: sync `sa_family_t` detection with cmake.
- configure: sync `ADDRESS_FAMILY` detection signals with cmake.
- doh: use `CURL_SA_FAMILY_T`.
- lib: drop mingw-specific `CURL_SA_FAMILY_T` workaround.
- cmake: extend instead of override check-specific
  configurations/requirements.
  This allows to honor global requirements added earlier.
  Necessary for AmigaOS for example.
- cmake: omit warning on disabled IPv6 for MS-DOS and AmigaOS.
  No IPv6 support on these platforms. Also sync with autotools.
- lib1960: use libcurl `inet_pton()` wrapper.
- cmake: detect LibreSSL (to match autotools).
- cmake: say the specific OpenSSL flavour detected.
- hostip: add missing `HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID` guard.
- lib: simplify classic mac feature guards.

Follow-up to a8861b6ccdd7ca35b6115588a578e36d765c9e38 #9764

---

- [x] split into multiple PRs or commits? [MERGE AS-IS]

w/o whitespace: https://github.com/curl/curl/pull/15543/files?w=1

### CODE REVIEW

**Comment by vszakats** [comment]
Successfully cross-built for MS-DOS using this command:
```
AR=~/path/to/djgpp/bin/i586-pc-msdosdjgpp-ar \
RANLIB=~/path/to/djgpp/bin/i586-pc-msdosdjgpp-ranlib \
CC=~/path/to/djgpp/bin/i586-pc-msdosdjgpp-gcc \
./configure --disable-debug \
  --build=<host-triplet> \
  --host=i586-pc-msdosdjgpp \
  --without-libpsl \
  --without-ssl \
  --disable-threaded-resolver \
  --enable-shared=no \
  --enable-static=yes \
  --disable-docs \
  WATT_ROOT=/path/to/djgpp/net/watt \
  LDFLAGS=-L/path/to/djgpp/net/watt/lib
```

**Comment by vszakats** [comment]
I'm wondering if it'd make sense to delete `lib/config-dos.h` and `lib/config-amigaos.h` with this? They are no longer used within the repo. Or maybe convert them to configure caches?

**Comment by bagder** [comment]
> I'm wondering if it'd make sense to delete `lib/config-dos.h` and `lib/config-amigaos.h` with this? They are no longer used within the repo. Or maybe convert them to configure caches?
> 
> edit: converting them to a cmake or autotools cache is certainly possible, but the maintenance cost is high.

I think trying to do them as caches is just overkill and not something we do for any other platforms either. configure/cmake should be able to generate the correct setup on their own. IMHO, those two "hard coded" config files should be removed if we think configure/cmake can do the job.

**Comment by vszakats** [comment]
Arrived to the same conclusion, it's overkill.

With MS-DOS + CMake the toolchain env is detected fine now (also matching previous manual values). Dependency detection is probably broken due to CMake insisting on the `.lib` suffix, but feeding the libs manually via `-DNAME_LIBRARY=/path/to/libname.a` should work it around.

**Comment by vszakats** [comment]
AmigaOS build in CI:
https://github.com/curl/curl/actions/runs/11896650529/job/33149038413

**Comment by boingball** [comment]
This compiles very cleanly now, nice work - testing with WinUAE emulator and curl works flawlessly.
on the real amiga, I think there's a bug with Roadshows bsdsocket.library - causing curl to crash (older versions of curl are also doing the same)

**Comment by vszakats** [comment]
@boingball Thanks for testing! I'm happy it works!

When running the result in vAmiga, it's saying `"usergroup.library" could not be opened`. When copying that in (from `AmiTCP-bin-30b2.lha`), this changes to `Couldn't open bsdsocket.library v4!`. I'm a noob to this.

I'll try making CMake work.

**Comment by boingball** [comment]
I'm definitely no expert at C - ChatGPT C has been helping me this week. So looking at that I think AmiTCP makes a memory resident bsdsockets.library when loaded on the Amiga. I'm wondering if curl would work if we compile against Roadshow 1.8 SDK which actually includes a bsdsockets.library on disk. (Which Roadshow TCP 1.15 includes) 

I wonder if the AmiTCP older lib is causing conflicts with the newer Roadshow TCP lib.

My 3 physical Amigas have Roadshow installed  

SDK for Roadshow 1.8 available from here :
https://www.amigafuture.de/app.php/dlext/details?df_id=3658

Roadshow is the modern TCP stack currently.

**Comment by vszakats** [comment]
> I'm definitely no expert at C - ChatGPT C has been helping me this week. So looking at that I think AmiTCP makes a memory resident bsdsockets.library when loaded on the Amiga. I'm wondering if curl would work if we compile against Roadshow 1.8 SDK which actually includes a bsdsockets.library on disk. (Which Roadshow TCP 1.15 includes)
> 
> I wonder if the AmiTCP older lib is causing conflicts with the newer Roadshow TCP lib.
> 
> My 3 physical Amigas have Roadshow installed
> 
> SDK for Roadshow 1.8 available from here : https://www.amigafuture.de/app.php/dlext/details?df_id=3658

Thanks. Turning these sources into binaries would need an Amiga pro I suppose :)

Interestingly the `Makefile.mk` 2 years ago was able (in vAmiga) to show curl's version string (then crash): #9764

The toolchain is unusual in that is has several versions (layers ?) of headers, APIs and libs, making grep not so useful. There are knobs altering the selection, some used here and there in curl detection and source. Interfaces are sometimes macros, which make autotools and cmake detections behave differently.

The CMake build works now, with minor differences compared to autotools.

**Comment by boingball** [comment]
> > I'm definitely no expert at C - ChatGPT C has been helping me this week. So looking at that I think AmiTCP makes a memory resident bsdsockets.library when loaded on the Amiga. I'm wondering if curl would work if we compile against Roadshow 1.8 SDK which actually includes a bsdsockets.library on disk. (Which Roadshow TCP 1.15 includes)
> 
> > 
> 
> > I wonder if the AmiTCP older lib is causing conflicts with the newer Roadshow TCP lib.
> 
> > 
> 
> > My 3 physical Amigas have Roadshow installed
> 
> > 
> 
> > SDK for Roadshow 1.8 available from here : https://www.amigafuture.de/app.php/dlext/details?df_id=3658
> 
> 
> 
> Thanks. Turning these sources into binaries would need an Amiga pro I suppose :)
> 
> 
> 
> Interestingly the `Makefile.mk` 2 years ago was able (in vAmiga) to show curl's version string (then crash): #9764
> 
> 
> 
> The toolchain is unusual in that is has several versions (layers ?) of headers, APIs and libs, making grep not so useful. There are knobs altering the selection, some used here and there in curl detection and source. Interfaces are sometimes macros, which make autotools and cmake detections behave differently.
> 
> 
> 
> The CMake build works now, with minor differences compared to autotools.

My C knowledge has came on this week that's for sure. ( getting zlib for Amiga was my first project last week )
I seen how obscure Curl was before hand to try and compile for AmigaOS - but looking at the changes in there , most was AmigaOS4 but were just marked as Amiga  (which I can't test as that's a platform I don't own) 

- I assume AmigaOS4 might have similar problems as they use Roadshow as their official TCP stack. 

When building curl at the moment, does it build against a certain bsdsockets? Or can that be selected - the Roadshow SDK has the same includes as AmiTCP - socketsbasetags.h 

I assume this is a roadshow bug in the end. As it should obey sockets openings in the same way as AmiTCP does. 

Thanks again for these patches - it's really appreciated !

**Comment by vszakats** [comment]
> * I assume AmigaOS4 might have similar problems as they use Roadshow as their official TCP stack.

Most likely, yes. Making this all work for v4 is another effort. There are conditional withing curl code too.

> When building curl at the moment, does it build against a certain bsdsockets? Or can that be selected - the Roadshow SDK has the same includes as AmiTCP - socketsbasetags.h

I have no idea! Took your build config a ran with it.

If the Roadshow SDK can be installed and used as-is for cross-builds, and
we know what knobs to set to select it, it probably could be done, or at least
attempted.

AmigaOS looks like in practice not one, but several platforms depending
on configuration and version. The socket library being just a lib (also 
bound to the TLS backend) and having at least two versions (3 and 4),
plus a `__libnix__` track with some past support in curl. 

This PR covers v3 with (or without) AmiSSL with `bsdsocket.library`.

(My picture of the components and their relations is very fuzzy though.)

> Thanks again for these patches - it's really appreciated !

You're welcome! It was fun and I think the code and builds benefitted
from the fixes, not just for Amiga, but also in general.

With two standard builds tools now at hand, it's probably easier to 
extend support into other Amiga OS variations.

**Comment by dfandrich** [comment]
FWIW there's an AmigaOS 4 binary for 8.7.1 on the downloads page pointing to
https://os4depot.net/index.php?function=modules/sql/filesbyuploader&submitter=Michael%20Trebilcock
So, somebody has gone through this exercise recently already.

**Comment by vszakats** [comment]
> FWIW there's an AmigaOS 4 binary for 8.7.1 on the downloads page pointing to https://os4depot.net/index.php?function=modules/sql/filesbyuploader&submitter=Michael%20Trebilcock So, somebody has gone through this exercise recently already.

Nice! I wonder about the toolchain. v4 is PowerPC.

Perhaps this?:
https://github.com/walkero-gr/AmigaGCConDocker
https://hub.docker.com/r/walkero/amigagccondocker/tags?page=2&name=gcc11

**Comment by vszakats** [comment]
Yes, we can do this!

I tried with this patch:
```diff
--- a/src/tool_main.c
+++ b/src/tool_main.c
@@ -63,6 +63,10 @@
 int vms_show = 0;
 #endif
 
+#if defined(__AMIGA__)
+static const char USED min_stack[] = "$STACK:16384";
+#endif
+
 #ifdef __MINGW32__
 /*
  * There seems to be no way to escape "*" in command-line arguments with MinGW
```

and got this:
```
./src/tool_main.c:67:24: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'min_stack'
 static const char USED min_stack[] = "$STACK:16384";
                        ^~~~~~~~~
```

`USED` is declared in `m68k-amigaos/include/SDI_compiler.h`, but
is this safe to assume it's there? Till we find out, this version compiles
fine:

```diff
--- a/src/tool_main.c
+++ b/src/tool_main.c
@@ -63,6 +63,15 @@
 int vms_show = 0;
 #endif
 
+#if defined(__AMIGA__)
+#if defined(__GNUC__)
+#define CURL_USED __attribute__((used))
+#else
+#define CURL_USED
+#endif
+static const char CURL_USED min_stack[] = "$STACK:16384";
+#endif
+
 #ifdef __MINGW32__
 /*
  * There seems to be no way to escape "*" in command-line arguments with MinGW
```

**Comment by boingball** [comment]
I added that patch to my local copy. But it doesn't seem to work. Maybe it doesn't get picked up correctly. Or doesn't work correctly - apparently this feature was added in AMIGAOS 3.1.4 and added to AmigaOS4 just after this. I'm using 3.2.2.1 (latest classic) which should work with it.

**Comment by vszakats** [comment]
> I added that patch to my local copy. But it doesn't seem to work. Maybe it doesn't get picked up correctly. Or doesn't work correctly - apparently this feature was added in AMIGAOS 3.1.4 and added to AmigaOS4 just after this. I'm using 3.2.2.1 (latest classic) which should work with it.

In my test build the string `$STACK:16384` is visible in the binary,
so that part is probably OK?

Can it be, that 16384 is still too low? The page uses 100K in its 
examples and suggests 80000 for a GUI apps.

**Comment by boingball** [comment]
Ignore me. It works a treat. 
I was pointed to the wrong folder in my test environment. I've set it to 32768 in my test build. 

And 16384

Both work fine 

Excellent work again!

**Comment by vszakats** [comment]
Some success with FS-UAE and trial and error with the placement of `.library` files!:
Screen Shot 2024-11-28 at AmigaOS3 curl-ssl-V

**Comment by boingball** [comment]
> Some success with FS-UAE and trial and error with the placement of `.library` files!:
> 
> Screen Shot 2024-11-28 at AmigaOS3 curl-ssl-V
> 
> 

Looking good. If you need any help that side please let me know.

I released the updated Curl binary with all the changes in here to Aminet - everything works great.

**Pull request closed without merging**
