### PR TITLE
Undefined behaviour in mprintf

### PR DESCRIPTION
**Pull request by stoeckmann**
Refactoring of mprintf code to prevent undefined behaviour (signed integer overflows and out of boundary accesses).

### CODE REVIEW

**Comment by bagder** [comment]
Thanks, but this seems to make test 557 fail sometimes. [example](https://github.com/curl/curl/pull/5722/checks?check_run_id=909964015#step:7:1699)

**Comment by bagder** [comment]
BTW, it would be awesome if we could also add test cases that reproduce these problems and then these fixes. Can you see if you can add that to [lib557.c](https://github.com/curl/curl/blob/master/tests/libtest/lib557.c) ?

**Comment by stoeckmann** [comment]
I have added a test case for this.

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
