### PR TITLE
Set SSL_BACKENDS from cmake build

### PR DESCRIPTION
**Pull request by webmaster128**
This groups all SSL backends into the feature "SSL" and sets the SSL_BACKENDS analogue to configure.ac.

This is a preparation for #3733 but independent of the DarwinSSL issue.

## Before

```
$ bash /build_dir/curl/curl-config --features
DarwinSSL
IPv6
unix-sockets
libz
AsynchDNS
```

```
$ bash /build_dir/curl/curl-config --ssl-backends

```

## After 

```
$ bash /build_dir/curl/curl-config --features
SSL
IPv6
unix-sockets
libz
AsynchDNS
```

```
$ bash /build_dir/curl/curl-config --ssl-backends
DarwinSSL
```

### CODE REVIEW

**Comment by MarcelRaad** [comment]
Unfortunately, the CMake build failed for the non-SSL builds on AppVeyor:

> -- Enabled features: IPv6 AsynchDNS
> -- Enabled protocols: DICT FILE FTP GOPHER HTTP IMAP LDAP POP3 RTSP SMTP TELNET TFTP
> CMake Error at CMakeLists.txt:1249 (list):
>  list sub-command SORT requires list to be present.

**Comment by webmaster128** [comment]
Thanks @MarcelRaad! Hmm, looks like due to the lack of a proper type system, there is no way to create an empty list. So we need to check if the variable is empty before trying to sort, which adds 2 additional lines for each of those lists. I'll do that later today or tomorrow if nobody has a better idea that allows us to call sort on every element count `>= 0`.

**Comment by webmaster128** [comment]
I could reproduce the problem locally with no SSL backend enabled and fixed it now.

**Comment by MarcelRaad** [comment]
Great, thanks! The AppVeyor failures are only the usual "slow response" tests, so I'm merging now.

**Pull request closed without merging**
