### PR TITLE
Enhance CURLOPT_FTP_SKIP_PASV_IP

### PR DESCRIPTION
**Pull request by Zenju**
In reference to: 
https://github.com/curl/curl/issues/1455

### CODE REVIEW

**Comment by bagder** [comment]
Try `make checksrc` in the root source code directory for some code style nits. Also visible [here](https://travis-ci.org/curl/curl/jobs/229298215).

**Comment by bagder** [comment]
Also, please squash commits suitably so that we get a set of logical linear changes (that could be merged) to review. Getting delta changes within the PR makes things harder to review.

**Comment by Zenju** [comment]
> Try make checksrc in the root source code directory for some code style nits

Done. I'll be blunt again and say that this should be solved by a pretty printer. Fixing the whitespace took me longer than the whole feature implementation.

> Also, please squash commits suitably

How can I do this? I'm using the git web interface.

**Comment by bagder** [comment]
> that this should be solved by a pretty printer

That would be cool, yes. Unfortunately the tools aren't there for it. See also https://github.com/curl/curl/wiki/clang-format-style

> I'm using the git web interface

I have no idea, I've never used that. I prefer the fine git command line tool.

**Comment by bagder** [comment]
Please squash the commits into the logical changes necessary. This is impossible to review as-is. Also, please use full and proper commit messages for the commits in the style we request. Commit messages should briefly explain the change.

**Comment by Zenju** [comment]
Not sure I understand the problem. This is a tiny patch, that can be easily reviewed at a glance via: https://github.com/curl/curl/pull/1470/files
Anyway, how can this commit be "sqashed"?

**Comment by bagder** [comment]
> This is a tiny patch, that can be easily reviewed

You used 19 commits to do this tiny patch and you pushed them all. Thus reviewing each change is unnecessarily complex for us. Sure, we can diff the final result but then we can't comment on the actual changes. That's sub-optimal. We want to be able to review the commits inline here on github and comment on them. And we want to merge the commits you provide instead of us then having to squash them.

> how can this commit be "sqashed"?

Enter `git squash` in a google search and you'll find plenty of resources describing how it works. It is basically a way to merge several commits into one.

As for the actual content of the patch, I would prefer to talk about the addresses as "private" and not "non routable" as that's how RFC 1918 speaks of them and that's the way I personally am used to refer to them. I think "non routable" sounds like some additional detection logic is used beyond just ignoring private addresses.

I think the defines `CURL_FTP_SKIP_PASV_IP_*` should have a `L` suffix to make them less error-prone when used in the code, like in the example. Maybe we can think of some way to shorten the names somewhat?

**Comment by bagder** [comment]
Still no response to the requested changes, closing.

**Pull request closed without merging**
