### PR TITLE
CI: debug if we randomly are killing ourselves on Win32

### PR DESCRIPTION
**Pull request by mback2k**
Not to be merged.

Previous example failure: https://github.com/curl/curl/runs/8285644244

### CODE REVIEW

**Comment by mback2k** [comment]
Reproduced failure: https://dev.azure.com/mback2k/curl/_build/results?buildId=1075&view=logs&j=e7c72124-b275-5783-0311-a91da4bbcc8b&t=73dc882c-50a4-5b1c-38aa-d437ef5d9e59&l=2170

**Comment by mback2k** [comment]
It seems like some processes are killed by `runtests.pl` after test 677 although that and the following test do not ask for that. Weird!

@bagder any idea why this might be happening?

**Comment by bagder** [comment]
Is this the `killpid()` function getting called? If so, from where?

**Comment by mback2k** [comment]
> Is this the `killpid()` function getting called? If so, from where?

That is also what I was wondering. I don't see a reason for it to be called. Is there some kind of stacktrace in Perl to figure this out?

**Comment by mback2k** [comment]
Closing, will come back to this at a later point. Right now I don't think just the Windows CI is a main source of flakiness anymore. Actually it seems much more stable recently.

**Pull request closed without merging**
