### PR TITLE
GHA: bump ngtcp2 and nghttp3 to 1.0.x, nghttp2 to 1.58.0

### PR DESCRIPTION
**Pull request by bagder**
"No more incompatible changes."

### CODE REVIEW

**Comment by bagder** [comment]
The lastest nghttp2 release (1.57.0) cannot build nghttpx with these versions, so we probably need a new version of that as well.

**Comment by vszakats** [comment]
nghttp2 1.78.0 is out: https://github.com/nghttp2/nghttp2/releases/tag/v1.58.0

**Comment by icing** [comment]
ngtcp2 has a v1.0.1 released. currently testing locally

**Comment by vszakats** [comment]
If we're at this, quictls also got an update yesterday to 3.0.12+quic, though 3.1.4+quic is also available.

**Comment by bagder** [comment]
> If we're at this, quictls also got an update yesterday to 3.0.12+quic, and 3.1.4+quic is also available.

Yeps, might as well do that while we're there.

**Pull request closed without merging**
