### PR TITLE
Revert "build: remove checks for WinSock 1"

### PR DESCRIPTION
**Pull request by bagder**
This reverts commit c2ea04f92b00b6271627cb218647527b5a50f2fc.

It caused CI problems

### CODE REVIEW

**Review by MarcelRaad — APPROVED** [review]
Sorry! I'll look into them as soon as possible.

**Review by MarcelRaad — APPROVED** [review]
Sorry! I'll look into them as soon as possible.

**Comment by bagder** [comment]
Ok no worries, do you think I shall merge this revert first to give you some extra time and piece to fix it?

**Comment by MarcelRaad** [comment]
Yes please! I'm looking into it right now, but haven't been able to reproduce the issue so far with MinGW. `autoreconf -fi && ./configure --with-schannel` works perfectly fine for me with https://github.com/curl/curl/pull/7788...

**Pull request closed without merging**
