### PR TITLE
tests: make Python-based servers compatible with Python 2 and 3

### LINKED ISSUE #5104: SMB tests on Debian?
### I did this

`apt install python3-impacket`

`cd tests && ./runtests.pl 1451`

~~~
Python package impacket needs to be installed!
Use pip or your package manager to install it.
RUN: failed to start the SMB server
~~~

(I could run them fine before 4be2560e01ed40)

### I expected the following

To be able to run test 1451

### curl/libcurl version

Current git master

### operating system

Debian Linux, unstable. Updated just now.

cc: @mback2k

### PR DESCRIPTION
**Pull request by mback2k**
Update `smbserver.py` and `negtelnetserver.py` to be compatible with
Python 3 while staying backwards-compatible to support Python 2.

Tested with both Python 2.7.17 and Python 3.7.7

Fixes #5104
Follow up to #5094

### CODE REVIEW

**Comment by mback2k** [comment]
I will add another commit to update CI dependencies after they have run once to see mismatches.

**Comment by bagder** [comment]
Do we really need to support python 2?

**Comment by mback2k** [comment]
I think we should at least until Ubuntu Xenial (16.04 LTS) and other distros that are currently still supporting it, stop doing that. There will probably be one last maintenance release for Python 2.7 around April and I guess some of our older CI environments are also still using it.

**Comment by bagder** [comment]
But surely they support python3 as well? And since we require special installed packages anyway, we could just require a python3 install?

**Comment by mback2k** [comment]
> But surely they support python3 as well? And since we require special installed packages anyway, we could just require a python3 install?

That is true for `smbserver.py`, but not for `negtelnetserver.py`. I am not against dropping Python 2 support later this year, but IMHO at the moment it is not really hurting us in any way. Both files just contain a small if-statement to do the right imports and that is it as of now. Most of the code is still 2-ish and does not make use of any 3-ish features.

**Comment by kdudka** [comment]
We use the following patch downstream to improve Python 3 compatibility:

    https://src.fedoraproject.org/rpms/curl/blob/ac5c236f/f/0103-curl-7.59.0-python3.patch

But I am not sure if it is still needed or useful.

**Comment by mback2k** [comment]
@kdudka you patch looks useful to me, would you mind me committing it here upstream?

**Comment by kdudka** [comment]
@mback2k That would be awesome.  Thanks!

**Comment by mback2k** [comment]
> I really can't comment on the code. I have no idea.

@bagder to squash or not to squash, that is the question here.

**Comment by mback2k** [comment]
Just for reference, these are the tests affected by this PR: 1326, 1327, 1451 and 1452

**Comment by kdudka** [comment]
I tried it on Fedora with Python 3.8.2.  Tests 1326, 1327 and 1452 are passing in my environment even on current master (commit d83402813b624d9067416bea2e7feb70a358cf65). Test 1452 is skipped on master with:
```
env: ‘python2’: No such file or directory
RUN: failed to start the SMB server
```

Unfortunately, the mentioned Fedora patch broke it completely:
```***************************************** 
test 1451 SKIPPED: precheck command error
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 47062)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/socketserver.py", line 316, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 347, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python3.8/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python3.8/socketserver.py", line 720, in __init__
    self.handle()
  File "/home/kdudka/curl/tests/negtelnetserver.py", line 97, in handle
    self.request.sendall(response_data.encode('utf8'))
AttributeError: 'bytes' object has no attribute 'encode'
[...]
```

If I revert the Fedora patch, `test1452` passes.  Please drop the patch.  Sorry for the troubles!

**Comment by kdudka** [comment]
I forgot to say that `test1451` is still being skipped in my environment.  This tiny patch seems to fix it:
```
--- a/tests/data/test1451
+++ b/tests/data/test1451
@@ -29,7 +29,7 @@ Basic SMB request
 -u 'curltest:curltest' smb://%HOSTIP:%SMBPORT/TESTS/1451
 </command>
 <precheck>
-python2 -c "__import__('pkgutil').find_loader('impacket') or (__import__('sys').stdout.write('Test only works if Python package impacket is installed\n'), __import__('sys').exit(1))"
+python -c "__import__('pkgutil').find_loader('impacket') or (__import__('sys').stdout.write('Test only works if Python package impacket is installed\n'), __import__('sys').exit(1))"
 </precheck>
 </client>
```

**Comment by mback2k** [comment]
@kdudka thanks for the feedback, instead of dropping your patch, I just fixed it the right way. 😉

**Comment by mback2k** [comment]
I am still working on making all CIs run the relevant tests and also turn green.

Once this happens, I will rebase, squash and merge this PR.

**Pull request closed without merging**
