### PR TITLE
ci/tests: Make it possible to still run but ignore failing tests

### PR DESCRIPTION
**Pull request by mback2k**
This enables the development of a solution for the failing tests by
running them on CI while ignoring their result for the overall status.

### CODE REVIEW

**Comment by bagder** [comment]
It's a good idea, although it seems it doesn't quite work correctly yet... :grin:

**Comment by jay** [comment]
Why run a test just to ignore the result?

**Comment by bagder** [comment]
If the results are kept/reported somewhere, a benefit would be that we could then possibly spot when ignored tests are starting to actually work again...

**Comment by mback2k** [comment]
Some tests have never worked on some platforms, e.g. Windows. Those have always been disabled. I want to keep them running, but do not make those "known failures" mark the CI red to avoid misunderstandings in PRs and such. By keeping them running and the result at least showing up in the logs, we can work on fixing them and then remove them from the ignore list.

**Comment by jay** [comment]
ok

**Comment by mback2k** [comment]
This was hopefully the last rebase to get a green CI in order to merge this before the release.

**Comment by mback2k** [comment]
My new plan is to get this in tomorrow after it has been updated once PR #5021 is merged.

**Pull request closed without merging**
