### PR TITLE
Add CURLINFO_PAUSE_STATE

### PR DESCRIPTION
**Pull request by Thalhammer**
This adds an CURLINFO flag to get the current pause state of the connection as it can be set using curl_easy_pause or by returning the special values from write/read callbacks. The change is pretty trivial given all the info is already present in the request struct (but with different flags), however theres lots of other documentation to do. I oriented myself on CURLINFO_PROTOCOL on whats needed and hope I caught everything. however there are two points in particular that might need to be looked at:

* `packages/OS400/curl.inc.in` I genuinely have no clue what that file does, nor how its structured.
* Testing. While the change is very small, I see that curl/libcurl is extremly well tested, so some kind of simple test is probably needed for this as well.

Given the simplicity of the change I wrote all the documentation under the assumption that it will land in 7.79.0. If thats not the case or it wont get merged at all (and I am perfectly fine if it aint) that needs to get changed as well.

### CODE REVIEW

**Comment by dfandrich** [comment]
I haven't looked at the patch, but if all it does is return the current pause
state, can't this be tracked by the application itself? The application must
explicitly tell libcurl when to pause and unpause, so it could just as easily
just track it without this patch.

**Comment by Thalhammer** [comment]
It can, but having access to the actual state of curl makes the tracking easier and the part having to unpause might not always have complete control over the connection. As a result of this it is impossible to unpause just the sending or receiving part of the connection without knowing the state of the other.

This already came up in #2588 and got added to the TODO list. This pr pretty much just implements the TODO item, cause I googled for the same thing and came across the original github issue. The tests seem to fail cause appearently I am a couple of characters to long, I will fix that tomorrow.

I am perfectly fine if this is not something to get merged though, given libcurl already is a huge library.

**Comment by bagder** [comment]
Keeping track of a boolean flag per transfer seems like a very easy thing to do, and most applications will need to keep at least some state and information per transfer anyway. It feels like a feature we maybe don't need to add?

I know it was me who suggested to use `curl_easy_getinfo()` back in #2588 but I also think there's a subtle problem with adding this flag to this function: it is right now clearly documented to be called **after** a transfer is complete and thus we only really guarantee post-transfer functionality.

Adding a feature that relies on the function working mid-transfer will need tests added for it and that we also document exactly what goes for which options mid and post transfer. I'm not convinced this minor flad is worth that additional work.

**Comment by Thalhammer** [comment]
> It feels like a feature we maybe don't need to add?

No its not at all a requirement. When I wrote the code for this the basic options where write my own on top of curl or do the todo item (since apearently someone else was interested in it as well) and maybe get it merged into curl. I am perfectly fine if this never makes it to curl since I did not really spend a lot of time on it.

> only really guarantee post-transfer functionality.

I did not see anything inside the function that would prevent it (at least the info items designed for it like this one) to be used during the transfer is active and in fact I have been using others (HTTPRESPONSECODE) during the transfer as well for ages now. But yes you are right, its obviously not something the documentation formally allows.

> I'm not convinced this minor flad is worth that additional work.

I am perfectly fine with this decision, even though I had multiple cases where it was usefull to query information before the transfer is finished (e.g. the http status inside write callbacks). While this is certainly possible to do by registering a header callback, getinfo is just way easier to use and documenting this behaviour would probably hold value in its own outside this pr.

**Comment by bagder** [comment]
Thanks a lot for your contribution and willingness to help out improving curl!

This is an easy state to keep track of outside of libcurl and as such I think resisting feature creep is worthwhile so I'm against merging this now.

**Pull request closed without merging**
