### PR TITLE
test1140/1173: extend wildcards to find curl.1

### PR DESCRIPTION
**Pull request by bagder**
... in its new build path.

Also update the test scripts to be more precise in error messages to help us understand CI errors better.

Ref: #13029

Follow-up to f03c85635f35269f1

### CODE REVIEW

**Comment by dfandrich** [comment]
Leaving the old glob there with no corresponding file means the shell doesn't expand it and it ends up as a literal string and the error  `test1140.pl could not open /tmp/cm/tests/../docs/*.1 ...` occurs

**Comment by bagder** [comment]
There should still be corresponding files there: `curl-config.1` and `mk-ca-bundle.1`

**Comment by bagder** [comment]
... which is why the tests still run fine on configure builds.

**Comment by dfandrich** [comment]
Maybe there should be, but they're not.  Run "cmake . && make -j9 && make -j9 test-ci TFLAGS='1140 1173'" in a new git clone and see for yourself.

**Comment by bagder** [comment]
I believe you, I'm just hinting that the problem is still in the cmake build of the docs.

**Pull request closed without merging**
