### PR TITLE
configure: set -Wextra-semi-stmt for clang with --enable-debug

### PR DESCRIPTION
**Pull request by bagder**
To have it properly complain on empty statements with no effect.

Ref: #6376

### CODE REVIEW

**Comment by olafhering** [comment]
This causes CI errors in MR, not sure if these errors are regressions.

**Comment by bagder** [comment]
MR? You mean pull request? If so which? If you rebase on master there should be no such warnings, surely?

**Comment by olafhering** [comment]
There are a few failures in curl/curl#6392
Some of them indicate "issues with semicolon", but I did not investigate them.

**Comment by bagder** [comment]
Thanks, I noticed! I don't know how I missed them before but I think I've fixed then now...

**Comment by olafhering** [comment]
I rebased to a6d20b89d, lets see how it goes.

**Comment by olafhering** [comment]
Thanks, appears to work. There are apparently some unrelated runtime errors left.

**Pull request closed without merging**
