### PR TITLE
hsts: enable by default

### PR DESCRIPTION
**Pull request by vszakats**
in:
- default build system
- `Makefile.m32`
- `MakefileBuild.vc`

### CODE REVIEW

**Comment by vszakats** [comment]
Reason for test failures:
```
test 0493...[HSTS and %{url_effective} after upgrade]

 493: protocol FAILED!
 There was no content at all in the file log/server.input.
 Server glitch? Total curl failure? Returned: 6
== Contents of files in the log/ dir after test 493
=== Start of file commands.log
 ../libtool --mode=execute /usr/bin/valgrind --tool=memcheck --quiet --leak-check=yes --suppressions=./valgrind.supp --num-callers=16 --log-file=log/valgrind493 ../src/curl --include --trace-ascii log/trace493 --trace-time -x http://127.0.0.1:46655 http://this.hsts.example/493 --hsts log/input493 -w '%{url_effective}\n' >log/stdout493 2>log/stderr493
=== End of file commands.log
=== Start of file ftpserver.cmd
 Testnum 493
=== End of file ftpserver.cmd
=== Start of file input493
 # Your HSTS cache. https://curl.se/docs/hsts.html
 # This file was generated by libcurl! Edit at your own risk.
 .hsts.example "20311001 04:47:41"
=== End of file input493
=== Start of file stderr493
   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                  Dload  Upload   Total   Spent    Left  Speed

   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: this.hsts.example
=== End of file stderr493
=== Start of file stdout493
 https://this.hsts.example/493
=== End of file stdout493
=== Start of file trace493
 19:37:21.794854 == Info: Switched from HTTP to HTTPS due to HSTS => https://this.hsts.example/493
 19:37:22.006503 == Info: Could not resolve host: this.hsts.example
 19:37:22.015886 == Info: Closing connection 0
=== End of file trace493
```

**Comment by vszakats** [comment]
After addressing the Windows build issues, this came up (e.g. `msys2_mingw32_debug_openssl`, `msys2_mingw64_debug_openssl`):
```
test 1660...[HSTS]
sh: line 1:  6583 Segmentation fault      ./unit/unit1660 - > log/stdout1660 2> log/stderr1660

 1660: stdout FAILED:
--- log/check-expected	2021-02-18 17:41:37.602128000 -0800
+++ log/check-generated	2021-02-18 17:41:37.602128000 -0800
@@ -1,34 +0,0 @@
-readfrom.example [readfrom.example]: 1633063661 includeSubDomains[LF]
-'old.example' is not HSTS[LF]
-'readfrom.example' is not HSTS[LF]
-example.com [example.com]: 1579905261[LF]
[...]
```

**Comment by jay** [comment]
CI output reference links aren't suited for commit messages because they seem to be mostly ephemeral.

**Comment by jay** [comment]
On a different project that was rarely updated we used appveyor artifacts as the download links and one day they expired

**Comment by vszakats** [comment]
AppVeyor artifacts do indeed expire after 6 months. This was introduced a few years ago. But logs are kept online without an expiration. With `travis-ci.org` (and `bintray.com`, etc...) being retired soon, no link lasts forever, so what I used to do is copy-paste the single relevant error message (+ compiler command-line) being fixed, if it is non-trivial.

**Comment by vszakats** [comment]
At this point the one remaining failure is 32-bit mingw debug builds segfaulting in `init1660`.

I'm also preparing a patch that fixes `time_t` size for 64-bit mingw builds, and that lets manually enabling 64-bit `time_t` for 32-bit mingw build. Newer mingw-w64 envs do support it.

**Comment by vszakats** [comment]
Can't put my finger on the underlying dynamic, but after swapping `time_t` for `curl_off_t` in the HSTS structure, the mingw failures/crashes are gone. Similar solution is already being used in `cookies.c` (but not in `altsvc.c`, where `time_t` is used internally.)

Anyhow, now the [`test493`](https://travis-ci.org/github/curl/curl/jobs/759863554#L4534) fail in one valgrind session, but that's probably easier to look after. All help is much welcome here.

**Comment by vszakats** [comment]
I'm sadly giving up on this — On the note, that it'd be real cool to enable it, and some of these fixes may make sense in a future time this happened.

**Comment by vszakats** [comment]
Rebooted here: https://github.com/curl/curl/pull/6700 — Thanks @bagder!

**Pull request closed without merging**
