### PR TITLE
CryptAcquireContext should be found

### PR DESCRIPTION
**Pull request by ALittleDruid**
After set(CMAKE_REQUIRED_INCLUDES "${CURL_SOURCE_DIR}/include")

image

image

"D:\vcpkg\installed\x64-windows\include" is correct

https://github.com/microsoft/vcpkg/issues/27978#issue-1462189230

### CODE REVIEW

**Comment by jay** [comment]
Can any dev familiar with cmake explain how CMAKE_REQUIRED_INCLUDES is supposed to work? I notice in CMakeLists.txt it is sometimes appended to as a list and other times cleared, as it is before getting the type of curl_off_t, which seems to have caused this bug. The reporter's fix to move the CryptAcquireContext check before the curl_off_t check looks like it masks a larger problem.

**Comment by jzakrzewski** [comment]
It's a list of include directories to use for all the checks that involve running a compiler. In my own projects I tend to re-set it after each check to make sure I'm not clobbering the next one, and to make sure the stuff I'm looking for is where I expect it, and not in some random place.

**Comment by ALittleDruid** [comment]
> 
https://cmake.org/cmake/help/latest/module/CheckSymbolExists.html

check_symbol_exists(CryptAcquireContext "${CURL_INCLUDES}" USE_WINCRYPT)

"${CURL_INCLUDES}" is windows.h;ws2tcpip.h;winsock2.h;wincrypt.h;sys/stat.h;sys/types.h;sys/utime.h;fcntl.h;idn2.h;io.h;locale.h;setjmp.h;signal.h;stdbool.h;stdlib.h;string.h;time.h;stddef.h

File CheckSymbolExists.c:
/* */
#include <windows.h>
#include <ws2tcpip.h>
#include <winsock2.h>
#include <wincrypt.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/utime.h>
#include <fcntl.h>
#include <idn2.h>
#include <io.h>
#include <locale.h>
#include <setjmp.h>
#include <signal.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stddef.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CryptAcquireContext
  return ((int*)(&CryptAcquireContext))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Another way to modify it: change "${CURL_INCLUDES}" to "windows.h"

check_symbol_exists(CryptAcquireContext "windows.h" USE_WINCRYPT)

**Comment by jzakrzewski** [comment]
`CryptAcquireContext` is documented to live in `wincrypt.h`, so I suppose this is where we should be looking for it, and not "everywhere".

**Comment by jay** [comment]
I looked at your latest changes and I don't understand how this works for you now if CMAKE_REQUIRED_INCLUDES does not need to be reset. Don't you have the same problem, where the previously set CMAKE_REQUIRED_INCLUDES uses the wrong include directory?

**Comment by ALittleDruid** [comment]
> I looked at your latest changes and I don't understand how this works for you now if CMAKE_REQUIRED_INCLUDES does not need to be reset. Don't you have the same problem, where the previously set CMAKE_REQUIRED_INCLUDES uses the wrong include directory?

check_symbol_exists(<symbol> <files> <variable>)
check_symbol_exists(CryptAcquireContext "${CURL_INCLUDES}" USE_WINCRYPT)
<files> is windows.h;ws2tcpip.h;winsock2.h;wincrypt.h;sys/stat.h;sys/types.h;sys/utime.h;fcntl.h;idn2.h;io.h;locale.h;setjmp.h;signal.h;stdbool.h;stdlib.h;string.h;time.h;stddef.h

CMAKE_REQUIRED_INCLUDES  is ${CURL_SOURCE_DIR}/include

cmake try compile CheckSymbolExists.c

`#include <windows.h>
#include <ws2tcpip.h>
#include <winsock2.h>
#include <wincrypt.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/utime.h>
#include <fcntl.h>
#include <idn2.h>
#include <io.h>
#include <locale.h>
#include <setjmp.h>
#include <signal.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stddef.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef CryptAcquireContext
  return ((int*)(&CryptAcquireContext))[argc];
#else
  (void)argc;
  return 0;
#endif
}`

CheckSymbolExists.c include unnecessary header files and idn2.h not found in ${CURL_SOURCE_DIR}/include

The latest changes only include windows.h and wincrypt.h

**Comment by jay** [comment]
> CheckSymbolExists.c include unnecessary header files and idn2.h not found in ${CURL_SOURCE_DIR}/include

So in that case is the reason the test fails that idn2.h isn't found?

**Comment by ALittleDruid** [comment]
> > CheckSymbolExists.c include unnecessary header files and idn2.h not found in ${CURL_SOURCE_DIR}/include
> 
> So in that case is the reason the test fails that idn2.h isn't found?

Yes

Befor `set(CMAKE_REQUIRED_INCLUDES "${CURL_SOURCE_DIR}/include")`, CMAKE_REQUIRED_INCLUDES  is D:\vcpkg\installed\x64-windows\include and idn2.h can be found in that path

That's enough to check CryptAcquireContext include `windows.h` and `wincrypt.h `, the default include path is able to find these header files

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
