### PR TITLE
Run tests in AppVeyor

### PR DESCRIPTION
**Pull request by MarcelRaad**
- use in-tree build
- remove redundant builds to compensate for the longer run times
- use the preinstalled MSYS2 shell to run the tests

Test 1139 was disabled as the CMake build doesn't generate `curl.1`.
Test 500 was disabled as it failed with `starttransfer vs total: 0.000001 0.000000` very often.

### CODE REVIEW

**Comment by bagder** [comment]
Lovely! Maybe switch off the verbose before landing but I love it!

**Comment by jay** [comment]
I'm skeptical of disabling tests, we may have a bug somewhere causing that issue.

**Comment by bagder** [comment]
> I'm skeptical of disabling tests, we may have a bug somewhere causing that issue.

Sure, but I think improving the CI to run all tests except those two is such a huge improvement that I'm willing to risk that. Before this step, we didn't run *any* CI tests on windows.

Improving test 500 to work also on appveyor could be done as a high-prio separate issue since its not really an appveyor issue, its just that it outputs timing data and that seems risky to do in general and even more so on "cloud computers".

**Comment by MarcelRaad** [comment]
I agree it would be better to not disable these tests. I'll try to enable one or both of them in the coming days after merging this.

**Pull request closed without merging**
