### PR TITLE
fix cmake build error that add_subdirectory for other cmake project using curl

### PR DESCRIPTION
**Pull request by chenchuanyin**

### CODE REVIEW

**Comment by snikulov** [comment]
@chenchuanyin Could you please gives us more details about build error you've observed?
Error log and how-to reproduce would be great.

Another observations:

1. Could you please read https://github.com/curl/curl/blob/master/docs/CONTRIBUTE.md and update your commit message accordingly? Squashing into single commit also welcomed.
2. Could you please explain why not using CMAKE_CURRENT_BINARY_DIR and CMAKE_CURRENT_SOURCE_DIR in your changes? (While it is the same values, it looks inconsistent with exiting code).

**Comment by chenchuanyin** [comment]
Hi @snikulov,
Thank you for replying.  I just want to fix the problem in adding curl in my cmake project at that time.

In my project, I meet three problems:
1. cmake cannot find "${CMAKE_BINARY_DIR}/docs/curl.1" in docs/cmdline-opts/CMakeLists.txt, because ${CMAKE_BINARY_DIR} is not equal with ${CURL_BINARY_DIR}. Error message is as follows:
`[ 46%] Generating ../../../../docs/curl.1
/bin/sh: /Users/silver/Documents/git/chenchuanyin/test/build/docs/curl.1: No such file or directory
make[2]: *** [docs/curl.1] Error 1
make[1]: *** [third_party/curl/docs/cmdline-opts/CMakeFiles/generate-curl.1.dir/all] Error 2
make: *** [all] Error 2`
2. cannot find "${CMAKE_SOURCE_DIR}/include/curl/curl.h" in tests/libtest/CMakeLists.txt. The reason is same with the No 1. Error message is as follows:
`make[2]: *** No rule to make target `../include/curl/curl.h', needed by `third_party/curl/tests/libtest/lib1521.c'.  Stop.
make[1]: *** [third_party/curl/tests/libtest/CMakeFiles/lib1521.dir/all] Error 2
make: *** [all] Error 2`
3. cannot find "curl/curl.h" in my code when adding target_link_libraries(app libcurl), so I add BUILD_INTERFACE

Have a nice day!
chenchuanyin

**Comment by jzakrzewski** [comment]
Again, I always recommend using external projects for non-header-only libraries. It's more reliable and avoids potential clashes.

**Comment by snikulov** [comment]
@chenchuanyin What about rest of my comments?

**Comment by snikulov** [comment]
@bagder @jzakrzewski Hey Daniel, Jakub!
IMO it's useful fixes for CMake build. I've played with CPR project which includes curl using 
`add_subdirectory(...)` and I can confirm that all observations are correct.
Fixes also are valid. So I give my :+1:  to merge this.

**Comment by snikulov** [comment]
@chenchuanyin landed on master with f8215f80abe3b3b037d037f891f5f94aad68b440
Thank you!

**Pull request closed without merging**
