### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by a1346054**
Review comments are very welcome, so that I can improve the commit messages if needed.

### CODE REVIEW

**Review by danielgustafsson — APPROVED** [review]
These seem all fine to me, thanks! They will be squashed to a single commit before merging into master, but the committer can take care of that.

**Comment by danielgustafsson** [comment]
This is not a feature of course, but I don't see any reason to merge more than we have to for the minor release going out. This can wait for 7.80 IMO.

**Comment by a1346054** [comment]
Sure, I can squish them all. Is there a recommended commit message you'd like me to use? It is fixing typos in many separate files from different parts of the codebase.

**Comment by danielgustafsson** [comment]
> Sure, I can squish them all. Is there a recommended commit message you'd like me to use? It is fixing typos in many separate files from different parts of the codebase.

Thanks! I would use "misc: fix typos in docs and comments" and then mention in the commit message that no user facing output from curl/libcurl is changed by this, just comments.

**Comment by a1346054** [comment]
Squashed commits and reworded commit message.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
