### PR TITLE
url: fix CURLU and location following

### PR DESCRIPTION
**Pull request by jay**
Prior to this change if the user set a URL handle (CURLOPT_CURLU) it was
incorrectly used for the location follow, resulting in infinite requests
to the original location.

Reported-by: sspiri@users.noreply.github.com

Fixes https://github.com/curl/curl/issues/5709
Closes #xxxx

### CODE REVIEW

**Comment by jay** [comment]
Also, I notice that in parseurlandfillconn that when it creates a URL handle even if following a location it uses the user settings to determine the flags. Is that right for following a location (regardless of whether CURLU is set by the user)?

https://github.com/curl/curl/blob/5a1fc8d33808d7b22f57bdf9403cda7ff07b0670/lib/url.c#L1866-L1873

**Comment by bagder** [comment]
How about also adding a libtest that proves it working?

**Comment by bagder** [comment]
> Is that right for following a location 

I think so, yes.

**Comment by jay** [comment]
Might there be other cases where a URL has changed but it's not a followed location, and in that case should we not default to the user's set url handle?

**Comment by bagder** [comment]
I can't think of any such case...

**Comment by jay** [comment]
I kind of feel like this isn't far enough but I'm not sure how to make it better. I'm concerned I'm missing some corner case. I can't redo it to always prefer data->change.url because currently if one sets both CURLOPT_CURLU and CURLOPT_URL the former overrides the latter and it's documented that way.

**Comment by bagder** [comment]
With a test case to verify, I think it's good to land as is.

**Pull request closed without merging**
