### PR TITLE
curl_setup: fix config-mac.h not being included

### PR DESCRIPTION
**Pull request by qaisjp**

### CODE REVIEW

**Comment by bagder** [comment]
Please elaborate on why and when you need this?! It's not like people don't already build curl perfectly fine on macOS without this patch!

**Comment by qaisjp** [comment]
Hi, sorry for not including a pull request description.

I'm currently unable to build curl without this patch.

<details><summary><em>Without this patch</em> I get the following build output...</summary>
<pre>
==== Building curl (debug_x64) ====
altsvc.c
asyn-ares.c
asyn-thread.c
base64.c
conncache.c
connect.c
content_encoding.c
cookie.c
In file included from ../vendor/curl/lib/cookie.c:83:
In file included from ../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:109:8: error: redefinition of 'timeval'
struct timeval {
       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:34:1: note: previous definition is here
_STRUCT_TIMEVAL
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:29:40: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
In file included from ../vendor/curl/lib/conncache.c:24:
In file included from In file included from ../vendor/curl/lib/curl_setup.h:../vendor/curl/lib/asyn-thread.c713::
23:
In file included from ../vendor/curl/lib/curl_setup.h../vendor/curl/lib/curl_setup_once.h::713109:
:8: ../vendor/curl/lib/curl_setup_once.h:109error:: 8: redefinitionerror : of 'timeval'redefinition
 of 'timeval'
struct timeval {In file included from
../vendor/curl/lib/cookie.cstruct timeval {:
       ^83
:
       ^In file included from
../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:174:3:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h :/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h34:error:34: 1::1 :unknown  typenote : notename:  previous'Error' previousdefinitionIn file included from   is../vendor/curl/lib/content_encoding.cdefinition
:  23ishere:
 In file included from here
../vendor/curl/lib/curl_setup.h:
713:
_STRUCT_TIMEVAL
../vendor/curl/lib/curl_setup_once.h_STRUCT_TIMEVAL  Error Missing_definition_of_macro_sread^:


109^  ^:

8: error: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h::2929::redefinition4040 ::of   'timeval'notenote
: : expanded from macro '_STRUCT_TIMEVAL'
struct timeval {
       ^
#define _STRUCT_TIMEVAL         struct timevalexpanded
                                       ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:34:1:  note: previous definition is here
from_STRUCT_TIMEVAL
^
 /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:29:40: note: expanded frommacro  macro '_STRUCT_TIMEVAL'
../vendor/curl/lib/curl_setup_once.h:174:42'_STRUCT_TIMEVAL':
error: expected ';' after top level declarator
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
In file included from ../vendor/curl/lib/asyn-thread.c:23:
In file included from ../vendor/curl/lib/curl_setup.h:713:
In file included from ../vendor/curl/lib/content_encoding.c../vendor/curl/lib/curl_setup_once.h::23174:
:In file included from 3../vendor/curl/lib/curl_setup.h:: 713:
error../vendor/curl/lib/curl_setup_once.h: :174:unknown3 :type  name error'Error':
unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
  Error Missing_definition_of_macro_sread
  ^
In file included from ../vendor/curl/lib/conncache.c:24:
In file included from ../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:174:3: error: unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
../vendor/curl/lib/curl_setup_once.h:174:42: error: ../vendor/curl/lib/curl_setup_once.hexpected: 174';': 42after:  top levelerror : declarator
expected ';' after top level declarator
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;../vendor/curl/lib/curl_setup_once.h
:174:42: error: expected ';' after top level declarator
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
In file included from ../vendor/curl/lib/altsvc.c:26:
In file included from ../vendor/curl/lib/curl_setup.hIn file included from :../vendor/curl/lib/cookie.c:87:
In file included from 3../vendor/curl/lib/urldata.h713::
82 errorIn file included from :
s generated.
../vendor/curl/lib/cookie.h../vendor/curl/lib/conncache.c:../vendor/curl/lib/curl_setup_once.h::3728:109:
:38:In file included from :  ../vendor/curl/lib/urldata.h:82errorerror:
: : ../vendor/curl/lib/cookie.hunknown: 37redefinitiontype:  3nameof:   'bool''timeval'

error: unknown type name 'bool'
struct timeval {
       ^
  bool tailmatch;    /* whether we do tail-matching of the domain name */
  ^
  bool tailmatch;    /* whether we do tail-matching of the domain name */
  ^/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h
:34:1: note: previous definition is here
_STRUCT_TIMEVAL
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:29:40: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
In file included from In file included from ../vendor/curl/lib/content_encoding.c../vendor/curl/lib/connect.c::2523:
:
In file included from ../vendor/curl/lib/urldata.h:82:
../vendor/curl/lib/cookie.h:37:3: In file included from ../vendor/curl/lib/curl_setup.herror: unknown type name 'bool'
  bool tailmatch;    /* whether we do tail-matching of the domain name */
  ^
:713:
../vendor/curl/lib/curl_setup_once.h:109:8: ../vendor/curl/lib/cookie.h../vendor/curl/lib/cookie.h::4343::33::  error: errorerror: : unknownunknown  typetype  namename  'bool''bool'

redefinition  bool secure;       /* whether the 'secure' keyword was used */
  bool secure;       /* whether the 'secure' keyword was used */
of  ^
  ^
 'timeval'
In file included from ../vendor/curl/lib/altsvc.c:26:
In file included from ../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:174:3: error: unknown type name 'Error'../vendor/curl/lib/cookie.h
:43:3: error: unknown type  Error Missing_definition_of_macro_sread name 'bool'
  bool secure;       /* whether the 'secure' keyword was used */
../vendor/curl/lib/cookie.h:  ^
44
../vendor/curl/lib/cookie.h::344:: 3: error: error: unknown typeunknown  nametype  'bool'name
'bool'
  bool livecookie;   /* updated from a server, not a stored file */
  bool livecookie;   /* updated from a server, not a stored file */
  ^
  ^
  ^
../vendor/curl/lib/cookie.h:44:3: error: unknown type name 'bool'
../vendor/curl/lib/cookie.h../vendor/curl/lib/cookie.h::4545::33::  errorerror:   bool livecookie;   /* updated from a server, not a stored file */:
unknown  ^ unknown
type  typename  name'bool' 'bool'

  bool httponly;     /* true if the httponly directive is present */  bool httponly;     /* true if the httponly directive is present */

  ^
  ^
../vendor/curl/lib/cookie.h:45:3: error: unknown type name 'bool'
../vendor/curl/lib/curl_setup_once.h../vendor/curl/lib/cookie.h::17464::423:  bool httponly;     /* true if the httponly directive is present */:
   ^error
error: : expectedunknown  ';'type  aftername  top'bool' level
 declarator
  bool running;    /* state info, for cookie adding information */
  ^  Error Missing_definition_of_macro_sread

                                         ^
                                         ;
struct timeval {
       ^
In file included from ../vendor/curl/lib/cookie.h:64:/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h3../vendor/curl/lib/cookie.h:::34 66::13:error: :  unknownerror : type nameunknown  'bool'type
name 'bool'
  bool running;    /* state info, for cookie adding information */
  ^
  bool newsession; /* new session, discard session cookies on load */../vendor/curl/lib/cookie.h
:64:  ^3
: error: unknown type name 'bool'
  bool running;    /* state info, for cookie adding information */
  ^
note: previous definition is here
_STRUCT_TIMEVAL
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:29:40: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
../vendor/curl/lib/base64.c../vendor/curl/lib/cookie.h:94:53: :25error:
: In file included from unknown type name 'bool'
../vendor/curl/lib/curl_setup.h:713../vendor/curl/lib/cookie.h:66:3../vendor/curl/lib/cookie.h:: 66:3error::  unknownerror                                struct CookieInfo *, bool header, bool noexpiry,: type
 name unknown                                                    ^'bool'
type
 name 'bool'
:
../vendor/curl/lib/curl_setup_once.h  bool newsession; /* new session, discard session cookies on load */
  ^
  bool newsession; /* new session, discard session cookies on load */
  ^
:109:In file included from 8: error: redefinition of 'timeval'
../vendor/curl/lib/cookie.h:94:66: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                                 ^
../vendor/curl/lib/cookie.h:94:53: ../vendor/curl/lib/cookie.h:error94: :53:unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                    ^
 error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                    ^
../vendor/curl/lib/cookie.h:97:32: error: unknown type name 'bool'
3 errors generated.
                               bool secure);
                               ^
../vendor/curl/lib/cookie.h:94:66: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                                 ^
../vendor/curl/lib/cookie.h:94:66: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                                 ^
../vendor/curl/lib/cookie.h:97:32: error: unknown type name 'bool'
                               bool secure);
                               ^
../vendor/curl/lib/cookie.h:97:32: error: unknown type name 'bool'
                               bool secure);
                               ^
In file included from ../vendor/curl/lib/cookie.c:87:
In file included from ../vendor/curl/lib/urldata.h:84:
../vendor/curl/lib/formdata.h:28:3: error: unknown type name 'bool'
  bool name_alloc;
  ^
../vendor/curl/lib/formdata.h:31:3: error: unknown type name 'bool'
  bool value_alloc;
  ^
In file included from ../vendor/curl/lib/conncache.c:28:
In file included from ../vendor/curl/lib/urldata.h:84:
../vendor/curl/lib/formdata.h:28:3: error: unknown type name 'bool'
  bool name_alloc;
  ^
In file included from ../vendor/curl/lib/content_encoding.c:25:
In file included from ../vendor/curl/lib/urldata.h:84:
../vendor/curl/lib/formdata.h:28:3: error: unknown type name 'bool'../vendor/curl/lib/formdata.h
:34:3:   bool name_alloc;error
:   ^
unknown type name 'bool'
  bool contenttype_alloc;
  ^
../vendor/curl/lib/formdata.h:31:3: error: unknown type name 'bool'
  bool value_alloc;
  ^
../vendor/curl/lib/formdata.h:31:3: ../vendor/curl/lib/formdata.herror:: 40:3:unknown  type errorname:  'bool'unknown
 type name 'bool'  bool value_alloc;

  ^
  bool showfilename_alloc;
  ^
../vendor/curl/lib/formdata.h:34:3: error: unknown type name 'bool'
  bool contenttype_alloc;
  ^
../vendor/curl/lib/formdata.h:34:3: error: unknown type name 'bool'
make[1]: *** [obj/x64/Debug/curl/asyn-thread.o] Error 1  bool contenttype_alloc;

  ^../vendor/curl/lib/formdata.h
:40:3: error: unknown type name 'bool'make[1]: *** Waiting for unfinished jobs....

  bool showfilename_alloc;
  ^
struct timeval {
../vendor/curl/lib/formdata.h:40:3: error: unknown type name 'bool'
  bool showfilename_alloc;
  ^
In file included from ../vendor/curl/lib/connect.c:23:
In file included from ../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:174:3: error: unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
       ^
../vendor/curl/lib/curl_setup_once.h:174:42:../vendor/curl/lib/asyn-ares.c :23:
errorIn file included from : ../vendor/curl/lib/curl_setup.h:713expected/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h :
:';'34 :after1 ../vendor/curl/lib/curl_setup_once.h:top:  level109 :notedeclarator8: :
previous definitionerror : is here
redefinition of 'timeval'
_STRUCT_TIMEVAL
^
  Error Missing_definition_of_macro_sread
                                         ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h                                         ;:
29:40: struct timeval {
note:        ^
expanded from macro '_STRUCT_TIMEVAL'
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:34:1: #define _STRUCT_TIMEVAL         struct timevalnote
: previous                                       ^
definition is here
_STRUCT_TIMEVAL
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/_types/_timeval.h:29:40: note: expanded from macro '_STRUCT_TIMEVAL'
#define _STRUCT_TIMEVAL         struct timeval
                                       ^
In file included from ../vendor/curl/lib/base64.c:25:
In file included from ../vendor/curl/lib/curl_setup.h:713:
../vendor/curl/lib/curl_setup_once.h:174:3: error: unknown type name 'Error'
  Error Missing_definition_of_macro_sread
  ^
../vendor/curl/lib/curl_setup_once.h:174:42: error: expected ';' after top level declarator
  Error Missing_definition_of_macro_sread
                                         ^
                                         ;
In file included from ../vendor/curl/lib/connect.c:61:
In file included from ../vendor/curl/lib/urldata.h:82:
../vendor/curl/lib/cookie.h:37:3: error: unknown type name 'bool'
  bool tailmatch;    /* whether we do tail-matching of the domain name */
In file included from ../vendor/curl/lib/content_encoding.c:25:
In file included from ../vendor/curl/lib/urldata.h:98  ^:

../vendor/curl/lib/hostip.h:105:1: error: unknown type name 'bool'
In file included from ../vendor/curl/lib/cookie.c:87:
In file included from ../vendor/curl/lib/urldata.h:98:
bool Curl_ipvalid(struct connectdata *conn);
../vendor/curl/lib/hostip.h:^105
:1: error: unknown type name 'bool'
bool Curl_ipvalid(struct connectdata *conn);
^
../vendor/curl/lib/hostip.h:148:55: error: ../vendor/curl/lib/cookie.hunknown: 43type: 3name:  'bool'
../vendor/curl/lib/hostip.h:148:CURLcode Curl_once_resolved(struct connectdata *conn, bool *protocol_connect);55
: In file included from                                                       ^../vendor/curl/lib/base64.c
:error26: :
In file included from ../vendor/curl/lib/urldata.hunknown: 82type:
 name../vendor/curl/lib/cookie.h :'bool'37:3
: error: unknown type name 'bool'
CURLcode Curl_once_resolved(struct connectdata *conn, bool *protocol_connect);
                                                      ^
  bool tailmatch;    /* whether we do tail-matching of the domain name */
  ^
make[1]: *** [obj/x64/Debug/curl/altsvc.o] Error 1
error: unknown type name 'bool'
In file included from   bool secure;       /* whether the 'secure' keyword was used */../vendor/curl/lib/conncache.c:28:
In file included from ../vendor/curl/lib/urldata.h:98:
../vendor/curl/lib/hostip.h:105:1: error: unknown type name 'bool'
bool Curl_ipvalid(struct connectdata *conn);
^

  ^
In file included from ../vendor/curl/lib/asyn-ares.c:23:
../vendor/curl/lib/cookie.hIn file included from :../vendor/curl/lib/curl_setup.h43::7133:
: ../vendor/curl/lib/curl_setup_once.h:174error:: 3: unknown typeerror : name 'bool'unknown
type name 'Error'
  Error Missing_definition_of_macro_sread  bool secure;       /* whether the 'secure' keyword was used */

  ^  ^

../vendor/curl/lib/curl_setup_once.h:174:42: error: expected ';' after top level declarator../vendor/curl/lib/hostip.h:
148:55: error: unknown../vendor/curl/lib/cookie.h :type44 :name3 :'bool'   Error Missing_definition_of_macro_sread

error:                                          ^
unknown                                          ;type
 name 'bool'
CURLcode Curl_once_resolved(struct connectdata *conn, bool *protocol_connect);
                                                      ^
In file included from ../vendor/curl/lib/content_encoding.c:25:
In file included from   bool livecookie;   /* updated from a server, not a stored file */../vendor/curl/lib/urldata.h
:116:
  ^
../vendor/curl/lib/mime.h:71:59: error: unknown type name 'bool'
  size_t         (*encodefunc)(char *buffer, size_t size, bool ateof,
                                                          ^
In file included from ../vendor/curl/lib/cookie.c:87:
In file included from ../vendor/curl/lib/urldata.h:116:
../vendor/curl/lib/mime.h:71:59: error: unknown type name 'bool'
  size_t         (*encodefunc)(char *buffer, size_t size, bool ateof,
                                                          ^
../vendor/curl/lib/cookie.h:45:3: error: unknown type name 'bool'
  bool httponly;     /* true if the httponly directive is present */
  ^
../vendor/curl/lib/cookie.h:44:3: error: unknown type name 'bool'
../vendor/curl/lib/cookie.h:64:3: error: unknown type name 'bool'
  bool running;    /* state info, for cookie adding information */
  ^
  bool livecookie;   /* updated from a server, not a stored file */
  ^
../vendor/curl/lib/cookie.h:66:3:fatal error : tooerror : many errorsunknown  emitted,type  stoppingname  now'bool' In file included from
[-ferror-limit=]
  bool newsession; /* new session, discard session cookies on load */
  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
../vendor/curl/lib/conncache.c3 errors generated.
:28:
In file included from ../vendor/curl/lib/urldata.h:116:
../vendor/curl/lib/mime.h:71:59: error: unknown type name 'bool'
  size_t         (*encodefunc)(char *buffer, size_t size, bool ateof,
                                                          ^
../vendor/curl/lib/cookie.h:94:53: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                    ^
../vendor/curl/lib/cookie.h:94:66: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                                 ^
../vendor/curl/lib/cookie.h:97:32: error: unknown type name 'bool'
                               bool secure);
                               ^
../vendor/curl/lib/cookie.h:45:3: error: unknown type namefatal error : 'bool'too
 many errors emitted, stopping now [-ferror-limit=]
  bool httponly;     /* true if the httponly directive is present */
  ^
In file included from ../vendor/curl/lib/base64.c../vendor/curl/lib/cookie.h::2664:
:In file included from 3../vendor/curl/lib/urldata.h:: 84:
error../vendor/curl/lib/formdata.h: :28:unknown3 :type  name error'bool':
unknown type name 'bool'
  bool name_alloc;
  ^
  bool running;    /* state info, for cookie adding information */
  ^
../vendor/curl/lib/formdata.h:31:3: error: unknown type name 'bool'
  bool value_alloc;
  ^
../vendor/curl/lib/cookie.h:66:3: error: unknown type name 'bool'
../vendor/curl/lib/formdata.h:34:3: error: unknown   bool newsession; /* new session, discard session cookies on load */type
 name   ^'bool'

  bool contenttype_alloc;
  ^
../vendor/curl/lib/formdata.h:40:3: error: unknown../vendor/curl/lib/cookie.h :type94 :name53 :'bool'
error: unknown type name  bool showfilename_alloc;
'bool'  ^

                               struct CookieInfo *, bool header, bool noexpiry,
                                                    ^
../vendor/curl/lib/cookie.h:94:66: error: unknown type name 'bool'
                               struct CookieInfo *, bool header, bool noexpiry,
                                                                 ^
../vendor/curl/lib/cookie.h:97:32: error: unknown type name 'bool'
                               bool secure);
                               ^
In file included from ../vendor/curl/lib/connect.c:61:
In file included from ../vendor/curl/lib/urldata.h:84:
../vendor/curl/lib/formdata.h:28:3: error: unknown type name 'bool'
  bool name_alloc;
  ^
../vendor/curl/lib/formdata.h:31:3: error: unknown type name 'bool'
  bool value_alloc;
  ^
../vendor/curl/lib/formdata.h:34:3: error: unknown type name 'bool'
  bool contenttype_alloc;
  ^
../vendor/curl/lib/formdata.h:40:3: error: unknown type name 'bool'
  bool showfilename_alloc;
  ^
In file included from ../vendor/curl/lib/base64.c:26:
In file included from ../vendor/curl/lib/urldata.h:98:
../vendor/curl/lib/hostip.h:105:1: error: unknown type name 'bool'
bool Curl_ipvalid(struct connectdata *conn);
^
../vendor/curl/lib/hostip.h:148:55: error: unknown type name 'bool'
CURLcode Curl_once_resolved(struct connectdata *conn, bool *protocol_connect);
                                                      ^
make[1]: *** [obj/x64/Debug/curl/asyn-ares.o] Error 1
In file included from ../vendor/curl/lib/base64.c:26:
In file included from ../vendor/curl/lib/urldata.h:116:
../vendor/curl/lib/mime.h:71:59: error: unknown type name 'bool'
  size_t         (*encodefunc)(char *buffer, size_t size, bool ateof,
                                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
In file included from ../vendor/curl/lib/connect.c:61:
In file included from ../vendor/curl/lib/urldata.h:98:
../vendor/curl/lib/hostip.h:105:1: error: unknown type name 'bool'
bool Curl_ipvalid(struct connectdata *conn);
^
../vendor/curl/lib/hostip.h:148:55: error: unknown type name 'bool'
CURLcode Curl_once_resolved(struct connectdata *conn, bool *protocol_connect);
                                                      ^
In file included from ../vendor/curl/lib/connect.c:61:
In file included from ../vendor/curl/lib/urldata.h:116:
../vendor/curl/lib/mime.h:71:59: error: unknown type name 'bool'
  size_t         (*encodefunc)(char *buffer, size_t size, bool ateof,
                                                          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
20 errors generated.
20 errors generated.
20 errors generated.
make[1]: *** [obj/x64/Debug/curl/conncache.o] Error 1
make[1]: *** [obj/x64/Debug/curl/cookie.o] Error 1
make[1]: *** [obj/x64/Debug/curl/content_encoding.o] Error 1
make[1]: *** [obj/x64/Debug/curl/base64.o] Error 1
20 errors generated.
make[1]: *** [obj/x64/Debug/curl/connect.o] Error 1
make: *** [curl] Error 2
</pre></details>

Note that one of the errors are:

```c
../vendor/curl/lib/curl_setup_once.h:109:8: error: redefinition of 'timeval'
struct timeval {
       ^
```

My `config-mac.h` contains:

```c
/* Define to 1 if you have the timeval struct. */
#define HAVE_STRUCT_TIMEVAL 1
```

`curL_setup_once.h` has this near the error line:

```c
#ifndef HAVE_STRUCT_TIMEVAL
struct timeval {
 long tv_sec;
 long tv_usec;
};
#endif
```

So it's pretty clear that my `config-mac.h` is not being included. Elsewhere in our own project we use `__APPLE__` to differentiate and it works well without manually making any defines, so this patch seemed suitable to send upstream.

Note that `__APPLE__` is actually [used elsewhere](https://github.com/curl/curl/pull/3911/commits/430e9a62be38af6f98c3b85cf6bbbd21858daecf#diff-79d57801db5a903e43d284948f9c02e2L226) in that file and in the rest of your repository:

```
➜ ag -u __APPLE__
lib/timeval.c
78:#if defined(__APPLE__) && (HAVE_BUILTIN_AVAILABLE == 1)
85:#if defined(__APPLE__) && (HAVE_BUILTIN_AVAILABLE == 1)

lib/curl_setup.h
230:#ifdef  __APPLE__

➜ ag -u macintosh
lib/curl_setup.h
71:#if defined(macintosh) && defined(__MRC__)

➜ ag -u __MRC__
lib/curl_setup.h
71:#if defined(macintosh) && defined(__MRC__)
```

**Comment by bagder** [comment]
Are you using configure or cmake?

**Comment by qaisjp** [comment]
I'm using `./configure --disable-ipv6` on your latest release and then copying `curl_config.h` to our repo's `config-mac.h`.

(We use premake to build our project.)

> The point here is rather that `config-mac.h` is for macos 9 and earlier so you shouldn't use it at all...

Oh, I did not know that. Is there a particular reason why there is not an entry for macOS (X) or I am I free to send a pull request to update that?

**Comment by bagder** [comment]
Because no system that can run configure needs a pre-generated config file. macOS 10 is such a system. Your config ends up `lib/curl_config.h` after configure is done and that is where it belongs!

(I don't know premake nor how it works.)

**Comment by qaisjp** [comment]
> Because no system that can run configure needs a pre-generated config file. macOS 10 is such a system. Your config ends up `lib/curl_config.h` after configure is done and that is where it belongs!
> 
> (I don't know premake nor how it works.)

Okay. is this the same situation with cmake?

**Comment by bagder** [comment]
Yes.

**Comment by qaisjp** [comment]
Thanks!

**Pull request closed without merging**
