### PR TITLE
mesalink: implement client authentication

### PR DESCRIPTION
**Pull request by kevinis**
Hello again! This is the author of the MesaLink TLS project. I'd like to add client authentication to the MesaLink backend.

Btw, I need some help here to implement the tests as I can't find any cases in `tests/data` that test client authentication.

Thanks in advance!

### CODE REVIEW

**Comment by bagder** [comment]
I don't think we have any tests for that! We use stunnel to front the test servers and I can't see that it supports client certs...

**Comment by kevinis** [comment]
Is it OK to merge this PR without curl's tests? I have some tests done on my side shown here:
https://paste.ubuntu.com/p/p7vr8f87Pb

**Comment by bagder** [comment]
Sure, since this is functionality without test coverage and your changes are limited to the mesalink backend only, I think I think it is okay. Will merge!

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
