### PR TITLE
WIP: Test suite improvements to make testing external HTTP proxies more convenient

### PR DESCRIPTION
**Pull request by fabiankeil**
This patch set allows to specify an external HTTP proxy when executing runtests.pl
and adjusts some of the tests to make it less likely that they fail when using a HTTP
proxy.

The patches make it possible to use 389 of curl's HTTP tests with Privoxy as proxy.
Additionally I wrote a couple of Privoxy-specific tests and intend to ship them with
future Privoxy releases.

I previously submitted the patches in https://curl.se/mail/lib-2021-01/0068.html and
was asked to open a pull request. I've updated the weekday commit to include recently
added tests.

### CODE REVIEW

**Comment by bagder** [comment]
I'm missing documentation for the new options to `runtests.pl` - there's a `runtests.1` man page that should have them explained. Also, `tests/FILEFORMAT.md` should get extended somewhat too as well right?

I'm fine with the changes to runtests.pl as they seem fairly non-intrusive. One problem is probably that you're adding a bunch of options that aren't used by curl's test suite itself which make them very fragile and easily broken going forward. Maybe it would be good to add something that uses them to make sure they get exercised by the test suite?

**Comment by fabiankeil** [comment]
Thanks for the review.

I've added documentation to runtests.1 and mentioned the %TESTNUMBER
variable in tests/FILEFORMAT.md.

I started adding tests but it turns out that testing runtests.pl
with runtests.pl is tricky business.

I'm currently (mis)using the <precheck> (see test 1182 as an example) to setup the
expected files and directories but I'm not sure if that's the way to go.

The alternative seems to be to commit another directory tree that is suitable for
running the runtests.pl under test.

**Comment by fabiankeil** [comment]
> I'm currently (mis)using the (see test 1182 as an example) to setup the
> expected files and directories but I'm not sure if that's the way to go.

The word "precheck" got lost as I wrote it as tag ...

**Comment by bagder** [comment]
Thanks for your hard work on this. I squashed your commit series into a 10 larger commits, including one fix in the TESTNUMBER (after rebase) so let's keep an eye on things to make sure I didn't mess them up!

**Pull request closed without merging**
