### PR TITLE
multissl: make openssl + wolfssl builds work

### PR DESCRIPTION
**Pull request by vszakats**
- make colliding vtls static function names unique.
- wolfssl: stop including an unused compatibility header.
- cmake: adapt detection logic for openssl+wolfssl coexist.
- wolfssl: fix to use native wolfSSL API in ECH codepath.
- openssl+wolfssl: fix ECH code to coexist.

Requires a post wolfSSL v5.7.4, recent master for `OPENSSL_COEXIST`
feature, and `CPPFLAGS=-DOPENSSL_COEXIST`.

Ref: https://github.com/wolfSSL/wolfssl/issues/8194

---

- [x] finalize cutoff version for wolfSSL's `OPENSSL_COEXIST`. → separate PR
- [x] wait for wolfSSL release with coexist support. → separate PR
  then add logic to auto-enable `OPENSSL_COEXIST` for wolfSSL.
- [x] wait for vcpkg supporting that version. → separate PR
- [x] enable wolfSSL in the vcpkg MultiSSL job. → separate PR
- [x] perhaps merge #15650 into this PR? [MERGED ORGINAL PR]
- [x] finalize if the `OTHERNAME` and `MD5_CTX` collision workarounds
  are still necessary. → https://github.com/wolfSSL/wolfssl/pull/8216

### CODE REVIEW

**Comment by bagder** [comment]
You need wolfSSL from their git master still to do a combo-build with OpenSSL. I presume that will come proper in their next release.

**Comment by vszakats** [comment]
> You need wolfSSL from their git master still to do a combo-build with OpenSSL. I presume that will come proper in their next release.

Yes, I'm testing this with wolfSSL master. This clear the way for the wolfSSL feature when it's released.

**Comment by vszakats** [comment]
It seems the way we build wolfSSL in CI isn't going to be
compatible with "coexist" mode, nor will be any distros 
building it with `--enable-all`:
```
In file included from /path/to/wolfssl.git/_pkg/include/wolfssl/ssl.h:33:
/path/to/wolfssl.git/_pkg/include/wolfssl/wolfcrypt/settings.h:4239:6: error: "OPENSSL_ALL can not be defined with OPENSSL_COEXIST"
    #error "OPENSSL_ALL can not be defined with OPENSSL_COEXIST"
     ^
```
Such distros are Homebrew and Debian AFAIK.

**Comment by talregev** [comment]
wolfssl vcpkg have now ech feature. Can you check that it correct and work in the tests?

**Comment by talregev** [comment]
Can we add in the curl --version if the ech feature is working or not?

**Comment by vszakats** [comment]
> Can we add in the curl --version if the ech feature is working or not?

It's already there if enabled:
```
Features: [...] ECH [...]
```

**Comment by talregev** [comment]
> > Can we add in the curl --version if the ech feature is working or not?
> 
> It's already there if enabled:
> 
> ```
> Features: [...] ECH [...]
> ```

It not working, even wolfssl vcpkg is compile with:
What is missing?
```
      -DWOLFSSL_ECH=yes
      -DWOLFSSL_HPKE=yes
      -DWOLFSSL_SNI=yes
```
https://github.com/curl/curl/actions/runs/12034376811/job/33550798676?pr=15438#step:10:36

**Comment by talregev** [comment]
> > Can we add in the curl --version if the ech feature is working or not?
> 
> It's already there if enabled:
> 
> ```
> Features: [...] ECH [...]
> ```

We need add a curl flag to enable ech?

**Comment by talregev** [comment]
I now understand:
https://github.com/curl/curl/pull/15647

**Comment by vszakats** [comment]
> > > Can we add in the curl --version if the ech feature is working or not?
> > 
> > 
> > It's already there if enabled:
> > ```
> > Features: [...] ECH [...]
> > ```
> 
> We need add a curl flag to enable ech?

Yes, the two options already enabled for BoringSSL.

**Comment by vszakats** [comment]
I dropped the auto-enable logic from this PR and will open it separately once a stable wolfSSL release allows it.

It means this PR is ready to merge to fix remaining coexist issues and enable using it with compatible wolfSSL revisions.

**Pull request closed without merging**
