### PR TITLE
Create a separate profile for upgraded TLS connections in IMAP

### LINKED ISSUE #422: Connections upgraded with STARTTLS are not reused
As stated in title, upgraded connections are not reused.
Issue appears to be in [ConnectionExists](https://github.com/bagder/curl/blob/master/lib/url.c#L3232) of url.c. The check (needle->handler->protocol & check->handler->protocol) resolves to false because the handler was switched to Curl_handler_imaps in imap_to_imaps called from [imap_perform_upgrade_tls](https://github.com/bagder/curl/blob/master/lib/imap.c#L501).

Code to reproduce the issue: https://gist.github.com/ehlertjd/d10e4f050e40f77b448d
(you'll need credentials against a mail server running IMAP with STARTTLS)

Tested against 7.42.1, but appears to still be present in 7.44.0.

### PR DESCRIPTION
**Pull request by ehlertjd**
One possible way to fix #422

### CODE REVIEW

**Comment by captain-caveman2k** [comment]
@bagder Do we think this is an appropriate fix - to introduce a TLS upgrade profile?

@ehlertjd As Daniel mentioned the other STARTTLS protocols are going to suffer the same fate. I guess it will be simple enough to apply this fix to both SMTP and POP3 as well - are you able to do that if required? Also did you look at a more generic fix in url.c?

**Comment by ehlertjd** [comment]
Hi Steve,
I did briefly look at url.c but didn't feel that I had enough of an
understanding to make a change at that level. The upgrade profile seemed
like a simple localized fix for my own purposes, and I figured I'd at least
share.

If the upgrade profile approach is admissible, then I don't have a problem
making the change for other protocols, but it'd be nice (if possible) to
formulate a few positive and negative tests to avoid regression and I'd may
need some assistance (or at the very least a review of the first one) on
that front.

Regards,
Justin

**Comment by captain-caveman2k** [comment]
Hi Justin,

Your fix seems simple enough and I quite like your approach. The only thing I would recommend is splitting the refactoring of the existing function and the adding of the new profile into two separate commit.

As for fixing it in url.c - I think we would need to save the protocol flags before the upgrade and the compare that in ConnectionExists() if the current protocol flags contains TLS.

It would be good to add some tests like you suggested - the one thing I'm not sure about (even though I added a fair amount if the email tests) is how we simulate the TLS layer.

**Comment by ehlertjd** [comment]
Based on the check on [Line 3232 of url.c](https://github.com/bagder/curl/blob/master/lib/url.c#L3232) it seems like the original intent was to keep the same protocol identifier when upgrading via STARTTLS. Best I can tell, if we were to amend the check as you suggested, we either have to add an additional field to Curl_handler structure to indicate the pre-upgrade protocol, or we have to be able to map between secure & non-secure versions of protocol IDs for comparison. 

Alternatively, since protocol definitions are a bitmask, we could carry both on the protocol field, but that seems a bit wonky, and would still require creating a new "TLS" profile for each protocol.

For the moment I'll proceed with an attempt to reproduce the issue via unit test, let me know which approach seems best.

**Comment by ehlertjd** [comment]
It looks like [stunnel does support STARTTLS via configuration](http://www.stunnel.org/static/stunnel.html#protocol-PROTO) however I don't really know perl well enough to mess around with runtests.pl & secureserver.pl. I can make any of the changes suggested and test them manually, but I can't currently spare the time to figure out how to automate them.

**Comment by captain-caveman2k** [comment]
Alternative fix provided in commit a5aec58726.

**Pull request closed without merging**
