### PR TITLE
appveyor: make one of the winbuilds use DEBUG=no

### PR DESCRIPTION
**Pull request by bagder**
... and invoke "curl -V" once done

### CODE REVIEW

**Comment by bagder** [comment]
No, it's not on purpose (and it seems VC is not used for much within those makefiles). I always get totally confused by those VC versions...

**Comment by jay** [comment]
Why is this needed, DEBUG is off by default isn't it but why wouldn't you want it on? In any case I think it would be better to add DEBUG: to each winbuild image in the matrix with yes/no (I'm pretty sure it has to be lowercase not like cmake ON/OFF) so `DEBUG=%DEBUG%`. I pushed something like that to your branch, it turns on debug for VS2015 and off for VS2017.

> No, it's not on purpose (and it seems VC is not used for much within those makefiles). I always get totally confused by those VC versions...

The one Marcel is referring to is VS2015 which would be VC14. For VS2017 some people like VC15 but it doesn't make sense to me since there is no VC15. That's debatable though, see #2189 and https://en.wikipedia.org/wiki/Microsoft_Visual_C%2B%2B#Internal_version_numbering

**Comment by bagder** [comment]
> Why is this needed, DEBUG is off by default isn't it but why wouldn't you want it on?

I figured it would be more useful to have one build of each, to test more. #4522 triggered the idea for me.

**Comment by jay** [comment]
> > Why is this needed, DEBUG is off by default isn't it but why wouldn't you want it on?
> 
> I figured it would be more useful to have one build of each, to test more. #4522 triggered the idea for me.

Ok. Rather than vs2015 debug on and vs2017 debug off how about vs2017 for both?

**Comment by bagder** [comment]
> Rather than vs2015 debug on and vs2017 debug off how about vs2017 for both?

I also think there's value in verifying the winbuild setup for more than one VS version. Possibly we should add new builds and do two 2015 builds debug on/off **and** two 2017 builds debug on/off... They don't run any tests so they're fairly low impact.

**Pull request closed without merging**
