### PR TITLE
cmake: Fix build with GSSAPI

### LINKED ISSUE #3743: CMake: configure may fail when building with custom GSSAPI build
Configuring build of curl 7.64.1 with example command line like:
`cmake ../curl -DCMAKE_INSTALL_PREFIX=/work/curl-install  -DBUILD_TESTING=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_USE_GSSAPI=ON -DGSS_ROOT_DIR=/work/krb5-1.17-install -DCMAKE_USE_OPENSSL=OFF -DCMAKE_PREFIX_PATH:PATH=/work/krb5-1.17-install -DCURL_CA_PATH=none -G Ninja`

Fails when checking for `recv`. Error log reveals that it tries to link the Kerberos libraries, which is totally unnecessary.

PR will follow.

### PR DESCRIPTION
**Pull request by jzakrzewski**
This primarily fixes #3743

### CODE REVIEW

**Comment by jzakrzewski** [comment]
The coverage decrease seems to be false. Only CMake files changed and the coverage build is done with the autotools...

**Comment by jay** [comment]
I suggest squash
~~~
cmake: Fix build with GSSAPI

- Remove unneeded include_regular_expression

- Don't check for pre-3.0.0 CMake version

We already require at least 3.0.0, so it's just clutter

- etc

- etc

Close #xxxx
~~~~

**Comment by jzakrzewski** [comment]
@jay If that's how you want to have it - no problem. I was just trying to make one thing per commit (if not for the clear history, then at least for review).
I can squash it in the evening.

**Comment by snikulov** [comment]
@jzakrzewski you've just added more changes then required to solve #3743 :)
For me it's OK.
So go ahead if @jay have no objections.

**Comment by jzakrzewski** [comment]
Yeah, I've sneaked in some simple cleanup and my initial (but insufficient) solution using the `CMAKE_TRY_COMPILE_TARGET_TYPE`. The fixing commit is clearly marked though.
Personally I'd squash first 3 together and let others as-is. But in the end I don't really care that much and will do however the more experienced colleagues find better.

**Comment by jay** [comment]
> Personally I'd squash first 3 together and let others as-is.

Anything you want to leave separate please add `Ref: ` lines since they came from this PR.

**Comment by jzakrzewski** [comment]
Now it's hopefully nicer :)

**Comment by jay** [comment]
Yes it's better but I have some formatting suggestions for each:

<br>

`cmake: minor cleanup` indent without line break after bullet point may be autowrapped and treated as continuing a sentence. Please use periods in such a case and/or a line break.
~~~
- abcdefg

- qwerty.

- Remove unneeded include_regular_expression.

It was setting what is already a default.

- Remove unneeded include_regular_expression.

  It was setting what is already a default.

- Remove unneeded include_regular_expression.
  It was setting what is already a default.
~~~


<br>

`cmake: clear CMAKE_REQUIRED_LIBRARIES after each use` needs the purpose which is to fix the GSSAPI build.How you might do that:

~~~
cmake: Fix GSSAPI build

- clear CMAKE_REQUIRED_LIBRARIES after each use.

fixes #3743
closes #3744
~~~

~~~
cmake: clear CMAKE_REQUIRED_LIBRARIES after each use

This fixes the GSSAPI build which failed when checking for recv. Error
log reveals that it tries to link the Kerberos libraries, which is
totally unnecessary.

fixes #3743
closes #3744
~~~

<br>

`cmake: avoid linking executable for some tests with cmake 3.6+` needs line break between paragraphs and what it fixes, for example:
~~~
This commit also avoids #3743 (GSSAPI build errors) on itself with cmake
3.6 or above. That issue was fixed separately for all versions.
~~~

**Comment by jay** [comment]
Looking good. All the CI failures appear due to transient stalls and can be ignored. The coveralls 7% reduction in coverage doesn't make any sense to me.

**Pull request closed without merging**
