### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tuxiqae**

### CODE REVIEW

**Comment by tuxiqae** [comment]
Why was this PR closed? As you can see there's inconsistency regarding the naming of "Curl" in the readme.

**Comment by jay** [comment]
I don't think it's necessary. I'll reopen and someone else can take a look.

**Comment by danielgustafsson** [comment]
@jay is right, this is referring to the command-line tool curl and the correct capitalization is "curl"; so I'm closing this again as it's intentional.

**Comment by tuxiqae** [comment]
Thank you for the lengthy explanation.
Shouldn't the others need to be changed likewise?

**Comment by danielgustafsson** [comment]
> Thank you for the lengthy explanation.
> Shouldn't the others need to be changed likewise?

Thats entirely possible, I didn't study them to have a strong opinion yet but it sounds plausible. I don't think we have hard rules on this but in general I think of it as: lowercase only for the tool and library; capitalized is fine when talking about the Curl project.

**Comment by tuxiqae** [comment]
To be honest, I always though that it's supposed to be cURL, guess I was wrong all along

**Comment by danielgustafsson** [comment]
> To be honest, I always though that it's supposed to be cURL, guess I was wrong all along

You are not wrong at all, up until 2016 the official capitaliation was cURL but it was then changed in commit 27302abb9467f21a481fcc6b8eca53d34e04373b. There are still some leftovers to be found, but we've mostly moved to just using "curl" these days.

**Comment by tuxiqae** [comment]
TIL!

**Pull request closed without merging**
