### PR TITLE
CI: bump wolfSSH and wolfSSL

### PR DESCRIPTION
**Pull request by bagder**
- wolfSSH 1.4.18
- wolfSSL 5.7.4

### CODE REVIEW

**Comment by bagder** [comment]
The rennovate bot does not detect the wolfSSH version bumps for some reason.

**Comment by bagder** [comment]
The yaml complaint seems wrong since all I did was changed a version number, I did not change syntax?

**Comment by bagder** [comment]
The yamllnt output is also super cryptic:
~~~
  7:11      error    syntax error: mapping values are not allowed here (syntax)
~~~

Is that a bible verse? Line number? Column?

**Comment by vszakats** [comment]
> The yaml complaint seems wrong since all I did was change a version number, I did not change syntax?
> 
> @vszakats any idea?

One yaml entry looks like was reflowed by accident.

**Comment by bagder** [comment]
oh yes how weird

**Comment by bagder** [comment]
thanks, that was silly

**Pull request closed without merging**
