### PR TITLE
CURLOPT_MAXAGE_CONN: the maximum allowed age for connection reuse

### PR DESCRIPTION
**Pull request by bagder**
... and disconnection too old ones. The limit is right now set hardcoded
to 120 seconds. We can consider offering a configurable value in the
future.

### CODE REVIEW

**Comment by jay** [comment]
I suggest a ref to #3722 in your commit message since some discussion took place there.

**Comment by bagder** [comment]
I [elaborated on this change a bit on the mailing list](https://curl.haxx.se/mail/lib-2019-04/0040.html) and opened for feedback.

**Comment by bagder** [comment]
oops! :smile:

**Comment by pps83** [comment]
> I [elaborated on this change a bit on the mailing list](https://curl.haxx.se/mail/lib-2019-04/0040.html) and opened for feedback.

I think forcing it to 120s isn't ok for those who intentionally rely on `TCP_KEEPALIVE` an long living connections. IMO it should be configurable and set to some kind of reasonable value by default (120s seems ok).

**Comment by bagder** [comment]
As you can see in this patch set, it is now configurable and is at 118 seconds by default.

**Comment by bagder** [comment]
TCP KEEPALIVE is rarely helping beyond the first few minutes since the time here is usually limited by how long the remote server keeps the connection alive. That's commonly limited to a few minutes at the most.

**Pull request closed without merging**
