### PR TITLE
USE_WIN32_CRYPTO check removed to get USE_NTLM2SESSION set.

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
To fix NTLM fails #3041

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by bagder** [comment]
Had to revert this due to #3708

**Comment by MonkeybreadSoftware** [comment]
So we need a check for #ifdef USE_SSL?

**Comment by MarcelRaad** [comment]
Something like this maybe?

```diff
 lib/curl_ntlm_core.h | 4 +++-
 1 file changed, 3 insertions(+), 1 deletion(-)

diff --git a/lib/curl_ntlm_core.h b/lib/curl_ntlm_core.h
index 07ef5deae..cda6135bd 100644
--- a/lib/curl_ntlm_core.h
+++ b/lib/curl_ntlm_core.h
@@ -50,7 +50,9 @@
 /* Define USE_NTLM2SESSION in order to make the type-3 message include the
    NTLM2Session response message, requires USE_NTRESPONSES defined to 1 and a
    Crypto engine that we have curl_ssl_md5sum() for. */
-#if defined(USE_NTRESPONSES) && !defined(USE_WIN32_CRYPTO)
+#if defined(USE_NTRESPONSES) && \
+  (!defined(USE_WIN32_CRYPTO) || \
+    (defined(USE_SSL) && !defined(CURL_DISABLE_CRYPTO_AUTH)))
 #define USE_NTLM2SESSION
 #endif
 ```

**Comment by bagder** [comment]
Looks fine to me. @MonkeybreadSoftware will you amend the PR?

**Comment by MonkeybreadSoftware** [comment]
I changed commit, so lets see what is says.

**Comment by bagder** [comment]
That had a syntax error. Fix and try again?

**Comment by MonkeybreadSoftware** [comment]
Well, tests failed due to #if line broken into three lines.
Should we simply change to one line or will that cause trouble with other checks due to line length?

**Comment by bagder** [comment]
Yes, splitting an `#if` on multiple lines needs each line to end with a backslash (`\`) to indicate a continuation.

**Comment by MonkeybreadSoftware** [comment]
but that is exactly what the change above shows!?
Sorry, I am confused.

**Comment by bagder** [comment]
Look again at your commit: https://github.com/curl/curl/pull/3704/commits/d0a030e41c911900450a53a2a23435ee27407bd4 ... it has no backslashes on the end of the two lines that are continued.

**Comment by MonkeybreadSoftware** [comment]
I was looking at Marcel's diff above. Now I committed the change with the missing backslashes. Sorry.

**Comment by MonkeybreadSoftware** [comment]
and now?
Did this go into a release?

**Comment by bagder** [comment]
If it had, it would say so. It has just collected dust here...

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
