### PR TITLE
tls: remove "successful" messages about cert locations

### PR DESCRIPTION
**Pull request by bagder**
Pointless

### CODE REVIEW

**Comment by jay** [comment]
I think if there is an error setting locations then that is useful information.

**Comment by bagder** [comment]
> I think if there is an error setting locations then that is useful information.

Why is that useful knowledge when the user as asked to ignore the results of it?

**Comment by bagder** [comment]
We don't normally output the reverse of error messages in curl. If things work fine, that's the expected behavior. If it does not, we output errors. Unless there are details in the success that could be good to reveal.

I couldn't find any such details here that are good to know in the event of success.

**Comment by jay** [comment]
> Why is that useful knowledge when the user has asked to ignore the results of it?

It's not as simple as that. That code is part of a much larger block if(verifypeer) meaning you only see those verbose warnings if you have peer verification enabled and it can continue on using some other verification (iirc)

**Comment by bagder** [comment]
Yes, but that's an optimization missing. In OpenSSL land we no longer even try to load them if no verification is being done and we should do the same for wolfSSL to gain valuable time when the user obviously doesn't care anyway.

**Comment by jay** [comment]
I don't think we are on the same page. I'm talking specifically of removal of the verbose warnings when the code continues on error.

For example with OpenSSL we can import native CA certs in Windows in addition to the CA bundle. It could be peer verification is enabled and the native CA certs are imported but the CA bundle isn't due to error.

**Comment by bagder** [comment]
ok, I still don't like the messages but this is not the hill for me

**Pull request closed without merging**
