### PR TITLE
Disable h2 server push if not requested

### PR DESCRIPTION
**Pull request by ghedo**

### CODE REVIEW

**Comment by jay** [comment]
I'm unclear on whether the server can just push to us without acceptance, however if this is the case now that we have large windows by default this change might be helpful. There is aproblem with the way you implemented it because we have a global settings we don't expect to be modified, so say for example you change it in one multi and some other one subsequent or another thread needs it off.

Also settings[2].value = 1 doesn't read well and the index could change if it's modified later. I'd rather check for it or put it in a function like 
~~~c
if(data->multi->push_cb) {
  int i;
  for(i = 0; i < sizeof(settings)/sizeof(settings[0]); ++i) {
    if(settings[i].settings_id == NGHTTP2_SETTINGS_ENABLE_PUSH) {
      settings[i].value = 1;
    }
  }
}
or even easier to understand:
if(!data->multi->push_cb)
  add_setting(settings, NGHTTP2_SETTINGS_ENABLE_PUSH, 0);
then in add_setting check settings for that setting and if not found add it as 0
~~~

So I am not one of the http2 experts here but I think this would involve renaming settings to default settings and then giving each conn a copy of the default settings which it could then modify, then modifying those settings to disable push. or maybe just a make_settings() that contains all the defaults and modifies them based on whatever

**Comment by ghedo** [comment]
> I'm unclear on whether the server can just push to us without acceptance

Yes, the server can send any data until the client resets the stream, which libcurl does if there is no `push_cb`. However by that time the server might have sent some data already (which would be a waste IMO).

> we have a global settings we don't expect to be modified

Oh, right, I'm dumb.

The easier implementation I think would be to keep an empty array on the stack and populate it manually like nghttp does https://github.com/nghttp2/nghttp2/blob/master/src/nghttp.cc#L846

Which would also make it easier to add more user-defined settings in the future, if that ever is needed.

**Comment by jay** [comment]
well you could put the settings array in http_conn because more than one function needs access to it (Curl_http2_switched, Curl_http2_request_upgrade) and populate it similarly like populate_settings(httpc->settings)

**Comment by bagder** [comment]
Will you do a follow-up to this or should we close it until you or someone else takes another shot at it?

**Comment by ghedo** [comment]
@jay mind reviewing again?

**Comment by ghedo** [comment]
Also fixed the failing test now.

**Pull request merged**
