### PR TITLE
http: ignore invalid Retry-After dates

### PR DESCRIPTION
**Pull request by jay**
- If the Retry-After date is in the past then set the retry after time to 0 instead of a negative number.

Prior to this change, libcurl could set the retry after time to a negative number of seconds. That is not documented and may be unexpected by the user.

Closes #xxxx

### CODE REVIEW

**Comment by jay** [comment]
This change is causing test 1596 to fail. The test is for Retry-After timestamp parsing using a date in the past, so it expects CURLINFO_RETRY_AFTER to return a negative number.

https://github.com/curl/curl/blob/fb1883d2265ae5c7da13d226781d39d1b9c77980/tests/data/test1596#L15-L18
https://github.com/curl/curl/blob/fb1883d2265ae5c7da13d226781d39d1b9c77980/tests/libtest/lib1594.c#L52-L58

If there's no objection I will change the timestamp to something in the future.

**Review by bagder — APPROVED** [review]
Nice catch!

**Comment by testclutch** [comment]
Analysis of PR #15833 at [75b506f6](https://github.com/curl/curl/commit/75b506f661d64714fb97911cdbf19f1dad4a20ec):

[Test 1596 failed](https://github.com/curl/curl/actions/runs/12508210554/job/34895960142#check-step-9), which has NOT been flaky recently, so **there could be a real issue in this PR**.  Note that this test has failed in 94 different CI jobs (the link just goes to one of them).

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by jay** [comment]
Being able to set the retry-after date this far into the future (year 2036) also makes me wonder. Is there an upper limit on what an acceptable time should be? I didn't see one in the RFC but I would think after some number of hours it's long enough

**Comment by bagder** [comment]
>  I would think after some number of hours it's long enough

Agreed. Maybe cap it at 5 or 10 hours or so?

**Comment by jay** [comment]
I really don't know. I changed the max to 24 hours but did not document it so that we'll have some flexibility to change it in the future.

**Comment by jay** [comment]
I changed my mind and made it 6 hours. 6 hours seems like a long time. Would a server return a longer time?

**Comment by bagder** [comment]
Highly unlikely. And even if there is a single one out there doing this, I don't think trying a little too early every 6 hours can be considered abuse.

**Comment by dfandrich** [comment]
I could see a legitimate use case in a server using a longer time, like a day
(or even more), to get clients to retry after a scheduled maintenance.

**Comment by jay** [comment]
Ok. I agree that there may be legit use cases and also that it's acceptable to try again in a shorter period of time so I landed it unchanged with a 6 hour limit.

**Pull request closed without merging**
