### PR TITLE
CI/tests: enable test target on TravisCI for CMake builds

### PR DESCRIPTION
**Pull request by snikulov**
Added test-nonflaky target to CMake builds

Ref: #6052

### CODE REVIEW

**Comment by mback2k** [comment]
@snikulov can you try also enabling the suppression generation @bagder mentioned here: https://github.com/curl/curl/issues/6078#issuecomment-708663776, thanks!

**Comment by snikulov** [comment]
> @snikulov can you try also enabling the suppression generation @bagder mentioned here: [#6078 (comment)](https://github.com/curl/curl/issues/6078#issuecomment-708663776), thanks!

It's done [already](https://github.com/curl/curl/pull/6074/files#diff-1f60080c90c71a3a82f36386b67736521b1950ecd0488a0b24531b8ddd02d433R694).
Unfortunately, it shows no sign that it was enabled in TravisCI logs.  :confused:

**Comment by bagder** [comment]
That's so weird and I don't understand why we get no suppression rules shown. I propose we try adding one manually instead, here's [my attempt](https://gist.github.com/bagder/c51479a8017642da7e619e9a78750bfe):
~~~diff
diff --git a/tests/valgrind.supp b/tests/valgrind.supp
index 10b07314a..4aaeac5b4 100644
--- a/tests/valgrind.supp
+++ b/tests/valgrind.supp
@@ -1,5 +1,13 @@
+{
+  zstd_decompression-1.3.3
+  Memcheck:cond
+  fun:ZSTD_decompressStream
+  obj:/usr/lib/x86_64-linux-gnu/libzstd.so.1.3.3
+  fun:zstd_unencode_write
+}
+
 {
    libidn-idna_to_ascii-error
    Memcheck:Addr4
    fun:idna_to_ascii_4z
    fun:idna_to_ascii_8z

**Comment by mback2k** [comment]
> I also tried a configure build on ubuntu 18.04 with libzstd 1.3.3 on a local VM of mine, but I couldn't reproduce the valgrind issues there. open_mouth

Maybe the Windows version of libzstd contains different (#ifdef'ed) code that is causing the issue?

**Comment by bagder** [comment]
@mback2k: these valgrind reports happen on the two travis ubuntu 18.04 cmake builds...

**Comment by mback2k** [comment]
Ah, mixed up the various issues in my head.

**Comment by bagder** [comment]
@snikulov try rebasing this now on master and force-push. The valgrind problems should be suppressed now.

**Comment by bagder** [comment]
TESTFAIL: These test cases failed: 1014 1139 

Test 1139 fails because the cmake build doesn't create `docs/curl.1` so it can't check that the man page is correct. This should be fixed by making sure the file is created in this build as well, but a work-around could be to just disable test 1139 - it is being tested in other builds anyway.

Test 1014 looks like a more genuine problem in the cmake build. curl doesn't properly get IDN enabled in the build even though it found libidn2 present. I'll post a separate PR in a sec with fix(es).

**Comment by mback2k** [comment]
@snikulov Please rebase and force-push in order to re-run the tests after @bagder's fixes.

**Comment by snikulov** [comment]
> @snikulov Please rebase and force-push in order to re-run the tests after @bagder's fixes.

@mback2k done.

**Comment by snikulov** [comment]
@mback2k @bagder now travis CI tests are [green](https://travis-ci.org/github/curl/curl/builds/740947609). I've also disabled 1139 as noted above.

**Comment by bagder** [comment]
Excellent! :heart:

**Comment by bagder** [comment]
Thanks!

**Comment by mback2k** [comment]
Thanks!

**Pull request closed without merging**
