### PR TITLE
Updated Readme

### PR DESCRIPTION
**Pull request by H3RSKO**
Fixed typo on Readme:

Changed "web site" to "website"

### CODE REVIEW

**Comment by bagder** [comment]
How about doing a `git grep -i "web site"` and update several other references while you're at it?

**Comment by H3RSKO** [comment]
Updated every 'web site' in repo to 'website'.

**Comment by bagder** [comment]
I think you missed a few:
~~~
$ git grep -li "web site" | wc -l
14

**Comment by H3RSKO** [comment]
Sorry about that! I think I got them all now, although 'git grep -li "web site" | wc -l' is still showing 1.

**Comment by bagder** [comment]
Is that perhaps because you missed the uppercase "WEB SITE" in `README` ?

**Comment by H3RSKO** [comment]
That was it

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
