### PR TITLE
formdata: avoid "Argument cannot be negative" warning

### PR DESCRIPTION
**Pull request by bagder**
... when converting a curl_off_t to size_t, by using `CURL_ZERO_TERMINATED` before passing the argument to the function.

Detected by Coverity CID 1486590.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Isn't it? We're still passing -1 to `curl_mime_data` further down with:
```
888         else if(post->flags & HTTPPOST_BUFFER)
889           result = curl_mime_data(part, post->buffer,
890                                   post->bufferlength? post->bufferlength: -1);
```
It might be lack of caffeine speaking but aren't we properly handling -1 in the mime code?

**Comment by bagder** [comment]
Hm, yeah I need to rethink this change. In the morning! Thanks!

**Review by danielgustafsson — APPROVED** [review]
Aha! I missed the difference in parameter type last night, now I get it.

**Comment by bagder** [comment]
Yeah, the `curl_off_t` to `size_t` conversion with a negative value is what coverity (rightfully I think) complains about.

**Pull request closed without merging**
