### PR TITLE
Fix MinGW build

### PR DESCRIPTION
**Pull request by MarcelRaad**
Fixes some build errors and compiler warnings on original MinGW as well as MinGW-w64. See individual commits for details.

### CODE REVIEW

**Comment by bagder** [comment]
@MarcelRaad, should there have been one more algo #ifdef'ed? See this [mingw build failure from the push](https://curlbuild.uxnr.de/builders/curl_winssl_mingw_x86/builds/4382/steps/compile/logs/stdio).

**Comment by MarcelRaad** [comment]
@bagder That's apparently a typo in MinGW's Windows SDK, w32api. I have patched this locally in w32api as `CALG_TLS1PRF` is defined but unusable and the undefined `ALG_CLASS_DHASH` is `ALG_CLASS_HASH` in the original Microsoft Windows SDK.

We could #ifdef on original MinGW, but then users cannot just fix their w32api. But fixing the autobuilds is probably more important?

I've created a ticket here: https://osdn.net/projects/mingw/ticket/38391

**Comment by bagder** [comment]
> fixing the autobuilds is probably more important?

Yeah, I consider that fairly important and getting mingw fixed and deployed sounds like a potentially rather slow operation...

What about doing a local "kludge" with a comment explaining the reasoning and a date for when we can try to remove it again?

**Comment by MarcelRaad** [comment]
Strange, it works for me, but the autobuild still fails:
https://curl.haxx.se/dev/log.cgi?id=20180712040614-17491#prob3

@mback2k Could you tell me what this tester's w32api.h says about the version macros, please? Are `__W32API_VERSION`, `__W32API_MAJOR_VERSION`, `__W32API_MINOR_VERSION`, and `__W32API_PATCHLEVEL` defined?

**Comment by mback2k** [comment]
@MarcelRaad I guess your question above was answered within https://github.com/curl/curl/issues/2924, right? Or are there any issues remaining I could test now that my build environment is running again?

**Comment by MarcelRaad** [comment]
Everything is clear now, thanks @mback2k !

**Pull request closed without merging**
