### PR TITLE
getinfo: provide info which auth was used for HTTP and proxy

### PR DESCRIPTION
**Pull request by bagder**
CURLINFO_HTTPAUTH_USED and CURLINFO_PROXYAUTH_USED

Ref: #12668
Idea-by: Ganesh Viswanathan

- [X] initial implementation
- [X] document both options
- [X] make sure NTLM is reported on subsequent requests
- [X] properly tested
- [X] save exposing it in the curl tool for later

### CODE REVIEW

**Comment by genotrance** [comment]
Thank you for implementing this! I'm looking into incorporating the feature. Meanwhile, these doc links aren't working:

https://curl.se/libcurl/c/CURLINFO_PROXYAUTH_USED.html
https://curl.se/libcurl/c/CURLINFO_HTTPAUTH_USED.html

**Comment by bagder** [comment]
Oops. Thanks for pointing this out. There was a minor breakage on the site, but it should be fixed now and those URLs should work momentarily. :face_with_head_bandage:

**Comment by genotrance** [comment]
I just tested this out and looks like BASIC auth is incorrectly returning 0 instead of 1.

DIGEST and NTLM seem to work fine. I am unable to test the other auth mechanisms to verify those

**Comment by jay** [comment]
> I just tested this out and looks like BASIC auth is incorrectly returning 0 instead of 1.
> 
> DIGEST and NTLM seem to work fine. I am unable to test the other auth mechanisms to verify those

Please open an issue if you've spotted a bug

**Pull request closed without merging**
