### PR TITLE
netrc: replace fgets with Curl_get_line

### PR DESCRIPTION
**Pull request by bagder**
Make the parser only accept complete lines and avoid problems with overly long lines.

Reported-by: Hiroki Kurosawa

### CODE REVIEW

**Comment by fredericgermain** [comment]
For info, this PR was included in curl 7.86.0 shipped with MacOS Ventura 13.2 (MacOS Ventura 13.1 had curl 7.85.0).

But https://github.com/curl/curl/pull/9973 was not included on curl 7.86.0, so there is a bug about .netrc files not ending with newlines not being handled properly on mac venture 13.2.

**Comment by bagder** [comment]
That sounds like an Apple problem.

**Comment by fredericgermain** [comment]
When I compile 7.86.0 on linux, there is this problem. it's a curl 7.86.0 problem.

**Comment by bagder** [comment]
Sure, which is why we fixed the problem and included that in an update.

**Pull request closed without merging**
