### PR TITLE
tool_operate: resume at last byte when retrying

### LINKED ISSUE #1084: curl throws away partial downloads on retry, even if told to resume
Say I want to download a large file, 1 GiB perhaps. I specify `-O`.
My network connection isn't very reliable, so I specify `-m` and `--retry`, so it doesn't hang up.

The problem is, on every retry, the output file is truncated, effectively throwing away all the work so far.
```
Warning: Transient problem: timeout Will retry in 1 seconds. 5 retries left.
Throwing away 327962289 bytes
```
This is wasteful, and makes `--retry` quite useless.
At least, if `-C -` is specified, it's pretty clear the user wants to _always_ resume automatically.

The workaround is to either not to use `--retry` & shell-wrap `curl` in a `for` loop, or to use `wget`.

Relevant [source](https://github.com/curl/curl/blob/8e8afa82cbb629bd2a95eba1cdf47f65dd62a6d5/src/tool_operate.c#L1521), for anyone interested.

---
curl 7.50.3

### PR DESCRIPTION
**Pull request by agners**
If continue/resume is enabled, try to also resume when retrying due to
transient connection problems.

Closes #1084

Note: Since I am not familiar with the code base this might not be a proper solution... It seems to work on a unreliable http connection here when using "--continue-at - --speed-limit 1024 --speed-time 4 --retry 10".

### CODE REVIEW

**Comment by bagder** [comment]
> If continue/resume is enabled

Should this really require that you have resume enabled? I would imagine that most cases where you want to download something, and you allow curl to retry a failure, you would prefer to have it continue at the breakage point rather than restart from the beginning - even if you didn't ask for a resumed transfer to begin with.

This logic should then probably make sure that the transfer is actually *downloading* something instead of checking for resume.

**Comment by NightMachinary** [comment]
What should I put in my .curlrc to make this work by default? I never use curl myself, a lot of tools use it internally.

**Comment by falstaff84** [comment]
@bagder Yeah we kind of (miss)use the resume flag to control behavior in the retry case, it is not ideal. I was just thinking it would be nice to have a way to control this new feature (maybe it might cause problems for somebody?).

**Comment by falstaff84** [comment]
@NightMachinary I guess just `--continue-at -` and `--retry xx`

**Comment by bagder** [comment]
> I was just thinking it would be nice to have a way to control this new feature

I appreciate that concern as we certainly need to make sure we don't break people's scripts or expectations, but in this case I would rather expect this to actually *improve* a bunch of scripts transparently if we don't require something else to be set. At least I think it is worth exploring before we take the cautionary route!

**Comment by falstaff84** [comment]
Updated this pull request. This time resuming is tried unconditionally for http(s). I tested this with an Apache server which does not support the HTTP range request (using `RequestHeader unset Range`) and throttled speed to artificially cause retries.

This shows that in case resuming fails, curl will fall back to the old mode (retry from beginning)
```
$ curl --speed-limit 100000 --speed-time 5 --show-error --connect-timeout 10 --retry 10 http://localhost/test -o /tmp/test 
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 20.0M    1  303k    0     0  61924      0  0:05:39  0:00:05  0:05:34 60788
Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
Continuing at 311108 bytes
  0 20.0M    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Warning: Transient problem: HTTP error Will retry in 2 seconds. 9 retries 
Warning: left.
Throwing away 311108 bytes
  1 20.0M    1  306k    0     0  61945      0  0:05:39  0:00:05  0:05:34 61477
Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
Throwing away 314004 bytes
  0 20.0M    0  155k    0     0  62823      0  0:05:34  0:00:02  0:05:32 62798
```

However, if range seems to work, it will continue to resume from the last byte on every retry:
```
$ curl --speed-limit 100000 --speed-time 5 --show-error --connect-timeout 10 --retry 10
http://localhost/test -o /tmp/test
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  1 20.0M    1  371k    0     0  61817      0  0:05:39  0:00:06  0:05:33 60436
Warning: Transient problem: timeout Will retry in 1 seconds. 10 retries left.
Continuing at 380612 bytes
  1 19.6M    1  299k    0     0  50778      0  0:06:46  0:00:06  0:06:40 60068
Warning: Transient problem: timeout Will retry in 2 seconds. 9 retries left.
Continuing at 687316 bytes
  1 19.3M    1  300k    0     0  61226      0  0:05:31  0:00:05  0:05:26 61068
Warning: Transient problem: timeout Will retry in 4 seconds. 8 retries left.
Continuing at 995468 bytes
100 19.0M  100 19.0M    0     0  13.9M      0  0:00:01  0:00:01 --:--:-- 13.9M```
```

**Comment by boonlert788** [comment]
ho.see.monney.in.mybank.acout.
to day. not. Slell. 10.hr
howlong. Click4mount. ago
Press. I. dontneed.tomuch.monney
Can.give.me.up.toyou.

**Comment by bagder** [comment]
Abandoned. Closing.

**Comment by agners** [comment]
Still interested get this upstream, we carry a patch downstream... Unfortunately I don't remember exactly why this got stuck.

**Comment by bagder** [comment]
Ok, great! Reopening. The tests in this PR are still not green so I've been waiting for those to get worked on.

**Comment by bagder** [comment]
I'd suggest a rebase and a force-push too since it now conflicts with git master.

**Comment by bagder** [comment]
This PR is abandoned and the idea of resuming on retry is already [mentioned in the TODO](https://curl.haxx.se/docs/todo.html#retry_should_resume). Closing.

**Pull request closed without merging**
