### PR TITLE
progress.c: Fixed download/Upload speed is not accurate.

### PR DESCRIPTION
**Pull request by julian0427**
Closes https://github.com/curl/curl/issues/2200

### CODE REVIEW

**Comment by bagder** [comment]
An alternative to using double for the calculation (which I tried to get rid of before), could be to make 'timespent' be number of centiseconds or maybe milliseconds, so that the calculation would be more accurate for sub second transfers without using floating point.

**Comment by julian0427** [comment]
Bagder, I see your alternative way but it is not accurate enough. Could you have a check on issue #2200 please?  This commit is to fix that issue.

**Comment by bagder** [comment]
> it is not accurate enough

It can still be done with high enough accuracy. Down to milliseconds should be enough as anything beyond that is likely to vary on other factors anyway. See #2206 as a first shot at what I mean.

**Comment by julian0427** [comment]
Bagder, got it, thanks.

**Pull request closed without merging**
