### PR TITLE
cookies: only save the cookie file if the engine is enabled

### PR DESCRIPTION
**Pull request by bagder**
Follow-up to 8eddb8f4259.

If the cookieinfo pointer is NULL there really is nothing to save.

Without this fix, we got a problem when a handle was using shared object
with cookies and is told to "FLUSH" it to file (which worked) and then
the share object was removed and when the easy handle was closed just
afterwards it has no cookieinfo and no cookies so it decided to save an
empty jar (overwriting the file just flushed).

Test 1905 now verifies that this works.

Assisted-by: Michael Wallner

### CODE REVIEW

**Comment by bagder** [comment]
@MarcelRaad or @jay, do you think you can help me out with this branch and see if you can tell me why the new test 1905 crashes on windows? All analyzer and travis jobs seem ok with the patch, but still this is what the [appveyor log](https://ci.appveyor.com/project/curlorg/curl/builds/22662179/job/va8pwb9xm3laur2r#L7979) says:
~~~
test 1905...[CURLOPT_COOKIELIST set to "FLUSH" of a shared cookie object]
sh: line 1:   256 Segmentation fault      ./libtest/lib1905 http://127.0.0.1:8990/we/want/1905 > log/stdout1905 2> log/stderr1905

**Comment by MarcelRaad** [comment]
I'll have a look.

**Comment by MarcelRaad** [comment]
With MinGW, the test fails because of line endings, but there is no crash. Trying with MSVC now.

**Comment by bagder** [comment]
aaah yes, I must mark the cookie file as `mode="text"` in the test file ...

**Comment by MarcelRaad** [comment]
I've finally managed to debug it. It took so long because of the tests only being able to run from an MSYS shell, but GDB not recognizing MSVC's debug info format.

The crash happens in `curl_multi_fdset`:
https://github.com/curl/curl/blob/6ee671fc6af1cc9cf619af096ce88cf82ee131b1/lib/multi.c#L969
`i` is 0, and `write_fd_set` looks very broken: `fd_count` is 3435973836 and every element in `fd_array` is 14757395258967641292 (same for the other `fd_set`s). `*max_fd` is -858993460.

**Comment by bagder** [comment]
Thanks, what a rookie mistake. I'll push a fix asap.

**Pull request closed without merging**
