### PR TITLE
WIP: Run test feature determination on client

### PR DESCRIPTION
**Pull request by foopoiuyt**
Run the server/disabled and curl -M feature determination on the test
client rather than test host.
Use angle brackets in scalar context rather than single iteration loop on curl -M response.

### CODE REVIEW

**Comment by bagder** [comment]
Test 1026 failed on a single build on travis, one that disables a lot of features so worth double-checking.

**Comment by foopoiuyt** [comment]
What's interesting is that test looks to depend only on the manual feature which doesn't appear to be disabled on that run. It seems like none of the expected files are there though, as the log shows a
`== Contents of files in the log/ dir after test 1026`
with no followup content which is presumably why the postcheck looking for the manual is failing.

I'm trying to get that to reproduce the failure.

**Comment by bagder** [comment]
I tried to reproduce with your branch and the same configure line but failed. Rerunning that job now to see what happens.

**Comment by jay** [comment]
test 1026 is still [failing in postcheck](https://github.com/curl/curl/blob/curl-7_67_0/tests/data/test1026#L28-L32), this can't move forward until that's addressed.

**Comment by bagder** [comment]
Half a year without activity, closing.

**Pull request closed without merging**
