### PR TITLE
travis: build with iconv enabled

### PR DESCRIPTION
**Pull request by bagder**
... to verify it builds and works fine.

Ref: https://curl.haxx.se/mail/lib-2017-09/0031.html

### CODE REVIEW

**Comment by monnerat** [comment]
> $ export CPPFLAGS=\\
> $ export DCURL_ICONV_CODESET_OF_HOST='\\"ISO8859-1\\"'

... missed again :-(

**Comment by frenche** [comment]
@bagder did you figure the error at getinfo.c:420:17 ?
I got the same on my PR and I can't figure what triggered it.

error: passing an object that undergoes default argument promotion to 'va_start' has undefined behavior

**Comment by MarcelRaad** [comment]
@frenche That's a false positive clang warning which only appears in version 3.9:
https://bugs.llvm.org/show_bug.cgi?id=29140
Maybe we should disable that warning for version 3.9.

**Comment by bagder** [comment]
Yes, it seems we need to inhibit that warning on clang 3.9. Otherwise this will annoy us quite a lot...

**Comment by bagder** [comment]
Squashed a little, rebased and now features `-Wno-varargs` on clang debug builds...

**Comment by frenche** [comment]
Thanks @MarcelRaad for the explanation, and thanks @bagder for the fix :)

**Comment by MarcelRaad** [comment]
@bagder Perhaps you could check for version >= 3.9 and < 4.0 instead of only >= 3.9? It's been fixed in 4.0 (present in 3.9.0 as well as 3.9.1). Being able to diagnose undefined behavior at compile time is pretty cool, I think :-)

**Comment by bagder** [comment]
good point, I'll fix that and cherry-pick that fix into master, then rebase this

**Comment by bagder** [comment]
okay, the current red travis builds are actual test case failures that appear to be either bugs in curl with codeset conversion enabled, or they're bugs in the test cases. I believe each one needs to be researched individually to see where we need to fix or possibly even if the test needs to be disabled for this build setup.

**Comment by bagder** [comment]
Putting this on hold.

**Comment by monnerat** [comment]
Problem with test 545 resolved by commit https://github.com/curl/curl/commit/d3db7bc72ddac249672d737906e98642b2952370.

Identified problem with test 555: when character conversion is enabled, data ends in CRLF instead of LF.
This is already fixed by a strippart, but the content length mismatches.

How would you fix it:

- Always send data ending with CRLF.
- Ignore Content-Length (multiple occurrences) with a strippart.
- Something else ?

**Comment by bagder** [comment]
I would pick one of your first two alternatives, yes. The one that makes most sense for what is being tested. When it is a libcurl test there's also the option to add more logic to the C code that can be #ifdef'ed or otherwise made conditional.

**Comment by monnerat** [comment]
Test 555 fixed a third way by commit https://github.com/curl/curl/commit/bd5b9e50ce10e75048c3f584b2c7784d31504f0c.

I have preferred droping the conversion stuff in this test because it is not its target. The iconv travis job should succeed now.

However there is a real mess for the Content-Type calculation when using CURLOPT_POSTFIELDSIZE + CURLOPT_TRANSFERTEXT/CURLOPT_CRLF and I raise a red flag about it. Should probably be the subject of an issue and additional tests.

In addition, doc says CURLOPT_TRANSFERTEXT is for FTP only, while it also acts on http data (in transfer.c, so maybe other protocols) when CURL_DOES_CONVERSION is enabled.

Please not also that with charconv enabled, a single LF is uploaded as CRCRLF if CURLOPT_TRANSFERTEXT and CURLOPT_CRLF are both enabled.

There may be more undiscovered oddities around that...

**Comment by bagder** [comment]
Rebased and pushed again.

**Pull request closed without merging**
