### PR TITLE
GHA/windows: add GnuTLS to MSVC jobs

### PR DESCRIPTION
**Pull request by vszakats**
- enable GnuTLS in MultiSSL job.

- add new GnuTLS job with HTTP/3 enabled.
  Replacing the `!ssl` job.
  Use `Release` mode to work around a vcpkg package issue, ending up
  depending on both the debug and release versions of the gnutls DLL,
  one of them miss to copy next to the binary.

- cmake: add `pkg-config` detection for GnuTLS.

Co-authored-by: Tal Regev
Fixes #14494

### CODE REVIEW

**Comment by vszakats** [comment]
@talregev There is an issue with GnuTLS + ngtcp2 which looks vcpkg-related:

When building in Debug mode, `curl.exe` gets linked with `gnutlsd.dll`
(the debug GnuTLS DLL), plus `ngtcp2.dll`. Which in turn pulls in
`ngtcp2_crypto_gnutls.dll`, which in turn pulls in the _release_ version
of `gnutls.dll`. This release mode DLL is not copied automatically next to
`curl.exe`, so it fails to launch.

**Comment by talregev** [comment]
> @talregev There is an issue with GnuTLS + ngtcp2 which looks vcpkg-related:
> 
> When building in Debug mode, `curl.exe` gets linked with `gnutlsd.dll` (the debug GnuTLS DLL), plus `ngtcp2.dll`. Which in turn pulls in `ngtcp2_crypto_gnutls.dll`, which in turn pulls in the _release_ version of `gnutls.dll`. This release mode DLL is not copied automatically next to `curl.exe`, so it fails to launch.

Thank you for investigating the problem.
I will report for this. 
I have a workaround. To identify the gnutls via pkg config and then it takes the correct dlls.

**Comment by vszakats** [comment]
@talregev The patch from #14494 did not help with the GnuTLS DLL issue. I believe it works in #14494 because it doesn't enable `USE_NGTCP2`, while this one does. I'm going back to the 'Release' mode workaround.

**Comment by talregev** [comment]
@dg0yt I want to report this on vcpkg

**Comment by talregev** [comment]
> @talregev The patch from #14494 did not help with the GnuTLS DLL issue. I believe it works in #14494 because it doesn't enable `USE_NGTCP2`, while this one does. I'm going back to the 'Release' mode workaround.

@vszakats what is your 'Release' mode workaround?

**Comment by dg0yt** [comment]
> There is an issue with GnuTLS + ngtcp2 which looks vcpkg-related:
> 
> When building in Debug mode, `curl.exe` gets linked with `gnutlsd.dll` (the debug GnuTLS DLL), plus `ngtcp2.dll`. Which in turn pulls in `ngtcp2_crypto_gnutls.dll`, which in turn pulls in the _release_ version of `gnutls.dll`. This release mode DLL is not copied automatically next to `curl.exe`, so it fails to launch.

Cf. https://github.com/microsoft/vcpkg/issues/40414#issuecomment-2284537159
TLDNR: There is a mismatch of `FindGnuTLS.cmake` search parameters and actual lib names in shiftmedia-gnutls. Must be fixed in the `shiftmedia-gnutls` vpckg port.

**Comment by vszakats** [comment]
> > @talregev The patch from #14494 did not help with the GnuTLS DLL issue. I believe it works in #14494 because it doesn't enable `USE_NGTCP2`, while this one does. I'm going back to the 'Release' mode workaround.
> 
> @vszakats what is your 'Release' mode workaround?

Building in 'Release' mode instead of 'Debug' makes it link to the release `gnutls.dll` only, which also gets correctly copied next `curl.exe` and makes is launch as expected.

**Comment by talregev** [comment]
@vszakats I think it better to add this PR, instead this https://github.com/curl/curl/pull/14494

**Comment by vszakats** [comment]
@talregev Yeah, make sense, let's do it this way!

**Pull request closed without merging**
