### PR TITLE
Delete plain README because Markdown is better

### PR DESCRIPTION
**Pull request by Time-dragon**
There was no template, so I did this.

### CODE REVIEW

**Comment by bagder** [comment]
The plain `README` is what is included in tarballs and releases. When I read the plain one and compare the markdown as plain text like with less or with a text editor, I find the plain one *much* easier to read. The markdown one is too polluted with badges etc. I don't see the need to remove this file. I think it serves a purpose.

**Comment by danielgustafsson** [comment]
> On 21 Jun 2021, at 23:26, Daniel Stenberg ***@***.***> wrote:

> I don't see the need to remove this file. I think it serves a purpose.


+1

**Comment by Time-dragon** [comment]
> On 21 Jun 2021, at 23:26, Daniel Stenberg ***@***.***> wrote: I don't see the need to remove this file. I think it serves a purpose.
> +1

-1

**Comment by xquery** [comment]
The commonality between most common document formats (org-mode, asciidoc, docbook, html, plain ole xml, including Markdown) is that they are all based on plain ole text ... we avoid forcing a document format choice on users by supplying the README as plain ole (UTF8) text. 

Markdown may be a superior document format but as you have not given any rationale why it is better (or needed) over plain ole UTF8 text I think we should keep README.

**Comment by bagder** [comment]
Thanks, but no thanks!

**Comment by Time-dragon** [comment]
> Thanks, but no thanks!

Go delete this organization.

**Pull request closed without merging**
