### PR TITLE
Use correct buffer sizes for OpenSSL error messages

### PR DESCRIPTION
**Pull request by mkauf**

### CODE REVIEW

**Comment by bagder** [comment]
I think the more important change here is that you changed to using `SSL_strerror` instead of `ERR_error_string`. Why? The former function seems to be completely undocumented? When was that introduced? Is it meant to work the same way as ERR_error_string?

**Comment by mkauf** [comment]
`SSL_strerror` is an internal libcurl function, implemented in lib/vtls/openssl.c :-)
It's a wrapper for OpenSSL's `ERR_error_string_n`

**Comment by bagder** [comment]
Hah, look at that. I totally blanked on that... thanks!

**Comment by bagder** [comment]
We should probably rename it to not use a "SSL_" prefix as some OpenSSL functions use that.

**Comment by bagder** [comment]
thanks!

**Pull request closed without merging**
