### PR TITLE
docs/INSTALL: refer mingw users to invoke configure

### PR DESCRIPTION
**Pull request by bagder**
Remove Makefile.dist from the repository and the dist tarball.

Ref: #8705

### CODE REVIEW

**Comment by jay** [comment]
I'm fine with this but I'll defer to Viktor since he's using it in curl-for-win.

**Comment by mnaser** [comment]
recheck

**Comment by vszakats** [comment]
This will make it more difficult to launch `Makefile.m32`-based builds, and curl-for-win scripts will have to be updated accordingly (looks to be a simple update). It seems this build method becomes even more niche after this point. I still prefer it over autotools/cmake, but it'd seem even more urgent to switch to one of these mainstream ones. Any patch or help would be more than welcome here. (I had one try and fail with cmake in the past.)

**Comment by bagder** [comment]
Nah sorry, I misunderstood and thought this wasn't used. Since it is actually in use, I don't feel a need to rush this now.

**Pull request closed without merging**
