### PR TITLE
Create CITATION.cff

### PR DESCRIPTION
**Pull request by oliver-peoples**
I've written a couple reports and internal research papers which frequently reference curl. I have my own bibtex file I use, but I thought it would be useful to add a standard CITATION.cff one.

### CODE REVIEW

**Comment by bagder** [comment]
I presume this is the format: https://citation-file-format.github.io/

I think it's a bad idea to put this file in the source tree root, for a single reason: it needs to be updated at least for every release if not more often - depending how the list of authors is done. It would be much better to have it automatically generated and made available on curl.se. The format page does however seem to indicate that the file should rather be in the source code repo which saddens me.

**Comment by emilengler** [comment]
> I think it's a bad idea to put this file in the source tree root, for a single reason: it needs to be updated at least for every release if not more often - depending how the list of authors is done. It would be much better to have it automatically generated and made available on curl.se. The format page does however seem to indicate that the file should rather be in the source code repo which saddens me.

I think we should only go with @bagder as the author and an `et al.`, as it is the case with the man-page and the COPYING file. This is because there is no fair way to determine when someones name should appear within that `CITATION.tff` file. By the number of commits? Unfair, because a single commit that changes hundreds of lines may have a deeper impact on the copyright than 100 commits where each of them just fixes a single typo. By the maintainer status? Unfair, because former maintainers and contributors who made more contributions than other maintainers are excluded then.

**Comment by bagder** [comment]
Anyone who wants to reference curl should reference [curl.se](https://curl.se/), not the GitHub repository URL.

**Review by bagder — CHANGES_REQUESTED** [review]
As commented

**Comment by bagder** [comment]
No response, closing

**Pull request closed without merging**
