### PR TITLE
test2100: make it run with and require IPv6

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
Not good enough apparently...

**Comment by msigoo33** [comment]
- [ ] Go

**Comment by emilengler** [comment]
Are you sure you want to commit a binary file or is GitHub just being silly?

**Comment by bagder** [comment]
It's the same test2100 file as before, just slightly edited. It really isn't a binary file, it is a text file with some small pieces of binary content embedded.

We *can* probably avoid this git/github problem by switching to the `%hex[]%` format for the test but I just haven't bothered to do it...

**Pull request closed without merging**
