### PR TITLE
nss: fix build after e60fe20fdf94e829ba5fce33f7a9d6c281149f7d

### PR DESCRIPTION
**Pull request by MarcelRaad**
Curl_llist_alloc is now Curl_llist_init.

### CODE REVIEW

**Comment by bagder** [comment]
Ouch, I had totally not done my homework properly there! I presume this can run the test suite fine after this change? Our travis jobs unfortunately don't do enough different-TLS tests.

**Comment by MarcelRaad** [comment]
> I presume this can run the test suite fine after this change?

I'm currently running it on Linux and MinGW, will know tomorrow morning.

> Our travis jobs unfortunately don't do enough different-TLS tests.

Yes, this is exactly why I thought I should try a different one today :-)

**Comment by MarcelRaad** [comment]
> I'm currently running it on Linux and MinGW, will know tomorrow morning.

Almost all of the 6xx failed, but from a cursory look, it seems unrelated.

**Comment by kdudka** [comment]
Looks good to me.  Thanks!

**Comment by MarcelRaad** [comment]
Thanks for the reviews!

**Pull request closed without merging**
