### PR TITLE
psl: use latest psl and refresh it periodically

### PR DESCRIPTION
**Pull request by monnerat**
The latest psl is cached in the multi or share handle. It is refreshed before use if its time to live has expired.
New option CURLOPT_PSL_TTL sets the associated psl cache life time.
New share lock CURL_LOCK_DATA_PSL controls the psl cache sharing.
Using a custom PSL is not (yet) supported.
I've set the default TTL to 1 hour.
I've deliberately not conditioned psl code compilation to cookies or http since it may be used for other purpose in the future.
There's no test yet, as I do not see how to check this.
I would appreciate a deep review and comments. Thanks in advance.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks a lot for working on this! (You might want to mark this as `fixes #2553`)

First some comments on the general approach: I question 1) the usefulness of the TTL option and 2) the very low default TTL.

1 - It feels like one of these options where users really won't have the faintest idea what to put here, and so far they've managed with an infinite TTL. I'm not even sure we need a TTL, but if we assume that there are applications that never exits and just keep on running forever I can see the point.

2 - Even the browsers tend to ship with hard-coded PSL lists so they're on a like 6-8 weeks TTL *at least*. I think a sensible TTL would be at least 24 hours. Possibly even 72 or something (which then basically makes 99.99% of applications never have to reload the PSL).

**Comment by monnerat** [comment]
> Thanks a lot for working on this! (You might want to mark this as fixes #2553)

You're welcome. In this PR's commit, there is Ref: 2553: this will be changed to `Fixes` in the final commit.

1 - The key point about TTL is: when someone installs a new PSL, (s)he might want to see the results ASAP. This option allows forcing a quick update. Maybe this should be replaced by some CURLOPT_REFRESH_PSL one-shot option.

2 - I've set the default TTL arbitrarily (not too long, not too short) because I had to set something. Of course your advice about it counts.

**Comment by bagder** [comment]
Btw, the distcheck CI test fails because `CURLOPT_PSL_TTL.3` is not in the dist.

> The key point about TTL is: when someone installs a new PSL, (s)he might want to see the results ASAP. This option allows forcing a quick update. Maybe this should be replaced by some CURLOPT_REFRESH_PSL one-shot option.

I don't think that's reason enough to reload the same file every hour. An application that really wants to forcibly reload a new PSL could just close and re-init the handle...

**Comment by monnerat** [comment]
OK, I'll remove CURLOPT_PSL_TTL, and set a fixed ttl of 72 hours.
Do you want a CURLOPT_REFRESH_PSL option ?

**Comment by bagder** [comment]
I don't think we need a refresh option. Plus: if someone actually ends up in a situation where one is needed, it will be easy to add one then. I don't think we should add one until we actually know there's someone wanting one.

**Comment by monnerat** [comment]
> I don't think we need a refresh option.

Thanks for your reply.
Regarding the tests: test 1136 already checks the PSL. I really don't know what we can reasonably add to test refresh and/or sharing. Unless you have a good idea, I won't write additional tests.

I'm currently waiting for the last CI to complete: if OK, this will be ready for review.

**Pull request closed without merging**
