### PR TITLE
help: update to current codebase

### PR DESCRIPTION
**Pull request by emilengler**
This commit bumps the help to the current state of the project.

### CODE REVIEW

**Review by bagder — APPROVED** [review]
One of these days we should shoehorn this into the build process itself...

**Comment by bagder** [comment]
Can you regenerate this again since I landed 90aad9cb1fa8 with a minor fix?

**Comment by emilengler** [comment]
> Can you regenerate this again since I landed 90aad9cb1fa8 with a minor fix?

Sure

**Comment by emilengler** [comment]
@bagder Updated to current codebase

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
