### PR TITLE
Updated copyright messages that ended in 2017 to 2018

### PR DESCRIPTION
**Pull request by peteski22**
All ' - 2017' ending copyright messages updated to ' - -2018', low hanging fruit.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
What about those with an earlier year than 2017? This typically isn't how the project deal with bumping the copyright year, to avoid commits with lots of churn like this one. Instead the year is updated when a file is touched. Iff a wholesale copyright change process were to be established, it should be based on a script which knows about the different copyrights in the tree,  and which can be invoked on January 1st (but I doubt we want to go there).

**Comment by peteski22** [comment]
Hi Daniel,

OK no worries, I see what you mean, just knock it back I guess.

Cheers
Peter

**Comment by bagder** [comment]
I'm with @danielgustafsson on this.

If you find files that are updated in $YEAR without the copyright string saying "- $YEAR", I'd say that could be a valid reason for update.

**Comment by peteski22** [comment]
👍🏼👌🏼

**Comment by peteski22** [comment]
Closing based on comments.

**Pull request closed without merging**
