### PR TITLE
checksrc: complain about #if defined(X) instead of #ifdef X

### PR DESCRIPTION
**Pull request by jsoref**
I'm not attached to this, it came up in some mbedtls PR...

https://github.com/curl/curl/pull/7428#discussion_r674619146

### CODE REVIEW

**Comment by jay** [comment]
I'm sure most of us have a preference for #if[n]def when there's a single macro. Though IMO the change is unnecessary. I'm fine either way. Also: it's possible we have some guideline for this and I forgot about it.

> I'm not attached to this, it came up in some mbedtls PR...

Include a reference if it came up in something else

**Comment by bagder** [comment]
> it's possible we have some guideline for this and I forgot about it

We just have that silent slight preference for #ffdef/#ifndef. It has never been expressed/documented. This PR would make it expressed if we go with route...

**Comment by gvanem** [comment]
> We just have that silent slight preference for #ffdef/#ifndef. 

When following with a `#elif defined(what_ever)`, IMHO starting with a `#if defined(X)` is more readable.
So why not use it everywhere to be consistent?

**Comment by bagder** [comment]
Others have also mentioned how `#if ...` lines makes it easier to extend them with additional conditions when needed.

>  So why not use it everywhere to be consistent?

I think my personal take is that `ifdef` is simpler. I think users are more accustomed to that for basic conditional compiles - I certainly do them myself by default and only do `#if` constructs if they need to be more complicated.

We currently (without this PR) have 3170 instances of `#ifdef` and `#ifndef` in the source tree. (2159 + 1011)
We currently have 1018 instances of `#if ...`.

I believe this PR changes 223 conditionals, and it is already a large patch. I don't like the prospect of changing 3170 conditions.

**I'm not hearing many votes in favor of merging this PR.**

**Comment by danielgustafsson** [comment]
I see more risk than good in wholesale changes like this when there isn't a clear problem being fixed. Reviewing large, mostly mechanical, patches is errorprone as eyes start to glaze over pretty quickly. I'd rather see that we codify how we'd like new code to be written and change the old code to conform as we touch it for other reasons.

**Comment by bagder** [comment]
@jsoref sorry, but the objections and concerns I hear from others make me have to decline this PR. We simply don't have a consensus for this detail.

**Comment by jsoref** [comment]
I'm not attached to this change (and won't be attached to pretty much any other change I proffer).

I definitely worry about changes where I invest more effort (this was relatively cheap).

**Comment by danielgustafsson** [comment]
> On 16 Aug 2021, at 08:59, Josh Soref ***@***.***> wrote:

> I definitely worry about changes where I invest more effort (this was relatively cheap).

PR’s don’t come with a guarantee of being merged, not for any one of us, that’s up to the community to decide. That doesn’t however mean that PR’s aren’t appreciated, regardless of resolution. Every PR brought to us is a win for the community even it if ends up rejected.

If you would like some more certainty that the work you’re doing will garner the right attention you can bring it up on the mailinglist first.

**Pull request closed without merging**
