### PR TITLE
cookies: make saving atomic with a rename

### LINKED ISSUE #4914: cookie jar updates should be atomic
### I did this

```sh
# Create a dummy cookie jar larger than 4KiB.
$ printf '%s\tFALSE\t/\tTRUE\t2147483647\to\tfoo=bar\n' {0..200}.example.com > x

# Run curl reading & writing that cookie jar.
$ strace -e'!signal' curl https://google.com --cookie x --cookie-jar x
...
openat(AT_FDCWD, "x", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(4, "# Netscape HTTP Cookie File\n# ht"..., 4096) = 4096
write(4, "e.com\tFALSE\t/\tTRUE\t2147483647\to\t"..., 4096) = 4096
write(4, "LSE\t/\tTRUE\t2147483647\to\tfoo=bar\n"..., 1884) = 1884
close(4)                                = 0
...
```

### I expected the following

other processes accessing the cookie jar should be able to rely on the file being coherent/complete.  as it stands, the cookie jar is unreliable with more than one user at a time.

seems like it wouldn't be too difficult to create a tempfile using the name as a base, write to that, then do a single atomic rename.

### curl/libcurl version

`curl 7.66.0 (x86_64-pc-linux-gnu) libcurl/7.66.0 OpenSSL/1.1.1d zlib/1.2.11 nghttp2/1.39.2`

### operating system

`Linux vapier 5.3.1 #1 SMP PREEMPT Fri Sep 27 00:26:44 EDT 2019 x86_64 AMD FX(tm)-4350 Quad-Core Processor AuthenticAMD GNU/Linux`

### PR DESCRIPTION
**Pull request by bagder**
Save the file as "[filename].[8 random hexdigits]" and rename away the extension when
done.

Reported-by: Mike Frysinger
Fixes #4914

### CODE REVIEW

**Comment by bagder** [comment]
For some reason, test 327 seems to not work very well on Windows with this PR... ?

**Comment by jay** [comment]
I've pushed what I hope is a fix for that. [Windows rename()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/rename-wrename?view=vs-2019) isn't the same as [POSIX rename()](https://pubs.opengroup.org/onlinepubs/009695399/functions/rename.html), since only the latter is guaranteed atomic and will overwrite an existing file. The closest thing on Windows is [MoveFileEx](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-movefileexa) which can optionally overwrite and according to an MS dev's comments [here](https://stackoverflow.com/a/57358387) is usually atomic. It will not work if there are open handles to the file, so if multiple processes are accessing it at the same time it won't work.

Starting in Windows 10 1607 there's an internal flag some of the API functions use for NTFS [FILE_RENAME_POSIX_SEMANTICS](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/ntifs/ns-ntifs-_file_rename_information) but if you read that SO thread a user has reported MoveFileEx doesn't use it. I set it to loop MoveFileEx up to 1 second on fail as a remedy.

Regardless of the Windows specific stuff wouldn't @vapier still have the same issue though if multiple curl processes are writing to .part? Maybe a unique temp file name is in order?

**Comment by bagder** [comment]
> I've pushed what I hope is a fix for that.

Thanks!

> Maybe a unique temp file name is in order?

Ah yes of course...

**Comment by bagder** [comment]
Any additional remarks on this PR? It has a lot of green CI builds now...

/cc @vapier @jay

**Comment by jay** [comment]
i pushed some improvements. Two concerns, 1) other OSes that don't support POSIX rename() may have similar behavior? and 2) other OSes may not support filenames beyond a certain length? Perhaps it should be out = fopen(tempstore...; if(!out) /* fall back on direct write */ tempstore = NULL; out = fopen(filename,...; then cleanup like if(tempstore) xrename(tempstore,...

**Comment by bagder** [comment]
> other OSes that don't support POSIX rename

Yes, that's a risk but I don't think we can do much about it now. I'm not aware of any such systems and I don't anyone will speak up here and tell us about them. With this code, such users will run into problems very quickly so at least it won't be a hard-to-detect issue.

> other OSes may not support filenames beyond a certain length?

Similarly, we don't know of any such systems and I think adding precautionary code for such imaginary systems is a bad idea. It adds extra code possibly never used and it is code that is complicated to test. For this case as well, I think we are better off being aware of the situation and we act on it if someone runs into problems with this approach.

**Comment by jay** [comment]
Ok. Some of the appveyor CI builds timed out so I've restarted them to make sure.

**Pull request closed without merging**
