### PR TITLE
Remove unused CMake variables

### PR DESCRIPTION
**Pull request by ruslo**
Remove variables:
* HAVE_SOCKLEN_T
* CURL_SIZEOF_CURL_SOCKLEN_T
* CURL_TYPEOF_CURL_SOCKLEN_T

### CODE REVIEW

**Comment by jzakrzewski** [comment]
If those are really unused, aren't the checks in autotools also redundant?

**Comment by ruslo** [comment]
> aren't the checks in autotools also redundant?

You mean this part:
* https://github.com/curl/curl/blob/4f2541f975c97338ef421ecfeb295d9f3894c1d8/acinclude.m4#L1898-L1899

?

`CURL_SIZEOF_CURL_SOCKLEN_T` can be removed indeed. I think it can be done as a follow-up by a person who use autotools to build CURL and have some experience with the language, because some related code should be removed too.

I'm not so sure about `CURL_SIZEOF_CURL_SOCKLEN_T`. `CURL_SIZEOF_CURL_SOCKLEN_T` defined at compile time for almost all cases except few, so probably the value of `CURL_SIZEOF_CURL_SOCKLEN_T` defined by autotools sometimes used (?):
* https://github.com/curl/curl/blob/4f2541f975c97338ef421ecfeb295d9f3894c1d8/include/curl/system.h

Anyway `CURL_SIZEOF_CURL_SOCKLEN_T` is not used in CMake part because it's not defined here:
* https://github.com/curl/curl/blob/4f2541f975c97338ef421ecfeb295d9f3894c1d8/lib/curl_config.h.cmake

**Comment by bagder** [comment]
> CURL_TYPEOF_CURL_SOCKLEN_T

This is defined by the public header `curl/system.h` so that should be totally fine to not define separately.

I can take care of the autotools cleanup of the `*SOCKLEN_T` macros.

**Comment by jzakrzewski** [comment]
Yeah, I meant that.
It would be quite surprising if one build system needed to define those and other didn't.

**Pull request closed without merging**
