### PR TITLE
IDN: Fix compile time detection of linidn2 TR46

### PR DESCRIPTION
**Pull request by rockdaboot**

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by bagder** [comment]
Urgh!  We can't use `IDN2_TRANSITIONAL`. It breaks the IDNA2008 feature for the .de TLD that is the primary reason we need IDNA2008 in the first place. It makes ß get converted to ss.

This is causes test 165 to fail.

**Comment by rockdaboot** [comment]
It depends what you want. If you want TRANSITIONAL, you have to adjust the test. If you want NON-TRANSITIONAL, you are basically at IDNA2008 plus input mapping (NFC, lowercasing, ...).
If you want both, you have to make it selectable with a new option. I considered this for wget/wget2 as well... overhead, but may satisfy users. With an option the default should IMO be NON-TRANSITIONAL.

Suggestion: --idna=<2008|tr46t|tr46>

If you go with that (or similar), I would implement this for wget/wget2 as well.

**Comment by bagder** [comment]
Well, I want curl to work with IDN on the .de TLD as they require it. Users won't know what option to use for that, so we need to pick one to use. Changing the test case doesn't make us work with that, only changing the code will. Clearly the transitional option is not good enough for that use case. I took out the transitional again in commit ee357664df9b.

I rather wait for someone to actually need an option to modify the IDNA level before we introduce that.

**Comment by rockdaboot** [comment]
Wait... use NON-TRANSITIONAL. As IDNA2008 but much better...

**Comment by bagder** [comment]
Aha! Was that added in the same version as the `IDN2_TRANSITIONAL` one?

**Comment by rockdaboot** [comment]
For example... German Umlauts (same goes for accents and special northern europe letters) may be in decomposed form (NFD/NFKD) or composed form (NFC/NFKC). TR46 accepts them both due to internal NFC transforming.

Yes, IDN2_NONTRANSITIONAL has been added with the same version as IDN2_TRANSITIONAL.

**Comment by bagder** [comment]
Excellent, thank you! Landed in 7d6e3f8cfa5c8d just now.

**Pull request closed without merging**
