### PR TITLE
[WIP] TLS ESNI implementation

### PR DESCRIPTION
**Pull request by niallor**
TLS: provide demonstration ESNI implementation for curl and libcurl

This change addresses TODO items the on current ESNI roadmap 
(docs/ESNI.md) by providing enough support to demonstrate ESNI
using either the curl tool or an app based on libcurl. Fetching of 
ESNI parameters automatically from the DNS is still a work in
progress, and so not implemented in this change. These parameters
must be known or discovered externally and passed as libcurl options
or on the curl command line.

This change builds on recently merged PR #4011.

Proposed-by: @niallor (Niall O'Reilly)\
Encouraged-by: @sftcd (Stephen Farrell)\

### CODE REVIEW

**Comment by bagder** [comment]
This looks more like a milestone and transient state until real ESNI support. Why do we need all these options?

**Comment by niallor** [comment]
Sorry for delayed follow-up. Some other things supervened. If I understand the hint "until real ESNI support" correctly, it means that automatic behind-the-scenes fetching of ESNI key material from DNS is needed for an acceptable PR, and not just a means to provide this material in a way analogous to the CURLOPT_RESOLVE option.

**Comment by bagder** [comment]
You tell me. Do you think we should support ESNI like `CURLOPT_RESOLVE` ? I'm not seeing how users would want that or even know what to get and insert into such an option!

**Comment by niallor** [comment]
As well as what @sftcd mentioned, I think there's a need for options which will allow decoupling libcurl operation from the DNS both during post-build testing (`make test`) and during operational fault isolation.

**Comment by bagder** [comment]
Thanks @sftcd, that certainly makes it crystal clear to me why we want those options!

@niallor:
> there's a need for options which will allow decoupling libcurl operation from the DNS both during post-build testing (make test) and during operational fault isolation

Perhaps, but options for testing and debugging shouldn't be made publicly available command line options. We already have a system for unit tests to allow for testing of internal functions that we can easily just follow for ESNI as well. If we want to provide command line options for debugging or internal reasons, I think we can do that as well but they should then also be marked up and made special so that they're not confused or mistakenly taken for "real" options.

**Comment by niallor** [comment]
I'll see @sftcd on Wednesday and we'll review. ATM, it seems to me that `ESNI_SERVER` is superfluous, and that the others (modulo naming) are likely needed for the use cases he mentioned.

**Comment by niallor** [comment]
Summary of what I think is the current status of this PR

- [TODO] Propagate result of (TXT, "_esni") DOH query to where it can be used for TLS setup
- [TODO] Check command-line docs for accuracy and consistency
- [TODO] Check libcurl docs likewise
- [TODO] Update ESNI.md
- [ONLY THEN] Alert @bagder for review

**Comment by niallor** [comment]
I expect that this needs to sit until IETF process converges. I'ld appreciate feedback on anything that is somehow undesirable in the code so far. I'm pretty sure that the propagation path from DNS by setting the relevant option is not how it should be done, but I haven't worked out the "right way".

**Comment by Lekensteyn** [comment]
As heads-up: the ESNI draft has significantly changed, instead of just encrypting the name, a new "outer" Client Hello embeds an encrypted "inner" Client Hello which enables encryption of SNI, ALPN and other extensions. This is currently called "ECHO" (Encrypted Client Hello), but that name is also not set in stone.

Since it is still an Internet-Draft, I suggest documenting which draft version is being tracked by this implementation.

**Comment by sftcd** [comment]
On 09/05/2020 11:27, Peter Wu wrote:
> As heads-up: the ESNI draft has significantly changed, instead of
> just encrypting the name, a new "outer" Client Hello embeds an
> encrypted "inner" Client Hello which enables encryption of SNI, ALPN
> and other extensions. This is currently called "ECHO" (Encrypted
> Client Hello), but that name is also not set in stone.
> 
> Since it is still an Internet-Draft, I suggest documenting which
> draft version is being tracked by this implementation.
> 

The current implementation supports drafts -02, -03, and
-04. AFAIK, only draft-02 has seen any deployment - by
Cloudflare, FF and in some test servers such as ours at
https://defo.ie

We continue to work on the implementation and will likely
have support for the next draft (which'll be -07) in an
upcoming version. (-05 and -06 are ok to skip.)

Note of course that our implementation is based on a fork
of openssl. We will be offering code back to upstream when
the spec is final.

Cheers,
S.

**Comment by niallor** [comment]
Draft-02 is more fully supported in this PR. For later drafts, it's necessary to specify the ESNI 'blob' on the curl command line (as HEX or BASE64). Automatic retrieval of ESNI data from DNS using DOH is implemented in libcurl only for (draft-02) TXT records.

I expect to wait until respective code points are announced by IANA in the RR TYPE registry before putting effort into implementing DOH retrieval of HTTPSSVC and/or SCVB, and extracting the ESNI option from in there. I understand that an number of different experimental code points are in use by trailblazers; I'm not minded to try either to follow more than one or to guess which one is best to pick.

Depending on the level of refactoring needed, it may make sense to close this PR and open a fresh, cleaner one for draft-07 and beyond.

**Comment by bagder** [comment]
ESNI has changed name . This PR is now out of date. We're still interested in the functionality but I think it makes better sense to close this now and open a new one when there's a take on the spec version that is more likely to ultimately become "the real thing".

**Comment by sftcd** [comment]
On 27/05/2020 22:41, Daniel Stenberg wrote:
> ESNI has changed name . This PR is now out of date. We're still
> interested in the functionality but I think it makes better sense to
> close this now and open a new one when there's a take on the spec
> version that is more likely to ultimately become "the real thing".
> 

Yeah that's likely right. We'll get back when we've updated
our OpenSSL fork to support the latest version of ECH (nee
ESNI;-)

Cheers,
S.

**Comment by niallor** [comment]
On 27 May 2020, at 22:41, Daniel Stenberg wrote:

> ESNI has changed name . This PR is now out of date. We're still 
> interested in the functionality but I think it makes better sense to 
> close this now and open a new one when there's a take on the spec 
> version that is more likely to ultimately become "the real thing".

Fair enough. Good housekeeping!

Niall

**Pull request closed without merging**
