### PR TITLE
ssh knownhost improvement

### PR DESCRIPTION
**Pull request by mickae1**
for my project I need a better handling of the know_host file:

I looked at the CURLSHOPT_LOCKFUNC mechanism, but it doesn't suit my need. 
( I need a lock mechanism different for each known_host file )

So I added a lock mechanism with two callback and a handle:

-   curl_func_lock func_lock; <== generic function
-   curl_func_unlock func_unlock; <== generic function
-   void* ssh_knowhost_hlock; <== handle for the lock mechanism used only for the known_host file

I need also to have one known_host file for multiple connection, so I added a pointer to an handle. If this pointer is not null, the handle of the known_host file is stored in the pointer.

I also need the ability to change an old fingerprint, so I added the option :

CURLKHSTAT_FINE_REPLACE_TO_FILE when the function ssh_keyfunc is called.

It's my first time that I make a pull request, so if there is something not correct with my english, or my code, tell me, I will change if it's possible.

Micka,

### CODE REVIEW

**Comment by jay** [comment]
I don't understand why we need this, it seems like it's something specific to your use case which is fine but why send it upstream?

**Comment by mickae1** [comment]
I just want to share my work. And I think that it can help others to better
manage their known host file: Avoiding conflict when two parallel
connection use the same file and try to modify it. That the main problem.

**Comment by mickae1** [comment]
And the ability to change an old fingerprint is something That is missing, it's very useful to add this.

**Comment by bagder** [comment]
Can you please describe your change so that we can understand what function it brings and why we want it merged into the code base? It sounds like two separate changes?

**Comment by bagder** [comment]
Test 1119 fails because of these missing names in `symbols-in-versions`, but you also didn't write any docs for them. But again, please describe this change and discuss it with us first before you run ahead and do a lot of work that we might not agree with or would prefer have done another way!
~~~
 CURLKHSTAT_FINE_REPLACE_TO_FILE
 CURLOPT_FUNCTION_LOCK
 CURLOPT_FUNCTION_UNLOCK
 CURLOPT_SSH_KNOWNHOSTS_HANDLE_KH
 CURLOPT_SSH_KNOWNHOSTS_HANDLE_LOCK

**Comment by mickae1** [comment]
The main problem of the known_host file is the access of the file.
When you have two sftp connection that happen at the same time and both of
those connection want to write at the same time on the same file...
Something wrong will happen.

The second point, is that sometime you need to modify the file known_host.
Example, the fingerprint of a host changed. It's a nightmare to remove the
old fingerprint and add the new one.


Micka,

Le dim. 10 nov. 2019 à 15:58, Daniel Stenberg <notifications@github.com> a
écrit :

**Comment by bagder** [comment]
> When you have two sftp connection that happen at the same time and both of
those connection want to write at the same time on the same file...
Something wrong will happen.

Okay, so I presume your take is a fix that makes it less wrong? Can you explain how? Isn't most of the known hosts logic done by the ssh libraries?

> sometime you need to modify the file known_host.
Example, the fingerprint of a host changed. It's a nightmare to remove the
old fingerprint and add the new one.

That's why you introduce CURLKHSTAT_FINE_REPLACE_TO_FILE, right? I would urge you to do that in a separate PR as it seems to be reasonably separate from the above change.

**Comment by bagder** [comment]
No response, PR of questionable value. Closing.

**Comment by mickae1** [comment]
I will work on this subject. It's just that I am busy for the moment.

Le ven. 29 nov. 2019 à 11:26, Daniel Stenberg <notifications@github.com> a
écrit :

**Pull request closed without merging**
