### PR TITLE
gen.pl: insert the current date and version in generated man page

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Gisle Vanem
Ref: #7780

### CODE REVIEW

**Comment by gvanem** [comment]
Almost, but with my Strawberry Perl, this generates:
```
curl 7.80.0                        1b 1e 1Y                            curl(1)
```

With Cygwin's Perl, it's fine; `Sep 28 2021`.

**Comment by gvanem** [comment]
*Update:* My Strawberry Perl doesn't like the `%e`. But a `%d` works. Giving `sep 28 2021` (lower-case month name).

**Comment by bagder** [comment]
It of course begs the question if your perl install isn't broken and if we should really care about broken perl installs. I found no records of %e not working in perl generally.

But I also checked a few other man pages and the date format used vary greatly. I don't think using a zero-prefixed number (`%d` instead of `%e`) would hurt. Maybe even use the full month name.

What do you think about `"%B %d %Y"` ?

**Comment by jay** [comment]
> It of course begs the question if your perl install isn't broken

It's not. strawberry perl posix seems to be using the C runtime's strftime and older MS CRTs likely do not support %e. I tried `"%b %e %Y"` in Windows 7 with a recent strawberry perl and I get a blank string.

> What do you think about `"%B %d %Y"` ?

That works here and all the format specifiers are C89.

**Comment by gvanem** [comment]
> What do you think about "%B %d %Y" ?

Work fine.

**Comment by bagder** [comment]
I'll do a PR with that change as soon as we get the winsock situation in master stable again

**Pull request closed without merging**
