### PR TITLE
redirect: skip URL encoding for host names

### PR DESCRIPTION
**Pull request by salshaaban**
This fixes redirects to IDN URLs

Bug: #1441
Reported by: David Lord

### CODE REVIEW

**Comment by bagder** [comment]
Thanks, I'm working on writing up a test for this. In fact, I already did but the problem now is that the test uses a hard-coded port number in the HTTP response header and that's not how we like to do things, so I need to come up with a solution to that ...

**Comment by salshaaban** [comment]
> I'm working on writing up a test for this. In fact, I already did

I should've done that myself. Sorry!
I will try to think of something too.

**Comment by bagder** [comment]
check out [test1448](https://github.com/curl/curl/files/1219849/test1448.txt) (remove the `.txt` extension)

**Comment by bagder** [comment]
**Aha!** I figured it out. I can use `--connect-to`, to redirect that port 8990 to the port it is actually on! ... I'll post a separate PR to see what the CI says.

**Comment by bagder** [comment]
That's now in #1772

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
