### PR TITLE
[CMakeLists.txt] Remove explicit `CMAKE_ANSI_CFLAGS`

### PR DESCRIPTION
**Pull request by SamuelMarks**
Hadn't seen the `CMAKE_ANSI_CFLAGS` flag before, searched it and found: https://gitlab.kitware.com/cmake/cmake/commit/5a834b0bb0bc2889bb67bdaac37ce9b17d4f0f59

### CODE REVIEW

**Comment by bagder** [comment]
Can you please clarify why you want to remove this and what effects it will have on users on new and old cmake verisons? That link didn't help me.

**Comment by SamuelMarks** [comment]
That link makes me think that this approach has been deprecated for 12 years…

**Comment by SamuelMarks** [comment]
That link makes me think that this approach has been redundant for 12 years…

**Comment by SamuelMarks** [comment]
@Lekensteyn Great!

Oh, I just searched for `CMAKE_ANSI_CFLAGS` when I was reviewing libcurl's way of doing things in its `CMakeLists.txt` (for my own projects, I'm adding support for different crypto libraries, HTTP & HTTPS libraries, &etc.).

**Comment by bagder** [comment]
@Lekensteyn is that an ack from you to merge this?

**Review by Lekensteyn — APPROVED** [review]
Yes sure, the patch looks fine. I would suggest updating the commit message to make clear why it is safe to remove this, but it looks fine otherwise.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
