### PR TITLE
tests: add support to test against OpenSSH for Windows

### PR DESCRIPTION
**Pull request by mback2k**
This a work-in-process pull-request to get the testsuite work with OpenSSH for Windows.

This pull-request is not complete and only open to trigger the CI tests.

### CODE REVIEW

**Comment by bagder** [comment]
@mback2k what's the plan here? It's been here for a long time and seemed to be fine until the merge conflict appeared. Is this still worth doing?

**Comment by mback2k** [comment]
@bagder I will get back to this, yes.

**Comment by mback2k** [comment]
@bagder I think this PR is ready to be merged once all checks have passed. Does this have to wait until the release or can it go into master during the freeze?

**Comment by bagder** [comment]
Since it has been waiting for this long, I think it won't harm much if we take it the safe route and wait with the merge until after Wednesday. There's so little time left I figure it might not be worth rocking the boat now... I'm not sure how to estimate how safe/risky this change is so I rather we play it safe.

**Pull request merged**
