### PR TITLE
ntlm: copy NTLM_HOSTNAME to host buffer

### PR DESCRIPTION
**Pull request by danielgustafsson**
Commit 709ae2454f43 added a fake hostname to avoid leaking the local hostname, but omitted copying it to the host buffer.

Closes: xxxx
Fixes: #8893
Reported-by: Patrick Monnerat <patrick@monnerat.net>

### CODE REVIEW

**Comment by danielgustafsson** [comment]
There's a lot of testfailures here, and there all of this variety:
```diff
 547: protocol FAILED:
--- log/check-expected	2022-05-21 18:05:51.119661197 +0200
+++ log/check-generated	2022-05-21 18:05:51.119661197 +0200
@@ -16,7 +16,7 @@
 [CR][LF]
 POST http://test.remote.example.com/path/547 HTTP/1.1[CR][LF]
 Host: test.remote.example.com[CR][LF]
-Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAEAAAAAYABgAWAAAAAAAAABwAAAACAAIAHAAAAALAAsAeAAAAAAAAAAAAAAAhoIBAFpkQwKRCZFMhjj0tw47wEjKHRHlvzfxQamFcheMuv8v+xeqphEO5V41xRd7R9deOXRlc3R1c2VyAAAAAAAAAAAAAAA=[CR][LF]
+Proxy-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAEAAAAAYABgAWAAAAAAAAABwAAAACAAIAHAAAAALAAsAeAAAAAAAAAAAAAAAhoIBAFpkQwKRCZFMhjj0tw47wEjKHRHlvzfxQamFcheMuv8v+xeqphEO5V41xRd7R9deOXRlc3R1c2VyV09SS1NUQVRJT04=[CR][LF]
 Accept: */*[CR][LF]
 Proxy-Connection: Keep-Alive[CR][LF]
 Content-Length: 36[CR][LF]
```
I'll fix all of those, but I'll wait until I know this PR is along the right track.

**Comment by bagder** [comment]
Good catch. Gee, that was mighty silly of me...

**Review by bagder — APPROVED** [review]

**Comment by danielgustafsson** [comment]
PR updated with test fixes to take for a spin across the CI.

**Comment by monnerat** [comment]
Thanks for fix!

**Pull request closed without merging**
