### PR TITLE
WIP: dict: Add CURLOPT_DICT_CLIENTNAME

### PR DESCRIPTION
**Pull request by emilengler**
This adds a new CURLOPT called `CURLOPT_DICT_CLIENTNAME`.
It allows to change the `CLIENT` value when doing a DICT request.
If it is not set, the current value will be used which is `libcurl CURRENTVERSION`.

**Before merge there is still ONE thing to do where I wasn't able to figure it out and this is to add an entry to `packages/OS400/curl.inc.in`. I don't know what the numbers on the right side mean.**

Some examples:
`curl_easy_setopt(curl, CURLOPT_DICT_CLIENTNAME, "Custom");` will result in (server side):
```
CLIENT Custom
DEFINE ! Test
QUIT
```
Leaving it blank will result in:
```
CLIENT libcurl 7.70.0-DEV
DEFINE ! Test
QUIT
```

### CODE REVIEW

**Comment by emilengler** [comment]
The FreeBSD CI fail is independent of this PR

**Comment by dfandrich** [comment]
Can't CURLOPT_USERAGENT be reused for this?

**Comment by emilengler** [comment]
> CURLOPT_USERAGENT

I also thought about this but the documentation says it is an HTTP only thing

**Comment by dfandrich** [comment]
On Thu, Apr 16, 2020 at 03:46:39AM -0700, Emil Engler wrote:
>     CURLOPT_USERAGENT
> 
> I also thought about this but the documentation says it is an HTTP only thing

That's only because your patch hasn't landed yet :-)

**Comment by emilengler** [comment]
> That's only because your patch hasn't landed yet :-)

Sure but I personally would like to keep it that way. The term user agent is unknown at DICT. Another suggestion would be to add a general CURLOPT which sets a client name for all protocols which support it

**Comment by bagder** [comment]
First, is this really something you have a use case for?

We should always be careful and really consider if a new option is ever necessary. We have too many options already and we can't easily remove any.

Suggesting a new option for a basically dead protocol for which the code has remained virtually untouched in curl for ages is an even harder bargain.

Lastly, I agree with @dfandrich that `CURLOPT_USERAGENT` seems like a suitable option to use for this protocol as well.

**Comment by bagder** [comment]
The fuzzer found a [memleak](https://github.com/curl/curl/pull/5245/checks?check_run_id=591644888#step:4:9237)? 
~~~
Running: /src/curl_fuzzer/corpora/curl_fuzzer_dict/test_url_dict

=================================================================
==40709==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 34 byte(s) in 1 object(s) allocated from:
    #0 0x52279d in malloc /src/llvm-project/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
    #1 0x5a2775 in curl_dbg_malloc /src/curl/lib/memdebug.c:174:9
    #2 0x64bfcd in dict_do /src/curl/lib/dict.c:156:19
    #3 0x5c06ac in multi_do /src/curl/lib/multi.c:1380:14
    #4 0x5b893e in multi_runsingle /src/curl/lib/multi.c:1854:18
    #5 0x5b770c in curl_multi_perform /src/curl/lib/multi.c:2363:14
    #6 0x555a6f in fuzz_handle_transfer(fuzz_data*) /src/curl_fuzzer/curl_fuzzer.cc:305:3
    #7 0x555281 in LLVMFuzzerTestOneInput /src/curl_fuzzer/curl_fuzzer.cc:93:3
    #8 0x45ac01 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerLoop.cpp:556:15
    #9 0x445721 in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:292:6
    #10 0x44b3de in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerDriver.cpp:774:9
    #11 0x475302 in main /src/llvm-project/compiler-rt/lib/fuzzer/FuzzerMain.cpp:19:10
    #12 0x7fa0d4f0882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)

SUMMARY: AddressSanitizer: 34 byte(s) leaked in 1 allocation(s).

**Comment by emilengler** [comment]
Ok, I will update CURLOPT_USERAGENT then as well.
> First, is this really something you have a use case for?

It has the same use case as the HTTP User-Agent if it is being actually used is probably unlikely due to the small amount of dict servers.

> Suggesting a new option for a basically dead protocol for which the code has remained virtually untouched in curl for ages is an even harder bargain.

If we support a protocol we should support it well in my opinion. If we don't try this we most likely failed at being the Swiss Army Knife for networking.

However I agree on the point to make CURLOPT_USERAGENT more global. I'm not sure but I think other protocols support client identification as well

**Comment by bagder** [comment]
> If we don't try this we most likely failed at being the Swiss Army Knife for networking.

New options add a tax for *all users* using *any protocol* (because it gives more words to read through, skip, understand and so on). Doing this for a virtually unused protocol is a disproportionate action. Give more load to 99.9% of all users for a *possible* benefit to 0.1% of the users.

Which is also why I asked for a use case. We don't add stuff to curl to make it "the Swiss Army Knife for networking". We add stuff to curl to make it support the things people want to use it for. If nobody ever asked for a feature, and we could possibly even suspect that nobody will use it even when we add it, then it's a useless addition.

All that said; a change to a virtually unused protocol that **doesn't** add an option is basically free to everyone using all the other protocols and makes it an entirely different discussion.

**Comment by emilengler** [comment]
Ok I will close this then to lack of possible use. If someone is interested in taking this over in the future feel free to do so

**Pull request closed without merging**
