### PR TITLE
VS2015 breaking Windows OpenSSL Application(s)

### PR DESCRIPTION
**Pull request by sunnyap**
VS2015 is breaking OpenSSL Application(s) including CURL.
Recent changes in VS2015 _IOB_ENTRIES is causing failure of some OpenSSL Application.
Possible Error: OPENSSL_Uplink(00007FFEBF310000,08): no OPENSSL_Applink.
Affected OS Platforms: Windows. OpenSSL Application Build with VS2015.
Affected Unix Platforms: <>, Try Solution 2.

Solution 1: Microsoft/OpenSSL (https://github.com/Microsoft/openssl)
-------------------------------------------------------------------------------------------------------------------
This solution is applicable if your OpenSSL Application is -
1. using OpenSSL from https://github.com/Microsoft/openssl distribution and 
2. build using VS2015 using latest Update - Update 3
FIX: Use latest Microsoft/OpenSSL and rebuild your Application.
FIX Description: Microsoft has fixed the VS2015 _IOB_ENTRIES breakage in <Microsoft/OpenSSL>/crypto/bio/bss_file.c
https://github.com/Microsoft/openssl/commit/3e8a22c4c880cad92f36aa29f0c75d118e11f362?diff=split 

Solution 2: Fixing Application as per OpenSSL Recommendation (Recommended)
-------------------------------------------------------------------------------------------------------------------
This solution is applicable if your OpenSSL Application is -
1. using OpenSSL from openssl.org distribution and 
2. build using VS2015 using latest Update - Update 3
FIX 1: Fix your OpenSSL Application to use BIO functions instead of FILE I/O Functions as per OpenSSL recommendation. OR
FIX 2: Apply https://github.com/openssl/openssl/pull/2701
OpenSSL LINK: https://mta.openssl.org/pipermail/openssl-dev/2015-December/003664.html OR 
openssl/openssl#2404
OpenSSL by Example: See how OpenSSL uses BIO functions in SSL_use_certificate_file()
LINK: https://github.com/openssl/openssl/blob/master/ssl/ssl_rsa.c

Solution 3: Fixing OpenSSL with Fix from Microsoft/OpenSSL
-------------------------------------------------------------------------------------------------------------------
This solution is applicable if your OpenSSL Application is -
1. using OpenSSL from openssl.org distribution and 
2. build using VS2015 using latest Update - Update 3
FIX: Patch your OpenSSL from openssl.org with fix from Microsoft/OpenSSL.
<Microsoft/OpenSSL>/crypto/bio/bss_file.c
https://github.com/Microsoft/openssl/commit/3e8a22c4c880cad92f36aa29f0c75d118e11f362?diff=split

### CODE REVIEW

**Comment by jay** [comment]
Ref https://rt.openssl.org/Ticket/Display.html?id=4156 which was migrated to openssl/openssl#2404

[PEM_read_X509 call](https://github.com/curl/curl/blob/curl-7_52_1/lib/vtls/openssl.c#L2831) doesn't have the same issue?

**Comment by bagder** [comment]
So what about these possible solutions?

3. Fix OpenSSL so that applications can remain unmodified

4. Don't build OperSSL with VS2015 (until 3 is done)

**Comment by rodwiddowson** [comment]
> Fix OpenSSL so that applications can remain unmodified
That would be my preference but who knows what leverage people have

> Don't build OpenSSL with VS2015 (until 3 is done)
You may hit resistance from upstream projects.  FWIW we are OK (for now).

Does anybody have any handy list of affected functions (OpenSSL) so I can grep over our code?  If not I'll see about generating one. 

If get that working I could try to do this over curl, but it looks like maybe @jay has done so already?

**Comment by rodwiddowson** [comment]
(sorry for the continuous flow of consciousness).

I should add the ApacheLounge is making it quite hard to find non VC14/VC2015 builds.  Of course, 
we may be a minority in having Apache and and OpenSSL (and libcurl) in our dependency tree.  Or not.

**Comment by sunnyap** [comment]
@jay 
The ticket was closed by OpenSSL suggesting to use BIO Functions. No code changes was made.
I haven't hit the issue around PEM_read_X509. May be this part of the code is not hit. Hence can't say for sure. In case if I hit the issue with PEM_read_X509 I will switched to PEM_read_bio_X509 and try

@bagder 
3. OpenSSL has suggested to switch to BIO instead of File I/O. Not sure if OpenSSL will take Microsoft/OpenSSL or provide their own fix. 

@rodwiddowson 
You can grep File I/O functions like (FILE *, fopen, fclose). Wherever you see this you should switch to BIO functions. Example -
1. FILE *p12_file; > BIO *p12_file = BIO_new(BIO_s_file());
2. p12_file = fopen(pkcsFile, "rb"); > BIO_read_filename(p12_file, pkcsFile);
3. d2i_PKCS12_fp(p12_file, NULL); > d2i_PKCS12_bio(p12_file, NULL);
4. fclose(p12_file); > BIO_free(p12_file);
5. PEM_read_X509() > PEM_read_bio_X509 etc..
https://www.openssl.org/docs/man1.1.0/crypto/bio.html
https://www.openssl.org/docs/man1.0.2/crypto/

**Comment by jay** [comment]
@rodwiddowson I went over it then and that was the only other call I saw.

The fix in this case seems harmless. Using FILEs that could potentially go across CRTs is not good. I'd guess most people using libcurl with OpenSSL have both built against the same CRT or simply aren't using PKCS or CURLOPT_ISSUERCERT otherwise we would have heard of this before.

I'm not opposed to addressing this.

**Comment by bagder** [comment]
I'm also fine with merging this fix (after the 7.53.0 release), but I'm also for fixing this in OpenSSL itself.

**Comment by sunnyap** [comment]
@bagder Thanks. Fixing OpenSSL itself sound great. So you will be taking fix from Microsoft/OpenSSL?

**Comment by bagder** [comment]
There are discussions in the OpenSSL issue now on how to proceed there.

**Comment by sunnyap** [comment]
@bagder Yeah. I am watching it.

**Comment by sunnyap** [comment]
All, OpenSSL #2701 worked for me.  Do we still merge this fix in curl since OpenSSL itself will have this fix?

**Comment by jay** [comment]
Though they fixed the issue I would do this patch or something similar anyway. OpenSSL can be running with a different CRT than the code calling it (eg libcurl). As a stopgap to port some legacy stuff they use something called applink which basically makes OpenSSL use the application's (ie the EXE) CRT, and only if it's built in. Assume an application w/applink, OpenSSL and libcurl are all using different CRTs... what then? No good. The solution as Polyakov has said is stop using the OpenSSL functions that have FILE pointers in the prototype.

**Comment by bagder** [comment]
Agreed. So any comments/complaints on @sunnyap's PR here or can we merge?

**Comment by jay** [comment]
I've reviewed it and have a few concerns.

There's [another call](https://github.com/curl/curl/blob/curl-7_53_1/lib/vtls/openssl.c#L2829) that passes FILE * and needs to be taken care of.

In Windows OpenSSL expects UTF-8 encoded filenames, so we should pass them in that encoding. We have some functions that are supposed to help with that [but actually don't](https://github.com/curl/curl/blob/curl-7_53_1/lib/curl_multibyte.h#L74-L88) unless curl is compiled for UNICODE which it usually isn't. In the highlighted section of code in that link you can see converting back and forth ANSI tchar (ie the local codepage) to UTF-8 is basically a no-op, which is incorrect. What is weirder is the code that actually uses those incorrect functions seems to correctly expect ANSI codepage when not UNICODE. I will have to investigate more into that.

OpenSSL 1.0.2 (and probably earlier) guards `BIO_s_file` and `BIO_new_file` [with `# ifndef OPENSSL_NO_FP_API`](https://github.com/openssl/openssl/blob/OpenSSL_1_0_2k/crypto/bio/bio.h#L653-L658) which makes no sense to me. This was removed in 1.1.0 in favor of OPENSSL_NO_STDIO which essentially does the same thing but correctly. I'm not sure how big an issue this is, see [this question](http://comments.gmane.org/gmane.comp.encryption.openssl.user/35645) from @alamaison.

Catching this in the future as the code changes I think define OPENSSL_NO_STDIO (the offspring of fixed OPENSSL_NO_FP_API) before any OpenSSL includes, then whenever libcurl is built with OpenSSL 1.1.0 it makes sure those FILE * function prototypes aren't declared, which may be good enough. Earlier versions we can't do something similar because of the issue I discussed above.

I think all of this is manageable however we could always read the files ourselves and use a memory BIO if it's easier.

**Comment by sunnyap** [comment]
> There's  another call that passes FILE * and needs to be taken care of.
@jay I can take care of this but I can't test it since my code will not hit this part of code. Will that do?

**Comment by jay** [comment]
> I can take care of this but I can't test it since my code will not hit this part of code. Will that do?

You're welcome to update your commit to get rid of the other OpenSSL API call with FILE. I have to add appropriate UTF-8 <-> ANSI conversion functions for Windows (see my previous post) and then amend your commit for that before I can land this.

**Comment by sunnyap** [comment]
Please review 853f8c1

**Comment by sunnyap** [comment]
Are we good to merge?

**Comment by bagder** [comment]
I think it looks good. I would however prefer to see the first commit get a better commit message. There's no point in listing and detailing two alternatives when one of them is the one implemented in the code. Also please use a short first line in the commits in the style. If you check other commits you can see how we do them.

[area]: [short overview of the change]

**Comment by sunnyap** [comment]
I think I am not done here. I planned to do -
1. Removed the long commit message as suggested by @bagder
2. Merge the code to master.

**Comment by sunnyap** [comment]
I am getting - 

remote: Permission to curl/curl.git denied to sunnyap.
fatal: unable to access 'https://github.com/curl/curl/': The requested URL returned error: 403
Pushing to https://github.com/curl/curl

**Comment by jay** [comment]
> I am getting -
> 
> remote: Permission to curl/curl.git denied to sunnyap.
> fatal: unable to access 'https://github.com/curl/curl/': The requested URL returned error: 403
> Pushing to https://github.com/curl/curl

To update your branch patch-1 you have to push to your remote sunnyap/curl not curl/curl. Run git remote -v to find which remote name is yours and push there.

**Comment by bagder** [comment]
This PR still generates heaps of warnings, as the travis build shows. @sunnyap, we want all the CI builds to go green before we consider merging!

**Pull request closed without merging**
