### PR TITLE
.cirrus.yml: freebsd 14

### PR DESCRIPTION
**Pull request by pheiduck**
ensure curl works on latest freebsd version

### CODE REVIEW

**Comment by dfandrich** [comment]
I wouldn't expect 14 to be released for another 4 months or so. We've had
issues with stability of prerelease versions before and had to disable them I
would prefer to wait another few months before adding it. The CI builds are
unstable enough as it is.

**Comment by pheiduck** [comment]
> I wouldn't expect 14 to be released for another 4 months or so. We've had issues with stability of prerelease versions before and had to disable them I would prefer to wait another few months before adding it. The CI builds are unstable enough as it is.

Thanks for your feedback @dfandrich sure definitely we should wait until it is released.

**Comment by vszakats** [comment]
Released today: https://www.freebsd.org/releases/14.0R/relnotes/

**Comment by pheiduck** [comment]
I may need to find a solution for this:
```
pkg: No packages available to install matching 'openssh-portable' have been found in the repositories
```

**Comment by vszakats** [comment]
Have you tried with `openssl-quictls`?:

https://cgit.freebsd.org/ports/tree/security/openssl-quictls

**Comment by pheiduck** [comment]
> Have you tried with `openssl-quictls`?:
> 
> https://cgit.freebsd.org/ports/tree/security/openssl-quictls

nope, will try :)

**Comment by vszakats** [comment]
Oh sorry, the build is green now, but I misread openssh as openssl... Regarding openssh-portable, these are the options according to package search:
https://ports.freebsd.org/cgi/ports.cgi?query=openssh-portable

**Comment by pheiduck** [comment]
> Oh sorry, the build is green now, but I misread openssh as openssl... Regarding openssh-portable, package search knows about it: https://ports.freebsd.org/cgi/ports.cgi?query=openssh-portable
> 
> I assume we use `openssh-portable` for tests. Tests are green too. I haven't checked ssh-based tests specifically, but perhaps openssh come with the base install?

Commit is reverted.

**Review by vszakats — APPROVED** [review]

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
