### PR TITLE
ignore: Ignore VSCode directory

### PR DESCRIPTION
**Pull request by jsoref**

### CODE REVIEW

**Comment by bagder** [comment]
Is there a good reason for us to add it to the project specific `.gitignore` ? Shouldn't a typical VS code user put this directory in a more system-wide gitignore file? I would rather we stopped adding new editor/IDE specific craziness into our ignore file ...

**Comment by danielgustafsson** [comment]
> Is there a good reason for us to add it to the project specific .gitignore ? Shouldn't a typical VS code user put this directory in a more system-wide gitignore file? I would rather we stopped adding new editor/IDE specific craziness into our ignore file ...

Ignoring files from toolchains which are outside of the core requirements to build curl/libcurl should go into users local gitignore files (core.excludesFile or $GIT_DIR/info/exclude). -1 on this from me.

**Comment by jsoref** [comment]
🤷‍♂️. I added it here to match a number of other items already present of the same family including VS.

If you'd rather remove all of them and add a comment pointing to a document about user git ignore suggesting that ide settings be ignored that way, that is also reasonable.

**Comment by jzakrzewski** [comment]
Yep - there were at least two similar request for other IDEs AFAIR and both turned down for the same reasons. Following that path this one should not be accepted either.

**Comment by jsoref** [comment]
https://github.com/curl/curl/blob/bba83ed285a0002b267eaed136ae341269f2a775/.gitignore#L14
https://github.com/curl/curl/blob/bba83ed285a0002b267eaed136ae341269f2a775/.gitignore#L18-L20

**Comment by bagder** [comment]
> If you'd rather remove all of them

I rather leave the existing and not add new ones. To keep the boat stable.

**Comment by jsoref** [comment]
Are you ok adding a comment advising people to use local gitignore instead?

**Comment by bagder** [comment]
I honestly don't think that will do any good.

**Comment by danielgustafsson** [comment]
> I honestly don't think that will do any good.

+1. I don't think it's our job to teach good Git practices, it's a slippery slope towards taking on a much larger documentation responsibility than what we have the capacity to handle.

**Pull request closed without merging**
