### PR TITLE
GHA/windows: add gssapi to openssl job

### PR DESCRIPTION
**Pull request by talregev**
Add gssapi to openssl job

waiting for:
- [x] https://github.com/curl/curl/pull/15564
- [x] https://github.com/curl/curl/pull/15545

### CODE REVIEW

**Comment by talregev** [comment]
It fail, and I am not sure if it intended:
```
D:\a\curl\curl\lib\strtok.h(31,9): error C2220: the following warning is treated as an error [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
  
D:\a\curl\curl\lib\strtok.h(31,9): warning C4005: 'strtok_r': macro redefinition [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
      C:\vcpkg\installed\x64-windows\include\win-mac.h(215,9):
      see previous definition of 'strtok_r'
  
D:\a\curl\curl\lib\krb5.c(252,[48](https://github.com/talregev/curl/actions/runs/11779158992/job/32807035787?pr=27#step:9:49)): error C2065: 'gss_nt_service_name': undeclared identifier [D:\a\curl\curl\bld\lib\libcurl_object.vcxproj]
  (compiling source file 'CMakeFiles/libcurl_object.dir/Unity/unity_0_c.c')
```

**Comment by vszakats** [comment]
Can you test it with #15564?

**Comment by talregev** [comment]
> Can you test it with #15564?

I rebase over your branch.

**Comment by talregev** [comment]
It solve the `'strtok_r': macro redefinition` But there is more compilation problems.

**Comment by vszakats** [comment]
There is something funny going on when trying and failing to detect `GSS_C_NT_HOSTBASED_SERVICE`.
Failing to detect it may cause the `'gss_OID' differs in levels of indirection from 'int'` errors.

Can you also apply #15545? It may help avoid some warnings, and perhaps this, and perhaps-perhaps the detection above:
```
LINK : fatal error LNK1104: cannot open file 'gssapi64.lib'
```
https://github.com/curl/curl/actions/runs/11819947642/job/32931130624?pr=15549#step:7:690

This still leaves a bunch of other issues though.

**Comment by talregev** [comment]
I rebease over your other branch. It solve many problems.

**Comment by vszakats** [comment]
It fixed the detection and some of the warnings with it.

Reduced to this now:
```
D:\a\curl\curl\lib\krb5.c(652,28): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data D:\a\curl\curl\lib\krb5.c(654,28): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data D:\a\curl\curl\lib\krb5.c(656,26): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data D:\a\curl\curl\lib\krb5.c(657,26): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data D:\a\curl\curl\lib\krb5.c(665,24): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data D:\a\curl\curl\lib\krb5.c(666,24): warning C4244: 'function': conversion from 'curl_socket_t' to 'int', possible loss of data 
```

I don't understand which type is wrong. There is a sockindex (int) and
the socket itself (curl_socket_t). On Windows their types are not
interchangeable.

`socket_write()` is passed a socket, but expects a sockindex. Then 
it passes down this sockindex to `Curl_conn_send()`.

**Comment by vszakats** [comment]
@talregev Would you mind opening an issue with the int/socket confusion warnings? To give it visibility.

**Comment by talregev** [comment]
> @talregev Would you mind opening an issue with the int/socket confusion warnings? To give it visibility.

I open an issue: 
https://github.com/curl/curl/issues/15582

**Comment by talregev** [comment]
I disable warning as errors to see what happen next.

**Comment by vszakats** [comment]
Thanks @talregev! I merged this separately and pushed in batch together with last round of fixes.

**Pull request closed without merging**
