### PR TITLE
travis: sanitize=address,undefined,signed-integer-overflow

### PR DESCRIPTION
**Pull request by bagder**
... using clang

### CODE REVIEW

**Comment by bagder** [comment]
I don't understand this error, nor do I understand why it build nghttp2 again here since it is supposed to be cached... :-/

**Comment by MarcelRaad** [comment]
Mixing clang and GCC also doesn't look right, does it?

```
      C compiler:     clang
      CFLAGS:         -fsanitize=address,undefined,signed-integer-overflow -fno-sanitize-recover=undefined,integer -Wformat -Werror=format-security -Werror=array-bounds -g
      LDFLAGS:        -fsanitize=address,undefined -fno-sanitize-recover=undefined,integer
      C++ compiler:   g++-8
      CXXFLAGS:       -g -O2
      CXXCPP:         g++-8 -E
      C preprocessor: clang -E
```

**Comment by bagder** [comment]
Exactly, that's the side-effect of nghttp2 getting built (again) with the setup that is meant only for the curl build. I tried to setup so that the nghttp2 build would remain cached and thus not having to get rebuilt so that the CFLAGS + clang settings wouldn't be used in the nghttp2 build...

**Comment by MarcelRaad** [comment]
`CXX="g++-8" CC="gcc-8" CFLAGS="" LDFLAGS="" LIBS="" ./configure` maybe for nghttp2?

**Comment by bagder** [comment]
Excellent suggestion. Rebased and squashed to make it easier to review.

**Pull request closed without merging**
