### PR TITLE
ossfuzz: check in generated corpora

### PR DESCRIPTION
**Pull request by cmeister2**
Add the current generated corpora to the codebase so that the cases are
regressibly tested in CI. Also fix up a few minor issues with code warnings.

### CODE REVIEW

**Comment by bagder** [comment]
This merge increases the number of files in the git repo by **67%**(!) (from 2835 to 4780). For files that the vast majority of people won't ever use, and certainly not change.

Would it be possible to consider putting the fuzz corpora files in a *separate* git repo to reduce the impact on users and devs not playing the fuzz game?

**Comment by cmeister2** [comment]
That's possibly doable. If there's a way of packaging the automated corpora into a zip file, say, we could download it as part of the build process. I have no problem with doing this to be honest assuming I can get it working.

**Comment by bagder** [comment]
I was thinking a separate `curl-fuzz-corpora` repo, that the build process would clone/update into the correct place. But thinking about it further, would it perhaps make sense to then move the entire `tests/fuzz` directory to a `curl-fuzzer` repo ?

Either way, we could then create the repo under the curl org on github and @cmeister2 should of course get permission to push to it!

A downside with such a separate repo is that it adds another step for users who download a regular tarball and want to do fuzzing, but I think we can cross that bridge later if anyone feels that need.

What approach do think would work best?

**Comment by cmeister2** [comment]
I mean, moving everything sounds like a pretty reasonable solution. It'll necessitate an update to oss-fuzz to point to a different place, and we'll have to work out the best way of building the code - possibly having the main CURL repo as a git submodule? I'm not sure. It would make my life a bit easier, obviously, as I don't have write access to the main repository.

**Comment by jay** [comment]
@cmeister2 I created a curl-fuzzer repo and you should have push access to that repo once you accept the invitation. Please review [push access guidelines](https://github.com/curl/curl/wiki/push-access-guidelines), most of which applies here (just substitute curl-fuzzer for curl). And as it says read the CONTRIBUTE for commit message style. All commits should have a link to whatever issue and/or pr that is related. Look at arbitrary commits in the curl repo for examples on all of this. The no-forced-push can be ignored for right now and discussion can continue for how best to move it over. 

As to your suggestion re submodules I think if there was a way to track master then I'm thinking curl-fuzz would have its own CI and run the fuzzer on the latest curl master.

**Comment by bagder** [comment]
I also moved over all commits that have been done to `tests/fuzz` into https://github.com/curl/curl-fuzzer and added a README stub.

**Comment by cmeister2** [comment]
I think if we're going to do this then we need to keep a fuzzing CI task in the main curl branch, otherwise fuzzing won't be tested for pull requests. We already have precedent for downloading and compiling programs from other locations; I think it would be good if we can do the same for the fuzzer.

I actually think we'll get most confidence out of having CI enabled on both sides:

- If it's enabled in the fuzzer repo, then PRs to the fuzzer repo will test with the latest master of curl.
- If it's enabled in the curl repo, then PRs to the curl repo will test with the latest master of the fuzzer.

Thoughts?

**Comment by bagder** [comment]
I agree @cmeister2. Having them done in both repos seems logical so that they get triggered on changes in either repo.

**Comment by cmeister2** [comment]
In which case, I'll close this PR and have a look at the best way of setting up the other repo. @bagder: if you could enable Travis for the other repo, that'd be great. Obviously there's no travis.yml file yet, but there will be.

**Pull request closed without merging**
