### PR TITLE
CI: update 32-bit CI to Ubuntu 24.04 and enable more

### PR DESCRIPTION
**Pull request by dfandrich**
Enable librtmp, libssh, libidn2 and c-ares support for broader test
coverage. Bump the gcc version to 14.

Closes #15068

### CODE REVIEW

**Comment by vszakats** [comment]
How about this variation for impacket:
```
--- a/.github/workflows/linux32.yml
+++ b/.github/workflows/linux32.yml
@@ -61,7 +61,9 @@ jobs:
           sudo dpkg --add-architecture i386
           sudo apt-get update -y
           sudo apt-get install -y --no-install-suggests --no-install-recommends libtool autoconf automake pkgconf stunnel4 ${{ matrix.build.install_packages }}
-          sudo python3 -m pip install impacket
+          python3 -m venv $HOME/venv
+          source $HOME/venv/bin/activate
+          python3 -m pip install impacket
         name: 'install prereqs'
 
       - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
@@ -83,7 +85,9 @@ jobs:
       - run: make V=1 -C tests
         name: 'make tests'
 
-      - run: make V=1 test-ci
+      - run: |
+          source $HOME/venv/bin/activate
+          make V=1 test-ci
         name: 'run tests'
         env:
           TFLAGS: "${{ matrix.build.tflags }}"
```

**Comment by dfandrich** [comment]
What's the point in using a venv here? This is a throwaway environment.

**Comment by vszakats** [comment]
To install impacket locally and not need the `--break-system-packages` option. It's the method used in other jobs.
The overhead is minimal, and plays nicely with python/pip.

**Comment by vszakats** [comment]
Hm, looking at a few runs (I've been testing this in #15065), installing venv seems to add an unexpected 2-3 seconds to the install step, so maybe it's better to opt-out from the enforcement. Could be true for other jobs that went with the venv way too.

**Review by bagder — APPROVED** [review]

**Review by vszakats — APPROVED** [review]

**Pull request closed without merging**
