### PR TITLE
lib655: silence compiler warning

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by jay** [comment]
I don't get a warning for this also and neither does the CI. How is it being compiled that you see a warning?

**Comment by vszakats** [comment]
It appears on Travis CI:
https://travis-ci.org/curl/curl/jobs/345254442#L3044

**Comment by vszakats** [comment]
With this one I can't spot any connection with PR https://github.com/curl/curl/pull/2334 (which belongs to the above Travis CI log). The warning looks valid, a global var is defined without a declaration, even though the variable is in this file only. It was committed recently in 23713645d4e9ae00a3065f7a3d995e57748da4c7.

**Comment by MarcelRaad** [comment]
Yes, warnings in tests and examples are easy to miss as they're never treated as errors.

**Comment by bagder** [comment]
I'm fixing that mistake in #2337!

**Comment by bagder** [comment]
I assume you meant to say that it silences a warning in lib655.c ?

**Comment by vszakats** [comment]
Yes, that's what I meant. I'm open to suggestions for better phrasing!

**Comment by bagder** [comment]
Nah, I think the phrasing is fine if it just mentions the right file! =)

**Comment by vszakats** [comment]
Wow, indeed, I messed up a copy-paste, thanks a bunch for the heads up! Correcting it right away.

**Pull request closed without merging**
