### PR TITLE
CI, remove unnecessary `enable-tls13`

### PR DESCRIPTION
**Pull request by icing**
and specify libdir for smaller curl config. Just a tidy up.

### CODE REVIEW

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Is this "draft" on purpose/for a reason?

**Comment by icing** [comment]
> Is this "draft" on purpose/for a reason?

I started doing drafts to save you time while I check if it is really working.😌

**Comment by jay** [comment]
I'm going to land this but not with the rpath removals because that causes the system ossl to be loaded

ossl rpath:
* libcurl/8.6.0-DEV OpenSSL/3.1.3 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libpsl/0.21.0

ossl no rpath:
* libcurl/8.6.0-DEV OpenSSL/3.0.2 zlib/1.2.11 brotli/1.0.9 zstd/1.4.8 libpsl/0.21.0

**Comment by jay** [comment]
It seems to me the GHA cache of the OpenSSL 3.1.3 build would be affected so I [deleted it](https://github.com/curl/curl/actions/caches) from the cache before landing this PR in master. I will check the related jobs to make sure it's regenerated and succeeds.

**Pull request closed without merging**
