### PR TITLE
Activating Open Collective

### PR DESCRIPTION
**Pull request by monkeywithacupcake**
Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/curl ❤️
  
  It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
You can also add a "Donate" button to your website and automatically show your backers and sponsors there with our widgets. Have a look here: https://opencollective.com/widgets

  P.S: As with any pull request, feel free to comment or suggest changes. The only thing "required" are the placeholders on the README because we believe it's important to acknowledge the people in your community that are contributing (financially or with code!).

  Thank you for your great contribution to the open source community. You are awesome! 🙌
  And welcome to the open collective community! 😊

  Come chat with us in the #opensource channel on https://slack.opencollective.com - great place to ask questions and share best practices with other open source sustainers!

### CODE REVIEW

**Comment by bagder** [comment]
I think we could mention it somewhat, but this PR is far too excessive for my taste.

**Comment by jay** [comment]
should we be encouraging donations through a website like that, they take 13% fees. for example according to them coinbase gave $5500 to the project but

$5,500 -$275 (host fee) -$275 (Open Collective fee) -$159.8 (payment processor fee) = $4,790.2

is that normal for donation sites to take fees like that for an open source project

**Comment by jzakrzewski** [comment]
Seems like awful lot of money wasted...

**Comment by bagder** [comment]
Thanks for your input on this.

1. We basically don't get donations at all, so I figured maybe this sort of exposure could change it. I sometimes get contacted by orgs who want to donate to us, like the sponsor now visible in the README.
2. It is expensive, yes, but is not getting any donations at all then a better situation?
3. We don't really have any particular need for money, and in fact we have a little problem now to decide how to spend it.
4. coinbase pretty much required we'd join this org to get the donation through it

**Pull request closed without merging**
