### PR TITLE
sectransp: handle errSSLPeerAuthCompleted from SSLRead()

### LINKED ISSUE #3932: Apple Secure Transport: ignore errSSLPeerAuthCompleted if CURLOPT_SSL_VERIFYPEER is 0
### I did this

my code contains:
curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);

I use curl with Apple Secure Transport.

During the handshake SSLRead returns -9841 which translates into https://developer.apple.com/documentation/security/1503828-secure_transport_result_codes/errsslpeerauthcompleted

Curl terminates the connection due to SSLRead returned an error. The select call in the function sectransp_recv chooses the "default" entry.

### I expected the following

I would presume that this return code is expected when CURLOPT_SSL_VERIFYPEER is set to 0.

Thus, curl should gracefully accept that return code with CURLOPT_SSL_VERIFYPEER set to 0.

### curl/libcurl version

7.54

However, the issue seems to be present in the current GIT HEAD.

### operating system

macOS 10.14.5

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: smuellerDD on github
Fixes #3932

### CODE REVIEW

**Comment by smuellerDD** [comment]
Does not compile:

vtls/sectransp.c:3217:66: error: use of undeclared identifier 'data'; did you
      mean 'atan'?
          CURLcode result = verify_cert(SSL_CONN_CONFIG(CAfile), data,
                                                                 ^~~~
                                                                 atan

**Comment by smuellerDD** [comment]
I have done some additional testing. One includes adding the CA certificate chain as a PEM bundle. That bundle is set as:

CKINT(curl_easy_setopt(curl, CURLOPT_CAINFO,
                                       net->certs_ca_file));
CKINT(curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 1L));
CKINT(curl_easy_setopt(curl, CURLOPT_CERTINFO, 1L));

Yet, I still get the errSSLPeerAuthCompleted error. So, it may be a bigger issue at work here.

**Comment by bagder** [comment]
The return code may appear no matter which curl options you use. I logged in to my mac and fixed the build problem now and pushed it here so you can try out if the retried SSLRead() call works...

**Comment by smuellerDD** [comment]
Confirmed, working. Thanks!

**Pull request closed without merging**
