### PR TITLE
tool_operate: CURLOPT_PROXY_CAINFO defaults to cacert

### PR DESCRIPTION
**Pull request by jay**
If config->proxy_cacert is unset then default CURLOPT_PROXY_CAINFO to
config->cacert.

Closes #xxxx

---

Currently `CURLOPT_PROXY_CAPATH` falls back on regular capath if there's no proxy specific capath, but `CURLOPT_PROXY_CAINFO` does not fall back on regular cacert if there's no proxy specific cacert. I wonder if that was an oversight? This change fixes it. On Windows it allows me to specify an HTTPS proxy without having to use `--proxy-cacert`, since the cacert bundle is detected automatically (FindWin32CACert), but there is no automatic detection for proxy cacert, so now it will default to cacert.

An alternative would be automatic detection for proxy cacert as well, that way if a user did something like `--cacert specific-host.crt` curl would still call FindWin32CACert to find the default bundle for the proxy cacert, which would be more robust. Thoughts?

/cc @rousskov

### CODE REVIEW

**Comment by rousskov** [comment]
@jay, I suspect (but cannot verify) that our thinking was that a _single_ CA is unlikely to validate both the proxy and the origin server because most proxy certificates do not come from well-known CAs (but I am sure there are many situations where a single CA would work). My speculation is based primarily on the following sentence in our HTTPS [commit](https://github.com/curl/curl/commit/cb4e2be7c6d42ca0780f8e0a747cecf9ba45f151) documentation:

> All --proxy-foo options are independent from their --foo counterparts,
> except --proxy-crlfile which defaults to --crlfile and --proxy-capath
> which defaults to --capath.

Both CRL file and CA path point to a "collection" of "often sharable" things while CA certificate is a single entity that is often server-specific.

Please do not misinterpret my comment as a negative vote. I have no standing and am just trying to guess what our original (and possibly wrong) thinking was.

**Comment by bagder** [comment]
I casually for this change.

I don't think there's a lot to lose by defaulting to using the same CA bundle. If users happen to share them for servers and proxies, it will make slightly more connections work at first try. If they have separate bundles, they need to set both options anyway and this change has no negative effect.

**Comment by jay** [comment]
> Both CRL file and CA path point to a "collection" of "often sharable" things while CA certificate is a single entity that is often server-specific.

@rousskov Ok. CA bundles are a pretty common use of cacert, so I would argue we have the same collection-style considerations.

> I'm casually for this change.

@bagder I agree with the comments you made however since it seems like you're hedging a bit I can leave this open to gather more feedback.

**Comment by jay** [comment]
I'm having second thoughts about this after a review and fixing some problems in the code. Though on Windows the curl tool will auto-detect the certificate bundle it is more common on Linux for example for libcurl to use a compile-time string. So consider this for a moment:
~~~
curl --cacert foo.pem --proxy https://bar https://qux
~~~
On Linux --proxy-cacert since it's unset I think should use the compile-time value in libcurl, if any. 

I've updated this PR basically doing a 180. The first commit in the branch shows the problems found and fixed, and does what was originally proposed by defaulting --proxy-cacert to --cacert. However the second commit changes it so that --proxy-{cacert,capath,crlfile} do not use their regular non-proxy counterpart. Since this was not documented and very early on, I think we could do this. Recall as I mentioned above if there's a compile-time value that is what would be used. Windows is a little more complicated since its detection is in the curl tool, and I have not addressed that yet.

Please take a look at both commits and tell me what you think.

**Comment by jay** [comment]
@bagder Even if we don't reach a consensus by 7.53 on the whole thing I think perhaps we could all agree on the compile time CURL_CA_BUNDLE string set as the default for STRING_SSL_CAFILE_PROXY, see [this line](https://github.com/curl/curl/pull/1257/files#diff-8fb104c402dc51bdffef05a372f32aa2R581).

**Comment by bagder** [comment]
Yes, that seems like a totally sensible thing to do by default. And with a sensible compile-time default, I agree that there's less of a need for fancy tool-side things.

**Comment by jay** [comment]
I have landed the fix to default to CURL_CA_BUNDLE. Remaining issues are in the tool for the next feature window. I see one of two routes for consistency:

1. Stop --proxy-capath and crl from using their non-proxy counterpart options as defaults. Also (Windows): Same auto-detection in tool for Windows ca cert bundle in PATH for --proxy-cacert as we do now for --cacert.
2. or make --proxy-cacert default to --cacert to be consistent with the other two.

Just to recap we have room to move here because this isn't documented, and I had originally proposed 2 but now think 1 is better.

**Comment by tmds** [comment]
curl is picking up the SSL_CERT_DIR and SSL_CERT_FILE environment variables.
Probably when these are set, they should also apply to the proxy?

**Comment by jay** [comment]
> curl is picking up the SSL_CERT_DIR and SSL_CERT_FILE environment variables.
> Probably when these are set, they should also apply to the proxy?

Thanks for your input. Work on this issue has stalled but I will keep that in mind.

**Pull request closed without merging**
