### PR TITLE
tests: speed up builds with single-binary test bundles

### PR DESCRIPTION
**Pull request by vszakats**
Add support for single-block binaries that contain all libtests and
unit tests respectively.

Enable with:
- autotools: `--enable-test-bundles`
- cmake: `-DCURL_TEST_BUNDLES=ON`

(They are compatible with `--enable-unity` and `-DCMAKE_UNITY_BUILD=ON`
options, for further speed-up.)

Makes libtests and unit tests build _fast_, needing little disk space
even in static mode. Similar to CMake unity mode, but with a custom
script, also supporting autotools builds.

The price is having to deal with symbols/macros colliding between
`lib*.c` and `unit*.c` sources. Maybe with naming conventions or other
solutions this can be improved gradually and reduce the need for manual
intervention by `mk-bundle.mk`. I've included a script that does the bulk
of detecting name collisions.

Also:
- CI: enable test bundles.
- CI: build tests in more jobs:
  - aws-lc cmake +6s
  - linux-mingw cmake +12s
- lib2305: fix FILE handle leak.
- unit1661: fix memleak found by torture test by releasing the `bufref`
  structure in `unit_stop()` that was allocated in `unit_setup()`.
  ```
  test 1661...[bufref unit tests]
  Leak detected: memory still allocated: 13 bytes
   allocated by /home/runner/work/curl/curl/tests/unit/unit1661.c:70
   1661: torture FAILED: function number 1 in test.
  ```
  Ref: https://github.com/curl/curl/actions/runs/10967279334/job/30456745290?pr=14772#step:8:41

Similar test suite builds with autotools default and cmake+bundle+unity:
- GHA/Linux: 33s vs 7s
  https://github.com/curl/curl/actions/runs/10705668823/job/29681617374
- GHA/macOS 34s vs 2s
  https://github.com/curl/curl/actions/runs/10705668813/job/29681632885
- GHA/FreeBSD: 15m25 vs 6m21 (full workflow time, ~qemu)
  https://github.com/curl/curl/actions/runs/10705668811/job/29681607915
- GHA/Cygwin: 9m52 vs 32s
  https://github.com/curl/curl/actions/runs/10705668809/job/29681609965
- GHA/MSYS2: 3m52 vs 14s
  https://github.com/curl/curl/actions/runs/10705668808/job/29681624295
- GHA/mingw-w64: 5m45 vs 30s
  https://github.com/curl/curl/actions/runs/10705668808/job/29681628787

Autotools test suite builds compared between master → `--enable-test-bundles`:
- GHA/Linux: 33s → 9s (run tests: 22m23 → 20m44)
  https://github.com/curl/curl/actions/runs/10710030193/job/29695932185
  https://github.com/curl/curl/actions/runs/10967831456/job/30458220344
- GHA/macOS: 25s → 4s (run tests: 2m58 → 2m24)
  https://github.com/curl/curl/actions/runs/10710030195/job/29695938444
  https://github.com/curl/curl/actions/runs/10967831452/job/30458225762
- GHA/non-native (FreeBSD): 4m8 → 3m12 (full workflow time, ~qemu)
  https://github.com/curl/curl/actions/runs/10710030198/job/29695928401
  https://github.com/curl/curl/actions/runs/10967831458/job/30458212692
- GHA/Cygwin: 9m25 → 1m9 (run tests: 9m19 → 3m28)
  https://github.com/curl/curl/actions/runs/10710030212/job/29695928213
  https://github.com/curl/curl/actions/runs/10967831453/job/30458213268
- GHA/MSYS2: 3m54 → 32s (run tests: 6m3 → 3m59)
  https://github.com/curl/curl/actions/runs/10710030190/job/29704850591
  https://github.com/curl/curl/actions/runs/10967831449/job/30459280005
- GHA/mingw-w64: 5m42 → 1m5 (run tests: 7m41 → 5m36)
  https://github.com/curl/curl/actions/runs/10710030190/job/29704852058
  https://github.com/curl/curl/actions/runs/10967831449/job/30459280862
- Azure MSYS2 mingw64 openssl: 38m55 → 11m58
  https://dev.azure.com/daniel0244/curl/_build/results?buildId=25546&view=logs&j=b58b8c59-0f61-52e9-0f9e-fad562a1e77f&t=0f9230a7-3b10-53ca-9938-700ece377c5e
  https://dev.azure.com/daniel0244/curl/_build/results?buildId=25547&view=logs&jobId=39473db1-3945-55d5-deb5-c218fad88dce&j=b58b8c59-0f61-52e9-0f9e-fad562a1e77f&t=0f9230a7-3b10-53ca-9938-700ece377c5e
- Azure Ubuntu default: 2m15 → 55s (all build)
  https://dev.azure.com/daniel0244/curl/_build/results?buildId=25546&view=logs&j=9d58b9ac-e1e6-53b6-f83a-1f9f1d912522&t=a6b38d83-e7cf-5a9b-c762-a178412717b7
  https://dev.azure.com/daniel0244/curl/_build/results?buildId=25547&view=logs&jobId=39473db1-3945-55d5-deb5-c218fad88dce&j=9d58b9ac-e1e6-53b6-f83a-1f9f1d912522&t=a6b38d83-e7cf-5a9b-c762-a178412717b7

Cmake test suite builds compared between master → `-DCURL_TEST_BUNDLES=ON` + unity:
- GHA/Linux: 29s → 7s (run tests: 4m50 → 4m57, 20m43 → 20m45)
  https://github.com/curl/curl/actions/runs/10710030193/job/29695941814
  https://github.com/curl/curl/actions/runs/10705668823/job/29681622201
- GHA/Linux old: 44s → 13s (bundle+no unity) (run tests: 5m5 → 5m6)
  https://github.com/curl/curl/actions/runs/10718264094/job/29719794727
  https://github.com/curl/curl/actions/runs/10718653175/job/29721009613
- GHA/macOS: 32s → 2s (run tests: 2m43 → 2m40)
  https://github.com/curl/curl/actions/runs/10710030195/job/29695931956
  https://github.com/curl/curl/actions/runs/10705668813/job/29681638937
- GHA/non-native (*BSD): inconclusive (full workflow time, ~qemu)
  https://github.com/curl/curl/actions/runs/10710030198
  https://github.com/curl/curl/actions/runs/10705668811
- GHA/Cygwin: 3m9 → 32s
  https://github.com/curl/curl/actions/runs/10710030212/job/29695929075
  https://github.com/curl/curl/actions/runs/10705668809/job/29681609965
- GHA/MSYS2: 2m24 → 14s
  https://github.com/curl/curl/actions/runs/10710030190/job/29704850996
  https://github.com/curl/curl/actions/runs/10705668808/job/29681624295
- GHA/mingw-w64: 3m56 → 30s (run tests: 4m2 → 3m52)
  https://github.com/curl/curl/actions/runs/10710030190/job/29704852219
  https://github.com/curl/curl/actions/runs/10705668808/job/29681631393
- GHA/mingw-w64-old: 7m19 → 1m44 (run tests: 3m30 → 2m53)
  https://github.com/curl/curl/actions/runs/10710030190/job/29704849763
  https://github.com/curl/curl/actions/runs/10705668808/job/29681622329
- GHA/MSVC: 3m22 → 13s (run tests: 9m43 → 4m22)
  https://github.com/curl/curl/actions/runs/10710030190/job/29704850411 
  https://github.com/curl/curl/actions/runs/10705668808/job/29681623313
- AppVeyor CI MSVC 2008: 4m3 → 45s (full build)
- AppVeyor CI MSVC 2010: 2m56 → 1m8 (full build)
- AppVeyor CI MSVC 2022: 10m19 → 2m23 (full build)
  https://ci.appveyor.com/project/curlorg/curl/builds/50538455
  https://ci.appveyor.com/project/curlorg/curl/builds/50536558
- AppVeyor CI total build time: 10m30 (master) → 6m48 (unity) → 4m5 (bundle) → 3m24 (bundle+unity) → 5m7 (bundle+unity+all jobs building tests)

---

- [ ] disable bundles for torture tests, or replace allocs with `Curl_cmalloc()` in test code?
- [x] replace `runtests.pl -bundle` option with something automatic? This would allow running it directly without having to add `-bundle` manually to match such build. [→ FUTURE]
- [x] cmake, autotools: disable by default.
- [x] CI: explicitly enable, except few places (Linux and/or macOS) to keep testing non-bundle.
- [x] GHA/old-linux: enable building tests in the `cmake build-only` job.
- [x] GHA/windows: enable building tests in `linux-mingw, AM/CM gcc` jobs.
- [x] add support for `tests/server`. + merge `mk-bundle.pl`, `mk-bundle-server.pl`? and perhaps `mk-unity.pl`? [→ SEPARATE PR]
- [x] rebase on #14971.
- [x] rebase om #14815.
- [x] rebase on #14765.
  (to give a speed boost for building `tests/servers`)
- [x] rebase on #14789.
- [x] fix autotools builds not switching to bundle mode.
- [x] add support to autotools.
- [x] soft rebase on #14765.
- [x] fix a second round of unit test startup failures on Windows: https://github.com/curl/curl/actions/runs/10704030336/job/29676019471
- [x] tidy up deprecation warning suppression.
- [x] fix widespread and consistent test failures on Windows: https://github.com/curl/curl/actions/runs/10702381760/job/29670489904
- [x] enable building tests for all AppVeyor CI jobs. It's +10–80 seconds per job with unity + bundle.
- [x] fix `getaddrinfo()` unwanted override yet again.

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #14772 at [2bdff798](https://github.com/curl/curl/commit/2bdff7988e55095f7eff6cac565092ec1bef8a35):

[Test 500 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 504 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 501 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 502 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 507 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 508 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

[Test 510 failed](https://github.com/curl/curl/actions/runs/10693521305/job/29643817400#check-step-23), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 9 different CI jobs (the link just goes to one of them).

There are more failures, but that's enough from Gha.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
This is ready now for the most part.

Remains is to set it up in CI without enabling these features by default.
Though, if the reception is good, we might as well enable it by default.
It also gives a significant speed (and disk consumption) improvements
in local builds.

**Comment by vszakats** [comment]
valgrind result for test 1661 fallout:
```
* Servers: SSL HTTP-IPv6 HTTP-unix FTP-IPv6 
***************************************** 
test 1661...[bufref unit tests]
 2 functions to make fail
 valgrind ERROR ==5619== 29 bytes in 1 blocks are possibly lost in loss record 1 of 1
==5619==    at 0x4846828: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==5619==    by 0x246D55: curl_dbg_malloc (in /home/runner/work/curl/curl/tests/unit/units)
==5619==    by 0x13D752: test_unit1661 (in /home/runner/work/curl/curl/tests/unit/units)
==5619==    by 0x1430C5: main (in /home/runner/work/curl/curl/tests/unit/units)
==5619== 
** MEMORY FAILURE
Leak detected: memory still allocated: 13 bytes
At 53c8cc8, there's 13 bytes.
 allocated by /home/runner/work/curl/curl/tests/unit/unit1661.c:70
LIMIT /home/runner/work/curl/curl/lib/strdup.c:114 malloc reached memlimit
 1661: torture FAILED: function number 1 in test.
 invoke with "-t1" to repeat this single case.
TESTDONE: 1 tests were considered during 2 seconds.
TESTDONE: 0 tests out of 1 reported OK: 0%

FAIL 1661: 'bufref unit tests' unittest, bufref

TESTFAIL: These test cases failed: 1661
```
https://github.com/curl/curl/actions/runs/10967279334/job/30456745290?pr=14772#step:8:41

**Comment by vszakats** [comment]
Torture test fallout fixed.

**Comment by vszakats** [comment]
Not sure what's happening, but here's a flaky torture test:
```
test 2305...[WebSocket curl_ws_recv() loop reading three larger frames]
 84 functions found, but only fail 25 (29.76%)
** MEMORY FAILURE
Open FILE handles left at:
fopen() called at /home/runner/work/curl/curl/tests/libtest/lib2305.c:46
LIMIT /home/runner/work/curl/curl/lib/cf-socket.c:1585 recv reached memlimit
 2305: torture FAILED: function number 81 in test.
 invoke with "-t81" to repeat this single case.
```
Ref: https://github.com/curl/curl/actions/runs/10968428889/job/30459756924?pr=14772#step:8:4061

**Comment by vszakats** [comment]
Despite torture tests finding TWO leaks in the test code itself,
I'm wondering if bundling tests into a single executable reduces 
the effectivenes of torture tests for libcurl code?

The libtests bundle have ~20 alloc calls in total, unit tests ~12,
while normally a single test has none or just a couple. Wouldn't
those extra calls "water down" the chance for the torture test to
hit on an allocation inside libcurl, which is what we're interested
about?

If this a valid problem, it's trivial to disable bundles for the 4 torture
CI jobs, but it's also an option to replace the allocations with
non-debug versions (`Curl_cmalloc()`) and exclude them for
all builds, because we're not really interesed in leaks in the test
code.

What do you think?

/cc @bagder

**Comment by vszakats** [comment]
Apart from one pending question/decision: https://github.com/curl/curl/pull/14772#issuecomment-2365067290,
this is ready to merge.

(The same optimization can be done for `tests/server`, but I'll do that in a separate PR.)

**Comment by bagder** [comment]
>  I'm wondering if bundling tests into a single executable reduces the effectivenes of torture tests for libcurl code?

I don't follow. Why would they? Are the bundled versions of the tests executing more/other code than the "regular" builds?

**Comment by vszakats** [comment]
> > I'm wondering if bundling tests into a single executable reduces the effectivenes of torture tests for libcurl code?
> 
> I don't follow. Why would they? Are the bundled versions of the tests executing more/other code than the "regular" builds?

They don't, besides a short lookup / dispatch in `main()` (that's not using malloc()). There is of course much more code in the binary, but all is idle besides the actual test executed.

It was curious the bundles caught two new leaks, that were never caught before. But this was more like a wild guess to explain it, and not breaking anything.

**Comment by bagder** [comment]
> It was curious the bundles caught two new leaks, that were never caught before. But this was more like a wild guess to explain it, and to not break something by accident.

I have not seen those fixes so I cannot comment on why they were not found before. Can you point them out for me? I suspect maybe it rather indicatives that we might have include problems or something in the affected tests.

**Comment by vszakats** [comment]
The two sub-commits with the fixes:

- lib2305: https://github.com/curl/curl/pull/14772/commits/657f6c3b63bb7b2c8087f292b4903658fd769069
  (details in the commit message)

- unit1661: https://github.com/curl/curl/pull/14772/commits/76baa18488816ac93662c3ec737cab291c4ebb66
  details: https://github.com/curl/curl/pull/14772#issuecomment-2364734343

**Comment by bagder** [comment]
As I suspected, fix here:  #15007

I'll ponder on a system where this can be caught better.

**Comment by vszakats** [comment]
Oh right, indeed, nice catch!

**Pull request closed without merging**
