### PR TITLE
GHA: ignore pushes when only other yml files are changed

### PR DESCRIPTION
**Pull request by andy5995**
The first time I tried this... I'm not sure if I got the syntax correct yet. I'll finish it up after a little feedback

### CODE REVIEW

**Comment by andy5995** [comment]
The intent of this is to automatically prevent a lot of tests from running. For example, if 'linux.yml' is the only file changed, only that workflow will run. Right now, most all workflows will run.

**Comment by cmeister2** [comment]
It's not obvious to me that having a negating rule in `paths-ignore` is valid syntax; https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore seems to indicate that the `!` character only operates in the `paths` key.

**Comment by andy5995** [comment]
@cmeister2 Thanks for pointing that out!

**Comment by andy5995** [comment]
rebased

**Comment by andy5995** [comment]
Apparently https://github.com/curl/curl/pull/10742 was merged instead, so closing this PR.

**Pull request closed without merging**
