### PR TITLE
GHA: add an -O3 build of OpenSSL

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
Unfortunately, GHA does not seem to run a new enough gcc to catch the #9450 issue...

**Comment by monnerat** [comment]
> Unfortunately, GHA does not seem to run a new enough gcc to catch the https://github.com/curl/curl/pull/9450 issue...

You don't need -O3 for that: -O2 causes it too with a younger gcc :-)

**Comment by bagder** [comment]
Ok, but the build [here](https://github.com/curl/curl/runs/8246146596?check_suite_focus=true) doesn't show the warning. Is the `-g` perhaps necessary in combination with the `-O3` to trigger the warning?

**Comment by monnerat** [comment]
I tried with only `CFLAGS=-O2` and the warning occurs.
I can't find the gcc version info in your job logs, but from what I can note from Internet searches, default for Ubuntu 20.04 is gcc9.

**Comment by bagder** [comment]
Okay, let's output the gcc version to see.

**Comment by bagder** [comment]
Yeps, `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` it says. But no warning!

**Comment by pheiduck** [comment]
> Yeps, `gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0` it says. But no warning!

on ubuntu 20.04 its possible to use gcc11:
https://launchpad.net/~ubuntu-toolchain-r/+archive/ubuntu/ppa

**Comment by bagder** [comment]
Thanks, I'll try that!

**Comment by bagder** [comment]
@pheiduck do you know why [this](https://github.com/curl/curl/pull/9454/commits/36084e858232b16db86bf51327877ef08e762069) isn't working? [log showing the error](https://github.com/curl/curl/runs/8273919584?check_suite_focus=true#step:2:47)

**Comment by pheiduck** [comment]
> @pheiduck do you know why [this](https://github.com/curl/curl/pull/9454/commits/36084e858232b16db86bf51327877ef08e762069) isn't working? [log showing the error](https://github.com/curl/curl/runs/8273919584?check_suite_focus=true#step:2:47)

@bagder you need to add the PPA first:
```
sudo add-apt-repository ppa:ubuntu-toolchain-r/ppa
sudo apt update
```

**Comment by bagder** [comment]
> ubuntu 22.04

Okay. I don't understand how you figure that out. But are you saying gcc-11 is available for 20.04 so if i try that instead it should work?

**Comment by monnerat** [comment]
You got it: https://github.com/curl/curl/runs/8287859831?check_suite_focus=true#step:9:47 !

**Comment by bagder** [comment]
I'll merge this after #9455 so that it can go green at once

**Pull request closed without merging**
