### PR TITLE
tool_operate: allow SSL_CERT_FILE and SSL_CERT_DIR

### LINKED ISSUE #11325: Curl CLI should handle both SSL_CERT_FILE and SSL_CERT_DIR (at the same time)
### I did this

When using both `SSL_CERT_FILE` and `SSL_CERT_DIR` environment variable, `curl` honors only the former:

~~~
$ strace curl https://www.example.com < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 6
stat("/etc/ssl/certs/e83d98dd.0", 0x7ffcf70f8310) = -1 ENOENT (No such file or directory)

$ SSL_CERT_FILE=./ssl/empty strace curl https://www.example.com < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "./ssl/empty", O_RDONLY) = -1 ENOENT (No such file or directory)

$ SSL_CERT_DIR=./ssl/certs strace curl https://www.example.com < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 6
stat("./ssl/certs/e83d98dd.0", 0x7fff4d848d60) = -1 ENOENT (No such file or directory)

$ SSL_CERT_FILE=./ssl/empty SSL_CERT_DIR=./ssl/certs strace curl https://www.example.com < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/etc/ssl/certs/ca-certificates.crt", O_RDONLY) = 6
stat("./ssl/certs/e83d98dd.0", 0x7fffa9e072f0) = -1 ENOENT (No such file or directory)
~~~

### I expected the following

I would expect the behavior to be consistent with OpenSSL which handles both at the same time:

~~~
$ strace openssl s_client -connect www.example.com:443 < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/ssl/ct_log_list.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/ssl/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/lib/ssl/certs/e83d98dd.0", 0x7fff93ef8fb0) = -1 ENOENT (No such file or directory)
stat("/usr/lib/ssl/certs/3513523f.0", {st_mode=S_IFREG|0644, st_size=1338, ...}) = 0
openat(AT_FDCWD, "/usr/lib/ssl/certs/3513523f.0", O_RDONLY) = 4
stat("/usr/lib/ssl/certs/3513523f.1", 0x7fff93ef8fb0) = -1 ENOENT (No such file or directory)

$ SSL_CERT_FILE=./ssl/empty strace openssl s_client -connect www.example.com:443 < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/ssl/ct_log_list.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./ssl/empty", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("/usr/lib/ssl/certs/e83d98dd.0", 0x7ffdfa475c70) = -1 ENOENT (No such file or directory)
stat("/usr/lib/ssl/certs/3513523f.0", {st_mode=S_IFREG|0644, st_size=1338, ...}) = 0
openat(AT_FDCWD, "/usr/lib/ssl/certs/3513523f.0", O_RDONLY) = 4
stat("/usr/lib/ssl/certs/3513523f.1", 0x7ffdfa475c70) = -1 ENOENT (No such file or directory)

$ SSL_CERT_DIR=./ssl/certs strace openssl s_client -connect www.example.com:443 < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/ssl/ct_log_list.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/usr/lib/ssl/cert.pem", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/e83d98dd.0", 0x7ffe31068200) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/3513523f.0", 0x7ffe31068200) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/3513523f.0", 0x7ffe31068200) = -1 ENOENT (No such file or directory)

$ SSL_CERT_FILE=./ssl/empty SSL_CERT_DIR=./ssl/certs strace openssl s_client -connect www.example.com:443 < /dev/null 2>&1 | grep /ssl/
openat(AT_FDCWD, "/usr/lib/ssl/openssl.cnf", O_RDONLY) = 3
openat(AT_FDCWD, "/usr/lib/ssl/ct_log_list.cnf", O_RDONLY) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "./ssl/empty", O_RDONLY) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/e83d98dd.0", 0x7ffd0e5362d0) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/3513523f.0", 0x7ffd0e5362d0) = -1 ENOENT (No such file or directory)
stat("./ssl/certs/3513523f.0", 0x7ffd0e5362d0) = -1 ENOENT (No such file or directory)
~~~

The difference in behavior could have generate bugs (possibly security impact) for users who are not aware of this subtlety.

### curl/libcurl version

~~~
curl 7.74.0 (x86_64-pc-linux-gnu) libcurl/7.74.0 OpenSSL/1.1.1n zlib/1.2.11 brotli/1.0.9 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.43.0 librtmp/2.3
Release-Date: 2020-12-09
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps mqtt pop3 pop3s rtmp rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: alt-svc AsynchDNS brotli GSS-API HTTP2 HTTPS-proxy IDN IPv6 Kerberos Largefile libz NTLM NTLM_WB PSL SPNEGO SSL TLS-SRP UnixSockets
~~~

### operating system

~~~
Linux skagos 5.10.0-23-amd64 #1 SMP Debian 5.10.179-1 (2023-05-12) x86_64 GNU/Linux
~~~

### PR DESCRIPTION
**Pull request by bagder**
... used at once.

Reported-by: Gabriel Corona
Fixes #11325

### CODE REVIEW

**Comment by bagder** [comment]
The valgrind errors in the CI on test 313 on openssl master looks like an openssl bug:
~~~
test 0313...[CRL test]
 valgrind ERROR ==91512== 1,795 (248 direct, 1,547 indirect) bytes in 1 blocks are definitely lost in loss record 32 of 32
==91512==    at 0x4848899: malloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==91512==    by 0x4EA2430: CRYPTO_malloc (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4EA258D: CRYPTO_zalloc (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4D5E128: asn1_item_embed_new (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4D5B254: asn1_item_embed_d2i (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4D5BFF2: ASN1_item_d2i_ex (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4F7B738: PEM_ASN1_read_bio (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4FE996D: X509_load_crl_file (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x48EB7CD: populate_x509_store (openssl.c:3244)
==91512==    by 0x48EB7CD: Curl_ssl_setup_x509_store (openssl.c:3395)
==91512==    by 0x48EBD72: bio_cf_in_read (openssl.c:764)
==91512==    by 0x4D6A69A: bread_conv (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4D68476: BIO_read (in /home/runner/openssl3/lib64/libcrypto.so.3)
==91512==    by 0x4C0E5E9: tls_default_read_n (in /home/runner/openssl3/lib64/libssl.so.3)
==91512==    by 0x4C0E972: tls_get_more_records (in /home/runner/openssl3/lib64/libssl.so.3)
==91512==    by 0x4C0D829: tls_read_record (in /home/runner/openssl3/lib64/libssl.so.3)
==91512==    by 0x4C064AE: ssl3_read_bytes (in /home/runner/openssl3/lib64/libssl.so.3)
==91512== 
== Contents of files in the log/ dir after test 313
=== Start of file commands.log

**Comment by icing** [comment]
Habe gerade in #11532 das OpenSSL master auf openssl-3.1.1 gestellt und sehe damit das Problem nicht.

**Comment by bagder** [comment]
Ok, I rebased on top of that to see if the problem goes away.

**Comment by bagder** [comment]
Yeps, I think this confirmed the previous leak was due to an OpenSSL problem (in their master branch).

**Comment by sahanaprasad07** [comment]
@bagder Hi, did you happen to report this OpenSSL bug upstream? Could you point me to the issue if you did.

**Comment by icing** [comment]
@sahanaprasad07 we do not have that information.

**Pull request closed without merging**
