### PR TITLE
Added CMake flag to enable the usage of /MT runtime in Visual Studio

### PR DESCRIPTION
**Pull request by madduci**
Added the option **WITH_MT** to enable the /MT (MultiThread) Runtime flag in Visual Studio

### CODE REVIEW

**Comment by snikulov** [comment]
@madduci Cool, but it would be better if you'll provide common option for static run-time build not only for MSVC, but for GCC ```-stacic``` also.

**Comment by madduci** [comment]
i guess that should belong to another pull request. I will try to integrate it for GCC and Clang

**Comment by snikulov** [comment]
@madduci I just suggest you to name it more generic (not ```WITH_MT```). Just because gcc/clang does not have Microsoft [MT option](https://msdn.microsoft.com/en-us/library/2kzt1wy3.aspx) to link run-time statically.

**Comment by madduci** [comment]
@snikulov do you have any suggestion for an alternative name? At the end, if you set it for gcc or clang, it has no effects, since I check only if MSVC is being used

**Comment by Lekensteyn** [comment]
Why can't you just use `-DCMAKE_C_CFLAGS=/MT`? Is this flag that special? (also, please keep the newline at the end of the file)

**Comment by snikulov** [comment]
@Lekensteyn the only idea, which is come into my mind, - update name resulting binary in some special way according to option. 
For ex: ```libcurl-mt.lib``` or ```libcurl-md.lib```

**Comment by madduci** [comment]
@Lekensteyn because it would overwrite the existing information in `CMAKE_C_CFLAGS`, but the naming convention suggested by @snikulov would then require the update of the FindCURL.cmake module shipped within CMake, and this just for Visual Studio.

The `/MT` flag is useful if you compile also other libraries in this way (e.g. OpenSSL, Boost) and it makes cURL compatible to them

**Comment by snikulov** [comment]
@madduci How about ```-DWITH_STATIC_RT=ON/OFF```? 
Regarding FindCurl.cmake, AFAIK, when #885 will be implemented, it should be updated, anyway.

**Comment by madduci** [comment]
I've renamed it. But the support to gcc and clang will come in future pull requests

**Comment by madduci** [comment]
I've tested it with gcc (6) and clang (3.8) to generate a static library and executable and it works without errors. I've also added the version number to the .so shared library

**Comment by madduci** [comment]
Issue should be fixed with my latest pull #852

**Comment by jay** [comment]
Just so I understand this, are you trying to make it so that the libcurl DLL builds with the static CRT on Windows and why?

**Comment by bagder** [comment]
No response for months and no +1s from the cmakers. Closing.

**Pull request closed without merging**
