### PR TITLE
Define HAVE_SSL_GET_SHUTDOWN when available (Windows)

### PR DESCRIPTION
**Pull request by Zenju**
Hi,

Just noticed, that the following code fragment in lib/vtls/openssl.c is disabled in the Windows build because HAVE_SSL_GET_SHUTDOWN is undefined, but shouldn't be:

````
#ifdef HAVE_SSL_GET_SHUTDOWN
            switch (SSL_get_shutdown(BACKEND->handle))
            {
                case SSL_SENT_SHUTDOWN:
                    infof(data, "SSL_get_shutdown() returned SSL_SENT_SHUTDOWN\n");
                    break;
                case SSL_RECEIVED_SHUTDOWN:
                    infof(data, "SSL_get_shutdown() returned SSL_RECEIVED_SHUTDOWN\n");
                    break;
                case SSL_SENT_SHUTDOWN|SSL_RECEIVED_SHUTDOWN:
                    infof(data, "SSL_get_shutdown() returned SSL_SENT_SHUTDOWN|"
                          "SSL_RECEIVED__SHUTDOWN\n");
                    break;
            }
#endif
````

I'm not sure in which OpenSSL version SSL_get_shutdown() was first introduced, but according to the docs it is at least available beginning with 1.0.2.

The patch follows the implementation strategy of other HAVE_* defines found in openssl.c, like HAVE_X509_GET0_SIGNATURE. If this is not the right approach, feel free to change.

Best, Zenju

### CODE REVIEW

**Comment by bagder** [comment]
So then maybe also remove the check for it from `configure.ac`? It seems wrong to have two different checks for it...

**Comment by Zenju** [comment]
I assume the HAVE_SSL_GET_SHUTDOWN mentioned in packages\vms\config_h.com should be scraped as well?

**Comment by jay** [comment]
@wb8tyw can you tell us how does this PR affect VMS builds? Can we remove [this](https://github.com/curl/curl/blob/curl-7_65_1/packages/vms/config_h.com#L828-L839) for example?

**Comment by bagder** [comment]
With the define handled in vtls/openssl.c, no platform should need to handle it special...

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
