### PR TITLE
Unbreak the cmake build. Fixes #1230

### LINKED ISSUE #1230: cmake: *** No rule to make target '../docs/curl.1'
### I did this

A fresh git clone.

    $ ./buildconf
    $ mkdir build && cd build
    $ cmake ..
    $ make

Which ends in:

~~~
make[2]: *** No rule to make target '../docs/curl.1', needed by 'src/tool_hugehelp.c'.  Stop.
~~~

### I expected the following

A successful build

### curl/libcurl version

git master since commit 4c49b835979694, as announced on the [curl-library list](https://curl.haxx.se/mail/lib-2017-01/0147.html).

### operating system

Any

### PR DESCRIPTION
**Pull request by sylvestre**

### CODE REVIEW

**Comment by bagder** [comment]
Thanks, but this doesn't really fix the whole problem, does it? I mean it removes the dependency, but the cmake build doesn't generate a curl.1 like the autotools build does so if you build from git for example (and not from a source tarball), the build will still fail. It works from a tarball because we ship a prebuilt curl.1 in those.

**Comment by bagder** [comment]
I suppose #1288 fixes what I wrote about, so I'm not sure where that leaves this PR...

**Comment by sylvestre** [comment]
It fixes the build itself but not the manpage. This isn't perfect for sure but it is better than the current state as the build completes and tests are built.

**Comment by Lekensteyn** [comment]
This patch removes the dependency, but then the commands executed by this target will not be correct. Can you try/review #1288?

**Comment by Lekensteyn** [comment]
This has been fixed in #1288

**Pull request closed without merging**
