### PR TITLE
mime: prevent curl_mime_subparts() from adding "itself"

### LINKED ISSUE #1962: Segfault when add mime as subpart to itself
### I did this
``` C
curl_mime *mime = curl_mime_init(easy);
curl_mimepart *part = curl_mime_addpart(mime);
CURLcode a1 = curl_mime_subparts(part, mime);
curl_mime_free(mime);
```

### I expected the following
`curl_mime_free(mime);` should not crash but `curl_mime_subparts(part, mime);` should returns `CURLE_BAD_FUNCTION_ARGUMENT` and do nothing.

### curl/libcurl version
curl 7.56.0 (i386-pc-win32) libcurl/7.56.0 WinSSL
Release-Date: 2017-10-04
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS Largefile SSPI Kerberos SPNEGO NTLM SSL

### operating system
Windows 7 x64

### PR DESCRIPTION
**Pull request by bagder**
Refuse to add its own "ancestor".

Reported-by: Alexey Melnichuk
Fixes #1962

### CODE REVIEW

**Comment by monnerat** [comment]
I do not agree with the commit: `subparts` can be NULL and this will make `curl_setopt(easy, CURLOPT_MIMEPOST, NULL);` always failing.

In addition, if we are going this way, we should check with the part's root `curl_mime` instead of only the part's parent.

Would you like I take it ?

**Comment by bagder** [comment]
> I do not agree with the commit: subparts can be NULL 

Sure, but `part->parent` cannot be NULL so I don't see how this fix affects the case when you pass NULL there? Maybe I misunderstood something.

> Would you like I take it ?

Please do, I'm under quite some load from the storm of fuzz issues right now.

**Comment by monnerat** [comment]
> Sure, but part->parent cannot be NULL so I don't see how this fix affects the case when you pass NULL there? Maybe I misunderstood something.

At `curl_easy_setopt(easy, CURLOPT_MIMEPOST, mime)` time, `curl_mime_subparts()` is called to attach `mime` to a part structure which has no parent. This is the top (invisible) part and it has no parent: I did it this way because it helps having custom and generated headers for the top multipart.

I will add the ancestor test.

**Comment by bagder** [comment]
@monnerat took over and landed a slightly different take, closing this!

**Pull request closed without merging**
