### PR TITLE
windows: implement send buffer tuning

### PR DESCRIPTION
**Pull request by bagder**
Bug: https://curl.haxx.se/mail/lib-2018-07/0080.html

### CODE REVIEW

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/issues/2224

**Comment by jay** [comment]
@djelinski regarding your comments on the list, can you do what @bagder suggested and use a define for SIO_IDEAL_SEND_BACKLOG_QUERY for when it's not available in the sdk and we can detect it at runtime, for example

~~~c
#ifndef SIO_IDEAL_SEND_BACKLOG_QUERY
#define SIO_IDEAL_SEND_BACKLOG_QUERY 0x4004747B
#endif
~~~

and we have a version checker at runtime you can use to ignore platforms where it's not supported
~~~c
if(Curl_verify_windows_version(6, 0, PLATFORM_WINNT, VERSION_LESS_THAN))
  return;
~~~

**Comment by djelinski** [comment]
@jay Here's a patch with that #define implemented. Runtime detection is included for free, WSAIoctl returns SOCKET_ERROR (WSAEINVAL) on older systems (tested on 2003). Let me know what you think.
[0002-windows-define-constant-for-compilers-that-do-not-re.zip](https://github.com/curl/curl/files/2218943/0002-windows-define-constant-for-compilers-that-do-not-re.zip)

**Comment by djelinski** [comment]
Ref: #708 #1485

**Comment by bagder** [comment]
I amended and force-pushed

**Comment by bagder** [comment]
Thanks everyone!

**Comment by vszakats** [comment]
For some reason the [merged commit](https://github.com/curl/curl/commit/1ba1dba76a8898d1de4dfbc9f1910a352d8a9dab) doesn't include the fix included in this PR, that sets the `SIO_IDEAL_SEND_BACKLOG_QUERY` constant, when missing. It means the logic isn't currently activated when built (e.g.) in a MinGW environment.

See this snippet in this PR:
```c
#ifdef WIN32
#ifndef SIO_IDEAL_SEND_BACKLOG_QUERY
#define SIO_IDEAL_SEND_BACKLOG_QUERY 0x4004747B
#endif
```
vs. the one in `master`:
```c
#if defined(WIN32) && defined(SIO_IDEAL_SEND_BACKLOG_QUERY)
```

**Comment by bagder** [comment]
Hm, I wonder how I managed to mess that up like that! Thanks for your keen eyes, I'll do a follow-up!

**Comment by bagder** [comment]
See d38b4737fde16d59b56847c8c5b50e97285a809f

**Comment by vszakats** [comment]
Thank you Daniel, no worries at all.

**Comment by vszakats** [comment]
It's looking good after 
https://github.com/curl/curl/commit/d38b4737fde16d59b56847c8c5b50e97285a809f. It's much tempting to retrofit this to the current release, but I'm going to hold out till Sept 5 :)

**Pull request closed without merging**
