### PR TITLE
rand: treat fake entropy the same regardless of endianness

### PR DESCRIPTION
**Pull request by bagder**
When the random seed is purposely made predictable for testing purposes
by using the CURL_ENTROPY environment variable, process that data in an
endian agnostic way so the the initial random seed is the same
regardless of endianness.

- Change Curl_rand to write to a char array instead of int array.

- Add Curl_rand_hexonly to write only random hex characters.

Fixes: #1315

Co-authored-by: Daniel Stenberg
Reported-by: Michael Kaufmann

### CODE REVIEW

**Comment by bagder** [comment]
Hm, three DIGEST tests (823 869 907) break, but only when compiled with gcc and not clang! Weird...

**Comment by bagder** [comment]
New take, which unfortunately made me have to also update 44 test cases but I think the fake random generator is now slightly simpler and hopefully works on big endian too. It now converts the given entropy from network byte order to host order and then converts to network order in every function call that wants random.

The previous version I pushed here didn't work and I gave up trying to create a fixed version that would generate the old sequence properly for both big and little endian systems.

**Comment by mkauf** [comment]
Thank you for working on this issue!

Unfortunately, the NTLM tests still fail on SPARC. This change is necessary:
```
diff --git a/lib/rand.c b/lib/rand.c
index 979c5a1..a61a070 100644
--- a/lib/rand.c
+++ b/lib/rand.c
@@ -57,7 +57,7 @@ static CURLcode randit(struct Curl_easy *data, unsigned int *r
nd)
     }
     else
       randseed++;
-    *rnd = htonl(randseed);
+    *rnd = randseed;
     return CURLE_OK;
   }
 #endif
```

With this change, ``randit()`` returns the same numbers on big/little endian instead of the same bit patterns.

This also means that the test data must be adjusted once again... including the digest tests 823, 869, 907. If you want, I can help you with this task.

**Comment by bagder** [comment]
> With this change, randit() returns the same numbers on big/little endian instead of the same bit patterns.

Which tests/logic need the same *number* returned and not the same bitpattern? That feels counter-intuitive to me.

Doing the change you suggest on top of the code in this PR does on the other hand break 34 tests on my x86-64 linux.

I get the same test failures even if I revert my test case update commit from this PR (1b1618cf77e).

Have you tried your change on both little + big endian with a few updated tests to see that it actually works on both?

**Comment by canavan** [comment]
Tried bagder/fake-rand-for-big-endian on IRIX/MIPS with the "native" MIPSPro compiler:
```
TESTDONE: 892 tests out of 927 reported OK: 96%
TESTFAIL: These test cases failed: 67 68 69 81 89 90 91 150 155 169 209 213 239 243 265 267 547 548 555 590 822 823 827 868 869 873 906 907 921 1008 1021 1100 1215 1233 1541 
TESTDONE: 1088 tests were considered during 2226 seconds.
```
make test in tests/:
```
test 0067...[HTTP with NTLM authorization]

 67: protocol FAILED:
--- log/check-expected  2017-05-06 00:49:27.703696827 +0200
+++ log/check-generated 2017-05-06 00:49:27.703345623 +0200
@@ -5,6 +5,6 @@
 [CR][LF]
 GET /67 HTTP/1.1[CR][LF]
 Host: 127.0.0.1:8990[CR][LF]
-Authorization: NTLM TlRMTVNTUAADAAAAGAAYAEAAAACeAJ4AWAAAAAAAAAD2AAAACAAIAPYAAAAIAAgA/gAAAAAAAAAAAAAABoKBAJb+qt7TfxoeBA41GhG8hMwxMjM0MTIzNXcHTmKrZZpStvdJ8Q/n1ikBAQAAAAAAAACAPtXesZ0BMTIzNDEyMzUAAAAAAgAEAEMAQwABABIARQBMAEkAUwBBAEIARQBUAEgABAAYAGMAYwAuAGkAYwBlAGQAZQB2AC4AbgB1AAMALABlAGwAaQBzAGEAYgBlAHQAaAAuAGMAYwAuAGkAYwBlAGQAZQB2AC4AbgB1AAAAAAAAAAAAdGVzdHVzZXJjdXJsaG9zdA==[CR][LF]
+Authorization: NTLM TlRMTVNTUAADAAAAGAAYAEAAAACeAJ4AWAAAAAAAAAD2AAAACAAIAPYAAAAIAAgA/gAAAAAAAAAAAAAABoKBAMOv20GsURsat8gdH/RfnYI0MzIxNTMyMeCdd8AzFZLZ/N1ujmilmCcBAQAAAAAAAACAPtXesZ0BNDMyMTUzMjEAAAAAAgAEAEMAQwABABIARQBMAEkAUwBBAEIARQBUAEgABAAYAGMAYwAuAGkAYwBlAGQAZQB2AC4AbgB1AAMALABlAGwAaQBzAGEAYgBlAHQAaAAuAGMAYwAuAGkAYwBlAGQAZQB2AC4AbgB1AAAAAAAAAAAAdGVzdHVzZXJjdXJsaG9zdA==[CR][LF]
 Accept: */*[CR][LF]
 [CR][LF]

 - abort tests
TESTDONE: 66 tests out of 67 reported OK: 98%
TESTFAIL: These test cases failed: 67                                                                          
TESTDONE: 78 tests were considered during 34 seconds.
TESTINFO: 11 tests were skipped due to these restraints:
TESTINFO: "configured as DISABLED" 11 times (594, 836, 882, 938, 1209, 1211, 1316, 1510, 1512 and 2 more)
*** Error code 1 (bu21)
```

**Comment by mkauf** [comment]
> Which tests/logic need the same number returned and not the same bitpattern?

``Curl_rand()`` needs the same numbers. It calls ``randit()`` to create random numbers, and then converts these to "bit patterns" (char*).

> Doing the change you suggest on top of the code in this PR does on the other hand break 34 tests on my x86-64 linux.
> I get the same test failures even if I revert my test case update commit from this PR (1b1618c).

That's true, the test data of the NTLM and digest tests needs to be updated. Your second commit needs to be updated accordingly. I haven't tried to make it work with the existing test data, it's easier to keep the code simple and update the test data.

> Have you tried your change on both little + big endian with a few updated tests to see that it actually works on both?

Yes I did. I have tested on Solaris 10 x86 and SPARC. The tests fail in the same way on both platforms.

**Comment by bagder** [comment]
thanks @mkauf and @canavan 

I now pushed an updated version here with @mkauf's correction and a separate commit with test 67, 68 and 69 fixed accordingly. I just want to make sure that these tests now work big endian as well before I proceed and also update the remaining ~30 tests that are still failing right now.

**Comment by mkauf** [comment]
Looks good:

x86
```
TESTDONE: 910 tests out of 940 reported OK: 96%
TESTFAIL: These test cases failed: 81 89 90 91 150 155 169 209 213 239 243 265 267 547 548 555 590 822 823 827 868 869 873 906 907 921 1008 1021 1100 1215
TESTDONE: 1088 tests were considered during 495 seconds.

 ./runtests.pl 67 68 69
...
test 0067...[HTTP with NTLM authorization]
-pd---em-- OK (1   out of 3  , remaining: 00:05)
test 0068...[HTTP with NTLM authorization and wrong password]
-pd---em-- OK (2   out of 3  , remaining: 00:01)
test 0069...[HTTP with NTLM, Basic or Wild-and-crazy authorization]
-pd---em-- OK (3   out of 3  , remaining: 00:00)
Terminated
TESTDONE: 3 tests out of 3 reported OK: 100%
TESTDONE: 3 tests were considered during 3 seconds.
```

SPARC
```
TESTDONE: 895 tests out of 926 reported OK: 96%
TESTFAIL: These test cases failed: 81 89 90 91 150 155 169 209 213 239 243 265 267 547 548 555 576 590 822 823 827 868 869 873 906 907 921 1008 1021 1100 1215
TESTDONE: 1088 tests were considered during 2730 seconds.

 ./runtests.pl 67 68 69
...
test 0067...[HTTP with NTLM authorization]
-pd---em-- OK (1   out of 3  , remaining: 00:06)
test 0068...[HTTP with NTLM authorization and wrong password]
-pd---em-- OK (2   out of 3  , remaining: 00:01)
test 0069...[HTTP with NTLM, Basic or Wild-and-crazy authorization]
-pd---em-- OK (3   out of 3  , remaining: 00:00)
Terminated
TESTDONE: 3 tests out of 3 reported OK: 100%
TESTDONE: 3 tests were considered during 5 seconds.
```

**Comment by bagder** [comment]
Thanks, I've now pushed a fresh/rebased version of the patch and 33 updated tests. All of them run fine on my x86-64.

**Comment by mkauf** [comment]
There's a typo in the commit message ("rake" -> "fake").

I think the tests would also break if ``sizeof(unsigned int) != 4``. Probably all ``unsigned int`` in rand.c should be replaced with ``uint32_t``.

The tests are currently running, I will post the results when they are done.

**Comment by mkauf** [comment]
Test 1139 fails (Verify that all libcurl options have man pages), probably caused by an unrelated commit:
```
--environment is not in tool_getparam.c tool_help.c (but in curl.1)
```
The other tests pass :thumbsup:

**Comment by bagder** [comment]
Thanks, yes the --environment issue is because of a different bug. I think I fixed that with commit 7800730520.

**Comment by bagder** [comment]
Thanks for the help @mkauf and @jay !

**Comment by mkauf** [comment]
Great, thank you!

A minor compiler warning appeared for builds without ``--enable-debug``: https://curl.haxx.se/dev/log.cgi?id=20170509021228-31587#prob1
```
../../../../home/autobuild/curl/curl.git/lib/formdata.c:1556:51: warning: unused parameter 'buflen' [-Wunused-parameter]
```
Maybe remove this parameter, or add ``(void)buflen;`` ?

**Comment by bagder** [comment]
Good catch. I prefer to have the length verified to avoid any mistakes in that department to slip in in the future so I opted to instead convert the assert to an if. Fixed in commit 158d7016419 just now. Thanks!

**Pull request closed without merging**
