### PR TITLE
 cacertinmem.c example only loads one certificate

### PR DESCRIPTION
**Pull request by DaVieS007**
Seems this example showing the only way to load CA file (curl-ca-bundle.crt) from memory now able to process the whole certificate-chain from memory.

### CODE REVIEW

**Comment by bagder** [comment]
This is an *example*. I don't see how it serves anyone better if we add 4000 lines of PEM data into it...

**Comment by DaVieS007** [comment]
> This is an _example_. I don't see how it serves anyone better if we add 4000 lines of PEM data into it...

Obviously not that 4000 lines are the subject, I inserted it to make it "work" with same method, maybe it should be load from file to demonstrate "memory" operation.

**Comment by bagder** [comment]
I think improving the example to work with more than one cert in memory is a good idea, but then I think having two in there is good enough for the example. Wouldn't you agree?

**Comment by bagder** [comment]
Additionally, also run `make checksrc` and you'll spot a few style nits to fix.

**Comment by bagder** [comment]
@DaVieS007 any plans on adjusting this as suggested above?

**Comment by DaVieS007** [comment]
@bagder yes for sure after I find out what causing memory leak and the code above is affacted or not.

**Comment by bagder** [comment]
Thanks @DaVieS007 for your work on this. I did some minor edits to the code before it landed.

**Pull request closed without merging**
