### PR TITLE
vauth/oauth2: Fix OAUTHBEARER token generation

### PR DESCRIPTION
**Pull request by merty**
OAUTHBEARER tokens were incorrectly generated in a format similar to
XOAUTH2 tokens. These changes make OAUTHBEARER tokens conform to the
RFC7628.

Fixes: #2487
Reported-by: Paolo Mossino

### CODE REVIEW

**Comment by jay** [comment]
Ref 7628 for `client-resp    = (gs2-header kvsep *kvpair kvsep) / kvsep` and ref RFC 5801 for GS2:
~~~
    UTF8-1-safe    = %x01-2B / %x2D-3C / %x3E-7F
                     ;; As UTF8-1 in RFC 3629 except
                     ;; NUL, "=", and ",".
    UTF8-2         = <as defined in RFC 3629 (STD 63)>
    UTF8-3         = <as defined in RFC 3629 (STD 63)>
    UTF8-4         = <as defined in RFC 3629 (STD 63)>
    UTF8-char-safe = UTF8-1-safe / UTF8-2 / UTF8-3 / UTF8-4

    saslname       = 1*(UTF8-char-safe / "=2C" / "=3D")
    gs2-authzid    = "a=" saslname
                      ;; GS2 has to transport an authzid since
                      ;; the GSS-API has no equivalent
    gs2-nonstd-flag = "F"
                      ;; "F" means the mechanism is not a
                      ;; standard GSS-API mechanism in that the
                      ;; RFC 2743, Section 3.1 header was missing
    cb-name         = 1*(ALPHA / DIGIT / "." / "-")
                      ;; See RFC 5056, Section 7.
    gs2-cb-flag     = ("p=" cb-name) / "n" / "y"
                      ;; GS2 channel binding (CB) flag
                      ;; "p" -> client supports and used CB
                      ;; "n" -> client does not support CB
                      ;; "y" -> client supports CB, thinks the server
                      ;;           does not
    gs2-header = [gs2-nonstd-flag ","] gs2-cb-flag "," [gs2-authzid] ","
                        ;; The GS2 header is gs2-header.
~~~

Would it make sense to break up the function into xoauth2 function and oauthbearer function, or at least note in the existing function that host and port must be omitted for older XOAUTH2 so that it is clear what is happening. And what happens if host is null and port is other than 0/80 there's a null deref. Should it be just if (!host) user= elseif port ==0 || port ==80 n, else n, . Is that not an issue ? And the tests will need to be adjusted now that the base64 strings are different, refer to the CI failures. Also I would give an assisted-by credit to Kerry Loux since he proposed something similar several months ago.

**Comment by bagder** [comment]
Thanks for your efforts @merty. You got comments from @jay on this and there are multiple test failures in the CI. Are you planning to address them?

**Comment by MonkeybreadSoftware** [comment]
clients are asking for this patch to be used. Can this get included soon in the next CURL release?

**Comment by MonkeybreadSoftware** [comment]
Customer confirms the patch is working for him.

**Comment by bagder** [comment]
I want to merge this, or at least fix the bug, but we cannot merge a patch that breaks the build and tests in numerous places. I think @jay's comments above seem reasonable but there's been no effort so far in accommodating or discussing them.

**Comment by MonkeybreadSoftware** [comment]
I am not 100% sure, but could it be one tests checks for OAUTHBEARER to be a certain format?
So the test needs to be changed to expect now a correct result.

-AUTH OAUTHBEARER dXNlcj11c2VyAWhvc3Q9MTI3LjAuMC4xAXBvcnQ9OTAwNQFhdXRoPUJlYXJlciBtRl85LkI1Zi00LjFKcU0BAQ==[CR][LF]
9780+AUTH OAUTHBEARER bixhPXVzZXIsAWhvc3Q9MTI3LjAuMC4xAXBvcnQ9OTAwNQFhdXRoPUJlYXJlciBtRl85LkI1Zi00LjFKcU0BAQ==[CR][LF]

Can you maybe just put in the right result to make tests work?

**Comment by bagder** [comment]
> Can you maybe just put in the right result to make tests work?

Yes, I presume so.

**Comment by merty** [comment]
Sorry for the late response @jay, @MonkeybreadSoftware, @bagder!

I will update this PR tonight with @jay's suggestions and updates to the tests! 👍

**Comment by merty** [comment]
Updated the tests, the failing check is due to (unrelated) test 1501 which seems to fail for other PRs too.

I believe this is good to merge now 👍

**Comment by jay** [comment]
Thanks for the follow up. 1501 is known to do that in the CI (I assume due to arbitrary slowdowns).

**Pull request closed without merging**
