### PR TITLE
strerror: Add Curl_winapi_strerror for Win API specific errors

### PR DESCRIPTION
**Pull request by jay**
- In all code call Curl_winapi_strerror instead of Curl_strerror when
  the error code is known to be from Windows GetLastError.

Curl_strerror prefers CRT error codes (errno) over Windows API error
codes (GetLastError) when the two overlap. When we know the error code
is from GetLastError it is more accurate to prefer the Windows API error
messages.

Reported-by: Richard Alcock

Fixes https://github.com/curl/curl/issues/4550
Closes #xxxx

### CODE REVIEW

**Comment by jay** [comment]
It's unclear to me the right behavior for dynamically generated strings and CURL_DISABLE_VERBOSE_STRINGS. Curl_sspi_strerror did not dynamically generate the error string (via FormatMessage) when CURL_DISABLE_VERBOSE_STRINGS, but Curl_strerror did. I left them both the same. For Curl_winapi_strerror I followed Curl_sspi_strerror and do not dynamically generate the error string when CURL_DISABLE_VERBOSE_STRINGS. (Instead I do it like `(err == ERROR_SUCCESS) ? "No error" : "Error"`) However I think the Curl_sspi and Curl_winapi versions should be changed to allow dynamic generation when CURL_DISABLE_VERBOSE_STRINGS. My understanding of CURL_DISABLE_VERBOSE_STRINGS is it's for disabling the literal error strings in libcurl, not the ones stored outside the library (like in the CRT,)

**Comment by jay** [comment]
@captain-caveman2k Do you have any opinion on this

**Comment by jay** [comment]
@bagder can you please review earlier comment and clarify CURL_DISABLE_VERBOSE_STRINGS? Is it expected to dynamically generate the strings when CURL_DISABLE_VERBOSE_STRINGS?

**Comment by bagder** [comment]
I think `CURL_DISABLE_VERBOSE_STRINGS` should be considered used by systems that don't care for error messages at all. Primarily as a way to save space but also for systems with no way to show the error in a useful manner.

**Comment by jay** [comment]
Ok that's what I did, so I left it as is.

**Pull request closed without merging**
