### PR TITLE
workflows: Ignore changes to md files for most GitHub workflows

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Review by bagder — COMMENTED** [review]
Seems like a great improvement!

**Comment by bagder** [comment]
@mback2k @cmeister2 4 days, I'm moving on without your reviews.

**Comment by bagder** [comment]
Thanks!

**Comment by cmeister2** [comment]
> @mback2k @cmeister2 4 days, I'm moving on without your reviews.

Apologies, I'm away from a PC at the mo. Thanks for reviewing.

**Comment by mback2k** [comment]
And I have been buried with work, sorry.

**Pull request closed without merging**
