### PR TITLE
curl --json

### PR DESCRIPTION
**Pull request by bagder**
`--json <data>` is a shortcut for `--data-binary <data> -H "Content-Type: application/json" -H "Accept: application/json"`

While the discussion continues on the curl-users list and in #8312, here's something to check and play with.

### CODE REVIEW

**Comment by jay** [comment]
I'd call it --data-json for consistency with all the other --data-foo

**Comment by bagder** [comment]
[A question](https://github.com/curl/curl/discussions/8312#discussioncomment-2032464) is if this should also set `Accept: application/json, */*`

**Comment by bmarwell** [comment]
Can I still overwrite the accept header? Some restful endpoints might return a document, an image etc instead.

**Comment by jzakrzewski** [comment]
Seems so. Just look at : https://github.com/curl/curl/pull/8314/files#diff-76a23840b36e3f9c5485019056c5ea0e3d195d6c55c9c1f5b2d3a16844674c0b around line 578

**Comment by bagder** [comment]
Yes, exactly like we're used to. The test cases I added verify that both headers this option sets can be overridden.

**Comment by bagder** [comment]
Ok, I'll merge this within 24 hours.

**Comment by crazysouthern** [comment]
Chido

**Pull request closed without merging**
