### PR TITLE
Dump HTTP request and response data to separate files

### PR DESCRIPTION
**Pull request by chenstrace**
A feature for tracing and debugging HTTP request and response.
For example, `curl --dump-bin a www.google.com` will generate 7 files.
- `a.req` (the whole request)
- `a.reqheader` (request header)
- `a.reqbody`  (request body)
- `a.resp` (the whole response)
- `a.respheader` (response header)
- `a.respbody` (response body)
- `a.trace` (trace)

### CODE REVIEW

**Comment by bagder** [comment]
But why? `--trace` and `--trace-ascii` already provide this data and information, right?

**Comment by chenstrace** [comment]
> But why? `--trace` and `--trace-ascii` already provide this data and information, right?

with `--trace`, we can not get the whole request  and response data, especially in a single file. sometimes we do not need the process of send and recv, but the whole content.

**Comment by bagder** [comment]
> with --trace, we can not get the whole request and response data

You can't? What's missing?

**Comment by chenstrace** [comment]
> > with --trace, we can not get the whole request and response data
> 
> You can't? What's missing?

Sorry, my point is we can get the data, but not in single file. To get the binary data of whole request or response, we must edit the file generated by `--trace`.

**Comment by bagder** [comment]
> we can get the data, but not in single file

You get it all in a single file, yes. I don't think it is curl's job to provide more options to offer the same functionality with such a small difference. Surely you can write a script that instead splits up that single file into multiple ones after the fact if that is what you want?

**Comment by bagder** [comment]
I don't think it is the interested of users and maintainers to add this functionality creep. I would propose you instead write a separate and external tool/script that splits the single file curl can already create.

**Pull request closed without merging**
