### PR TITLE
crypto: ensure crypto initialization works

### PR DESCRIPTION
**Pull request by danielgustafsson**
Make sure that context initialization during hash setup works to avoid going forward with the risk of a null pointer dereference.

Closes: xxxx
Reported-by: Philippe Antoine on HackerOne

### CODE REVIEW

**Comment by catenacyber** [comment]
(Found by nallocfuzz)

**Comment by bagder** [comment]
Windows related compiler warnings:
~~~
sha256.c: In function 'my_sha256_init':
sha256.c:231:25: error: passing argument 1 of 'CryptReleaseContext' makes integer from pointer without a cast [-Wint-conversion]
  231 |     CryptReleaseContext(&ctx->hCryptProv, 0);
      |                         ^~~~~~~~~~~~~~~~
      |                         |
      |                         HCRYPTPROV * {aka long unsigned int *}
In file included from sha256.c:82:
C:/msys64/mingw32/i686-w64-mingw32/include/wincrypt.h:783:58: note: expected 'HCRYPTPROV' {aka 'long unsigned int'} but argument is of type 'HCRYPTPROV *' {aka 'long unsigned int *'}
  783 |   WINIMPM WINBOOL WINAPI CryptReleaseContext (HCRYPTPROV hProv, DWORD dwFlags);
      |                                               ~~~~~~~~~~~^~~~~

**Comment by danielgustafsson** [comment]
> Windows related compiler warnings:

Ah yes, silly mistake, fixed.

There are still test failures in the NTLM code that I have to hunt down.

**Comment by bagder** [comment]
I squashed these and rebased on current master and made #11614 in an attempt to fix this.

**Pull request closed without merging**
