### PR TITLE
cmake: soname number for output .so file

### PR DESCRIPTION
**Pull request by jainvishal**
Originally the output .so file lacked the soname number under CMake.
It was available in makefile. The change collects the libcurl version
from curlver.h file and then uses it for generated .so file.

### CODE REVIEW

**Comment by bagder** [comment]
The SONAME of a library and of liibcurl is very different than the version number and it really **must not** be set to be the same. It would be much better if the cmake build would use and set the same SONAME as the libtool build does.

**Comment by jainvishal** [comment]
You are right, I completely missed that. Thanks for the pointer. I will
check it out and submit another PR.

Thank you.
Vishal Jain

**Comment by jainvishal** [comment]
Hi @bagder , I did find the versioning scheme for libcurl. But I have a question.

Why curlver.h contains names that start with LIBCURL instead of CURL. Effectively they are renamed e.g. from LIBCURL_VERSION_MAJOR to CURL_VERSION_MAJOR (in src/tool_version.h).

My preference is to rename them to drop LIB. That will make it clear that CURL* are for curl binary while LIBCURL* are for library. That will also allow us to have a single version file for curl and libcurl simplifying the versioning process.

Another less intrusive approach would be to leave them as is and define a new set of variables that are sourced by both make and cmake system but that will not be as elegant.

Please advise.

**Comment by bagder** [comment]
> Why curlver.h contains names that start with LIBCURL instead of CURL

Because of a (perhaps wrong) decision taken a long time ago. 

> My preference is to rename them to drop LIB.

We have provided these symbols in the public header using these names since 2004. I think it's a little late to rename them now. We could *possibly* add new symbols as aliases to the existing names, but I don't really see where the big value in that is.

> Another less intrusive approach would be to leave them as is and define a new set of variables that are sourced by both make and cmake system but that will not be as elegant.

I thought you were looking into generating the proper SONAME. You don't need the version number for that. It's actually more complicated since it only set in `lib/Makefile.am` using libtool syntax:

https://github.com/curl/curl/blob/82149e70a505ca43c606836fac023a750510d71d/lib/Makefile.am#L69

The `10:0:6` string ends up `libcurl.so.4.6.0` on a typical Linux box.

**Comment by bagder** [comment]
Maybe we should start with splitting out the soname variable, perhaps like this: https://github.com/curl/curl/commit/8485e26b60e58e6a893745c81a138f4d266f969e

**Comment by jainvishal** [comment]
Sorry it took me some time to get this back on my radar. I have now made the changes on bagder/soname branch and submitted the PR. Let me know if my new changes make sense. We can delete this current PR as the changes were anyway not correct and concentrate on the new PR.

**Comment by bagder** [comment]
Duplicate of #5935

**Pull request closed without merging**
