### PR TITLE
travis: run more tests with coverage build

### PR DESCRIPTION
**Pull request by MarcelRaad**
This enables the following features and tests for the coverage build:
- brotli
- synchronous resolver / TrackMemory
- libssh2
- alt-svc

### CODE REVIEW

**Comment by bagder** [comment]
> synchronous resolver / TrackMemory

Why this?

**Comment by MarcelRaad** [comment]
Because of:
```
TESTINFO: 129 tests were skipped due to these restraints:
TESTINFO: "curl lacks TrackMemory support" 3 times (96, 558, 1330)
TESTINFO: "curl has threaded-resolver support" 1 times (506)
```

**Comment by bagder** [comment]
This certainly makes more tests run in the coverage build. Interestingly, coveralls says it *reduced* the coverage by 1 percentage point. While coveralls is shaky and its numbers not always to be trusted, it certainly can also be true since this change also made a lot more code build and thus get used and included in the coverage number.

**Comment by MarcelRaad** [comment]
On my fork (https://github.com/MarcelRaad/curl/pull/23), coveralls said the coverage increased from 76 to 82 %. With the previous push without the last commit and based on an older master, it said it increased from 75 to 80 %. So I would have expected it to go up.

**Comment by jay** [comment]
> While coveralls is shaky and its numbers not always to be trusted

Sometimes it makes no sense it's like it pulled some numbers out of a hat completely arbitrary

**Comment by MarcelRaad** [comment]
For reference, this is what the tests result look like now:
```
TESTDONE: 1180 tests out of 1180 reported OK: 100%
TESTDONE: 1251 tests were considered during 559 seconds.
TESTINFO: 71 tests were skipped due to these restraints:
TESTINFO: "failed starting HTTP-IPv6 server" 12 times (240, 241, 242, 263, 1046, 1056, 1083, 1230, 1265 and 3 more)
TESTINFO: "curl lacks GSS-API support" 3 times (1282, 2056, 2057)
TESTINFO: "failed starting FTP-IPv6 server" 6 times (252, 253, 254, 255, 1048, 1050)
TESTINFO: "openssl engine not supported" 1 times (307)
TESTINFO: "disabled by keyword" 10 times (573, 587, 644, 1086, 1113, 1162, 1163, 1208, 1452 and 1 more)
TESTINFO: "curl lacks WinSSL support" 1 times (2043)
TESTINFO: "configured as DISABLED" 18 times (530, 584, 594, 836, 882, 938, 1209, 1211, 1307 and 9 more)
TESTINFO: "curl has ipv6 support" 1 times (1454)
TESTINFO: "curl lacks Metalink support" 18 times (2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 and 9 more)
TESTINFO: "failed starting GOPHER-IPv6 server" 1 times (1203)
```
and before:
```
TESTDONE: 1123 tests out of 1123 reported OK: 100%
TESTDONE: 1252 tests were considered during 569 seconds.
TESTINFO: 129 tests were skipped due to these restraints:
TESTINFO: "configured as DISABLED" 18 times (530, 584, 594, 836, 882, 938, 1209, 1211, 1307 and 9 more)
TESTINFO: "curl lacks GSS-API support" 3 times (1282, 2056, 2057)
TESTINFO: "curl lacks sftp support" 1 times (632)
TESTINFO: "curl has ipv6 support" 1 times (1454)
TESTINFO: "failed starting HTTP-IPv6 server" 12 times (240, 241, 242, 263, 1046, 1056, 1083, 1230, 1265 and 3 more)
TESTINFO: "disabled by keyword" 10 times (573, 587, 644, 1086, 1113, 1162, 1163, 1208, 1452 and 1 more)
TESTINFO: "curl lacks Metalink support" 18 times (2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013 and 9 more)
TESTINFO: "curl lacks scp server support" 11 times (601, 603, 605, 607, 617, 619, 621, 623, 629 and 2 more)
TESTINFO: "failed starting GOPHER-IPv6 server" 1 times (1203)
TESTINFO: "curl has threaded-resolver support" 1 times (506)
TESTINFO: "curl lacks WinSSL support" 1 times (2043)
TESTINFO: "curl lacks alt-svc support" 3 times (355, 356, 1654)
TESTINFO: "openssl engine not supported" 1 times (307)
TESTINFO: "failed starting FTP-IPv6 server" 6 times (252, 253, 254, 255, 1048, 1050)
TESTINFO: "curl lacks sftp server support" 36 times (582, 583, 600, 602, 604, 606, 608, 609, 610 and 27 more)
TESTINFO: "curl lacks brotli support" 3 times (314, 315, 316)
TESTINFO: "curl lacks TrackMemory support" 3 times (96, 558, 1330)
```
Torture tests now:
```
TESTDONE: 91 tests out of 91 reported OK: 100%
TESTDONE: 92 tests were considered during 1153 seconds.
TESTINFO: 1 tests were skipped due to these restraints:
TESTINFO: "disabled by keyword" 1 times (1452)``
and before:
```
TESTDONE: 89 tests out of 89 reported OK: 100%
TESTDONE: 94 tests were considered during 1034 seconds.
TESTINFO: 5 tests were skipped due to these restraints:
TESTINFO: "curl lacks alt-svc support" 1 times (1654)
TESTINFO: "curl lacks sftp server support" 1 times (600)
TESTINFO: "disabled by keyword" 1 times (1452)
TESTINFO: "curl has threaded-resolver support" 1 times (506)
TESTINFO: "curl lacks scp server support" 1 times (601)
```

**Comment by bagder** [comment]
Since you enable alt-svc in the build now, maybe add test 355, 356 and 1654 to the torture tests? They are the alt-svc tests...

**Comment by MarcelRaad** [comment]
> Since you enable alt-svc in the build now, maybe add test 355, 356 and 1654 to the torture tests? They are the alt-svc tests...

As 355 and 356 are failing and 1654 (the one you fixed recently) is already enabled, I'd rather do that separately.

**Comment by MarcelRaad** [comment]
Oh no, I pushed from the wrong computer which didn't have the PR reference yet :-(
Merged in commit https://github.com/curl/curl/commit/972bdffb9f675e44abb85d93fd26507d9602d90d.

**Pull request closed without merging**
