### PR TITLE
Add USE_HTTP2 define

### LINKED ISSUE #6949: TLS backends rely on USE_NGHTTP2 to send "h2" ALPN
Right now, if you build with Hyper, but without nghttp2, curl will never send the "h2" ALPN protocol and therefore will never negotiate HTTP/2. The TLS backends currently check USE_NGHTTP2 when deciding whether to send "h2", in part because they rely on these two macros from nghttp2: NGHTTP2_PROTO_VERSION_ID and NGHTTP2_PROTO_VERSION_ID_LEN.

We should introduce a new #define, USE_HTTP2, which is defined by both Hyper and nghttp2. We should also define constants within curl for the "h2" ALPN value and its length (which are set by standard), so implementations don't have to use values from different backends.

/cc @kevinburke, who helped find this.

### PR DESCRIPTION
**Pull request by jsha**
This abstracts across the two HTTP/2 backends: nghttp2 and Hyper.

Add our own define for the "h2" ALPN protocol, so TLS backends can use
it without depending on a specific HTTP backend.

Fixes #6949.

### CODE REVIEW

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
I think `CMakeLists.txt` also needs a fix for this?

**Comment by jsha** [comment]
I'm afraid I don't know CMake. Can you point me in roughly the right direction? I know I need to set the USE_HTTP2 #define when either Hyper or nghttp2 are enabled, but I can't see how #defines are added in the CMake config.

**Comment by bagder** [comment]
An alternative approach that works better independently of build system would be to mimic the QUIC way:

https://github.com/curl/curl/blob/7843fe0a1ba495d8e108115be0f1bab4cf86beb9/lib/curl_setup.h#L804-L806

**Comment by bagder** [comment]
~~~
vtls/openssl.c:2717:24: error: incompatible pointer to integer conversion assigning to 'unsigned char' from 'const char [3]' [-Werror,-Wint-conversion]
      protocols[cur++] = ALPN_H2;

**Review by Lionz01 — APPROVED** [review]
``

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
