### PR TITLE
option: Disallow username in URL

### PR DESCRIPTION
**Pull request by zagor**
This solves TODO 1.1.

### CODE REVIEW

**Comment by jay** [comment]
This needs a test, it can be fairly straightforward I think, just test the return code in the fail case. See [test2044](https://github.com/curl/curl/blob/curl-7_58_0/tests/data/test2044) for a very simple example.

Also CI says symbols-in-versions and document the command line switch in cmdline-opts. I would rename the switch from `--disallow-username` to `--disallow-username-in-url`. It's longer but for someone reading a script it's easier to understand what it does.

I suggest not using TODO: as the area because it reads like you're adding something to the todo. sample alternatives
`lib: Add option to disallow usernames in URLs`
`url: Add option CURLOPT_DISALLOW_USERNAME_IN_URL`
etc

**Comment by bagder** [comment]
It seems the new test case 2074 fails sometimes? Is it because of different build options?

**Comment by bagder** [comment]
@zagor Any chance you're up for rebasing this and fixing the conflict?

**Comment by zagor** [comment]
Absolutely!

**Comment by bagder** [comment]
Thanks! (slightly edited before I pushed)

**Pull request closed without merging**
