### PR TITLE
http/2, http/3, decouple stream state from easy handle

### PR DESCRIPTION
**Pull request by icing**
- add convenience functions to `hash.h` for using a hash with `curl_off_t` as keys. Use this in h2+h3 connection filters to associate `data->id` with the internal stream state.
- changed implementations of all affected connection filters
- removed `h2_ctx*` and `h3_ctx*` from `struct HTTP` and thus the easy handle
- solves the problem of attaching "foreign protocol" easy handles during connection shutdown

### CODE REVIEW

**Comment by bagder** [comment]
This introduces a second hash table implementation. Have you ruled out instead using the existing lib/hash.c functions for this? It seems to me like they could be used...

**Comment by icing** [comment]
Separate hash implementation removed again. Convenience functions added.

**Comment by bagder** [comment]
merge conflicts now after some other merges

**Comment by icing** [comment]
`curl-for-win` fails with:

```
++ gpg --batch --keyserver-options timeout=15 --display-charset utf-8 --keyid-format 0xlong --verify-options show-primary-uid-only --verify pkg.sig pkg.bin
gpg: can't open signed data 'pkg.bin'
gpg: can't hash datafile: No such file or directory
```

Anyone has an idea what is going on here? @vszakats ?

**Comment by vszakats** [comment]
Package or signature downloads from GitHub failed:
```
++ curl --disable --user-agent '' --fail --silent --show-error --globoff --remote-time --xattr --connect-timeout 15 --max-time 60 --retry 3 --max-redirs 10 --location --proto-redir =https --output pkg.bin https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz --output pkg.sig https://github.com/rockdaboot/libpsl/releases/download/0.21.5/libpsl-0.21.5.tar.gz.sig
curl: (22) The requested URL returned error: 500
curl: (22) The requested URL returned error: 500
curl: (22) The requested URL returned error: 500
curl: (22) The requested URL returned error: 500
```
A retry should fix this.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
