### PR TITLE
Removed uneeded decleration within for

### PR DESCRIPTION
**Pull request by Mipsters**
fixed error: 'for' loop initial declaration used outside C99 mode
by declaring `i` in the beginning of the block instead of inside the for loop

gcc version 3.3.5 (Debian 1:3.3.5-13)

after fix and successful compilation, `make test` results:
https://pastebin.com/znEufH5H

### CODE REVIEW

**Comment by danielgustafsson** [comment]
There is another one in `docs/examples/crawler.c` which I think we should change too to keep us C89 across the tree. Care to include that one too in this patch?

**Comment by Mipsters** [comment]
Done!
maybe the ci cd should include an old compiler test?
I noticed this because I work with a very old compiler, and it's best to catch these things early!
just a suggestion of course :)

**Comment by danielgustafsson** [comment]
Thanks, looks good! There is a copyrightyear warning but don't worry about that one, I'll take care of that when pushing to master.

**Comment by danielgustafsson** [comment]
Pushed with a tweak to the copyright year and some mild copyediting of the commit message. Thanks for your contribution!

**Pull request closed without merging**
