### PR TITLE
Get rid of the unused HAVE_SIG_ATOMIC_T et. al.

### PR DESCRIPTION
**Pull request by dfandrich**
It was added in 2006 but I see no evidence it was ever used.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Or should we start using it instead? `exit_signal_handler()` in `tests/server/util.c` seems like a callsite which really ought to be using `sig_atomic_t`

**Comment by dfandrich** [comment]
I thought that might have been the reason it was originally added, but I also
figured if nobody had found a need for it in 15 years, it wasn't needed :-) I
won't submit this if someone wants to see if it's actually useful.

**Comment by danielgustafsson** [comment]
> On 29 Jun 2021, at 00:20, Dan Fandrich ***@***.***> wrote:

> I thought that might have been the reason it was originally added, but I also
> figured if nobody had found a need for it in 15 years, it wasn't needed :-) I
> won't submit this if someone wants to see if it's actually useful.

That certainly is a fairly strong case for removing it =) I will take a stab at using it, but if I fall short of finding time within a week or so feel free to push this, it can always be revived if so.

**Comment by dfandrich** [comment]
Submitted as 83245d9f

**Pull request closed without merging**
