### PR TITLE
ssh execute

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Comment by bagder** [comment]
Test 1013 and 1119 fail.

I miss: docs and tests. I presume this works with the URI format in the [secsh-scp-sftp-ssh-uri draft](https://tools.ietf.org/html/draft-ietf-secsh-scp-sftp-ssh-uri-04)?

**Comment by RekGRpth** [comment]
> Test 1013 and 1119 fail.

I fix it

**Comment by RekGRpth** [comment]
I do not understand, why 
in commit 1ef9c0a check continuous-integration/appveyor/pr — AppVeyor build failed
but in commit 9dedaae check continuous-integration/appveyor/pr — AppVeyor build succeeded

**Comment by bagder** [comment]
Some of the appveyor tests are flaky which can make them red without good reason. :disappointed:

**Comment by bagder** [comment]
For making this PR easier to review, can you squash all commits into a single one, rebase it and then force-push?

**Comment by RekGRpth** [comment]
> can you squash all commits into a single one, rebase it and then force-push?
May be easy to fork again and put all my changes to one single commit?

**Comment by RekGRpth** [comment]
https://github.com/curl/curl/pull/3734

**Pull request closed without merging**
