### PR TITLE
CI/azure: increase Windows job timeout once again

### PR DESCRIPTION
**Pull request by mback2k**
Avoid aborted jobs due to performance issues on Azure DevOps.

### CODE REVIEW

**Comment by bagder** [comment]
The question is perhaps if increasing the timeouts actually help anything or just will make it take 30 minutes more per job to fail... I mean, already at 90 minutes it is an awfully long time we're giving them.

**Comment by mback2k** [comment]
I observed that many PRs have green CI jobs for these Windows CI builds, but not the jobs for commits on master. The difference is that for commits on master we are running this test reporting functionality, which seems to increase the required time a little bit.

Sometimes there are flaky tests that make the testsuite painfully slow or stuck, but that is a different issue, yes. I will try to fix these as well, but first I need to get a better picture about that and for that I need less aborted runs there the cause is not a test itself.

**Comment by mback2k** [comment]
@bagder any objections to increasing the timeout temporarily to get a better understanding of the situation?

**Comment by jay** [comment]
I'm already getting 90 minute azure timeouts in another PR and also other cancelations. I agree with Daniel it seems really slow, and in the [raw log](https://dev.azure.com/daniel0244/5571c33c-81e1-43d7-93ee-d3d4152f27b2/_apis/build/builds/2604/logs/157) for example I don't see that it's attributable to any one thing it's just generally slow.

**Comment by mback2k** [comment]
The root cause is and will always remain: emulated fork on Windows is slow and we cannot do anything about that.

But, I am still trying to optimize any other area I can identify. Just give me the time, life has changed my priorities, but I am working on this from time to time.

**Pull request closed without merging**
