### PR TITLE
lib: change curl_blob data pointer to const

### PR DESCRIPTION
**Pull request by jay**
- Change curl_blob's 'void *data' to 'const void *data'.

- Document the curl_blob struct in each _BLOB opt doc.

Prior to this change the user may have faced a compiler warning when
assigning their const blob data to the non-const curl_blob data pointer.

Bug: https://curl.se/mail/lib-2021-02/0048.html
Reported-by: Laurent Dufresne

Closes #xxxx

### CODE REVIEW

**Comment by bagder** [comment]
Can we be certain this can be done everywhere without breaking ABI?

**Comment by tomalakgeretkal** [comment]
And are there no usages that intend to change the data? Will there never be any?
I would not change this existing type. At most, a similar `const` one to go alongside it.

**Comment by bagder** [comment]
No that should be safe. One of the primary ideas is actually to allow the application to pass on read-only memory as input.

**Comment by tomalakgeretkal** [comment]
In that case, it seems like an excellent idea as presented, and I would add a suggestion to document exactly that in comments alongside its definition in easy.h.

I don't believe this'll cause any ABI changes.

**Comment by jay** [comment]
> Can we be certain this can be done everywhere without breaking ABI?

I think it would probably be fine, however the C89 (or any later) standard says _"Moreover, two structure, union, or enumeration types declared in separate translation units are compatible if they have the same number of members, the same member names, and compatible member types; for two structures, the members shall be in the same order"_ (3.1.2.6). and _"For two qualified types to be compatible, both shall have the identically qualified version of a compatible type"_ (3.5.3). In this case the new type member is qualified const and the old type member isn't qualified at all, which isn't defined therefore afaict it's not truly backwards compatible.

**Comment by jay** [comment]
Also some of the API functions we pass it to may expect non-const data even if they don't modify. Schannel for one uses [CRYPT_INTEGER_BLOB](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa381414(v=vs.85)) which is non-const. OpenSSL's is a memory BIO which is const. Secure Transport I'm not sure.

**Comment by tomalakgeretkal** [comment]
@jay  Neither type is qualified.

**Comment by jay** [comment]
What I mean is `void *data` and `const void *data`, only one of them is qualified with const.

**Comment by tomalakgeretkal** [comment]
They are different types, but neither of them is `const`-qualified. `const void*` (or `void const*`) is not the same thing as `void* const`.

**Comment by jay** [comment]
Yes but what it points to is qualified.

**Comment by jay** [comment]
Having second thoughts about this. The user may want to free the blob data after the transfer like free(b->data) which they can't do without warning if it's const.

**Comment by reduf** [comment]
Hey (I'm Laurent),

so before sending the original mail, I was looking at how this `struct curl_blob` was used in libcurl and found the mentioned use of [CRYPT_INTEGER_BLOB](https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/aa381414(v=vs.85)). I thought this is why led to the current decision (non-const), but from this conversation it's not so clear anymore.

[PFXImportCertStore](https://docs.microsoft.com/en-us/windows/win32/api/wincrypt/nf-wincrypt-pfximportcertstore) doesn't seem to guarantee anywhere that the blob won't be modified. Does it make sense to rely on this behavior in libcurl?

Maybe the most robust thing to do is to simply document that the field `data` of `struct curl_blob` is immutable when `CURL_BLOB_COPY` is set.

**Comment by bagder** [comment]
> Maybe the most robust thing to do is to simply document that the field `data` of `struct curl_blob` is immutable when `CURL_BLOB_COPY` is set.

I think this is the safest way forward that is certain to not break ABI and it will not cause any new compiler warnings that adding `const` might introduce.

**Comment by jay** [comment]
Abandoned, closing. IMO it's implied that CURL_BLOB_COPY won't change the data but I won't object to a PR.

**Pull request closed without merging**
