### PR TITLE
shiftmedia-libgnutls test

### PR DESCRIPTION
**Pull request by talregev**
shiftmedia-libgnutls test
I am testing latest shiftmedia vcpkg. I updated it on vcpkg, now test it in the ci.
from upstream comment:
> Ive update the repo to version 3.8.7 and as part of that Ive modifed the project to use the gnulib implementation of open/close/read/write (and a few others). This should handle the crash in read_file. Ive checked everything I can so I think ive included everything that is needed, however, if there are still issues I would need a minimal reproducable test case before I can even start looking into what else is going on.
Anyway try the latest version and let me know if it fixes the issues

https://github.com/ShiftMediaProject/gnutls/issues/23#issuecomment-2424949932

Do curl have a small test case to send upstream to test shiftmedia-libgnutls?

### CODE REVIEW

**Comment by talregev** [comment]
I am able to connect to http3 with shiftmedia-libgnutls on windows:

```
>curl --version
curl 8.10.1-DEV (Windows) libcurl/8.10.1-DEV GnuTLS/3.8.7 zlib/1.3.1 ngtcp2/1.7.0 nghttp3/1.6.0
Release-Date: [unreleased]
Protocols: http https ipfs ipns
Features: alt-svc AsynchDNS HSTS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM SSL threadsafe TLS-SRP Unicode UnixSockets
```

```
>curl -IL --http3 --ca-native https://google.com
HTTP/3 301
location: https://www.google.com/
content-type: text/html; charset=UTF-8
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-Bd2og_wzAYHkkaV5QZHPdw' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
date: Wed, 23 Oct 2024 16:34:34 GMT
expires: Fri, 22 Nov 2024 16:34:34 GMT
cache-control: public, max-age=2592000
server: gws
content-length: 220
x-xss-protection: 0
x-frame-options: SAMEORIGIN
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000

HTTP/3 200
content-type: text/html; charset=ISO-8859-1
content-security-policy-report-only: object-src 'none';base-uri 'self';script-src 'nonce-0K7pPTLwQCY6VC__dHbJwA' 'strict-dynamic' 'report-sample' 'unsafe-eval' 'unsafe-inline' https: http:;report-uri https://csp.withgoogle.com/csp/gws/other-hp
accept-ch: Sec-CH-Prefers-Color-Scheme
p3p: CP="This is not a P3P policy! See g.co/p3phelp for more info."
date: Wed, 23 Oct 2024 16:34:34 GMT
server: gws
x-xss-protection: 0
x-frame-options: SAMEORIGIN
expires: Wed, 23 Oct 2024 16:34:34 GMT
cache-control: private
set-cookie: AEC=AVYB7cotpP5u7PevT-TelmEqsX2DF6_ZZM2R0-tMnjRZBNwfVBTGZiZpAvQ; expires=Mon, 21-Apr-2025 16:34:34 GMT; path=/; domain=.google.com; Secure; HttpOnly; SameSite=lax
set-cookie: NID=518=pGaMbsAyAv7V2LwY9JIOfAKgvkZpLXUMyv_C4UAqX0vACiEIJrQPVSyker19KZiGFejv8JWmJU2HO2Zi0yoly58KOnd2UGDoyLk_rc6UBNrqO29rKRob66trCk5nTEPyv8y5eLN1n_8HyKkljvTKPJ92zMPKvLo2iF5e0BR0uPiD32Gj59ZUAnfBaTdjiZA; expires=Thu, 24-Apr-2025 16:34:34 GMT; path=/; domain=.google.com; HttpOnly
alt-svc: h3=":443"; ma=2592000,h3-29=":443"; ma=2592000
```

connect to curl site, it didn't connect:

```
>curl -ILvvvv --http3 --ca-native https://curl.se/
19:37:19.432192 [0-x] == Info: [READ] client_reset, clear readers
19:37:19.452314 [0-0] == Info: Host curl.se:443 was resolved.
19:37:19.456920 [0-0] == Info: IPv6: (none)
19:37:19.459667 [0-0] == Info: IPv4: 151.101.1.91, 151.101.129.91, 151.101.193.91, 151.101.65.91
19:37:19.470661 [0-0] == Info: [HTTPS-CONNECT] added
19:37:19.474851 [0-0] == Info: [HTTPS-CONNECT] connect, init
19:37:19.479767 [0-0] == Info: [HAPPY-EYEBALLS] created ipv4 (timeout 149976ms)
19:37:19.484878 [0-0] == Info: [HAPPY-EYEBALLS] ipv4 starting (timeout=149974ms)
19:37:19.490102 [0-0] == Info:   Trying 151.101.1.91:443...
19:37:19.494393 [0-0] == Info: [UDP] cf_socket_open() -> 0, fd=420
19:37:19.499654 [0-0] == Info: [UDP] QUIC socket 420 connected: [192.168.0.253:64205] -> [151.101.1.91:443]
19:37:19.506938 [0-0] == Info: [UDP] cf_udp_connect(), opened socket=420 (192.168.0.253:64205)
19:37:19.513729 [0-0] == Info: GnuTLS ciphers: NORMAL:-VERS-ALL:+VERS-TLS1.3:-CIPHER-ALL:+AES-128-GCM:+AES-256-GCM:+CHACHA20-POLY1305:+AES-128-CCM:-GROUP-ALL:+GROUP-SECP256R1:+GROUP-X25519:+GROUP-SECP384R1:+GROUP-SECP521R1:%DISABLE_TLS13_COMPAT_MODE
19:37:19.531644 [0-0] == Info: [HTTP/3] No cached session ID for https://curl.se:443
19:37:19.537944 [0-0] == Info: [HTTP/3] vquic_send(len=1200, gso=1200) -> 0, sent=1200
19:37:19.543668 [0-0] == Info: [HAPPY-EYEBALLS] ipv4 connect -> 0, connected=0
19:37:19.548056 [0-0] == Info: [HTTPS-CONNECT] connect -> 0, done=0
19:37:19.554510 [0-0] == Info: [UDP] adjust_pollset, !active, POLLIN fd=420
19:37:19.559578 [0-0] == Info: [HAPPY-EYEBALLS] adjust_pollset -> 1 socks
19:37:19.564514 [0-0] == Info: [HTTPS-CONNECT] adjust_pollset -> 1 socks
19:37:19.570743 [0-0] == Info: [HTTP/3] loading trust anchors and CRLs
19:37:19.584523 [0-0] == Info: found 84 certificates in native ca store
```

**Comment by talregev** [comment]
@Sibras I run the latest shiftmedia-libgnutls on curl ci. The tests are hang. I am not sure what is not working.
Maybe @vszakats can help us here.

**Comment by vszakats** [comment]
In CI it's tricky to figure out which tests is hanging/busylooping. If you can run the build and tests locally, it might be easier by looking at Process Explorer to see which process (and test number) is hanging or pegging the CPU.
In CI you can try passing `-j0` to TFLAGS to disable parallel tests and if lucky the last test will be the problematic one. (if unlucky the test doesn't happen in non-parallel mode.)

**Comment by talregev** [comment]
> In CI it's tricky to figure out which tests is hanging/busylooping. If you can run the build and tests locally, it might be easier by looking at Process Explorer to see which process (and test number) is hanging or pegging the CPU. In CI, you can try passing `-j0` to TFLAGS to disable parallel tests and if lucky the last test will be the problematic one. (if unlucky the test doesn't happen in non-parallel mode.)

Thank you for your advice. I run the ci with -j0:
  test 0310...[simple HTTPS GET] is hang.

**Comment by bagder** [comment]
So "shiftmedia-libgnutls" is GnuTLS built for Windows?

Can we call it just "gnutls" perhaps? It seem weird to name it like it is something else.

**Comment by talregev** [comment]
> So "shiftmedia-libgnutls" is GnuTLS built for Windows?
> 
> Can we call it just "gnutls" perhaps? It seem weird to name it like it is something else.

This is unofficial fork of gnutls to compile and run on windows. This is the name that is given by vcpkg.

**Comment by vszakats** [comment]
> > In CI it's tricky to figure out which tests is hanging/busylooping. If you can run the build and tests locally, it might be easier by looking at Process Explorer to see which process (and test number) is hanging or pegging the CPU. In CI, you can try passing `-j0` to TFLAGS to disable parallel tests and if lucky the last test will be the problematic one. (if unlucky the test doesn't happen in non-parallel mode.)
> 
> Thank you for your advice!🙏🏻 I run the ci with -j0: test 0310...[simple HTTPS GET] is hang.

That's a good lead, glad it worked.

There is also a list of failing tests before hitting the hang, starting with:
```
test 0300...[simple HTTPS GET]
```

**Comment by talregev** [comment]
@Sibras write me:
> If you can make make a mininal reproducable test program then ill take a look at it and see if i can debug what the issue is

https://github.com/ShiftMediaProject/gnutls/issues/23#issuecomment-2439432540

I don't have the knowledge to do minimal reproducible example.
Can someone here can help him?

**Comment by edmcln** [comment]
> I don't have the knowledge to do minimal reproducible example.
> Can someone here can help him?

I believe you don't need to write any code. I'm not familiar with this library, does it come with the cli tool (gnutls-cli.exe)? If so, you could use the cli tool and repeat the test. In theory, you should be able to trigger the same bug.

You could run the server on linux, and the cli tool on Windows (with some adjustments) or use Windows for both (requires stunnel and strawberry-perl?).

The command line for the server looks like this:

`./secureserver.pl --pidfile "log/server/https_server.pid" --logfile "log/https_stunnel.log" --logdir "log" --ipv4 --proto https --certfile "Server-localhost-sv.pem" --stunnel "/usr/bin/stunnel4" --srcdir "." --connect 46807 --accept 43979`

The curl command line for the test 310 (we only care about the `url` & `cacert` path):

`../src/curl -q --output log/curl310.out  --include --trace-ascii log/trace310 --trace-config all --trace-time --cacert ./certs/EdelCurlRoot-ca.crt https://localhost:43979/310 > log/stdout310 2> log/stderr310`

Hope this helps.

**Comment by bagder** [comment]
@talregev is this PR still in the works?

**Comment by talregev** [comment]
@bagder I contact the owner of shiftmedia-libgnutls about the bug, he want a minimal reproducible test program that can show the bug.
Unfortunately I don't have the knowledge to provide such a test program. 
Maybe someone in curl community can help?

See the commetns:
https://github.com/ShiftMediaProject/gnutls/issues/23#issuecomment-2439432540

**Comment by bagder** [comment]
This sounds like a GnuTLS on Windows problem, not a curl problem. I propose we close this PR until we believe there is a chance it can move forward.

**Comment by talregev** [comment]
ok.

**Pull request closed without merging**
