### PR TITLE
tests/server/util.c: fix support for Windows Unicode builds

### PR DESCRIPTION
**Pull request by mback2k**
Detected via #6066

### CODE REVIEW

**Comment by mback2k** [comment]
@bagder would you mind waiting with the release tomorrow till this and #6066 is merged to make sure we have a good state of curl on Windows before release?

**Comment by bagder** [comment]
Sorry, but no. There's no delaying of the release, I can't deal with that this late. Both these changes are also in testing/CI and doesn't actually change the product we ship tomorrow.

**Comment by mback2k** [comment]
Yes, I get that. Unfortunately these issues mean that we have no way to know if Unicode curl is working or not on Windows at the moment. Unless someone performs a manual test with the changes applied. cc @MarcelRaad @vszakats

**Comment by jay** [comment]
It looks correct as long as the TEXT macro is available (windows.h included). I don't know much about cmake and #6066. If there is some command you need me to run here let me know, I have cmake version 3.18.1 installed in Windows.

**Comment by mback2k** [comment]
Since the non-Unicode CI completed successfully, I will merge this in a few minutes since this means the macro is available as assumed.

**Pull request closed without merging**
