### PR TITLE
#1613 Some quoted commands require real path

### PR DESCRIPTION
**Pull request by JohnDeHelian**
Added realPathname function needed to perform some
quoted commands

### CODE REVIEW

**Comment by JohnDeHelian** [comment]
This is my first commit ever using Git. I'm very unfamiliar with Git and the process. If anything has been done improperly please let me know.

**Comment by bagder** [comment]
The key here is "Some checks were not successful". Click the '[Details](https://travis-ci.org/curl/curl/builds/265701439?utm_source=github_status&utm_medium=notification)' link for the travis errors and you get a listing of all the builds your pull-request ran on travis.

Those that have red markings failed somehow (they should be green). Click on one of them and scroll down the build output until you see the error.  They seem to mostly report this:

```
ssh.c:3427:25: error: conversion to ‘unsigned int’ from ‘size_t’ may alter its value [-Werror=conversion]
     for(i = 0, j= strlen(*path); i <= strlen(cp); i++) {
```
You can just fix that in your git branch, and then push that commit and it'll appear here and run another travis build.

**Comment by JohnDeHelian** [comment]
Sorry for the sloppy check ins. I still don't quite understand the process. I was trying to amend my fork but didn't succeed so then there were three separate commits to fix the reported errors and warnings.

**Comment by bagder** [comment]
If you check test 608 and 610 in the travis builds on Linux you see they now fail with this PR applied. Do they work for you locally?

**Comment by JohnDeHelian** [comment]
Sorry again for the difficulty in adding this patch. I created a new branch sftpQuoteAllowRelativePath so I could start over with the latest master. I'm still getting used to git and github. Please delete the pull request for realPath.

**Comment by bagder** [comment]
Replaced by #1900

**Pull request closed without merging**
