### PR TITLE
LDAP: updated documentation per #878 changes

### PR DESCRIPTION
**Pull request by snikulov**
Updated documentation according #878 code changes.

### CODE REVIEW

**Comment by captain-caveman2k** [comment]
Many thanks @snikulov,

Unfortunately, I think we need to add some updates to the following as well:

docs/curl.1
docs/TODO - add "auth= in URLs" to LDAP (copy and paste item from HTTP section)
docs/libcurl/libcurl-tutorial
docs/libcurl/opts/CURLOPT_USERPWD.3
docs/libcurl/opts/CURLOPT_USERNAME.3
docs/libcurl/opts/CURLOPT_HTTPAUTH.3

**Comment by snikulov** [comment]
@captain-caveman2k Unfortunately, I'm not familiar with format used in files you've mentioned.
Could you please help me with those files?
Thank you.

**Comment by captain-caveman2k** [comment]
@snikulov Any progress on this as I would like to get this change into 7.50.2 which we might lable 7.51 with this change?

The format of the files is plain text and very easy to understand ;-)

**Comment by snikulov** [comment]
Sorry @captain-caveman2k 
I do whatever I can do. You can merge or reject.

**Comment by bagder** [comment]
ping @snikulov and @captain-caveman2k, what's the status here you think? Going forward or closing?

**Pull request closed without merging**
