### PR TITLE
url: assume UTF-8 when doing idn2 lookup

### PR DESCRIPTION
**Pull request by ghedo**
Thanks to Tim Rühsen for the suggestion.

### CODE REVIEW

**Comment by bagder** [comment]
Is this really the right way? In your test case, you passed in UTF-8 while having an environment setup that said you wouldn't use UTF-8. Isn't that rather a user error?

If I understand things correctly, the `*_ul()` function is supposed to work with the current locale that is used, which thus should make us support even non-UTF-8 locales for the ones that happen to use those. Switching to `*_u8()` will then instead force such users to recode to UTF-8.

I want to emphasize that this is just a question, I'm really not well versed in locales, unicode, UTF8 or IDNA.

**Comment by rockdaboot** [comment]
If curl doesn't do any normalization of the input, then the *_ul() function is correct. But in this case, you have to amend your tests. If they run in non-UTF-8 locale, any (domain) input to curl must be converted to the current locale in advance, else *_ul() will misbehave. You could simply do that by using the `iconv` tool.

The approach of this pull request it to assume UTF-8 input. I suggested that because I was sure that curl (as other tools like wget) 'normalize' the input to UTF-8.

The current locale doesn't always is the correct encoding for input strings. Maybe the user copied them from a file in a different encoding. For such cases wget has --local-encoding to override the current locale. That takes away the extra `iconv` step for the user.

That should be enough information to make a decision for *_ul() or *_u8().

**Comment by ghedo** [comment]
I wonder if it would make sense to check if the input is UTF-8 in advance. Does _u8 return an error if the input isn't UTF-8 (`IDN2_ENCODING_ERROR` maybe?)? If so we could just retry with _ul if _u8 fails. Or maybe _ul could just check if the input is UTF-8 already and just pass it through (assuming it doesn't do that already).

**Comment by rockdaboot** [comment]
You are looking for an imperfect shortcut.
UTF-8 detection is a heuristic method (at least a pretty good one), so not 100% save - expect bug reports or CVEs in the future.
_u8() simply gives the input string to libunistring's u8_to_u32() which likely gives you an error (transformed to IDN2_ENCODING_ERROR by _u8()) if the input is not utf-8. But basically this is the same as your heuristic before.
_ul() is u8_strconv_from_locale() + _u8(). Why should u8_strconv_from_locale (libunistring) check for utf-8 ? Same heuristic argument matches here...

For me it is pretty simple: curl must know about the encoding of input strings resp. rely on what the user provides. Anyways, it would be nice if the user could say which encoding the string (e.g. URL) has that he provides to curl. With such an option you can also make your tests locale independent without fiddling with the iconv tool. FYI, wget2 has 3 settable input encodings, one for the command line, one for stdin and one for files to parse (all three sources of URLs can be used in parallel and maybe the encoding is different in all three cases).

**Comment by bagder** [comment]
Well, libcurl only as one entry point to specify the URL so if we would have URL encoding as an option, it would have to be a new `curl_easy_setopt()` value 

Previously when we used libidn, [we had a hack for windows](https://github.com/curl/curl/blob/42b650b9ea5f26b2f5347af3072eaf690658ed62/lib/easy.c#L153) that extracted the charset and set it in the environment variable "CHARSET" as a hint for libidn to use when dealing with the host name (brought by @gvanem in commit 877f16e5a5222a13e69ab3477). Given that, I suppose trying to figure out the existing locale/charset is the most backwards compatible, if somewhat unreliable, way. I think we can be reasonably sure that there will be other encodings than UTF8 used, especially on windows which doesn't normally use that as much if I understand things correctly.

**Comment by rockdaboot** [comment]
Just looked up the sources of libidn, libidn2, libunistring.

*libidn*
The CHARSET var seems to be a special hack, part of a home-grown way to find out the locale.

*libidn2*
Calls u8_strconv_from_locale() from libunistring which in turn calls gnulib's locale_charset().
This function addresses all kinds of (even old) OSes - it looks very likely that this function works for Windows as well.

So, if you are using the _ul() function of libidn2, you should be fine. But your IDN tests should set the locale so it matches the string/URL encoding used in those files.

In that way a possible encoding option can be separately handled later.

**Comment by bagder** [comment]
> if you are using the _ul() function of libidn2, you should be fine. But your IDN tests should set the locale so it matches the string/URL encoding used in those files.

Yes, I think this matches my impression/conclusion as well. We should have our IDNA tests set the correct locale to match the encoding used when they pass strings to curl.

**Comment by ghedo** [comment]
My only concern was the tests failures in the Debian packages build, but given the discussion here I guess it's just because of fragile tests rather then actual problems in the code, so this PR is not needed.

**Pull request closed without merging**
