### PR TITLE
easy_transfer: Timeout fix

### LINKED ISSUE #3305: Unexpected timeouts
Hi,

### I did this
I have a simple URL that takes some time before reply.
For example: "http://127.0.0.1/sleep.php?sleep=5.3" will took 5.3 seconds.
```
<?php
usleep($_GET['sleep']*1000*1000):
echo "OK";
```
I also have a small program based on (https://curl.haxx.se/libcurl/c/simple.html).
Basically I've changed the URL and added timeout control:
`curl_easy_setopt(curl, CURLOPT_TIMEOUT, 6L);`
Or (tested both with same results):
`curl_easy_setopt(curl, CURLOPT_TIMEOUT_MS, 6*1000);`

When I run the program it raises a timeout error after 6 seconds of execution.
`curl_easy_perform() failed: Timeout was reached`

### I expected the following

Timeout should not be raised when the client receives the response before the specified timeout option.

### curl/libcurl version

After some work, I've found the problem starts with this commit, merged before 7.61.0:
https://github.com/curl/curl/commit/3ef67c6861c9d6236a4339d3446a444767598a58

### operating system
Linux 4.18.0-2-amd64 (Debian based)

### PR DESCRIPTION
**Pull request by frikiluser**
Closes #3305

### CODE REVIEW

**Comment by bagder** [comment]
What platform do you run your libcurl code on? What resolver backend was that built to use? (it uses the threaded one by default)

**Comment by frikiluser** [comment]
Hi,

My first commit remove the line:
`Curl_wait_ms((int)sleep_ms);`

Probably this commit introduces the busy-loop in case "curl_multi_wait" returns instantly.

After, I've "git push --force" a code based on the code before commit 3ef67c6861c9d6236a4339d3446a444767598a58. I think this code doesn't introduce a busy-loop.

Sorry if it generated a confusion.


Are you able to reproduce the bug? I'll upload complete c code to reproduce easily (server + client).
I've found the commit that introduced the bug using "git bisect". So I'm pretty sure the bug shows up since this commit exact.
ODD time response times (in seconds) works fine because the timeout occurs in Curl_multi_wait.
EVEN times fails because the timeout occurs in Curl_wait_ms and it doesn't wait for socket events.

Looking into the code...
`mcode = curl_multi_wait(multi, NULL, 0, 1000, &rc);`
This line should update 'rc' value.
What is the expected value for 'rc'? I've observed it set rc=0 even after connection is open (and TCP.ACK is sent to the server). Is it expected?


I've reproduced the bug in Debian testing (Buster). Also reproduced building libcurl from sources without changing any default. I'm not sure about the "resolver backend", sorry.

**Comment by frikiluser** [comment]
> In case TIMEOUT=5, the client receives the response during "curl_multi_wait", and it works like a charm.
Of course in this case you should run the server with parameter 4210.

**Comment by bagder** [comment]
Thanks to the lovely code snippets @frikiluser, I can reproduce the issue. Looking into this...

**Comment by frikiluser** [comment]
It also works for me. Thanks a lot!!

I'll try to test the patch intensively next week.

**Pull request closed without merging**
