### PR TITLE
CURLINFO_XFER_STATE info

### PR DESCRIPTION
**Pull request by neovasant**
Sometime back I had a requirement(asynchronous model - synchronous till connect + request write and return control) that needed internal state of easy handle. Refer these threads for my interaction with Daniel
http://stackoverflow.com/questions/30030202/libcurl-multi-asynchronous-support 
This PR includes patch shared by Daniel(https://curl.haxx.se/mail/lib-2013-08/0029.html) with minor changes along with sample program.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks, but there are some gaps present here that we need to fix before we can consider merging this.

First: do we really need a new separate epoll example, can't the existing example just be adjusted to extract the state? If not, can't do do the example in plain C instead of C++ (and make it follow our code style) ? And please add comments to the example that explains why it does what it does.

Then, there's no documentation for this new feature and I have a feeling it will take quite a lot of documentation for anyone to be able to use this. Which brings me to: what exactly are you intending to use this state for? That SO question is still making me get a feeling that you won't get your desires satisfied with this feature alone.

We also need a test or two added that verify at least basic feature functionality.

**Comment by neovasant** [comment]
1. In our environment we did not want to use select nor introduce dependencies to event libraries hence we used epoll to build non blocking async rest client wrapper over libcurl multi interface. This partial example could serve as reference to other developers who might be in similar situation.
2. C++ : I've used std::map to keep track of request and associated easy handle . With this it's easier to timeout,  retry, log and mark status based on associated easy handle state. I'll add some more comments in the sample program.
3. Existing examples demonstrate firing requests simultaneously and block for response on all. This example is to demonstrate non blocking mode i.e. for each request block only till it's written to socket(DNS + tcp connect + handshake + request write) . To achieve this we need the current state of easy handle associated with the request. This will allow client application to do some other processing once the control is returned after request write. Client app can block for response on a particular request later or ignore(fire and forget).

Shall I add the status check to existing test case lib597.c?

**Comment by bagder** [comment]
> Existing examples demonstrate firing requests simultaneously and block for response on all

Not at all. That seems like a misunderstanding of the API. The multi API doesn't "block" at all (*). You add any amount of easy handles, then run libcurl when something happened but it doesn't block. This new suggested way to extract state information will not make it block any less (nor more).

Instead you seem to want to *add* blocking to your code for a particular duration of a handle's life time. Can you explain to us what purpose that has?

> This will allow client application to do some other processing once the control is returned after request write

You get control back much earlier than so. The only difference this adds, is that now your application can know when the request has been sent. But I'm more curious about why you need to know when the request has been sent.

As you can tell, I'm reluctant to allow exporting of this internal state unless there's a clear use case proving that it fulfills a good purpose. I'm convinced this is a little pandora's box here waiting, and once this gets added it'll get used and we'll have to support it, make it reliable, document it and more. I don't think we should walk that route without having it properly motivated.

(*) = unfortunately it *does* block at times, but those are rare situations and we are always working on minimizing/removing those situations.

**Comment by neovasant** [comment]
Apologies Daniel. I might not have used proper terminology.

I did not mean multi API is blocking but client application has to block. Internal states will let the application decide on how long to block/wait. You are right about blocking till request is written in our case. I'll try to provide clear use case which is widely prevalent in our environment:
Assume there's client X that has to invoke services A, B, C and D. Calls can be async, sequential or fire and forget.
* Calls to A and B can be async but Call B only if A was reachable(request written to socket). In the worst case this will allow app to make decision quickly and avoid unnecessary calls to B if A was unreachable.  
* X Blocks for response from A and B.
* Calls to C and D (requests composed using responses from A and B) can be async and independent i.e. Fire request to D irrespective of whether C was reachable.
* Block for response from C only or both. 

Apart from supporting such composition of calls, access to states has allowed us to implement logging/retry/timeout at the request level. Subset of states exposed has served our use cases well for more than a year now. I understand your reluctance and agree this could become maintenance nightmare if exposed states are not enough for others.

**Comment by bagder** [comment]
> if A was reachable(request written to socket)

So you're gonna use libcurl's internal state to decide that? what if the server then responds a 5xx to that or perhaps even the connection just gets closed immediately and we don't even know if the server received the request or not? It is terribly fragile and error-prone to deem a HTTP operation successful just because data was sent to the kernel by libcurl!

> access to states has allowed us to implement logging/retry/timeout at the request level

True, by using the different states an application gets a whole new ability to do differentiated timeouts. Possibly the best motivation for this feature I've read so far!

Oh, and you should look at the failed CI build which point out some nits in your PR.

**Comment by neovasant** [comment]
Libcurl state is not used to infer HTTP operation status. It's only used in limited way to decide whether to go ahead with the dependent async service call.
In case of two dependent async service calls, the motivation at framework level is to avoid the second one if the first endpoint is unreachable(DNS, tcp connect or handshake) due to system issues. This ensures second service capacity is not wasted with calls whose response will be ignored by client as the first service was unreachable. Ensures reduced latency on the client side as well.
5XX responses are left to application as those could indicate application/server side issues. 

In our case main goal was composition of service calls followed by differentiated timeouts, request retry and logging for metrics collection.

I'll look at the CI failure(). Also shall I add the status check to existing test case lib597.c?

**Comment by bagder** [comment]
Note that you still have compiler warnings to fix and test 1119 fails due to missing symbols in `symbols-in-versions`

**Comment by neovasant** [comment]
Yes, state won't be needed in case of failure. It is essential in case of success (i.e. first service is reachable) to fire the subsequent async request reliably and without any delay. 
Without state, one option is to wait for a fixed amount of time to see if there's error or else proceed with the next async request. This will introduce unnecessary latency if the dns + tcp connect + handshake are faster.
Can you provide some inputs on the latest CI failures(1139, 1140)?

**Comment by neovasant** [comment]
Current failure does not seem to be related to this change. Can you provide some pointers?

> test 1086...[FTP download with strict timeout and slow data transfer]
 1086: protocol FAILED:

**Comment by bagder** [comment]
Asked for [feedback on the mailing list](https://curl.haxx.se/mail/lib-2017-05/0084.html)

**Comment by bagder** [comment]
I find very little to non-existing support for this feature. It simple exports too much internal info with very little gains, plus the fact that apps would need to poll to notice transitions etc. I don't see us merging this feature. Sorry.

**Comment by neovasant** [comment]
Thanks for the discussion Daniel.

**Pull request closed without merging**
