### PR TITLE
travis: build the examples too

### PR DESCRIPTION
**Pull request by bagder**
to make sure they keep building warning-free

### CODE REVIEW

**Comment by MarcelRaad** [comment]
Isn't `--enable-werror` only for the library and tool? IIRC, the examples and tests always build without warnings-as-errors. But keeping them building at all is an improvement too of course :-)

**Comment by bagder** [comment]
Yes, I'm mostly concerned that they build at all, I'm not at all convinced that `--werror` is a good idea for the examples.

**Comment by MarcelRaad** [comment]
Ah, I misread the description to mean that. Yes, warnings-as-errors doesn't even work on Windows without complicating the examples because some WinSock function parameter is `unsigned int` when it should be `size_t`.

**Comment by bagder** [comment]
Thanks for the review @MarcelRaad

**Pull request closed without merging**
