### PR TITLE
cmake: Fix libcurl.pc and curl-config library specifications

### LINKED ISSUE #6169: cmake: libcurl.pc uses absolute library paths
The libcurl.pc file generated by cmake contains things like `Libs.private:  /usr/lib64/libssl.so /usr/lib64/libcrypto.so /usr/lib64/libz.so`. The autotools equivalent would say `Libs.private: -lssl -lcrypto -lz`.

Not sure of the implications. But I guess it would affect, for example, somebody who wants to use also a static version of libz.

### LINKED ISSUE #12748: Build using cmake incorrectly creates Libs.private with full paths
### I did this

Compile with `configure` generates a libcurl.pc with

### correct
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
supported_protocols="FILE FTP FTPS HTTP HTTPS RTMP RTSP"
supported_features="AsynchDNS HSTS HTTP2 HTTPS-proxy IDN IPv6 Largefile NTLM SSL TLS-SRP UnixSockets alt-svc libz threadsafe"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with ftp, http, etc.
Version: 8.5.0
Libs: -L${libdir} -lcurl 
Libs.private: -lnghttp2 -lidn2 -lrtmp -lz -lssl -lcrypto -lssl -lcrypto -lssl -lcrypto -lz -lgcc
Cflags: -I${includedir}
```
Build with cmake
### incorrect
```
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
supported_protocols="FILE FTP FTPS HTTP HTTPS RTMP RTSP"
supported_features="SSL IPv6 UnixSockets libz AsynchDNS IDN Largefile alt-svc HSTS NTLM TLS-SRP HTTP2 HTTPS-proxy threadsafe"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with ftp, http, etc.
Version: 8.5.0
Libs: -L${libdir} -lcurl 
Libs.private:  -lgcc -lgcc_s -lc -lgcc -lgcc_s -lidn2 /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86_64-12.0-dev
el/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libssl.so /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreELEC-Generic.x86
_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libcrypto.so /var/media/DATA/home-rudi/LibreELEC.tv/build.LibreE
LEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libz.so /var/media/DATA/home-rudi/LibreELEC.tv/bu
ild.LibreELEC-Generic.x86_64-12.0-devel/toolchain/x86_64-libreelec-linux-gnu/sysroot/usr/lib/libnghttp2.so
Cflags: -I${includedir}
```

### I expected the following

libcurl.pc should be -lyyyyy

### curl/libcurl version

curl 8.5.0

### operating system

LibreELEC 12 master build

### PR DESCRIPTION
**Pull request by levitte**
Letting CMake figure out where libraries are located gives you full paths.
When generating libcurl.pc and curl-config, getting libraries as full paths
is unusual when one expects to get a list of -l<libname>.

To meet expectations, an effort is made to convert the full paths into
-l<libname>, possibly with -L<libdir> before it.

Fixes #6169
Fixes #12748

### CODE REVIEW

**Comment by levitte** [comment]
I'm wondering, should this also avoid adding a `-L${_libdir}` when `_libdir MATCHES "^/usr/lib"`?

**Comment by jay** [comment]
> I'm wondering, should this also avoid adding a `-L${_libdir}` when `_libdir MATCHES "^/usr/lib"`?

shouldn't that be true of all default linker paths?

**Comment by levitte** [comment]
> > I'm wondering, should this also avoid adding a `-L${_libdir}` when `_libdir MATCHES "^/usr/lib"`?
> 
> shouldn't that be true of all default linker paths?

Sooo...  I'm thinking checking `_libdir` against `CMAKE_SYSTEM_LIBRARY_PATH` could address that?  Would you agree?

**Comment by jay** [comment]
Sounds fine to me but hopefully someone more familiar with cmake can step in to review.

**Comment by levitte** [comment]
Getting the system path checking right took a little more than I expected...  but I think I got it.

**Comment by heitbaum** [comment]
Using this patch the resulting .pc file is - similar to that of the configure output.

```
…
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib
includedir=${prefix}/include
supported_protocols="FILE FTP FTPS HTTP HTTPS IPFS IPNS RTMP RTSP"
supported_features="SSL IPv6 UnixSockets libz AsynchDNS IDN Largefile alt-svc HSTS NTLM TLS-SRP HTTP2 HTTPS-p
roxy threadsafe"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with ftp, http, etc.
Version: 8.6.0
Libs: -L${libdir} -lcurl 
Libs.private:  -lgcc -lgcc_s -lc -lgcc -lgcc_s -lidn2 -lssl -lcrypto -lz -lnghttp2
Cflags: -I${includedir}
```

**Comment by levitte** [comment]
Do you deem it good enough?

**Comment by heitbaum** [comment]
> Do you deem it good enough?

👍Looks great

**Comment by vszakats** [comment]
I suggest adding `Fixes #6169` to the commit message. This was an earlier report for what it looks like this same issue.

Then delete the KNOWN_BUGS entry added in 192099333b8c6c1da894e08c3471befd67225730.

**Comment by levitte** [comment]
> I suggest adding `Fixes #6169` to the commit message. This was an earlier report for what it looks like the same issue.
> 
> Then delete the KNOWN_BUGS entry added in [1920993](https://github.com/curl/curl/commit/192099333b8c6c1da894e08c3471befd67225730).

Both done

**Review by vszakats — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
