### PR TITLE
tool: Rename GETOPT_USEREMOTE to GETOPT_USER_REMOTE

### PR DESCRIPTION
**Pull request by emilengler**
This is a minor fix but in my opinion the old CPP name looks a bit awkward and ugly to the eye.

### CODE REVIEW

**Comment by bagder** [comment]
I disagree: it is meant to stand for "use the remote name", not "user remote"

**Comment by emilengler** [comment]
Ok, then I misunderstood it. I think it's best to rename it to `GETOPT_USE_REMOTE` then?

**Comment by danielgustafsson** [comment]
> Ok, then I misunderstood it. I think it's best to rename it to `GETOPT_USE_REMOTE` then?

It's not used by `getopt()` so the name should still be `GETOUT_*`. FWIW I don't see much value in renaming, and the current name matches  `GETOUT_NOUPLOAD` which also doesn't have a separator between the words.

**Comment by bagder** [comment]
This define was introduced in and has been used since commit 14ca732a8 (January 2001). We have several names in the code similar to this where USE or NO are glued to the following word. I don't think this rename helps.

**Pull request closed without merging**
