### PR TITLE
Winbuild doc

### PR DESCRIPTION
**Pull request by kdekker**
Updated documention:

- Setenv has gone. 
- A compiler (cl.exe) is not part of more recent Windows (platform) SDK's (all after v7.1)

Not updated: if a visual studio command prompt is used, the cl.exe PATH has been setup, and setting the VC variable is actually of no sense (you may like to use the VisualStudioVersion for that purpose).

Yuo may even consider drop support for ancient Visual Studio 6, resulting in the possibility to cleanup more.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks for your work, but this PR is a bit broken. It is much better if you create a new dedicated branch for each separate PR you make so that they don't intermix, In this case it looks like this PR has commits from #2455 that I just merged.

Can you rebase/squash this to only contain the relevant changes you want to change in this PR?

**Comment by kdekker** [comment]
I'm lost. When I clone a fresh repository from master (using the instructions from https://ec.haxx.se/sourcecode-contributing.html, running git clone https://github.com/curl/curl.git) I don't see any change I made on one of the files in winbuild. So I'm in doubt what has been committed now? Or do I lack knowledge in where commit #2455 resides. Is it not on the master branch? What I expected is that this #2459 PR became visible, but it is not. 

I was also expecting that switching the default branch in GitHub deskop + a new pull should update all source files to exactly the same state as on the (remote) source repository.

And finally: I see that some pieces of my changes got inserts like '<<<<<<< HEAD' and >>>>>>> parent of d01d6e338 (which were not added by me). I don't know why these exist, and whether I need to keep them. This is IMO something from git...

Can you please help me in how to proceed?

**Comment by bagder** [comment]
When you clone a fresh copy now, you should find commit 858502652 in there (which is where #2455 ended up). That was merged in the master branch a few days ago.

When you have a fresh clone, create a new local branch for each new thing you want to work on (and send pull requests for). Then you can do them independently of each other and from other things that happen on the master branch. Once your PRs have been merged, you can delete your corresponding local branch as then the stuff will trickle into the master branch when you update that.

The `<<<<<` things are just the standard merge conflict markers which indicate that your branch or now in conflict with things merged upstream.

**Comment by bagder** [comment]
(I'm not @badger) 

It looks like your master branch and the curl/curl master branch are different. Then of course added changes will add to that...

**Comment by MarcelRaad** [comment]
That happened That happened when you created https://github.com/curl/curl/pull/2455 from your master branch. Just create a new master branch from romotes/origin/master again, overwriting the old one.

**Comment by kdekker** [comment]
If I revert all changes on the master branch in my clone, am I done then? Or is there a simple 'overwrite all command'? I've stored my changes in a different place, so it is ok for me to revert all and become in sync with the curl repo.

Excuse me my innocence with git.

**Comment by MarcelRaad** [comment]
You can do
```
git reset --hard remotes/origin/master
```
which resets your local master branch to the curl github repo's master branch,

**Comment by kdekker** [comment]
Hopefully, I did al in the right way, and now created first PR from a (hopefully in sync-repo):
https://github.com/curl/curl/pull/2472

I will create another PR for the Windows makefiles.

**Pull request closed without merging**
