### PR TITLE
GHA/windows: ignore test 165 in Schannel MSVC job

### PR DESCRIPTION
**Pull request by talregev**
Schannel MSVC job: Ignore test 165 when -DUSE_WIN32_IDN=ON

After this ci is fail on Schannel
https://github.com/curl/curl/pull/14387

https://github.com/curl/curl/actions/runs/10251838878/job/28360790340?pr=14383
```
  TESTDONE: 1054 tests out of 1056 reported OK: 99%
  FAIL 165: 'HTTP over proxy with IDN host name' HTTP, HTTP GET, HTTP proxy, IDN
  TESTFAIL: These test cases failed: 165
```

### CODE REVIEW

**Comment by bagder** [comment]
I removed this the other day. Test 165 is now in `DISABLED` for `WinIDN` so should be ignored for these runs by default. Clearly something makes that fail here, but that's what we need to fix.

**Comment by talregev** [comment]
> I removed this the other day. Test 165 is now in `DISABLED` for `WinIDN` so should be ignored for these runs by default. Clearly something makes that fail here, but that's what we need to fix.

I understand. Do you want me to close this PR?

**Comment by bagder** [comment]
Either that, or to figure out why 165 was not ignored and fix that.

**Comment by vszakats** [comment]
To add: disabling AppleIDN tests fails too in GHA/macos.

**Comment by talregev** [comment]
I see that you already add these on disable test file.
I am not sure who parse it and how.

**Comment by talregev** [comment]
I don't mind to close this PR. Let me know if you know / can solve it.

**Pull request closed without merging**
