### PR TITLE
Make execpath() work correctly in Unicode build.

### PR DESCRIPTION
**Pull request by dEajL3kA**
Note:  `GetModuleFileNameA()` won't work if the path of 'curl.exe' contains any characters that cannot be represented in system's ANSI codepage. So, instead of `GetModuleFileNameA()`, we should use  `GetModuleFileName()`, which will expand to  `GetModuleFileNameW()` in Unicode builds. Also adapted code to use `TCHAR` and appropriate generic-text routine mappings.

### CODE REVIEW

**Comment by bagder** [comment]
## Build problems
~~~
x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H   -I../include -I../lib -I../src -I../lib -I../src -DCURL_STATICLIB -isystem C:/msys64/mingw64/include -isystem C:/msys64/mingw64/include -DWINVER=0x0600  -Werror-implicit-function-declaration -O2 -Wno-system-headers -Wenum-conversion -Werror -pedantic-errors -MT tool_parsecfg.o -MD -MP -MF $depbase.Tpo -c -o tool_parsecfg.o tool_parsecfg.c &&\
mv -f $depbase.Tpo $depbase.Po
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ../include/curl/system.h:422,
                 from ../include/curl/curl.h:38,
                 from ../lib/curl_setup.h:162,
                 from tool_setup.h:36,
                 from tool_parsecfg.c:22:
tool_parsecfg.c: In function 'execpath':
../lib/curl_setup.h:488:25: error: passing argument 2 of 'strrchr' makes integer from pointer without a cast [-Wint-conversion]
  488 | #  define DIR_CHAR      "\\"
      |                         ^~~~
      |                         |
      |                         char *
tool_parsecfg.c:57:52: note: in expansion of macro 'DIR_CHAR'
   57 |     TCHAR *lastdirchar = _tcsrchr(filebuffer, TEXT(DIR_CHAR));
      |                                                    ^~~~~~~~
In file included from C:/msys64/mingw64/x86_64-w64-mingw32/include/guiddef.h:154,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winnt.h:635,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/minwindef.h:163,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windef.h:9,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/windows.h:69,
                 from C:/msys64/mingw64/x86_64-w64-mingw32/include/winsock2.h:23,
                 from ../include/curl/system.h:422,
                 from ../include/curl/curl.h:38,
                 from ../lib/curl_setup.h:162,
                 from tool_setup.h:36,
                 from tool_parsecfg.c:22:
C:/msys64/mingw64/x86_64-w64-mingw32/include/string.h:93:60: note: expected 'int' but argument is of type 'char *'
   93 |   _CONST_RETURN char *__cdecl strrchr(const char *_Str,int _Ch);
      |                                                        ~~~~^~~
~~~

## Code style issues
~~~
./tool_parsecfg.c:56:5: warning: if with space (SPACEBEFOREPAREN)
   if ((len > 0) && (len < MAX_MODULE_FILE_LENGTH)) {
     ^
./tool_parsecfg.c:61:81: warning: Longer than 79 columns (LONGLINE)
     if (_tcslen(filebuffer) + _tcslen(filename) + 1U < MAX_MODULE_FILE_LENGTH) {
./tool_parsecfg.c:61:7: warning: if with space (SPACEBEFOREPAREN)
     if (_tcslen(filebuffer) + _tcslen(filename) + 1U < MAX_MODULE_FILE_LENGTH) {
       ^
./tool_parsecfg.c:62:7: warning: use of _tcscat is banned (BANNEDFUNC)
       _tcscat(filebuffer, TEXT(DIR_CHAR));
       ^
./tool_parsecfg.c:63:7: warning: use of _tcscat is banned (BANNEDFUNC)
       _tcscat(filebuffer, filename);
       ^

**Comment by dEajL3kA** [comment]
Don't understand why `_tcscat` is banned. It is generic-text routine mappings that will expand to `strcat` or `wcscat` as needed, so that Unicode and ANSI build can both be supported with the same code. What should I use instead ❓

**Comment by bagder** [comment]
`strcat()` is similarly also banned. They're prohibited simply because they're too easy to misuse due to them not having any buffer size argument/boundary. Alternative functions to use are those that make sure that the target buffer is not overflowed. Like `msnprintf()` or plain old `strncpy()` etc.

**Comment by dEajL3kA** [comment]
I see. Does `msnprintf()` have a generic TCHAR version? Is `_tcsncat()` allowed?

**Comment by vszakats** [comment]
According to the [CHECKSRC doc](https://github.com/curl/curl/blob/b67d3ba73e98cba63dc6246ee0da22ea803ec3e8/docs/CHECKSRC.md), `*ncat()` functions are not allowed and `msnprintf()` does not have a Windows-specific variant either.

A workable approach might be to convert the Win32 API result to UTF-8 right away and continue using the existing char string manipulation logic.

**Comment by dEajL3kA** [comment]
> A workable approach might be to convert the Win32 API result to UTF-8 right away and continue using the existing char string manipulation logic.

I really wanted to avoid converting from UTF-16 to UTF-8 just for the string concatenation; we'd have to convert back to UTF-16 for the `fopen` (effectively `wfopen`) right away. Not only would this be inefficient, but also _not_ better (except that it satisfies the code checker). Also the code would be more bloated/less readable with the additional (unneccessary) conversion.

So, latest version of the patch now uses `_tcsncpy`, which hopefully should be fine.

**Comment by vszakats** [comment]
@dEajL3kA: Fair point, I totally missed `fopen()` lurking there. Current version LGTM.

**Comment by bagder** [comment]
I don't see any action on this.

**Pull request closed without merging**
