### PR TITLE
avoid using SECONDARYSOCKET when FTP is not support

### PR DESCRIPTION
**Pull request by MAntoniak**
In additional it reduce number of allocation for ssl backend.

I'm not sure about this solution. This will make it more difficult next socket channel. Maybe it doesn't matter? I'm curious to hear your opinions.

### CODE REVIEW

**Comment by bagder** [comment]
The likeliness of there ever being another protocol using >1 connection I would say is very slim so we don't need to think about that.

I think the primary problem with this patch is the extreme #ifdef-maze it introduces. It makes the code much harder to read. I think it needs to be done with more "finesse".

**Comment by MAntoniak** [comment]
I originally wanted to reduce the amount of memory allocated. I extracted this work in #8471

**Comment by bagder** [comment]
With #8471 merged, I presume we can close this.

**Comment by MAntoniak** [comment]
Yes, thanks for pull #8471.

**Pull request closed without merging**
