### PR TITLE
ngtcp2: build with 0.16.0 and nghttp3 0.12.0

### PR DESCRIPTION
**Pull request by bagder**
- moved to qlog_write
- crypto => encryption
- CRYPTO => ENCRYPTION
- removed "_is_"

### CODE REVIEW

**Comment by bagder** [comment]
Needs a nghttp2 update as well, which has not been released yet.

**Comment by pheiduck** [comment]
nghttp2 **1.54.0** is published now.

**Comment by tatsuhiro-t** [comment]
Test failed with error  "curl: ngtcp2_conn.c:67: conn_update_timestamp: Assertion `conn->log.last_ts <= ts' failed.\n".

Starting ngtcp2 v0.16, we verify that timestamp an application passes to ngtcp2 library does not go back.  ngtcp2 entirely depends on that property.

The problem is, in cf_process_ingress, the timestamp is recorded in rctx.ts, and it is passed to ngtcp2_conn_read_pkt.
Inside the loop, cf_flush_egress is called, there we get fresh timestamp, and it could be larger than the value we recorded in rctx.ts.  Then next loop, ngtcp2_conn_read_pkt would cause assertion failure because rctx.ts points to back in time.

Perhaps, we need to pass rctx.ts to cf_flush_egress (or make it some internal sub-function that takes timestamp), so that the timestamp does not go back.

**Comment by icing** [comment]
> Test failed with error "curl: ngtcp2_conn.c:67: conn_update_timestamp: Assertion `conn->log.last_ts <= ts' failed.\n".
> 
> Starting ngtcp2 v0.16, we verify that timestamp an application passes to ngtcp2 library does not go back. ngtcp2 entirely depends on that property.
> 
> The problem is, in cf_process_ingress, the timestamp is recorded in rctx.ts, and it is passed to ngtcp2_conn_read_pkt. Inside the loop, cf_flush_egress is called, there we get fresh timestamp, and it could be larger than the value we recorded in rctx.ts. Then next loop, ngtcp2_conn_read_pkt would cause assertion failure because rctx.ts points to back in time.
> 
> Perhaps, we need to pass rctx.ts to cf_flush_egress (or make it some internal sub-function that takes timestamp), so that the timestamp does not go back.

That can certainly be done. I'll look into this, probably tomorrow.

**Pull request closed without merging**
