### PR TITLE
Check if IPv6 works during global init.

### PR DESCRIPTION
**Pull request by bprodoehl**
re #915.  I added it to the resolver init, since that's the only user of this.

### CODE REVIEW

**Comment by jay** [comment]
libcurl can be built with several different resolvers and each has its own `Curl_resolver_global_init`. You've addressed this for c-ares only. Rather than duplicate it for all resolvers I suggest you update this PR to instead call it once [right after the resolver global init is called](https://github.com/curl/curl/blob/curl-7_49_1/lib/easy.c#L269-L272).

**Comment by bprodoehl** [comment]
Thanks for the great feedback.  I updated the PR.

**Comment by jay** [comment]
Thanks, landed in c509808. You'll notice I made two modifications that may seem unnecessary.

I removed the guard, and that is because we have a Curl_ipv6works even when not IPv6 enabled, and although it doesn't do anything now (and I really don't anticipate in the future) it's best practice.

I cast it `(void)` since we're ignoring the return value, and that is because it's already done a number of places in the repo to let the compiler know we are explicitly ignoring a function's return value, which to me seems like noise but it's probably necessary to avoid a warning during static analysis.

**Comment by dfandrich** [comment]
This change seems to have caused test 558 to start failing. Presumably, all that's needed is to update the expected results with the new socket calls.

**Comment by jay** [comment]
are you sure about that number

**Comment by dfandrich** [comment]
Take a look at any of the red builds at https://curl.haxx.se/dev/builds.html (i.e. almost all of them), for example:

 test 0558...[libtest memory tracking operational]

goto problem 2
558: output (log/memdump) FAILED:
--- log/check-expected 2016-07-20 17:42:31.039365750 +0100
+++ log/check-generated 2016-07-20 17:42:31.039365750 +0100
@@ -1,3 +1,5 @@
+FD /curl/lib/hostip6.c: socket()[LF]
+FD /curl/lib/connect.c: sclose()[LF]
MEM lib558.c: malloc()[LF]
MEM lib558.c: free()[LF]
MEM escape.c: malloc()[LF]

**Comment by bagder** [comment]
Fixed now in commit c6d3fa11e6

**Comment by jay** [comment]
Thanks to the Daniels.

**Pull request closed without merging**
