### PR TITLE
binmode: convert to macro and use it from tests

### PR DESCRIPTION
**Pull request by vszakats**
And use it from src and tests.

Syncing this functionality between platforms and build targets.

Also: Stop redefining `O_BINARY` in src, and use a local macro with
the same effect. `O_BINARY` is used in `CURL_SET_BINMODE()` to decide
if this functionality is supported, and redefining it makes this check
pass always in unity builds. The check is required for Apple OS, because
it offers a `setmode()` function, successfully detected by both CMake
and autotools, but that function has a different functionality and
signature than that expected by `CURL_SET_BINMODE()`.

Also:
- drop MetaWare High C (MS-DOS) support for set binmode.
- tests/libtest/Makefile.inc: dedupe comments.
- lib/curl_setup_once.h: tidy up feature guards for `io.h`, `fcntl.h`.

Ref: #15652

### CODE REVIEW

**Comment by vszakats** [comment]
No, not used from libcurl itself, but from tests/servers, tests/libtest (and src).
There is curltool lib where this could be put, but that's only linked to tests/unit.
Seems more straighforward to distribute it via libcurl, which already linked at
the necessary places.

**Comment by bagder** [comment]
I agree that is indeed *practical* and probably the easiest way to do it, but I still believe it is the wrong approach. I think code in lib/ should only be for the library's own sake.

**Comment by vszakats** [comment]
Adding it to curltool and adding curltool as a dependency to everything
feels overkill for this tiny use.

Maybe converting this to a macro and offering it via the usual macro
ways (from lib but outside libcurl) could work? What do you think?

**Comment by bagder** [comment]
> Adding it to curltool and adding curltool as a dependency to everything feels overkill for this tiny use.

Yes, that also seems like the wrong thing to do.

> Maybe converting this to a macro and offering it via the usual macro ways (from lib but outside libcurl) could work? What do you think?

Less bad, but I am against adding stuff to lib/ that is not necessary for the library itself. Even if that means that the alternative might mean duplicated code or more work.

I would prefer to have a dedicated source file in the tool's source code directory or something that the test servers can use in their build as well.

**Comment by vszakats** [comment]
> I would prefer to have a dedicated source file in the tool's source code directory or something that the test servers can use in their build as well.

Converted to a macro and moved to `src/tool_setup.h`.

The seems fine given the simplicity of the macro.

I like the looks of it, but we can move it back out to a separate
`src/tool_binmode.h`, and include that where the macro is used.
Shall I do this?

**Comment by bagder** [comment]
> I like the looks of it, but we can move it back out to a separate
src/tool_binmode.h, and include that where the macro is used.
Shall I do this?

Yeah, I think that sounds like the cleanest approach.

> (edit: I think the builds will have to be updated to pick up headers
from src, either way.)

Yes, I believe we don't include anything from there before.

**Comment by vszakats** [comment]
OK, pushed!

While we're here, the set binmode macro now has the single mention
of `__HIGHC__` in the core code (with the other one present in
`curl/system.h`). Traces say it was an MS-DOS compiler. Its last
release was in the early 90s. [^1]

It's doubtful it'd compile curl, regardless of this guard.

Do we need it?

---

[^1]: https://winworldpc.com/product/metaware-high-c-cpp/2x

**Comment by bagder** [comment]
> Do we need it?

Nah.

**Pull request closed without merging**
