### PR TITLE
NTLM authentication fails when using proxy without username and password

### PR DESCRIPTION
**Pull request by ustcqidi**
try to fix the issue https://github.com/curl/curl/issues/5911

### CODE REVIEW

**Comment by bagder** [comment]
Except for the compiler warnings it seems reasonable:

~~~
url.c:2385:9: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  char *proxyuser = data->set.str[STRING_PROXYUSERNAME] ? data->set.str[STRING_PROXYUSERNAME] : "";
        ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
url.c:2386:9: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
  char *proxypasswd = data->set.str[STRING_PROXYPASSWORD] ? data->set.str[STRING_PROXYPASSWORD] : "";
        ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by ustcqidi** [comment]
> Except for the compiler warnings it seems reasonable:
> 
> ```
> url.c:2385:9: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
>   char *proxyuser = data->set.str[STRING_PROXYUSERNAME] ? data->set.str[STRING_PROXYUSERNAME] : "";
>         ^           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> url.c:2386:9: error: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Werror,-Wincompatible-pointer-types-discards-qualifiers]
>   char *proxypasswd = data->set.str[STRING_PROXYPASSWORD] ? data->set.str[STRING_PROXYPASSWORD] : "";
>         ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

@bagder  thanks for your review, I have updated the patch.  Could you please help to review it again? Many thanks.

**Comment by bagder** [comment]
The CI builds still complain:
~~~
./url.c:2385:106: warning: Longer than 79 columns (LONGLINE)
   const char *proxyuser = data->set.str[STRING_PROXYUSERNAME] ? data->set.str[STRING_PROXYUSERNAME] : "";
./url.c:2386:108: warning: Longer than 79 columns (LONGLINE)
   const char *proxypasswd = data->set.str[STRING_PROXYPASSWORD] ? data->set.str[STRING_PROXYPASSWORD] : "";
checksrc: 0 errors and 2 warnings

**Comment by ustcqidi** [comment]
fixed the warning and verify with checksrc.bat. thanks @bagder

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
