### PR TITLE
build: drop unused `NROFF` reference

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by bagder** [comment]
`src/Makefile.mk` seems to have some NROFF leftovers as well

**Comment by vszakats** [comment]
> `src/Makefile.mk` seems to have some NROFF leftovers as well

Yep, seen them! I'll open a PR, lightly tested.

I wonder if anyone is using `Makefile.mk`? It's for MS-DOS and Amiga, are those covered by `./.configure` (or CMake)?

**Comment by bagder** [comment]
> I wonder if anyone is using Makefile.mk? It's for MS-DOS and Amiga, are those covered by ./.configure (or CMake)?

We don't have any CI jobs that use them. We have no real way of knowing if anyone uses them.

**Comment by vszakats** [comment]
Updated `Makefile.mk` in #14813.

**Pull request closed without merging**
