### PR TITLE
Add the option of specifying * as host for --resolve

### PR DESCRIPTION
**Pull request by claesjac**
The attached patch adds support for wildcard host (any) in CURLOPT_RESOLVE (--resolve). If specified any host not matched by another CURLOPT_RESOLVE config will use this as fallback.

Example send a.com to 10.0.0.1 and everything else to 10.0.0.2: curl --resolve *:443:10.0.0.2 --resolve a.com:443:10.0.0.1 https://a.com https://b.com

This is probably quite similar to using --connect-to a.com:443:10.0.0.1:443 --connect-to :443:10.0.0.2:443

### CODE REVIEW

**Comment by bagder** [comment]
This looks promising! I recommend you run `make checksrc` and fix some nits:
```
/usr/bin/perl ./checksrc.pl -D. -W./curl_config.h      \
	./*.[ch] ./vauth/*.[ch] ./vtls/*.[ch]
./hostip.c:303:2: warning: Trailing whitespace (TRAILINGSPACE)
   
  ^
./hostip.c:312:2: warning: Trailing whitespace (TRAILINGSPACE)
   
  ^
./hostip.c:316:2: warning: Trailing whitespace (TRAILINGSPACE)
   
  ^
./hostip.c:803:2: warning: Trailing whitespace (TRAILINGSPACE)
   
  ^
./hostip.c:916:9: warning: if with space (SPACEBEFOREPAREN)
       if (hostname[0] == '*' && hostname[1] == '\0') {
         ^
./hostip.c:917:94: warning: Longer than 79 columns (LONGLINE)
         infof(data, "RESOLVE %s:%d is wildcard, enabling wildcard checks\n", hostname, port);
```

**Comment by claesjac** [comment]
Fixed formatting issues reported by make checksrc

**Comment by bagder** [comment]
It seems someone else nicked that test number in the mean time. Can you update this to use another one in preparation for a merge in the next feature window?

**Comment by bagder** [comment]
This PR still conflicts. Can you please rebase the set and force-push?

**Comment by bagder** [comment]
You might as well squash them all too? ping @claesjac

**Comment by danielgustafsson** [comment]
This is being replaced by #3406 in an effort to try and get this in.

**Pull request closed without merging**
