### PR TITLE
Win32: enable IPv6 and LDAPS for non-configure builds

### PR DESCRIPTION
**Pull request by MarcelRaad**
As done by default in the autotools and CMake builds.

IPv6 is enabled for Winsock2 when targeting Windows XP or later, which introduced stable IPv6 support. Only when `HAVE_GETADDRINFO` is defined to avoid a linker error as `Curl_ipv4_resolve_r` is used but undefined otherwise.

LDAPS is enabled unconditionally when using WinLDAP.

### CODE REVIEW

**Comment by jay** [comment]
IPv6 is supposed to be enabled by USE_IPV6 so isn't the real issue that those projects should do it by default? IIRC Visual Studio 2010 or later we know the default SDKs include IPv6 so what if I add that define to those project files?

**Comment by MarcelRaad** [comment]
Yes, for Visual Studio 2010 and later it's safe to define it as the minimum target Windows version is XP. However, IIRC it's also supported in much older Visual Studio versions (at least 2005) as long as the target Windows version is at least XP. Maybe add it to the 2008+ projects and see what AppVeyor says - if one patches the project to target Windows 2000, they can surely also remove that define.

The reason I put it there was that it looked like config-win32.h seems to support many more build environments than Visual Studio. I thought there were at least non-configure MinGW makefiles, but it seems they have been removed? But then there would be no way to disable it except patching config-win32.h if we don't introduce a macro for that. Adding it to the Visual Studio projects would definitely be the more backward compatible way.

**Comment by jay** [comment]
AppVeyor uses cmake so I don't think it applies. winbuild/ the makefile already uses USE_IPV6 and I tried with VS2008 and it builds fine (as long as IDN is disabled). The pre-generated project files in projects/ I added USE_IPV6 to the VS2008 project and it builds fine. I am using VS2008 SP1 though I don't know about when SP1 isn't applied.

**Comment by MarcelRaad** [comment]
Oh, of course, then AppVeyor is already using IPv6. Thanks for confirming! I'll add it to the project files instead then.

**Comment by MarcelRaad** [comment]
Replaced the commit enabling IPv6 via config-win32.h by one adding `USE_IPV6` to all Visual Studio libcurl project files since Visual Studio 2008.

**Comment by jay** [comment]
Ok LGTM

**Comment by MarcelRaad** [comment]
Thanks!

**Pull request closed without merging**
