### PR TITLE
Some more work on conn->data

### PR DESCRIPTION
**Pull request by monnerat**
Starting now with nss.
Passes tests locally (without valgrind).
I'll carry on with other TLS backends.

### CODE REVIEW

**Comment by bagder** [comment]
Sorry, I rebased #6425 due to me landing #6443 in between and it caused you some issues here. :disappointed:

**Comment by monnerat** [comment]
> Sorry, I rebased #6425 due to me landing #6443 in between and it caused you some issues here

Rebased my commits on my side now and they still pass local tests.

Please note the openssl trace case I do not know how to resolve.

**Comment by bagder** [comment]
> Please note the openssl trace case I do not know how to resolve.

You write that it is called asynchronously, but that's not strictly true. It's a callback from OpenSSL so it only get gets called when we call openssl to perform TLS operations.

The challenge is of course that this tls trace setup function is called when we setup a connection and that connection can then be reused later by other easy handles than the one that created it.

I think we need to always set the callback pointer pointer (to pass on `data`) before we use OpenSSL functions. So that if we use a TLS connection in a multiplexed manner, the particular transfer that happens to operate on the connection when the callback is called gets the trace.

**Comment by bagder** [comment]
We can attack that OpenSSL detail once we've landed the initial rework.

**Comment by monnerat** [comment]
> You write that it is called asynchronously, but that's not strictly true.

Right, "asynchronously" is not the appropriate word.

> I think we need to always set the callback pointer pointer (to pass on data) before we use OpenSSL functions.

This is a bit cumbersome, but probably the good idea. Thanks for the hint.

**Comment by bagder** [comment]
I rebased #6425 again (due to merge conflicts) and squashed it into a single commit, I just couldn't manage to keep the commits separate sensibly.

**Comment by monnerat** [comment]
Except for the openssl trace case, the vtls subdirectory is free of conn->data references with commit df530eb.
This lower the overall reference count to 355.
TLS backends gskit, schannel, mesalink and sectransp have not been tested, because I do not have OS support for them. Perhaps deeper CI tests will help me here ?
Maybe you can review/pull it before I restart on another part ? Or would you prefer I merge all these commits into a single one ?

**Comment by bagder** [comment]
I just merged #6425, so please rebase this against master and I'll give it a proper review and then aim to merge.

The schannel, mesalink and sectransp backends are all tested in the CI builds at least so they should be fairly safe. For gskit we pretty much have to change it "blindly" and hope for the best, as I doubt we can expect any gskit hackers to just show up anytime soon.

**Comment by monnerat** [comment]
Will issue a PR against master. Closing this one.

**Pull request closed without merging**
