### PR TITLE
housekeeping: Add housekeeping for connections

### PR DESCRIPTION
**Pull request by maxdymond**
Add functionality so that protocols can do custom keepalive on their connections, when an external API function is called.
-------------------------------
I'm not expecting this pull request to make it in as is - I've created this to discuss the direction going forward.

### CODE REVIEW

**Comment by bagder** [comment]
Some thoughts so far:

- consider a function for the multi API too that accepts a `CURLM *` handle
- I would like to see this "housekeeping" done automatically also while a multi handle is in use, for when there are idle connections in the cache to keep alive
- I would prefer the name of the function to hint about it being about connections or the connection cache rather than "housekeeping"
- the travis error happens because you have to add new functions at the bottom of the header file for some particular platforms' sake 
- an option to set the keep-alive interval time, and I would imagine there could also be a time for a maximum time to keep an unused connection alive 
- docs
- future expansion: the ping-pong protocols could actually do NOOP commands or similar to achieve a similar effect

**Comment by cmeister2** [comment]
Naming: "curl_conn_upkeep" has been discussed on IRC and could be a good option.

**Comment by vpeter4** [comment]
I have added a function for the multi API and have it running. Also setting for keep-alive interval time. Thanks to this work by @maxdymond.

@bagder: Can you explain little more your second point above? How would this work? When calling some other multi functions this keep-alive would be automatically called or what?

**Comment by cmeister2** [comment]
@vpeter4: I seem to have lost your patch; any chance you could link it here please? 😄

**Comment by cmeister2** [comment]
@vpeter4 Perfect, thanks!

**Comment by maxdymond** [comment]
I freshened this pull request.

@bagder: regarding your comments:

- consider a function for the multi API too that accepts a CURLM * handle
- I would like to see this "housekeeping" done automatically also while a multi handle is in use, for when there are idle connections in the cache to keep alive
  - **I would like to do these, but looking at the curl multi code, I haven't the faintest idea where I'd add such code in in a safe manner. Any thoughts? Otherwise, I'd prefer it if we could defer this feature request to a later date?**
- I would prefer the name of the function to hint about it being about connections or the connection cache rather than "housekeeping"
  - **Now refers to "connection upkeep".**
- the travis error happens because you have to add new functions at the bottom of the header file for some particular platforms' sake
  - **Hopefully fixed in the latest commit**
- an option to set the keep-alive interval time, and I would imagine there could also be a time for a maximum time to keep an unused connection alive
  - **Added an option to set the interval time from @vpeter4's code.**
- docs
  - **Can you possibly go into more detail here? I think this needs docs for the new API functions and new CURLOPT value - anything else? An example?**
- future expansion: the ping-pong protocols could actually do NOOP commands or similar to achieve a similar effect

**Comment by bagder** [comment]
> I'd prefer it if we could defer this feature request to a later date?

Sure, I have no problems with taking baby steps. We can take that on in a follow-up work.

> **docs**
> Can you possibly go into more detail here? I think this needs docs for the new API functions and new CURLOPT value - anything else? An example?

I was primarily thinking of the mandatory pieces: a man page for the function and setopt that describes what they do and why someone would want to use them, and these man pages should ideally include at least a small example snippets (as all our man pages should).

Of course I would consider a separate example code for docs/examples/ a great addition as well. Supposedly we would add at least one test case for this feature anyone so code has to be written that uses it, which then could be the basis for an example... The example doesn't *have to* be included in the original PR either, we can work on that separately after the feature lands.

**Comment by cmeister2** [comment]
🎉

**Comment by cmeister2** [comment]
Docs updated for 7.62.0.

**Comment by cmeister2** [comment]
Rebased for 7.62.0. I set the dates as 31/Oct as I believe that's the correct date!

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
