### PR TITLE
[CMakeLists.txt] Set reasonable default for macOS brew-installed OpenSSL…

### PR DESCRIPTION
**Pull request by SamuelMarks**
…also set `CMAKE_C_STANDARD`

Bit of a hack, but it works and guards effectively

### CODE REVIEW

**Comment by jzakrzewski** [comment]
I cannot really comment on the path as I am totally ignorant of Macs and everything around but:
1. Since you set CMAKE_C_STANDARD, shouldn't you also set CMAKE_C_EXTENSIONS to OFF (cc @bagder - curl doesn't rely on special compiler extensions, right?)
2. Is the CMAKE_C_STANDARD change required for this to work? If not I don't think the changes should be in one commit.

**Comment by SamuelMarks** [comment]
No worries I'll move that into its own commit. I think setting the standard sets the minimum needed for this project, other people relying on C11 can including libcurl and it'll use C11 for whole process (if static).

Do you want that new PR with that one line change?

**Comment by bagder** [comment]
What exactly does setting `CMAKE_C_STANDARD` mean? What impact will it have? #5017 might be merged soon, which can go beyond C89/90 if available...

**Comment by bagder** [comment]
Regarding the `OPENSSL_ROOT_DIR` change: we don't change the default dir for any other setup plus that we often document and refer to the default OpenSSL install dir and this will change that. Not sure it matters nor how much this modified default will help anyone...  Is there a risk this will change a default that some users might rely on?

**Comment by jzakrzewski** [comment]
> What exactly does setting `CMAKE_C_STANDARD` mean? What impact will it have? #5017 might be merged soon, which can go beyond C89/90 if available...

It basically adds a flag to the compiler cmdline, like ```--std=c90``` (or however the right flag for the particular compiler looks like).

**Comment by bagder** [comment]
> adds a flag to the compiler cmdline, like --std=c90

Doing that *by default* is going to cause problems and headaches. People build libcurl with lots of different 3rd party dependencies and far from all of them are C90 "clean". Setting such an option will make it harder to build curl when for example using include files from such projects. That's why the configure builds never set such options unless a "debug option" is used.

**Comment by jay** [comment]
> Bit of a hack, but it works and guards effectively

Explain

**Comment by SamuelMarks** [comment]
@jay So anyone who installs openssl on macOS using brew, it will default to using this installation.

@bagder No, I don't think it'll adversely effect anyones build pipeline. This is only if `OPENSSL_ROOT_DIR` isn't defined this sets a reasonable default, and even then, only on macOS and iff the directory exists. Could probably go a little further and look for common other locations of the `OPENSSL_ROOT_DIR`, or alternatively look to contribute this to cmake itself rather than libcurl, e.g., a PR to https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindOpenSSL.cmake

Wait, does that referenced issue mean libcurl is moving from C89 to C11?

**Comment by jay** [comment]
Is there a reason why brew has this problem, is it something to do with brew, why should we hack around it? Also I echo what everyone has said CMAKE_C_STANDARD seems unnecessary.

/cc @vszakats

**Comment by vszakats** [comment]
Defaulting to brew-specific locations is by itself okay, but then comes the question: Why specifically OpenSSL, and not any other of the dependencies that don't come with macOS by default (or come in an obsolete or not-preferred version). So, while this may be useful to have one less build setting to worry about on macOS, I'd go for consistency.

Regarding `CMAKE_C_STANDARD`, I don't believe this is something Homebrew needs, at least by skimming though the [latest](https://github.com/Homebrew/homebrew-core/blob/5ac352701847ad210a3134ebb02b423ed844c460/Formula/curl.rb) [curl](https://github.com/Homebrew/homebrew-core/blob/5ac352701847ad210a3134ebb02b423ed844c460/Formula/curl-openssl.rb) formulae, and according to memories building curl manually against Homebrew components.

Enabling this option may not play well with dependencies built without it or built with a different `--std=` value. I'd vote to leave it as-is.

**Comment by bagder** [comment]
> No, I don't think it'll adversely effect anyones build pipeline

Not even if they rely on the previously used default path? 

> Wait, does that referenced issue mean libcurl is moving from C89 to C11?

No it doesn't. I means that if _Atomic works, curl might use it.

**Comment by bagder** [comment]
I think I'm mostly against changing the default OpenSSL path because we document and keep saying what the OpenSSL default path is and then for this particular build setup it will not be that path. I'm a little scared that this will come back and bite us somehow.

**Comment by Lekensteyn** [comment]
I would be in favor of not setting this in the CMake script. It bypasses other mechanisms such as pkg-config. `OPENSSL_ROOT_DIR` is supposed to be set by the user.

See also this hint when you install `openssl` 1.1.1g through Homebrew:
```
openssl@1.1 is keg-only, which means it was not symlinked into /usr/local,
because macOS provides LibreSSL.

If you need to have openssl@1.1 first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"' >> /Users/pwu/.bash_profile

For compilers to find openssl@1.1 you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"

For pkg-config to find openssl@1.1 you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

**Comment by bagder** [comment]
I see very little (none at all) support for this PR among the comments.

**Comment by SamuelMarks** [comment]
In that case I'll have to close… I suppose

**Pull request closed without merging**
