### PR TITLE
configure.ac: better use of pkg-config for gssapi, with krb5-config as a fallback

### PR DESCRIPTION
**Pull request by asedeno**
This reverts commit 6fe4e7d3bfc1520da032ea067b4712cc1357f016.

As per #8289, this breaks builds for folks with custom MIT Kerberos installation paths.

### CODE REVIEW

**Comment by bagder** [comment]
I don't think a straight out revert is the correct fix. I believe the intention in 6fe4e7d3bfc1520da0 was to use the pkg-config file if it is indeed installed in the custom path, and I still think that seems reasonable. If that isn't present there, then a fallback to the `krb5-config` tool seems totally reasonable.

**Comment by asedeno** [comment]
I agree that perhaps being more clever is a good idea, but that can be done separately from fixing the builds that were broken by the change while that fix is figured out.

**Comment by bagder** [comment]
We originally had bug A that was fixed with a commit that introduced bug B. You seem to be suggesting we should immediately reintroduce bug A because of B.

Instead of doing a back-and-forth dance, I think fixing this *proper* is a better idea and I think we are better off not doing a plain revert because if we do, everyone who now suffers from B will just go away and happily leave bug A because they don't suffer from it. I've seen that happen many times.

**Comment by asedeno** [comment]
We had a bug that inconvenienced one person's build system, and fixed that with a bug that broke other people's build systems. There's a severity to be considered.

That said, I have tried to generate a `configure` file from `configure.ac` using autoconf (versions 2.69 and 2.71, both via debian), and I can't get what is in the release bundle. If you can get me explicit instructions, including dependencies, on how to generate the configure that I find in, say, curl 7.81.0, I will try to make a patch that works for everyone.

**Comment by asedeno** [comment]
I believe this will work for everyone involved, and as a bonus, eliminates the debugging that went into figuring out and filing #8289 by trying to link gssapi early.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
