### PR TITLE
github workflow: Add ios/watchos/tvos builds

### PR DESCRIPTION
**Pull request by manuyavuz**

### CODE REVIEW

**Review by fossdd — APPROVED** [review]

**Comment by bagder** [comment]
Clearly something is missing here..

**Comment by manuyavuz** [comment]
Himm, the exact scenario is working on my local. I will try to debug on CI.

**Comment by manuyavuz** [comment]
@bagder I think it should be working now.

https://github.com/curl/curl/runs/2316471458?check_suite_focus=true#step:6:77

There is a build failure for `appletvos 13.0` above as a deprecated method is being used in curl. You would know better how we should proceed. If needed, we can disable `-Werror` for `-Wdeprecated-declarations` on non-macosx platforms.

**Comment by manuyavuz** [comment]
Also, there is a different behavior for macosx builds when `-isysroot` is explicitly set or not.

- If you do not set `-isysroot` explicitly, default compiler include paths include `/usr/local/include` which is used by homebrew installed libraries such as `libssh2`.
- If you do set `-isysroot` explicitly, compiler include paths not does NOT include `/usr/local/include`, causing `configure` to fail as `libssh2` could not be found.

We could either NOT set `-isysroot` for macosx builds, or explicitly add `-I/usr/local/include` as header search path. @bagder  up to you.

**Comment by bagder** [comment]
> There is a build failure for appletvos 13.0 above as a deprecated method is being used in curl. You would know better how we should proceed. If needed, we can disable -Werror for -Wdeprecated-declarations on non-macosx platforms.

It complains on MD4 and MD5 which curl uses for legacy protocols. I find it curious that it only complains on some specific platforms as the algorithms functions are equally bad on all of them. I presume there's no way for us to specifically mark these functions as "vetted and deemed okay for our purposes" ?

> We could either NOT set -isysroot for macosx builds, or explicitly add -I/usr/local/include as header search path.

But we're not setting `-isysroot` now, do we? It seems wrong to set `-I/usr/local/include` without anyone asking for it.

**Comment by manuyavuz** [comment]
Ok, I see that there is a deployment target check for macosx 10.15 in `md4.c`, which should be disabling the use of native functions and use curl implemented ones. I think that's why it does not give errors when we build for macosx with 10.15 as deployment target.

The deployment target check has been added in this commit: https://github.com/curl/curl/commit/2998749850f88d83d2ce291bc8f0a8b5e33e9599

I have added the same check for ios platform (it's also deprecated in ios 13.0), which should fix the issue (we might need to add appletvos version too.)


> But we're not setting -isysroot now, do we? It seems wrong to set -I/usr/local/include without anyone asking for it.

I used `-isysroot` for macosx too in CI to have a common script for all platforms. I can discard that in CI. However, users trying to build curl with libraries from homebrew and use `-isysroot` for convenience will still have the build error, which might cause future unnecessary bug reports. Adding `-isysroot` flag or `SDKROOT=` environment variable (which is automatically done by `xcrun -sdk macosx ${command}` is Apple's suggested way of building things for platforms. That's why I'm a bit concerned. It's your call.

**Comment by manuyavuz** [comment]
@MarcelRaad , I see that you have used `__MAC_OS_X_VERSION_MIN_ALLOWED` to check deployment target, but I don't see it defined anywhere. The standard macro for that should be `__MAC_OS_X_VERSION_MIN_REQUIRED`. Can you refer me why you have used the former one?

**Comment by bagder** [comment]
> I used -isysroot for macosx too in CI to have a common script for all platforms. I can discard that in CI.

I'm confused. I thought we were talking about the default configure script and not the CI builds. The CI builds can use whatever they need to get the builds going I think.

> However, users trying to build curl with libraries from homebrew and use -isysroot for convenience will still have the build error, which might cause future unnecessary bug reports.

But that's then the user's choice and actions that take them there. If we don't make that decision, the users can decide for themselves which way they think is the best and works for them.

If libssh2, or any other library you can make a curl build to use, is put in `/usr/local/lib` and the user wants the configure script to find it, the user needs to make sure the system is setup and configure is invoked to make sure it is detected there correctly. We should not assume that's a directory to check.

> Adding -isysroot flag or SDKROOT= environment variable (which is automatically done by xcrun -sdk macosx ${command} is Apple's suggested way of building things for platforms.

So if this flag is used, then the user just have to specify that the libraries they want are installed with a `/usr/local` prefix right? Isn't that how we already tell users they should invoke configure?

**Comment by manuyavuz** [comment]
> 
> I'm confused. I thought we were talking about the default configure script and not the CI builds. The CI builds can use whatever they need to get the builds going I think.

Default configure script does not add anything, so `/usr/local/include` is in header search paths with default configure script.
Ok, I can arrange CI configurations accordingly.

> But that's then the user's choice and actions that take them there. If we don't make that decision, the users can decide for themselves which way they think is the best and works for them.
> 
> If libssh2, or any other library you can make a curl build to use, is put in `/usr/local/lib` and the user wants the configure script to find it, the user needs to make sure the system is setup and configure is invoked to make sure it is detected there correctly. We should not assume that's a directory to check.

Sounds good.

> > Adding -isysroot flag or SDKROOT= environment variable (which is automatically done by xcrun -sdk macosx ${command} is Apple's suggested way of building things for platforms.
> 
> So if this flag is used, then the user just have to specify that the libraries they want are installed with a `/usr/local` prefix right? Isn't that how we already tell users they should invoke configure?

Actually yes, they should run sth like this when it happens as suggested in `UNIX` section of `INSTALL.md`:
```
export SDK=macosx
export DEPLOYMENT_TARGET=10.8
export CFLAGS="--isysroot $(xcrun -sdk $SDK --show-sdk-path) -m$SDK-version-min=$DEPLOYMENT_TARGET"
# Set CPPFLAGS AND LDFLAGS as needed
CPPFLAGS="-I/usr/local/include" LDFLAGS="-L/usr/local/lib" ./configure --with-libssh2
make -j8
make install
```

**Comment by MarcelRaad** [comment]
> @MarcelRaad , I see that you have used __MAC_OS_X_VERSION_MIN_ALLOWED to check deployment target, but I don't see it defined anywhere. The standard macro for that should be __MAC_OS_X_VERSION_MIN_REQUIRED. Can you refer me why you have used the former one?

I can't remember, sorry. I'm actually not a Mac guy, so it *might* not even be on purpose.

**Comment by bagder** [comment]
@manuyavuz the macos libssh2 job needs the path set in the configure line now, right? `--with-libssh2=/usr/local`  or where is it installed?

**Comment by bagder** [comment]
There's also a merge conflict now

**Comment by bagder** [comment]
No development, closing.

**Comment by manuyavuz** [comment]
@bagder hi, sorry I had lost all my free time for a very long time, and this got stuck here. I will update the PR if I find some time in future.

Thanks for the help!

**Pull request closed without merging**
