### PR TITLE
CMake: CMake config files are defining CURL_STATICLIB for static builds

### LINKED ISSUE #2817: Generated CMake config files do not define `CURL_STATIC` for static builds
I am building Curl 7.61.0 using the CMake files, and I see it is now generating config files (CMake/curl-config.cmake) when installed. Big thanks for adding this feature to your CMake code !

Up to now, we where using a custom FindCurl.cmake module, that was detecting when the library was statically compiled, and when it was the case, was defining `CURL_STATICLIB` as an `INTERFACE_COMPILE_DEFINITIONS` of the imported curl target, with this code:

```
set_target_properties(CURL::libcurl PROPERTIES
    INTERFACE_COMPILE_DEFINITIONS
	CURL_STATICLIB
)
```

Looking through the config files generated during install, this symbol is never defined on the imported static target, thus this target make downstream build fail at link time.

### PR DESCRIPTION
**Pull request by Adnn**
This change allows to use the CMake config files generated by Curl's
CMake scripts for static builds of the library.
The symbol CURL_STATIC lib must be defined to compile downstream,
thus the config package is the perfect place to do so.

Fixes #2817
Reported-by: adnn

### CODE REVIEW

**Comment by MarcelRaad** [comment]
The Travis failures were caused by download failures, I've restarted the jobs.

This looks generally good to me, but shouldn't the condition for library users defining `CURL_STATICLIB` match the condition used by the library itself [here](https://github.com/Adnn/curl/blob/633c055cd9e6afec1b3a19e3cb4f6fdcbdd24404/lib/Makefile.am#L113)?

**Comment by Adnn** [comment]
@MarcelRaad Thank you for your review and restarting the job (is the failed result above the first attempt, or did the restart also fail?)

I am not sure to understand what is your suggestion? Sadly, I am not familiar with this build system, but I think you are referring to an Automake file, and it seems unlikely that CMake share the same variables?

Anyway, the CMake variable allowing the user to request a static build is indeed `CURL_STATICLIB`, defined [here](https://github.com/Adnn/curl/blob/master/CMakeLists.txt#L79). And it is already used by the CMake logic as the condition to determine if it is a static build ([example here](https://github.com/Adnn/curl/blob/master/lib/CMakeLists.txt#L62)).

Do you have an alternative in mind?

**Comment by MarcelRaad** [comment]
The Travis failure is from the restarted build, but looks unrelated.

Sorry, you're right, `Makefile.am` is not used by the CMake build (`Makefile.inc` is at least partially).

What I was looking for is where `CURL_STATICLIB` is added to the preprocessor definitions when building libcurl itself. And it seems the answer is "never" according to https://github.com/Adnn/curl/blob/633c055cd9e6afec1b3a19e3cb4f6fdcbdd24404/CMakeLists.txt#L1250? I'm totally consued now, sorry.

**Comment by bagder** [comment]
The failed travis build is the mysterious new mac fail due some weirdo SecureTransport thing that started showing up recently! =(

@nickzman can you figure out why [this happens](https://travis-ci.org/curl/curl/jobs/410782959#L2430) now on travis? It looks like it doesn't happen every time which is even worse...

**Comment by jzakrzewski** [comment]
@MarcelRaad The CURL_STATICLIB define sits here: https://github.com/Adnn/curl/blob/master/lib/curl_config.h.cmake#L80 . If the CURL_STATICLIB CMake option is set, this line https://github.com/Adnn/curl/blob/master/lib/CMakeLists.txt#L3 will bring it to life ;)

**Comment by snikulov** [comment]
As @jzakrzewski already mentioned, CURL_STATICLIB will be set through curl_config.h and not through compiler command line.

Latest master (ref #2755) slightly changed behavior to control build static/shared by using 
`cmake .. -DBUILD_SHARED_LIBS=OFF/ON`

Resulting curl_config.h will be 

```
╭─snikulov@snikulov-lin ~/work/github/curl/build.static  ‹master*›
╰─$ diff lib/curl_config.h ../build.shared/lib/curl_config.h                                                                                         130 ↵
80c80
< #define CURL_STATICLIB 1
---
> /* #undef CURL_STATICLIB */
╭─snikulov@snikulov-lin ~/work/github/curl/build.static  ‹master*›

```

@Adnn should we close this or you have objections?

**Comment by MarcelRaad** [comment]
But curl_config.h is not meant for inclusion by users of libcurl, or is it? If I understood correctly, `INTERFACE_COMPILE_DEFINITIONS` sets `CURL_STATICLIB` only for users of the library, not for building libcurl itself.

**Comment by Adnn** [comment]
@snikulov I am not sure to follow, do you propose to discard the PR?

@MarcelRaad You are right about the `INTERFACE_xxx` properties of CMake: they will be propagated to downstreams (consumers of the target), but will not define it for the target itself. So the point you are making seems to be the good one: if `curl_config.h` is not intended to be included by the clients, then it will of course not help in defining the required symbols for the client. In which case, the CMake package config remains a very good place to define it imo.

**Comment by snikulov** [comment]
@Adnn @MarcelRaad now I see what you mean.
Imported target contains CURL_STATIC definition after this PR. 
This definetely useful addition!

```
╰─$ diff -u /home/snikulov/work/github/curl/install.shared/lib/cmake/curl/libcurl-target.cmake /home/snikulov/work/github/curl/install.static/lib/cmake/curl/libcurl-target.cmake
--- /home/snikulov/work/github/curl/install.shared/lib/cmake/curl/libcurl-target.cmake  2018-08-08 12:49:56.000000000 +0300
+++ /home/snikulov/work/github/curl/install.static/lib/cmake/curl/libcurl-target.cmake  2018-08-08 12:52:04.000000000 +0300
@@ -51,9 +51,10 @@
 endif()

 # Create imported target CURL::libcurl
-add_library(CURL::libcurl SHARED IMPORTED)
+add_library(CURL::libcurl STATIC IMPORTED)

 set_target_properties(CURL::libcurl PROPERTIES
+  INTERFACE_COMPILE_DEFINITIONS "CURL_STATICLIB"
   INTERFACE_INCLUDE_DIRECTORIES "${_IMPORT_PREFIX}/include"
   INTERFACE_LINK_LIBRARIES "lber;ldap;dl;-lpthread;OpenSSL::SSL;OpenSSL::Crypto;/usr/lib64/libz.so"
 )
```

**Comment by bagder** [comment]
@snikulov should I take that as a :+1: from you on merging this?

**Comment by snikulov** [comment]
@bagder not exactly. 
I have a proposal regarding the variable usage.
Since we agreed to use the standard BUILD_SHARED_LIBS option to control shared/static build with the previous PR (#2755), perhaps it is better to use these option in condition.
Awaits for @Adnn and @MarcelRaad comments or agreement.

**Comment by Adnn** [comment]
Hi,

**Comment by snikulov** [comment]
@Adnn I see no cases where `BUILD_SHARED_LIBS` will be different with the TYPE property for libcurl target. IMO, value from option should be enough.

**Comment by Adnn** [comment]
@snikulov Thank you for your feedback. It should not be different, but it could be more future-proof. Any reason for avoiding `TYPE` though?

**Comment by snikulov** [comment]
@Adnn another reason - less code.

**Comment by snikulov** [comment]
@bagder could you please merge it? Thank you.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
