### PR TITLE
configure: resolve conflict with AC_CHECK_HEADERS

### PR DESCRIPTION
**Pull request by Irfy**
AC_CHECK_HEADERS produces `ac_cv_header_*_h' cache variables, which
conflict with curl-specific header check for windows.h. By renaming the
variable used by curl, any conflict with other projects and shared
config.caches is resolved. The conflict occurs under CYGWIN, as
AC_CHECK_HEADERS (from a different project) will set
ac_cv_header_windows_h=1, while the expected value for curl is 0.

### CODE REVIEW

**Comment by Irfy** [comment]
According to [autoconf docs](https://www.gnu.org/software/autoconf/manual/autoconf-2.68/html_node/Cache-Variable-Names.html) curl ought to use the `curl_cv_*` prefix for variables not directly created by AC_* macros.

There are 16 such variables, and an alternative to this patch would be to rename them *all* to `curl_cv_*`.

**Comment by bagder** [comment]
Yes, I think they all should be renamed to use the `curl_cv_` prefix. You think you can update the patch to do that? Will that change fix #603 ?

**Comment by Irfy** [comment]
I agree that fixing them all is the Right thing to do.

On second analysis, there are 107 `ac_cv_*` variables and 281 references in
curl's configure.ac and m4 files combined, just so you know the diff will
be big. It's likely that some of those are proper `ac_cv_*` variable
references, but most will likely be curl-specific, I'll look into it later
today.

**Comment by Irfy** [comment]
And yes, this fix would fix #603 and any other similar conflict.

**Comment by Irfy** [comment]
The following 71 `ac_cv_*` variables are modified in curl `m4` macros, which makes them candidates for renaming, but they are never used within `AC_CACHE_CHECK`, which makes the `_cv_` part of their name meaningless (they are cached but the cached values are never taken into account). They should either be renamed to `curl_*` and left at that, or to `curl_cv_*` with appropriately added `AC_CACHE_CHECK` checks. Since checking them with `AC_CACHE_CHECK` is preferable,  I'm going to rename them to `curl_cv_*` and leave the `AC_CACHE_CHECK` addition for someone else / some later time.

Note that some of the variables, like the #603's `ac_cv_func_gethostbyname` is not going to be trivial to cache, as each level of checking (i.e. -lnsl, -lsocket, -lwatt, ...) would require a separate variable for each of the various library checks. Best would be to cache the actual result "what needs to be included in LIBS for gethostbyname" -- but all this is a separate issue.

ac_cv_func_alarm
ac_cv_func_basename
ac_cv_func_clock_gettime
ac_cv_func_closesocket
ac_cv_func_closesocket_camel
ac_cv_func_connect
ac_cv_func_fcntl
ac_cv_func_fcntl_o_nonblock
ac_cv_func_fdopen
ac_cv_func_fgetxattr
ac_cv_func_flistxattr
ac_cv_func_freeaddrinfo
ac_cv_func_freeifaddrs
ac_cv_func_fremovexattr
ac_cv_func_fsetxattr
ac_cv_func_ftruncate
ac_cv_func_gai_strerror
ac_cv_func_getaddrinfo
ac_cv_func_getaddrinfo_threadsafe
ac_cv_func_gethostbyaddr
ac_cv_func_gethostbyaddr_r
ac_cv_func_gethostbyname
ac_cv_func_gethostbyname_r
ac_cv_func_gethostname
ac_cv_func_getifaddrs
ac_cv_func_getnameinfo
ac_cv_func_getservbyport_r
ac_cv_func_getxattr
ac_cv_func_gmtime_r
ac_cv_func_inet_ntoa_r
ac_cv_func_inet_ntop
ac_cv_func_inet_pton
ac_cv_func_ioctl
ac_cv_func_ioctl_fionbio
ac_cv_func_ioctl_siocgifaddr
ac_cv_func_ioctlsocket
ac_cv_func_ioctlsocket_camel
ac_cv_func_ioctlsocket_camel_fionbio
ac_cv_func_ioctlsocket_fionbio
ac_cv_func_listxattr
ac_cv_func_localtime_r
ac_cv_func_memrchr
ac_cv_func_pipe
ac_cv_func_poll
ac_cv_func_recv
ac_cv_func_removexattr
ac_cv_func_select
ac_cv_func_send
ac_cv_func_setsockopt
ac_cv_func_setsockopt_so_nonblock
ac_cv_func_setxattr
ac_cv_func_sigaction
ac_cv_func_siginterrupt
ac_cv_func_signal
ac_cv_func_sigsetjmp
ac_cv_func_socket
ac_cv_func_socketpair
ac_cv_func_strcasecmp
ac_cv_func_strcmpi
ac_cv_func_strdup
ac_cv_func_strerror_r
ac_cv_func_stricmp
ac_cv_func_strncasecmp
ac_cv_func_strncmpi
ac_cv_func_strnicmp
ac_cv_func_strstr
ac_cv_func_strtok_r
ac_cv_func_strtoll
ac_cv_func_writev
ac_cv_header_stdint_h
ac_cv_sig_atomic_t_volatile

**Comment by Irfy** [comment]
I have now renamed the variables, inspecting each single one to make sure it's correct to rename them. A few `ac_cv_` variables rename, with mostly correct usage. One offender is reported in #770, the other one is a major call to `AC_CHECK_FUNCS` with potential modification of the `ac_cv_func_*` variables in its handling of `action-if-not-found` case. I've documented what could be done about that in the commit message itself, but I'd leave it for now.

**Comment by bagder** [comment]
Thanks a bunch, this is now merged as of commit d9f3b365a3b6.

**Pull request closed without merging**
