### PR TITLE
Add a dns resolver interface

### PR DESCRIPTION
**Pull request by Andersbakken**
I'm aware that this isn't complete, it needs documentation, examples and probably some other cleanup but it works for me and I wanted someone to take a look at my approach and give feedback and how I decided to implement this before I venture deeper.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks @Andersbakken. I've started to review this and I agree with your general approach. I think it would be useful if you could describe in a document the high level of how you do write/add a resolver backend using this new mechanism. I'm also a bit hesitant to add that many new functions to the public API for this purpose, but that's just my initial gut feeling - I need to dig deeper before I know for real.

**Comment by Andersbakken** [comment]
Hi Daniel

I was just wondering if you've had any more time to look at the
patch/example. We've been using the code here for awhile and it seems
stable and functional and definitely improves our ability to integrate our
own DNS resolving.

regards

Anders

**Comment by bagder** [comment]
> I've cooked up an example showing how to use the interface which is attached.

That seems to have gotten lost somewhere?

Also, how about fixing the merge conflicts and maybe do some squashes to reduce the number of commits/fixups to help us review this?

In particular I want to see the API for the backend but I also want us to be very careful about every extra function that we introduce with this. Not providing more than we have to and making sure the functions are all documented and tested.

**Comment by Andersbakken** [comment]
Oops. Forgot to attach and to check my email properly :-)

Will squash and fix merge conflicts.

regards

Anders

**Comment by Andersbakken** [comment]
[main.c.txt](https://github.com/curl/curl/files/1543403/main.c.txt)

**Pull request closed without merging**
