### PR TITLE
tests: remove python_dependencies for smbserver from our tree

### PR DESCRIPTION
**Pull request by mback2k**
Users of the SMB tests will have to install impacket manually.

Reasoning: our in-tree version of impacket was quite outdated
and only compatible with Python 2 which is already end-of-life.
Upgrading to Python 3 and a compatible impacket version would
require to import additional Python-only and CPython-extension
dependencies. This would have hindered portability enormously.

See also #5085 for the previous discussion leading into this PR.

### CODE REVIEW

**Comment by mback2k** [comment]
This PR will only cover the removal of our in-tree Python dependencies. For Python 3 another PR will follow.

**Comment by dfandrich** [comment]
FWIW, FreeBSD has impacket in ports as py37-impacket.

**Comment by mback2k** [comment]
@dfandrich thanks, would you mind pushing the relevant change as an additional commit to my branch? You should have permission for that.

**Comment by mback2k** [comment]
@bagder test 323 is now failing in this PR, because I made stunnel available to the CI builds. But I do not have any clue why it is failing, would you mind taking a look at the failed Azure jobs?

**Comment by mback2k** [comment]
@dfandrich for now I added `py27-impacket` to the CirrusCI builds due to smbserver.py not (yet) being fully Python 3 compatible logic-wise. I will work on that in a follow-up PR.

**Comment by bagder** [comment]
I don't see any azure jobs at all?

**Comment by mback2k** [comment]
> I don't see any azure jobs at all?

@bagder that is what I meant with "something is wrong with Azure CI not triggering for PRs anymore". After doing a force-push they weren't triggering anymore for some unknown reason.

**Comment by mback2k** [comment]
@dfandrich would you mind taking a look at the CirrusCI failures? I do not know what is wrong with those packages.

**Comment by mback2k** [comment]
Azure CI builds are for unknown reasons missing for this PR, but are looking good on my end.

**Comment by mback2k** [comment]
@dfandrich I will just add impacket to the FreeBSD builds in another PR to have this finished.

**Comment by mback2k** [comment]
Pending topics for follow up PRs:
- [ ] Add impacket to FreeBSD CirrusCI builds.
- [ ] Fully port smbserver.py to Python 3.

**Comment by mback2k** [comment]
@MarcelRaad good idea, I guess it will make sense to include it in the WSL-based builds I am creating.

For the other builds I am not sure how to install something in the Git bash.exe environment.

**Pull request closed without merging**
