### PR TITLE
Modify appropriate CMakeLists.txts to use curldown

### PR DESCRIPTION
**Pull request by levitte**
This throws away the previous HTML and PDF producers, to mimic what
Makefile.am does as faithfully as possible.  They can easily be added
back if that's desirable.

Amends #12730

### CODE REVIEW

**Comment by levitte** [comment]
Currently in draft...  I wanna see what happens in appveyor (I think I still have that enabled)

**Comment by levitte** [comment]
close/open dance to kick appveyor into gear

**Comment by levitte** [comment]
Nope...  apparently, my appveyor-fu is too weak to get it running.  Oh bother.

**Comment by bagder** [comment]
Lovely, many thanks. Trying it out now!

**Comment by levitte** [comment]
Hold on, the install instructions aren't quite right

**Comment by levitte** [comment]
*Now* they're done right.

**Comment by levitte** [comment]
... and some cleaning up.  Hadn't noticed the "disappeared" commits that this PR carried around

**Pull request closed without merging**
