### PR TITLE
libtest/make: generate lib1521.c

### PR DESCRIPTION
**Pull request by bagder**
... instead of having the generated code checked in. This saves space in
the tarball but primarily automatically adapts to newly added options.

### CODE REVIEW

**Comment by jay** [comment]
I tried this in mingw and it works ok. Note lib1521.c isn't removed in your changes. Also it's failing one of the CI configs with weirdness
~~~
make[2]: *** No rule to make target `mk-lib1521.pl', needed by `lib1521.c'. Stop.
make[2]: Leaving directory `/home/travis/build/curl/curl/build/tests/libtest'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/travis/build/curl/curl/build/tests'
make: *** [test] Error 2
~~~

**Comment by bagder** [comment]
Right thanks, needs some polishing...

**Comment by bagder** [comment]
right, the cmake system needs a poke too...

**Comment by dfandrich** [comment]
This seems to have broken all the autobuilds, presumably when built out of tree.

**Comment by bagder** [comment]
Gah, how did I miss that? =(

**Comment by dfandrich** [comment]
My fix is in PR#1628

**Pull request closed without merging**
