### PR TITLE
curl with c-ares: No DNS requests if a file lookup is successful

### PR DESCRIPTION
**Pull request by ChristianAmmer**
curl with enabled c-ares `--enable-ares` calls `ares_gethostbyname` for both families (`AF_INET` and `AF_INET6`). Even if one family could be resolved through a file lookup, the other family is requested through a DNS lookup. 

curl without c-ares on the other hand uses `getaddrinfo` which does not make a DNS lookup if a file lookup was successful. This is different behavior (E.g. I observed curl with ares timed out on a specific host, while curl without ares did not)

This patch solves this problem by making an explicit file lookup with `ares_gethostbyname_file` before doing any DNS requests. If the file lookup is successful `Curl_resolver_getaddrinfo` returns before calling `ares_gethostbyname`.

### CODE REVIEW

**Comment by bagder** [comment]
`ares_gethostbyname_file` was introduced in c-ares 1.6.0, which we already have documented as the lowest supported version so it should be fine to use without additional #ifdefs.

**Comment by bagder** [comment]
Isn't this strictly speaking a c-ares bug?

**Comment by ChristianAmmer** [comment]
I don't would say it's a bug I think it is more the lack of AF_UNSPEC support of c-ares. Calling ares_gethostbyname for each family was a [workaround for a missing ares_getaddrinfo](https://curl.haxx.se/mail/lib-2010-12/0041.html) function. I think this patch extends the workaround to make "curl with ares" behave more like curl.

**Comment by ChristianAmmer** [comment]
@bagder @yangtse @novikov-dorogatv mention-bot identified you as potential reviewers, what do you think about this Pull Request?

**Comment by bagder** [comment]
Sure, but the choice to go file-first instead of DNS-first is configurable on many systems, and c-ares should (does) read that config file and respects that configured order. Having curl go file-first unconditionally does not make it more similar to the stock resolver for systems configured that way!

**Comment by ChristianAmmer** [comment]
I did not think about that. But the file-first option can be retrieved through `ares_save_options` and if the file lookup is preferred, we could safely call `ares_gethostbyname_file` prior to `ares_gethostbyname`.

**Comment by bagder** [comment]
switching to `ares_getaddrinfo` as being worked on in https://github.com/c-ares/c-ares/pull/112 seems like the most attractive option rather than trying to second-guess the resolver from within curl.

**Comment by ChristianAmmer** [comment]
Meanwhile I'm thinking the same way. Therefore I would agree if this Pull Request gets closed. I hope that some day I will find the time to learn all the things needed for implementing the destination sorting and the other open points for [c-ares#112](https://github.com/c-ares/c-ares/pull/112).

**Pull request closed without merging**
