### PR TITLE
crank up default parallelism in CI to 20

### PR DESCRIPTION
**Pull request by icing**

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15016 at [3e5fd998](https://github.com/curl/curl/commit/3e5fd998cc8ae61c9a226d31f5afe4cabfe562dd):

[Test 1540 failed](https://github.com/curl/curl/actions/runs/10998242995/job/30535754524#check-step-40), which has NOT been flaky recently, so **there could be a real issue in the PR**.  Note that this test has failed in 2 different CI jobs (the link just goes to one of them).

[Test 1070 failed](https://github.com/curl/curl/actions/runs/10998243022/job/30535744829#check-step-14), which has NOT been flaky recently, so **there could be a real issue in the PR**.

[Test 190 failed](https://github.com/curl/curl/actions/runs/10998243022/job/30535730665#check-step-14), which has NOT been flaky recently, so **there could be a real issue in the PR**.

[Test 445 failed](https://github.com/curl/curl/actions/runs/10998243022/job/30535741718#check-step-14), which has NOT been flaky recently, so **there could be a real issue in the PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
It's not much, but this will bump up a couple of cmake Linux jobs (`openssl3 clang krb5` and `aws-lc`):
```diff
--- a/tests/CMakeLists.txt
+++ b/tests/CMakeLists.txt
@@ -91,6 +91,6 @@ add_runtests(test-am        "-a -am")
 add_runtests(test-full      "-a -p -r")
 # ~flaky means that it ignores results of tests using the flaky keyword
 add_runtests(test-nonflaky  "-a -p ~flaky ~timing-dependent")
-add_runtests(test-ci        "-a -p ~flaky ~timing-dependent -r -rm -j2")
+add_runtests(test-ci        "-a -p ~flaky ~timing-dependent -r -rm -j20")
 add_runtests(test-torture   "-a -t -j2")
 add_runtests(test-event     "-a -e")
```

**Comment by icing** [comment]
> It's not much, but this will bump up a couple of cmake Linux jobs (`openssl3 clang krb5` and `aws-lc`):
> 
> ```diff
> --- a/tests/CMakeLists.txt
> +++ b/tests/CMakeLists.txt
> @@ -91,6 +91,6 @@ add_runtests(test-am        "-a -am")
>  add_runtests(test-full      "-a -p -r")
>  # ~flaky means that it ignores results of tests using the flaky keyword
>  add_runtests(test-nonflaky  "-a -p ~flaky ~timing-dependent")
> -add_runtests(test-ci        "-a -p ~flaky ~timing-dependent -r -rm -j2")
> +add_runtests(test-ci        "-a -p ~flaky ~timing-dependent -r -rm -j20")
>  add_runtests(test-torture   "-a -t -j2")
>  add_runtests(test-event     "-a -e")
> ```

Thanks! Added that.

**Comment by icing** [comment]
Replaced with the squash and cleaned up version #15029

**Pull request closed without merging**
