### PR TITLE
vtls: repair build with disabled proxy

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by icing** [comment]
So, this removes the PROXY ifdefs in openssl.c, because the called functions handle that case already?

**Comment by bagder** [comment]
> So, this removes the PROXY ifdefs in openssl.c, because the called functions handle that case already?

This *adds* the ifdef in openssl.c because those variables are unused when there is no proxy support built-in.

**Comment by icing** [comment]
> > So, this removes the PROXY ifdefs in openssl.c, because the called functions handle that case already?
> 
> This _adds_ the ifdef in openssl.c because those variables are unused when there is no proxy support built-in.

Clearly, need more coffee. 

Yes, this looks necessary since structures in `connectdata` will not exist in such a build.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
