### PR TITLE
Fix GEN_PDB option for release builds using MakefileBuild.vc to match Visual Studio project files

### PR DESCRIPTION
**Pull request by mcconkeyp**
Symbol database (PDB) files are not being added to the release DLL target because the /DEBUG switch is not added to the linker command line for release DLL builds.

A PBD file is being generated for the import library, but this does not provide symbols for the DLL.

I have modified LFLAGS_PDB so that the /DEBUG switch is used by the linker for all builds that require a PDB file. The /incremental:no switch is implied by /DEBUG so /incremental:no is removed.

As the linker uses the target DLL name to create a filename for the PDB file, the PBD file for the import library is overwritten by the linker. I have added '_imp' to the name that will be used for the import library PDB file. Both files are now copied to the distribution lib folder.

### CODE REVIEW

**Comment by gvanem** [comment]
@mcconkeyp  You wrote:

> The /incremental:no switch is implied by /DEBUG so /incremental:no is removed.`

Are you sure it's a good idea to remove `/incremental:no`? If I do, I'm getting those pesky `libcurl*.ilk` files after linking. I see no use for such `.ilk` in such a *small* project like libcurl. This switch to seems unrelated to `-release` or `-debug`. Or can you confirm with some quote from MSDN?

**Comment by mcconkeyp** [comment]
@gvanem 

> I see no use for such .ilk in such a small project like libcurl.

I agree.

> Are you sure it's a good idea to remove /incremental:no?

Double checking MSDN shows I am wrong - /DEBUG implies /INCREMENTAL so /incremental:no should stay. I suggest:

`LFLAGS_PDB = /DEBUG /incremental:no /opt:ref,icf`

instead.

**Comment by bagder** [comment]
So will you update this PR?

**Comment by mcconkeyp** [comment]
> So will you update this PR?

Done.

**Comment by mcconkeyp** [comment]
Closed in error.

**Comment by bagder** [comment]
@gvanem, does this PR get a thumbs up from you?

**Comment by gvanem** [comment]
Not sure since I don't use this `Makefile.VC`. This change:
```
+PDB_NAME_DLL           = $(BASE_NAME)_imp.pdb
+PDB_NAME_DLL_DEBUG     = $(BASE_NAME_DEBUG)_imp.pdb
```
will produce `libcurl.dll` and `libcurl_imp.pdb`. No? If yes, :-1: .

AFAICS, a post-mortem debugger (WinDbg) will look for symbols in `foo.pdb` to match a crash-address in `foo.dll`. But a `.pdb` is a good thing (i.e. the `/debug` switch).

@mcconkeyp  I don't understand the:
> .. the PBD file for the import library is overwritten by the linker.

part. Why is having a `libcurl_imp.pdb` important? I'm confused as to the motivation of this PR.

**Comment by mcconkeyp** [comment]
@gvanem 

The makefile as it stands does not create a PDB file for release builds of the DLL. It will only create a PDB file for debug builds. We have modified the makefile so that we can create PDBs for post-mortem debugging of our production builds which use the release version of libcurl.dll.

I agree that PDB files for import libraries are probably not needed for much.

**Comment by mcconkeyp** [comment]
@gvanem 

In addition to my previous comment...

> will produce libcurl.dll and libcurl_imp.pdb. No?

No.

With my changes you get libcurl.lib and libcurl_imp.pdb; you also get libcurl.dll and libcurl.pdb. When you link an exe or another DLL using the import library, the linker uses libcurl_imp.pdb as input, if it is colocated with libcurl.imp, and merges it with any PDB that it is creating.

The libcurl.pdb file is just put into a symbol server with the DLL, or used locally for pm debugging.

**Comment by captain-caveman2k** [comment]
@gvanem 

Traditionally, and I am remembering stuff here from years ago, most people didn't use or want the PDB files from release builds - I know I didn't and probably like others here I've used Visual C++ since v1.0 ;-)

However, I think more and more people are finding them useful so I understand the motivation in this PR and for enabling them. This article gives a useful insight for having them on release builds:

http://www.wintellect.com/devcenter/jrobbins/pdb-files-what-every-developer-must-know

I have also checked our Visual Studio project files to see what we do there and we have both the /Zi flag enabled on the compiler and /DEBUG enabled on the linker for release builds.

@mcconkeyp 

What is the reason for using _imp for the libcurl.lib PDB files? Why not use libcurl.lib and libcurl.pdb for static library builds and libcurl.dll and libcurl.pdb for DLL builds like I do in the project files?

**Comment by mcconkeyp** [comment]
@captain-caveman2k 

> What is the reason for using _imp for the libcurl.lib PDB files?

The suffix _imp was just to distinguish the PDB file generated by the compiler from the PDB file generated by the linker. The PDB file created by the compiler is not needed in DLL builds.

If you pass the /DEBUG switch to the linker it creates a PDB file with the same base name as the EXE or DLL that it is linking, unless you include the /PDB switch to change the name. Here, the linker writes to a file called libcurl.pdb when creating libcurl.dll and, because this was overwriting the compiler's libcurl.pdb, I changed the name for the compiler's /fd switch.

I'm going to have another look at the makefile to change the behaviour so that you end up with this:

1. Static library: libcurl.lib and libcurl.pdb in $(DIRDIST)\lib
2. DLL: libcurl.dll and libcurl.pdb in $(DIRDIST)\bin; import library libcurl.lib in $(DIRDIST)\lib

I think that for DLL builds, libcurl.pdb should be copied to the bin folder because it relates to the dll.

**Comment by mcconkeyp** [comment]
The build file is now modified to generate a PDB file for DLL builds. If a PDB is generated for DLL builds, the file is moved to the \bin folder from the \lib folder so that it is alongside the DLL.

**Comment by bagder** [comment]
I'm awaiting someone knowledgeable in windows (builds) to give this a +1 before I'd merge it.

**Comment by jay** [comment]
The only thing I notice is the if statement is not prefixed with `@`. That symbol is used by nmake as a prefix to hide the command line being executed (not its output, the actual command line). A command line may be silenced other ways but for consistency I'd prefix it with `@` like all the other commands we have there.

**Comment by mcconkeyp** [comment]
> I'd prefix it with @ 

Good point - I've done that.

**Comment by captain-caveman2k** [comment]
@mcconkeyp Just a couple of follow up queries:

* IS GEN_PDB defaulted to true (if it isn't set) for debug builds? If it isn't then I think it should be to maintain current/default behaviour for debug builds
* Rather than copy the .pdb files to \lib and then move them to \bin if the build is DLL, assuming I have understood the current code correctly, it would be slightly more efficient to copy them to \lib if not a DLL build and copy them to \bin if a DLL build

@bagder Once my points are addressed then its a +1 from me ;-)

**Comment by mcconkeyp** [comment]
@captain-caveman2k 

I found that the easiest way to retain the original behaviour is to revert the change that removes the \DEBUG switch for debug DLL builds. If I make GEN_PDB default to true for debug DLL builds, then the compiler emits a warning for every object compilation because both \Z7 and \Zi are defined.

I've modified the file copying to avoid the rename.

I've also updated the comments to match the locations that the files end up in.

**Comment by jay** [comment]
I forget why we're sitting on this

**Comment by bagder** [comment]
AFAIR, we're only waiting for a Windows knowledgeable person to give 👍 to it.

**Comment by mcnulty** [comment]
Would it be possible to merge this change? I just gave it a test drive and it works great.

**Comment by jay** [comment]
> Would it be possible to merge this change? I just gave it a test drive and it works great.

There was some issue with this, it had failed when I tested it. I modified it by putting a - before the commands so if the copy failed it would continue, but there was some problem with it and I didn't get to look into it further. You can see it at https://github.com/curl/curl/compare/master...jay:pr_730_modified?expand=1

**Comment by mcconkeyp** [comment]
@jay I think the - should be at the beginning of the line ie: @-if exist $(DIRDIST)\...

I'm not entirely sure why you would want to suppress an error - the PDB files should only be generated if you set the GEN_PDB option and if they fail to generate for some reason if would be good to know that the the build had failed.

We use this with a Jenkins CI server and it would silently allow the build to fail if you suppress the error from a failed copy. That would be bad in a CI environment where you are relying on failures to be reported.

**Comment by mcnulty** [comment]
@jay: 
> There was some issue with this, it had failed when I tested it. I modified it by putting a - before the commands so if the copy failed it would continue, but there was some problem with it and I didn't get to look into it further. You can see it at https://github.com/curl/curl/compare/master...jay:pr_730_modified?expand=1

Do you happen to have the options you are specifying to nmake? I'm using the following command line/options:

     nmake /f Makefile.vc mode=dll VC=11 WITH_ZLIB=static ENABLE_SSPI=yes ENABLE_IPV6=yes ENABLE_IDN=yes ENABLE_WINSSL=yes GEN_PDB=yes DEBUG=no MACHINE=x64

I wonder if different options would trigger the failure you are seeing. I'd be interested in looking into the failure.

Also, if the copy of the PDB file is not quite right yet, perhaps the addition of the /DEBUG flag to LFLAGS_PDB can be merged separately? Without this flag the PDB generated in the lib directory of the build does not contain line number info or local variable info. In my testing, adding the /DEBUG flag results in the generated PDB being usable for debugging libcurl when linked to an application as a DLL.

**Comment by mcconkeyp** [comment]
@mcnulty 

If I make the changes that @jay made (adding a - in front of the copy commands) I get an error using almost the same command line as yours:

`nmake /f Makefile.vc mode=dll VC=12 ENABLE_SSPI=yes ENABLE_IPV6=yes ENABLE_IDN=yes ENABLE_WINSSL=yes GEN_PDB=yes DEBUG=no MACHINE=x64`

I dropped the zlib option and I'm using VC12.

The error is this:

`NMAKE : fatal error U1077: 'if' : return code '0x1'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.10.25017\bin\HostX64\x64\nmake.exe"' : return code '0x2'
Stop.`

As I said earlier, I think you need to move the - to the start of the command to suppress errors. However, I don't understand why you would want to suppress an error if the copy fails. None of the other copy commands have errors suppressed and if the PDB file fails to be copied, that implies a failed build.

**Comment by mcnulty** [comment]
@mcconkeyp thanks for clarifying.

I was using the changes associated with this pull request, not the changes from [@jay's fork](https://github.com/curl/curl/compare/master...jay:pr_730_modified?expand=1). When using the changes from that fork, I see the same failure. After making the change you suggested, the `NMAKE : fatal error U1077: 'if' : return code '0x1' Stop.` is not encountered.

It looks like some of the other copy commands have errors suppressed. For example, the copy of the export library and the copy of the headers both suppress errors:

`@-copy $(LIB_DIROBJ)\*.exp                 $(DIRDIST)\lib /y >nul 2<&1`
`@-copy ..\include\curl\*.h   $(DIRDIST)\include\curl\ /y  >nul 2<&1`

Also, before the changes in this pull request, the copy of the PDB was suppressing errors:

`@-copy $(LIB_DIROBJ)\*.pdb                 $(DIRDIST)\lib /y >nul 2<&1`

It's probably desirable to maintain that behavior to avoid breaking builds that are depending on errors in this copy being suppressed.

**Comment by mcconkeyp** [comment]
The most important fix in this PR has now been merged nearly two years later in [https://github.com/curl/curl/pull/2274](url) so I'm going to close it. I'll open a new one to see if it's possible to fix the location that the .pdb is copied to for DLL builds in my lifetime.

**Pull request closed without merging**
