### PR TITLE
http2: Add handling stream level error

### PR DESCRIPTION
**Pull request by tatsuhiro-t**
Previously, when a stream was closed with other than NGHTTP2_NO_ERROR
by RST_STREAM, underlying TCP connection was dropped.  This is
undesirable since there may be other streams multiplexed and they are
very much fine.  This change introduce new error code
CURLE_HTTP2_STREAM, which indicates stream error that only affects the
relevant stream, and connection should be kept open.  The existing
CURLE_HTTP2 means connection error in general.

Discussed in GH-659

### CODE REVIEW

**Comment by bagder** [comment]
@jay, how's your plan for this PR? Sounds like something we want to merge...

**Comment by jay** [comment]
> @jay, how's your plan for this PR? Sounds like something we want to merge...

Yes. I ran out of time to review it, and I planned to revisit it after the release but I got caught up in other things. If I can't get to it this week I'll relinquish my assignment. It looks like I have to add some overflow detection as well, as Tatsuhiro noted in his last comment in #659.

**Comment by jay** [comment]
Also this may affect #750, I'm not sure...

**Comment by bagder** [comment]
I don't think it affects #750, as that's not actually a http2 error, stream or otherwise.

**Comment by jay** [comment]
Landed in b2a0376...3f57880, any discussion should continue in #659. Thanks!

**Pull request closed without merging**
