### PR TITLE
CI: macOS fixup nghttp2 install

### PR DESCRIPTION
**Pull request by pheiduck**
[Fixup] Warning: The following dependents of upgraded formulae are outdated but will not be upgraded because they are not bottled:
  mongodb-community@5.0

### CODE REVIEW

**Comment by bagder** [comment]
How come we need it at all in the first place? Can't we just remove it instead?

**Comment by pheiduck** [comment]
> How come we need it at all in the first place? Can't we just remove it instead?
Yes sure we can remove it, I want to fix this CI issue here: https://github.com/curl/curl/actions/runs/3904373833/jobs/6670071643#step:3:590

**Comment by bagder** [comment]
I appreciate that! I just don't understand how mongodb is being involved in our builds in the first place nor how you could identify that being the problem...

Also, how come the circle CI macOS builds that also use homebrew don't see the same problem?

**Comment by pheiduck** [comment]
> I appreciate that! I just don't understand how mongodb is being involved in our builds in the first place nor how you could identify that being the problem...
> 
> Also, how come the circle CI macOS builds that also use homebrew don't see the same problem?

I am not sure. I think we have to open an issue at the homebrew upstream project. Because it fails on all github macOS CIs, or we build it from scratch.

**Pull request closed without merging**
