### PR TITLE
multi: reuse WinSock events variable in Curl_multi_wait

### PR DESCRIPTION
**Pull request by mback2k**
Since the struct is quite large (1 long and 10 ints) we
declare it once at the beginning of the function instead
of multiple times inside loops to reduce stack usage.

cc @rcombs

### CODE REVIEW

**Comment by rcombs** [comment]
I don't object to the change, but I doubt it actually affects the compiler output substantially. No sane modern compiler actually emits anything expensive when entering a block where a POD struct is declared; in most cases they don't emit anything there at all. I wouldn't be surprised if compilers produced exactly the same output both before and after this change. Even if they did emit anything at block entry and exit, at worst it'd be an add or subtract to the stack pointer register, which is 1 cycle on an ALU.

**Comment by bagder** [comment]
I agree with @rcombs . This doesn't fix "stack movements", but it may reduce stack use a little bit. But looking at the diff, doesn't it come at the expense of making the code a tad bit more complicated to read?

**Comment by mback2k** [comment]
> I don't object to the change, but I doubt it actually affects the compiler output substantially. No sane modern compiler actually emits anything expensive when entering a block where a POD struct is declared; in most cases they don't emit anything there at all. I wouldn't be surprised if compilers produced exactly the same output both before and after this change. Even if they did emit anything at block entry and exit, at worst it'd be an add or subtract to the stack pointer register, which is 1 cycle on an ALU.

> I agree with @rcombs . This doesn't fix "stack movements", but it may reduce stack use a little bit.

Thanks for the feedback. I guess that some compilers can optimize this away on high optimization levels, but I am not sure that all the compilers currently supported on Windows are actually doing this. I guess this is neither a pro nor a contra argument.

> But looking at the diff, doesn't it come at the expense of making the code a tad bit more complicated to read?

I personally think the new version is more readable, but I guess I am biased due the similar implementation in [`sockfilt.c`](https://github.com/curl/curl/blob/a935f0bdeb1715ad819c92fc75a49ed3374d5585/tests/server/sockfilt.c#L629).

**Comment by mback2k** [comment]
So it seems like there are more reasons to drop this PR from @rcombs, @jay (the 👍) and @bagder than to keep it.

Would you mind doing 👍 or 👎 on this comment for a final vote?

**Review by vszakats — APPROVED** [review]

**Review by bagder — COMMENTED** [review]
I'm a +0 on this. If you really want to do it like this go ahead, I won't veto it. But:

- I don't think this makes the code more efficient. Using a few less bytes on the stack isn't changing anything
- I think it makes the code harder to read and follow due to the much more frequent use of a very long variable name and access of a struct field member instead of plain local variable
- "if it wasn't broken, don't fix it"

**Comment by mback2k** [comment]
> * I think it makes the code harder to read and follow due to the much more frequent use of a very long variable name and access of a struct field member instead of plain local variable

Thanks, I think I will update the PR to use the struct globally for there it makes sense in the post-wait code path and use a plain local variable for the event mask in the pre-wait code path. This should strike a good balance between the arguments raised.

**Comment by mback2k** [comment]
I force-pushed a rebased new take on this PR. Please take another look @rcombs and @bagder. This should address your points.

**Comment by rcombs** [comment]
Still not sure what the point of hoisting the var is, but I do like the second commit's optimization to cut down on extra checks at least.

**Comment by mback2k** [comment]
Just rebased this to current master again. @bagder would you be fine with me merging this even though the feature window already closed? I was too busy to merge it before and wanted to get your go first after [updating the PR](https://github.com/curl/curl/pull/5886#issuecomment-691538641). Thanks in advance!

**Comment by bagder** [comment]
I'm fine with that. go ahead. This change is in a what I would call a bit of a grey area anyway, not a clear cut "feature" but can also be seen as a sort of bug-fix.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
