### PR TITLE
cmake: restore cmake args list in `buildinfo.txt`

### PR DESCRIPTION
**Pull request by vszakats**
This feature was recently dropped because of a bad side-effect of
silencing unused cmake command-line option warnings.

Fix this issue by retrieving variable values using `get_property()`,
instead of accessing the variables directly. It allows restoring
this feature without the bad side-effect.

Also limit the logic to CI runs.

Follow-up to 96edb5f611c9e54da1ae824d9dc0e219619c24c0 #15501

### CODE REVIEW

**Comment by dg0yt** [comment]
Did you test how much this writes on CMake re-run? I would assume it includes all variables which are also in `CMakeCache.txt`, i.e. all the cache variables from `find_library` and friends.

**Comment by vszakats** [comment]
Running an initial out-of-tree `cmake -B _bld <options>`, then re-running `cmake -B _bld` shows a _subset_ of the original command-line option, but not the whole cache:

initial:
```
-- | -DBUILD_LIBCURL_DOCS="OFF" -DBUILD_MISC_DOCS="OFF" -DCMAKE_TRY_COMPILE_TARGET_TYPE="STATIC_LIBRARY" -DCMAKE_UNITY_BUILD="ON" -DCURL_BROTLI="ON" -DCURL_CA_BUNDLE="none" -DCURL_CA_SEARCH_SAFE="ON" -DCURL_DISABLE_LDAP="ON" -DENABLE_CURL_MANUAL="OFF" -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl@3" -DUNUSED_VARIABLE="FOOBAR"|
```
re-run:
```
-- |                                                    -DCMAKE_TRY_COMPILE_TARGET_TYPE="STATIC_LIBRARY" -DCMAKE_UNITY_BUILD="ON"                                            -DCURL_CA_SEARCH_SAFE="ON"                                                     -DOPENSSL_ROOT_DIR="/usr/local/opt/openssl@3" -DUNUSED_VARIABLE="FOOBAR"|

```

**Comment by vszakats** [comment]
I plan to merge this, unless there is some remaining concern.

**Pull request closed without merging**
