### PR TITLE
Nmake install prefix

### PR DESCRIPTION
**Pull request by eiszapfen2000**
Add WITH_PREFIX flag to the nmake based build to allow for a custom install directory.
Please add rdw@steadingsoftware.com as reviewer.

Thanks,
Thomas

### CODE REVIEW

**Comment by rodwiddowson** [comment]
@eiszapfen2000 I'll try and get a build done from this during the week.  Thanks !

**Comment by bagder** [comment]
Coveralls is just being silly, ignore that.

**Comment by rodwiddowson** [comment]
I Just noticed `winbuild\BUILD_WINDOWS.txt` which  I suppose needs changed, but this is an edge build case so full documentation migth be irrelevant? dunno

Anyway I just did a build from this PR and (to noone's great surprise, I'm sure) I could build just fine

**Comment by bagder** [comment]
Thanks! I added a small blurb to `BUILD_WINDOWS.txt` and merged.

**Pull request closed without merging**
