### PR TITLE
ci/tests: Send test results to Azure DevOps for reporting purposes

### PR DESCRIPTION
**Pull request by mback2k**
This PR adds support for test case reporting within builds running on Azure DevOps / Pipelines.

An example can be seen here: https://mback2k.visualstudio.com/curl/_build/results?buildId=751&view=ms.vss-test-web.build-test-results-tab
image
Unfortunately the detailed test result statistics will only be available to project members:
image
image

What do you think about this? This PR is not yet ready to be merged, because it needs some final rebase/fix before merge, especially in case PR #4866 is merged before.

### CODE REVIEW

**Comment by mback2k** [comment]
@bagder Please enable the "Test Plans" feature inside your curl project on Azure DevOps to test this.

**Comment by mback2k** [comment]
For security reasons it is important to limit the access token in the Pipeline to the current project:
image

**Comment by bagder** [comment]
> @bagder Please enable the "Test Plans" feature inside your curl project on Azure DevOps to test this.

Sorry, I don't know what that is nor where I would find it. I tried searching for it but failed...

**Comment by bagder** [comment]
> For security reasons it is important to limit the access token in the Pipeline to the current project:

That setting is not possible to change in the curl project: *"This setting cannot be changed as it is enforced at the organization level."* (which thus means that it is already set I guess because it is enabled for my user, under which the curl repo sits)

**Comment by mback2k** [comment]
> > @bagder Please enable the "Test Plans" feature inside your curl project on Azure DevOps to test this.
> 
> Sorry, I don't know what that is nor where I would find it. I tried searching for it but failed...

Hi Daniel, no problem, this is on the project settings page. You can probably reach it via:
https://dev.azure.com/daniel0244/curl/_settings/
At the bottom of that page you will find "Azure DevOps services" to enable "Test Plans".

**Comment by mback2k** [comment]
> > For security reasons it is important to limit the access token in the Pipeline to the current project:
> 
> That setting is not possible to change in the curl project: _"This setting cannot be changed as it is enforced at the organization level."_ (which thus means that it is already set I guess because it is enabled for my user, under which the curl repo sits)

That is alright, I meant the organization level setting (your account) instead of the project setting. You can check that here: https://dev.azure.com/daniel0244/_settings/pipelinessettings

**Comment by mback2k** [comment]
> I'm not knowledgeable enough to review the actual code and what it does, but if it works as the attached images show it is certainly a feature I think it should be worth investigating and playing around further with!

Do you think it is okay to have the code directly in runtests.pl? I am also planning on adding that same feature for AppVeyor, because they also have test reporting capabilities. Or do you think it would be better to move the code into a Perl module that is used by runtests.pl?

**Comment by mback2k** [comment]
> Do you think it is okay to have the code directly in `runtests.pl`? I am also planning on adding that same feature for AppVeyor, because they also have test reporting capabilities. Or do you think it would be better to move the code into a Perl module that is used by `runtests.pl`?

The new version of this PR has the Azure-specific code moved into `azure.pm`.

**Comment by mback2k** [comment]
Manually rebased and merged via ada581f2cc32f48c1629b729707ac19208435b27.

**Comment by mback2k** [comment]
Example test reporting can be seen for this commit [here](https://dev.azure.com/daniel0244/curl/_build/results?buildId=838&view=ms.vss-test-web.build-test-results-tab).

**Pull request closed without merging**
