### PR TITLE
Missing EINTR handling

### PR DESCRIPTION
**Pull request by BuGlessRB**
Each of the commits can be committed independently of each other.

### CODE REVIEW

**Comment by BuGlessRB** [comment]
Well, maybe my assessment is incorrect.
What I noticed are the following things:
- In a particular use case (in sx using libcurl) I find a frequently occurring race condition that ends up with an EAGAIN on the first read() after connect().
- Upon investigating the code, I start to look at the first two spots where I find read() system calls, and in one spot I see EAGAIN/EINTR unhandled, and if it occurs, a buffer underrun.  In the second spot I find EINTR unhandled, EAGAIN status unclear.
- I fix both read() cases, and did not try to look at all the rest of the read() calls.
My preliminary conclusion was that handling of EAGAIN and EINTR in (lib)curl is shaky at best.
Apparently that should not be the case, so I'll look at the code again and will try to come up with different fixes for the race.

**Comment by jay** [comment]
I do notice the one in security.c sec_recv does not handle EINTR or EAGAIN or return CURLE_AGAIN but I'm not sure why. It looks like it is used for [FTP GSSAPI authentication](https://github.com/curl/curl/blob/curl-7_53_1/lib/ftp.c#L2678-L2693) and but might be blocking according to the comment (offhand I can't find where this happens).

If non-blocking [readwrite_data](https://github.com/curl/curl/blob/curl-7_53_1/lib/transfer.c#L434) --> Curl_read --> sec_recv --> (if plaintext) read
then the recv handler sec_recv I believe should return CURLE_AGAIN. If so maybe it would be better to call [Curl_recv_plain](https://github.com/curl/curl/blob/curl-7_53_1/lib/sendf.c#L449-L452) which handles both EINTR and EAGAIN and will set CURLE_AGAIN.

OTOH if it's blocking it looks like there's a function for that, [socket_read in security.c](https://github.com/curl/curl/blob/curl-7_53_1/lib/security.c#L141), but it can go into a busy loop.

Concerning the separate case of reading from file:// I believe that's blocking, therefore you shouldn't get EAGAIN but you could possibly get EINTR there or some others, in which case it looks like the current behavior is nread is -1 and it breaks out of the loop and the curl tool code is 0. I don't know why there isn't an error when read result is -1

/cc @frenche

**Comment by frenche** [comment]
@BuGlessRB regarding file.c changes, "file:// transfers" are documented to be blocking as a known bug, see docs/TODO. Can you share a minimal sample of code that reproduces the problem?

@jay I'm not sure what that comment means exactly, but I suspect two things:
**a.** there are several calls in this flow which lead to busy-wait loops, like in Curl_ftpsend (instead of an IO based state-machine).
**b.** the gss_init_sec_context call can block on IO (afaik), in practice it'll depend on the underlying mechanism being used (krb5 would probably block on initiator side but not on acceptor while ntlmssp the opposite).
This affects HTTP negotiate as well, and the only solution I can think of as now is to use a thread in order to do the gss and sspi calls.

**Comment by frenche** [comment]
btw, according to Linux open(2) man page, O_NONBLOCK has no effect on regular files, so the file:// protocol shouldn't EAGAIN I guess.

**Comment by jay** [comment]
Thanks for taking a look. I think we can boil this issue down to EINTR occurring then. @BuGlessRB are you using libcurl threaded and if so please read [libcurl thread safety](https://curl.haxx.se/libcurl/c/threadsafe.html).

**Comment by bagder** [comment]
We should definitively handle them separately anyway. Let's make this PR/issue about possible EINTR problems and their fixes.

**Comment by bagder** [comment]
@BuGlessRB, do you intend to update this?

**Comment by BuGlessRB** [comment]
I will get back on this.  I'm running things through gdb and am trying to pinpoint exact responsibilities.  Watch this space.

**Comment by bagder** [comment]
Stale PR. If you want to continue on this, we can reopen or file a new PR.

**Pull request closed without merging**
