### PR TITLE
curl: add --custom-http-version option

### PR DESCRIPTION
**Pull request by x-way**
This allows setting a custom HTTP/X.Y version for requests.
The HTTP/1.1 vs 1.0 vs 2.0 specific client behavior is not affected,
as this only changes the string sent in the HTTP request, but not the
client behavior.

### CODE REVIEW

**Comment by jay** [comment]
What's the use case for this?

**Comment by x-way** [comment]
It is for testing the webserver response to various HTTP protocol versions:
- does it return a proper error for an unsupported/invalid version?
- does it change its behavior unexpectedly when a different version is passed?

This is used when auditing webserver security, but also during implementation of a new webserver component.

Currently curl allows to specify every aspect of an HTTP request except the HTTP protocol version (eg. you can can define an arbitrary request type with -X, define arbitrary headers with -H, define the payload with -d).
This adds the functionality to also define an arbitrary HTTP protocol version.

**Comment by bagder** [comment]
The test failure implies a memory leak. Presumably because the string is never freed.

**Comment by bagder** [comment]
Abandoned, closing.

**Pull request closed without merging**
