### PR TITLE
example/cookie_interface: fix scan-build printf warning

### LINKED ISSUE #7497: scan-build complaint on cookie_interface.c
Unfortunately, #7490 caused scan-build to yell:
~~~
cookie_interface.c: In function ‘main’:
cookie_interface.c:96:53: error: ‘%.0lf’ directive output may be truncated writing between 1 and 310 bytes into a region of size 230 [-Werror=format-truncation=]
     snprintf(nline, sizeof(nline), "%s\t%s\t%s\t%s\t%.0lf\t%s\t%s",
                                                     ^~~~~
cookie_interface.c:96:5: note: ‘snprintf’ output between 70 and 379 bytes into a destination of size 256
     snprintf(nline, sizeof(nline), "%s\t%s\t%s\t%s\t%.0lf\t%s\t%s",
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              ".example.com", "TRUE", "/", "FALSE",
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              difftime(time(NULL) + 31337, (time_t)0),
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
              "PREF", "hello example, i like you very much!");
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors

_Originally posted by @bagder in https://github.com/curl/curl/pull/7490#issuecomment-886606852_

### PR DESCRIPTION
**Pull request by bagder**
Follow-up to 4b79c4fb565

Fixes #7497

### CODE REVIEW

**Comment by bagder** [comment]
Scan-build didn't like this either:
~~~
cookie_interface.c:96:53: error: ‘%.0f’ directive output may be truncated writing between 1 and 310 bytes into a region of size 230 [-Werror=format-truncation=]
     snprintf(nline, sizeof(nline), "%s\t%s\t%s\t%s\t%.0f\t%s\t%s",

**Comment by danielgustafsson** [comment]
> Scan-build didn't like this either:
> 
> cookie_interface.c:96:53: error: ‘%.0f’ directive output may be truncated writing between 1 and 310 bytes into a region of size 230 [-Werror=format-truncation=]
>      snprintf(nline, sizeof(nline), "%s\t%s\t%s\t%s\t%.0f\t%s\t%s",

IIUC we are printing the number of seconds since epoch, so we know how many digits we need to cover between now and a long time going forward, so we should be able to limit the field accordingly without losing any precision?

**Comment by bagder** [comment]
Yes, I just thinking enlarging the output buffer was better since adding more data into the printf format string might make it harder for users to follow.

**Comment by danielgustafsson** [comment]
> Yes, I just thinking enlarging the output buffer was better since adding more data into the printf format string might make it harder for users to follow.

Fair point.

**Pull request closed without merging**
