### PR TITLE
Sync values for HTTP_ONLY

### PR DESCRIPTION
**Pull request by donny-dont**
The values for HTTP_ONLY differed between CMakeLists.txt and curl_setup.h. Sync them and sort the values in curl_setup.h to make it easier to spot differences.

### CODE REVIEW

**Comment by donny-dont** [comment]
If there are any additional options that should or shouldn't be in that listing let me know and I'll update it.

I just sorted it because its way easier to eyeball differences but I can roll that back too if that's an issue.

**Comment by bagder** [comment]
> The values for HTTP_ONLY differed

Did they? Your commit makes it look like the only thing that differed was the order? (I'm fine with sorting the order, I'm just curious about what I'm missing)

**Comment by donny-dont** [comment]
> > The values for HTTP_ONLY differed
> 
> Did they? Your commit makes it look like the only thing that differed was the order? (I'm fine with sorting the order, I'm just curious about what I'm missing)

CURL_DISABLE_MQTT was missing from the header. If anything else should also be there I’m happy to add the entries.

**Comment by bagder** [comment]
Ah right, didn't spot that!

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
