### PR TITLE
KNOWN_BUGS: cmd: untrusted terminal control chars

### LINKED ISSUE #6150: prevent terminal injection when sending to terminal
### I did this

```
> echo -e '#!/bin/sh\n\necho "evil!"\nexit 0\n\033[2Aecho "Hello World!"\n' > evil.sh
> curl file:/home/jan_automation/evil.sh
#!/bin/sh

echo "Hello World!"
exit 0
```
Classical terminal injection (see https://www.infosecmatter.com/terminal-escape-injection/ ). Everyone using a terminal is expected to know not to do this on untrusted or random content. It is very user unfriendly and it is possible to do better.

Even careful humans make mistakes, so this can happen unintentionally.

Quick way to show that this is also the case for headers in case of a curious reader:
```
> echo -ne "HTTP/1.0 200 OK\r\nEvil: yes\033[2Ano\r\n\r\nEverything is fine.\nHave some tea.\n" | nc -l -p 8080 &
> curl -v localhost:8080
```

### I expected the following

```
> curl file:/home/jan_automation/evil.sh
#!/bin/sh

echo "evil!"
exit 0
␛[2Aecho "Hello World!"
> curl file:/home/jan_automation/evil.sh | cat
#!/bin/sh

echo "Hello World!"
exit 0
> curl --disable-terminal-filter file:/home/jan_automation/evil.sh
#!/bin/sh

echo "Hello World!"
exit 0
> curl --enable-terminal-filter file:/home/jan_automation/evil.sh
#!/bin/sh

echo "evil!"
exit 0
␛[2Aecho "Hello World!"
```

There seems to be no way around detecting a terminal and only doing this when output is sent there, so as not to break many scripts using curl that redirect output to a file or pipe. An argument would be needed to disable this always and one to enable it always. There are more places where output will need to be filtered, like response headers when using --verbose.

Would such a fix be acceptable?

### curl/libcurl version

all of them

### operating system

most of them

### PR DESCRIPTION
**Pull request by JanZerebecki**
Closes #6150

### CODE REVIEW

**Review by bagder — COMMENTED** [review]
So `curl parrot.live` is a bug?

**Comment by JanZerebecki** [comment]
Maybe. Most often the user intent for curl is probably not to to render a terminal movie, but to understand the source of the response body. But if you were to see the parrot only from the http headers with --verbose, certainly. I'd consider this documentation important for people unfamiliar with the implementations details of curl. Though I'm not attached to you labelling it in the same way, as I explained in the linked issue.

Is there a different wording that would be more to your linking?

**Comment by bagder** [comment]
I see curl as a "cat for URLs" and the use of escape sequences to play movies or show graphs in the terminal is a feature that comes with that. If we consider that a bug, then fixing the bug breaks this feature.

I rather view this issue as a feature request for adding a filter that would somehow alter contents before saved or sent to a terminal. That's why I have a hard time to see this added to the known bugs document.

**Review by bagder — CHANGES_REQUESTED** [review]
This is not a bug, it is perhaps a missing feature that could be added to TODO.

**Comment by bagder** [comment]
No response or activity. Closing.

**Pull request closed without merging**
