### PR TITLE
GHA: switch off proselint

### PR DESCRIPTION
**Pull request by bagder**
- typography.symbols.curly_quotes Use curly quotes “”, not straight quotes "". Found once elsewhere.

- typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.a

- typography.symbols.copyright (c) is a goofy alphabetic approximation, use the symbol ©.

- typography.symbols.multiplication_symbol Use the multiplication symbol ×, not the letter x.

### CODE REVIEW

**Comment by bagder** [comment]
Apparently this inability to switch off individual warnings or the entire `typography.symbols` group is a known bug https://github.com/amperser/proselint/issues/1367

We might just need to switch off proselint.

**Comment by dfandrich** [comment]
Analysis of PR #15314 at [0e846ef9](https://github.com/curl/curl/commit/0e846ef9da225211d25d89b0effc930137e090bb):

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-0--2] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-0--1] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-0-0] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-1--2] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-1--1] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-1-0] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test http/test_17_ssl_use.py::TestSSLUse::test_17_09_ssl_min_max[TLSv1-2--2] failed](https://github.com/curl/curl/actions/runs/11380671637/job/31660466786#check-step-28), which has NOT been flaky recently, so **there could be a real issue in this PR**.

There are more failures, but that's enough from Gha.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by dfandrich** [comment]
How about just running proselint's output through grep -v to filter out the unwanted warnings?

**Comment by bagder** [comment]
That could work. We also need to make sure the job "fails" when there are output lines though.

**Pull request closed without merging**
