### PR TITLE
sshserver.pl fixes 

### PR DESCRIPTION
**Pull request by Karlson2k**
Testsuite running SSH script fixes.

### CODE REVIEW

**Comment by bagder** [comment]
AuthorizedKeysFile2 was removed in OpenSSH 5.9, released in September 2011. I say we just remove using that option completely everywhere. Agree?

**Comment by Karlson2k** [comment]
@bagder Agree. 
Update this PR?

**Comment by captain-caveman2k** [comment]
I don't know if this is related but a bunch of autobuilds seem to be failing, as of this commit, due to issues starting the SSH server:

* Dan Fandrich's torture tests
* My Ubuntu 14.04 and 15.04 builds but not my 15.10 builds

I haven't looked at the problem in detail but just wanted to make you aware of the problem before release.

**Comment by bagder** [comment]
Thanks! Hm. A quick google tells me ubuntu 14.04 has a newer openssh server than 5.9 and thus support for that config option was already removed then.

But ok, let me revert that for now and see if we get back some working builds.

**Comment by bagder** [comment]
commit d5e7f50e63 reverted the commit

**Comment by Karlson2k** [comment]
@bagder This PR should break anything.
However, strange that removing usage of undocumented option breaks something.

**Comment by bagder** [comment]
I agree, but since *something* broke I'm testing it out by reverting this...

**Comment by captain-caveman2k** [comment]
Ironically, with fantastic timing, it looks like my autobuild VMs have gone down - my email server is still up so I'm not sure what is wrong at the moment :(

Hopefully Dan's tests will run over night.

**Comment by captain-caveman2k** [comment]
It turns out I had filled up my mailbox on my mail server - deleting some of the emails has enabled my autobuild emails to go out now.

As such, you can see that the 14:30 Ubuntu 14.04 and 16:30 15:04 are now passing as they did previously. I don't know why this fix affected them as it did - but I will try and investigate at the weekend.

Unfortunately I only have 15.10 on my laptop which wasn't affected by the change.

**Comment by bagder** [comment]
Thanks @captain-caveman2k . So @Karlson2k, what was your original reason for removing this option? Was it something that failed to work properly with it still present?

**Comment by Karlson2k** [comment]
@bagder No, it was just annoying strings in logs.
Pay attention to second commit. It helps not only with stderr, but also with any parameter with space or tab.

**Comment by bagder** [comment]
> Pay attention to second commit. It helps not only with stderr, but also with any parameter with space or tab.

And we have a problem with that?

**Comment by bagder** [comment]
That quote fix is now in commit e32644851a4a8. If I may ask, please read https://curl.haxx.se/dev/contribute.html#Write_good_commit_messages for a small "guideline" on how we prefer our commit messages. It would make me merge your fixes even faster!

**Comment by Karlson2k** [comment]
>> Pay attention to second commit. It helps not only with stderr, but also with any parameter with space or tab.

> And we have a problem with that?

If any path is passed in parameter - it may be misinterpreted as several parameters as path may contain spaces.

**Comment by Karlson2k** [comment]
> If I may ask, please read https://curl.haxx.se/dev/contribute.html#Write_good_commit_messages for a small "guideline" on how we prefer our commit messages.

I read it already, but it isn't easy to keep all different preferences for different project in my mind. 
Will try better! :smile:

**Comment by bagder** [comment]
As that old config option doesn't seem to harm anyone but caused trouble when we tried to remove it, let's leave it there a few more years and then do another attempt! case closed for this time.

**Comment by patrikhson** [comment]
Hey,

I need your help with some info I've just read, had some issues and thought you could clarify some moments, please read it here <http://stuwadytri.friendsofthejewishchapel.org/xyfbjn>

paf@frobbit.se

**Pull request closed without merging**
