### PR TITLE
cmake: document `-D` and env build options

### PR DESCRIPTION
**Pull request by vszakats**
Extend `INSTALL-CMAKE` document with the list of available options,
a short description and default values.

The list may not be 100% complete.

There are no component boundaries in CMake, so the line is blurry
between curl options, CMake options, CMake Find modules options.
I included certain CMake options that seemed useful, and/or have
dedicated use withing curl's CMake source. But, all CMake built-in
options are usable, as documented upstream in CMake.

The naming of the options has a heritage and the inconsistencies with
it, including a lack of clear namespace. This may be subject to future
updates, also after figuring out which name has special meaning within
CMake and/or CMake projects out of unwritten convention or something
more tangible.

CMake allows to initialize any internal variable via `-D`. This may be
useful to pre-initialize/override feature check results. The list
doesn't contain these, and they remain officially undocumented.

Also:
- make adjustments to keep the spellchecker happy.
- retrofit description changes to the cmake sources.
- stop documenting deprecated `Find*` variables.

Reported-by: Daniel Stenberg
Fixes #14885

---

Preview:
https://github.com/vszakats/curl/blob/cm-global-internal/docs/INSTALL-CMAKE.md#cmake-build-options

I'm not entirely happy with this due to the possibly tedious (and easy
to miss) maintenance this adds, but likely worth it to have an inventory
like this.

- [x] split to multiple PRs.
- [x] think how to re-sync Find* module option descriptions between
  the documentation an in-source comments.
- [x] add more grouping.
- [ ] make #15005 to also update this documentation.

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15388 at [ab7f649d](https://github.com/curl/curl/commit/ab7f649da43e7048fed96f6b5f93e6e83ea86d23):

[Test 1450 failed](https://github.com/curl/curl/actions/runs/11490563227/job/31981500769#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by bagder** [comment]
Amazing work here @vszakats !

**Comment by vszakats** [comment]
Thanks @bagder!

**Comment by jzakrzewski** [comment]
I'm too generally impressed with all the work you're doing on CMake since some time. Sorry, that I cannot currently chime in :(

**Pull request closed without merging**
