### PR TITLE
http: allow overriding timecond with custom header

### LINKED ISSUE #4103: --header "If-Modified-Since:" doesn't suppress that header
### I did this

```
touch hello.txt
curl --silent --verbose --time-cond hello.txt --header "If-Modified-Since:" --remote-name http://localhost:8080/hello.txt
```

i.e. use `--time-cond` but suppress the header it generates with `--header` as described in the man page: "Remove an internal header by giving a replacement without content on the right side of the colon".

(For context, I'm also adding the `If-None-Match` header, so I do want the 304-means-keep-file behaviour that `--time-cond` provides, just with a different header.)

### I expected the following

The generated `If-Modified-Since` header would be suppressed, like so:
```
GET /hello.txt HTTP/1.1
Host: localhost:8080
User-Agent: curl/7.64.0
Accept: */*
```

### curl/libcurl version
$ curl -V
curl 7.64.0 (x86_64-redhat-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1c zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.20.2 (+libidn2/2.0.5) libssh/0.8.7/openssl/zlib nghttp2/1.38.0
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz brotli TLS-SRP HTTP2 UnixSockets HTTPS-proxy PSL Metalink 

### operating system

Fedora 30

### PR DESCRIPTION
**Pull request by psimonyi**
With `CURLOPT_TIMECONDITION` set, a header is automatically added (e.g. `If-Modified-Since`).  Allow this to be replaced or suppressed with `CURLOPT_HTTPHEADER`.

Closes #4103

### CODE REVIEW

**Comment by psimonyi** [comment]
I do not understand why coveralls thinks coverage went down.  I *added* a test.  The code it's complaining about is nowhere near anything I changed.

Also, the AppVeyor failure doesn't seem to be related either; it's some FTP test failure.  I'm not sure what's wrong.

**Comment by bagder** [comment]
We have some flaky appveyor tests and coveralls sometimes just go totally bananas, none of them are your fault! You can ignore them.

**Comment by bagder** [comment]
Thanks!

**Comment by psimonyi** [comment]
Thank you!

**Pull request closed without merging**
