### PR TITLE
Fix progress meter in parallel mode

### PR DESCRIPTION
**Pull request by Cherish98**
Make sure the total amount of DL/UL bytes are counted before the transfer finalizes. Otherwise if a transfer finishes too quick, its total numbers may not be added, and results in a DL%/UL% that goes above 100%.

### CODE REVIEW

**Comment by jay** [comment]
Is it reproducible? I'm trying to figure out why progress_meter wouldn't be called before progress_finalize, or if it is then why it is not updating those variables.

https://github.com/curl/curl/blob/3266b35bbe21c68dea0dc7ccd991eb028e6d360c/src/tool_operate.c#L2279-L2331

I do see progress_meter a time difference of at least 500 ms if not the final round. Perhaps there should be a check for the initial round as well.

**Comment by jay** [comment]
try this
~~~diff
diff --git a/src/tool_progress.c b/src/tool_progress.c
index 7db6df9..20edaeb 100644
--- a/src/tool_progress.c
+++ b/src/tool_progress.c
@@ -174,13 +174,7 @@ bool progress_meter(struct GlobalConfig *global,
   now = tvnow();
   diff = tvdiff(now, stamp);
 
-  if(!header) {
-    header = TRUE;
-    fputs("DL% UL%  Dled  Uled  Xfers  Live   Qd "
-          "Total     Current  Left    Speed\n",
-          global->errors);
-  }
-  if(final || (diff > 500)) {
+  if(!header || final || (diff > 500)) {
     char time_left[10];
     char time_total[10];
     char time_spent[10];
@@ -199,6 +193,13 @@ bool progress_meter(struct GlobalConfig *global,
     unsigned int i;
     stamp = now;
 
+    if(!header) {
+      header = TRUE;
+      fputs("DL% UL%  Dled  Uled  Xfers  Live   Qd "
+            "Total     Current  Left    Speed\n",
+            global->errors);
+    }
+
     /* first add the amounts of the already completed transfers */
     all_dlnow += all_dlalready;
     all_ulnow += all_ulalready;
~~~

**Comment by Cherish98** [comment]
> Is it reproducible? 

Yes, I found it is easily reproduced when you make a lot of medium-sized transfers on a high-speed link. For example, I was downloading 200 files (5 MB each) from localhost.

```
$ curl -Z 127.1/xx{000..199} > /dev/null
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
869 --  1000M     0   200     0     0 --:--:-- --:--:-- --:--:-- 1402M

$ curl -Z 127.1/xx{000..199} > /dev/null
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
588 --  1000M     0   200     0     0 --:--:-- --:--:-- --:--:-- 1283M
```

If the files are too small (e.g., 1 MB each), the transfers will finish too quickly and DL% will remain `--`.

```
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
--  --   200M     0   200     0     0 --:--:-- --:--:-- --:--:-- 1960M
```

And if the files are too big (e.g., 100 MB each), the progress is likely to be correct.

```
DL% UL%  Dled  Uled  Xfers  Live   Qd Total     Current  Left    Speed
100 --  19.5G     0   200     0     0  0:00:13  0:00:13 --:--:-- 1504M
```

YMMV, because it depends on the loopback interface speed, and in turn your CPU speed, etc.

---

> I'm trying to figure out why progress_meter wouldn't be called before progress_finalize, or if it is then why it is not updating those variables.

Because when a transfer is finished, parallel_transfers() deletes the `struct per_transfer` before calling progress_meter(), and thus its stats need to be saved in progress_finalize(). That is why progress_finalize() existed in the first place.

progress_meter() is called periodically, and it may not catch a transfer's total bytes if the value was unknown during the last call, and the transfer is finished and deleted (i.e., lost) during the next call. (That is why the progress meter is correct when the file size is big enough.) So, you have to make sure progress_finalize() saves the value before it goes away.

---

> 
> 
> try this
> 
> ```diff
> diff --git a/src/tool_progress.c b/src/tool_progress.c
> index 7db6df9..20edaeb 100644
> --- a/src/tool_progress.c
> +++ b/src/tool_progress.c
> @@ -174,13 +174,7 @@ bool progress_meter(struct GlobalConfig *global,
>    now = tvnow();
>    diff = tvdiff(now, stamp);
>  
> -  if(!header) {
> -    header = TRUE;
> -    fputs("DL% UL%  Dled  Uled  Xfers  Live   Qd "
> -          "Total     Current  Left    Speed\n",
> -          global->errors);
> -  }
> -  if(final || (diff > 500)) {
> +  if(!header || final || (diff > 500)) {
>      char time_left[10];
>      char time_total[10];
>      char time_spent[10];
> @@ -199,6 +193,13 @@ bool progress_meter(struct GlobalConfig *global,
>      unsigned int i;
>      stamp = now;
>  
> +    if(!header) {
> +      header = TRUE;
> +      fputs("DL% UL%  Dled  Uled  Xfers  Live   Qd "
> +            "Total     Current  Left    Speed\n",
> +            global->errors);
> +    }
> +
>      /* first add the amounts of the already completed transfers */
>      all_dlnow += all_dlalready;
>      all_ulnow += all_ulalready;
> ```

This does not fix the issue.

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
@jay you okay with this?

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
