### PR TITLE
fuzzer: in fuzzing mode, ensure sync resolution

### PR DESCRIPTION
**Pull request by cmeister2**
In the fuzzer we don't really want to be waiting around for names
to resolve. So, if the name doesn't natively resolve to an IP,
resolve a hostname to 127.0.0.1 instead.

---

Tested on a timeout testcase from the oss-fuzz overnights; previously was stuck in WAITRESOLVE, now it tests the case properly.

### CODE REVIEW

**Comment by bagder** [comment]
How about we instead use [CURLOPT_RESOLVE](https://curl.haxx.se/libcurl/c/CURLOPT_RESOLVE.html) and set 127.0.0.1 for a fixed host name we use when fuzzing?

**Comment by cmeister2** [comment]
https://curl.haxx.se/libcurl/c/CURLOPT_RESOLVE.html won't quite work because the fuzzer autogenerates the URL, including the hostname. We'd have to have a function which extracts the hostname out of the CURLOPT_URL and creates an entry.

I think this way we actually test more code, too; we'll get coverage of the resolution functions (or at least some of them) rather than dropping out too early.

**Comment by bagder** [comment]
Okay, so what about this slightly more generic take in #1958 ? I'd prefer to make something like this in a single place and still provide flexibility...

**Comment by cmeister2** [comment]
My immediate issue is that the field is defined in an environment variable; not sure we can guarantee any environment variables when running the fuzzer.

Part of the reason I went with my approach as well was that we only override the address if we absolutely need to; if the host is a valid IP, then let's use that.

**Comment by cmeister2** [comment]
Any more thoughts here? If there's any markups I have to make I'd like to know.

**Comment by jay** [comment]
are you saying the fuzzer is generating random hostnames and then curl is trying to resolve them? of the two @bagder's seems cleaner

**Comment by cmeister2** [comment]
Yes (in fact it generates URLs and curl tries to resolve those).

I agree that it's clearer; however it does hit less code. However, at this point I don't really mind which we go with. If we go with @bagder 's we do need to address the environment variable issue.

**Comment by bagder** [comment]
Since the actual resolving step is the only step where the generated host name won't be used, I don't think it is a very big compromise. The generated one will still be used everywhere else.

**Comment by cmeister2** [comment]
Shall we continue discussion over at #1958 ? I'll close this as it seems the prevailing opinion is against this approach.

**Pull request closed without merging**
