### PR TITLE
New libcurl option to keep uploading on error

### PR DESCRIPTION
**Pull request by mkauf**
Add the new option CURLOPT_KEEP_UPLOADING_ON_ERROR to control whether uploads
shall be completed when the server responds early with an error status code.

This is suitable for manual NTLM authentication. I have started a discussion about this topic here: https://curl.haxx.se/mail/lib-2016-06/0061.html

### CODE REVIEW

**Comment by bagder** [comment]
I would suggest that the option should use the term  "sending" instead of "uploading". Only because people that send a fixed string in a POST don't always see that as "uploading" but it certainly is sending.

**Comment by mkauf** [comment]
Thank you for the feedback. I have renamed the option to CURLOPT_KEEP_SENDING_ON_ERROR.

**Comment by jay** [comment]
Why did you choose error code >= 300? What if the server returns 302, you need to keep sending? Also why is there no test, is this the type of thing the test suite can't handle?

**Comment by mkauf** [comment]
I haven't chosen this myself, the existing code stops sending data if an early HTTP response with status code >= 300 is received:
https://github.com/curl/curl/blob/af2d679e1414369f23a2d37a113634b0ac7f38b0/lib/http.c#L3155

If the server returns 302, it may happen that the URL in the "Location" header points to the same server, and so keep sending may be important.

I will check whether an automated test is possible.

**Comment by mkauf** [comment]
I have added an automated test.

**Comment by jay** [comment]
@mkauf I've submitted some minor issues as a pr to your branch. After that +1 and since you have the ability to commit now you can do that yourself after security patch release 7.50.3 is released (last I heard will be released this coming week). See https://github.com/curl/curl/wiki/push-access-guidelines because before you push upstream you'll need to amend the commit message to reference this issue

**Comment by mkauf** [comment]
@jay I have read the "push access guidelines" document, it is very helpful for newbies :-)

Thank you for the review and the suggestions!

**Comment by jay** [comment]
No problem and thanks for your work. One thing for the future, as noted in contribute the subject of the commit should be `[area]: [short line describing the main effect]` and it should be imperative present tense if possible. for options I reviewed the history for the last few options added and there doesn't seem to be a standard area or way of doing it. here are some ways, taken from the format of other options recently added
url: add CURLOPT_KEEP_SENDING_ON_ERROR option
news: CURLOPT_KEEP_SENDING_ON_ERROR
http: add new option to keep sending on error
etc

**Pull request closed without merging**
