### PR TITLE
enable multiplexing and HTTP/2 when over HTTPS - by default

### PR DESCRIPTION
**Pull request by bagder**
Starting 7.62.0, multiplexing is enabled by default in multi handles.

[Enable multiplexing by default mail](https://curl.haxx.se/mail/lib-2018-07/0024.html)

[Enable HTTP/2 when using HTTPS, by default mail](https://curl.haxx.se/mail/lib-2018-07/0027.html)

### CODE REVIEW

**Comment by bagder** [comment]
Prerequisites: both #2674 and #2688 need to be fixed accordingly first.

**Comment by dscho** [comment]
@bagder one of our users is facing [a problem with this change](https://github.com/Microsoft/Git-Credential-Manager-for-Windows/issues/812), and maybe you have a quick idea how to solve this.

Apparently NTLM is incompatible with HTTP/2 (I could not find any official documentation, but [this comment on the Firefox bug tracker](https://bugzilla.mozilla.org/show_bug.cgi?id=1366824#c15) seems to suggest so).

However, with the new default in libcurl 7.62.0, it seems that we're upgrading to HTTP/2 before realizing that we cannot authenticate via NTLM, and then the connection is closed without success.

Any idea how to fix this neatly?

**Comment by dscho** [comment]
@ljani indeed. The problem is that cURL somehow does not fall back to HTTP/1.1...

**Comment by dscho** [comment]
I should have known better than to clutter this here, closed ticket with a new concern, so I opened a new ticket: https://github.com/curl/curl/issues/3341. Let's discuss this over there.

**Pull request closed without merging**
