### PR TITLE
tool_homedir: Fix GetEnv for Windows Unicode builds

### PR DESCRIPTION
**Pull request by jay**
- For Windows Unicode builds retrieve the homedir in UTF-8 encoded
  Unicode instead of ANSI local character encoding.

Fixes https://github.com/curl/curl/pull/7252
Closes #xxxx

---

/cc @dEajL3kA

### CODE REVIEW

**Comment by jay** [comment]
This could be a problem if homedir is expected in local encoding by some dependencies. For example, homedir() is used to pass the homedir to the ssh library:

https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/src/tool_operate.c#L1755-L1760
https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/lib/vssh/libssh.c#L2224-L2232
https://github.com/curl/curl/blob/6b951a6928811507d493303b2878e848c077b471/lib/vssh/libssh2.c#L3159-L3177

**Comment by vszakats** [comment]
@jay: You're right, this may indeed be a problem. To resolve this with the least amount of confusion, I think a viable solution is to introduce one variant of `homedir()` that can be used by callers needing legacy 8-bit encodings (e.g. because they need to pass it along to libs that specifically expect 8-bit encodings, or, they have undefined requirements) and another one (say `homedir_utf8()`) that can be used wherever we know that an UTF-8 string is needed.

This also generally describes the problem encodings create. For example, last week I decided to update a libcurl wrapper for Windows Unicode support, but instantly bumbed into the problem where I would have to know precisely when various libcurl `CURLOPT`s, `CURLINFO`s, functions and structures expect/return a zero-terminated raw string (including legacy 8-bit codepage ones), a binary string (this one is obvious because it comes with a length), an 7-bit ASCII string, an UTF-8 string. Depending on this, I need to either convert the string to/from UTF-8 (from the callee's codepage) or leave it untouched. In many cases it's difficult to decide without knowing the whole called stack and at the moment the documentation misses this information. For now I started with a rough map to assign an encoding requirement with each string input/output.

E.g. I assumed that URLs and local filenames are always UTF-8. But, for example usernames and password can be anything, and this is something libcurl needs to specify. Non-local filenames passed around in MIME are a different category, because here we may need to inform the other party about the encoding used (and vice versa).

When this is defined, even curl tool may need be adapted to allow passing raw strings from the command-line (without any codepage/encoding conversion), for example as hex- or base64-encoded strings. This way any password values could be passed without applying any conversion to them, or sending other values just like a server expects.

Back to `GetEnv()`: What also needs to be addressed are all direct `curl_getenv()` calls made from curl/libcurl. Here, 8-bit strings are returned even though some callers would need UTF-8. This could be solved by a `curl_getenv_utf8()` which would always make sure to return UTF-8.

**Comment by vszakats** [comment]
FWIW I've created a Wiki page with the goal to collect string encoding rules for the various libcurl APIs. It is now showing pretty rough, initial state. This is a result of quick walk-through on the ones I used in a particular [libcurl wrapper](https://github.com/vszakats/hb/tree/main/contrib/hbcurl) (not exactly the linked one, but an updated, local version) and doing a rough guess about string encoding:
<https://github.com/curl/curl/wiki/WIP:-libcurl-API-and-expected-string-encodings>

**Comment by jay** [comment]
The latest iteration of this I've banned curl_getenv in the tool in favor of tool_getenv which maps to tool_getenv_local or tool_getenv_utf8. Similarly homedir which maps to homedir_local or homedir_utf8. The _utf8 versions are the default versions used in Windows Unicode builds and local otherwise.

The Windows Unicode builds also have access to _local for situations where a string encoded in the current locale needs to be passed to a dependency. For example, the paths set via curlopt to be passed to the SSH and SSL libraries are retrieved via _local. I'm assuming here these dependencies are using the local encoding, and also this is effectively the way we had it before. The wiki page @vszakats created guesses UTF-8 for these paths, but I haven't seen any dependency documentation supporting that.

The commit message contains more detail.

**Comment by vszakats** [comment]
@jay: LGTM! The codepage wiki indeed only lists the codepage that "makes sense" in its context (hence the included comment). Mapping these codepages to actual build combination behaviour is a next (likely large) undertaking. `libssh2` indeed doesn't have special support for Unicode now, so it needs strings as-is.

**Comment by jay** [comment]
I redid it again to cover both libcurl and the curl tool. getenv, curl_getenv, curlx_getenv are banned in favor of Curl_getenv which maps to Curl_getenv_utf8 for Windows Unicode and Curl_getenv_local otherwise. The Curl_getenv functions are curlx functions that are compiled in both the lib and tool. File paths that are passed to dependencies are retrieved in the current locale encoding always by calling Curl_getenv_local, regardless of build type.

**Comment by vszakats** [comment]
Maybe late to note but OpenSSL _does_ support UTF-8 in default Windows builds (for filenames notably), in these cases, it'd be useful to keep strings in UTF-8.

**Comment by jay** [comment]
> Maybe late to note but OpenSSL _does_ support UTF-8 in default Windows builds (for filenames notably), in these cases, it'd be useful to keep strings in UTF-8.

OpenSSL falls back to the local encoding like we used to do. In that case though passing UTF-8 ca paths from the tool would be more correct. I'll look into if it's practical to special case it.

**Comment by vszakats** [comment]
Yeah, I've noticed (to my horror) that OpenSSL does have a fallback logic. But, UTF-8 is the primary encoding there and without it, it's only possible to pass non-ASCII strings that match your system locale. (This isn't ideal because in shipped software you have no control over the system locale.)

**Comment by jay** [comment]
> Yeah, I've noticed (to my horror) that OpenSSL does have a fallback logic. But, UTF-8 is the primary encoding there and without it, it's only possible to pass non-ASCII strings that match your system locale. (This isn't ideal because in shipped software you have no control over the system locale.)

Frankly this is a good tradeoff, and looking at their source it's actually not the logic I had used. They use the current locale (ie it calls fopen) if the string is not UTF-8 encoded. We have libcurl options that may be passed in local encoding and it would be nice not to break anything, but also not cause any security issue. I may backpedal a bit (To your horror I guess..) and submit a PR to fall back the way OpenSSL does. My comments in 765e060 are wrong. Currently in Windows Unicode builds, if the user is passing a string in the current locale it may be valid UTF-8 and treated as such, regardless of any change there is nothing we can do about that except document such and such option requires (or prefers maybe) UTF-8 for those builds.

**Comment by jay** [comment]
> OpenSSL falls back to the local encoding like we used to do. In that case though passing UTF-8 ca paths from the tool would be more correct. I'll look into if it's practical to special case it.

Ok I did this with a tool global variable `ssl_paths_use_utf8`, you can see how in [tool_libinfo.c changes](https://github.com/curl/curl/pull/7281/commits/a1a983c84de6bae40762d007584bf7f872a8a5bb#diff-b22f876bce1846fac4058338f09b19ec142e9a7f8eaeaec6c139c7ee0efa8a94)

**Comment by vszakats** [comment]
`ssl_paths_use_utf8` is a neat idea! The method may well work for URL strings too.

**Comment by jay** [comment]
I'm second guessing this, I think it may be better to document each string option in Windows Unicode builds should be passed to libcurl in UTF-8 and then in libcurl convert to the current locale. It could be done in Curl_vsetopt when the string option is set or later on when it is passed to the dependency. Otherwise we end up with a mix of having to document for each option which encoding and I think that will make it harder for the user to maintain their code.

**Comment by jay** [comment]
Dead. Adding it to known bugs see #9305. I'm not certain about any of the solutions discussed including this PR which in retrospect seems too complicated. homedir paths may be passed to other libraries that expect the current locale. If this issue comes up again we can reconsider all the options.

**Pull request closed without merging**
