### PR TITLE
[DEBUG] Revert "test122[12]: remove these two tests"

### PR DESCRIPTION
**Pull request by bagder**
This reverts commit 15997f6db53c70070177739716dc518e667e6090.

This mostly a DEBUG-ATTEMPT to see if this makes the auotools builds on
appveyor work again.

### CODE REVIEW

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/issues/6120

**Comment by jay** [comment]
runtests arguments:
~~~
$VAR1 = [
          '-a',
          '-b1034',
          '-p',
          '!flaky',
          '!19',
          '~1056',
          '!1233'
        ];
~~~
what is -b1034 ? It looks like 1034 is extrapolated from the appveyor api url, I can't figure out what it does. Also [these errors](https://ci.appveyor.com/project/curlorg/curl/builds/35939886/job/k6kgjje127chwqjy#L2427).

/cc @mback2k

**Comment by bagder** [comment]
This revert confirmed that this commit was not related to the new failures though as they still fail.

**Comment by bagder** [comment]
I landed e2bcdf557b1 over in master that removed the `-b` use there.

@jay, you think of anything else to test in this PR? Otherwise we can close it again as it didn't help one bit...

**Comment by jay** [comment]
> I landed [e2bcdf5](https://github.com/curl/curl/commit/e2bcdf557b16962af51a34ce493c4375e24895a7) over in master that removed the `-b` use there.
> 
> @jay, you think of anything else to test in this PR? Otherwise we can close it again as it didn't help one bit...

That commit appears to have fixed #6120. It looks like what happened was since the -b flag was removed it was treated as a keyword, in other words run only tests containing the keyword `-b1034`. I would say we should ban unknown options, but it looks like they are intentionally passed on as keywords, since some curl options are used as keywords. For example `--write-out` when passed to runtests is used to identify tests that have keyword `--write-out`.

**Comment by jay** [comment]
Fixed by e2bcdf5.

**Comment by bagder** [comment]
aaaah, thanks for the analysis @jay, I was too thick to think of that! I suppose this tells us we should make runtests.pl fail if used with an unrecognized command line option...

**Comment by jay** [comment]
> I suppose this tells us we should make runtests.pl fail if used with an unrecognized command line option...

That's an option but by doing that we'd break tool options passed as keywords. I don't know how big a deal that is. A workaround could be remove the -- from the tool option keywords so for example keyword `--write-out` would become `write-out` then ./runtests.pl write-out instead of ./runtests.pl --write-out

**Comment by bagder** [comment]
Yeah I realized that as well. I think #6126 might be enough for next time we see this happen!

**Comment by mback2k** [comment]
Thanks for working on this, unfortunately I was too busy with private life in the past days.

**Pull request closed without merging**
