### PR TITLE
azure: add a macos build

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
Can't run configure on the macos image for some reason?!

**Comment by MarcelRaad** [comment]
And the reason is:
> buildconf: autoconf not found.

**Comment by bagder** [comment]
Ah!

**Comment by bagder** [comment]
That wasn't too hard, no. I'll merge this to get the basic macOS azure build in place, and then fire up a new PR for more macOS versions on it, possibly removing a few from travis.

**Pull request closed without merging**
