### PR TITLE
curl: use dot as decimal separator independent of locale

### PR DESCRIPTION
**Pull request by bagder**
Independently of what the locale says

Reported-by: Daniel Faust
Ref: #9969

### CODE REVIEW

**Comment by bagder** [comment]
Unfortunately, this change is also likely to break a few scripts out there... :cry:

**Review by MarcelRaad — APPROVED** [review]
> Unfortunately, this change is also likely to break a few scripts out there... 😢

At least they're broken consistently then. Or maybe wait 12 weeks for the last v7 release before breaking stuff? :-D

**Comment by jay** [comment]
You are changing the locale on everything not just decimals.

**Comment by bagder** [comment]
Yes, but is there anywhere we *want* locale dependent behavior?

**Comment by jay** [comment]
System error messages. The default is c so you could delete the statement.

**Comment by bagder** [comment]
The IDN tests seem to fail with this so I guess I have to do it differently.

**Pull request closed without merging**
