### PR TITLE
[Cmake] Fix cmake build on Ubuntu 14.04

### PR DESCRIPTION
**Pull request by akhilkedia**
Fixed a syntax error with setting cache variables (The type and docstring were missing), resulting in build errors.
Quoted the CA_BUNDLE_PATH otherwise the path was written without quotes in C code, resulting in build errors.

Signed-off-by: Akhil <akhil.kedia@samsung.com>

### CODE REVIEW

**Comment by bagder** [comment]
@webmaster128: you agree?

**Comment by webmaster128** [comment]
I'd rather add quotes where CURL_CA_BUNDLE is inserted into C-code because it is not cmake's business that C need quotes, right?

**Comment by bagder** [comment]
Why not? It's cmake's business to figure out the define and provide it in a way that can be used, and we've had configure set the define with quotes since a very long time.

Also, a define with a path without quotes is a weird thing to set to a C program as it would require funky preprocessor "tricks" to turn it into a proper string in code.

**Comment by jzakrzewski** [comment]
I'm with @bagder on this one.

**Comment by webmaster128** [comment]
Maybe I expressed myself in a misleading way. I'm preparing a patch to show my point

**Comment by webmaster128** [comment]
I think the quotes should not be contained in the value of the cmake variables `${CURL_CA_PATH}` and `${CURL_CA_BUNDLE}` but be inserted at the point where cmake generates a C-compatible `curl_config.h` file from `curl_config.h.cmake`

See diff: https://github.com/curl/curl/compare/master...webmaster128:build-issue

This is the way it is done for `RANDOM_FILE` in curl_config.h.cmake as well.

**Comment by jzakrzewski** [comment]
Hmmm... that would actually make sense.

**Comment by bagder** [comment]
Aha, yes @webmaster128 I think that's a nicer approach!

**Comment by webmaster128** [comment]
Feel free to cherry pick those commits. Or do you need a PR?

Sorry for breaking master. Looks like I only tested the absense of the paths in #1461. And thanks for pinging me here.

**Comment by bagder** [comment]
@akhilkedia: you think you can incorporate @webmaster128's idea into your PR here?

**Comment by akhilkedia** [comment]
@Badger - i'll update the PR

**Comment by bagder** [comment]
Thanks @akhilkedia, @webmaster128 and @jzakrzewski!

**Pull request closed without merging**
