### PR TITLE
lib: Added 'IS_HTTP_PROXY' macro similar to 'IS_HTTPS_PROXY'

### PR DESCRIPTION
**Pull request by gblmrn**

### CODE REVIEW

**Comment by bagder** [comment]
I don't think this actually helps since the macro is only used once. and it now conflicts

**Comment by gblmrn** [comment]
Thank you for the reply, I saw that there was a 'IS_HTTPS_PROXY' macro  already and I though to create one for HTTP.

**Comment by bagder** [comment]
Sure, but in this case you add an indirection that is used in a single instance. It does not help code readability.

**Comment by gblmrn** [comment]
Thank you for you response, in this case I will close this PR

**Pull request closed without merging**
