### PR TITLE
build: define WIN32_LEAN_AND_MEAN in VS project files

### PR DESCRIPTION
**Pull request by MarcelRaad**
This adds the nmake build fix from commit
cd34ffa614b04ed6ab6533fa3b8661f0ef9abfa9 to the Visual Studio project
files.

### CODE REVIEW

**Comment by jay** [comment]
rather than put this in all the build systems in every project would this be a better candidate for curl_setup or something

**Comment by bagder** [comment]
I think @jay's suggestion sounds fine. Or is there a downside with doing it there?

**Comment by MarcelRaad** [comment]
Good idea! I thought that would also affect users of libcurl, but it doesn't. curl_setup. h is guaranteed to always be the first include, isn't it? (I've just checked and in practice it seems to be the first file to get included in every compilation unit.)

**Comment by MarcelRaad** [comment]
Moved it to the top of curl_setup.h in #1672.

**Comment by MarcelRaad** [comment]
Fixed by #1672.

**Pull request closed without merging**
