### PR TITLE
Some work on the OS/400 port

### PR DESCRIPTION
**Pull request by monnerat**
The most important commit of this bunch implements the curl cli tool in the ILE environment.
This is an important step towards supporting the tests on OS/400.

There is also a libtests compilation error fix.

The OS/400 build parameters are now customized in a separate file.

Rest is minor fixes and specific doc update.

Compiles and runs (tested manually!).

### CODE REVIEW

**Comment by monnerat** [comment]
> Oops, https://github.com/curl/curl/pull/11650 made this merge conflict

Yes, I was expecting it. Fixed now, together with some adaptations to latest commits.

**Comment by monnerat** [comment]
@bagder: are you planning to pull this before release? There is an OS400 build fix (followup to commit cfe85ca) in it. I would prefer not to backport it.
There are no new feature in this PR: only fixes and cli tool building on OS400. It should not affect other builds. Servers/libtests compilation is NOT performed by makefile.sh.

**Comment by bagder** [comment]
@monnerat it is very helpful if you request a review from me or otherwise mention in a comment that the PR is ready for merge when it is, as it is hard for me to keep track. Then I could perhaps act a little sooner on PRs.

I'll get to this one asap!

**Comment by monnerat** [comment]
> I'll get to this one asap!

Thanks!

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
