### PR TITLE
ssh execute with libssh

### PR DESCRIPTION
**Pull request by RekGRpth**

### CODE REVIEW

**Comment by bagder** [comment]
There's no need to create new PRs just to squash multiple commits into a single one. You can just "fixup" the commits (to make them a single one in your branch) and force-push.

**Comment by bagder** [comment]
There's still no documentation nor tests for this feature. How do we use it? How do we know it works?

**Comment by RekGRpth** [comment]
```sh
echo hello | curl ssh://login:password@server.com:22/bin/cat
```

**Comment by RekGRpth** [comment]
but I use it in https://github.com/RekGRpth/pg_curl to run ssh commands from postgres

**Comment by bagder** [comment]
I meant that I miss docs as part of this PR. We can't merge code that isn't documented how it is supposed to be used.

That's not following any existing URI spec for the syntax, does it? What does that example even do? Sends 'hello' to the `/bin/cat` command? So how do you invoke the `bin/cat` command? (ie no leading slash) ?

So this code accepts data on stdin and sends output to stdout by default? What happens when the command you invoke stops?

**Comment by RekGRpth** [comment]
> That's not following any existing URI spec for the syntax, does it?

It uses syntax of scp upload

**Comment by RekGRpth** [comment]
> So how do you invoke the `bin/cat` command? (ie no leading slash) ?

```sh
echo hello | curl ssh://login:password@server.com:22/bin/sh -c cat
```

**Comment by RekGRpth** [comment]
> So this code accepts data on stdin and sends output to stdout by default?

Yes, as and scp upload does

**Comment by RekGRpth** [comment]
> What does that example even do? Sends 'hello' to the `/bin/cat` command?

Yes, and receives answer from command

**Comment by RekGRpth** [comment]
> What happens when the command you invoke stops?

execution terminates

**Comment by bagder** [comment]
> `echo hello | curl ssh://login:password@server.com:22/bin/sh -c cat`

curl's `-c` option is for saving cookies!

**Comment by RekGRpth** [comment]
> > `echo hello | curl ssh://login:password@server.com:22/bin/sh -c cat`
> 
> curl's `-c` option is for saving cookies!

I mean of course
```sh
echo hello | curl "ssh://login:password@server.com:22/bin/sh -c cat"
```

**Comment by bagder** [comment]
> echo hello | curl "ssh://login:password@server.com:22/bin/sh -c cat"

I'd call that seriously crazy. Not only do you invent your own URI syntax, you come up with one where you can only invoke commands that start with a slash. That command line still invokes a command starting with slash, you just happen to invoke one that itself then can run another command.

**Comment by RekGRpth** [comment]
> Not only do you invent your own URI syntax

No! The syntax is same for scp upload

**Comment by RekGRpth** [comment]
> space is not legal in a URL

scp upload allows file names with space, isn't it?

**Comment by bagder** [comment]
> No! The syntax is same for scp upload

Right, the syntax that is defined for `SCP://` URIs (and not `SSH:`) is made for path names in the file systems and there's a way to specify file names relative to the user's home directory instead of relative to root. To me it seems strange to specify command names in that same manner. It starts a shell in the remote end, doesn't it? Then we have a default PATH there, right? So what if I want to invoke "xeyes" (without absolute path) ? Saying I need to invoke `/bin/sh` and know that it supports a `-c` option is pretty poor. What if I want to SSH to a host without `/bin/sh` or one without `-c` support?

If I made up my own syntax for this, I would probably argue that the first slash after the port number is a *separator* not the first letter of the command ǹame. So I'd have to write two slashes if you wanted to specify the root slash. Similar to how FTP URIs work.

> scp upload allows file names with space, isn't it?

Hm, yes, thinking another round on this I'm pretty the parser will accept plain spaces there too. Even though they're strictly speaking not legal according to the URI syntax (RFC 3986).

**Comment by bagder** [comment]
Two months with no update, and several merge conflicts. Closing.

**Pull request closed without merging**
