### PR TITLE
Porting subset internal patches from FreeBSD port tree

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by bagder** [comment]
Please explain what the patch does and why!

**Comment by bagder** [comment]
"signal/threads issues on this platform" is not clear enough. There are signal and threads issues on all platforms for all I know, but libcurl typically lets the application make the decision on how to deal with those. Explicitly disabling this needs more explanation and if deemed really necessary it should also be documented accordingly.

**Comment by bagder** [comment]
It could also be noted that we successfully build and run all tests on FreeBSD for every commit and PR already without this patch. On several FreeBSD versions too.

**Comment by devnexen** [comment]
In fact I just tried to port an internal patch from the packaged version. but maybe you are right, it does not need to be and more likely to suppress this "fix" in the package ... If confirmed, I may close this PR.

**Comment by bagder** [comment]
I think this just shows the problem of someone doing their own patch in their packaged version without ever bothering to take the patch to us discuss it or argue for it, thus ending up with a useless patch that causes work and friction.

If this is a good idea, then we should merge it upstream in our repo. If it is a bad idea, then it shouldn't be shipped separately in the FreeBSD version either...

**Comment by devnexen** [comment]
In fact it was a very old patch which was seemingly necessary in the past but somewhat remained until now.

**Pull request closed without merging**
