### PR TITLE
[WIP] Publish Zuul CI build status on GitHub

### PR DESCRIPTION
**Pull request by dvejmz**

### CODE REVIEW

**Comment by bagder** [comment]
@mnaser @albinvass any chance you can help us out get the zuul jobs show up proper again?

**Comment by dvejmz** [comment]
I had a stab at this yesterday. With my limited understanding of Zuul CI and the way it's configured for this project, it looks like the config side of things shouldn't be too dissimilar to the diff on this PR

```
- pipeline:
    name: check
    manager: independent
    start:
      github:
        check: in_progress
```

The Zuul status reporter for GitHub is configured at the pipeline level, but we don't seem to define a Zuul CI pipeline per se in the Zuul config file. I think Zuul just assigns a default `check` pipeline to the project. So what I've done in this PR is use the same name, hoping it will just pick it up. Not too sure if there's something else we need to admin in Zuul CI or on GitHub to grant Zuul perms to send updates to the GitHub API.

**Comment by dvejmz** [comment]
Cool, if changes need to be made in the curl repo, I'm happy to update this PR to include them. If the fix lies elsewhere, also happy to close it down.

**Comment by dvejmz** [comment]
I've decided to close off this PR as, in light of the comments above, I most likely lack the required level of access or knowledge of the existing setup to bring this to completion. I'm happy to let someone else open a new PR to have a go at it.

**Comment by mnaser** [comment]
Hi there,

I can try and pick this up @dvejmz -- can you let me know what is needed from my side?

Thanks

**Pull request closed without merging**
