### PR TITLE
naive attempt to implement CURLOPT_CURLU

### PR DESCRIPTION
**Pull request by xquery**
Implement CURLOPT_CURLU (as per https://github.com/curl/curl/wiki/URL-API) so we can just pass to easy_setopt aka:
```
  easy_setopt(handle, CURLOPT_CURLU, urlp);
```

Unsure of the idiom eg. I have emulated how CURLOPT_URL does things in CASE CURLOPT_CURLU, perhaps I should have set CURLOPT_URL. 

In addition, could use advice on what needs doing when we create a new option (man file, version in, etc).

### CODE REVIEW

**Comment by bagder** [comment]
Thanks @xquery!

This is certainly a good first take in supporting providing an already parsed URL, but I would prefer that it took it one extra step:

Instead of this generating a URL to use that is then later parsed again and separated into components, it would be more clever to just save the CURLU handle and then we can *skip* the "ordinary" parsing of the URL since its already done. When we avoid two rather costly steps.

**Comment by bagder** [comment]
> advice on what needs doing when we create a new option (man file, version in, etc).

Some things that come to mind:

- There needs to be a man page for the option and curl_easy_setopt.3 must mention/link it. (test 1139 verifies)
- the new man page must be added to the Makefile.inc file to get included in the distrbution
- `docs/libcurl/symbols-in-versions` must be updated with the new symbol (verified by test 1119)
- test 1521 might need attention since it generates source code to test options
- the test(s) for the new option of course need to run fine, even with valgrind and with `runtests.pl -t`

**Comment by xquery** [comment]
I missed off the fact you already replaced internals for urls ... thx will use that!

**Comment by bagder** [comment]
I would think the set CURLU handle should be in `struct UserDefined` and in `url.c:parseurlandfillconn()` that handle could be used directly (if set) instead of parsing `data->change.url`.

Oh btw, this also needs some attention/consideration in `curl_easy_dup()` if `CURLOPT_CURLU` is set on a handle that is then duplicated.

**Comment by xquery** [comment]
Do we need to change what CURLOPT_URL eg. should it now reuse new url internals ?

**Comment by xquery** [comment]
> I would think the set CURLU handle should be in `struct UserDefined` and in `url.c:parseurlandfillconn()` that handle could be used directly (if set) instead of parsing `data->change.url`.
> 
> Oh btw, this also needs some attention/consideration in `curl_easy_dup()` if `CURLOPT_CURLU` is set on a handle that is then duplicated.

getting a little lost ... need some hand holding.

so ... in url.c:parseurlandfillconn which gets invoked by url.c:create_conn, up front of url.cparseurlandfillconn I see:

```
 uh = data->state.uh = curl_url();
``` 
and then it seems like this function populates uh for when CURLOPT_URL but not the reverse eg. when uh is passed via CURLOPT_CURLU. 

Presumably if I do something like the following in setopt.c in CASE CURLOPT_CURLU

```
    data->set.uh = (CURLU *)va_arg(param, void *);
```

then I can grab onto that in url.c:parseurlandfillconn

does that seem like a rational approach ?

**Comment by bagder** [comment]
> does that seem like a rational approach ?

Yes, totally! What's set with `CURLOPT_CURLU` is stored in the `data->set` struct unmodified, and then when it is time to parse the URL it can skip the parsing and assign `data->state.uh` straight from that. Of course, the cleaning up of that handle should then also be skipped if `data->set.uh` was used...

**Pull request closed without merging**
