### PR TITLE
Add CURL_STATICLIB warning to static linking instructions.

### PR DESCRIPTION
**Pull request by mvittiglio**
This should help with future users to prevent some head-scratching and keyboard-smashing.

### CODE REVIEW

**Comment by jay** [comment]
This is already covered in [INSTALL.md](https://github.com/curl/curl/blob/curl-7_67_0/docs/INSTALL.md#important-static-libcurl-usage-note) and in the [FAQ](https://github.com/curl/curl/blob/curl-7_67_0/docs/FAQ#L1240-L1266). Why do we need it in the build notes?

**Comment by mvittiglio** [comment]
@jay I appreciate that having information increases the upkeep of said knowledge. My thought is that putting this critical bit adjacent to the windows readme info (where some information is already being duplicated regardless) can only help prevent unnecessary time wasted. Perhaps, ideally, a wiki could get around this by linking between info but, easier would be to include this critical "gotcha" in the document for the time being.

That's just my 2 cents so feel free to disregard. Have a great day!

**Comment by jay** [comment]
Ok. I went with a different wording that is close to that in the FAQ.

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
