### PR TITLE
README.md: use SVG logo

### PR DESCRIPTION
**Pull request by vszakats**

### CODE REVIEW

**Comment by bagder** [comment]
I wanted to use the version of the image hosted at github itself and not suck in the image from the haxx.se server. And when I viewed the SVG image "raw" as hosted by github it showed me the SVG data, not an image - while displaying the PNG version "raw" shows an image. I figured it is likely because github doesn't send the correct content-type or similar and I ended up picking the PNG version...

I can of course still try to use the SVG version and see what happens.

**Comment by bagder** [comment]
~~~
$ curl -sI https://raw.githubusercontent.com/curl/curl-www/master/logo/curl-logo.svg | grep Type
X-Content-Type-Options: nosniff
Content-Type: text/plain; charset=utf-8

**Comment by vszakats** [comment]
Indeed, the `.svg` cannot be used right from the GitHub servers for the reason you mention.
I don't see a problem with linking directly to the final domain (except for the excess traffic that is), but there is another trick, relying on an interim [server](https://rawgit.com/) as `https://rawgit.com/curl/curl-www/master/logo/curl-logo.svg`:


It's a free service and appears to support loads via a well-known CDN.

**Comment by bagder** [comment]
Thanks, I merged that version and it works nicely!

**Comment by vszakats** [comment]
You're welcome and thanks! One minor note, I just noticed after posting the above that now `rawgit.com` asks to use the domain `cdn.rawgit.com` for production and keep the old bare `rawgit.com` for testing/development only, so it'd be probably nice to change it to play nicely with their service. (I did update my post above as well)

**Pull request closed without merging**
