### PR TITLE
mbedtls: support CURLOPT_CERTINFO

### PR DESCRIPTION
**Pull request by sergio-nsk**

### CODE REVIEW

**Comment by bagder** [comment]
The **Linux / mbedtls** job fails here. Was that just a temporary glitch or is this PR making it fail?

**Review by bagder — APPROVED** [review]
I presume the fact that this PR is still in draft is not significant?

**Comment by sergio-nsk** [comment]
I am experimenting with what is wrong with the proxy tests on Linux/mbedtls. I've disabled `SSLSUPP_CERTINFO` and got the tests passed. All looks well in other tests, I might miss something in other files.

**Review by bagder — CHANGES_REQUESTED** [review]
Is this going anywhere soon or can we close this again? Having a draft PR queued up in a temp state does us no good.

**Comment by sergio-nsk** [comment]
I will fix and finish this PR. Just getting troubles with runnings and debugging the python tests locally.

**Comment by bagder** [comment]
I think you want something like this?

~~~diff
diff --git a/tests/test1275.pl b/tests/test1275.pl
index 47ce799578..353391d2f3 100755
--- a/tests/test1275.pl
+++ b/tests/test1275.pl
@@ -30,10 +30,11 @@ my @m = `git ls-files -- $root`;
 my $errors;
 
 my %accepted=('curl' => 1,
               'libcurl' => 1,
               'macOS' => 1,
+              'mbedTLS' => 1,
               'c-ares' => 1);
 
 sub checkfile {
     my ($f) = @_;
     chomp $f;

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
