### PR TITLE
Install curl.1 with cmake as well

### PR DESCRIPTION
**Pull request by levitte**
Ref: #12730

### CODE REVIEW

**Review by vszakats — APPROVED** [review]

**Comment by vszakats** [comment]
LGTM, thanks @levitte!

**Comment by bagder** [comment]
@levitte do you think you can rebase this against master? I merged the curldown branch and now this has merge conflicts ...

**Comment by vszakats** [comment]
When testing this locally, it applies fine to the latest master (e17b89db8).

**Comment by bagder** [comment]
Thanks, so yes if I just get the patch and git am it, it works as-is! Good, I'll merge!

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
