### PR TITLE
cmake: Build manual pages (curl.1 and libcurl (3) manpages)

### LINKED ISSUE #1230: cmake: *** No rule to make target '../docs/curl.1'
### I did this

A fresh git clone.

    $ ./buildconf
    $ mkdir build && cd build
    $ cmake ..
    $ make

Which ends in:

~~~
make[2]: *** No rule to make target '../docs/curl.1', needed by 'src/tool_hugehelp.c'.  Stop.
~~~

### I expected the following

A successful build

### curl/libcurl version

git master since commit 4c49b835979694, as announced on the [curl-library list](https://curl.haxx.se/mail/lib-2017-01/0147.html).

### operating system

Any

### PR DESCRIPTION
**Pull request by Lekensteyn**
Also make Perl mandatory to allow building the docs.

While CMakeLists.txt could probably read the list of manual pages from
Makefile.am, actually putting those in CMakeLists.txt is cleaner so that
is what is done here.

Fixes #1230
___
cmake: add support for building HTML and PDF docs

Note that for some reason there is this warning (that also exists with
autotools, added since curl-7_15_1-94-ga718cb05f):

    docs/libcurl/curl_multi_socket_all.3:1: can't open `man3/curl_multi_socket.3': No such file or directory

Additionally, adjust the roffit --mandir option to support creating
links when doing out-of-tree builds.
___
(NOTE: this does not install manpages yet)

### CODE REVIEW

**Comment by Lekensteyn** [comment]
I created a new change to separate the variables and rebased the other changes on top of them. Tested with cmake only.

(If another iteration is needed, I'll probably add try to move the `MANPAGE` variable to cmdline-opts/Makefile.inc, but that is a small issue.)

**Comment by bagder** [comment]
I'd be happy to see this change land, anything still pending @Lekensteyn ? (apart from a needed rebase that is)

**Comment by Lekensteyn** [comment]
Rebased and resolved conflicts in Makefile.am; `git diff be426dbe1 4343de2b8 -- ":docs/*/Makefile.inc"`:
```diff
diff --git a/docs/cmdline-opts/Makefile.inc b/docs/cmdline-opts/Makefile.inc
index 79db71119..97c0547ee 100644
--- a/docs/cmdline-opts/Makefile.inc
+++ b/docs/cmdline-opts/Makefile.inc
@@ -35,8 +35,10 @@ DPAGES = abstract-unix-socket.d anyauth.d append.d basic.d cacert.d capath.d cer
   service-name.d show-error.d silent.d socks4a.d socks4.d socks5.d      \
   socks5-gssapi-nec.d socks5-gssapi-service.d socks5-hostname.d         \
   speed-limit.d speed-time.d ssl-allow-beast.d ssl.d ssl-no-revoke.d    \
-  ssl-reqd.d sslv2.d sslv3.d stderr.d tcp-fastopen.d tcp-nodelay.d      \
+  ssl-reqd.d sslv2.d sslv3.d stderr.d suppress-connect-headers.d        \
+  tcp-fastopen.d tcp-nodelay.d                                          \
   telnet-option.d tftp-blksize.d tftp-no-options.d time-cond.d          \
+  tls-max.d                                                             \
   tlsauthtype.d tlspassword.d tlsuser.d tlsv1.0.d tlsv1.1.d tlsv1.2.d   \
   tlsv1.3.d tlsv1.d trace-ascii.d trace.d trace-time.d tr-encoding.d    \
   unix-socket.d upload-file.d url.d use-ascii.d user-agent.d user.d     \
diff --git a/docs/libcurl/opts/Makefile.inc b/docs/libcurl/opts/Makefile.inc
index c8edade6a..5a201fe3f 100644
--- a/docs/libcurl/opts/Makefile.inc
+++ b/docs/libcurl/opts/Makefile.inc
@@ -278,6 +278,7 @@ man_MANS =                                      \
   CURLOPT_STREAM_DEPENDS.3                      \
   CURLOPT_STREAM_DEPENDS_E.3                    \
   CURLOPT_STREAM_WEIGHT.3                       \
+  CURLOPT_SUPPRESS_CONNECT_HEADERS.3            \
   CURLOPT_TCP_FASTOPEN.3                        \
   CURLOPT_TCP_KEEPALIVE.3                       \
   CURLOPT_TCP_KEEPIDLE.3                        \
```

Tested by building with cmake. TODO for later: add install targets for manpages

**Comment by bagder** [comment]
Is that travis failure just totally bogus? I can't understand why this PR would trigger that.

**Comment by jay** [comment]
> Is that travis failure just totally bogus? I can't understand why this PR would trigger that.

I see it also. Here is the bad section:
capture

So probably a typo
~~~diff
diff --git a/docs/libcurl/opts/Makefile.am b/docs/libcurl/opts/Makefile.am
index 02623b6..cd9eada 100644
--- a/docs/libcurl/opts/Makefile.am
+++ b/docs/libcurl/opts/Makefile.am
@@ -23,7 +23,6 @@
 AUTOMAKE_OPTIONS = foreign no-dependencies
 
 include Makefile.inc
- CURLOPT_SUPPRESS_CONNECT_HEADERS.3             \
 
 man_DISTMANS = $(man_MANS:.3=.3.dist)
~~~

**Comment by Lekensteyn** [comment]
Oops, that was a merge fail. Removed that line, the other files seem OK. Attempt 2, counting on travis to do the autotools build.

**Comment by jay** [comment]
CI has passed. Before you push these upstream can you please add a line to the commit messages that reference this PR. For example Closes or Ref.

~~~
Ref: https://github.com/curl/curl/pull/1288
~~~

**Comment by Lekensteyn** [comment]
Rebased with tags added, will push when CI passed (when I am awake tomorrow).

**Comment by Lekensteyn** [comment]
Fixed in:
898b012a9 cmake: add support for building HTML and PDF docs
84a226a30 cmake: build manual pages (including curl.1)
6f6e9193d docs: split file lists into Makefile.inc

**Pull request closed without merging**
