### PR TITLE
transfer: Switch PUT to GET/HEAD on 303 redirect

### PR DESCRIPTION
**Pull request by jay**
Prior to this change if there was a 303 reply to a PUT request then
the subsequent request to respond to that redirect would also be a PUT.
It was determined that was most likely incorrect based on the language
of the RFCs. Basically 303 means "see other" resource, which implies it
is most likely not the same resource, therefore we should not try to PUT
to that different resource.

Refer to the discussion in #5237 for more information.

Fixes https://github.com/curl/curl/issues/5237
Closes #xxxx

---

In Curl_http it will override the request string to PUT when data->set.upload is true, which is why I decided to fix this issue by setting data->set.upload as false on 303.

https://github.com/curl/curl/blob/b81e0b07784dc4c1e8d0a86194b9d28776d071c0/lib/http.c#L2070-L2073

/cc @PofMagicfingers @jzakrzewski

### CODE REVIEW

**Comment by michael-o** [comment]
I'd like to hear the clarification of the HTTP WG before this gets merged.

**Comment by bagder** [comment]
I believe this seems changes matches what I read the spirit of [RFC 7231 section 6.4.4](https://tools.ietf.org/html/rfc7231#section-6.4.4) is. I do however think that this change also requires a test to verify it. I could only spot test 1332 when looking for existing tests using 303.

**Comment by jay** [comment]
@michael-o do you have an update? I would like to land this before the release next week.

**Comment by michael-o** [comment]
@jay I did not inquire anything with the HTTP WG. I expect this either you doing or @PofMagicfingers.

**Comment by PofMagicfingers** [comment]
I did send an email to the http-wg mailing list a week ago, but as I'm not a member of their mailing list my message is pending manual processing. I've had no news about it and the question is not published : 

https://lists.w3.org/Archives/Public/ietf-http-wg/2020AprJun/thread.html

**Comment by michael-o** [comment]
@PofMagicfingers You can also try the GitHub project of them. @reschke, can you help?

**Comment by reschke** [comment]
I would recommend to subscribe to the mailing list and re-post.

**Comment by PofMagicfingers** [comment]
@reschke Indeed. Reposted and it worked :
 https://lists.w3.org/Archives/Public/ietf-http-wg/2020AprJun/0044.html

Thanks!

**Comment by PofMagicfingers** [comment]
We got an answer : https://lists.w3.org/Archives/Public/ietf-http-wg/2020AprJun/0046.html

> The Location URL in a 303 is defined for _retrieval_. Only retrieval
> methods can be expected to work on it.
> 
> HTTP defined GET and HEAD for regular use, but other protocols may
> define more methods for retrieval. So there is no requirement to use
> GET/HEAD specifically. Those other protocol alternatives may be used if
> the context needs one.
> 
> 
> Amos

**Comment by jay** [comment]
Thanks

**Comment by MattyRad** [comment]
It looks like this issue was closed as a result of the [http-wg mailing list response}(https://github.com/curl/curl/pull/5248#issuecomment-617790010), but that response seems to confirm that GET/HEAD _should_ be used following a 303 redirect from a PUT request correct? Or am I misinterpreting it?

I executed PUT requests with wget and httpie and both appear use GET following a 303 redirect, for what that's worth.

**Pull request closed without merging**
