### PR TITLE
configure: do not echo most inherited `LDFLAGS` to config files

### PR DESCRIPTION
**Pull request by vszakats**
`libcurl.pc` `Libs.private` (since 8.11.0, and in `Libs` before 7.20.0)
and `curl-config` `--static-libs` (since 7.17.1, and in `Libs` between
7.7.2-7.25.0). This included all flags inherited from the environment,
in addition to those coming from dependency detections.

To avoid spilling all linker flags inherited from the environment to
the libcurl config files, this patch omits them all, except `-L`, `-F`,
`--library-path=` and `-framework` options, which are still passed.
The rationale for the exceptions is that `LIBS` is passed as-is, and
`LDFLAGS`, `LIBS` are the canonical way to pass custom libs options
to a build. `LIBS` may not work without a matching custom libpath.

This brings autotools behaviour closer to cmake, and `curl-config`
closer to `libcurl.pc`.

Follow-up to 9f56bb608ecfbb8978c6cb72a04d9e8b23162d82 #14681
Follow-up to 4c8adc8fee5e55754da3d8f8d982733a7bf3dece
Reported-by: Peter Marko
Fixes #15533

---

- [ ] `CMAKE_SHARED_LINKER_FLAGS` is included via cmake unfiltered.
  It's a raw string and isn't too fit for manual filtering.
  → Separate future patch when this can be done cleanly.

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15550 at [6e2f0d94](https://github.com/curl/curl/commit/6e2f0d94f56472c3f074017357d2b717b1a9b829):

[Test http/test_14_auth.py::TestAuth::test_14_03_digest_put_auth[0-h3] failed](https://github.com/curl/curl/actions/runs/11781861440/job/32815645569#check-step-25), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 714 failed](https://github.com/curl/curl/actions/runs/11781861436/job/32815630413#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
@petermarko Do you have any feedback on this, would it improve your use-case?

**Comment by petermarko** [comment]
I have tested these changes (rebased to 8.11.0 tag) and they resolved the issue I had with libcurl.pc.
(generated file was identical to the one from 8.10.1 and to one with my patch except one additional whitespace)
It also improved generated curl-config, which was sub-optimal before and now it looks much better.

Looking forward to seeing this PR merged.
Thanks for this awesome support!

**Comment by vszakats** [comment]
@petermarko: Thanks for your tests and feedback! This is merged now.

**Comment by diizzyy** [comment]
curl still "leaks" stuff like ```-fstack-protector-strong``` from LDFLAGS which shouldn't be in .pc file or curl-config

**Comment by vszakats** [comment]
Do you have an example? Is this leaking from the `LDFLAGS` env? Or is it coming from a dependency `pkg-config`?

**Comment by diizzyy** [comment]
It's leaking from LDFLAGS env

**Comment by vszakats** [comment]
Are you sure you re-run `autoreconf -fi` after applying the patch?

**Comment by diizzyy** [comment]
Ahh sorry, I should've mentioned that it's using CMake, latest commit in master branch

**Comment by vszakats** [comment]
Ah CMake, that was left as a TODO in the OP. Here's my attempt: #15617

**Pull request closed without merging**
