### PR TITLE
Generated test: add to make clean and fix removal from tarball

### PR DESCRIPTION
**Pull request by rikardfalkeborn**
From what I could read in the mentioned commit, it was intended to not include the generated code in the tarball (hence the dist-rule), but it doesn't work (I never bothered figure out why). The size difference of the tarball is 8kB so pretty much negligible.

Also, add it to make clean to add a simple way to remove accidental changes to the generated test.

### CODE REVIEW

**Comment by rikardfalkeborn** [comment]
Apparently I didn't check the cmake build. Before I try to fix this, is the idea of the PR sound?

I **think** it should be possible to get it to work by modifying tests/libtest/CMakeLists.txt according to the following but I haven't manage to get the Cmake build work locally.
```
 foreach(TEST_NAME ${noinst_PROGRAMS})
-  setup_test(${TEST_NAME} ${${TEST_NAME}_SOURCES})
+  if(NOT DEFINED ${${TEST_NAME}_SOURCES})
+    setup_test(${TEST_NAME} ${nodist_${TEST_NAME}_SOURCES})
+  else()
+    setup_test(${TEST_NAME} ${${TEST_NAME}_SOURCES})
+  endif()
 endforeach()
```

**Comment by bagder** [comment]
> is the idea of the PR sound?

Absolutely!

**Comment by rikardfalkeborn** [comment]
New attempt. The only difference is that in this one I tried to fix the CMake build.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
