### PR TITLE
Allow empty authority for unknown schemes

### PR DESCRIPTION
**Pull request by jfinkhaeuser**
I discussed this briefly with @bagder 

According to [RFC3986](https://tools.ietf.org/html/rfc3986) Section 3.2.2 on page 21

> If the URI scheme defines a default for host, then that default
   applies when the host subcomponent is undefined or when the
   registered name is empty (zero length).  For example, the "file" URI
   scheme is defined so that no authority, an empty host, and
   "localhost" all mean the end-user's machine, whereas the "http"
   scheme considers a missing authority or empty host invalid.

cURL implements this behaviour for the `file` scheme, but doesn't - and cannot - implement this behaviour for schemes it does not know. For such schemes, passing a new flag that permits empty authority sections is desirable.

This PR adds such a `CURLU_NO_AUTHORITY` flag, as well as test cases.

### CODE REVIEW

**Comment by jfinkhaeuser** [comment]
I've got to run - if there are tests failing, or there should be changes, I'll look at them in a few days, probably. Locally everything looked fine. And obviously if you'd like changes, I'm happy to provide them.

**Comment by bagder** [comment]
I think this is a sensible way to make the parser handle such URLs so I'm in favor of merging once things are green. Still missing: documentation of the new flag and `symbols-in-versions` update.

**Comment by jfinkhaeuser** [comment]
Makes sense - will probably get to those changes tomorrow.

**Comment by bagder** [comment]
The who building using borinssl fail due to other reasons, not your fault!

**Comment by jfinkhaeuser** [comment]
Excellent, then let me know if you want any other changes, otherwise I'm done.

**Comment by bagder** [comment]
Thanks!

**Comment by jfinkhaeuser** [comment]
No worries, glad to be of help!

**Pull request closed without merging**
