### PR TITLE
winbuild: add initial wolfSSL support

### PR DESCRIPTION
**Pull request by vszakats**
Ref: https://datagirl.xyz/posts/wolfssl_curl_w2k.html

### CODE REVIEW

**Comment by vszakats** [comment]
@jay: I don't mean to test it with wolfSSL. It probably "should" work, or if not, someone using it can report any issue. But I have no way to run this script to verify if I made a silly mistake that breaks it.

**Comment by vszakats** [comment]
But, according to AppVeyor CI, there is no trivial typo in this PR and existing builds continue to work.

**Comment by jay** [comment]
It should be confirmed working before it is added, that said it looks ok

**Comment by vszakats** [comment]
I'd say it's good as an initial implementation and straighforward enough that it "just works". The same change has been added and tested earlier in `Makefile.mk`. It's basically a copy-paste change with `include`, `lib` and `wolfssl.lib` set compared to e.g. mbedTLS.

One setting that may or may not be necessary is the `-DSIZEOF_LONG_LONG=8`. It seemed necessary a few years ago to avoid a build issue within a wolfSSL header. Also with CMake, but our CI builds never needed that.
https://github.com/curl/curl-for-win/commit/04f3a9cb624aef56cdbb5e96fca5611e5b78b5e2

Chances are good this setting is no longer needed. In any case if it's an issue, someone would likely report it.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
