### PR TITLE
cmake: sync GSS config code with other deps

### PR DESCRIPTION
**Pull request by vszakats**
- stop passing explicit libpaths via `CMAKE_SHARED_LINKER_FLAGS` and
  `CMAKE_EXE_LINKER_FLAGS`. `link_directories()` is doing that already.
- use `curl_required_libpaths()` to pass libpaths to the feature test.
  Reported-by: Daniel Engberg
  Fixes #15536
  Also fixes GSS feature detection with non-gcc/clang compilers,
  such as MSVC.
- add libpaths to `CURL_LIBPATHS`.
- move `GSS_CFLAGS`, `GSS_LDFLAGS` stringifications to FindGSS.
  To match the `CFLAGS` format returned by the rest of Find modules.
- reorder calls to match other dependencies.
- don't extend system `LDFLAGS` when FindGSS did not return any.
- ignore `LDFLAGS` when detecting GSS via `pkg-config`. `LDFLAGS` holds
  a copy of libpaths and libs in this case. Ignore those to avoid these
  duplicates making into `libcurl.pc` and `curl-config`. Also syncing
  behavior with other Find modules which also ignore raw `LDFLAGS`.
- ignore raw `LDFLAGS` coming from `krb5-config --libs`. FindGSS
  no longer returns dependency-specific `LDFLAGS` after this. Syncing
  behavior with other Find modules.
- reduce scope of checker state push/pop/set.

---

w/o whitespace: https://github.com/curl/curl/pull/15545/files?w=1

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15545 at [97a8fcd5](https://github.com/curl/curl/commit/97a8fcd53faa5c61b357fbc26cd244454e6e9340):

[Test 310 failed](https://github.com/curl/curl/actions/runs/11797128611/job/32860520011#check-step-13), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by diizzyy** [comment]
Using GSS in base, path is now missing is pc file

```
-- FindGSS krb5-config --cflags: -I/usr/include
-- FindGSS krb5-config --libs: -L/usr/lib -lgssapi -lgssapi_krb5 -lheimntlm -lkrb5 -lhx509 -lcom_err -lcrypto -lasn1 -lwind -lheimbase -lroken -lcrypt -pthread
-- Found GSS: Heimdal (found version "FreeBSD heimdal 1.1.0")
```

**Comment by vszakats** [comment]
> Using GSS in base, path is now missing is pc file
> 
> ```
> -- FindGSS krb5-config --cflags: -I/usr/include
> -- FindGSS krb5-config --libs: -L/usr/lib -lgssapi -lgssapi_krb5 -lheimntlm -lkrb5 -lhx509 -lcom_err -lcrypto -lasn1 -lwind -lheimbase -lroken -lcrypt -pthread
> -- Found GSS: Heimdal (found version "FreeBSD heimdal 1.1.0")
> ```

curl's CMake do not add system libpaths to the .pc file. As detected via `CMAKE_SYSTEM_PREFIX_PATH` with some extra logic applied.

Before this patch this logic was accidentally circumvented for libpaths detected in this single GSS detection codepath, that's why it was here before.

Is this causing any fallouts in your case?

**Comment by diizzyy** [comment]
Works for me (tm) but it's inconsistent with GNU Autotools?

**Pull request closed without merging**
