### PR TITLE
connect: add CURLOPT_IPTIMEOUT_MS

### PR DESCRIPTION
**Pull request by bagder**
Allow applications to specify the timeout per IP address connect attempt
instead of letting libcurl do its "halfing" method.

### CODE REVIEW

**Comment by jay** [comment]
All the millisecond timeouts use the prefix _MS to distinguish them from the second timeouts. I think we should continue that here, for example CURLOPT_ADDRTIMEOUT_MS, CURLOPT_ADDR_TIMEOUT_MS, CURLOPT_IPTIMEOUT_MS, CURLOPT_IP_TIMEOUT_MS, etc

**Comment by bagder** [comment]
Good point. I'll go with that!

**Comment by bagder** [comment]
Nobody spoke up in favor of this. Closing.

**Comment by bagder** [comment]
> In my case, the latest IP address connection attempts are failing only after 4-9 ms.

Since #11693, curl stops doing the "halving" when there is less than 600 milliseconds left.

**Pull request closed without merging**
