### PR TITLE
alt-svc: enable by default

### PR DESCRIPTION
**Pull request by bagder**
No longer considered experimental

Checklist:

- [X] remove `CURLALTSVC_IMMEDIATELY` as it isn't implemented
- [X] works with curl_easy_duphandle() - #5923 landed

Proposal taken to the mailing list: https://curl.haxx.se/mail/lib-2020-08/0033.html

### CODE REVIEW

**Comment by HoneyryderChuck** [comment]
does the alt-svc feature also support the HTTP/2 alt-svc frame? Does any server actually use it?

**Comment by bagder** [comment]
> does the alt-svc feature also support the HTTP/2 alt-svc frame?

No, unfortunately it doesn't.

> Does any server actually use it?

I don't know...

**Comment by xquery** [comment]
looks good to me

**Comment by bagder** [comment]
The CI jobs are in a very sorry state right now but independent of this work. Since there's no short term fix for that, I'm going to merge this PR anyway really soon.

**Pull request closed without merging**
