### PR TITLE
lib: remove exclamation marks

### PR DESCRIPTION
**Pull request by bagder**
... from infof() and failf() calls. Make them less attention seeking.

### CODE REVIEW

**Review by danielgustafsson — COMMENTED** [review]
How about this one in `lib/vquic/ngtcp2.c`?:
```c
H3BUGF(infof(data, "!!!!!!!!! cb_h3_readfunction sets EOF"));
```
It is a debug output, but unless the exclamation marks means something I think it can be improved.

**Comment by bagder** [comment]
Indeed. I'll remove them from there.

**Comment by kdudka** [comment]
This change broke pycurl's test-suite:
```
=================================== FAILURES ===================================
_____________________ ErrorTest.test_pycurl_error_libcurl ______________________
self = <tests.error_test.ErrorTest testMethod=test_pycurl_error_libcurl>
    def test_pycurl_error_libcurl(self):
        try:
            # perform without a url
>           self.curl.perform()
E           pycurl.error: (3, 'No URL set')
tests/error_test.py:20: error
During handling of the above exception, another exception occurred:
self = <tests.error_test.ErrorTest testMethod=test_pycurl_error_libcurl>
    def test_pycurl_error_libcurl(self):
        try:
            # perform without a url
            self.curl.perform()
        except pycurl.error:
            exc_type, exc = sys.exc_info()[:2]
            assert exc_type == pycurl.error
            # pycurl.error's arguments are libcurl errno and message
            self.assertEqual(2, len(exc.args))
            self.assertEqual(int, type(exc.args[0]))
            self.assertEqual(str, type(exc.args[1]))
            # unpack
            err, msg = exc.args
            self.assertEqual(pycurl.E_URL_MALFORMAT, err)
            # possibly fragile
>           self.assertEqual('No URL set!', msg)
E           AssertionError: 'No URL set!' != 'No URL set'
E           - No URL set!
E           ?           -
E           + No URL set
tests/error_test.py:32: AssertionError
______________________ ErrorTest.test_pycurl_errstr_type _______________________
self = <tests.error_test.ErrorTest testMethod=test_pycurl_errstr_type>
    def test_pycurl_errstr_type(self):
        self.assertEqual('', self.curl.errstr())
        try:
            # perform without a url
>           self.curl.perform()
E           pycurl.error: (3, 'No URL set')
tests/error_test.py:43: error
During handling of the above exception, another exception occurred:
self = <tests.error_test.ErrorTest testMethod=test_pycurl_errstr_type>
    def test_pycurl_errstr_type(self):
        self.assertEqual('', self.curl.errstr())
        try:
            # perform without a url
            self.curl.perform()
        except pycurl.error:
            # might be fragile
>           self.assertEqual('No URL set!', self.curl.errstr())
E           AssertionError: 'No URL set!' != 'No URL set'
E           - No URL set!
E           ?           -
E           + No URL set
tests/error_test.py:46: AssertionError
```

**Comment by jzakrzewski** [comment]
I'm sorry, but who tests human-readable error messages from the 3-party code?
That makes no sense and the comments in those tests confirm that the author knew it may break.

**Pull request closed without merging**
