### PR TITLE
cmake: forward `USE_LIBRTMP` option to C

### PR DESCRIPTION
**Pull request by talregev**
Define in c USE_LIBRTMP if user request it from the cmake.

### CODE REVIEW

**Comment by talregev** [comment]
Maybe add this feature to here:
https://curl.se/libcurl/c/curl_version_info.html

**Comment by bagder** [comment]
> Maybe add this feature to here: https://curl.se/libcurl/c/curl_version_info.html

Ah yes, looks like a total oversight!

**Comment by vszakats** [comment]
I'd suggest adding this line to show that `USE_LIBRTMP` is a CMake option:

```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -377,6 +377,9 @@ endif()
 
 check_function_exists(gethostname HAVE_GETHOSTNAME)
 
+option(USE_LIBRTMP "Enable librtmp" OFF)
+# TODO: Detect librtmp
+
 if(WIN32)
   list(APPEND CURL_LIBS "ws2_32" "bcrypt")
   if(USE_LIBRTMP)
```

What's missing is auto-detection and setting up the necessary libs and paths, if requested and available. Hence the TODO.

**Review by vszakats — APPROVED** [review]

**Comment by talregev** [comment]
I agree that you can add your suggestion in next PR.
Thank you for the review!

**Comment by vszakats** [comment]
Thank you @talregev, merged now.

**Pull request closed without merging**
