### PR TITLE
winbuild: remove docs from Makefiles and refer to README.md

### PR DESCRIPTION
**Pull request by bagder**
Reduce risk for conflicting docs and makes it to a single place to fix
and polish.

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by jay** [comment]
welcome.. one thing I notice now that I'm looking closer at this is ENABLE_UNICODE defaults to false but elsewhere (such as project files) defaults to true. Have any problems been reported with the UNICODE builds other than #6089?

/cc @MarcelRaad @vszakats

**Comment by vszakats** [comment]
`Makefile.m32` builds did not have support to enable `UNICODE` so far. Here's a new PR that adds it: https://github.com/curl/curl/pull/6228

Not enabled by default yet. The only reason is that I'm not sure how well the `-municode` linker option is supported accross the MinGW landscape.

**Comment by jay** [comment]
> Not enabled by default yet. The only reason is that I'm not sure how well the `-municode` linker option is supported accross the MinGW landscape.

It doesn't work in original mingw. (gcc.exe (GCC) 4.7.0)

**Comment by vszakats** [comment]
Yes, it indeed needs a "recent" release, and most likely it's a mingw-w64 feature only, unless backported to classic mingw. The original mingw is seriously outdated at this point, including its Win32 header package.

**Pull request closed without merging**
