### PR TITLE
[TESTING] runtests on Windows

### PR DESCRIPTION
**Pull request by vszakats**
---

- [ ] rebase on #15374.

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #14949 at [b0c0c9e9](https://github.com/curl/curl/commit/b0c0c9e9c74e5b097c117f536c86172329e5bb7f):

[Test 2087 failed](https://github.com/curl/curl/actions/runs/10909303707/job/30277256859#check-step-14), which has NOT been flaky recently, so **there could be a real issue in the PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
Strawberry Perl uses cleartext HTTP to download code, wow:
http://cpan.strawberryperl.com/authors/id/J/JD/JDB/Win32-Process-0.17.tar.gz

**Comment by vszakats** [comment]
This Perl module is 10KB. It needs 44s to compile from source and finish installing.

**Review by medo-mc — COMMENTED** [review]
#14949 

>

**Comment by vszakats** [comment]
Strawberry Perl doesn't give good impressions: The Perl version is outdated, the bundled gcc version is ancient and security practices are lacking. Cleartext links are also common on the homepage.

Now trying to figure out how to tell it to use a HTTPS CPAN endpoint. It first needs figuring out where the config file is. Perhaps there is canonical way to do this?

**Comment by vszakats** [comment]
Anyhow, if we don't want to install CPAN modules, Strawberry Perl should be fine for curl builds.
It does seem to use the native `TerminateProcess()` call for native-`kill()`:
https://github.com/Perl/perl5/blob/9a036659c691047471ebdc984eb8a8699dd4d793/win32/win32.c#L1317-L1345

**Comment by bagder** [comment]
> Anyhow, if we don't want to install CPAN modules, Strawberry Perl should be fine for curl builds.

I feel I'm missing something here and this PR has no description.

What is Strawberry Perl and why this work on using it?

**Comment by vszakats** [comment]
> > Anyhow, if we don't want to install CPAN modules, Strawberry Perl should be fine for curl builds.
> 
> I feel I'm missing something here and this PR has no description.

This is a PR for experimenting, there is no clear description to put there.
I'm not sure if it will matrialize into anything worthy for a non-draft PR, yet.

I'm trying to figure out when and why the external Windows tools `taskkill`
and `tasklist` (possibly also `handle64`) are used and if there is any way to 
replace them with native Perl code.

Calling external tools sometimes fail hard:
https://github.com/curl/curl/discussions/14854#discussioncomment-10664929
(also in the top post there)

It may be just a symptom, but in general, especially on Windows, probably
even more so in a hybrid env like MSYS2/Cygwin, using external calls is not
an ideal solution, prone to error cases, and heavy, inefficient.

The code for converting between Cygwin PID, Windows PID seems rather
fragile and non-trivial to understand. One reason is that Cygwin PIDs and
Windows PID look exactly the same, but incompatible. There is extra logic
in tests/servers to make them different for those processes by adding 65536
to them, and subtracting it in the runner code. But those may not be the only
places where PIDs are born, there is also `fork()`, maybe more.

> What is Strawberry Perl and why this work on using it?

curl's GHA Windows runners have at least 4 different Perl builds on them:
- Strawberry Perl
- Git for Windows Perl
- MSYS2 Perl
- Cygwin Perl (installed by us via cygwin/cygwin-install-action)

These are all Cygwin/MSYS2 builds, _except_ Strawberry Perl, which
is a native Windows Perl build, meaning it can access the native Win32 API.
Win32 API access can be useful, because it can replace external calls, or
just enable the built-in Perl `kill()` to kill curl server processes and others,
without hacks.

I imagine there could be less friction between the moving parts by using
MSYS2/Cygwin Perl for MSYS2/Cygwin curl jobs (which is already done,
and those jobs are solid), and native Perl for native Windows jobs (that
is not done, and those jobs are flaky/unstable). These combinations would
make all fragile PID conversions unnecessary.

So far it looks like that a Windows native Perl has not really been tried with
the test runner code. But I'm still looking what it'd take to make them work.

(The issue with native Perl is: `../src/curl.exe` not found.)

**Comment by vszakats** [comment]
tasklist/taskkill/handle execution stats (with tasklist calls deleted before taskkill calls):
```
                      tasklist    taskkill -f    taskkill    handle64
msys native                  0              0           0           1
msys mingw-w64            1927             90           3           1
mingw-w64 standalone       464              2           0           1
msvc                       443              0           0           1
```
(Represent trends, these are not the same build/test configurations)

It seems that `handle64` calls are never followed-up by a `taskkill` call,
suggesting a bug there?

Also there is not a whole lot of `taskkill` call, but very many `tasklist` calls.
It'd be useful to see the return value `taskkill` calls after all, or really of
these calls.

**Comment by vszakats** [comment]
Useful parts of this PR were merged via separate PRs.

What remains is solving the the running of servers with native Windows Perl, and support for parallel tests. They may not be easy patches.

The other takeaway is that `handle64` may not (or no longer) be required. I could never see it actually returning results. For now its runs are logged in detail, to be able to say more by analysing logs throughout a longer period. Or perhaps disabling it and see if flakiness worsens or remains the same.

Closing this PR without merging what remains in here.

**Pull request closed without merging**
