### PR TITLE
Support HTTPS proxy (--proxy https://). Support SOCKS+HTTP* proxy combo.

### PR DESCRIPTION
**Pull request by rousskov**
This feature was developed in 2013. Despite the death of one of the primary developers, we kept the code in sync with the official Curl releases, but failed to find the cycles for the official submission until now. The first sections below describe the two major parts of the new code (in a format suitable for a commit message) followed by usage examples and a to-do list.

### 1. HTTPS proxies:

```
An HTTPS proxy receives all transactions over an SSL/TLS connection.
Once a secure connection with the proxy is established, the user agent
uses the proxy as usual, including sending CONNECT requests to instruct
the proxy to establish a [usually secure] TCP tunnel with an origin
server. HTTPS proxies protect nearly all aspects of user-proxy
communications as opposed to HTTP proxies that receive all requests
(including CONNECT requests) in vulnerable clear text.

With HTTPS proxies, it is possible to have two concurrent _nested_
SSL/TLS sessions: the "outer" one between the user agent and the proxy
and the "inner" one between the user agent and the origin server
(through the proxy). This change adds supports for such nested sessions
as well.

A secure connection with a proxy requires its own set of the usual SSL
options (their actual descriptions differ and need polishing, see TODO):

  --proxy-cacert FILE        CA certificate to verify peer against
  --proxy-capath DIR         CA directory to verify peer against
  --proxy-cert CERT[:PASSWD] Client certificate file and password
  --proxy-cert-type TYPE     Certificate file type (DER/PEM/ENG)
  --proxy-ciphers LIST       SSL ciphers to use
  --proxy-crlfile FILE       Get a CRL list in PEM format from the file
  --proxy-insecure           Allow connections to proxies with bad certs
  --proxy-key KEY            Private key file name
  --proxy-key-type TYPE      Private key file type (DER/PEM/ENG)
  --proxy-pass PASS          Pass phrase for the private key
  --proxy-ssl-allow-beast    Allow security flaw to improve interop
  --proxy-sslv2              Use SSLv2
  --proxy-sslv3              Use SSLv3
  --proxy-tlsv1              Use TLSv1
  --proxy-tlsuser USER       TLS username
  --proxy-tlspassword STRING TLS password
  --proxy-tlsauthtype STRING TLS authentication type (default SRP)

All --proxy-foo options are independent from their --foo counterparts,
except --proxy-crlfile which defaults to --crlfile and --proxy-capath
which defaults to --capath.

Curl now also supports %{proxy_ssl_verify_result} --write-out variable,
similar to the existing %{ssl_verify_result} variable.
```

### 2. SOCKS proxy + HTTP/HTTPS proxy combination:

```
If both --socks* and --proxy options are given, Curl first connects to
the SOCKS proxy and then connects (through SOCKS) to the HTTP or HTTPS
proxy.
```

### 3. Copyright statement:

Copyright (C) 2015 The Measurement Factory, Inc.
Distributed under the terms of the Curl project itself.
Authors: Dmitry Kurochkin, Vasy Okhin, and Alex Rousskov.

### 4. Usage examples:

```
proxy='--proxy https://localhost:3129/'
ca='--proxy-cacert ssl_cert/myCA.pem'
curl $ca $proxy http://www.example.com
curl $ca $proxy https://www.example.com
curl $ca $proxy --proxytunnel https://www.example.com

socks='--socks5 127.0.0.1:1080'
curl $ca $proxy --proxytunnel $socks http://www.example.com
curl $ca $proxy --proxytunnel $socks https://www.example.com

curl --insecure --proxytunnel $ca $socks $proxy \
	ftps://user:pass@127.0.0.1/example.txt

curl --insecure --proxytunnel $ca $socks $proxy \
    --ftp-ssl ftp://user:pass@127.0.0.1/example.txt

format='OR=%{ssl_verify_result},PR=%{proxy_ssl_verify_result}\n\n';
curl --proxy-insecure -w $format $proxy https://www.example.com
```

### 5. TODO:

1. Change `--proxy-foo` option descriptions. The current approach of appending "for proxy" to the original `--foo` description does not work well in most cases.
1. Add `--proxy-foo` options to mimic `--tlsv1.0`, `--tlsv1.1`, and `--tlsv1.2` added to Curl v7.42, after the active work on this feature has stopped.
1. Finalize version-related `TBD` symbols.
1. Man page updates.

The code passes `make check` tests except test cases that sometimes fail on "slow" boxes (165, 323, and 1900-1903) and the check-easy test case (missing `CURLOPT_PIPEWAIT`). The same test cases fail in virgin master.

Please note that SSL-inside-SSL does not work with OpenSSL versions ranging from 0.9.7a to 1.0.0-beta2, inclusively, due to an OpenSSL bug.

The code has seen more than a year of light use in a few different environments.

We will do our best to address your change requests, but we do _not_ consider ourselves Curl experts, and are looking forward to finally leaving this code in more capable hands :-). Thank you for Curl!

### CODE REVIEW

**Comment by rousskov** [comment]
The information in the pull request description is that same as in pull request #268 _except_ for the last (TODO) section which has a new list of occasionally failing test cases and new notes about compatibility with older OpenSSL versions.

**Comment by bagder** [comment]
There's a pattern of code mixed with declarations in several places: "ISO C90 forbids mixed declarations and code [-Werror=pedantic]"

If you build with `./configure --enable-debug --enable-werror` you'll get some help to find a whole slew of minor mistakes.

**Comment by rousskov** [comment]
Will fix.

**Comment by rousskov** [comment]
Done. Configuring with `--enable-debug` was the key -- I have not seen any compilation warnings without that option. Sorry. The warnings are fixed now.

**Comment by bagder** [comment]
I have this merged in a local branch now. Will make a public branch out of it within soon. We need quite a lot of documentation added...

**Comment by bagder** [comment]
There's now a HTTPS-proxy branch: https://github.com/bagder/curl/tree/HTTPS-proxy where this work has been merged (and slightly edited, mostly for style). 

I'd like docs and at least some amount of tests added before merging this work to master.

**Comment by rousskov** [comment]
Thank you for making progress on this! If you need any specific changes/additions from us, please let me know, and we will start nibbling at your to-do list. Unfortunately, if you ask us to add  documentation and/or test cases, it will take us some time to deliver due to overload and unfamiliarity with Curl's test framework.

**Comment by bagder** [comment]
I'll work on adding tests. I hope to get it working with stunnel in front of the test proxy, similiar to how we do tests with HTTPS normally.

The documentation isn't that hard to do, it may be a slightly unfamiliar format but if you just compare with the current docs you'll quickly see how to write the docs.

**Comment by bagder** [comment]
Ok, I managed to get something running but I've halted the testing work to make sure I polish up the other TLS backends first to primarily build and work with the existing functionality, but then of course I would also like them to work with HTTPS proxies just like the openssl backend does.

I just pushed initial work for gnutls, but it still doesn't do proxies correctly.

**Comment by bagder** [comment]
This is too much work for me to pull through on my own as things keep developing in the master branch too and I need to give that attention as well.

**Comment by rousskov** [comment]
Sigh. Is this because I was too slow with submitting documentation additions? If not, what can we do to get this feature accepted instead of abandoned?

**Comment by bagder** [comment]
The patch must build with all existing TLS backend without any breakage - we cannot merge a patch that breaks master. I've not been able to find the time and energy for this myself and apparently neither has anyone else.

**Comment by rousskov** [comment]
If we submit changes that fix build with GnuTLS, would you be willing to reopen and commit this feature? If yes, do you require the feature to actually _work_ with GnuTLS? I hope that fixing the build would be sufficient, but want to double check before we try to fix this.

**Comment by bagder** [comment]
I already made it build with GnuTLS, but we have a bunch of more backends to fix.

**Comment by bagder** [comment]
... alternatively, we make sure the new proxy code doesn't change the old code so that the existing backend code remains building.

**Comment by bagder** [comment]
My work (on top) is in the https://github.com/bagder/curl/tree/HTTPS-proxy branch

**Comment by rousskov** [comment]
I am not sure it is practical (or even a good idea) to restrict the new code so much that other backends do not notice its addition. Unfortunately, I do not have good enough understanding of both cURL and the proxy architecture to make that call.

After seeing a [list](http://curl.haxx.se/docs/ssl-compared.html) of curl backends, I understand that this is a "large" problem. On the other hand, most of your GnuTLS changes look straightforward to me so perhaps we can make similar changes for other backends without understanding their internals. What do you think of the following plan?

1. You postpone the decision to abandon this feature for another month.
1. Factory tries to make as many cURL backend libraries build as we can within that month.
1. If, after ~30 days, you see significant progress, you will help us finish and merge the results. _You_ define what "significant progress" is (preferably now so that we can estimate whether there is a good chance we can meet your standard).

**Comment by bagder** [comment]
Thanks for keeping up the work.

The "abandonment" was only me thinking I couldn't handle this alone. If I'm not alone there's a completely different picture and we should have a much better chance to pull this through. Also, I truly never close the door for others' work: if its just good code and a good feature we will merge gladly when presented the code. You don't need to deliver within a month for that to happen, you can take as long time as you need! We (the project) won't go anywhere!

If you prefer us to keep this PR open until then, then I could indeed consider having it so, but we can also just re-open it once there's new stuff to present or we can start a new then. Either way is fine with me.

**Comment by rousskov** [comment]
I think we are more-or-less on the same page. I am worried about the total effort ahead of us, but Factory will try to fix the build with alternative backends. We will start with the POSIX ones. I will add comments to this closed pull request to track our progress in hope to minimize conflicts with your work (unless you prefer a different mechanism).

No need to re-open this pull request now. As you said, that can always be done later if needed.

**Comment by bagder** [comment]
The amount of work to get this landed is substantial, yes. That's also why I mentioned that perhaps an easier way is to implement it differently that leaves the existing (other) TLS backends functional without source edits, as if that would be possible it would make it a much smaller effort with less risk of breakage.

**Comment by rousskov** [comment]
I agree that it is probably possible to redesign the code to ease (or, to be more precise, essentially remove the need for) integration with backends. However,

1. the redesign itself requires spending significant amounts of yours or mine time, which is the most precious resource/bottleneck here (as opposed to integration work that, hopefully, can be done by junior staff), and
1. the redesign may make it more difficult/risky to _add_ support to backends (the compiler essentially tells us what to do now but if we avoid changing existing structure members, the responsibility of finding all the right integration places would fall on a human).

We are now working on integrating with NSS. I will update you once we are done. This initial integration experience may also help us estimate the total effort required (albeit NSS is probably easier to integrate than some of the other backends). I hope we can finish before master moves too far away from this branch.

**Comment by rousskov** [comment]
FYI: NSS, PolarSSL, CyaSSL, axTLS compile now. The code is going through internal review, and I hope to push it soon.

**Comment by rousskov** [comment]
I posted pull request #515 that contains build fixes for NSS, PolarSSL, CyaSSL, axTLS backends. Actual HTTPS proxying support was added to NSS only.

That pull request #515 is against your https://github.com/bagder/curl/tree/HTTPS-proxy branch, not against your master (like this pull request #305). I hope that was the right thing to do because you can just merge those fixes into your branch and proceed further without disturbing master, but please let me know if we should do something else instead.

The last item we are working on now is fixing HTTPS proxying with GnuTLS that you have reported as broken in you July 1, 2015 [comment](#issuecomment-117514436).

**Comment by bagder** [comment]
We're discussing this branch on the curl-library list now. A valid remark was made: http://curl.haxx.se/mail/lib-2015-12/0058.html

The strings set in setopt() should be added to the set.str[] array in the way we have all the other strings already, not otherplaces like the codes now. We need consistency, plus it makes cloning the handle work (easier).

**Comment by rousskov** [comment]
Will fix. BTW, to answer another question in that post, Squid (www.squid-cache.org) supports HTTPS clients (look for the htts_port option in squid.conf.documented).

**Comment by patrikhson** [comment]
Hi,

I wanted to share with you some interesting links that they gave us at the last meeting, here is the list <http://thistulynu.funplace2dance.com/xyhdawnn>

Hugs, paf@frobbit.se

**Comment by patrikhson** [comment]
Hey,

This is what I've just read and it's something really new and interesting, you can read more at <http://tholerdyshy.lookamazingnaked.net/xyxahd>

Yours sincerely, paf@frobbit.se

**Comment by fscr** [comment]
This pull request seems to have stalled. I would like to put some effort in merging this branch with master to get it into one of the next releases. Actually I already implemented this feature before discovering this branch but did not implement proxy certs etc. and was only supporting the OpenSSL backend, so this branch is much more advanced. Nevertheless I could contribute my test cases.

In addition to the HTTPS proxy support I would also like to contribute a feature allowing the import of an existing SSL session to the CURL session cache later on (as exported e.g. by _openssl s_client -sess_out session.pem -connect host:port_). OpenSSL's s_client also implements this with _-sess_in_.

Background is to have a reference implementation for an upcoming ISO specification proposal which identifies proxy clients by them resuming a TLS connection from an application protocol.

**Comment by bagder** [comment]
Hi @fscr,

Yes this branch clearly has stalled. It was never merged because it still breaks the build/functionality for a few TLS backends and we don't accept that. Not supporting specific features in specific backend is fine, but not breaking the build or existing functionality. This unfortunately makes this kind of big change a bit heavy to pull along - when the master keeps developing as well.

Support for HTTPS proxies remain high on my wish list so I'm very happy to see your interest in bringing this forward.

It sounds like a good first step would be to rebase this work onto current master and incorporate your improvements, then make sure that all the TLS backends we can try still build and work.

**Comment by rousskov** [comment]
IIRC, we have fixed all the backends as requested (at the time). See pull request #515.

**Comment by bagder** [comment]
> IIRC, we have fixed all the backends as requested

Okay cool, I missed that but that's great. Then there's "just" a matter of refreshing the work on top of the current master and we should be in a decent shape to merge it soon.

**Comment by bagder** [comment]
Since this branch is severely out-of-date with no signs of it being worked to get back on track, I'm closing this now. I would really like to see this branch get rebased and worked on again to have it merged in the master branch.

**Comment by rousskov** [comment]
Based on your last pull request #571 comment, we are waiting for the next curl release to re-re-sync the HTTPS proxy branch. I do not yet know how big that effort will be (or if there is a fixed release schedule). Any help is appreciated, of course.

**Comment by bagder** [comment]
The next curl release ships on November 2. There will not be any major changes in the TLS area before then. After the release, we have the "feature window" open for 4 weeks during which we merge features If we miss that window, it opens again 4 weeks later of the the following release. And repeat.

**Comment by rousskov** [comment]
Understood. I hope we can update the branch by November 16 and get into the first 4-week window.

**Pull request closed without merging**
