### PR TITLE
docs/TODO: Add feature request for metalink in HTTP headers

### PR DESCRIPTION
**Pull request by dustymabe**

### CODE REVIEW

**Comment by dustymabe** [comment]
If this gets merged we can close https://github.com/curl/curl/issues/728

**Comment by dustymabe** [comment]
@antbryan might be happy with this feature request :)

**Comment by antbryan** [comment]
a few people have requested it privately so I'm surprised no one has tackled it yet :)

**Comment by bagder** [comment]
thanks!

**Pull request closed without merging**
