### PR TITLE
tests/*server.pl: flush output before executing subprocess

### PR DESCRIPTION
**Pull request by mback2k**
Also avoid shell processes staying around by using exec. This may solve the random Windows CI issues.

### CODE REVIEW

**Comment by mback2k** [comment]
After a total of 5 CI runs without any AppVeyor or Azure test failing in this PR, I am quite sure this will finally fix their flakiness.

**Review by bagder — APPROVED** [review]

**Review by jay — APPROVED** [review]
The commit message needs an explanation as to why this change is necessary, and any references where it is discussed.

**Comment by mback2k** [comment]
@jay thanks, please take another look at the updated commit message.

**Comment by mback2k** [comment]
Unfortunately even this PR is experiencing some flakiness again, although it seems reduced. That is why I added another commit for testing purposes.

**Comment by mback2k** [comment]
@jay @bagder if you are fine with the first commit (content and message), I would probably go ahead and merge that already as this PR and then move the remaining flakiness testing to a new PR.

**Comment by bagder** [comment]
Works for me!

**Comment by jay** [comment]
I think it needs a reference to the issue(s) where the random CI fails are discussed, so it can be understood why it is necessary to make this change to avoid the buffering. In other words the issue that you are fixing. I'm not really opposed to this but I think that there may be some underlying issue here that we just aren't aware of that is causing these problems. That said if it is an improvement then :+1:

**Comment by mback2k** [comment]
Thanks! @jay it is hard to link to a single issue or instance of this flakiness since we have been expierencing that on Azure and AppVeyor since months now. You can see it in the test analytics of Azure quite well:
https://dev.azure.com/daniel0244/curl/_test/analytics?definitionId=1&contextType=build

Filter like this:
image
image

You will see the test failures spread quite evenly over a lot of tests (test 2100 was recently fixed by you):
image

**Pull request closed without merging**
