### PR TITLE
Rewrote HTTP status line parser

### PR DESCRIPTION
**Pull request by andydude**
Fix for https://github.com/curl/curl/issues/855

### CODE REVIEW

**Comment by jay** [comment]
Thanks but this is failing the ci, please run checksrc on the code and follow [code style](https://github.com/curl/curl/blob/master/docs/CODE_STYLE.md). Also while I think your intentions are good it would probably be easier to just add another sscanf:
~~~diff
diff --git a/lib/http.c b/lib/http.c
index 6a76b88..481a9a8 100644
--- a/lib/http.c
+++ b/lib/http.c
@@ -3306,10 +3306,21 @@ CURLcode Curl_http_readwrite_headers(struct SessionHandl
         nc = sscanf(HEADER1,
                     " HTTP/%d.%d %d",
                     &httpversion_major,
                     &conn->httpversion,
                     &k->httpcode);
+
+        if(nc == 1 && httpversion_major == 2) {
+          nc = sscanf(HEADER1, " HTTP/2 %d", &k->httpcode);
+          if(nc == 1) {
+            conn->httpversion = 0;
+            nc = 3;
+          }
+          else
+            nc = 1;
+        }
+
         if(nc==3) {
           conn->httpversion += 10 * httpversion_major;

           if(k->upgr101 == UPGR101_RECEIVED) {
             /* supposedly upgraded to http2 now */
~~~

**Comment by andydude** [comment]
The advantage of rewriting that code is that every scanf call return values are actually used, by adding another scanf, there are 3 scanf calls, and most of the data is thrown away.

**Comment by andydude** [comment]
If you want to add another scanf, that's fine. Do I have to delete this PR then?

**Comment by jay** [comment]
No, please leave it and give other people a chance to weigh in. Also regardless of what goes in Daniel said it needs a test.

**Comment by bagder** [comment]
Yeah, we need a test but as I haven't done my home work yet we don't really have a good way to do HTTP/2 tests so I think we need to fix this bug without a test for now.

I do prefer @jay's version of fix here simply because its smaller and easier to read.

**Comment by jay** [comment]
Ok. If I don't hear anything else I'll add my version tomorrow.

**Comment by bagder** [comment]
I'll probably land my first "proper" HTTP/2 test this week. Powered by the [nghttpx proxy](https://nghttp2.org).

**Comment by jay** [comment]
Andrew I landed my version in 1aa899f. Thanks for your work and report.

**Pull request closed without merging**
