### PR TITLE
make OpenSSL builds with VS2015 work again

### PR DESCRIPTION
**Pull request by sunnyap**
Can't submit the code change with original pull request  https://github.com/curl/curl/pull/1267. Hence creating new one.

### CODE REVIEW

**Comment by bagder** [comment]
You've introduced a memory leak in test 300:
~~~
 valgrind ERROR ==25874== 112 bytes in 1 blocks are definitely lost in loss record 45 of 47
==25874==    at 0x4C2AB80: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==25874==    by 0x6411DB2: CRYPTO_malloc (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==25874==    by 0x648F12E: BIO_new (in /lib/x86_64-linux-gnu/libcrypto.so.1.0.0)
==25874==    by 0x4E94352: servercert (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E9651D: ossl_connect_common (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E97265: Curl_ssl_connect_nonblocking (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E49621: https_connecting (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E4AEA2: Curl_http_connect (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E55B90: Curl_protocol_connect (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E6B05D: multi_runsingle (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E6BD02: curl_multi_perform (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x4E62957: curl_easy_perform (in /home/travis/build/curl/curl/lib/.libs/libcurl.so.4.5.0)
==25874==    by 0x40D435: operate_do (in /home/travis/build/curl/curl/src/.libs/lt-curl)
==25874==    by 0x40EB64: operate (in /home/travis/build/curl/curl/src/.libs/lt-curl)
==25874==    by 0x402C2C: main (in /home/travis/build/curl/curl/src/.libs/lt-curl)
==25874==

**Comment by bagder** [comment]
... and a style nit:
~~~
./vtls/openssl.c:668:1: warning: Trailing whitespace (TRAILINGSPACE)
  
 ^

**Comment by bagder** [comment]
This is still leaking memory in several of the travis builds, see this:

https://travis-ci.org/curl/curl/jobs/369998652#L9446

**Comment by sunnyap** [comment]
@bagder Seems test 1056 is failing, not so sure which code change is causing test 1056 failure.
https://travis-ci.org/curl/curl/jobs/373017975
test 1056...[HTTP follow redirect from IPv4 to IPv6 with scope]
1056: protocol FAILED:

**Comment by bagder** [comment]
Yeah 1056 is on the border of getting marked as flaky. I've restarted that build since that failure isn't related to your work.

**Comment by bagder** [comment]
Thanks for your hard work on this!

**Pull request closed without merging**
