### PR TITLE
Make libcurl library output name configurable

### PR DESCRIPTION
**Pull request by RLangendam**

### CODE REVIEW

**Comment by RLangendam** [comment]
The failures seem to me to be unrelated to the change, but I could be wrong. Would someone else be able to confirm that judgment or point out what should be fixed? Thanks in advance.

**Comment by jay** [comment]
Why do you want to change the basename? 

> The failures seem to me to be unrelated to the change

yes

**Comment by RLangendam** [comment]
> Why do you want to change the basename?
To avoid naming conflicts with the system-wide library, in case it is installed by other means than as part of our legacy product. In the past changes were made to a local copy of earlier CURL sources, some of which we can't avoid to port as part of upgrading this library to remain backward compatible. These changes shouldn't be contributed back, because they violate the HTTP spec.

**Comment by bagder** [comment]
I don't see any harm in accepting this.

**Comment by bagder** [comment]
Thanks!

**Comment by jzakrzewski** [comment]
Sorry for missing that but that's really not the best way of doing that as it renames the target. CMake provides properties that can be set on a target to rename the output artifact without changing the name of a target.

**Comment by bagder** [comment]
@jzakrzewski no worries. Do you think we should revert this first then to do it right or would we tweak what's already landed?

**Comment by jzakrzewski** [comment]
The change does not make much sense, so I'd revert it. Using variables for target name is in any case not a best practise...
The method I'm talking about is using the `OUTPUT_NAME` property on the `libcurl` target.

**Comment by bagder** [comment]
Reverted again in 3057c6cd736d

**Comment by RLangendam** [comment]
> The change does not make much sense, so I'd revert it. Using variables for target name is in any case not a best practise...
> The method I'm talking about is using the `OUTPUT_NAME` property on the `libcurl` target.

Thanks for pointing this out. Indeed, this is a neater approach. Before creating another PR for this I'd like to be sure it will be accepted in advance. I propose to add a new variable

    set(LIBCURL_OUTPUT_NAME libcurl CACHE STRING "Basename of the curl library")

to be used like this

```
add_library(
  ${LIB_NAME}
  OUTPUT_NAME ${LIBCURL_OUTPUT_NAME}
  ${HHEADERS} ${CSOURCES}
  )
```
Does that sound acceptable to you?

**Pull request closed without merging**
