### PR TITLE
refactor: Use more constants in tool_help.c

### PR DESCRIPTION
**Pull request by emilengler**

### CODE REVIEW

**Review by jay — COMMENTED** [review]
We don't set pointers and/or struct members const, though what is pointed to may be const. I don't believe this is formalized anywhere but that's just the way it's been (and IMO the way it should be).

**Comment by emilengler** [comment]
> We don't set pointers and/or struct members const, though what is pointed to may be const. I don't believe this is formalized anywhere but that's just the way it's been (and IMO the way it should remain).

We do!

616c30ad6768991eab4e187ad630ccbbf91ce388

**Comment by mback2k** [comment]
I think the spacing to the right side of the `*` in that commits looks weird. It should either be left or right aligned IMHO and @bagder just confirmed to me the other day via IRC that we right align in curl.

**Comment by emilengler** [comment]
> I think the spacing to the right side of the `*` in this and that commit you linked to looks weird. It should either be left or right aligned IMHO and @bagder just confirmed to me the other day via IRC that we right align in curl.

Will change it to that. Maybe we should adjust checksrc.pl?

**Comment by bagder** [comment]
Does this extensive use of `const` help in any way? Does it product noticeably better output? Does it help us to write better code? I believe the answer is no and then I don't consider it necessary.

The formatting of the code with 'const' on the right side of asterisk is always weird as that's a keyword and not a variable name and I'm not sure they should then follow the same style. (In general i'm all for fixing checksrc to validate our code is strict as possible.)

**Comment by emilengler** [comment]
> Does this extensive use of `const` help in any way? Does it produce noticeably better output? Does it help us to write better code? I believe the answer is no and then I don't consider it necessary.
> 
> 
> 
> The formatting of the code with 'const' on the right side of asterisk is always weird as that's a keyword and not a variable name and I'm not sure they should then follow the same style. (In general i'm all for fixing checksrc to validate our code is strict as possible.)

Constants offer sometimes a better performance as well as easier code maintenance.

**Comment by bagder** [comment]
> Constants offer sometimes a better performance

That's the theory and I suppose it *can* be true in some cases. Is it true in modern compilers?  Does it ever make even a measure impact in a code base like curl's?

I mean, `register` is also there in the C language to presumably help the compiler but we don't that either because it's pointless and only makes the code readability worse. Possibly even ruins performance too since it second-guesses what clever things the compiler can do.

> easier code maintenance

Really? How does a lot of consts in the code make it easier to maintain?

**Comment by emilengler** [comment]
> Really? How does a lot of consts in the code make it easier to maintain?

No accidental changes

**Comment by jzakrzewski** [comment]
I don't really know how that translates to C but in C++ it's encouraged to use const kinda by default (the language itself has it, of course, backwards) not so much for performance (although compilers do optimize on that) but for correctness.
So for me, as a C++ programmer this PR looks sensible. I'm in no position to comment on C though.

**Comment by infinnovation-dev** [comment]
With regard to parameter declarations:  In, for example
```c
void tool_help(const char * const category)
```
the second const is promising to the compiler that you are not going to assign to the parameter `category`.  But the compiler is well able to figure that out for itself.  It just adds a pointless obstacle to a future maintainer who may want to add some code such as
```c
  if(some_cond) category = "http";
```

As for struct members, e.g.:
```c
struct feat {
  const char * const name;
  const int bitmask;
};
```
The extra `const` have no effect on the generated code, since the only instance `feats` is already declared const (so in .rodata, ROMmable for embeddded systems etc.).  It just stops a future maintainer doing e.g.
```c
  struct feat tmp = feats[i];
  tmp.bitmask = 0;
```

I don't see any benefit in these changes.

**Comment by bagder** [comment]
I'm siding with the skeptics here. Mildly negative to this PR.

I think this adds code but to very little use. This is not code that typically are "changed by mistake" just because they're not `const` all the way and these added consts are not likely to change the compiler output to any notable degree - two metrics I think we should focus on when considering sprinkling more `const` in the code.

**Comment by emilengler** [comment]
Ok I'll close this then!

**Pull request closed without merging**
