### PR TITLE
Some more conn->data removals

### PR DESCRIPTION
**Pull request by monnerat**
curl->conn count down to 123

### CODE REVIEW

**Comment by bagder** [comment]
Sorry, but #6498 had some overlaps with your PR here so now when I've merged that, there's merge conflicts in this...

**Comment by monnerat** [comment]
Never mind: I'm currently tracking the CI issues of this PR (torture and w$), then will force push the new commits.

**Comment by monnerat** [comment]
The fix for torture test 2100 failing I pushed here conflicts again with b97a60f5.
Failing CI tests do not seem to be related to this PR.
I'll now resolve the conflict and then consider this PR ready for review/pull.

**Comment by bagder** [comment]
I believe my DoH fix is better for this. I tried your approach first, but the logic in hostip.c (around line 586) would need to be updated as well if we'd go your way.

And yeah, we have a lot of failing CI now that is unrelated... :cry:

**Comment by monnerat** [comment]
OK, thus I'll simply drop my doh commit.

**Comment by bagder** [comment]
Lovely, at 89 now!

**Pull request closed without merging**
