### PR TITLE
Make all public symbols curl prefixed

### LINKED ISSUE #4793: public headers use non-curl prefixed symbols
All symbols curl defines and provides in public include files/headers should be prefixed by curl or libcurl to minimize the risk of them colliding with other libraries' or applications' symbols.

This is *mostly* done already with a few exceptions (`WIN32`, `CINIT`, `CFINIT` and some of the related defines around the CINIT macro dance). This should be fixed and we should introduce a test that verifies that we maintain this situation going forward.

### PR DESCRIPTION
**Pull request by bagder**
Cleanup all symbols in public headers to be prefixed with curl or libcurl (either case) and a new test (1167) to verify that this is the case.

The biggest change is the modified enum setups in the curl.h and multi.h headers. Another benefit of cleaning them up like this is that we can avoid the "ISO cpp" check we did and needed there.

Fixes #4793

### CODE REVIEW

**Comment by jay** [comment]
This is a lot of change I would wait until the next feature window to give it some time to marinate.

**Comment by bagder** [comment]
Absolutely.

**Comment by bagder** [comment]
Ah, preprocessing the headers was a bad idea since they might bring in symbols from other header files...

**Comment by bagder** [comment]
No, it needs preprocessing so that the macros gets evaluated and comments removed. I'll instead make sure to parse the `#` (`#line`) lines and skip "external" files that way.

**Pull request closed without merging**
