### PR TITLE
Bug fix: handle [] in URLs more gracefully

### LINKED ISSUE #2044: Bug: foo[] parameters in URLs cause an error
### I did this

`$ curl "http://localhost:8000/api/some-resource?PYNO[]=ZA2134&PYNO[]=ZA2323&PYNO[]=100004232&PYNO[]=ZA1213"` (the real list of `PYNO[]` values is much longer, abbreviated example.)

### I expected the following

To get the result of the URL. 😄 

With the `-g` / `--globoff` parameter, it works as expected.

I know that the behavior we have now has been this way for _years_, but... I still consider it a bad default _personally_, since I happen to use URLs with "array parameters" from time to time. It's also something that is easily supported in web frameworks like [PHP](http://php.net/manual/en/faq.html.php#faq.html.arrays). Given the "principle of least surprise", I think it would make more sense to invert the flag so that `--globon` is opt-in, for the cases when you want to work with URL sequences and ranges.

But maybe I'm the oddball here? I don't know, if people really like it this way, we shouldn't change it. On any occurrence, this would be a candidate for 8.x rather than something that should be done right now because we shouldn't make changes like this on a minor version release to avoid confusing people.

### curl/libcurl version

```
$ curl -V
curl 7.47.1 (x86_64-apple-darwin15.3.0) libcurl/7.47.1 SecureTransport zlib/1.2.11
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
```

### operating system
macOS High Sierra.

### PR DESCRIPTION
**Pull request by perlun**
Fixes #2044.

### CODE REVIEW

**Comment by bagder** [comment]
Thank you, I'll volunteer writing a test case for it!

**Comment by bagder** [comment]
My test proved the patch wasn't really complete, so I updated it and pushed a PR as #2048 to see that the CI likes it!

**Comment by perlun** [comment]
> My test proved the patch wasn't really complete, so I updated it and pushed a PR as #2048 to see that the CI likes it!

Thanks! What was the problem btw? I did test my fix locally a bit (by running it on an URL with embedded `[]`) but only briefly; great to have CI coverage for it as well. 👍

**Comment by bagder** [comment]
if you compare your initial version with what I landed you'll see that the code (now) changes no less than three pointers. Your version skipped the '[]' all right but didn't included them in the output string. If you go back and build with your version of the code and run the new test 1290 with it, it will be quite clear to you.

**Pull request closed without merging**
