### PR TITLE
hyper: Fixxed tests 580 and 581 for the hyper backend

### PR DESCRIPTION
**Pull request by liamwarfield**
Hyper will be able to preserve header order once this PR merges:
https://github.com/hyperium/hyper/pull/2798
This commit adds a few lines setting the connection options
for this feature and enable tests 580 and 851.

Related to issue #8617

DO NOT MERGE UNTIL THE HYPER COMMIT MERGES

### CODE REVIEW

**Comment by bagder** [comment]
Nice work!

**Comment by liamwarfield** [comment]
@bagder, the hyper commit has merged. Could you please rerun the checks on this commit?

**Comment by bagder** [comment]
@liamwarfield if you rebase this branch and force-push it, it'll run all the CI again...

**Comment by liamwarfield** [comment]
Thanks.

**Comment by bagder** [comment]
The hyper build is now green! :heavy_check_mark:

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
