### PR TITLE
require a slash after the colon to be a scheme

### LINKED ISSUE #3233: a short hostname + port is not a URL scheme!
`curl: (3) URL using bad/illegal format or missing URL`
Not a false positive this time it seems :-)

_Originally posted by @MarcelRaad in https://github.com/curl/curl/pull/3223#issuecomment-435624905_

### PR DESCRIPTION
**Pull request by bagder**
... and remove test 2070 which is basically a duplicate of 203.

Fixes #3233

### CODE REVIEW

**Comment by bagder** [comment]
The debug log now says

     [00:08:52]  22:05:56.265000 == Info: curl_url_set rejected file;C:\projects\curl\tests\log\test203.txt

... so clearly:
1. There's not even a single slash, which thus makes the test wrong and the parser right to reject it. I think I need to create yet another PWD variable so that I can make a URL with one slash and then the full path to the file...
2. That's a **semicolon** after `file`! How on earth did it get there?

**Comment by MarcelRaad** [comment]
> That's a semicolon after file! How on earth did it get there?

That's probably MSYS's POSIX path conversion again, detecting `:` as a POSIX directory separator and converting it to the Windows directory separator `;`, caused by the change from using the Windows path to using the POSIX path. You can disable it with `MSYS2_ARG_CONV_EXCL=file:`.

**Comment by bagder** [comment]
Thanks @MarcelRaad !

**Comment by bagder** [comment]
This is certainly a rathole and I'm afraid this is now getting us deeper into the mingw weeds of magic trickery.

Now it instead says:

    [00:07:19]  curl: (37) Couldn't open file /c/projects/curl/tests/log/test203.txt

... which means that it parsed the URL fine - mingw didn't convert the colon in `file:` nor the leading slash following that colon. But instead it converted the entire rest of the current path to a unix-looking path with forward slashes and - most importantly - a forward slash instead of the colon after C so now our parser doesn't recognize it as a "magic windows path" and thus it tries to use it as-is and that fails since this is not a legitimate path on windows. This looks mostly like mingw craziness and not actually a curl bug anymore, although I'm not sure how to beat it over the head in the right manner to make it behave.

Trial and error via appveyor builds is mighty painful.

**Comment by MarcelRaad** [comment]
Ah, that's now because you're not using the native path from https://github.com/curl/curl/blob/20a8b7be17991530384879dcb9aa932e4b9110ec/tests/runtests.pl#L2694 but the original POSIX one, which native Windows builds cannot handle (but MinGW builds can). The path you see is the original one from runtests.pl, but before using `MSYS2_ARG_CONV_EXCL` it was converted to a native Windows path by MSYS.

What do you want the path to look like? I *think* `%FILE_PWD` does nothing because it's based on the POSIX path, which starts with a slash anyway. Maybe you want to base it on the native path instead of the POSIX path?

**Comment by bagder** [comment]
I want the path to be...
1. on windows: `file:/C:\windows\blabla`
2. on linux: `file:/home/blabla`

This would verify that we can handle file: URLs with a single slash correctly, and it needs a little special handling since that initial slash is part of the path for linux but needs to be skipped on Windows.

**Comment by MarcelRaad** [comment]
Ah, makes sense! Then you maybe want to set the new variable as late as at https://github.com/curl/curl/blob/20a8b7be17991530384879dcb9aa932e4b9110ec/tests/runtests.pl#L3121 so that you can use the updated `$pwd` for it instead of what has become `$posix_pwd` by then.

**Comment by bagder** [comment]
You mean something like this?
~~~
   $$thing =~ s/%POSIX_PWD/$posix_pwd/g;
+
+  my $file_pwd = $pwd;
+  if($file_pwd !~ /^\//) {
+      $file_pwd = "/$file_pwd";
+  }
+
   $$thing =~ s/%FILE_PWD/$file_pwd/g;

**Comment by MarcelRaad** [comment]
Yes!

**Comment by bagder** [comment]
Trying that now! (Also rebased and squashed for readability.)

**Comment by bagder** [comment]
Ah, green at last!

**Pull request closed without merging**
