### PR TITLE
Patch 9 - Remove strlen call for Curl_checkheaders and Curl_checkProxyheaders

### PR DESCRIPTION
**Pull request by HenrikHolst**
Both Curl_checkheaders and Curl_checkProxyheaders are both only called by string literals so we can use the STRCONST macro instead of calling strlen.

### CODE REVIEW

**Comment by bagder** [comment]
Oops, this now has merge conflicts. Can you rebase onto the latest and force-push?

**Comment by HenrikHolst** [comment]
The merge conflict should now be fixed AFAIK

**Comment by bagder** [comment]
Sorry, totally failed to force-push a squashed version here.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
