### PR TITLE
CI: increase '-j' when running make

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by cmeister2** [comment]
I'm not averse to the general principle, though I worry that running tests in parallel will cause interesting problems.

**Comment by bagder** [comment]
I double-checked, `make test` works fine to invoke with `-j`, the tests themselves will not run in parallel.

**Comment by mback2k** [comment]
On native shells it should be quite unproblematic, but just to mention it already: Cygwin and msys shells are known to have trouble with make parallelism.

**Comment by dfandrich** [comment]
IIRC Github actions only get 2 CPUs so going beyond that won't help much.

**Comment by andy5995** [comment]
> IIRC Github actions only get 2 CPUs so going beyond that won't help much.

Looks right

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources

Except 3 on macOS VMs

**Comment by vszakats** [comment]
In local build tests (many thousands of them) on macOS with an 4-core HT Intel CPU, `nproc` returns 8 (logical cores), yet `-j4` gives better results then `-j8`. Using `nproc` as-is for `-j` seems overoptimistic to me. Maybe taking half of it, or maxing the value at 4 could help. Though in CI's (in our free tiers at least), there is seldom more than 2 cores.

**Comment by mback2k** [comment]
We also tested -j2 on Cirrus CI (also 2 cores) before and it didn't improve the overall speed in any meaning full way. I guess the 2 cores are busy enough with the various processes spawned during an autotools-based build and context switching between them.

**Comment by andy5995** [comment]
I manually checked the difference on a couple workflows. There seemed to be a worthwhile difference.

I'll do that again soon and make a few notes here.

**Comment by bagder** [comment]
@andy5995 do you have any results/measurements on the differences you can add here to help us make a decision about this?

**Comment by andy5995** [comment]
The right column shows the results with the PR applied

The left column shows results from the workflow https://github.com/curl/curl/pull/10349

image


Here, the left column is from https://github.com/curl/curl/pull/10390

image

There's more contrast here because 'j3' is specified in the macos workflow

image

**Comment by thesamesam** [comment]
Does this affect the total build time at all across all jobs? (Do github throttle or something?)

**Comment by andy5995** [comment]
> Does this affect the total build time at all across all jobs? (Do github throttle or something?)
> 

@thesamesam I don't think so. I don't see anything about it mentioned at

https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners

or

https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration

**Pull request closed without merging**
