### PR TITLE
getinfo: reset retry_after value on initinfo fct

### PR DESCRIPTION
**Pull request by sterchelen**
- Avoid re-using retry_after value from preceding request
- Add libtest

Thanks to @joey-l-us for having see it.

ref #5661

### CODE REVIEW

**Comment by sterchelen** [comment]
First lib test for me... not sure if it the right way to do it :/

**Comment by jay** [comment]
Your test needs an xml file in tests/data. [test1909](https://github.com/curl/curl/blob/curl-7_71_1/tests/data/test1909) is already used for --retry-all-errors so you'll need to create a separate test. However you can see in that test how two server responses are sent so that may be helpful for creating your test, since it requires the same thing (I think). Also since your test uses a lib you'll need to override the tool by using the xml `<tool>` section to point to your lib. See test1910 and also [FILEFORMAT.md](https://github.com/curl/curl/blob/curl-7_71_1/tests/FILEFORMAT.md).

**Comment by sterchelen** [comment]
> Your test needs an xml file in tests/data. [test1909](https://github.com/curl/curl/blob/curl-7_71_1/tests/data/test1909) is already used for --retry-all-errors so you'll need to create a separate test. However you can see in that test how two server responses are sent so that may be helpful for creating your test, since it requires the same thing (I think). Also since your test uses a lib you'll need to override the tool by using the xml `<tool>` section to point to your lib. See test1910 and also [FILEFORMAT.md](https://github.com/curl/curl/blob/curl-7_71_1/tests/FILEFORMAT.md).

Roger that, thank you :)

**Comment by bagder** [comment]
~~~
./lib1909.c:31:13: warning: no space before equals sign (NOSPACEEQUALS)
   CURL *curl= NULL;
             ^
./lib1909.c:49:4: warning: // comment (CPPCOMMENTS)
     //Checking that retry_after is reset
    ^
checksrc: 0 errors and 2 warnings

**Comment by bagder** [comment]
Thanks!

@sterchelen: if you want extra gold points in your next PR, try use the `Reported-by:` and `Fixes` etc keywords in the commit message!

**Pull request closed without merging**
