### PR TITLE
openssl: if verifypeer is not requested, skip the CA loading

### PR DESCRIPTION
**Pull request by bagder**
It was previously done mostly to show a match/non-match in the verbose
output even when verification was not asked for. This change skips the
loading of the CA certs unless verifypeer is set to save memory and CPU.

### CODE REVIEW

**Comment by sjadhavar** [comment]
This commit is causing the problem in our application that uses libcurl.

Please see the old comment for more details on this.
https://github.com/curl/curl/pull/2290#issuecomment-378230863

IMO, we should revert this commit.

**Comment by bagder** [comment]
I think a start would be to file an issue explaining the problem.

**Comment by pschlan** [comment]
Interesting (and glad) to see this has been re-added after my previous commit has been reverted. After my PR in #2290, I've added a note in https://github.com/pschlan/curl/blob/master/docs/libcurl/opts/CURLOPT_SSL_VERIFYPEER.3#L61-L68 to document the expensive loading of the ca file despite VERIFYPEER being disabled. Should we remove this note now?

**Comment by bagder** [comment]
Oh nice catch @pschlan, yes we should. You wanna do it?

**Pull request closed without merging**
