### PR TITLE
conncache: fix several lock issues

### LINKED ISSUE #2132: Crash with libCurl 7.57.0 and CURL_LOCK_DATA_CONNECT
### I did this
I tried the new option CURLSHOPT_SHARE  with parameter  CURL_LOCK_DATA_CONNECT available in libcurl 7.57.0 according to https://curl.haxx.se/dev/release-notes.html. If I use this option I get random crashes in my application with different call stacks.

Here is an example program to reproduce the problem:
```c
#include <windows.h>
#include <iostream>
#include <tchar.h>
#include <strsafe.h>
#include <curl/curl.h>

using namespace std;

const size_t MAX_THREADS = 3;
const size_t ITERATIONS = 100;

#define CHECK_CURL(cmd) \
    if ((cmd) != CURLE_OK) \
    { \
        throw runtime_error( "Error executing: "#cmd ); \
    }

DWORD WINAPI MyThreadFunction( LPVOID lpParam );

HANDLE ghMutex;

static void ShareLockFunc( CURL* pHandle, curl_lock_data Data, curl_lock_access Access, void* pUseptr )
{
    (void)pHandle;
    (void)Data;
    (void)Access;
    (void)pUseptr;
    WaitForSingleObject(
        ghMutex,    // handle to mutex
        INFINITE );  // no time-out interval
}

static void ShareUnlockFunc( CURL* pHandle, curl_lock_data Data, void* pUseptr )
{
    (void)pHandle;
    (void)Data;
    (void)pUseptr;
    ReleaseMutex( ghMutex );
}

typedef struct MyData {
    CURLSH* pShare;
} MYDATA, *PMYDATA;

int CurlPerformGet( CURL* pHandle )
{
    CHECK_CURL( curl_easy_setopt( pHandle, CURLOPT_FOLLOWLOCATION, 1L ) );
    CHECK_CURL( curl_easy_setopt( pHandle, CURLOPT_URL, "http://127.0.0.1:3000" ) );
    CHECK_CURL( curl_easy_perform( pHandle ) );
    int StatusCode = 0;
    CHECK_CURL( curl_easy_getinfo( pHandle, CURLINFO_RESPONSE_CODE, &StatusCode ) );
    return StatusCode;
}

int _tmain()
{
    PMYDATA pDataArray[MAX_THREADS];
    DWORD   dwThreadIdArray[MAX_THREADS];
    HANDLE  hThreadArray[MAX_THREADS];

    ghMutex = CreateMutex(
        NULL,              // default security attributes
        FALSE,             // initially not owned
        NULL );            // unnamed mutex

    if (ghMutex == NULL)
    {
        printf( "CreateMutex error: %d\n", GetLastError() );
        return 1;
    }

    (void)curl_global_init( CURL_GLOBAL_ALL );

    CURLSH *pShare = curl_share_init();
    curl_share_setopt( pShare, CURLSHOPT_SHARE, CURL_LOCK_DATA_CONNECT );
    curl_share_setopt( pShare, CURLSHOPT_LOCKFUNC, ShareLockFunc );
    curl_share_setopt( pShare, CURLSHOPT_UNLOCKFUNC, ShareUnlockFunc );

    // Create MAX_THREADS worker threads.
    for (int i = 0; i < MAX_THREADS; i++)
    {
        pDataArray[i] = (PMYDATA)HeapAlloc( GetProcessHeap(), HEAP_ZERO_MEMORY,
            sizeof( MYDATA ) );

        pDataArray[i]->pShare = pShare;

        if (pDataArray[i] == NULL)
        {
            ExitProcess( 2 );
        }

        hThreadArray[i] = CreateThread(
            NULL,                   // default security attributes
            0,                      // use default stack size
            MyThreadFunction,       // thread function name
            pDataArray[i],
            0,                      // use default creation flags
            &dwThreadIdArray[i] );   // returns the thread identifier

        if (hThreadArray[i] == NULL)
        {
            cout << "Create thread failed" << endl;
            ExitProcess( 3 );
        }
    }


    WaitForMultipleObjects( MAX_THREADS, hThreadArray, TRUE, INFINITE );

    for (int i = 0; i < MAX_THREADS; i++)
    {
        CloseHandle( hThreadArray[i] );
    }

    curl_share_cleanup( pShare );
    curl_global_cleanup();

    CloseHandle( ghMutex );

    return 0;
}


DWORD WINAPI MyThreadFunction( LPVOID lpParam )
{
    PMYDATA pData = (PMYDATA)lpParam;
    CURLSH* pShare = pData->pShare;

    for (size_t i = 0; i < ITERATIONS; ++i)
    {
        CURL* pHandle = curl_easy_init();
        curl_easy_setopt( pHandle, CURLOPT_SHARE, pShare );
        cout << "Status: " << CurlPerformGet( pHandle ) << endl;
        curl_easy_cleanup( pHandle );
    }

    return 0;
}
```

As test server I used a small nodejs express server:
```js
const express = require('express');

const app = express();
let requestsCount = 0;

process.on('uncaughtException', function (err) {
    console.log("uncaught exception");
    console.log(err);
});

app.get('/', (req, res) => {
    console.log(req.headers);
    requestsCount += 1;
    setTimeout(() => {
        res.send('Hello World!');
    }, 1);
});

app.use(function (err, req, res, next) {
    console.error("Express error catched!", err);
    res.status(500).send("Error happened");
});


const server = app.listen(3000, () => {
    console.log('Example app listening on port 3000!');
});

let count = 0;
server.on("connection", (socket) => {
    console.log(`GOT CONNECTION ${count++} on addr: ${JSON.stringify(socket.address())}`);
    socket.setKeepAlive(true);
});

const interval = 2000;
setInterval(() => {
    console.log(`got ${requestsCount} requests in ${interval/1000}s`);
    requestsCount = 0;
}, interval);
```

Here are the callstacks from the crashes I got:

Callstack 1 (this one happens most of the time) with the following error: 
`free(ca->ai_addr); // Read access violation, ca is 0x1`

~~~
libcurl.dll!Curl_freeaddrinfo(Curl_addrinfo * cahead) Line 84      C
libcurl.dll!freednsentry(void * freethis) Line 744               C
libcurl.dll!hash_element_dtor(void * user, void * element) Line 41          C
libcurl.dll!Curl_llist_remove(curl_llist * list, curl_llist_element * e, void * user) Line 130 C
libcurl.dll!Curl_llist_destroy(curl_llist * list, void * user) Line 138               C
libcurl.dll!Curl_hash_destroy(curl_hash * h) Line 213      C
libcurl.dll!curl_multi_cleanup(Curl_multi * multi) Line 2237         C
libcurl.dll!Curl_close(Curl_easy * data) Line 327                C
HttpClientDirectTest2.exe!MyThreadFunction(void * lpParam) Line 134 C++
~~~

Callstack 2 (less frequently than callstack 1 in my tests) with the following error: 
`diff = Curl_timediff(node->time, now); // node is 0`

~~~
libcurl.dll!add_next_timeout(curltime now, Curl_multi * multi, Curl_easy * d) Line 2483               C
libcurl.dll!curl_multi_perform(Curl_multi * multi, int * running_handles) Line 2187         C
libcurl.dll!easy_transfer(Curl_multi * multi) Line 683      C
libcurl.dll!easy_perform(Curl_easy * data, bool events) Line 769               C
libcurl.dll!curl_easy_perform(Curl_easy * data) Line 788               C
HttpClientDirectTest2.exe!CurlPerformGet(void * pHandle) Line 49         C++
HttpClientDirectTest2.exe!MyThreadFunction(void * lpParam) Line 133 C++
~~~

### I expected the following
I expected that the application does not crash and that the sockets are reused so that the operating system does not report 300 WAITING sockets after the application has finished.

### curl/libcurl version
7.57.0

### operating system
Windows 7 Enterprise Service Pack 1

### PR DESCRIPTION
**Pull request by bagder**
If the lock is released before the dealings with the bundle is over, it may
have changed by another thread in the mean time.

Fixes #2132

### CODE REVIEW

**Comment by bagder** [comment]
forgot to update test case 1554 but since it didn't completely fix the issue...

**Comment by ahodesuka** [comment]
When using the share interface with `CURL_LOCK_DATA_CONNECT` with these changes and a multi interface that sets `CURLMOPT_MAX_TOTAL_CONNECTIONS` breaks after a few connections get disconnected, but using `CURLMOPT_MAX_HOST_CONNECTIONS` instead gives me the desired result.

The following gives me the expected behaviour with `CURLMOPT_MAX_TOTAL_CONNECTIONS` set.
```
diff --git a/lib/conncache.c b/lib/conncache.c
index cacfa9abc..860603300 100644
--- a/lib/conncache.c
+++ b/lib/conncache.c
@@ -462,6 +462,10 @@ Curl_conncache_extract_oldest(struct Curl_easy *data)
   if(conn_candidate) {
     /* remove it to prevent another thread from nicking it */
     bundle_remove_conn(bundle_candidate, conn_candidate);
+    bc->num_conn--;
+    DEBUGF(infof(conn_candidate->data, "The cache now contains %"
+                CURL_FORMAT_CURL_OFF_TU " members\n",
+                (curl_off_t) bc->num_conn));
   }
   CONN_UNLOCK(data);

```

**Comment by bagder** [comment]
@ahodesuka oh yes, thanks. Since I modified that function to *extract* the connection from the cache, it needs to decrease the counter storing the amount of connections in it. I'm adopting that!

**Comment by jay** [comment]
I'm getting a consistent crash but I don't know what's causing it (specifically). I'm using your most recent changes and the repro from #2132 but I changed the `MAX_THREADS` to `MAXIMUM_WAIT_OBJECTS` (64) and `ITERATIONS` to 10000 to give it a workout. After 5 seconds it will crash and always in the same place (based on 20 runs) in transfer.c:
https://github.com/curl/curl/blob/62c07b5743490ce373910f469abc8cdc759bec2b/lib/transfer.c#L454-L463
~~~
First-chance exception at 0x609f86dd (libcurld.dll) in shared_connection_cache_crash.exe: 0xC0000005: Access violation reading location 0xddddde1d.
Unhandled exception at 0x609f86dd (libcurld.dll) in shared_connection_cache_crash.exe: 0xC0000005: Access violation reading location 0xddddde1d.
~~~
`conn->handler` is 0xdddddddd (freed heap). From [the looks of it](https://user-images.githubusercontent.com/965580/33596326-51026a8e-d969-11e7-923e-24937d0ee14e.png) conn has some invalid elements but it appears data is valid

**Comment by bagder** [comment]
I modified my own example to now fetch 4KB from a local HTTP server from 67 threads, each iterating 10000 loops. This also reproduces a crash now. I'll make sure this works before I ask for more tests.

**Comment by bagder** [comment]
This no longer crashes my aggressive test application.

**Comment by jay** [comment]
> This no longer crashes my aggressive test application.

Since the conn cache changes have been applied I've been running the reporter's repro for 2 days at 64 threads at 10000 iterations with _CRTDBG_CHECK_ALWAYS_DF (check memory at every allocation and free) which drastically slows things down but also prevents running out of local ports (otherwise connections start to fail because tons are in TIME_WAIT). Everything ok, all connections successful.

**Pull request closed without merging**
