### PR TITLE
curl: Add --retry-connrefused

### PR DESCRIPTION
**Pull request by gnawhleinad**
to consider ECONNREFUSED as a transient error.

/cc: @andrewgaul (because https://github.com/curl/curl/issues/1036)
## 

Any suggestions on a `tests/` addition for this change?

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by jay** [comment]
~~~
     --retry-connrefused  Consider "connection refused" a transient error
~~~
I think that could be misinterpreted, if you use it just as --retry-connrefused it doesn't work, so I think it should be adjusted
~~~
     --retry-connrefused  Retry on connection refused (use with --retry)
~~~

**Comment by jay** [comment]
> --retry-connrefused Retry on connection refused (use with --retry)

I changed the wording to that since there were no objections, landed in 4bda3e0.

**Comment by mlovic** [comment]
I haven't been able to get this to work. The docs mention that it needs to be used with `--retry`, so I've tried

    curl --retry-connrefused --retry 5 https://google.com

with variations in argument order but I just get

    curl: (48) An unknown option was passed in to libcurl

Am I using this right?

**Pull request closed without merging**
