### PR TITLE
scripts/completion.pl: parse all opts

### PR DESCRIPTION
**Pull request by tumd**
For tab-completion it may be preferable to include all the available options.

### CODE REVIEW

**Review by bagder — APPROVED** [review]
Good catch, makes sense!

**Comment by bagder** [comment]
Thanks!

**Comment by EdiDD** [comment]
Hi.
There is almost no bash completion after upgrade to 7.74.0-1.1, only this:
--data         --fail         --help         --include      --output       --remote-name  --silent       --upload-file  --user         --user-agent   --verbose      --version

**Comment by bagder** [comment]
> after upgrade to 7.74.0-1.1

That sounds like a Debian version. The script `scripts/completion.pl` we have is not shipped by Debian in the curl package.

The Debian package `bash-completion` seems to rather be based on this project: https://github.com/scop/bash-completion which has their curl completions here: https://github.com/scop/bash-completion/blob/master/completions/curl

**Comment by EdiDD** [comment]
@bagder thanks for your suggestion. Seems you are right. There is an old curl completion script in bash-completion package from debian testing repo.

**Pull request closed without merging**
