### PR TITLE
doc: tag eprt as FTP

### PR DESCRIPTION
**Pull request by jsoref**
This matches:
https://github.com/curl/curl/blob/bc035f5c9dc4e0387a615d2cc5914f37a90be1e2/docs/cmdline-opts/disable-epsv.d#L6

### CODE REVIEW

**Review by bagder — COMMENTED** [review]
Why? The tooling adds this by itself in the generated man page already...

**Comment by jsoref** [comment]
Because a sibling file has the same annotation:

https://github.com/curl/curl/blob/bc035f5c9dc4e0387a615d2cc5914f37a90be1e2/docs/cmdline-opts/disable-epsv.d#L6

**Comment by jsoref** [comment]
I was reading the files in the directory linearly and building a model of how they worked.

**Comment by bagder** [comment]
see d896184c9, it was used wrongly there... I then conclude this change isn't necessary.

**Comment by jsoref** [comment]
50/50 coin toss, I tossed wrong 🙂

**Pull request closed without merging**
