### PR TITLE
doh: fix bugs on big-endian machines

### PR DESCRIPTION
**Pull request by mkauf**
This fixes the same problem as #3091 , with a slightly different approach. I developed this before I saw #3091.. now you can choose one :)

### CODE REVIEW

**Comment by jay** [comment]
As always thanks for the effort but in my opinion the way @bagder wrote it is cleaner, and so I would like to see that one land.

**Comment by bagder** [comment]
Yeah, I think it was good to get rid of a whole bunch of bitshifts too the way my approach did.

**Comment by mkauf** [comment]
OK, so please go ahead with #3091.

**Comment by bagder** [comment]
Thanks anyway @mkauf !

**Pull request closed without merging**
