### PR TITLE
Implemented gsasl version info in curl_version_info struct

### PR DESCRIPTION
**Pull request by MortenMacFly**
As a follow-up to the discussion on the libcurl mailing list I've implemented the ability to obtain the gsasl version info from the curl_version_info struct as it is done with the other third party libs, too.
Rationale: Ability to structure and format version info e.g. on a GUI an not relay on the long, unformatted string from curl_version() method.

### CODE REVIEW

**Comment by bagder** [comment]
The new symbol needs to be added to `docs/libcurl/symbols-in-versions` to make test 1119 pass!

**Comment by MortenMacFly** [comment]
> Thanks!
> The new symbol needs to be added to `docs/libcurl/symbols-in-versions` to make test 1119 pass!

Ah, OK - I understand. The question is: What version should I add? The reference version (7.76.0) or the upcoming - which is either 7.76.1 or 7.77.0?

Sorry for maybe asking stupid questions, I am new to this. :-)

**Comment by bagder** [comment]
We'll count this as a change, so it will not be merged for 7.76.1. We should plan to get it into 7.77.0

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
