### PR TITLE
docs: add code visualization action & markdown 

### PR DESCRIPTION
**Pull request by sterchelen**
To explore visually the code hierarchy and help newcomers to see how the code
is structured.

---
The github's office of the CTO (octo) has created a tool to fingerprint
a codebase to see its structure.
Here is the link to the project https://octo.github.com/projects/repo-visualization
Here is the link to the interactive visualization https://octo-repo-visualization.vercel.app/?repo=curl%2Fcurl

### CODE REVIEW

**Comment by sterchelen** [comment]
See how it looks like --> https://github.com/sterchelen/curl/blob/diagram/ci/docs/CODE_VISUALIZATION.md

**Comment by dfandrich** [comment]
Reminds me of the gource visualization tool: https://youtu.be/Un73TaG3reg

**Comment by bagder** [comment]
It's a cool visualization, yes, but does it actually help anyone not already somewhat familiar with the source? I'm not convinced this helps...

**Comment by sterchelen** [comment]
> It's a cool visualization, yes, but does it actually help anyone not already somewhat familiar with the source? I'm not convinced this helps...

Speaking as a visual guy, it helps me to see how the code is structured, that we have a **LOT** of unit tests as well as the documentations.
But after your feedback, I am not sure that it really deserves a github action, as the svg is not interactive as this [one](https://octo-repo-visualization.vercel.app/?repo=curl%2Fcurl).
Maybe we could just add the visualization link? Create a code visualization section in our doc? wdyt?

**Comment by bagder** [comment]
I see what you mean. It could be an interesting way to document the source tree layout. The "image nature" of it makes it a bit hard for user who'd read it in a file in the docs/ directory though. Do you think we should instead move it to the "everything curl" book's chapter on the [source code layout](https://everything.curl.dev/source/layout)?

We could then probably be satisfied by regenerating the image every now and then to keep up with changes.

**Comment by sterchelen** [comment]
> The "image nature" of it makes it a bit hard for user who'd read it in a file in the docs/ directory though

Yep, you convinced me with this argument. The book sounds a better place 👍🏼.
Then, let's close this PR.

**Pull request closed without merging**
