### PR TITLE
CI: build examples for additional code verification

### PR DESCRIPTION
**Pull request by mback2k**
Some CIs already build them, let's do it on more of them.

Follow up to #7690
Replaces #7591

### CODE REVIEW

**Comment by mback2k** [comment]
Is Circle CI actually running for PRs? I can't find it in the listing below or am I just blind?

**Comment by mback2k** [comment]
Quoting @jay from https://github.com/curl/curl/pull/7591#issuecomment-903308993 for further discussion:

> > do you have any idea why the examples using `fprintf` cannot compile on the failed Azure DevOps builds?
> 
> It looks like warnings are treated as errors but I don't know why it's an error for just the examples. I found [this post](https://curl-library.cool.haxx.narkive.com/QL3dOZrx/warning-iso-c-does-not-support-the-i64-ms-printf-length-modifier) from you many years ago, and maybe we can get around it with -Wno-pedantic-ms-format

Thanks. I just checked and found that `-Wno-pedantic-ms-format` is actually being used to build the examples. The error message is also a little different this time:

```
2021-10-29T20:45:35.3132082Z depbase=`echo anyauthput.o | sed 's|[^/]*$|.deps/&|;s|\.o$||'`;\
2021-10-29T20:45:35.3137364Z i686-w64-mingw32-gcc -DHAVE_CONFIG_H   -I../../include -DCURL_NO_OLDIES  -isystem C:/msys64/mingw32/include -isystem C:/msys64/mingw32/include -isystem C:/msys64/mingw32/include  -Werror-implicit-function-declaration -g -O0 -pedantic -Wall -W -Wpointer-arith -Wwrite-strings -Wunused -Wshadow -Winline -Wnested-externs -Wmissing-declarations -Wmissing-prototypes -Wno-long-long -Wbad-function-cast -Wfloat-equal -Wno-multichar -Wsign-compare -Wundef -Wno-format-nonliteral -Wendif-labels -Wstrict-prototypes -Wdeclaration-after-statement -Wold-style-definition -Wstrict-aliasing=3 -Wcast-align -Wtype-limits -Wold-style-declaration -Wmissing-parameter-type -Wempty-body -Wclobbered -Wignored-qualifiers -Wconversion -Wno-sign-conversion -Wvla -ftree-vrp -Wno-pedantic-ms-format -Wdouble-promotion -Wformat=2 -Warray-bounds=2 -Wshift-negative-value -Wshift-overflow=2 -Wnull-dereference -fdelete-null-pointer-checks -Wduplicated-cond -Wunused-const-variable -Wduplicated-branches -Wrestrict -Walloc-zero -Wformat-overflow=2 -Wformat-truncation=2 -Wimplicit-fallthrough=4 -Wno-system-headers -Wenum-conversion -Werror -pedantic-errors -MT anyauthput.o -MD -MP -MF $depbase.Tpo -c -o anyauthput.o anyauthput.c &&\
2021-10-29T20:45:35.3148223Z mv -f $depbase.Tpo $depbase.Po
```
```
2021-10-29T20:45:36.3328869Z anyauthput.c: In function 'read_callback':
2021-10-29T20:45:36.3329906Z anyauthput.c:93:19: error: ISO C does not support the 'I' printf flag [-Werror=format=]
2021-10-29T20:45:36.3330688Z    93 |   fprintf(stderr, "*** We read %" CURL_FORMAT_CURL_OFF_T
2021-10-29T20:45:36.3331692Z       |                   ^~~~~~~~~~~~~~~
2021-10-29T20:45:36.3332535Z anyauthput.c:93:19: error: format '%d' expects argument of type 'int', but argument 3 has type 'curl_off_t' {aka 'long long int'} [-Werror=format=]
2021-10-29T20:45:36.3334204Z In file included from ../../include/curl/curl.h:35,
2021-10-29T20:45:36.3334847Z                  from anyauthput.c:32:
2021-10-29T20:45:36.3335536Z ../../include/curl/system.h:199:42: note: format string is defined here
2021-10-29T20:45:36.3336240Z   199 | #  define CURL_FORMAT_CURL_OFF_T     "I64d"
2021-10-29T20:45:36.3949522Z cc1.exe: all warnings being treated as errors
2021-10-29T20:45:36.4188318Z make[2]: *** [Makefile:1813: anyauthput.o] Error 1
2021-10-29T20:45:36.4189142Z make[2]: *** Waiting for unfinished jobs....
2021-10-29T20:45:36.6744255Z make[2]: Leaving directory '/c/__w/1/s/docs/examples'
2021-10-29T20:45:36.6756852Z make[1]: *** [Makefile:1928: check-am] Error 2
2021-10-29T20:45:36.6759935Z make[1]: Leaving directory '/c/__w/1/s/docs/examples'
2021-10-29T20:45:36.6848015Z make: *** [Makefile:1741: examples] Error 2
2021-10-29T20:45:36.7881488Z ##[error]Cmd.exe exited with code '2'.
2021-10-29T20:45:36.8831887Z ##[section]Finishing: compile
```
So the error message mentions `'%d'` , but then points to a definition of `CURL_FORMAT_CURL_OFF_T` as `"I64d"`.

I think something is off with how the typedef's are done if used from the examples. This looks like a mismatch to me.

**Comment by mback2k** [comment]
Another interesting find: the error message does not appear in the Cirrus Windows builds which are using the same Docker images as the Azure Windows builds, therefore use the identical toolchain. The only difference is that the Cirrus Windows builds are release and not debug builds.

**Comment by jay** [comment]
This looks like #6079, which was solved by ignoring `-Wformat`. If it's a bug in gcc 10 then one of us should report it. I don't have mingw-w64 gcc 10 but I just tried mingw-w64 gcc 9 and I don't get the error unless I exclude `-Wno-pedantic-ms-format`.

**Comment by mback2k** [comment]
Thanks @jay. Let's see what happens if I put the same workaround into the examples, although I am still wondering why the Cirrus CI builds are not affected without it.

It also looks like this is mostly affecting external code, because curl internal code mostly uses the `curlx_*` versions of `printf*`. For example `tool_writeout.c` uses curlx as a workaround while `tool_filetime.c` uses @bagder pragma-based workaround. I guess a follow up PR could be to make `tool_filetime.c` also use curlx instead, right?

**Comment by mback2k** [comment]
Regarding the follow up PR mentioned above. I just [created a draft](https://github.com/curl/curl/pull/7941) one, since the pragma is now obsolete due to #6535.

**Comment by mback2k** [comment]
@bagder I don't have the time now, but you may wanna investigate this error that shows up in AppVeyor for master and this PR:
```
3>c:\projects\curl\src\tool_operate.c(889) : error C2220: warning treated as error - no 'object' file generated
3>c:\projects\curl\src\tool_operate.c(889) : warning C4701: potentially uninitialized local variable 'per' use
```

**Comment by mback2k** [comment]
@bagder please confirm with another approval if you are fine with adding the pragma to the relevant examples, thanks.

**Review by bagder — COMMENTED** [review]
I think the added pragma lines are unfortunate since the examples are meant to contains as little "extra fluff" as possible. I assume you haven't figured out any other way to work around the problems you get without them? Can we remove/change the printf lines instead?

**Comment by mback2k** [comment]
@bagder I tried to update the relevant `print`f lines by using `unsigned long` instead of `curl_off_t`.

**Comment by mback2k** [comment]
Rebased again after @bagder simplified `progressfunc.c` with e75bc3ae3ff695d51350d9eeb20742ad0abcf8c3.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
