### PR TITLE
Minor script cleanups

### PR DESCRIPTION
**Pull request by a1346054**

### CODE REVIEW

**Comment by bagder** [comment]
I think the style changes for the shell scripts are unnecessary. I don't think they increase readability.

**Comment by a1346054** [comment]
I'm taking advice from http://mywiki.wooledge.org/BashFAQ/082 and https://github.com/koalaman/shellcheck/wiki/SC2006 as well as other places.

**Comment by bagder** [comment]
I still don't agree with the code style commits and I think you should've done them in a separate PR as they're not the same change. I will go ahead and merge the shebang-fixes.

**Comment by a1346054** [comment]
I reworked the patches to make fewer changes https://github.com/a1346054/curl/tree/fixes

I would appreciate any review feedback on how to proceed, whether I should make a new PR or leave things as they are.

**Pull request closed without merging**
