### PR TITLE
tls13-ciphers.d: mention it is only for OpenSSL >= 1.1.1 [ci skip]

### LINKED ISSUE #3938: Clarify setting TLS 1.3 ciphers using different backends
### I did this

#2607 added [CURLOPT_TLS13_CIPHERS](https://curl.haxx.se/libcurl/c/CURLOPT_TLS13_CIPHERS.html) and [--tls13-ciphers](https://curl.haxx.se/docs/manpage.html#--tls13-ciphers). They're documented as setting TLS 1.3 cipher suites, though the lib option shows in AVAILABILITY that "OpenSSL >= 1.1.1" and the option only works when SSLSUPP_TLS13_CIPHERSUITES which is only enabled for OpenSSL.

### I expected the following

I find this confusing. I figured based on the docs and [SSL Ciphers](https://curl.haxx.se/docs/ssl-ciphers.html) we had a separate option to set TLS 1.3 ciphers only to discover that that only applies only to OpenSSL, and [other backends](https://github.com/curl/curl/pull/3916#discussion_r286798498) use regular --ciphers?

/cc @kdudka @tomato42

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Jay Satiro
Fixes #3938

### CODE REVIEW

**Comment by jay** [comment]
I think it's still confusing. I have pushed some suggestions, I'm not particularly committed to them but I want you to have a better idea of what I mean.

**Comment by bagder** [comment]
Why is this confusing?

**Comment by jay** [comment]
> Why (or perhaps how) is this confusing?

The usage is what's confusing, not what you added here. That is why I suggested clarify the lib and tool options:
~~~
This option is currently used only when curl is built to use OpenSSL 1.1.1 or
later. If you are using a different SSL backend you can try setting TLS 1.3
cipher suites by using the XXXXXX option.
~~~

 and the shorthelp:
~~~
     --ciphers <list of ciphers> SSL ciphers to use
     --proxy-ciphers <list> SSL ciphers to use for proxy
     --proxy-tls13-ciphers <list> TLS 1.3 ciphersuites for proxy (OpenSSL)
     --tls13-ciphers <list> TLS 1.3 ciphersuites (OpenSSL)
~~~

However on second thought I think it's still an inconvenience to users to keep track of that. Perhaps we abandon this and do what I suggested in the issue and take whatever is set in TLS 1.3 ciphers and concatenate it into regular ciphers for those backends that take a cipher list but do not take a separate cipher list for TLS 1.3 (or in other words the TLS 1.3 ciphers are allowed in the regular cipher list).

/cc @kdudka

**Comment by bagder** [comment]
> take whatever is set in TLS 1.3 ciphers and concatenate it into regular ciphers for those backends that take a cipher list but do not take a separate cipher list for TLS 1.3

That could certainly work. I'm not sure we gain much though. The cipher suite names/lists are already backend specific so I don't think these two separate options will cause much problems in reality.

**Comment by kdudka** [comment]
> The cipher suite names/lists are already backend specific so I don't think these two separate options will cause much problems in reality.

I agree with Daniel on this.

@tomato42 Do you think that we should handle the `--tls13-ciphers` option for other TLS backends, too?  Or is it fine to keep the option OpenSSL-specific?

**Comment by tomato42** [comment]
r+ on the PR

@kdudka 
> Do you think that we should handle the --tls13-ciphers option for other TLS backends, too? Or is it fine to keep the option OpenSSL-specific?

AFAIK, only OpenSSL does something like this - it's not how NSS works, it's not how GnuTLS works, it's not how Go TLS works. So yes, I think this option should remain openssl specific.

**Pull request closed without merging**
