### PR TITLE
pytest: include curl version string and python platform in log

### PR DESCRIPTION
**Pull request by vszakats**
For the Test Clutch matrix.

https://testclutch.curl.se/static/reports/feature-matrix.html

### CODE REVIEW

**Comment by vszakats** [comment]
macOS jobs are broken since Homebrew upgraded to OpenSSL 3.4.0 (from 3.3.x) in the last 15 hours.
It fails when generating certificates.

**Comment by icing** [comment]
> macOS jobs are broken since Homebrew upgraded to OpenSSL 3.4.0 (from 3.3.x) in the last ~10 hours. It fails when generating certificates.

the build-cert steps fails for me locally on macOS also. My system openssl is 3.3.6.

**Comment by dfandrich** [comment]
Analysis of PR #15470 at [40b6898d](https://github.com/curl/curl/commit/40b6898d01b9607743c81409a61454eabb791e41):

[Test 1452 failed](https://github.com/curl/curl/actions/runs/11629235760/job/32385871165#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by icing** [comment]
@vszakats : libressl (which is behind macOS `openssl` command) now requres a `.srl` file for a CA. If we add a file `EdelCurlRoot-ca.srl` that just contains a hexnumber line like:

```
34566D
```
 it will work. It updates the file whenever it generates a certificate.

**Comment by vszakats** [comment]
@icing: Indeed, I'm trying the `-CAcreateserial` approach here: #15471 

(what's unclear is why the fallout now. It seems LibreSSL always required that option, we always stripped the Homebrew OpenSSL and must have been using LibreSSL all along, and there was no OS update between these jobs. Hopefully the added `openssl version` log will help with this in the future.)

**Review by dfandrich — APPROVED** [review]
The only thing left missing on the features table is the host architecture, and we can get that with #15256. But maybe it's better to just add the equivalent to pytest_report_header() which means essentially just printing platform.platform(), or perhaps a more structured version.

**Comment by vszakats** [comment]
> The only thing left missing on the features table is the host architecture, and we can get that with #15256. But maybe it's better to just add the equivalent to pytest_report_header() which means essentially just printing platform.platform(), or perhaps a more structured version.

`platform.platform()` sounds good, but there is `buildinfo.host.cpu`, is there an issue with it?

**Comment by dfandrich** [comment]
If that comes from autoconf (at least), the host info isn't always the same as
the build info and doesn't always reflect the machine it's running on, which is
what "arch" means on Test Clutch. See
https://www.gnu.org/software/autoconf/manual/autoconf-2.72/html_node/Specifying-Target-Triplets.html

**Comment by vszakats** [comment]
Ah ok, I didn't know. We could try to emulate what [CMake is doing](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_SYSTEM_PROCESSOR.html), but `platform.platform()` will no doubt be simpler. Making an attempt in this PR.

**Comment by vszakats** [comment]
```
============================= test session starts ==============================
platform linux -- Python 3.12.3, pytest-8.3.3, pluggy-1.5.0 -- /usr/bin/python3
cachedir: .pytest_cache
Testing curl 8.11.0-DEV
  platform: Linux-6.8.0-1015-azure-x86_64-with-glibc2.39
  curl: Version: curl 8.11.0-DEV (x86_64-pc-linux-gnu) libcurl/8.11.0-DEV BearSSL zlib/1.3 brotli/1.1.0 zstd/1.5.5 libpsl/0.21.2 nghttp2/1.59.0 OpenLDAP/2.6.7
[...]
```

**Review by dfandrich — APPROVED** [review]

**Comment by vszakats** [comment]
Merged via 25025419c9c32bb5c59b97b7381678917a590d20. (GH missed running triggers on push?)

**Pull request closed without merging**
