### PR TITLE
GHA/windows: build uwp tests with MSVC

### PR DESCRIPTION
**Pull request by talregev**
build uwp tests

### CODE REVIEW

**Comment by vszakats** [comment]
We have an UWP build for tests, with mingw. Is there anything new that an MSVC variant brings here?

**Comment by talregev** [comment]
> We have an UWP build for tests, with mingw. Is there anything new that an MSVC variant brings here?

You can say that mingw also compile openssl, so why we need to compile with msvc. When cmake generate for msvc it generate with solution files and compile with visual studio c++ compiler and not gcc.
I don't know what happened in uwp with vcpkg vs uwp on mingw

**Comment by vszakats** [comment]
Yeah, but in case of tests, the code compiled is totally the same, except maybe 2 lines. We also cannot run tests with UWP, so the value is already low. OpenSSL is on the other end of this spectrum.

**Comment by talregev** [comment]
I think it not add time overall, because with compile the uwp is shorter then other tests that in parallel.

Let me know if you want me to close this PR.

**Comment by talregev** [comment]
> Yeah, but in case of tests, the code compiled is totally the same, except maybe 2 lines. We also cannot run tests with UWP, so the value is already low. OpenSSL is on the other end of this spectrum.

code is the same with different compiler maybe.

**Comment by talregev** [comment]
I think this explains the difference 
https://stackoverflow.com/questions/12909139/can-windows-store-applications-be-built-with-mingw

**Comment by vszakats** [comment]
> https://stackoverflow.com/questions/12909139/can-windows-store-applications-be-built-with-mingw

The accepted answer is saying that mingw-w64 is capable of creating UWP apps. Which is what we use already.
The advantage of mingw-w64 that it supports cross builds, allowing testing without a Windows env.

Building the tests once is sufficient to ensure the code isn't regressing IMO. Perhaps even that is a waste: There was no sign anybody ever attempted to build tests for UWP, let alone run them, they have been broken till I fixed them a month ago: 998b17ea7f0a4aecaa39c15d0e6f9ece110a41e1.

**Comment by talregev** [comment]
Thank you for your time to read my comments.
As I understand when compile uwp with mingw and vcpkg we are using different compilers: gcc and msvc.
Even if it the same code, different compiler are respond and give different warning / errors. 
I can give you 2 examples: 
1. when I compile tests in msvc one test is not compile due the warning that it give. Even it was the same code that was compile with mingw. 
2. You still compile the same code with gcc and clang compiler, even if the same code, as it can give different warning and errors as I describe above. 

So my conclusion is that compile uwp with msvc it not give you overread  of time testing overall, and also can detected potentials errors when compile it with msvc.

**Comment by vszakats** [comment]
I still can't see the value in this. Judging by the reports and feedback, it doesn't seem there is a whole lot of people interested to compile and run tests (or curl even) under UWP. As I mentioned most of curl didn't compile for UWP for years.

We already compile curl with both mingw and msvc extensively, so what may be interesting here, is the tiny, UWP-specific branches. They are in lib3026 and 3 more files. The patterns used there are also used in lib/tool, that we build already, and some stub code.

This suggests that the existing coverage is sufficient.

**Comment by talregev** [comment]
ok. Thank you for your time for review. I will close this PR.

**Pull request closed without merging**
