### PR TITLE
Allow disabling of more features

### PR DESCRIPTION
**Pull request by bagder**
This is a patch set that
1. Makes the #ifdefs for features disable more code that isn't used
2. Adds more defines to disable more specific features if desired (not all yet available via easy configure options)
3. Adjusts tool code to be able to run with a libcurl built with features disabled
4. The API/ABI is maintained but will return errors for disabled features.

### CODE REVIEW

**Comment by bagder** [comment]
Blah, silly me. It broke because it relies on something like #3846 so I'll get that fixed and landed first, then fixup this branch again and push a fix.

**Comment by bagder** [comment]
I'm having a hard time figuring out why the windows CI builds fail like this, so I'm more or less bisecting in the separate branch [bagder/ci](https://github.com/curl/curl/tree/bagder/ci). I might then land some of the commits piecemeal instead once proven to pass the CI.

**Comment by MarcelRaad** [comment]
Ah, here is the PR is was looking for. Did you forget a "Closes" line? These are in master now and broke the HTTP-only AppVeyor tests.

**Comment by bagder** [comment]
Only some of them are in master, the ones I (wrongly apparently) thought didn't break master...

**Pull request closed without merging**
