### PR TITLE
tool_cb_hdr: allow --remote-header-name for all http responses

### PR DESCRIPTION
**Pull request by jay**
- Use the content-disposition filename (server-specified filename) for non-2xx responses.

For example, a server may send a content-disposition filename header with a redirect reply (3xx) but not with the final response (2xx). Without this change curl would ignore the server's specified filename and continue to use the filename extracted from the user-specified URL.

This is a partial revert of 75d79a44, which limited content-disposition and etag header processing to 2xx response codes. There's no explanation for why that was done.

Reported-by: Morgan Willcock

Fixes https://github.com/curl/curl/issues/13302
Closes #xxxx

### CODE REVIEW

**Comment by jay** [comment]
This looks like a lot of change but it's almost all whitespace change. Add `w=1` to the URL query to suppress the whitespace changes https://github.com/curl/curl/pull/13303/files?w=1

**Comment by bagder** [comment]
> There's no explanation for why that was done.

It was made to make curl more careful about when to use data in response headers. It should probably allow 3xx as well as 2xx. Not convinced about 1xx, 4xx and 5xx.

**Comment by jay** [comment]
> It was made to make curl more careful about when to use data in response headers. It should probably allow 3xx as well as 2xx. Not convinced about 1xx, 4xx and 5xx.

The RFC doesn't limit it though I struggle to think of why a server would want to send a filename for those responses.

**Comment by bagder** [comment]
> I struggle to think of why a server would want to send a filename for those responses.

Right. Hence this precaution: it seems unlikely and surprising to get the header for the other ranges, so it seems safer to not parse it then.

**Comment by jay** [comment]
I don't think it is safer just limiting.

**Comment by jay** [comment]
Does anyone else have an opinion on this

**Comment by jay** [comment]
Closing in favor of #13484

**Pull request closed without merging**
