### PR TITLE
GHA/windows: Change to specific hash vcpkg

### PR DESCRIPTION
**Pull request by talregev**
Change to specific hash vcpkg

### CODE REVIEW

**Comment by vszakats** [comment]
As discussed earlier, I don't think it's good for the CI to depend on the tip of a live package manager repo.
This may fix this specific case, but it will introduce constant variance in every CI run.

**Comment by talregev** [comment]
> As discussed earlier, I don't think it's good for the CI to depend on the tip of a live package manager repo. This may fix this specific case, but it will introduce constant variance in every CI run.

It will not living on the tip of a live package manager repo.
I will change it to the custom hash.

**Comment by talregev** [comment]
> It also add 9 minutes to each job run?

Not really. it take only less than 2 min on each run. I downgrade the timeout to be 3 to be safe.

**Comment by vszakats** [comment]
This has been discussed not long ago. I still don't think that curl's CI is the correct place to debug vcpkg issues for dependencies.

Ref: f99c08dba40307c07341013ff5f71fa8e3464ffc #14090.

**Comment by talregev** [comment]
> This has been discussed not long ago. I still don't think that curl's CI is the correct place to debug vcpkg issues in dependencies.
> 
> Ref: [f99c08d](https://github.com/curl/curl/commit/f99c08dba40307c07341013ff5f71fa8e3464ffc) #14090.

ok. I can remove the logs.
Should I keep this PR?

**Comment by vszakats** [comment]
I think it's also not an improvement to roll our own vcpkg repo hash. It introduces a regular maintenance task and who is to tell which hash is good and in sync with the changing `windows-latest` image? Plus the overhead. I don't this solution helps us.

**Comment by talregev** [comment]
ok.

**Pull request closed without merging**
