### PR TITLE
CI/cirrus: remove superfluous double-quotes and sudo

### PR DESCRIPTION
**Pull request by mback2k**
Follow up to #9565 and #9677

### CODE REVIEW

**Comment by mback2k** [comment]
@pheiduck I don't think sudo is required for the build and test steps after all. I will only be needed for the install step.

**Comment by pheiduck** [comment]
@mback2k As far as I know we used it to parse the `TFLAGS` to test step, but I think it is unnecessary since it is a variable.
We can remove it also on build step.

**Comment by mback2k** [comment]
There is no sudo command to escalate privileges required for build or test steps, just for the install step it is needed.

You had sudo there before, we added just the -E to it with: https://github.com/curl/curl/commit/4896a8d59cfd792cafa790ec16effe7e97fe8a26

Now I am removing it completely and therefore the environment variables are present anyway.

**Comment by mback2k** [comment]
@pheiduck do you have an idea why "macOS arm64 libssh2" is failing here?

**Comment by pheiduck** [comment]
The output say this:
`Warning: Couldn't find a known_hosts file!`

**Comment by pheiduck** [comment]
@mback2k maybe openssh from homebrew will help not sure that the latest version is shipped on macOS 13.

**Comment by mback2k** [comment]
@pheiduck tried the openssh server from Homebrew, but unfortunately that does not seem to help.

I would guess that libssh2 is not modern enough, so the problem is the other way around.

**Comment by pheiduck** [comment]
@mback2k than we can drop this task until libssh2 works w/ M1 Chip.

**Comment by mback2k** [comment]
I think I found a solution, let's see what the CI will say.

**Pull request closed without merging**
