### PR TITLE
memory: ensure to check allocation results

### PR DESCRIPTION
**Pull request by danielgustafsson**
The result of a memory allocation should always be checked, as we may run under memory pressure where even a small allocation can fail. This adds checking and error handling to a few cases where the allocation wasn't checked for success. Also bumps the copyright years on affected files.

This is based on manual static analysis/code reading, no live bugs have been observed.

### CODE REVIEW

**Comment by jay** [comment]
you don't need this pattern if(foo)free(foo) just free(foo). also the second one i think the lock needs to be freed as well and for that you do need if(foo)NXMutexFree(foo)

**Comment by danielgustafsson** [comment]
> you don't need this pattern if(foo)free(foo) just free(foo). 

Right, I was mainly following the style of the surrounding code there, to make the flow easier to read.

>also the second one i think the lock needs to be freed as well and for that you do need if(foo)NXMutexFree(foo)

Nice catch, have pushed a fixup commit with this.

**Comment by danielgustafsson** [comment]
Pulled in the related `strdup()` fix from #3078, will squash these three commits into one before pushing.

**Comment by jay** [comment]
> Right, I was mainly following the style of the surrounding code there, to make the flow easier to read.

There is no need for a conditional there, just free(foo) is fine. Other than that LGTM

**Pull request closed without merging**
