### PR TITLE
HTTP/2 buffer/pausedata and outpu flush fix.

### PR DESCRIPTION
**Pull request by icing**
* do not process pending input data when copying pausedata to the caller
 * return CURLE_AGAIN if the output buffer could not be completely written out.

Refs #10525.

### CODE REVIEW

**Comment by eworm-de** [comment]
Your commit message has a typo. 😜

**Comment by eworm-de** [comment]
With this change applied on top of `7.88.0` I can no longer reproduce this issue.
Thanks a lot for investigating and fixing!

**Comment by eworm-de** [comment]
The first commit still causes trouble... Will try with the second one tomorrow.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
