### PR TITLE
travis: use go master

### PR DESCRIPTION
**Pull request by bagder**
... as the boringssl builds needs a very recent version

### CODE REVIEW

**Comment by bagder** [comment]
I just can't figure out how to get a go 1.13 package and use it. I give up. I'll now switch to try to download a binary package and use that, and try to make the install directory cached so that it doesn't have to get redone on every build.

**Comment by jay** [comment]
I can't find the doc to back it up but I've seen it done elsewhere in a separate section so I'm trying that

**Comment by bagder** [comment]
I tried those `go` things too first but failed.

**Comment by jay** [comment]
Looks like @ghedo did as well, I stumbled on an old pr of his last night which tried the same thing. Support got back to me this morning and said we can install a specific version as a [secondary language](https://docs.travis-ci.com/user/customizing-the-build/#installing-a-second-programming-language) so I'm going to try that.

**Comment by bagder** [comment]
It worked! (and I ignore the other reds)

**Pull request closed without merging**
