### PR TITLE
tests: enable test 1117 on hyper.

### PR DESCRIPTION
**Pull request by nnethercote**
Because it works.

### CODE REVIEW

**Comment by nnethercote** [comment]
At least, it works on my machine. Let's see what CI says?

**Comment by nnethercote** [comment]
CI fails. When built with `--enable-debug`, this debug assertion is triggered:
```
curl: transfer.c:1275: Curl_single_getsock: Assertion `conn->writesockfd != -1' failed.
```
I was testing locally without `--enable-debug`.

It's interesting that the assertion failing doesn't seem to actually matter.

**Comment by bagder** [comment]
`conn->writesockfd` is meant to contain a file descriptor to send data to. This assert is in a block checked when the transfer is marked for *sending* and yet the sending socket is `CURL_SOCKET_BAD`. That seems unexpected.

**Comment by nnethercote** [comment]
@bagder: With vanilla curl we never even execute that `DEBUGASSERT`, because `data->req.keepon` is always 1 (`KEEP_RECV`), for all 48 calls to `Curl_single_getsock` that occur in test 1117.

With curl+hyper the 17th call to `Curl_single_getsock` has `data->req.keepon` of 3 (`KEEP_RECV|KEEP_SEND`). Where does that `KEEP_SEND` come from? From the `exp100` stuff at the top of `Curl_hyper_stream`.

I tried simply commenting out the `k->keepon |= KEEP_SEND;` line in `Curl_hyper_stream`. That fixed test 1117 and didn't cause any new test failures(!)  I'm guessing that's probably not the right solution, but maybe it's a useful pointer; it definitely seems to be a problem with the exp100 handling.

**Pull request closed without merging**
