### PR TITLE
GHA: longer timeouts for torture tests

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by vszakats** [comment]
Is this meant to fix the two torture fallouts in the recent days?

Those have all the properties of hangs/busyloops, so lengthening the
job time isn't going to help.

As commented here, they started with a specific PR/commit:
https://github.com/curl/curl/pull/15283

**Comment by bagder** [comment]
#15322 probably negates the need for this

**Comment by bagder** [comment]
> As commented here

Next time, please make an issue - I missed that comment.

**Comment by dfandrich** [comment]
Analysis of PR #15320 at [1071ed29](https://github.com/curl/curl/commit/1071ed29a3cb747279addc8fbf0b6f5a7fd55d5d):

[Test http/test_19_shutdown.py::TestShutdown::test_19_02_check_shutdown[0-h2] failed](https://github.com/curl/curl/actions/runs/11385007133/job/31673970605#check-step-49), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 1452 failed](https://github.com/curl/curl/actions/runs/11385007161/job/31673969210#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 3207 failed](https://github.com/curl/curl/actions/runs/11385007163/job/31673963953#check-step-14), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by bagder** [comment]
discard this

**Comment by vszakats** [comment]
> > As commented here
> 
> Next time, please make an issue - I missed that comment.

I will, sorry!

**Pull request closed without merging**
