### PR TITLE
tool_setopt: for builds with disabled-proxy, skip all proxy setopts()

### LINKED ISSUE #3926: --disable-proxy build causes tests failing
### I did this

As seen in this autobuild:
https://curl.haxx.se/dev/log.cgi?id=20190522044629-2216

```
./configure --enable-threaded-resolver --disable-pthreads --enable-debug --enable-warnings --enable-curldebug --enable-optimize --enable-static --disable-shared --enable-http --disable-ftp --disable-file --disable-ldap --disable-ldaps --disable-rtsp --disable-dict --disable-telnet --disable-tftp --disable-pop3 --disable-imap --disable-smb --disable-smtp --disable-gopher --disable-manual --disable-libcurl-option --enable-ipv6 --enable-sspi --disable-cookies --without-zlib --without-libpsl --without-libmetalink --without-libssh2 --without-librtmp --without-winidn --without-libidn2 --without-nghttp2 --without-zsh-functions-dir --without-brotli --disable-proxy --disable-crypto-auth --with-ssl && make && cd tests && ./runtests.pl -a -p -v 19 20 1084 1085 1247 1260 1263 1264 1281 1291 2075 2080
```

### I expected the following

The tests to succeed. Instead, they failed with `curl: (48) An unknown option was passed in to libcurl`. The unknown option was always 10254 (`CURLOPT_PROXY_SSLCERT`).

### curl/libcurl version

https://github.com/curl/curl/commit/a57e4786b710b51fe463420f36f1d2a61a029f36

### operating system

MSYS2 on Windows 10 using MinGW-w64

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Marcel Raad
Fixes #3926

@MarcelRaad, due to the excessive amount of proxy options I opted to a slightly different take on handling them when building without proxy support (to avoid a bazillion of separate #ifdefs). I hope this approach works for your case? Consider this a first shot and a discussion starter.

### CODE REVIEW

**Comment by bagder** [comment]
Ah right. Gotta take another think on this.

**Comment by bagder** [comment]
Okay, new take that should work independently of `--disable-libcurl-option`. If this works, we could probably move all the options to this concept and clear out #ifdefs from tool_operate.c

**Comment by MarcelRaad** [comment]
After moving the new code out of the `CURL_DISABLE_LIBCURL_OPTION` #ifdefs to be able to compile and link, I get a new compiler warning as tool_formparse.h seems not to be self-contained:
```
In file included from tool_setopt.h:26,
                 from tool_setopt.c:24:
tool_formparse.h:64:22: warning: 'struct OperationConfig' declared inside parameter list will not be visible outside of this definition or declaration
```

After that, the tests still fail :-( I'll take another look later.

**Comment by bagder** [comment]
Sorry for being lazy. Let me offer a fixup...

**Comment by bagder** [comment]
Okay, this version was compiled with and without this disable options and seem to work for me!

**Comment by bagder** [comment]
I have a more complete solution in the works as well, but I'll still land this first independently of that once the CI seems to be happy with it, so that we mend the regression first.

**Pull request closed without merging**
