### PR TITLE
autotools: allow unix sockets on Windows

### PR DESCRIPTION
**Pull request by vszakats**
Fixes: https://github.com/curl/curl-for-win/blob/73a070d96fd906fdee929e2f1f00a9149fb39239/curl-autotools.sh#L44-L47

Closes #9688

Cleaner patch w/o whitespace changes: https://github.com/curl/curl/pull/9688/files?w=1

### CODE REVIEW

**Comment by bagder** [comment]
> Also: Surely this can be done more elegantly for someone better versed in autotools.

Why does it need this Windows adjustment at all? Is that not merely a problem with an include file? The struct field it checks for is used for Windows as well in `lib/connect.c`.

**Comment by vszakats** [comment]
On native Windows there is never a `sys/un.h` header, so the check fails consistently.

**Comment by vszakats** [comment]
There is a complex detection logic inside `lib/curl_setup.h` already. That could be duplicated inside `configure.am`, but that seems (to me) less elegant and certainly more fragile/maintenance-heavy.

**Comment by vszakats** [comment]
After fixing the `configure` `Features:` line, tests are green. (except some unrelated-looking issues)

**Pull request closed without merging**
