### PR TITLE
mime: latch last read callback status.

### LINKED ISSUE #4813: CURL_READFUNC_ABORT is lost if returned in a middle of transfer
### I did this
	I'm uploading multipart form data (large stream) to server.
        I'm doing it by using curl_easy_perform() in thread1 with specified CURLOPT_READFUNCTION
       CURLOPT_READDATA, CURLOPT_WRITEDATA, CURLOPT_NOPROGRESS =0.
in a middle of transfer want to cancel transfer. so i return in my callback function to CURL specified
CURL_READFUNC_ABORT value.

### I expected the following
expect to see immediately aborted transfer but libcurl *REPEATEDLY* call again and again my callback function and doesn't stop!
### curl/libcurl version
7.68.0

### operating system
VS2015 Windows 8.1.

after debugging i find out some strange behaviour in mime.c function 
readback_part() calling sz = read_part_content(part, buffer, bufsize);
we are returning in sz CURL_READFUNC_ABORT value , stepping next switch

      switch(sz) {
      case 0:
        mimesetstate(&part->state, MIMESTATE_END, NULL);
        /* Try sparing open file descriptors. */
        if(part->kind == MIMEKIND_FILE && part->fp) {
          fclose(part->fp);
          part->fp = NULL;
        }
        /* FALLTHROUGH */
      case CURL_READFUNC_ABORT:
      case CURL_READFUNC_PAUSE:
      case READ_ERROR:
        return cursize? cursize: sz;
      }

here i see random non zero 'cursize' values (is it bytes transfered already before we abort?)
and cursize is not zero it will don't return (losing) proper CURL_READFUNC_ABORT to upper levels of callstack.
it's sounds something simular to old 2011 bug . (see git repo commit 840eff44f2).
transfer isn't stopped and hung  in curl_easy_perform()

### PR DESCRIPTION
**Pull request by monnerat**
This prevents calling again a mime read callback after it has returned a special status.
A small sequence has been added to `curl_easy_pause`() to properly resume an active paused mime structure.
New tests 670-673 check form/mime unpausing. 

Fixes #4813

### CODE REVIEW

**Comment by jay** [comment]
Change the test global variables to be static. I can't submit it as a single comment for some reason, github keeps trying to turn it into a review.

**Comment by jay** [comment]
Change the test global variables to be static. I can't submit it as a single comment for some reason, github keeps trying to turn it into a review.

**Comment by jay** [comment]
Change the test global variables to be static. I can't submit it as a single comment for some reason, github keeps trying to turn it into a review.

**Comment by monnerat** [comment]
> Change the test global variables to be static.

I've seen this and already updated it locally.
I still have to resolve the non-existence of `alarm()`/`SIGALRM` on W$ before pushing a fixup.
I'll probably disable the tests using them on this platform. Do you have an idea how to do it? There's no platform test feature.

**Comment by jay** [comment]
Yup that won't work in Windows and I wouldn't do it anyway. I suggest unpausing from CURLOPT_PROGRESSFUNCTION as described in [curl_easy_pause](https://curl.haxx.se/libcurl/c/curl_easy_pause.html).

**Comment by bagder** [comment]
Does it also fix #4813 ?

**Comment by bagder** [comment]
Note how test 670 and 671 fail torture tests.

**Comment by monnerat** [comment]
@jay 
> Yup that won't work in Windows and I wouldn't do it anyway.

That works very well in a single-threaded program. It's a pity W$ does not have it.
> I suggest unpausing from CURLOPT_PROGRESSFUNCTION as described in curl_easy_pause.

Thanks for the hint. I will try this approach.

@bagder 

> Does it also fix #4813 ?

Yes, as noted in the commit message.

> Note how test 670 and 671 fail torture tests.

Thanks for the "heads up". It was effectively a double `curl_mime_free`() call.

**Comment by monnerat** [comment]
The CI failures are not related to this PR and MrdUkk [confirmed](https://github.com/curl/curl/issues/4826#issuecomment-578773859) it resolves his problems. Unless you want to review the commits, I consider it as ready for merge.

**Comment by monnerat** [comment]
@bagder: maybe it's time to merge this. Remember I can't do it myself anymore...

**Comment by bagder** [comment]
Thanks!

**Comment by bagder** [comment]
Reopened since we had to revert the merge due to frequent test 670 hangs.

**Comment by bagder** [comment]
@monnerat, if you rebase this branch on the current master, I figure we'll see the problems in here too

**Comment by monnerat** [comment]
Test 670-673 hang, as well as 1533 and 1540 because curl_easy_pause() is broken since commit fa0216b294af4c7113a9040ca65eefc7fc18ac1c.
Do I open a new issue for that ?

**Comment by bagder** [comment]
Yes, because I need "broken" qualified as no existing tests say it is...

**Comment by monnerat** [comment]
The problem is: after commit fa0216b294af4c7113a9040ca65eefc7fc18ac1c, `data->state.drain` is incremented each time `curl_easy_pause`() is called for unpausing, even if this operation does not change any flag.
If you call `curl_easy_pause`() more often than perform, `data->state.drain` never steps down to zero and the normal operations do not resume.
Test 670-673 do that: they unpause repeatedly in the loop. Even the CURLOPT_XFERINFOFUNCTION callback is called at least as many time as the perform code in non-multi mode.
Thus these tests can have a dual purpose: their original one and the general unpausing functionality.
I think the `curl_easy_pause`() code should be changed to check what flags are really changed before executing "auxiliary" tasks. Would you welcome a new commit in this direction ? Do you need a new issue for that ?
In the meantime, I can change the `lib670.c` program to include a timeout...

**Comment by jay** [comment]
If that commit is a problem my vote is revert it before putting in a fix. drain is just hard to do properly and we're close to a release.

**Comment by bagder** [comment]
I don't mind reverting breaking commits, but I would prefer if we then could properly identify the issue with existing code or recipes, not because a pending PR has a problem with existing code. It seems backwards.

> data->state.drain is incremented each time curl_easy_pause() is called for unpausing, even if this operation does not change any flag.

What do you mean "does not change any flag" ? Unpausing a connection changes flags and we cannot in fact be totally sure if we can read new data from the transfer, which is why we increase the drain counter. To make sure we do a read from there.

> If you call curl_easy_pause() more often than perform, data->state.drain never steps down to zero and the normal operations do not resume.

That seems so, yes, but it also seems like a very peculiar use case?

>  I think the curl_easy_pause() code should be changed to check what flags are really changed before executing "auxiliary" tasks. Would you welcome a new commit in this direction ? Do you need a new issue for that ?

You mean checking that it actually changed from paused to unpaused in either direction? That sounds like a fair improvement, but it also makes me wonder why you'd do that so often in a new test case?

**Comment by bagder** [comment]
if `curl_easy_pause()` is called and it doesn't actually change the pause state, it should probably be made a complete no-op.

**Comment by bagder** [comment]
But also: a drain++ will make the transfer to try to read/write, that should not cause an error. It could possibly make us try to do that too often, but that should "just" become a performance problem.

**Comment by monnerat** [comment]
> You mean checking that it actually changed from paused to unpaused in either direction? That sounds like a fair improvement, but it also makes me wonder why you'd do that so often in a new test case?

The test simply does something like:
```
function xferinfo()
{
  if elapsed time > 2 seconds
    unpause()
}
```
without checking if the pause is active or not.

> But also: a drain++ will make the transfer to try to read/write, that should not cause an error. It could possibly make us try to do that too often, but that should "just" become a performance problem.

This makes me think there might be another problem, something in the `drain--` side that causes the `Curl_mime_read`() function call to be bypassed while `drain` is not zero. I'm not too familiar with this part of the code so I have to investigate more deeply.

**Comment by monnerat** [comment]
> This makes me think there might be another problem...

I think I've found it. In transfer.c:
- assume (line 1203) `conn->cselect_bits == 0`, then `select_res = 0`
- line 1222, `select_res = CURL_CSELECT_IN` if `drain` is non zero.
- line 1226, `Curl_socket_check`() is not called because `select_res != 0`. This does not let a chance to set bit `CURL_CSELECT_OUT`.
- line 1247, `CURL_CSELECT_OUT` is not set thus output (`readwrite_upload`) is skipped.

This occurs as long as `drain` is not zero.

Moving the `drain` test after the select would probably fix this.

**Comment by monnerat** [comment]
Prepended a commit fixing the drain semaphore consumer.
Introduced an unpause timeout in tests 670-673.
Simplified curl_formget as #5012 
Now let's see new checks results...

**Comment by bagder** [comment]
> Prepended a commit fixing the drain semaphore consumer

That sounds like it's actually independent from the mime work of this PR, right? If you agree, then can you file a separate PR for just that to handle separately and merge before this?

**Comment by monnerat** [comment]
> That sounds like it's actually independent from the mime work of this PR, right?

Yes it is. But this fixes the problem with tests 670-671 so it should be applied before e3a5c1f390614933d52b55a843c5d666106b3370

**Comment by monnerat** [comment]
> can you file a separate PR for just that ?

Done: PR #5042

**Comment by monnerat** [comment]
Rebasing once again to resolve new tests name conflicts :-(

**Comment by bagder** [comment]
Thanks!

**Comment by monnerat** [comment]
Thanks to you for merge!

**Pull request closed without merging**
