### PR TITLE
use openssl's built in verify path as fallback

### PR DESCRIPTION
**Pull request by lnussel**
adds the configure option as requested in #175

### CODE REVIEW

**Comment by lnussel** [comment]
I have no idea what that windows failure is about

**Comment by gvanem** [comment]
@lnussel error C2020: 'connecting_state': 'struct' member redefinition

You mean the:
```
'connecting_state': 'struct' member redefinition
```

Seems like both `USE_SCHANNEL` and another SSL define is set. Hard to see which. 
But IMHO `urldata.h` (or some other .h-file) should have tests and an `#error` for such a case.

**Comment by lnussel** [comment]
but that is unrelated to my change, right?

**Comment by gvanem** [comment]
@lnussel but that is unrelated to my change, right?

Probably. According to the AppVeyour, some error in Win-build [5 days ago](https://ci.appveyor.com/project/bagder/curl/history). Before your change?

**Comment by bagder** [comment]
I hear lots of other projects having problems with using openssl's default paths anyway since they are often not set correctly. Can you help us understand when exactly this feature will make an actual difference/improvement to users of libcurl?

**Comment by lnussel** [comment]
well, if 3rd parties bundle curl and want to build it in a way to be as independent as possible from weird issues in random operating systems then this change is not useful indeed. It is useful for Linux distributions though that know that their openssl resp gnutls is configured properly. That's why I added the explicit configure switch as requested.

**Comment by bagder** [comment]
Agreed. I mean to merge this immediately after the pending patch release.

**Comment by bagder** [comment]
thanks!

**Pull request closed without merging**
