### PR TITLE
CMake: Respect BUILD_SHARED_LIBS

### PR DESCRIPTION
**Pull request by ruslo**
Use standard CMake variable BUILD_SHARED_LIBS instead of introducing
custom option CURL_STATICLIB.

### CODE REVIEW

**Comment by jzakrzewski** [comment]
I am not sure about this (even though I actually prefer using standard ways of doing things) because it inverts the default we had. I feel that
* most of people want dynamic libs
* building and using static libs is more involved

But the CMake documentation says: "This variable is often added to projects as an OPTION so that each user of a project can decide if they want to build the project using shared or static libraries." 
If it would be an OPTION, we could probably have it defaulted to ON.

**Comment by ruslo** [comment]
> because it inverts the default we had

`option` added, by default shared library will be build.

**Comment by snikulov** [comment]
@ruslo Appveyour should also be updated not to use [CURL_STATICLIB](https://github.com/curl/curl/blob/master/appveyor.yml#L69)

**Comment by ruslo** [comment]
> CURL_STATICLIB is not really "introduced" by this code. The define is used and known by the public curl/curl.h header. See

@bagder C++ part is not affected by this change, `CURL_SHATICLIB` still defined by `curl_config.h` header, see `configure_file` step:

```cmake
if(BUILD_SHARED_LIBS)
  set(CURL_STATICLIB NO)
else()
  set(CURL_STATICLIB YES)
endif()

# Use:
# * CURL_STATICLIB
 configure_file(curl_config.h.cmake
   ${CMAKE_CURRENT_BINARY_DIR}/curl_config.h)
```

**Comment by snikulov** [comment]
LGTM 👍

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
