### PR TITLE
getinfo: CURLINFO_POSTTRANSFER_TIME_T

### PR DESCRIPTION
**Pull request by alexsn**
Returns the time, in microseconds, from the start until the last byte is sent by libcurl (i.e. the request is sent off).

Note that I've used `timerid->TIMER_POSTRANSFER` as it was defined but unused.

### CODE REVIEW

**Comment by alexsn** [comment]
See discussion [here](https://github.com/curl/curl/discussions/14184), note that I'm missing documentation which I'll add once this PR is accepted.

**Comment by alexsn** [comment]
@bagder are you ok with this change? If so I'll update the docs to reflect this PR.

**Comment by bagder** [comment]
This PR still breaks a lot of tests.

**Comment by alexsn** [comment]
@bagder - Most tests are now passing. I still see a failure in 1541 on 'Linux / AM hyper' where `CURLINFO_POSTTRANSFER_TIME_T` is zero after `curl_easy_perform` is done (though this test runs on all platforms without errors).

Is it possible for `req_set_upload_done ` to not get called?

**Comment by alexsn** [comment]
@bagder -merge window is about to close, could I please get a response on the above?

**Comment by bagder** [comment]
> Is it possible for req_set_upload_done to not get called?

I just tested your PR locally with a hyper build and yes, that's exactly what (not) happens. `req_set_upload_done` is not called... /cc @icing

**Comment by icing** [comment]
> req_set_upload_done

Made #14539 to add the missing call in hyper.

**Comment by bagder** [comment]
@alexsn please rebase on top of master and force-push. Should work now!

**Comment by icing** [comment]
I would exclude test500 from hyper. The time of the sending is a guess in hyper.

**Comment by alexsn** [comment]
> I would exclude test500 from hyper. The time of the sending is a guess in hyper.

You want me to do it in this PR?

**Comment by icing** [comment]
> > I would exclude test500 from hyper. The time of the sending is a guess in hyper.
> 
> You want me to do it in this PR?

That would be best.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
