### PR TITLE
smb.c: Fixed 'bad suffix on number' on VC6 & 7

### PR DESCRIPTION
**Pull request by skyline75489**

### CODE REVIEW

**Comment by bagder** [comment]
```
./smb.c:735:2: warning: Trailing whitespace (TRAILINGSPACE)
   
  ^

```

**Comment by bagder** [comment]
The function `get_posix_time()` is a weird one:

First, we should fix the second argument to not use a void pointer and instead pass in a correct type. Then, it seems the second argument is only ever `&smb_m->last_change_time` and I can't find any code that actually sets the `last_change_time` struct member to anything, so I can't see how that is ever anything but zero?

**Comment by bagder** [comment]
How about changing the order of the math?

If we divide with 10 million first, we can deduct a much smaller value that shouldn't need any suffix at all for any compiler?

```
  timestamp /= 10000000;
  timestamp -= 11644473600;

```
If my thinking is right, it shouldn't change the net result.

**Comment by skyline75489** [comment]
@bagder Anything that suits you. I just want to make it compile 😉

**Pull request closed without merging**
