### PR TITLE
libcurl-env.3: add CURL_DBG_ envvars

### PR DESCRIPTION
**Pull request by jay**
- Document debug variables CURL_DBG_SOCK_WBLOCK, CURL_DBG_SOCK_WPARTIAL and CURL_DBG_QUIC_WBLOCK.

Follow-up to 331b89a3 which added those variables.

Closes #xxxx

### CODE REVIEW

**Comment by bagder** [comment]
I think these should be documented somewhere in `tests/` instead, since they are for debug/development/testing only. Then we can document *all* the debug environment variables we have in that document.

**Comment by jay** [comment]
> Then we can document _all_ the debug environment variables we have in that document.

This document already has a specific section for debug variables. IMO it's easier to keep all of them in the same document. That way we can refer to just https://curl.se/libcurl/c/libcurl-env.html

**Comment by bagder** [comment]
okay, let's do that. We need to figure out the failed spell CI job though.

**Review by bagder — APPROVED** [review]

**Comment by jay** [comment]
> IMO it's easier to keep all of them in the same document. That way we can refer to just https://curl.se/libcurl/c/libcurl-env.html

I've since documented more debug variables and split off into a separate document libcurl-env-dbg.3.

**Comment by jay** [comment]
> We need to figure out the failed spell CI job though.

I added `AltSvc`, `CURLINFO` and `DEBUGBUILD` to spellcheck.words.

I don't know what to do about `dbg`, `DBG` and `WPARTIAL`.

`dbg` is seen only in the title. I could add it to spellcheck.words but it could also be considered a misspelling of debug.
~~~
.TH libcurl-env-dbg 3 "18 September 2023" "libcurl" "libcurl"
.SH NAME
libcurl-env-dbg \- environment variables libcurl DEBUGBUILD understands
~~~

`DBG` & `WPARTIAL` are seen only here:
~~~
.IP "CURL_DBG_SOCK_WPARTIAL"
Percentage of data that shall be written to the network. For TCP/UNIX sockets.
This is applied to every send. Example: CURL_DBG_SOCK_WPARTIAL=80 means a send
with 1000 bytes would only send 800.
~~~
I think I can ignore CURL_DBG_ vars by putting a regex in cleanspell? I'm not sure why only this CURL_DBG_ triggers the spellcheck but I'm guessing it's the example.

**Comment by bagder** [comment]
You can use the fact that the spell checker ignores emphasized words:

    Example: CURL_DBG_SOCK_WPARTIAL=80

Could be made as

    Example: \fBCURL_DBG_SOCK_WPARTIAL\fP=80

... which usually helps making the man page clearer as well!

**Comment by jay** [comment]
> \fBCURL_DBG_SOCK_WPARTIAL\fP=80

Thanks. I did it like \fICURL_DBG_SOCK_WPARTIAL=80\fP because I think changing the color looks better than bolding it (in my msys terminal that just makes it brighter). If you think it makes more sense as bold I'll change it.

Capture

**Comment by bagder** [comment]
I'm fine with whichever, I can't say I am consistent when I use them...

**Comment by jay** [comment]
@icing I added the two variables from #12035, please confirm

> CURL_DBG_SOCK_RBLOCK
> 
> The percentage of recv() calls that should be answered with a EAGAIN at random. For TCP/UNIX sockets.
> 
> CURL_DBG_SOCK_RMAX
> 
> The maximum data that shall be received from the network in one recv() call. For TCP/UNIX sockets. This is applied to every recv.
> 
> Example: CURL_DBG_SOCK_RMAX=400 means recv buffer size is limited to a maximum of 400 bytes.

**Comment by icing** [comment]
> @icing I added the two variables from #12035, please confirm
> 
> > CURL_DBG_SOCK_RBLOCK
> > The percentage of recv() calls that should be answered with a EAGAIN at random. For TCP/UNIX sockets.
> > CURL_DBG_SOCK_RMAX
> > The maximum data that shall be received from the network in one recv() call. For TCP/UNIX sockets. This is applied to every recv.
> > Example: CURL_DBG_SOCK_RMAX=400 means recv buffer size is limited to a maximum of 400 bytes.

Thanks!

**Review by icing — APPROVED** [review]

**Pull request closed without merging**
