### PR TITLE
Add SMB to list of disabled protocols if HTTP_ONLY is specified

### PR DESCRIPTION
**Pull request by sergey-raevskiy**

### CODE REVIEW

**Comment by MarcelRaad** [comment]
I'm none of the CMake experts, but where is `CURL_DISABLE_SMB` defined? Shouldn't there be an option for it? 😕

**Comment by jzakrzewski** [comment]
@MarcelRaad See https://github.com/curl/curl/blob/4f2541f975c97338ef421ecfeb295d9f3894c1d8/lib/curl_config.h.cmake#L55
It's used to configure that file.

**Comment by MarcelRaad** [comment]
> It's used to configure that file.

Ah, thanks @jzakrzewski ! So https://github.com/curl/curl/blob/361be51b00ad9a13c4ba51668d232aaad4bffe9a/CMakeLists.txt#L131 is only for the help text? SMB should probably have one too though.

**Comment by jzakrzewski** [comment]
I think you're right - the actual option is missing. Adding it would totally be in the scope of this PR.

**Comment by sergey-raevskiy** [comment]
Hi! I've updated my patch.

**Comment by bagder** [comment]
@jzakrzewski you think this is good now?

**Comment by jzakrzewski** [comment]
LGTM.
I'd squash it all into one commit though.

**Comment by bagder** [comment]
Thanks!

**Comment by bagder** [comment]
This broke the [windows builds](https://ci.appveyor.com/project/curlorg/curl/builds/25188586) for, to me,  unknown reasons.

**Comment by MarcelRaad** [comment]
That's https://github.com/curl/curl/issues/1262:

```
test 1013...[Compare curl --version with curl-config --protocols]
Mismatch in protocols lists:
curl:        dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smtp smtps telnet tftp
curl-config: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smtp smtps telnet tftp
```

**Comment by bagder** [comment]
Hm right that issue was never fixed. It means win32-crypto is still only used in some strange build combinations that users probably can't even figure out...

So, SMB simply isn't enabled this easily as this patch makes it out to and that's why the autoconf logic for the same thing looks like this:

https://github.com/curl/curl/blob/29177f422a55310976378440ffb00ee7d19ce6e9/configure.ac#L4329-L4338

**Comment by bagder** [comment]
@sergey-raevskiy still interested in fixing this?

**Comment by bagder** [comment]
No response for months. Closing.

**Pull request closed without merging**
