### PR TITLE
vtls: upgrade the MesaLink TLS backend to v1.0.0

### PR DESCRIPTION
**Pull request by kevinis**
This attempts to solve #3776 and brings in MesaLink 1.0.0.

### CODE REVIEW

**Comment by kevinis** [comment]
Looks good here: https://travis-ci.com/mesalock-linux/curl/jobs/196814757

**Comment by bagder** [comment]
Coveralls is drunk again

**Comment by bagder** [comment]
Thanks!

**Comment by kevinis** [comment]
No problem ;-)

**Pull request closed without merging**
