### PR TITLE
[WIP] cookie: curl_filter_cookies public function

### PR DESCRIPTION
**Pull request by jay**
[WIP] Expose a function to show a list of cookies for a url.

Ref: https://curl.haxx.se/mail/lib-2019-09/0100.html

---

Filters a linked list of cookies to determine which match the URL. Untested. I already see a few mistakes.

/cc @dhoelzl

### CODE REVIEW

**Comment by bagder** [comment]
1. I think that if/when we provide a dedicated cookie match function, it should return the list of matching cookies in a better format than string in netscape format. It is a bit too error prone for users to have to parse that. I think there should be a `struct curl_cookie` for each cookie to allow the application to get the already parsed details from them.
2. I don't think the function needs a list of input cookies to set. It just complicates the function.
3. I think this PR should also provide a basic description of how the function works to make it easier to review and discuss. Possibly done as a wiki page.

**Comment by bagder** [comment]
I think the function name should start with `curl_cookie_`, to group nicer if/when we figure out other cookie-related functions to add.

**Comment by jay** [comment]
Sure, this is to get the ball rolling so that we have a topic. curl_filter_cookies (now _curl_cookie_filter_) takes cookies obtained with CURLINFO_COOKIELIST as input, filters that input according to url and the filtered list is received as output.

**Comment by jay** [comment]
I'm mothballing this due to lack of interest.

**Pull request closed without merging**
