### PR TITLE
test1660: create HSTS file in text mode

### PR DESCRIPTION
**Pull request by bagder**
To make sure it compares fine on Windows machines too.

Follow-up to d71ff2b9db5

### CODE REVIEW

**Comment by bagder** [comment]
Blah, so test 1660 now only fails on Windows builds on azure, not on appveyor or in @mback2k's buildbots... :cry:

**Comment by mback2k** [comment]
> Blah, so test 1660 now only fails on Windows builds on azure, not on appveyor or in @mback2k's buildbots... 😢

Simple explanation: the AppVeyor builds are non-native Windows builds, but msys2-layer builds and the buildbots are cross-platform builds that do not run tests since they are Linux based. So only the Azure builds are actually real native Windows builds.

**Comment by mback2k** [comment]
With or without your fix it seems like the expected file is generated with [LF] while curl actually generates [CR][LF]. So what is the actually expected line ending?

**Comment by bagder** [comment]
hsts.c writes "\n" to the file, but this is windows and it is a text file...

**Comment by bagder** [comment]
I'm silly, I had been changing the wrong part of the test file. Now things have a better chance of working correctly...

**Pull request closed without merging**
