### PR TITLE
Add support for %{stderr} and %{stdout} for --write-out

### PR DESCRIPTION
**Pull request by gevaerts**
Note that the actual stderr test is incomplete: runtests.pl doesn't have easy support for stderr

### CODE REVIEW

**Comment by jay** [comment]
I proposed something similar a while ago but it died due to lack of interest, see [https://github.com/curl/curl/compare/master...jay:add_flags_to_write-out](jay:add_flags_to_write-out). Yours is cleaner. In any case one issue is stderr is used for errors and that could disrupt the write-out text. I liked fd 3 - 9 as an alternative even though I couldn't get it working in Windows.

**Comment by gevaerts** [comment]
My approach is mainly cleaner because it does a lot less... I do like the flexibility of your approach though, and separating output variables from things like this does make sense.

**Comment by bagder** [comment]
I prefer this version due to its simplicity and minimalism.

**Comment by bagder** [comment]
Would you mind also removing the TODO entry for this? (18.11)

**Comment by gevaerts** [comment]
OK, should be done now! (as well as rebased)

**Comment by bagder** [comment]
Thanks!

**Comment by sarankxbczjn** [comment]
e431daf

**Pull request closed without merging**
