### PR TITLE
fix $logfile init in http2/http3server.pl and http-server.pl

### PR DESCRIPTION
**Pull request by icing**
The value was sometimes uninitialized which made perl cry in CI.

### CODE REVIEW

**Comment by icing** [comment]
@dfandrich does this look correct to you?

**Review by dfandrich — CHANGES_REQUESTED** [review]
Each of these three perl programs doesn't do any logging itself but execs another program and passes in the computed filename in $logfile. Therefore, importing the global $logfile variable will make no difference as no other entity will see it, making this effectively a no-op.

If this is to solve the issue on serverhelp.pm line 89 the it will be in some file that's already using logmsg.

**Comment by dfandrich** [comment]
From the logs, it does look like the problem is in http-server.pl, but I see no logmsg calls in there or in anything it uses.

**Comment by icing** [comment]
Yeah, I was trying to find the place where this error originates and hunted for local `my $logfile` definitions that overshadow setting of serverhelp::$logfile. Hmm...

**Comment by icing** [comment]
> From the logs, it does look like the problem is in http-server.pl, but I see no logmsg calls in there or in anything it uses.

Yes, I see the same - or lack of it. A mystery?

**Comment by icing** [comment]
@dfandrich may that change only in secureserver.pl is an improvement. I reverted the other ones.

**Comment by icing** [comment]
Closed, replaced with #15040

**Pull request closed without merging**
