### PR TITLE
runtests: add %repeat[]% for test files

### PR DESCRIPTION
**Pull request by bagder**
... and use this new keywords in all the test files larger than 50K to reduce
their sizes and make them a lot easier to read and understand.

### CODE REVIEW

**Comment by emilengler** [comment]
I like the idea but I think an asterisk would fit better than a "x"

**Comment by bagder** [comment]
This mimics the syntax for how to do this in perl so I think there's a minor point in sticking to x...

**Comment by emilengler** [comment]
> This mimics the syntax for how to do this in perl so I think there's a minor point in sticking to x...

I don't understand what's bad about that, please elaborate.

**Comment by bagder** [comment]
I didn't say nor imply it was bad. I said there's a point in sticking to this syntax I chose since it is already used in perl.

**Pull request closed without merging**
