### PR TITLE
vtls: deduplicate some DISABLE_PROXY ifdefs (continue #5735)

### PR DESCRIPTION
**Pull request by MAntoniak**
Using SSL_HOST_NAME, SSL_HOST_DISPNAME, SSL_PINNED_PUB_KEY for other tls backend
Create SSL_HOST_PORT

### CODE REVIEW

**Comment by bagder** [comment]
@MAntoniak can you rebase this and fix the merge conflict? I would like to merge...

**Comment by MAntoniak** [comment]
> 
> 
> @MAntoniak can you rebase this and fix the merge conflict? I would like to merge...

Done

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Awesome, thanks!

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
