### PR TITLE
vtls: deduplicate client certificates in ssl_config_data

### PR DESCRIPTION
**Pull request by ngg**
This is split from https://github.com/curl/curl/pull/5619#issuecomment-650722293
I have only tried with OpenSSL, but other backends should be fine as well, let the CI try them.

### CODE REVIEW

**Comment by ngg** [comment]
I've rebased this PR onto current master (without any conflicts), can your merge it if CI succeeds?

**Comment by ngg** [comment]
CI failures seem unrelated.

**Comment by ngg** [comment]
@bagder can you merge this?

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
