### PR TITLE
runtests: add option -u to error on server unexpectedly alive

### PR DESCRIPTION
**Pull request by mback2k**
Let's try to actually handle the server unexpectedly alive
case by first making them visible on CI builds as failures.

### CODE REVIEW

**Comment by mback2k** [comment]
This helped discover the issues fixed with #7481, #7482 and #7506 and will probably be merged after #7530.

**Review by bagder — CHANGES_REQUESTED** [review]
The commit message needs an update. I suppose the reason for this option is to detect and provide a way to debug problems with killing off test servers?

**Comment by mback2k** [comment]
Thanks for the feedback @bagder. I just rebased and pushed an extended commit message.

**Comment by mback2k** [comment]
@bagder is this ready to go?

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
