### PR TITLE
Amartz/curl updates

### PR DESCRIPTION
**Pull request by amartz-ATG**
Updates

### CODE REVIEW

**Comment by bagder** [comment]
Please explain what this is for. Using lots of words

**Comment by amartz-ATG** [comment]
I'm trying merge my changes in my local branch into my fork. I'm not trying to push this into the mainline yet.

**Comment by bagder** [comment]
Fair enough, but then you should not propose it as a PR here.

**Comment by amartz-ATG** [comment]
How should the branch be pulled into the fork and not the mainline?

**Comment by bagder** [comment]
If you want it as a PR, make the PR for your cloned repo. Not for curl/curl.

**Comment by amartz-ATG** [comment]
Figured out what I did incorrectly. Sorry to bother you.

**Pull request closed without merging**
