### PR TITLE
Make curl_getenv() work correctly in Unicode build.

### PR DESCRIPTION
**Pull request by dEajL3kA**
Until now, `curl_getenv()` internally uses `GetEnvironmentVariableA()` on Windows, even in Unicode build. This does **not** work correctly, if the environment variable contains characters that cannot be represented in the system's ANSI codepage. A typical exampel would be the `HOME` environment variable. It contains a string like `C:\Users\Βαρουφάκης`, depending on user name.

### CODE REVIEW

**Comment by bagder** [comment]
~~~
libtool: compile:  x86_64-w64-mingw32-gcc -DHAVE_CONFIG_H -I../include -I../lib -I../lib -DBUILDING_LIBCURL -DCURL_STATICLIB -isystem C:/msys64/mingw64/include -isystem C:/msys64/mingw64/include -DWINVER=0x0600 -Werror-implicit-function-declaration -O2 -Wno-system-headers -Wenum-conversion -Werror -pedantic-errors -MT libcurl_la-getenv.lo -MD -MP -MF .deps/libcurl_la-getenv.Tpo -c getenv.c -o libcurl_la-getenv.o
getenv.c: In function 'GetEnvWin32':
getenv.c:45:14: error: returning 'void *' from a function with return type 'TCHAR' {aka 'char'} makes integer from pointer without a cast [-Wint-conversion]
   45 |       return NULL;
      |              ^~~~
getenv.c:56:14: error: returning 'void *' from a function with return type 'TCHAR' {aka 'char'} makes integer from pointer without a cast [-Wint-conversion]
   56 |       return NULL;
      |              ^~~~
getenv.c:61:14: error: returning 'TCHAR *' {aka 'char *'} from a function with return type 'TCHAR' {aka 'char'} makes integer from pointer without a cast [-Wint-conversion]
   61 |       return buf;
      |              ^~~
getenv.c: In function 'GetEnv':
getenv.c:87:10: error: returning 'TCHAR' {aka 'char'} from a function with return type 'char *' makes pointer from integer without a cast [-Wint-conversion]
   87 |   return GetEnvWin32(variable);
      |          ^~~~~~~~~~~~~~~~~~~~~

**Comment by jay** [comment]
curl_getenv is a public api function that returns local codepage. I think there was some discussion whether to return UTF-8 here. We'd break existing legacy clients.

**Comment by dEajL3kA** [comment]
> We'd break existing legacy clients.
Maybe the lesser of two evils 😈 

Current behaviour, with the "official" Unicode build, is as follows:
grafik

**Comment by vszakats** [comment]
Given that this function is already deprecated (since [2004](38cc79a54ff11e96e527666137fc9eb77db96c60)), my initial thought was that we should rather just document the unexpected behaviour in UNICODE builds and leave it as-is.

But, the issue here is that this function is actively used _inside curl_ (and libcurl), so the values returned from it will thus unexpectedly introduce 8-bit values internally to UNICODE builds. That's most likely not what those callers (or the user) expects. (E.g. it may make `.netrc` and SSH keys being read from the wrong path if the user has a username with non-ASCII characters, or a proxy will be misread if the URL has non-ASCII characters.)

So to operate on UTF-8 as intended, either this function should also be fixed (by breaking compatibility), or a new version introduced while leaving this one as-is, and upgrade to the new (UTF-8 capable) version internally in curl/libcurl.

**Comment by jay** [comment]
The function should not be changed or broken. I'll add a GetEnv in the curl tool that returns UTF-8 for Windows Unicode builds.

**Comment by jay** [comment]
Closing, we aren't going to change curl_getenv. An attempt to add a different getenv for the curl tool that returns a UTF-8 encoded path in Windows Unicode builds has died and this is now known bug [5.14 Windows Unicode builds use homedir in current locale](https://curl.se/docs/knownbugs.html#Windows_Unicode_builds_use_homed)

**Pull request closed without merging**
