### PR TITLE
ldap: Fixed multiple regressions

### PR DESCRIPTION
**Pull request by samsinsane**
- Match URL scheme with LDAP and LDAPS
- Retrieve attributes, scope and filter from URL query instead

These regressions were introduced in #3017

### CODE REVIEW

**Comment by bagder** [comment]
~~~
./ldap.c:864:5: warning: if with space (SPACEBEFOREPAREN)
   if (!query) {
     ^

**Comment by bagder** [comment]
As we're a bit tight on time to release, I'll amend this myself before merge.

**Comment by bagder** [comment]
Thanks!

**Comment by samsinsane** [comment]
Sorry about that, thanks for fixing it up and merging!

**Pull request closed without merging**
