### PR TITLE
tool_listhelp: easier to generate with gen.pl

### PR DESCRIPTION
**Pull request by bagder**
tool_listhelp.c is now a separate file with only the command line --help
output, exactly as generated by gen.pl. This makes it easier to generate
updates according to what's in the docs/cmdline-opts docs.

  cd $srcroot/docs/cmdline-opts
  ./gen.pl listhelp *.d > $srcroot/src/tool_listhelp.c

### CODE REVIEW

**Comment by gvanem** [comment]
Would it be possible to make `gen.pl` generate a *frontpage help* a bit nicer like this:
```
Usage: curl [options...] <url>
 -d, --data <data>          HTTP POST data
 -f, --fail                 Fail silently (no output at all) on HTTP errors
 -h, --help <category>      Get help for commands
 -i, --include              Include protocol response headers in the output
 -o, --output <file>        Write to file instead of stdout
 -O, --remote-name          Write output to a file named as the remote file
 -s, --silent               Silent mode
 -T, --upload-file <file>   Transfer local FILE to destination
 -u, --user <user:password> Server user and password
 -A, --user-agent <name>    Send User-Agent <name> to server
 -v, --verbose              Make the operation more talkative
 -V, --version              Show version number and quit
```

Since `curl --help category` is nice and aligned, so should this *frontpage* IMHO.

Or it could be done in `tool_listhelp.c` itself by something like:
```c
static void print_category(curlhelp_t category)
{
  unsigned int i;
  size_t len, longest = 0;

  if (category & CURLHELP_IMPORTANT)
    for(i = 0; helptext[i].opt; ++i) {
       if(!(helptext[i].categories & CURLHELP_IMPORTANT))
         continue;
       len = strlen(helptext[i].opt);
       if (len > longest)
          longest = len;
    }
  else
     longest = 18;

  for(i = 0; helptext[i].opt; ++i)
    if(helptext[i].categories & category) {
      printf(" %-*s %s\n", longest, helptext[i].opt, helptext[i].desc);
    }
}
```

**Comment by bagder** [comment]
We could even do it for all categories! And since that's not really related to this change, I'll do that in a separate PR.

**Comment by bagder** [comment]
See #7792 for how I took your proposal a little further.

**Comment by gvanem** [comment]
> We could even do it for all categories! 

Ok, fine. But maybe that could generate too much indent. Like in `curl --help tls`:
```
...
-E, --cert <certificate[:password]> Client certificate file and password
...
 --ssl                              Try SSL/TLS
```

**Comment by bagder** [comment]
Yes, which is why I attempted to only do it as wide as it can without wrapping...

**Comment by bagder** [comment]
In the FreeBSD 11.4 CI-job this change mysteriously causes:
~~~
test 1027...[curl --help]
core dumped

**Pull request closed without merging**
