### PR TITLE
GHA: rename wolfssl and torture workflows

### PR DESCRIPTION
**Pull request by andy5995**

### CODE REVIEW

**Comment by andy5995** [comment]
The practical intent of this is to make it easier to view workflow information from the Actions tab. Right now, there are far too many "Linux" workflows:

image

**Review by mback2k — APPROVED** [review]
Okay for now, although further CI file merges are still pending my side.

**Comment by bagder** [comment]
I don't quite see the point.

|before|now|
|----|----|
| **Linux/wolfssl** | **wolfssl/wolfssl** |
| **Linux/torture** | **torture/torture** |

This change just removes an information bit and instead add a (pointless) repetition in the name. Also, there is an existing separate **macos/torture** job that goes well with the **Linux/** version as it hints what differences there are.

**Comment by bagder** [comment]
I think this makes the output worse, as explained above.

**Pull request closed without merging**
