### PR TITLE
cmake: set TESTCASES as sources

### PR DESCRIPTION
**Pull request by orgads**
This includes them in the project tree for IDEs.

### CODE REVIEW

**Comment by bagder** [comment]
Please elaborate on why this change is necessary. This changes the 'show' target for the makefile which AFAIK isn't used anymore.

**Comment by orgads** [comment]
For IDEs that use CMake file api (like Qt Creator), this change lists the testcase files in the project tree.

**Comment by bagder** [comment]
I don't think you are correct.

This change proposed changing the 'show' target in the makefile in there, I really do not see how an IDE would magically use that. I have now removed that target completely since it isn't in use anymore.

This PR therefore has conflicts.

**Comment by orgads** [comment]
Only files that are listed as SOURCES (for any target) are shown in the project tree on Qt Creator.

So I just picked the first target I found :)

Maybe @cristianadam can elaborate, and suggest an alternative.

**Comment by bagder** [comment]
Ok. Then I think you need to create a target for that and properly document what it's for.

I would perhaps argue that test cases are not source code, but I don't know why you want this nor how your IDE works so I will not.

**Pull request closed without merging**
