### PR TITLE
Make CURLOPT_CAINFO work on Windows 7

### PR DESCRIPTION
**Pull request by faizur**
CERT_NAME_SEARCH_ALL_NAMES_FLAG doesn't exist before Windows 8. As a
result CertGetNameString doesn't quite work on those versions of
Windows. This change provides an alternative solution for
CertGetNameString by iterating through CERT_ALT_NAME_INFO for earlier
versions of Windows.

### CODE REVIEW

**Comment by faizur** [comment]
This should fix the issue reported here https://github.com/curl/curl/issues/3711

**Comment by jay** [comment]
Neat. Does this handle wildcards like *.foo.amazon.com?

/cc @jeroen

**Comment by faizur** [comment]
@jay It does handle wildcards. Actually, the logic(Curl_cert_hostcheck) to handle those hasn't changed.

**Comment by faizur** [comment]
AFAICT, the failing two checks seem to be flaky.

**Comment by jay** [comment]
> AFAICT, the failing two checks seem to be flaky.

Yes. I've set it to re-run the failed checks.

**Comment by faizur** [comment]
> > AFAICT, the failing two checks seem to be flaky.
> 
> Yes. I've set it to re-run the failed checks.

Thanks! Down to one failing check now.

**Comment by jay** [comment]
Thanks

**Comment by jay** [comment]
I missed a bug, a char * was used to advance a tchar * which caused problems in Unicode builds. Fixed in 16da8bc.

**Pull request closed without merging**
