### PR TITLE
Changing behavior from from "FETCH" to "UID FETCH" and add "MAILINDEX"

### PR DESCRIPTION
**Pull request by nicklasaven**
As described in #2789, this is a suggested solution.
Changing UID=xx to actually get mail with UID xx and add "MAILINDEX"
to get a mail with a special index in the mail box (old behavior).
So MAILINDEX=1 gives the first non deleted mail in the mail box.

### CODE REVIEW

**Comment by nicklasaven** [comment]
I edited that file a little to mention the new behavior. But where to mark more clearly about breaking change?

**Comment by bagder** [comment]
> But where to mark more clearly about breaking change?

That's a very good question. I think the IMAP section in CURLOPT_URL.3 is the best place for this info, even if it is a bit hidden away. It will also be listed as a "change" in the release notes for the release where this ships. Any other suggestion?

> I will also write a blog post about how I use this and can contribute to "everything curl" about imap

That'd be awesome!

Note that your PR still gets that red marker since you haven't updated the IMAP tests so they now fail with your changed applied. It would also be great if you could add a test that verifies that your `MAILINDEX` approach works.

**Comment by nicklasaven** [comment]
Yes, I will look at it

**Comment by nicklasaven** [comment]
Hmm, I don't understand how I can have produced that error from Travis 8352.17

```
Undefined symbols for architecture x86_64:
  "_SSLCopyALPNProtocols", referenced from:
      _darwinssl_connect_step2 in libcurlu.a(libcurlu_la-darwinssl.o)
  "_SSLSetALPNProtocols", referenced from:
      _darwinssl_connect_step1 in libcurlu.a(libcurlu_la-darwinssl.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [unit1300] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [test-nonflaky] Error 2
```

**Comment by bagder** [comment]
@nicklasaven no, sorry, that's an independent problem - not your fault. We're working on that separately so just ignore that annoying one for now.

**Comment by nicklasaven** [comment]
Ah, ok. No problem

I also try to figure out how to make tests with the actual UID call. I get the call right I think, but I do not understand how to modify the server to handle it correct. If I understand right the mail server used in the tests is some sort of dummy server that answers what it is told to answer? 

I guess I will find out how it works, but any hint is appreciated :-)

**Comment by nicklasaven** [comment]
The solution committed now is very hackish. 
It seems like the server, before I did the last commit 9a4a1e2 seems to expect a "UID FETCH" command. 

What I have done is just detecting if the command starts with "UID FETCH" and then sends it to "FETCH" - handling instead of "UID" - handling. 

Maybe it would be more correct to actually identify "UID FETCH" as a command earlier and handle that in a dedicated sub. But I cannot see that the server easily can handle identifying a 2 word command without hard coding special cases. 

I just don't know what is the most correct way of doing this.

**Comment by bagder** [comment]
> One of them is the same as before

Right, that one is fixed in master now.

> The other one 8355.2 seems to be a timing out. Is also that unrelated?

Very weird. I restarted that job now to see if this was a one-off or not...

**Comment by nicklasaven** [comment]
Yes, now it looks better :-)

**Comment by bagder** [comment]
All green! For the sake of easier code review, can you squash, rebase and force-push please?

**Comment by nicklasaven** [comment]
will do my best

**Comment by nicklasaven** [comment]
Yes, I think a had it right. All in 1 commit and passing tests :-) 

For review: Is there a better solution for making the server accept UID FETCH requests. I am also not sure that I pass through the arguments correctly in row 1566 in ftpserver.pl

**Comment by nicklasaven** [comment]
Will this be included in next release?
Anything more I should do about it?

**Comment by nicklasaven** [comment]
I see, thank you

**Comment by bagder** [comment]
Thanks a lot!

**Pull request closed without merging**
