### PR TITLE
cookie: fix crash in netscape cookie parsing

### PR DESCRIPTION
**Pull request by jay**
- Tokenize a copy of the input string instead of the original.

Prior to this change a segfault could occur if the input string was const because the tokenizer modified the input string. For example if the user set CURLOPT_COOKIELIST to a const string then libcurl would likely cause a crash when modifying that string. Even if the string was not const or a crash did not occur there was still the incorrect and unexpected modification of the user's input string.

This issue was caused by 30da1f59 (precedes 8.11.0) which refactored some options parsing and eliminated the copy of the input string. Also, an earlier commit f88cc654 incorrectly cast the input pointer when passing it to strtok.

Closes #xxxx

### CODE REVIEW

**Comment by bagder** [comment]
I think it would be even nicer to rewrite the parser to not touch the input string without strdup()ing the full line for every line. A middle-ground would be to use a dynbuf() or something so that it wouldn't have to alloc/free for every single line when it reads many lines.

**Comment by jay** [comment]
If by full line for every line you mean all the subsequent lines then yeah there is no reason to copy that because parse_netscape only parses the first line it is given. i've added a change to only copy the first line for tokenizing. however if you mean implement our own tokenizing rather than using strtok that would be messier imo than just copying a string that can be tokenized.

**Comment by jay** [comment]
> I think it would be even nicer to rewrite the parser to not touch the input string

#15826

**Comment by jay** [comment]
Closing in favor of #15826

**Pull request closed without merging**
