### PR TITLE
multi: add curl_multi_init2 for advanced multi init

### PR DESCRIPTION
**Pull request by jay**
Allow initializing a multi with a specific socket table hash size,
connection cache hash size, and flags. Flag
CURL_MULTI_DISABLE_POLL_WAKEUP can be used to disable the
curl_multi_poll wakeup socketpair. A user requested the option to
disable creating those sockets due to resource constraints.

Prior to this change it was not possible to disable the wakeup
socketpair (added in 7.68.0) used by the multi.

Reported-by: Anders Bakken

Fixes https://github.com/curl/curl/issues/4829
Closes #xxxx

---

/cc @Andersbakken

### CODE REVIEW

**Comment by bagder** [comment]
I'm :+1: for this approach. I'm not particularly thrilled with appending a `2` to the name like this, but I also can't figure out a better name/approach...

**Comment by danielgustafsson** [comment]
> On 22 Jan 2020, at 09:38, Daniel Stenberg <notifications@github.com> wrote:
> 
> I'm 👍 for this approach. I'm not particularly thrilled with appending a 2 to the name like this, but I also can't figure out a better name/approach...

curl_multi_extended_init ?

**Comment by jay** [comment]
> curl_multi_extended_init

eh. I prefer curl_multi_init2.

Is it worth exposing the hostcache table hashsize, which is currently hardcoded at 7 slots?

**Comment by danielgustafsson** [comment]
> On 23 Jan 2020, at 08:08, Jay Satiro <notifications@github.com> wrote:
> eh. I prefer curl_multi_init2.
> 

Well, as long as we're happy with it since whatever is chosen should reflect a naming convention going forward.

**Comment by bagder** [comment]
[on the name]

I think `2` implies a natural successor/replacement, while in this case the new function is an alternative version with more fancy options. `curl_multi_init_options()` would be better in my mind as it describes a little how the new function differs from the original. In similar style with how we have already `curl_global_init` and `curl_global_init_mem` and even `curl_version`  and `curl_version_info`.

> Is it worth exposing the hostcache table hashsize, which is currently hardcoded at 7 slots?

We've never had anyone express concerns, we haven't seen any report on DNS cache slowness and we don't have any particular performance numbers ourselves to back up any particular different values to pass there. I think offering this to users is a little too big of a foot-gun and we can't really document any obvious benefits for changing this value. So I think not.

**Comment by dfandrich** [comment]
This thread makes me think of the old saying that goes something like "A
function taking 9 arguments is missing one". One of the reasons libcurl has
been so successful IMHO is because of its stable and extensible API. Rather
than coming up with replacement APIs with new arguments all the time, it has
setopt functions that can be (nearly) infinitely added without breaking any
sort of compatibility.

Rather than breaking that tradition here, can this problem be solved in the
curl way? For example, there's no reason the hash size needs to be available in
the init function—that's merely an implementation detail and the easiest way to
solve the problem today. Why not make that a setopt instead? If you have to,
document that the hash size can't be changed once the first handle has been
added, which makes implementation easy.

Same with the flags. Make the disable_poll option a setopt and if it's set,
close the socket pair then, or set a flag to prevent them from being opened
lazily later.

Sometimes there's no alternative to a new API, but I yet don't see that here.

**Comment by jay** [comment]
I agree with that sentiment but I don't see how else it could be done in this case. The two sockets should not be created at all if there are resource constraints, but also if they are created must be available by the time curl_multi_init returns because they may be evaluated from other threads ([curl_multi_wakeup](https://curl.haxx.se/libcurl/c/curl_multi_wakeup.html)) until curl_multi_cleanup is called. The reason for this is libcurl has no internal thread synchronization. (I've included proposed documentation to clarify the usage of curl_multi_wakeup.)

I named it curl_multi_initN because that is the convention I have seen with some API where there is Nth iteration of a function/class that adds more options. Since the consensus seems to be against the name I've changed it.

CURL_EXTERN CURLM *curl_multi_init_advanced(int flags, ...);

The hash table sizes are no longer exposed. Variable arguments is for the future if there are ever more options that can only be set prior to initialization then a flag could be added or CURL_MULTI_EXTENDED_INIT_OPTIONS and then pass a variable length struct as the second parameter.

**Comment by dfandrich** [comment]
curl_multi_wakeup is brand-new so we might be able to get away with changing it
so that it takes a call to curl_multi_setopt first to enable use of it. Or
assume that no system is going to be so resource constrained that it can't
handle one extra socket open for a few microseconds and close them after init.

**Comment by jay** [comment]
Not a fan of either of those options, to be sure.

**Comment by rcombs** [comment]
> Or assume that no system is going to be so resource constrained that it can't handle one extra socket open for a few microseconds and close them after init.

This wouldn't be a big deal on its own, but each socket pair allocates 2 ports, which then spend a few minutes in TIME_WAIT. This can pretty easily exhaust the available dynamic TCP ports on the loopback interface.

**Comment by jay** [comment]
This PR does not have enough support. Hopefully one of the other ideas to fix #4829 will gain some traction.

**Pull request closed without merging**
