### PR TITLE
Silence warning on comma misuse

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
Building curl with -Wcomma, I see warnings about "possible misuse of comma operator here" and moving fields assignment out of the for() fixes it.

### CODE REVIEW

**Review by danielgustafsson — APPROVED** [review]
LGTM

**Comment by danielgustafsson** [comment]
Thanks, I think this is a step towards less clever and more readable code. I'll just let CI have a look before pushing.

**Comment by bagder** [comment]
We should probably add `-Wcomma` to the picky compiler options

**Comment by bagder** [comment]
Turns out we already do (with clang)! @MonkeybreadSoftware are you perhaps using a very recent clang with perhaps some changes for this warning?

**Comment by MonkeybreadSoftware** [comment]
Sorry, this is just my test project in Xcode 15.3 to work on curl changes in the IDE.
It has a few warnings enabled like suspicious commas and reported the two source code lines here.

Maybe your CI with Xcode 14 doesn't report this.

**Comment by bagder** [comment]
> Maybe your CI with Xcode 14 doesn't report this.

This is a clang option added in 3.9 and we build with this option in several builds. Totally independent of xcode. I have no idea why they don't warn on these.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
