### PR TITLE
multi: unlink handles in pending or msgsent states

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
I'll also make a test to move completed handles over to a new list so that they can be skipped in the main loop as well.

**Comment by bagder** [comment]
The pytest failures are very curious. I need to dig into those...

**Comment by bagder** [comment]
@icing I could use a little hand-holding to learn the best way to debug these pytest failures.

**Comment by bagder** [comment]
> I think the problem is that you modify mult->easyp while iterating over it.

Ah yes indeed.

**Comment by bagder** [comment]
@icing thanks for that hint, it seems that was the bug that held this back.

**Comment by icing** [comment]
> @icing thanks for that hint, it seems that was the bug that held this back.

Yep, works now locally here as well.

**Pull request closed without merging**
