### PR TITLE
hostip: add CURL_ALLOW_DOT_ONION to allow .onion lookups

### PR DESCRIPTION
**Pull request by omnivagant**
RFC 7686 states that:

> Applications that do not implement the Tor protocol SHOULD generate
> an error upon the use of .onion and SHOULD NOT perform a DNS lookup.

RFC 2119 states that:

> SHOULD NOT   This phrase, or the phrase "NOT RECOMMENDED" mean that
> there may exist valid reasons in particular circumstances when the
> particular behavior is acceptable or even useful, but the full
> implications should be understood and the case carefully weighed
> before implementing any behavior described with this label.

### CODE REVIEW

**Comment by omnivagant** [comment]
I have tested and it works as intended but I currently consider this WIP as it doesn't add any tests or to documentation and `ALLOW_ONION_LOOKUP` was just grabbed out of my behind. Still wanted to share for comments and input.

**Comment by omnivagant** [comment]
Also, when curl is `./configure`d with `--enable-ares` this is will still fail since https://github.com/c-ares/c-ares/commit/955df983d7f643d1b00aa433f31ca3ec7f86b4bd with "Could not resolve host" but that is out-of-scope for this PR besides documentation, probably.

**Comment by jzakrzewski** [comment]
If the env. name is not standardized (via a paper or de-facto), it should probably be namespaced (start with `CURL_`).

**Comment by bagder** [comment]
I want to hear more about how this is used for legitimate purposes and not just actually for the purpose of snooping on `.onion` hosts being resolved - the exact thing this is meant to prevent.

In the previous discussion about this ask, it was mention how you could resolve a `.onion` name using a Tor DNS, but if you do, you would get a set of IP addresses back that can only be used within the Tor network so curl would still not be able to connect to those IP addresses normally surely?

**Comment by omnivagant** [comment]
Transparent Tor Proxying (as mentioned in #11111) where you direct all traffic through Tor, and DNS requests (at least for .onion) to tor(1), where your applications do not need to know about Tor, is not that uncommon. There are multiple guides on how to set this up and several projects that will do this for you.

Usually with help of your systems firewall with NAT rules and sometimes additionally helped by dnsmasq or dnscrypt-proxy configuration for .onion addresses. Sometimes you do this locally on your host, sometimes in a chained network VM (like a Qubes OS "ProxyVM") and sometimes for a whole LAN.

**Comment by omnivagant** [comment]
The, now namespace prefixed, toggle name change was inspired by Firefox that does follow RFC 7686 by having `network.dns.blockDotOnion` set to *true*, available to toggle through `about:config`.

**Comment by bagder** [comment]
A follow-up question is: if we want to allow switching this off, how should we do that? Adding an environment variable for this purpose is a little surprising and unusual, possibly also a bit hard to find for users. We normally add options to `curl_easy_setopt()` for these things.

Alternatives that I can think of:

1. only environment variable support in libcurl (current PR)
2. environment variable + setopt in libcurl
3. environment variable + cmdline option in curl, setopt in libcurl
4. cmdline option in curl, setopt in libcurl

Where (4) is the standard for transfer options and we should only deviate from that path with very good reasons.

**Comment by omnivagant** [comment]
I think I'm leaning toward (3) and not have the environment variable namespace prefixed, if the name is standardized, so that it can also be picked up by others. What would flag like `--allow-dot-onion` help if curl was built with `--enable-ares`?

I've opened https://gitlab.torproject.org/tpo/core/torspec/-/issues/202 to see what the Tor Project  people have to say.

**Comment by Kangie** [comment]
Tor [do not believe](https://gitlab.torproject.org/tpo/core/torspec/-/issues/202#note_2909909) than an environment variable is the appropriate mechanism for 'disable rfc protection'.

IMO the RFC doesn't leave any wiggle-room there; adhere to it or don't; please don't implement a non-standard mechanism that changes the way DNS resolution works.

Instead, I suggest that this moves back into the discussion space. Some suggestions based on what we have so far from Tor:

1. Is Transparent Proxying best practice in 2023? Is there a better way to accomplish your goal that doesn't require doing anything client applications? Assume that RFC7686 is going to be adhered to by client applications.
2. How can cURL become aware that it's part of a Tor-enabled environment?

**Comment by bagder** [comment]
> Tor [do not believe](https://gitlab.torproject.org/tpo/core/torspec/-/issues/202#note_2909909) than an environment variable is the appropriate mechanism for 'disable rfc protection'.

I am strongly against doing things in libcurl based on environment variables unless it is some kind of standard set somewhere. Which this is not.

**Comment by milahu** [comment]
thanks! im using this workaround on nixos linux via https://github.com/milahu/nur-packages/commit/33b3ef8cc8f4d2b177f153464db2ba37a304b08c

**Comment by milahu** [comment]
it would be nice to add a hint after the error message, something like

> hint: wrap your command with "CURL_ALLOW_DOT_ONION=1 torsocks"

**Comment by markozajc** [comment]
Is there a workaround for this that doesn't involve recompiling curl?

**Comment by milahu** [comment]
> Is there a workaround for this that doesn't involve recompiling curl?

https://github.com/curl/curl/discussions/11125#discussioncomment-6982136

**Comment by markozajc** [comment]
> > Is there a workaround for this that doesn't involve recompiling curl?
> 
> [#11125 (comment)](https://github.com/curl/curl/discussions/11125#discussioncomment-6982136)

Thanks!

**Review by bagder — CHANGES_REQUESTED** [review]
libcurl should not be controlled by environment variables like this. It makes it very inconvenient for applications. There is an API that should rather be used.

**Comment by bagder** [comment]
This needs further discussion and deliberation.

**Pull request closed without merging**
