### PR TITLE
H2 upload busy loop fix

### PR DESCRIPTION
**Pull request by icing**
Fixing busy loop on large uploads for HTTP/2.

- refs #10449 with improvements in h2_cf_send() and nwritten return code
  handling. Cherry picked and improved after review by @jay
- setting KEEP_SEND_PAUSE flags when exhausting remote HTTP/2 window
  size of a stream.
- clearing KEEP_SEND_PAUSE when receiving HTTP/2 window updates
  on a paused stream.

Refs #10618

### CODE REVIEW

**Comment by jay** [comment]
Cursory tests in windows host and linux guest are ok. There appears to be some wild speed variations, especially on download, but I think it's the website because I get the same variations with --http1.1. I will try tomorrow to run the profilers to compare before the refactor against this fix.

**Comment by bagder** [comment]
Even if there is "wild speed variations" that would be a separate issue, as this is about fixing https://github.com/curl/curl/issues/10618

**Comment by jay** [comment]
Thanks! I landed it after moving logical operators at the beginning of a line to the end of the previous line, as described in [code style](https://github.com/curl/curl/blob/master/docs/CODE_STYLE.md#column-alignment).

> Even if there is "wild speed variations" that would be a separate issue, as this is about fixing #10618

At the time it was too soon to tell.

**Comment by jay** [comment]
@bagder Can you take a look at this, because it looks possible that if KEEP_SEND_PAUSE is set outside of curl_easy_pause it may be possible that http2 can now unpause sending when the user has paused it with curl_easy_pause. Also, curl_easy_pause has some additional pause/unpause logic (like to [unpause mime sending](https://github.com/curl/curl/blob/d9ccc75b007aefb2b706ce1976ddadc39531fa23/lib/easy.c#L1096-L1102)).I see a KEEP_SEND_HOLD but it is not used anywhere.

**Comment by icing** [comment]
@jay and @bagder: I agree that the semantics of this keepon handling are uncleear. Jay is correct to point out that the h2 busy loop fix might interfere with other uses of keepon.However, h2 needs flow control other than socket events (and h3 as well) and there seems to be no other mechanism in curl.Am 02.03.2023 um 04:43 schrieb Jay Satiro ***@***.***>:﻿
@bagder Can you take a look at this, because it looks possible that if KEEP_SEND_PAUSE is set outside of curl_easy_pause it may be possible that http2 can now unpause sending when the user has paused it with curl_easy_pause. Also, curl_easy_pause has some additional pause/unpause logic (like to unpause mime sending).I see a KEEP_SEND_HOLD but it is not used anywhere.

**Comment by jay** [comment]
Do you know for certain that the cause of #10618 was a flow control issue, and do you know how the refactor caused the bug?

**Comment by icing** [comment]
@jay I added test case `test_07_31_put_10m` to reproduce and the fix the issue.

The test uploads 10MB to a url that does a 10ms delay between accepting data chunks from the client. This causes the HTTP/2 upstream window for that stream to become full. And stay full for 10ms again and again.

On the curl side, this led to 100% cpu without progress, as the transfer loop was calling readwrite again and again only to get -1, CURLE_AGAIN all the time.

I am not claiming this change fixes all possible busy loops, but the one exposed in `test_07_31_put_10m`.

**Comment by jay** [comment]
I think we should open it as an issue because curl8 is coming and we can't have curl_easy_pause sporadically unpausing, and also I'm concerned about the additional unpause logic in the function. I don't think it's going to work properly to also use it for flow control. I haven't had enough time to look into this. I will try tomorrow but unless I come up with something I will open it as a new issue.

**Pull request closed without merging**
