### PR TITLE
New ARM CI because Circle CI seems to have removed the arm hosts

### PR DESCRIPTION
**Pull request by pheiduck**
reference: https://github.com/curl/curl/pull/8630#issuecomment-1077675400
@bagder I need your feedback about it, and its still in progress. ;)

### CODE REVIEW

**Comment by pheiduck** [comment]
And yes, I need to touch up here and there, I still need to figure that out. I just wanted to put that as an idea

**Comment by bagder** [comment]
Seems like a fine idea!

**Comment by pheiduck** [comment]
maybe we should use fosshost for this @bagder?

**Comment by pheiduck** [comment]
not sure why this does not execute the commands :/

**Comment by pheiduck** [comment]
Best solution for this is fosshost + selfhosted arm runner

**Comment by pheiduck** [comment]
How much space does the Hyper Build need?

**Comment by pheiduck** [comment]
I think we should go with fosshost and selfhosted arm runner on it.

**Comment by pheiduck** [comment]
Or Azure CLI can also be used for this.

**Comment by pheiduck** [comment]
Otherwise we use builds as documented

**Comment by pheiduck** [comment]
I think we need another solution for this :( I don’t get this to work.

**Pull request closed without merging**
