### PR TITLE
schannel: check for close notify on ssl shutdown

### PR DESCRIPTION
**Pull request by jay**
- Revert "schannel: ignore error on recv beyond close notify".

- During Schannel SSL shutdown do not error if schannel_recv failed but the close notify flag was set.

This is a revert of the change earlier today so that we again error on a recv call for more bytes after a close notify has been received. The change to ignore the error was made to allow SSL shutdown to call schannel_recv with 1024 bytes and not have it error, however in other cases attempting to read more data should remain an error. Therefore this is best addressed in SSL shutdown instead.

Closes #xxxx

### CODE REVIEW

**Comment by icing** [comment]
Hmm, I am not sure. The error suppression is done *when the close notify* has been decoded from the buffer, as I read the Schannel code. This would not happen again on a receive after that, I think?

**Comment by jay** [comment]
By ignoring the error that means the unrecoverable error flag `recv_unrecoverable_err` is not set so future recv calls will not return that error. Instead they will see the close notify flag is set and goto cleanup, presumably with no data

https://github.com/curl/curl/blob/ac7ae08f0259a2e956d805b6d769d498fb5044be/lib/vtls/schannel.c#L2138-L2152

so I'm thinking of a situation where curl is calling schannel_recv for some data --not during a shutdown-- and it sees the close notify flag and returns 0 with err set to CURLE_OK and that just happens repeatedly. I'm just not sure offhand if that can actually happen...

**Comment by FrankBosmansDtn** [comment]
This fix broke it again :(
```
> RETR 505
< 150 Opening data channel for file download from server of "/505"
* Maxdownload = -1
* Getting file with size: 10
* STATE: DOING_MORE => DID handle 0x133c228; line 2563
* STATE: DID => PERFORMING handle 0x133c228; line 2587
* shutdown start on secondary connection
* schannel: shutting down SSL/TLS connection with localhost port 21
* Recv failure: Connection was aborted
* schannel: recv returned CURLE_RECV_ERROR
* schannel: server close notification received (close_notify)
* sendrecv_dl() -> 56
* Curl_sendrecv() -> 56
* multi_done[PERFORMING]: status: 56 prem: 1 done: 0
* schannel: clear security context handle
* Curl_multi_closed, fd=616 multi is 0x133d110
* Curl_multi_closed, fd=616 entry is (nil)
* multi_done, not reusing connection=0, forbid=0, close=1, premature=1, conn_multiplex=0
* Curl_disconnect(conn #0, aborted=1)
* closing connection #0
* connection #0, shutdown protocol handler (aborted=1)
* [CCACHE] closing #0
* schannel: clear security context handle
* Curl_multi_closed, fd=368 multi is 0x133d110
* Curl_multi_closed, fd=368 entry is (nil)
* Expire cleared
Test ended with result 56
```

**Comment by jay** [comment]
Thanks for testing. Interesting. I will have to think on this some more then.

**Pull request closed without merging**
