### PR TITLE
Fix CURLOPT_SSLCERT_BLOB for OpenSSL

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
Fix for CURLOPT_SSLCERT_BLOB

https://github.com/curl/curl/issues/6816

### CODE REVIEW

**Comment by MonkeybreadSoftware** [comment]
There may be more places, where CURL should clone/create a fresh BIO before passing in to openssl and reusing it later.

**Comment by bagder** [comment]
cc @gvollant

**Comment by gvollant** [comment]
I read text on #6816 , I first try understand the problem.

On ossl_connect_step1, we create the BIO* ssl_cert_bio, call cert_stuff, and then call BIO_free.

So, I suppose cert_stuff itself reuse the BIO*. Pehaps 

```
    if((!key_file) && (!key_bio)) {
      key_file = cert_file;
      key_bio = cert_bio;
   } 
```

pehaps we need only bopy the bio if key_bio and key_file are NULL...

**Comment by gvollant** [comment]
> 
> 
> Yes, you may find a better fix. Maybe it would better to pass around the curl_blob pointer instead of the BIO and create a BIO when needed.

You are right. Do you find other dangerous bio reuse in the code?

**Comment by gvollant** [comment]
and if you need workaround on current curl version, you can probably give the same blob as CURLOPT_SSLKEY_BLOB and CURLOPT_SSLCERT_BLOB

**Comment by MonkeybreadSoftware** [comment]
I just looked into the SSL Key, but the same may happen with certificate.
As said, a BIO is a stream and functions like SSL_CTX_use_PrivateKey_bio, SSL_CTX_use_certificate_chain_bio and SSL_CTX_use_certificate_bio may consume the data and then it's empty after it. The clone helps for my case.

**Comment by gvollant** [comment]
> SSL_CTX_use_PrivateKey_bio, SSL_CTX_use_certificate_chain_bio

So the most secure idea is remplace these function by SSL_CTX_use_PrivateKey_membuffer and SSL_CTX_use_certificate_chain_membuffer, and create local bio, use and immediatly free it.

**Comment by gvollant** [comment]
I created another fix #6820

The real work (understand the problem) was made by you, @MonkeybreadSoftware

**Comment by MonkeybreadSoftware** [comment]
Thanks for your work. I close this.

**Pull request closed without merging**
