### PR TITLE
The final conn data removals!

### PR DESCRIPTION
**Pull request by bagder**
This set completely removes the struct member `data` from `connectdata`.

It merges #6515 from @monnerat and #6511, #6512, #6513 from myself and then cleans up the remainders.

The OpenSSL edit probably needs further attention before we can merge.

### CODE REVIEW

**Comment by bagder** [comment]
The OpenSSL take is not working like this.

**Comment by monnerat** [comment]
> The OpenSSL take is not working like this.

I confirm: test 1561 fails.
I'm currently working on a solution as we discussed in a previous PR.

Likewise, in openldap, the ldapsb_tls_* stuff seems very similar and some care should be taken about it, mainly because we have no test for it.

**Comment by bagder** [comment]
>  I'm currently working on a solution as we discussed in a previous PR.

I tried that, but it doesn't seem to be working quite correctly either. I believe it is because there's a lag or something in the pointer that it passes on.

**Comment by bagder** [comment]
> Likewise, in openldap, the ldapsb_tls_* stuff seems very similar and some care should be taken about it, mainly because we have no test for it.

But we also don't do persistent connections with LDAP, so the connection <=> transfer association should be fairly fixed...

**Comment by bagder** [comment]
I'll get back with a new take soon.

**Pull request closed without merging**
