### PR TITLE
Feature/checksrc space o

### PR DESCRIPTION
**Pull request by gbrlmarn**
Added rule to check for spaces around bitwise OR operator.

### CODE REVIEW

**Comment by bagder** [comment]
Hm, almost all existing code using bitwise OR do that *without* a space. I think that rather says that we prefer to allow these to be used without spaces.

**Comment by gbrlmarn** [comment]
Ok. Is this also true for other bitwise operators, for example bitwise AND?
Also I saw some uses of bitwise OR with spaces around, It would be a good idea to remove spaces there?

**Comment by jay** [comment]
I think either way is ok.

**Comment by gbrlmarn** [comment]
Ok, thank you for the response,
I will close this pull request.

**Pull request closed without merging**
