### PR TITLE
mqtt: add support for username and password

### PR DESCRIPTION
**Pull request by bagder**
Added test 2200 to 2205

This is #7117, rebased, edited, cleaned up and with an added test (2205) case that currently breaks.

/cc @Gealber

### CODE REVIEW

**Comment by bagder** [comment]
@Gealber the code doesn't check for too long user name or password or total packet size. it needs to error out then and not silently truncate.

**Comment by Gealber** [comment]
Reading [3.1.3.5 Password](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349247) it seems that the maximum amount of bytes for password is 65535 bytes. While on the [3.1.3.4 User Name](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349247) they say
> The User Name MUST be a UTF-8 encoded string as defined in Section 1.5.3 

and in this section they specify that

> Unless stated otherwise all UTF-8 encoded strings can have any length in the range 0 to 65535 bytes.

So in both case it needs to be checked that they are below 65535 bytes.

**Comment by bagder** [comment]
... then you also need to make sure the code uses more than the single byte it uses now to store the lengths!

**Comment by bagder** [comment]
#7243 replaces this

**Pull request closed without merging**
