### PR TITLE
move authneg bit

### PR DESCRIPTION
**Pull request by icing**
- from `conn->bits.authneg` to `data->req.authneg`
- AFAICT, this is a property of the request about to be made and not a property of the connection
- in multiuse connections, transfer could step on each others toes here potentially.

### CODE REVIEW

**Comment by jay** [comment]
hm. I feel like there was probably a good reason authneg was put on the connection level... maybe because of authentications that are connection level and not request level like NTLM and that is why?

**Comment by icing** [comment]
AFAICT, it was only used to make the special tweaks for an empty PUT/POST when auth negotiation was still ongoing.

**Comment by jay** [comment]
@iboukris

**Review by bagder — APPROVED** [review]
I believe this is a correct change.

**Pull request closed without merging**
