### PR TITLE
[snap] Add 'snap/snapcraft.yaml'

### PR DESCRIPTION
**Pull request by alexmcan**
A snap is a bundle of your app and its dependencies that works without modification across Linux.
Snaps are discoverable and installable from the Snap store.

### CODE REVIEW

**Comment by danielgustafsson** [comment]
Since curl/libcurl is packaged by most Linux distros and already available, why would we want take on the role of packagers ourselves like this?

**Comment by bagder** [comment]
I agree with @danielgustafsson. This is just another file with meta/config information for a specific distribution to make a certain kind of curl package. I don't understand the value in having us include this and host it in our git. We don't ship "snaps".

It feels like this file should rather be hosted where it is actually *used*!

**Comment by flexiondotorg** [comment]
Snaps are not distribution specific, there are currently millions of snaps installed across ~50 distributions. The benefit of curl publishing a snap is that you are in complete control of the release process, can provide the freshest version of curl to multiple Linux distros and decouple the version of curl available from distro release/support windows.

`snapcraft.yaml` tend to be fairly static over time and have minimal maintenance overhead. The build process can be automated via the free [Snapcraft build service](https://build.snapcraft.io) or CI such as [Travis Snap integration](https://docs.travis-ci.com/user/deployment/snaps/) or [Circle Snap Build and Publish](https://circleci.com/docs/2.0/build-publish-snap-packages/).

**Comment by danielgustafsson** [comment]
> Snaps are not distribution specific, there are currently millions of snaps installed across ~50 distributions. The benefit of curl publishing a snap is that you are in complete control of the release process, can provide the freshest version of curl to multiple Linux distros and decouple the version of curl available from distro release/support windows.

Packagers are today taking on a large responsibility in testing to ensure that curl works well on their respective system. The chance of the distro shipping software as part of the distro itself which depends on libcurl is fairly high. Assuming the role of distributors of curl/libcurl puts the burden of verifying and testing on us which is a task I doubt we have the resources to handle.

**Comment by bagder** [comment]
> Snaps are not distribution specific

Those package names the file lists surely won't be the names used by every distro out there? They seem to imply versions and a naming scheme specific to one or more specific distros.

To further illustrate why this isn't a good place for this file. We don't know what the contents of this file is or why it looks like this.

Why does it list python as a build package? Why does it list nss3-dev  + gnutls + a openssl lib as build packages? It lists libtool but not autoconf nor automake? Why does it install curl in usr/local/bin ? Surely that's very unorthodox for a distro to do?

It seems like this file is better taken care of by someone who knows about the file format, who uses the file and who can explain why it looks like it does. And also maintain and update it whenever that's suitable.

**Comment by flexiondotorg** [comment]
@bagder Correct, the `build-packages` and `stage-packages` in the yaml reference packages from the Ubuntu archive. In order for snaps to work across distributions a "base" snap is used to provide the required compatiibility. The default base uses a thin Ubuntu runtime, so the build and stage packages also reference Ubuntu packages. Bases for other distros are being created.

A snap is a squashfs filesystem that bundles all the runtime requirements. Snaps use container primitives to isolate them from the host OS, the contents of a snap is not installed over the host OS but instead mounted as a loopback device with `snapd` mediating access. So, where binaries are installed with in the context of the snap are not so important. Although, I agree I'd like to see a `prefix=/usr` passed to this build, @alexmcan can you update that please. 

Looking at the proposed yaml in this PR, I can see that it could be improved somewhat. @alexmcan Can you update this PR so the `snapcraft.yaml` uses the autotools plugin. Please also review the `build-packages` and `stage-packages` and remove any unneccessary packages. For example, you should not stage `libcurl3-gnutls` since that would be a library potentially built inside the snap and `libc` is in the base snap, so need to stage it.

**Comment by alexmcan** [comment]
Hi, sorry for the late reply. Yes, I'll have a look and update what's needed.

**Comment by danielgustafsson** [comment]
Any progress on the mentioned changes in this PR?

**Comment by bagder** [comment]
I have not seen any strong motivation for merging this into the curl repository, as we would not use it ourselves. I can only repeat that I think those who wants to use this file should host it as they have the incentive to keep it up to date and working.

Closing.

**Pull request closed without merging**
