### PR TITLE
CI: macOS fixup nghttp2 install

### PR DESCRIPTION
**Pull request by pheiduck**
branch rename of https://github.com/curl/curl/pull/10287
CI issue: https://github.com/curl/curl/actions/runs/3904373833/jobs/6670071643#step:3:590
Goal fixup macOS github CIs to install nghttp2
Solved by uninstall both Python3 versions 3.11 and 3.10
3.9 is used to install pip pkgs.

### CODE REVIEW

**Comment by pheiduck** [comment]
So the issue seems to be python 3.11 is installed twice. https://github.com/orgs/Homebrew/discussions/4117#discussioncomment-4690084

**Comment by jay** [comment]
Do you have a reference to the brew issue that caused this problem?

**Comment by pheiduck** [comment]
> ~Do you have a reference to the brew issue that caused this problem?~ Nevermind, I missed your post above. So, can't we just stop it from being installed twice? Where is that happening?

```
==> Pouring python@3.10--3.10.9.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.10

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.10

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3-config
==> /usr/local/Cellar/python@3.10/3.10.9/bin/python3.10 -m ensurepip
==> /usr/local/Cellar/python@3.10/3.10.9/bin/python3.10 -m pip install -v --no-d
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python@3.10/libexec/bin

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.10/site-packages

tkinter is no longer included with this formula, but it is available separately:
  brew install python-tk@3.10

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python@3.10/3.10.9: 3,108 files, 56.4MB
==> Running `brew cleanup python@3.10`...
Removing: /usr/local/Cellar/python@3.10/3.10.8... (3,136 files, 56.9MB)
Removing: /Users/runner/Library/Caches/Homebrew/python@3.10--3.10.8... (14.6MB)
==> Upgrading python@3.11
  3.11.0 -> 3.11.1 

==> Pouring python@3.11--3.11.1.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-3.11
Target /usr/local/bin/2to3-3.11
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3-3.11'
```

**Comment by pheiduck** [comment]
@jay we can try:
```
brew link --overwrite python@3.10
brew link --overwrite python@3.11
```

**Comment by pheiduck** [comment]
@jay overwrite symlink does not help same error.
So I think the solution is to get rid of Python 3.10 and 3.11 as long as possible

**Comment by jay** [comment]
What doesn't make sense to me is why we have to do that. It seems like we are coming in after the fact on cleanup when this shouldn't happen in the first place. Why does it happen? Isn't this a brew problem?

**Comment by pheiduck** [comment]
@jay the PR is now no longer necessary, since the CI toolchain was updated yesterday https://github.com/actions/runner-images/commit/fda2b5e0d667a52902356cec0c296872dfd56056

**Pull request closed without merging**
