### PR TITLE
Test for HTTP/2 corruption as reported in #10525

### PR DESCRIPTION
**Pull request by icing**
- adding test_02_20 for reproducing the situation
- using recently released mod_h2 Apache module
- skipping test if an older version is installed
- adding installation of current mod_h2 to github pytest workflow

This reproduces the error reliable (for me) on the lib/http2.c version of curl 7.88.0. And passes with the recent curl master.

### CODE REVIEW

**Comment by pheiduck** [comment]
libnghttp2 was not found.
https://github.com/curl/curl/actions/runs/4194306873/jobs/7272293483#step:7:111

**Comment by pheiduck** [comment]
@icing it introduce a bug which need to be fixed on mod_h2 it self.
https://github.com/curl/curl/actions/runs/4194419967/jobs/7272559234#step:7:189

**Comment by icing** [comment]
> @icing it introduce a bug which need to be fixed on mod_h2 it self.
> https://github.com/curl/curl/actions/runs/4194419967/jobs/7272559234#step:7:188

Thanks, currently trying to add support for building against old versions of httpd. ubuntu latest is a bit lagging behind here.

**Comment by pheiduck** [comment]
@icing it needs to be removed after install

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
