### PR TITLE
cmake: Only refer to .pc files for GSS-API if found

### PR DESCRIPTION
**Pull request by diizzyy**
Only refer to pkg-config files if they're found otherwise omit adding reference to Requires.private in curl's .pc file

### CODE REVIEW

**Comment by diizzyy** [comment]
@vszakats 
I think I understood the logic correctly

**Comment by vszakats** [comment]
Thanks for your report and patch.

Do I understand correctly that GSS is correctly detected, but you don't want this detection to trigger adding `heimdal-gssapi` to the `Required.private` list in this particular case? Does FreeBSD not have a `.pc` file?

**Comment by diizzyy** [comment]
@vszakats 
Yes, that's exactly the case but it should still validate irregardless how GSS was detected.

**Comment by vszakats** [comment]
> @vszakats Yes, that's exactly the case but it should still validate irregardless how GSS was detected.

Would it be a solution to skip adding this reference when the target OS is FreeBSD?
In both CMake and autotools.

Something like:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -1246,7 +1246,9 @@ if(CURL_USE_GSSAPI)
     elseif(GSS_FLAVOUR STREQUAL "MIT")
       list(APPEND LIBCURL_PC_REQUIRES_PRIVATE "mit-krb5-gssapi")
     else()  # Heimdal
-      list(APPEND LIBCURL_PC_REQUIRES_PRIVATE "heimdal-gssapi")
+      if(NOT CMAKE_SYSTEM_NAME STREQUAL "FreeBSD")
+        list(APPEND LIBCURL_PC_REQUIRES_PRIVATE "heimdal-gssapi")
+      endif()
     endif()
   else()
     message(WARNING "GSSAPI has been requested, but no supporting libraries found. Skipping.")
--- a/configure.ac
+++ b/configure.ac
@@ -2071,7 +2071,13 @@ if test x"$want_gss" = xyes; then
   if test -n "$gnu_gss"; then
     LIBCURL_PC_REQUIRES_PRIVATE="$LIBCURL_PC_REQUIRES_PRIVATE gss"
   elif test "x$not_mit" = "x1"; then
-    LIBCURL_PC_REQUIRES_PRIVATE="$LIBCURL_PC_REQUIRES_PRIVATE heimdal-gssapi"
+    case $host_os in
+      freebsd*)
+        ;;
+      *)
+        LIBCURL_PC_REQUIRES_PRIVATE="$LIBCURL_PC_REQUIRES_PRIVATE heimdal-gssapi"
+        ;;
+    esac
   else
     LIBCURL_PC_REQUIRES_PRIVATE="$LIBCURL_PC_REQUIRES_PRIVATE mit-krb5-gssapi"
   fi
```

**Comment by diizzyy** [comment]
That would break if you use the port which is a valid configuration,
https://cgit.freebsd.org/ports/tree/security/heimdal/pkg-plist#n201
https://cgit.freebsd.org/ports/tree/Mk/Uses/gssapi.mk

**Comment by vszakats** [comment]
> That would break if you use the port which is a valid configuration, https://cgit.freebsd.org/ports/tree/security/heimdal/pkg-plist#n201 https://cgit.freebsd.org/ports/tree/Mk/Uses/gssapi.mk

There a "base-gssapi" package on FreeBSD which is installed by default, and a port that is `heimdal-gssapi`, is that correct?

If so, perhaps we should make a new "base-gssapi" GSS flavour, adjust detections to detect and return this flavour, then skip adding it to the pc dependency list for this flavour?

**Comment by diizzyy** [comment]
No, "base" refers to the bundled version included in the OS which is the one you see get detected in the CI logs.
The ported (packaged) versions needs to be installed as any other package.

**Comment by vszakats** [comment]
> No, "base" refers to the bundled version included in the OS which is the one you see get detected in the CI logs. The ported (packaged) versions needs to be installed as any other package.

That is what I meant, so I don't understand the "no". Is there is isn't two distinct kind of GSS implementations on FreeBSD? One with `.pc` files, one without?

**Comment by diizzyy** [comment]
You have 3 variants,
base: (heimdal, without .pc files)
ports: (heimdal and mit shipped with .pc files)
So validating by OS is incorrect and in general seems an odd choice instead of just doing a global check.

**Comment by vszakats** [comment]
> You have 3 variants, base: (heimdal, without .pc files) ports: (heimdal and mit shipped with .pc files) So validating by OS is incorrect and in general seems an odd choice instead of just doing a global check.

We want to depend on the `.pc` file regardless of how GSS was detected on the build host. On another machine GSS may be available via `.pc` file, even if it isn't on the build host.

Except on FreeBSD where there seem to be multiple flavour of heimdal, one with a .pc file, one without, and they cannot be mixed with each other, if I understand correctly.

If that's the case we have not 3 but 4 "flavours".

**Comment by diizzyy** [comment]
I really don't see where this would be an issue in practice where you'd have a "desynced" build root/host compaed to run host, if you insist make it a toggle instead of adding os/distro specific hacks?

**Comment by vszakats** [comment]
> I really don't see where this would be an issue in practice where you'd have a "desynced" build root/host compaed to run host, if you insist make it a toggle instead of adding os/distro specific hacks?

Thinking in generic terms, are you saying that a `.pc` reference should only be added if the `Requires` list the dependency if we detected it via `pkg-config`?

**Comment by diizzyy** [comment]
Yes, that's what I'm suggesting

**Comment by vszakats** [comment]
This might be a way to deal with, but it assumes that curl itself and its dependents are
built in the same build environment. This is not true in some envs, notably non-unix ones,
certain cross-builds, possibly more. Question if `.pc` files are used in these scenarios,
or this would be something undesired in such env.

It also flies in the face of idea that a `.pc` file should describe the dependencies and it's
up to the user (builder) to ignore what's missing and use whatever parts of the config
that helps completing a build. This might be my idea, but it's kind of hard to figure out
what the original intention (there is almost no documentation).

Such solution will also result in different `.pc` files depending on the private details
of how a certain dependency was detected in a build, for builds that are otherwise
identical.

In practice it also means that implementation details of curl's autotools and cmake
dependency detection will affect the generated `.pc` files. Even such tiny ones as
the detection order when using multiple methods for a given dependency.
(I think this might okay, `pkg-config` is done first most if not all of the time.)

CMake doesn't yet have `pkg-config`-based detection for certain dependencies.
This has been worked on recently and pending completion in #15408. Scheduled
for the next release.

Assuming we want to go with this solution, this is important to merge first, otherwise
these components would always miss their `Require` entry when using CMake. As
would have many others before implementing native `pkg-support` for them earlier.

Such change will be a relatively large one because we'd need to keep track the
detection method for all dependencies in both autotools and cmake, and change
the logic to update the requires list based on that.

A lighter solution is to implement this solely for the problematic ones, which seem
to be (so far) GSS, LDAP, mbedTLS, Rustls and MSH3.

Of these, LDAP is also pending a detection overhaul in CMake: #15273, adding
`pkg-config` support too.

**Comment by vszakats** [comment]
Patch proposal: #15573

**Pull request closed without merging**
