### PR TITLE
BigGuy573/curl/bigguy573-curl.1-main.yml

### PR DESCRIPTION
**Pull request by BigGuy573**

### CODE REVIEW

**Comment by jzakrzewski** [comment]
@BigGuy573 are you asking for [a ban](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization)?
Those changes are completely bogus.

**Comment by emilengler** [comment]
STOP!

**Comment by BigGuy573** [comment]
@emilengler thanks, I'm trying to figure this out.  I get confused a bit at times.  My apologies.

**Comment by bagder** [comment]
And again you didn't submit any description. You're not really trying.

**Pull request closed without merging**
