### PR TITLE
use valgrind on more tests

### PR DESCRIPTION
**Pull request by bagder**
We've learned before that disabling valgrind on purpose can lead to bugs sneaking in without us noticing them...

### CODE REVIEW

**Comment by kdudka** [comment]
This makes the test-suite unusable on my Gentoo Linux with ```libssh2-1.7.0``` and ```openssl-1.0.2k```.  I am attaching the output: [test.log.zip](https://github.com/curl/curl/files/1217250/test.log.zip)

**Comment by bagder** [comment]
Wow. Yeah I realize it is rather futile to try to land this right now. I think perhaps I need a way for *me* to run these tests without valgrind but not disable it for everyone. Not sure exactly how I want to control that...

Your valgrind errrors are very different to the ones I've got. Especially the `sendto()` one looks like it is a genuine bug in libssh2/libcurl and not just a false positive caused by the crypto backend. Do you also get them with libssh2 1.8.0? If so they could be worth digging into.

The `BN` ones and a few others seem to be OpenSSL's problems.

**Comment by kdudka** [comment]
I am observing the uses of uninitialized memory with ```libssh2-1.8.0-39-g6762664```, too:
```
 ==17559== Syscall param socketcall.sendto(msg) points to uninitialised byte(s)
 ==17559==    at 0x64BF45D: send (in /lib64/libpthread-2.23.so)
 ==17559==    by 0x4E4C96E: _libssh2_send (misc.c:164)
 ==17559==    by 0x4E64D17: _libssh2_transport_send (transport.c:862)
 ==17559==    by 0x4E55A87: session_startup (session.c:749)
 ==17559==    by 0x4E55C49: libssh2_session_handshake (session.c:804)
 ==17559==    by 0x50D8DDB: ssh_statemach_act (ssh.c:737)
 ==17559==    by 0x50DEFFC: ssh_multi_statemach (ssh.c:2813)
 ==17559==    by 0x50AC025: Curl_protocol_connecting (url.c:3974)
 ==17559==    by 0x50CB9CD: multi_runsingle (multi.c:1622)
 ==17559==    by 0x50CCB77: curl_multi_perform (multi.c:2160)
 ==17559==    by 0x50BFD60: easy_transfer (easy.c:708)
 ==17559==    by 0x50BFF9F: easy_perform (easy.c:794)
 ==17559==    by 0x50C0006: curl_easy_perform (easy.c:813)
 ==17559==    by 0x415469: operate_do (tool_operate.c:1563)
 ==17559==    by 0x4167CB: operate (tool_operate.c:2064)
 ==17559==    by 0x40EFF9: main (tool_main.c:252)
 ==17559==  Address 0x72d95b0 is 17,040 bytes inside a block of size 54,576 alloc'd
 ==17559==    at 0x4C2BF6F: malloc (vg_replace_malloc.c:299)
 ==17559==    by 0x50C440A: curl_domalloc (memdebug.c:175)
 ==17559==    by 0x50D8333: my_libssh2_malloc (ssh.c:318)
 ==17559==    by 0x4E55382: libssh2_session_init_ex (session.c:487)
 ==17559==    by 0x50DF33F: ssh_connect (ssh.c:2930)
 ==17559==    by 0x50AC1CB: Curl_protocol_connect (url.c:4046)
 ==17559==    by 0x50CB8F3: multi_runsingle (multi.c:1602)
 ==17559==    by 0x50CCB77: curl_multi_perform (multi.c:2160)
 ==17559==    by 0x50BFD60: easy_transfer (easy.c:708)
 ==17559==    by 0x50BFF9F: easy_perform (easy.c:794)
 ==17559==    by 0x50C0006: curl_easy_perform (easy.c:813)
 ==17559==    by 0x415469: operate_do (tool_operate.c:1563)
 ==17559==    by 0x4167CB: operate (tool_operate.c:2064)
 ==17559==    by 0x40EFF9: main (tool_main.c:252)
```

**Comment by bagder** [comment]
simply too many false positives to make this worthwhile

**Pull request closed without merging**
