### PR TITLE
Update libssh2.c

### PR DESCRIPTION
**Pull request by MonkeybreadSoftware**
Added NULL check for password and user name for libssh2.c

### CODE REVIEW

**Comment by bagder** [comment]
@MonkeybreadSoftware this PR fails the CI tests due to checksrc failures

**Comment by MonkeybreadSoftware** [comment]
Well, I thought, we my better close this and you put the check on a central place to make sure username and password are not empty. Or for SFTP when those values are passed to transfer object.
Instead of adding for all protocols the NULL checks.

**Comment by jay** [comment]
Is this still needed now that #6691 is fixed? (Same question is in #6695..)

**Comment by bagder** [comment]
The #6782 change fixed this problem more appropriately, we should close this.

**Pull request closed without merging**
