### PR TITLE
test651: curl_formadd with huge COPYCONTENTS

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
ping @monnerat, we got an interesting regression reported by @jeroen that I just managed to reproduce with this test case and the amended commit. It shows that the output data is somehow repeating after the first 16K!

**Comment by bagder** [comment]
I think that fixes it, just needs to run through the CI to make sure nothing breaks while I run some more tests locally as well.

**Comment by jeroen** [comment]
Thanks for the quick fix! Are there plans for a patch release soon, or should i better cherry pick the patch into my deployment?

**Comment by bagder** [comment]
I have had discussions with some peeps about about a possible patch release but not properly (ie not on the mailing list) and nothing has been decided yet. And even if we will decide to make one, it will be at a set date at least one week into the future.

**Pull request closed without merging**
