### PR TITLE
CI: freebsd build heimdal from source

### PR DESCRIPTION
**Pull request by pheiduck**
freebsd have dropped heimdal?

### CODE REVIEW

**Comment by danielgustafsson** [comment]
I'm not sure why pkg install fails, but don't think heimdal has been dropped: https://www.freshports.org/security/heimdal/

`pkg install heimdal` works fine on my FreeBSD 14 box, but I don't have a 13 installation to try on. The db5 package which it depends on is however deprecated (yet still available), maybe that holds a clue?

**Comment by pheiduck** [comment]
it is no longer found on 12 and 13:
```
pkg: No packages available to install matching 'heimdal' have been found in the repositories
```

**Comment by danielgustafsson** [comment]
That could just as well be an issue with the mirror though? As it's still in the ports tree, listed as a package and installable on FreeBSD 14 it seems there is more to this. If we do anything, shouldn't we the use the [ports tree entry for heimdal](https://cgit.freebsd.org/ports/tree/security/heimdal) to ensure we are building a version representative of what users might have?

**Comment by pheiduck** [comment]
okay, then we'll wait and see how it develops.
I split the PR so we can merge the pip install fix

**Comment by pheiduck** [comment]
Will be closed its solved on 13.1 maybe 12.4 later as well

**Pull request closed without merging**
