### PR TITLE
Finish curlx_tvnow rename; provide backward-compatible curlx names

### PR DESCRIPTION
**Pull request by dtikhonov**

### CODE REVIEW

**Comment by bagder** [comment]
but why do we want those names preserved?

**Comment by dtikhonov** [comment]
I figured we need them because INTERNALS.md says that they are provided.  I did not think I know enough to modify INTERNALS.md, as I don't know what your plans for these functions are.

**Comment by bagder** [comment]
Aha, ok so now they're no longer mentioned in INTERNALS since 647f9aea6 =)

**Comment by dtikhonov** [comment]
Should curlx.h even provide timeval.h anymore?

**Comment by bagder** [comment]
Good point, I forgot about that file. No, it shouldn't. I'll clean that up as well. Thanks!

**Comment by dtikhonov** [comment]
Closing: nothing to do.

**Pull request closed without merging**
