### PR TITLE
support .P12 or .PFX certificat client file with MS-Windows Schannel

### PR DESCRIPTION
**Pull request by gvollant**
support .P12 or .PFX certificat client file with MS-Windows Schannel
to be used with curl command line option: --cert <filename>:<password> --cert-type p12

### CODE REVIEW

**Comment by bagder** [comment]
The first windows build on appveyor says this:
~~~
2>schannel.c
2>.\vtls\schannel.c(653) : error C2220: warning treated as error - no 'object' file generated
2>.\vtls\schannel.c(653) : warning C4013: 'Curl_convert_UTF8_to_wchar' undefined; assuming extern returning int
2>.\vtls\schannel.c(653) : warning C4047: '=' : 'WCHAR *' differs in levels of indirection from 'int'

**Comment by gvollant** [comment]
Yes, Curl_convert_UTF8_to_wchar is not avaiable in all build option

 

I just commited a new version

 

De : Daniel Stenberg [mailto:notifications@github.com] 
Envoyé : dimanche 15 septembre 2019 17:03
À : curl/curl
Cc : gvollant; Author
Objet : Re: [curl/curl] support .P12 or .PFX certificat client file with MS-Windows Schannel (#4356)

 

The first windows build on appveyor says this:

2>schannel.c
2>.\vtls\schannel.c(653) : error C2220: warning treated as error - no 'object' file generated
2>.\vtls\schannel.c(653) : warning C4013: 'Curl_convert_UTF8_to_wchar' undefined; assuming extern returning int
2>.\vtls\schannel.c(653) : warning C4047: '=' : 'WCHAR *' differs in levels of indirection from 'int'

**Comment by gvollant** [comment]
I done the squash

**Comment by gvollant** [comment]
All the change from this PR are included in #4371. 
So if 4371 is merged, we can suppress this #4356

**Comment by gvollant** [comment]
Il feature #4371 cannot be merged now, I suggest reopen and merge #4356 (which is a subset of #4371), because it is more simple

**Comment by bagder** [comment]
We're in a "feature freeze" now until the next release meaning we will only merge bug-fixes until Jan 8, 2020 (when we release 7.68.0). I'd say this PR is not a bugfix so it will have to wait until the window opens again.

Looking at these two PRs, it's not clear to me why this is closed in favor of #4371. This is about reading other file types while the other is about providing said files directly in memory. Shouldn't we offer both?

**Comment by gvollant** [comment]
I closed 4656 just because #4371 is a "superset" of #4656 : all feature of #4656 are included in #4371.

If we are able to integrate #4371 by selecting a way to store binary "blob" parameters, we can just merge #4371 .

**Comment by ryoqun** [comment]
@gvollant Maybe typo? `4656` => `4356`? #4656 seems to be unrelated to this.

**Comment by bagder** [comment]
@gvollant Then the descriptions must be wrong somewhere. Can you point out where I get this wrong?

#4356 - makes it possible to provide `.p12` and `.pfx` *files* (stored on disk) to the cert options when using Schannel.
#4371 - allows a user to provide client certs in memory to libcurl

If we only merge #4371, doesn't that mean that users will have to load the files into memory manually first in order to get the functionality of #4356?

**Comment by gvollant** [comment]
#4371 allow provide .p12/.pfx from file OR from memory buffer using windows schannel

**Comment by gvollant** [comment]
> 
> 
> @gvollant Maybe typo? `4656` => `4356`? #4656 seems to be unrelated to this.

right, I made three PR : #4346, #4356 and #4371

**Pull request closed without merging**
