### PR TITLE
Multiple content encodings and Brotli support

### PR DESCRIPTION
**Pull request by monnerat**
Although I wrote a test for the multi-encoding, I have not been able to find a real server resource providing such data.

I've checked Brotli successfully both with tests and in the real world.

### CODE REVIEW

**Comment by bagder** [comment]
How about an added test or two for it as well?

And if you're brave: try adding a travis build that uses it!

**Comment by monnerat** [comment]
> And if you're brave: try adding a travis build that uses it!

I have already thought about it but no idea how it works and how to install brotli in travis/ubuntu.
I have to dig into it. Hints are welcome!

**Comment by bagder** [comment]
You can make travis download, configure and install custom software with some clever extra hacking. I did that in another project you can look at for some inspiration: https://github.com/NEAT-project/neat/blob/master/.travis.yml

**Comment by monnerat** [comment]
> You can make travis download, configure and ...
Thanks, will try.

**Comment by monnerat** [comment]
@vszakats: thanks for the patch: I'm currently fighting with travis CI, but I will apply it immediately after it.

Once landed in master, there probably will be some updates needed for other non-autotool Makefiles too.

**Comment by vszakats** [comment]
Thank you @monnerat!

**Comment by monnerat** [comment]
@vszakats : you're welcome, although this is still not pushed to master. I won't forget your commit when I'll do :-)

**Comment by monnerat** [comment]
Pushed in master: commits https://github.com/curl/curl/commit/dbcced8e32b50c068ac297106f0502ee200a1ebd, https://github.com/curl/curl/commit/11bf1796cd015373a996e6eb26212e2e1aadb066, https://github.com/curl/curl/commit/609aa62f53387f35eaf728c4e4692badbce68ef2 and https://github.com/curl/curl/commit/c675c40295045d4988eeb6291c54eb48f138822f

**Pull request closed without merging**
