### PR TITLE
Tests for speedcheck, again, plus a weird delay

### PR DESCRIPTION
**Pull request by paulharris**
Hi,
Here are those same tests, put on top of the recent progress fix #1559.
Seems to work well.

But, there is a weird delay I see...

test3004 (see attached) is part of the series I made for speedcheck.
3004 has no write delay, yet there is a 1 second pause.
I zeroed all the wait_ms() calls in sws.c with no effect, so is this a curl.exe thing?

From the server log:
```
10:47:51.047000 ====> Client connect
10:47:51.047077 accept_connection 3 returned 4
10:47:51.047132 accept_connection 3 returned 0
10:47:51.048245 Read 216 bytes
10:47:51.048326 Process 216 bytes request
10:47:51.048390 Got request: POST /3004 HTTP/1.1
10:47:51.048437 Requested test number 3004 part 0
10:47:51.048533 - request found to be complete
10:47:51.048572 Found Content-Length: 143 in the request
// HERE IS THE 1 second pause
10:47:52.049343 Read 143 bytes
10:47:52.049404 Process 359 bytes request [CONTINUED]
10:47:52.049455 - request found to be complete
10:47:52.049472 Wrote request (359 bytes) input to log/server.input
10:47:52.049489 Send response test3004 section <data>
10:47:52.049558 Sent off 200 bytes
10:47:52.049579 Sent off 200 bytes
10:47:52.049599 Sent off 200 bytes
10:47:52.049617 Sent off 200 bytes
10:47:52.049634 Sent off 200 bytes
10:47:52.049651 Sent off 200 bytes
10:47:52.049668 Sent off 200 bytes
10:47:52.049685 Sent off 200 bytes
10:47:52.049702 Sent off 200 bytes
10:47:52.049719 Sent off 200 bytes
10:47:52.049736 Sent off 200 bytes
10:47:52.049753 Sent off 200 bytes
10:47:52.049770 Sent off 200 bytes
10:47:52.049786 Sent off 134 bytes
10:47:52.049803 Response sent (2734 bytes) and written to log/server.response
10:47:52.049815 => persistant connection request ended, awaits new request
```

### CODE REVIEW

**Comment by bagder** [comment]
>  3004 has no write delay, yet there is a 1 second pause.

I presume that's curl waiting for 100-continue...

**Comment by paulharris** [comment]
Ah ok, and out of interest, how do you turn that off for a unit test?
I didn't see anything obvious in the FILEFORMAT text...

**Comment by bagder** [comment]
> how do you turn that off for a unit test? 

That's not a unit test with our terminology though, that's a curl test (unit tests are the tests that verifies individual specific internal libcurl functions that aren't present in the API). And there's nothing magic for the test suite there as you're using the plain curl tool so you need to disable it the "regular way" with `-H Expect:`.

> Is it my (the libcurl library user) job to detect that error number and disable the header for further communications? Or is there something else going on?

Yes it is, unless you can think of a better way to do it... The `Expect: 100-continue` is valid and correct HTTP/1.1 so only a broken server will have a problem with it, but a large number of servers won't care about it at all and cause libcurl to wait in vain. Maybe it is about time to start considering removing that header by default...

**Comment by paulharris** [comment]
re -H in curl-test, oh yes...
So, sws does not respond with the 100-continue, ie its not HTTP/1.1 compliant?
Right?

re the "Broken server", I'm not sure its broken behaviour.
From https://www.w3.org/Protocols/rfc2616/rfc2616-sec8.html
      - If the proxy knows that the version of the next-hop server is
        HTTP/1.0 or lower, it MUST NOT forward the request, and it MUST
        respond with a 417 (Expectation Failed) status.

I read that has, its valid for the proxy to respond with 417 if it knows the next hop can't handle 100-continue.
From my naive perspective, I would prefer libcurl to manage the 100-continue behaviour, and in this case drop Expect:100 header and repost.

From my reading, 100-continue is an optimisation hint, so if the optimisation isn't supported then I (the library user) has no choice but to drop back to posting the whole request each time (no continue-stuff).

**Comment by bagder** [comment]
sws is not really a HTTP server at all, it responds as the test case instructs it so it *can* be HTTP/1.1 compliant but only if told so. I don't remember off-hand how sws handle 100 or not but I'm sure there are room for improvements theres as well.

>  I would prefer libcurl to manage the 100-continue behaviour, and in this case drop Expect:100 header and repost.

I agree that it would be nice, but the most problems people have with Expect: is exactly how you say it: it simply causes a one second delay. Actually getting a 417 response is pretty rare.

**Comment by paulharris** [comment]
Well I had to turn it off due to problems, so I think it is only rare
because people who use corporate proxies don't tend to report bugs or be
developers?

**Comment by bagder** [comment]
Sure that's possible. But it is also possible that your situation actually is rare... But it doesn't matter too much how rare or not it is, it still requires someone to work on the issue if curl is going to handle it better itself.

**Comment by bagder** [comment]
How about rebasing these and trying to make them run fine in the CI ?

**Comment by paulharris** [comment]
I'm working on this.
How do you make a test that should fail?  ie I want to make a test that will be too slow.

**Comment by paulharris** [comment]
The tests are currently very long.  I noticed that you changed the sws speed/sec to 20 bps, so I adjusted the speed thresholds to suit.
TODO is to add some failing tests (to prove that the low speed test will trip), and to reduce the time that the tests need to run.

**Comment by bagder** [comment]
Is this abandoned?

**Comment by paulharris** [comment]
I don't think so.
I worked around the problem by handling the error in my code, same as
curl.exe does, but I think the library should do that for me.

I'm unable to do more with curl for a month or two but will be after that.

Can we tag this as "on ice" or put a date tag on it to revisit later?

**Pull request closed without merging**
