### PR TITLE
vtls: Fix comment typo about macosx-version-min compiler flag

### PR DESCRIPTION
**Pull request by jzinn**

### CODE REVIEW

**Comment by jay** [comment]
Are you sure it's a typo, isn't mmacos-version-min valid?

**Comment by jzinn** [comment]
Clang documents both [1]:
> `-mmacosx-version-min=`<arg>, `-mmacos-version-min=`<arg>
>
> Set Mac OS X deployment target
[1]: https://clang.llvm.org/docs/ClangCommandLineReference.html

But gcc documents only one [2]:
> -mmacosx-version-min=version
[2]: https://gcc.gnu.org/onlinedocs/gcc/Option-Summary.html

In the wild and elsewhere in curl, `macosx-version-min` seems to be the
standard spelling.

I may have a gcc on my mac that I can try with tomorrow.

**Comment by jzinn** [comment]
I had not considered that `macos-version-min` could be valid, given that `macosx-version-min` already exists.  It looks like both are valid for clang but only one for gcc.

Here's a test showing that gcc accepts `macosx-version-min`:
```
$ touch empty.c
$ /opt/gcc-7.3.0/bin/gcc -O2 -fpic -shared empty.c -mmacosx-version-min=10.11
```

Here's a test showing that gcc does not accept `macos-version-min`:
```
$ touch empty.c
$ /opt/gcc-7.3.0/bin/gcc -O2 -fpic -shared empty.c -mmacos-version-min=10.11
gcc: error: unrecognized command line option ‘-mmacos-version-min=10.11’; did you mean ‘-mmacosx-version-min=’?
```

I also grepped through the current gcc source code and did not find `macos-version-min`.

Please close this if you like the current spelling.

**Comment by jay** [comment]
Thanks

**Pull request closed without merging**
