### PR TITLE
ci/openssl-3.1.0+quic updates

### PR DESCRIPTION
**Pull request by pheiduck**

### CODE REVIEW

**Comment by pheiduck** [comment]
test `2501` and `2502` aren't working until now.
Maybe when **openssl-3.1.0+quic** is out of _beta/dev_ state.

**Comment by pheiduck** [comment]
@bagder is there a way to explicit disable tests for  ngtcp2 CIs?

**Comment by bagder** [comment]
> @bagder is there a way to explicit disable tests for ngtcp2 CIs?

No... but I also don't think we should disable this test in a HTTP/3 build.

**Comment by pheiduck** [comment]
Will do revert later than.

**Comment by pheiduck** [comment]
if I understand it correctly, the connection with QUIC is not established here.

**Comment by pheiduck** [comment]
@bagder, this PR is ready for review/merge.

**Pull request closed without merging**
