### PR TITLE
Make building successful

### PR DESCRIPTION
**Pull request by choury**
avoid  "Makefile:299: *** missing separator.  Stop."

### CODE REVIEW

**Comment by bagder** [comment]
Please tell us more. What system is showing this problem? The configure.ac file has had that `AC_COPYRIGHT` macro use all since commit d5ba030942, which makes it over 13 years old and yet now suddenly you have a problem with it!?

**Comment by choury** [comment]
My system is centos 6, and GUN Make 3.81

**Comment by choury** [comment]
I get a Makefile like this:

`PACKAGE_COPYRIGHT = Copyright (c) 1998 - 2016 Daniel Stenberg, <daniel@haxx.se>
 This configure script may be copied, distributed and modified under the                                                                                                                 
 terms of the curl license; see COPYING for more details`

which make the build failed

**Comment by bagder** [comment]
Are you building from git? Which autoconf version is this? I don't have any `PACKAGE_COPYRIGHT =` in my makefiles.

**Comment by choury** [comment]
I build the tag:7.49.1 with "autoconf (GNU Autoconf) 2.69"

**Comment by bagder** [comment]
I use autoconf 2.69 as well. What automake version? Somehow you've gotten a crap version AC_COPYRIGHT installed that ruins the curl output. **This is not a bug in curl**. See for example how someone else broke it in the past: https://bugs.launchpad.net/libnih/+bug/519278

And if you just want to build 7.49.1, you should consider downloading the release tarball instead as that is the official release ([like this](https://curl.haxx.se/download/curl-7.49.1.tar.gz)). The tag named 7_49_1 is just the state of the source tree at the time of the release.

**Comment by choury** [comment]
Ｉ use automake (GNU automake) 1.11.1.
If the reason is what you said, I will build it successful after i relogin system, but not.
Even it is true, this commit can avoid this situation too.

**Comment by bagder** [comment]
You doing a "relogin" will of course not fix your broken macro install. You'd need to first identify the bad macro and then fix or uninstall it.

You can work-around this problem by building from the release tarball instead of from git directly.

This is not a problem in curl so I do not agree with the suggest change

**Pull request closed without merging**
