### PR TITLE
Android build fix & CMake fix

### PR DESCRIPTION
**Pull request by bwalle**
See the individual patches.

### CODE REVIEW

**Comment by snikulov** [comment]
@bwalle It would be great to see "how to reproduce" description for the issue. 
Thank you in advance.

**Comment by bwalle** [comment]
To reproduce:

```
CC=/home/builduser/toolchains/android/tc/ndk14b-api19-x86/bin/i686-linux-android-gcc  ./configure --host=arm-linux
```

The declaration is just missing in the header, the problem is that the configure check just checks if the function is available at link-time, not if it's declared.

Contents of `pwd.h`:

```
#if 0 /* MISSING FROM BIONIC */
int getpwnam_r(const char*, struct passwd*, char*, size_t, struct passwd**);
int getpwuid_r(uid_t, struct passwd*, char*, size_t, struct passwd**);
struct passwd* getpwent(void);
int setpwent(void);
#endif /* MISSING */
```

I know that the toolchain is a bit older, but we're still using that one.

**Comment by bwalle** [comment]
But the cmake fix should be ok, isn't it?

**Comment by MarcelRaad** [comment]
See also https://github.com/curl/curl/issues/2058. This is a bug in the NDK fixed in later versions.

**Comment by snikulov** [comment]
@bwalle I see no CMake invocation in your "how to reproduce". Why do you add it to the subject?

**Comment by bwalle** [comment]
@snikulov Well, the CMake thing has nothing todo with Android. The check for `getpwuid_r` is just missing. There's no build error, but the function is not used then. I'm just using `cmake ..` on Linux.

**Comment by bagder** [comment]
@snikulov it seems to be an omission in the cmake build

@bwalle I think @MarcelRaad is spot on; this is an NDK issue that is already fixed. And if we were to add a work-around for this in our code, I don't see how this is a good such one!

**Comment by bwalle** [comment]
@bagder I can remove the Android patch and keep it in my local build system until we update the toolchain. Would you merge the cmake part?

**Comment by bagder** [comment]
> I can remove the Android patch and keep it in my local build system until we update the toolchain

You can of course do what you want, but I still consider it a lame "fix". It just disables the use of the function so instead you'll use a function that isn't thread-safe. A more proper fix would be to instead provide a private prototype to avoid the warning when the correct function is used!

The cmake fix is valid and I'll merge!

**Comment by bwalle** [comment]
I can create a new patch for the NDK issue if you advise me how you want to get it fixed, but I'm also fine with closing that PR.

**Comment by bagder** [comment]
I believe a proper fix for this broken NDK would be as following (assuming I've understood this correctly):

1 - detect the lack of `getpwuid_r` declaration, similar to how you did it already. If there's no proto for it, set a custom define (`HAVE_NO_GETPWUID_R_PROTO` perhaps?)
2 - in `lib/netrc.c` and `lib/curl_ntlm.c`, add code in the top of the files similar to:
~~~c
#ifdef HAVE_NO_GETPWUID_R_PROTO
int getpwuid_r(uid_t uid, struct passwd *pwd, char *buf,
               size_t buflen, struct passwd **result);
#endif

**Comment by bwalle** [comment]
I've updated the branch.

**Comment by bagder** [comment]
And yes, it figured out this:
~~~
lib/curl_setup.h:804:34: error: "HAVE_DECL_GETPWUID_R" is not defined [-Werror=undef]
 #if defined(HAVE_GETPWUID_R) && !HAVE_DECL_GETPWUID_R
                                  ^
~~~

It highlights this problem: only the configure script will define `HAVE_DECL_GETPWUID_R` for the time being, so all other builds (primarily the cmake one) will use this custom prototype. I'm not 100% sure that is a real problem but I suspect it might become one.

I would prefer if the configure script defines name for the reverse: when the prototype is found to be missing as then we could be sure that only systems for which configure has detected a missing prototype would use this custom one.

**Comment by bwalle** [comment]
I've updated my patch.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
