### PR TITLE
fix asiohiper.cpp, access invalid pointer fdp

### PR DESCRIPTION
**Pull request by Jackarain**
Signed-off-by: jack <jack.wgm@gmail.com>

### CODE REVIEW

**Comment by bagder** [comment]
@Aulddays, you improved this example recently, do you have any comment on @Jackarain's take here?

**Comment by Aulddays** [comment]
I see the point. It could be possible that `event_cb()` be called after `remsock()`, where `fdp` becomes an invalid pointer.
Actually I originally modified the example a little like what @Jackarain is doing, by adding an new variable to keep the current "state". However, after I ran a few tests, I found that `remsock()` would be called only if some thing happens, i.e. when an earlier `event_cb()` is being called. So I decided it is safe to just reuse `fdp` (which was already there before my improvement, so that no need an extra variable) in `event_cb()`.
@Jackarain, do you have an idea when the invalid pointer access happens? Maybe when a timeout?

**Comment by Jackarain** [comment]
@Aulddays maybe read eof in curl_multi_socket_action.
the callstack eg:
remsock()
sock_cb()
singlesocket()
multi_socket()
curl_multi_socket_action()
event_cb()

In fact, the first PR don't not really fix that. (;-
see last commit!

and the following is a use of c++ rewriting the asl call curl implementation.
very clean and very easy to understand.
`
#include <curl.h>
#include <boost/asio.hpp>
#include <boost/bind.hpp>
#include <iostream>


#define MSG_OUT stdout

class curl_http
{
public:
	curl_http(boost::asio::io_service& io)
		: m_io_service(io)
		, m_timer(io)
		, m_sock(io)
		, m_curl_multi(nullptr)
		, m_curl_easy(nullptr)
		, m_still_running(0)
	{}
	~curl_http()
	{
		if (m_curl_multi)
			curl_multi_cleanup(m_curl_multi);
	}

public:
	bool open(const std::string& url)
	{
		if (url.empty())
			return false;

		m_curl_multi = curl_multi_init();
		if (!m_curl_multi)
			return false;

		curl_multi_setopt(m_curl_multi, CURLMOPT_SOCKETFUNCTION, curl_sock_cb);
		curl_multi_setopt(m_curl_multi, CURLMOPT_SOCKETDATA, this);

 		curl_multi_setopt(m_curl_multi, CURLMOPT_TIMERFUNCTION, curl_multi_timer_cb);
 		curl_multi_setopt(m_curl_multi, CURLMOPT_TIMERDATA, this);

		m_curl_easy = curl_easy_init();
		if (!m_curl_easy)
			return false;

		m_url = url;

		curl_easy_setopt(m_curl_easy, CURLOPT_URL, m_url.c_str());
		curl_easy_setopt(m_curl_easy, CURLOPT_WRITEFUNCTION, curl_write_cb);
		curl_easy_setopt(m_curl_easy, CURLOPT_WRITEDATA, this);
		curl_easy_setopt(m_curl_easy, CURLOPT_VERBOSE, 1L);
		// curl_easy_setopt(m_curl_easy, CURLOPT_ERRORBUFFER, conn->error);
		curl_easy_setopt(m_curl_easy, CURLOPT_PRIVATE, this);
		curl_easy_setopt(m_curl_easy, CURLOPT_NOPROGRESS, 1L);
		curl_easy_setopt(m_curl_easy, CURLOPT_PROGRESSFUNCTION, curl_prog_cb);
		curl_easy_setopt(m_curl_easy, CURLOPT_PROGRESSDATA, this);
		curl_easy_setopt(m_curl_easy, CURLOPT_LOW_SPEED_TIME, 3L);
		curl_easy_setopt(m_curl_easy, CURLOPT_LOW_SPEED_LIMIT, 10L);

		/* call this function to get a socket */
		curl_easy_setopt(m_curl_easy, CURLOPT_OPENSOCKETFUNCTION, curl_opensocket);
		curl_easy_setopt(m_curl_easy, CURLOPT_OPENSOCKETDATA, this);

		/* call this function to close a socket */
		curl_easy_setopt(m_curl_easy, CURLOPT_CLOSESOCKETFUNCTION, curl_close_socket);
		curl_easy_setopt(m_curl_easy, CURLOPT_CLOSESOCKETDATA, this);

		CURLMcode rc = curl_multi_add_handle(m_curl_multi, m_curl_easy);
		if (rc != CURLM_OK)
			return false;
		return true;
	}


private:

	void check_multi_info()
	{
		CURLMcode rc = curl_multi_socket_action(m_curl_multi, CURL_SOCKET_TIMEOUT, 0, &m_still_running);
		CURLMsg* msg;
		int msgs_left;
		while ((msg = curl_multi_info_read(m_curl_multi, &msgs_left))) {
			if (msg->msg == CURLMSG_DONE) {
				CURL* easy = msg->easy_handle;
				CURLcode res = msg->data.result;
				char* eff_url = nullptr;
				curl_easy_getinfo(easy, CURLINFO_EFFECTIVE_URL, &eff_url);
				std::cout << "done, url: " << eff_url << ", result: " << res << std::endl;
				curl_multi_remove_handle(m_curl_multi, easy);
				curl_easy_cleanup(easy);
			}
		}

	}

	static int curl_multi_timer_cb(CURLM *multi, long timeout_ms, void* data)
	{
		curl_http* p = (curl_http*)data;
		return p->multi_timer_cb(timeout_ms);
	}

	int multi_timer_cb(long timeout_ms)
	{
		boost::system::error_code ec;
		m_timer.cancel(ec);

		if (timeout_ms > 0) {
			/* update timer */
			m_timer.expires_from_now(boost::posix_time::millisec(timeout_ms));
			m_timer.async_wait([this](const boost::system::error_code& error)
			{
				if (!error) {
					CURLMcode rc = curl_multi_socket_action(m_curl_multi, CURL_SOCKET_TIMEOUT, 0, &m_still_running);
					if (rc != CURLM_OK)
						return;
					check_multi_info();
				}
			});
		} else {
			/* call timeout function immediately */
			boost::system::error_code error; /*success*/
			check_multi_info();
		}
		return 0;
	}

	static int curl_close_socket(void* data, curl_socket_t item)
	{
		curl_http* p = (curl_http*)data;
		return p->close_socket(item);
	}

	int close_socket(curl_socket_t item)
	{
		boost::system::error_code ec;
		m_sock.close(ec);
		return 0;
	}

	static curl_socket_t curl_opensocket(void* data, curlsocktype purpose, struct curl_sockaddr *address)
	{
		curl_http* p = (curl_http*)data;
		return p->opensocket(purpose, address);
	}

	curl_socket_t opensocket(curlsocktype purpose, struct curl_sockaddr *address)
	{
		curl_socket_t sockfd = CURL_SOCKET_BAD;

		/* restrict to IPv4 */
		if (purpose == CURLSOCKTYPE_IPCXN && address->family == AF_INET) {
			boost::system::error_code ec;
			m_sock.open(boost::asio::ip::tcp::v4(), ec);	/* open it and get the native handle*/
			if (!ec)
				sockfd = m_sock.native_handle();
		}

		return sockfd;
	}

	static int curl_prog_cb(void *data, double dltotal, double dlnow, double ult, double uln)
	{
		curl_http* p = (curl_http*)data;
		return p->prog_cb(dltotal, dlnow, ult, uln);
	}

	int prog_cb(double dltotal, double dlnow, double ult, double uln)
	{
		return 0;
	}

	static size_t curl_write_cb(void *ptr, size_t size, size_t nmemb, void* data)
	{
		curl_http* p = (curl_http*)data;
		return p->write_cb(ptr, size, nmemb);
	}

	size_t write_cb(void *ptr, size_t size, size_t nmemb)
	{
		size_t written = size * nmemb;
		char *pBuffer = (char *)malloc(written + 1);

		strncpy(pBuffer, (const char *)ptr, written);
		pBuffer[written] = '\0';

		fprintf(MSG_OUT, "%s", pBuffer);

		free(pBuffer);

		return written;
	}

	static int curl_sock_cb(CURL *e, curl_socket_t s, int what, void *cbp, void *sockp)
	{
		curl_http* p = (curl_http*)cbp;
		return p->sock_cb(e, s, what, sockp);
	}

	void curl_event(int action, const boost::system::error_code& error, std::size_t/*bytes_transferred*/)
	{
		if (error)
			return;

		if (m_current_action != action && m_current_action != CURL_POLL_INOUT)
			return;

		curl_socket_t s = m_sock.native_handle();
		if (error)
			action = CURL_CSELECT_ERR;
		CURLMcode rc = curl_multi_socket_action(m_curl_multi, s, action, &m_still_running);
		check_multi_info();

		if (m_still_running <= 0) {
			boost::system::error_code ec;
			m_timer.cancel(ec);
		}

		if (m_current_action == action || m_current_action == CURL_POLL_INOUT) {
			switch (action) {
			case CURL_POLL_IN:
			{
				m_sock.async_read_some(boost::asio::null_buffers(),
					boost::bind(&curl_http::curl_event, this, action,
						boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
			}
			break;
			case CURL_POLL_OUT:
			{
				m_sock.async_write_some(boost::asio::null_buffers(),
					boost::bind(&curl_http::curl_event, this, action,
						boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
			}
			break;
			default:
				break;
			}
		}
	}

	int sock_cb(CURL *e, curl_socket_t s, int action, void *sockp)
	{
		if (action == CURL_POLL_IN || action == CURL_POLL_OUT) {
			if (!sockp) {
				curl_multi_assign(m_curl_multi, s, (void *)this);
			}
		}

		m_current_action = action;

		switch (action) {
		case CURL_POLL_IN: {
				m_sock.async_read_some(boost::asio::null_buffers(),
					boost::bind(&curl_http::curl_event, this,
						action, boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
			}
			break;
		case CURL_POLL_OUT: {
				m_sock.async_write_some(boost::asio::null_buffers(),
					boost::bind(&curl_http::curl_event, this,
						action, boost::asio::placeholders::error, boost::asio::placeholders::bytes_transferred));
			}
			break;
		case CURL_POLL_REMOVE: {
				std::cout << "CURL_POLL_REMOVE" << std::endl;
				m_current_action = -1;
			}
			break;
		default:
			break;
		}

		return 0;
	}

private:
	boost::asio::io_service& m_io_service;
	boost::asio::deadline_timer m_timer;
	boost::asio::ip::tcp::socket m_sock;

	std::string m_url;
	CURLM* m_curl_multi;
	CURL* m_curl_easy;
	int m_current_action;
	int m_still_running;
};


int main_test(int argc, char **argv)
{
	boost::asio::io_service io_service;

	curl_http c(io_service);
	c.open("www.google.com");

	io_service.run();
	return 0;
}
`

**Comment by Aulddays** [comment]
I ran a few tests and discovered that there are situations the original fdp pointer can't handle, and a "global state" is indeed necessary.
@Jackarain 's seems to handle the problems.

**Comment by jay** [comment]
This looks fine except for one thing, it is possible to have more than one socket open at the same time per easy handle (FTP) but the proposed change assumes there will only be one socket open per easy handle.

For example consider remsock where the socket action stored in the easy info is set to invalid (-1). Well, some socket may be invalidated in the easy handle but some other socket may still be valid, and since that information is not now stored per socket it is a problem.

The variable naming currently in the example I realize probably makes this confusing because the name of the struct for each easy handle data is 'conn' but there can be multiple connections within the easy handle.

**Comment by bagder** [comment]
> it is possible to have more than one socket open at the same time per easy handle (FTP)

It is even *likely* to happen since libcurl does "happy eyeballs" for TCP connections on dual-stack hosts. And for libcurl built with c-ares it might also expose more than one socket during the name resolve.

**Comment by Aulddays** [comment]
To be added, libcurl may "rebind" an existing tcp socket to another easy handle in the situation of keep-alive. So the idea is, tcp socket and easy handles should be managed separately.
However, in my opinion, for a demonstrating key points on how to combine libcurl and asio, maybe the demo has provided enough information. After all, the demo now runs correctly on its specific situation.
In real world programs, one should definitely implement a much more complicate mechanism to keep track of the sockets and easy handles than some global variable as the demo does, and I think those attempt to use "hiper" ones instead multi-threaded synchronous ones are probably already quite good at this. What they need is to find out key points of how libcurl are exposed to asynchronous interfaces. So I think maybe the current demo has done its job.

**Comment by bagder** [comment]
> maybe the demo has provided enough information

I can't tell exactly how this example works or what it assumes (mostly because I don't know asio at all and haven't gone to the trouble to figure this out completely), but the code **MUST NOT** make assumptions about number of connections per easy handle or number of sockets used, neither in parallel or serially.

Sure, it's "just an example", but we see over and over how the examples are used as a copy and paste resource, or are based as the foundations for the first stumbling steps when people start off writing libcurl-using apps. It is important that the examples do not mislead users into wrong assumptions or downright bad practices.

So, I think it is worth spending a little extra time to make sure the examples are correct.

**Comment by frenche** [comment]
I didn't follow the whole thread, but perhaps registering CURLOPT_OPENSOCKETFUNCTION could help the code to keep better track of the connections.

**Comment by Aulddays** [comment]
@bagder Well, I agree with you. The connection number assumption does seem misleading.

And I also raised a confusion on curl (possibly has already been discussed): Besides multiple connections per easy handle problem, the sample also assumes each connection is only bond to one easy handle, as I mentioned in the last post (the sample runs because it creates only one easy handle).
However, the `CURLOPT_OPENSOCKETFUNCTION` and `CURLOPT_CLOSESOCKETFUNCTION` seem kind of "suggest" connection's bond to easy handle, as they are per easy-handle options. But it is possible that the connection to be opened in one easy session and closed in another.
I notice that the callbacks actually do not have an easy handle passed. Maybe the two options themselves should be made "global" instead of easy-handle level.

**Comment by bagder** [comment]
> the sample also assumes each connection is only bond to one easy handle

It is bound to *one easy handle at a time*, but the same connection (and thus socket value) can very well get used by another easy handle over time.

> CURLOPT_OPENSOCKETFUNCTION and CURLOPT_CLOSESOCKETFUNCTION

When using the multi-socket API, the application shouldn't need to use those callbacks just for socket tracking at least. The socket callback set with `CURLMOPT_SOCKETFUNCTION` should give the application information enough about which sockets to wait for and for what activities. I think the problem is rather when applications try to deduce information or conclusions from that information that libcurl doesn't provide.

**Comment by bagder** [comment]
> It is bound to one easy handle at a time

Sorry, that's also a wrong assumption. Bad of me. With HTTP/2, pipelining and other things the same connection can be used by multiple handles.

**Comment by bagder** [comment]
@Jackarain, any further updates coming on this?

**Comment by bagder** [comment]
The work seems to have stalled and the last suggested fix unfortunately had some wrong assumptions making it impossible for us to merge. I'm all for opening this again if it comes back to life.

**Pull request closed without merging**
