### PR TITLE
build: omit certain deps from `libcurl.pc` unless found via `pkg-config`

### LINKED ISSUE #15469: libcurl's package config file unconditionally references mbedtls in Requires.private but it does not exist
### I did this

Install mbedtls 3.6.0 (or any older version) with their makefile build system

It does *not* produce a package config file.

Now install curl with this mbedtls, and it will produce a `libcurl.pc` like this:

```
...
Requires.private: zlib,mbedtls,libssh2,libnghttp2
...
```

which then breaks builds of dependents of curl such as `elfutils`, because:

```
configure:13512: checking for libcurl >= 7.29.0
configure:13519: $PKG_CONFIG --exists --print-errors "libcurl >= 7.29.0"
configure:13522: $? = 0
configure:13536: $PKG_CONFIG --exists --print-errors "libcurl >= 7.29.0"
configure:13539: $? = 0
configure:13553: result: no
Package 'mbedtls', required by 'libcurl', not found
```

### I expected the following

I would expect curl not to put mbedtls in the Requires.private section of its libcurl.pc file, because it never tested whether this package config file exists.

I would also expect curl to continue to allow users to build mbedtls using their makefile build system, given that cmake itself depends on curl, so requiring cmake as a build system for mbedtls causes circular dependencies across these packages.

Lastly, I would expect curl to produce a sensible pc file when using old mbedtls, which did not produce a pc file to start with.

### curl/libcurl version

curl 8.9.0 and up

### operating system

irrelevant

### LINKED ISSUE #15507: 8.11.0: Requires.private ldap issue
### I did this

I tried to built many versions of php with ldap support. Since curl-8.11.0 no one builds anymore:
`checking for cURL support... yes, shared                                                      
checking for libcurl >= 7.29.0... no
configure: error: Package requirements (libcurl >= 7.29.0) were not met:

Package 'ldap', required by 'libcurl', not found`

### I expected the following

I expect php to build like it does with previous curl-8.10.1 version. I notice I have this issue only with openldap-2.4. It works fine with openldap-2.6.
Anyway, after building and installing curl, I can build php aside of openldap-2.4 if I remove ldap from Requires.private in libcurl.pc.

### curl/libcurl version

curl 8.11.0

### operating system

Linux myhostname 6.11.6-tom.server #1 SMP PREEMPT_DYNAMIC Fri Nov  1 16:32:45 CET 2024 x86_64 Intel(R) Xeon(R) CPU E3-1245 V2 @ 3.40GHz GenuineIntel GNU/Linux.
I use Slackware.

### PR DESCRIPTION
**Pull request by vszakats**
The idea of linking dependencies found to `libcurl.pc` turns out not
to work in practice in some cases.

Specifically: gss, ldap, mbedtls, libmsh3, rustls

A `.pc` may not work or be missing for a couple of reasons:
- not all build methods generate it: mbedTLS, Rustls
- generated file is broken: msh3
  Ref: https://github.com/nibanks/msh3/pull/225
- installed package flavour isn't shipping with one:
  FreeBSD GSS, OmniOS LDAP, macOS LDAP

The effect of such issues shall be subtle in theory, because
`libcurl.pc` normally lists these dependencies in the `Requires.private`
section meant for static linking. But, e.g. `pkg-config --exists`
requires these to be present, and builds sometimes use this check
regardless of build type. This bug is not present in `pkgconf`; it only
checks for them when `--static` is also passed.

Fix these by adding affected `.pc` references to `libcurl.pc` only when
we detected the dependency via `pkg-config`.

There are a few side-effects of this solution:
- references are never added for dependencies where curl doesn't
  implement `pkg-config` detection. These are:
  - autotools: ldap, mbedtls, msh3
  - cmake: ldap (pending #15273)
- generated `libcurl.pc` depends on the build-time environment.
- generated `libcurl.pc` depends on curl build tool (cmake, autotools).
- generated `libcurl.pc` depends on curl build implementation details.

Make an exception for GNU GSS, where I blindly guess that `gss.pc` is
always available, as no issues were reported.

Other, not mentioned, dependencies continue to be added regardless
of the detection method.

Reported-by: Harmen Stoppels, Thomas, Daniel Engberg, Andy Fiddaman
Fixes #15469
Fixes #15507
Fixes #15535
Fixes https://github.com/curl/curl/pull/15163#issuecomment-2473358444

---

- [x] Keep in sync with #15545
- [x] Keep in sync with #15273
- [x] Keep an eye on #15408

### CODE REVIEW

**Comment by vszakats** [comment]
@haampie, @Thom1b, @diizzyy, @citrus-it: Can you give this a test and report if it improves your build case?

**Comment by Thom1b** [comment]
Hi,

I just applied these both patches to curl-8.11.0.tar.xz tarball:
b69ebe36a45222ee845239bbe908bb90415f483a.patch
fb6f0185197e695156029afadfaf7922429be9f1.patch

Then I built and installed curl (using ./configure, not cmake). I understand the patch avoid adding ldap in Requires.private but it's still there:

```
# grep Requires.private /usr/lib64/pkgconfig/libcurl.pc
Requires.private: libidn2,ldap,zlib,libbrotlidec,libzstd,mit-krb5-gssapi,openssl,libpsl,libssh2,libnghttp2,libnghttp3,libcares
```

So php still can't build with openldap2.4 which has no .pc file.

**Comment by vszakats** [comment]
> Hi,
> 
> I just applied these both patches to curl-8.11.0.tar.xz tarball: [b69ebe3](https://github.com/curl/curl/commit/b69ebe36a45222ee845239bbe908bb90415f483a) [fb6f018](https://github.com/curl/curl/commit/fb6f0185197e695156029afadfaf7922429be9f1)
> 
> Then I built and installed curl (using ./configure, not cmake). I understand the patch avoid adding ldap in Requires.private but it's still there:
> 
> ```
> # grep Requires.private /usr/lib64/pkgconfig/libcurl.pc
> Requires.private: libidn2,ldap,zlib,libbrotlidec,libzstd,mit-krb5-gssapi,openssl,libpsl,libssh2,libnghttp2,libnghttp3,libcares
> ```
> 
> So php still can't build with openldap2.4 which has no .pc file.

Thanks for testing!

It's odd because this patch unconditionally disables adding `ldap` via both cmake and autotools.

Did you run `autoreconf -fi` after applying this patch?

**Comment by Thom1b** [comment]
> Did you run `autoreconf -fi` after applying this patch?

I forgot of course. ;)
I just retried, it works fine. ldap is not in Requires.private so I can build php now. It solved the issue. Thanks!

**Comment by citrus-it** [comment]
I tested this PR on OmniOS and it works - the `libcurl.pc` files are back to exactly the same content as curl 8.10.x

```
bloody:omnios:curl-ldap% sed '1,/^$/d' tmp/pkg/usr/lib/amd64/pkgconfig/libcurl.pc
prefix=/usr
exec_prefix=${prefix}
libdir=/usr/lib/amd64
includedir=/usr/include
supported_protocols="DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS IPFS IPNS LDAP LDAPS MQTT POP3 POP3S RTSP SMB SMBS SMTP SMTPS TELNET TFTP WS WSS"
supported_features="alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IPv6 Largefile libz NTLM PSL SSL threadsafe TLS-SRP UnixSockets zstd"

Name: libcurl
URL: https://curl.se/
Description: Library to transfer files with HTTP, FTP, etc.
Version: 8.11.0
Requires:
Requires.private: zlib,libbrotlidec,libzstd,openssl,libpsl,libnghttp2
Libs: -L${libdir} -lcurl
Libs.private: -m64 -L/usr/lib/amd64 -L/usr -L/usr/lib/amd64 -L/usr/lib/amd64 -lnghttp2 -lpsl -lssl -lcrypto -lssl -lcrypto -lldap -lzstd -lbrotlidec -lz -lsocket -lnsl
Cflags: -I${includedir}
Cflags.private: -DCURL_STATICLIB
```

**Comment by diizzyy** [comment]
@vszakats
Hi,
Still broken on FreeBSD

```
Requires.private: libidn2,openssl,zlib,libnghttp2,libpsl,heimdal-gssapi
```

-L is now also missing for library (tested with GSSAPI in base)

**Comment by diizzyy** [comment]
@vszakats 
Appears to work as expected on my end, thanks!

**Pull request closed without merging**
