### PR TITLE
Re-add CURLE_OBSOLETE20 as alias of CURLE_HTTP3

### PR DESCRIPTION
**Pull request by cmb69**
See also mailing list thread <https://curl.haxx.se/mail/lib-2019-11/0045.html>.

### CODE REVIEW

**Comment by dfandrich** [comment]
Do we really want to do this? It used to be basically harmless if applications
still referenced CURLE_OBSOLETE20, either directly or via
CURLE_FTP_WRITE_ERROR, since it hasn't been returned by libcurl for more than
13 years. But now, it will start being returned and for a completely different
reason. There's no way to safely let old programs run any more that still
reference such old symbols. It may be time to more forcefully tell application
owners that it's time to fix their programs by letting them fail. If someone
insists, we could include some kind of source-level backwards compatibility
behind a macro called
CURL_THIS_APPLICATION_USING_CURL_IS_HOPELESSLY_OUT_OF_DATE_AND_SHOULD_BE_EMBARRASSED

**Comment by bagder** [comment]
hm, wise thoughts there @dfandrich that certainly made me rethink my initial response...

@cmb69, can you tell us if this at least will make the PHP team remove all references and uses of anything in the curl header that says **OSBOSLETE** so that we won't have to do this dance every time?

**Comment by cmb69** [comment]
Well, I had a closer look, and in this case it isn't actually about `CURLE_OBSOLETE20`, but rather about `CURLE_FTP_WRITE_ERROR` which is defined as https://github.com/curl/curl/blob/7627a2dd9d4b7417672fdec3dc6e7f8d3de379de/include/curl/curl.h#L644
This definition makes no sense, if `CURLE_OBSOLETE20` is no longer defined.

On the PHP side, `CURLE_FTP_WRITE_ERROR` (which is defined as PHP constant) should have been removed already, but apparently that has been overlooked, and we can't just drop constants for the next patch revision, let alone for PHP versions which only receive security patches, so these versions couldn't be built with latest libcurl anymore what would be a problem if these versions ship security fixes. Of course, the PHP team can work around this by defining these PHP constant otherwise, but still, this won't happen for security branches.

The way forward for PHP would be to actually build with `CURL_NO_OLDIES` defined, and to fix all issues for actively supported versions, and to remove obsolete constants in PHP 8 altogether. And of course, to repeat that for future libcurl versions.

For libcurl, maybe it would make sense to change the definition referred to above to:
````.c
#define CURLE_FTP_WRITE_ERROR CURLE_HTTP3
````

**Comment by dfandrich** [comment]
On Sat, Nov 16, 2019 at 01:05:48AM -0800, Christoph M. Becker wrote:
> For libcurl, maybe it would make sense to change the definition referred to
> above to:
> 
> #define CURLE_FTP_WRITE_ERROR CURLE_HTTP3

IMHO this is even worse because is complete hides the fact that this is dealing
with an obsolete entry.

**Comment by pgnd** [comment]
Given that^ discussion, for fixing php ext/curl with *current* php 7.3 release (&/or 7.4 branch), what's the approach to be taken?  this current curl PR's changes?  a different tack? &/or a fix in php src?

**Comment by cmb69** [comment]
If nothing changes from the libcurl side, I think in PHP 7.3/7.4 this would have to be solved by defining the PHP constants by the respective integer values instead of using the macros.

**Comment by pgnd** [comment]
@cmb69 thx.

if that's the case, is there an open issue (yet) for that @ php bugs?

afaict, this problem is cropping up with current release packages.

**Comment by bagder** [comment]
Thanks everyone for your feedback and comments. Due to the inherit problems in this concept I'm going to instead backtrack on the error code reuse and instead make it a new one.

**Pull request closed without merging**
