### PR TITLE
http2: Don't send header fields prohibited by HTTP/2 spec

### PR DESCRIPTION
**Pull request by tatsuhiro-t**
Previously, we just ignored "Connection" header field.  But HTTP/2
specification actually prohibits few more header fields.  This commit
ignores all of them so that we don't send these bad header fields.

### CODE REVIEW

**Comment by tatsuhiro-t** [comment]
Good point..  Yes, we need to parse it.  Does curl have convenient function to parse this comma separated list header fields?

**Comment by tatsuhiro-t** [comment]
Thank you.  I ended up not to use strtok_r since it requires NULL-terminated string, and it replaces delimiter with NUL byte.  Instead, I added hand crafted "trailers" detection code.

**Comment by jay** [comment]
> I ended up not to use strtok_r since it requires NULL-terminated string, and it replaces delimiter with NUL byte. Instead, I added hand crafted "trailers" detection code.

Oops I forgot about that. Your changes just landed. I made a few corrections:

- Typo. Searching for tab had used 't' instead of '\t'
- Unnecessary goto. We discourage goto when not necessary so I redid the logic.
- enum names too generic. (For example `IGNORE` is defined to 0 somewhere in my includes so I prefixed them with `HEADERINST_`)
- Unreachable code. Some compilers may warn that since the `for(;;)` is never exited the return after that block will never be hit, so I removed it.
- Minor style changes

Thanks!

**Comment by tatsuhiro-t** [comment]
The commit looks good.  Thank you for merging this.

**Pull request closed without merging**
