### PR TITLE
travis: export the CC/CXX variables when set

### LINKED ISSUE #4637: ngtcp2 C++ example build failure on travis
### I did this

I noticed build failures on travis on current ngtcp2 builds. They build ngtcp2 from their git master and the failure is in the [building of their example client](https://travis-ci.org/curl/curl/jobs/616730788#L4691).

~~~
In file included from client.cc:47:0:
client.h:35:23: fatal error: string_view: No such file or directory
compilation terminated.
Makefile:719: recipe for target 'client.o' failed
make[2]: *** [client.o] Error 1
~~~

### I expected the following

The build to go green

#### Details

I asked @tatsuhiro-t about it in another channel and he responded like this:

> It is in C++17 standard.  Recent gcc/clang should work.  I'll add configure option to build library only.

We can work on fixing the C++ in travis or just disable the example build for ngtcp2 (once support for that has landed). Disabling the example will be preferably anyway since it'll speed up the build and we don't use the example for anything!

### PR DESCRIPTION
**Pull request by bagder**
Suggested-by: Peter Wu
Fixes #4637

### CODE REVIEW

**Comment by bagder** [comment]
Bah, me and typos... :wink:

**Comment by bagder** [comment]
Yeps, that fixed the ngtcp2 example build.

**Comment by MarcelRaad** [comment]
@Lekensteyn Is there any documentation where you found this fix? I only know https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning, which uses `eval`, so I thought that did practically the same as `export`.

**Comment by Lekensteyn** [comment]
@MarcelRaad There are no docs for that, I just looked at the build output and saw that CC was being exported (presumably due to `language: c`), but no `CXX`.

Perhaps the Travis documentation should be updated to use `export` instead of `eval` too?

**Pull request closed without merging**
