### PR TITLE
GHA: drop codeql

### PR DESCRIPTION
**Pull request by bagder**
We started using codeql for static code analysis in 7183f5acc3d7ca39, June 2020.

Since then, not a single commit has been merged into the source code repository citing codeql as source or reason. Yet, it keeps getting updated and we get constant reminders to upgrade pinning to the latest hash.

During 4.5 years with intense development and significant code churn. While Coverity, scan-build and CodeSonar have belped us point out many mistakes, codeql has remained silent (or had false positives).

For this little gain, I think we spend a disproportionate amount of work on codeql maintanance.

### CODE REVIEW

**Comment by bagder** [comment]
I also brought the subject to the mailing list to make more people aware and the chance to speak their mind: https://curl.se/mail/lib-2024-12/0026.html

**Comment by testclutch** [comment]
Analysis of PR #15798 at [8ba19452](https://github.com/curl/curl/commit/8ba1945267814df9faf6026db6a610943b96ddf4):

[Test http/test_09_push.py::TestPush::test_09_02_h2_push[0] failed](https://github.com/curl/curl/actions/runs/12445795238/job/34747526691#check-step-43), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 1450 failed](https://github.com/curl/curl/actions/runs/12445795230/job/34747527419#check-step-15), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
Perhaps also delete references from test docs and spellchecker:
```diff
diff --git a/.github/scripts/spellcheck.words b/.github/scripts/spellcheck.words
index 7aa13af70..8d20279a3 100644
--- a/.github/scripts/spellcheck.words
+++ b/.github/scripts/spellcheck.words
@@ -121,8 +121,6 @@ CMakeLists
 CNA
 CNAME
 CNAMEs
-CodeQL
-codeql
 CODESET
 codeset
 Comcast
diff --git a/tests/CI.md b/tests/CI.md
index 16aba0830..c4954097c 100644
--- a/tests/CI.md
+++ b/tests/CI.md
@@ -31,10 +31,8 @@ Consider the following table while looking at pull request failures:
 
  | CI platform as shown in PR          | State  | What to look at next       |
  | ----------------------------------- | ------ | -------------------------- |
- | CI / codeql                         | stable | quality check results      |
  | CI / fuzzing                        | stable | fuzzing results            |
  | CI / macos ...                      | stable | all errors and failures    |
- | Code scanning results / CodeQL      | stable | quality check results      |
  | FreeBSD FreeBSD: ...                | stable | all errors and failures    |
  | LGTM analysis: Python               | stable | new findings               |
  | LGTM analysis:  C/C++               | stable | new findings               |
@@ -42,7 +40,6 @@ Consider the following table while looking at pull request failures:
  | AppVeyor                            | flaky  | all errors and failures    |
  | curl.curl (linux ...)               | stable | all errors and failures    |
  | curl.curl (windows ...)             | flaky  | repetitive errors/failures |
- | CodeQL                              | stable | new findings               |
 
 Sometimes the tests fail due to a dependency service temporarily being offline
 or otherwise unavailable, for example package downloads. In this case you can
@@ -62,7 +59,6 @@ GitHub Actions runs the following tests:
 - Fuzz tests ([see the curl-fuzzer repo for more
   info](https://github.com/curl/curl-fuzzer)).
 - Curl compiled using the Rust TLS backend with Hyper
-- CodeQL static analysis
 
 These are each configured in different files in `.github/workflows`.
 
```

**Comment by jay** [comment]
Ref: https://github.com/curl/curl/security/code-scanning?query=is%3Aclosed+branch%3Amaster+sort%3Acreated-desc+tool%3ACodeQL

158 of 232 security alerts, all of them false positive/ won't fix except 2 potentially uninitialized variable. To be fair though, [security-extended](https://docs.github.com/en/code-security/code-scanning/managing-your-code-scanning-configuration/codeql-query-suites#security-extended-query-suite) is set which makes more noise.

https://github.com/curl/curl/blob/7cf47a7740f666ae3c06361781a341a7da403041/.github/workflows/codeql-analysis.yml#L66

Some warnings like cpp/missing-check-scanf and cpp/weak-cryptographic-algorithm seem to be responsible for a number of entries. There's no filter that I can find to rank which warnings are making the most noise but you can kind of tell from the titles what's up. I think if individual noisy warning/rules like cpp/path-injection that are never right were [excluded from analysis](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#excluding-specific-queries-from-analysis) then it could be tolerable. That said the constant renovate / depedency updates at least once a week for the last year is overdoing it IMO.

**Comment by bagder** [comment]
The fact still remains that it does not seem to find relevant problems for us.

I've seen no objections to the proposed removal.

**Pull request closed without merging**
