### PR TITLE
cmake: skip superfluous hex2dec conversion using math expr

### LINKED ISSUE #9406: CMakeLists.txt : HAVE_WIN32_WINNT value detection and threadsafe
I use CMake version 3.12.4 and at cofigure time I get error and wrong featire detect:
`curl version=[7.85.0]
Performing Curl Test HAVE_WIN32_WINNT
Performing Curl Test HAVE_WIN32_WINNT - Success
CMake Error at CMakeLists.txt:1170 (math):
  math EXPR called with incorrect arguments.

Found _WIN32_WINNT=0x502 (1)
LTO supported and enabled
Enabled features: SSL IPv6 unixsockets libz brotli zstd AsynchDNS Largefile alt-svc HSTS NTLM HTTP2 HTTPS-proxy unicode threadsafe
Enabled protocols: DICT FILE FTP FTPS GOPHER GOPHERS HTTP HTTPS IMAP IMAPS LDAP MQTT POP3 POP3S RTSP SCP SFTP SMB SMBS SMTP SMTPS TELNET TFTP
Enabled SSL backends: OpenSSL
Configuring incomplete, errors occurred!`

threadsafe should not be enabled in my case and error is from not supported version of math() function:
CMake v3.13+
math(EXPR <output-variable> <math-expression> [OUTPUT_FORMAT <format>])
CMake v3.12 and before:
math(EXPR <output variable> <math expression>)

threadsafe feature detected like this:
`_add_if("threadsafe"    HAVE_ATOMIC OR (WIN32 AND
                        HAVE_WIN32_WINNT GREATER_EQUAL 0x600))`
with is wrong I think - it resolved to TRUE if HAVE_ATOMIC is not zero with any winver 

I get it resolved in my case like this:
`if(WIN32)

  curl_internal_test(HAVE_WIN32_WINNT)
  if(HAVE_WIN32_WINNT)
    string(REGEX MATCH ".*_WIN32_WINNT=0x[0-9a-fA-F]+" OUTPUT "${OUTPUT}")
    string(REGEX REPLACE ".*_WIN32_WINNT=0x" "" OUTPUT "${OUTPUT}")
    math(EXPR HAVE_WIN32_WINNT "${OUTPUT}")
    message(STATUS "Found _WIN32_WINNT=${OUTPUT} (${HAVE_WIN32_WINNT})")
  endif()

  unset(HAVE_WIN32_WINNT CACHE)
endif()

----------------------------------------
_add_if("threadsafe"    HAVE_ATOMIC AND (WIN32 AND
                        (HAVE_WIN32_WINNT GREATER_EQUAL 600)))`

### PR DESCRIPTION
**Pull request by mback2k**
CMake seems to be able to compare two hex values just fine.
Also make sure CURL_TARGET_WINDOWS_VERSION is respected.

Assisted-by: Marcel Raad
Reviewed-by: Viktor Szakats
Reported-by: Keitagit-kun on github

Fixes https://github.com/curl/curl/issues/9406

### CODE REVIEW

**Review by MarcelRaad — APPROVED** [review]

**Comment by MarcelRaad** [comment]
That's hard to tell because neither the AppVeyor builds nor I have access to a system not enabling C11 atomics by default. But if you want, I can test manually tomorrow, forcing an old Windows version and old C standard.

**Comment by mback2k** [comment]
Thanks would be great and I would appreciate that very much, thank you!

**Review by vszakats — APPROVED** [review]

**Comment by mback2k** [comment]
At least CI is completely green now ✅ except the perma-failing ones on Zuul.

**Comment by bagder** [comment]
> except the perma-failing ones on Zuul.

We were all-green on Zuul just the other day, so not entire permafailing I think... But still probably not related to this PR.

**Comment by mback2k** [comment]
> > except the perma-failing ones on Zuul.
> 
> 
> 
> We were all-green on Zuul just the other day, so not entire permafailing I think... But still probably not related to this PR.

Ok, seems like the previously often failing ngtcp2 builds have been fixed in the meantime and this was actually another failure.

**Comment by MarcelRaad** [comment]
Works for me (with a small bugfix)! Using
```
cmake .. -DCMAKE_C_STANDARD=99 -DCMAKE_C_EXTENSIONS=OFF -DENABLE_UNICODE=ON -DCURL_WERROR=ON -DENABLE_DEBUG=ON -DCURL_TARGET_WINDOWS_VERSION=0x0502
```
with Visual Studio 2022, I get:
```
-- Performing Curl Test HAVE_ATOMIC
-- Performing Curl Test HAVE_ATOMIC - Failed
[...]
-- Performing Curl Test HAVE_WIN32_WINNT
-- Performing Curl Test HAVE_WIN32_WINNT - Success
-- Found _WIN32_WINNT=0x0502 [or, originally, 0x0A00]
[...]
-- Enabled features: IPv6 unixsockets AsynchDNS Largefile alt-svc HSTS NTLM unicode
-- Enabled protocols: DICT FILE FTP GOPHER HTTP IMAP LDAP MQTT POP3 RTSP SMB SMTP TELNET TFTP
```

But we need an extra `set(CURL_TEST_DEFINES "${CURL_TEST_DEFINES} -D_WIN32_WINNT=${CURL_TARGET_WINDOWS_VERSION}")` here so that `CURL_TARGET_WINDOWS_VERSION` is respected for `curl_internal_test`:
https://github.com/curl/curl/blob/f00028037786676969f311a15fabc5762962d5ef/CMakeLists.txt#L89

**Comment by vszakats** [comment]
At this point, it would seem better to get rid of `CURL_TARGET_WINDOWS_VERSION`. I think it's best to have a single canonical way to set Windows target version.

**Comment by mback2k** [comment]
@MarcelRaad thanks, I will try to incorporate your fix.

@vszakats sounds reasonable, but let's do changes incrementally and leave that for another PR.

**Review by MarcelRaad — APPROVED** [review]

**Pull request closed without merging**
