### PR TITLE
smbserver: pin Python version to 2 since we are not yet 3 compatible

### PR DESCRIPTION
**Pull request by mback2k**
Even though the existing code can be fixed to run on Python 3, the
tests will fail due to the Unicode transition the protocol is invalid.

Follow up to ee63837

### CODE REVIEW

**Comment by mback2k** [comment]
Yeah, I took a look at the new impacket, unfortunately it at least requires pyasn1 (Python only, therefore no problem) and Cryptodome (Python + C extension, which would need to be compiled).

I would rather not like to bring a Python C extension into our testsuite, because that would hinder portability enormously. Building Python C extensions on Windows for example is not straightforward.

**Comment by mback2k** [comment]
We could think about dropping the Python dependencies from this repository and instead requiring our users to install them from PyPI. At least for Cryptodome there are [pre-compiled wheels available](https://pypi.org/project/pycryptodome/#files).

**Comment by mback2k** [comment]
@bagder What do you think about dropping the Python dependencies from this repository?

People would have to run "pip install impacket" in their Python environment before being able to run the smbserver-based tests. We could add a pre-check to the relevant test cases to skip them if impacket is not available in the relevant Python environment.

**Comment by bagder** [comment]
> People would have to run pip install impacket

It sounds very attractive! I mean as long as we just use an independently developed packet we save ourselves work by not bundling it.

I think a reason to bundle it is that we would *prefer* to edit the server and improve it for our purposes. The obvious downside with using a "real" server for testing purposes is that we have a very hard time to do negative testing with it (ie having the server return broken protocol bytes to make sure curl handles that properly). This said, we have not done it so far with impacket...

**Comment by mback2k** [comment]
> It sounds very attractive! I mean as long as we just use an independently developed packet we save ourselves work by not bundling it.

Sounds good, I will follow up with a separate PR for removing python_depencies once this PR is merged.

> I think a reason to bundle it is that we would _prefer_ to edit the server and improve it for our purposes. The obvious downside with using a "real" server for testing purposes is that we have a very hard time to do negative testing with it (ie having the server return broken protocol bytes to make sure curl handles that properly). This said, we have not done it so far with impacket...

We will still ship the `smbserver.py` at the top-level `tests/` directory, we will just remote its dependencies and rely on people installing impacket themselves.

**Pull request closed without merging**
