### PR TITLE
Remove unused data when IPv6 is not supported

### PR DESCRIPTION
**Pull request by MAntoniak**

### CODE REVIEW

**Comment by bagder** [comment]
I think #8439 offers a nicer way (== ends up in more readable and maintainable code) to accomplish the same thing for two of the functions: provide "compatibility macros" so that we don't have to do embedded #ifdefs as much.

**Comment by MAntoniak** [comment]
That is look reasonable. The goal of the PR is removed scope_id from connectdata and UserDefined structures . I am going to rebase my PR to use your changes.

**Comment by bagder** [comment]
ok, cool! I'll merge #8439 and then it'll be easier

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
