### PR TITLE
clang-tidy: add to CI, add cmake support, fix fallouts

### PR DESCRIPTION
**Pull request by vszakats**
build:
- autotools: fix to build generated sources for the `tidy` target.
- autotools: allow passing custom clang-tidy options via
  `CURL_CLANG_TIDYFLAGS` env.
- cmake: add `CURL_CLANG_TIDY` option to configure for `clang-tidy`.
  Also add:
  - `CLANG_TIDY` variable to customize the `clang-tidy` tool.
  - `CURL_CLANG_TIDYFLAGS` to pass custom options to `clang-tidy`.
- apply `--enable-werror` and `-DCURL_WERROR=ON` to `clang-tidy`.

CI/GHA:
- add clang-tidy job for Linux, using autotools and clang-tidy v18.
  This one needs to disable `clang-analyzer-valist.Uninitialized`
  to avoid false positives:
  https://github.com/llvm/llvm-project/issues/40656
  Duration: 5.5 minutes
- add clang-tidy job for macOS, using cmake and clang-tidy v19.
  This one also covers tests and examples, and doesn't hit the false
  positives seen with llvm v18 and earlier.
  Duration: 4.5 minutes
- Linux/macOS: skip installing test dependencies when not building or
  running tests.

fix fallouts reported by `clang-tidy`:
- lib:
  - cf-h2-proxy: unused assignment in non-debug builds.
  - cf-socket: silence warning.
    FIXME: https://github.com/curl/curl/pull/15825#issuecomment-2561867769
  - ftp: NULL passed to `strncmp()`.
  - http2: NULL-ptr deref.
  - mprintf: silence warning.
- src/tool_writeout: NULL passed to `fputs()`.
- examples:
  - invalid file pointers.
  - missing `fclose()`.
- tests:
  - http/clients/hx-download: memory leaks on error.
  - http/clients/hx-download: memory leak on repeat `-r` option.
  - server: double `fclose()`.
    https://www.man7.org/linux/man-pages/man3/fclose.3.html
  - server: invalid file pointer/handle.
  - server/getpart: unused assignments.
  - server/mqttd: leak on failed `realloc()`.
  - server/tftpd: NULL passed to `strcmp()`.

---

- [x] move CMake to separate PR? [NO]
- [x] add CMake `clang-tidy` job? [DONE]
- [x] suppress `clang-analyzer-valist.Uninitialized` ~~per-file~~ ~~per-line~~, not globally? [DONE for GHA/linux]
- [x] move clang-tidy to a single macOS job.

### CODE REVIEW

**Comment by vszakats** [comment]
There are lots of `clang-analyzer-valist.Uninitialized` false-positive warnings
(in tool_setopt, getinfo, multi, setopt and share) due to this clang-tidy issue:
https://github.com/llvm/llvm-project/issues/40656

I re-excluded it again to avoid the log noise, but it's possible to just have
them there, or to suppress via `/* NOLINT */` or `NOLINTBEGIN`/`NOLINTEND`
in source.

Ref: https://clang.llvm.org/extra/clang-tidy/#suppressing-undesired-diagnostics

**Comment by dfandrich** [comment]
Or, perhaps use an old version of clang-tidy? The bug report states 12–18 has
the problem, but it's not actually stated that <=11 doesn't have it.

**Comment by bagder** [comment]
> There are lots of clang-analyzer-valist.Uninitialized false-positive warnings

Yeah, we used to disable that warning before. I used clang-tidy 19.1.6 locally and I did not see it using this version anymore.

**Comment by vszakats** [comment]
llvm 10 is available on the Ubuntu 20.04 runner, but also affected by the bug:
  https://github.com/curl/curl/actions/runs/12488068561/job/34850007591

On macOS llvm@11 is not installable, but there is llvm 19, which 
indeed seems to have the `valist` false-positives fixed.

One option is to limit clang-tidy to macOS. It uses CMake there,
which runs it for tests and examples too.

For keeping the Linux job, we have these workaround options:
- disable the warning globally. (easy, but risks missing valid `valist` issues)
- disable per-file or per `switch` block. (almost as easy, with risk of missing valid issues in excluded code)
- disable it per line. (as committed ATM) (not pretty, but avoids the risk of missing valid issues.)

**Comment by vszakats** [comment]
This clang-tidy warning remains:
```
/Users/runner/work/curl/curl/lib/cf-socket.c:1853:8: warning: The 1st argument to 'connect' is -1 but should be >= 0 [clang-analyzer-unix.StdCLibraryFunctions]
 1853 |   rc = connect(ctx->sock, &ctx->addr.curl_sa_addr,
      |        ^
```
https://github.com/curl/curl/actions/runs/12492756056/job/34860387302#step:11:33

It's caught by `DEBUGASSERT()` in debug builds, but not otherwise,
and according to clang-tidy, it may happen.

**Comment by vszakats** [comment]
OK, I kept the Linux job and silenced the false-positives with
custom global option for the CI only.

I silenced the `cf-socket` issue with `NOLINT` and `FIXME`.
This needs a true fix.
https://github.com/curl/curl/pull/15825#issuecomment-2561867769

`tests/server/rtspd.c` could also probably use a better fix than the
rough one I committed.

I'd appreciate a review for the all warning fixes.

Other than these, this seems ready to merge.

**Comment by bagder** [comment]
> disable the warning globally. (easy, but risks missing valid valist issues)

I think that's fine, We ran many other tools as well that can discover such problems, plus we have never actually had a real such valist problem AFAICR.

**Comment by vszakats** [comment]
I'm merging this. valist warnings are kept by default and only disabled globally in Linux CI where hitting the pre-19 llvm.

Also the FIXME remains, ref https://github.com/curl/curl/pull/15825#issuecomment-2561867769.

**Pull request closed without merging**
