### PR TITLE
vtls: remove 'detach/attach' functions from TLS handler struct

### PR DESCRIPTION
**Pull request by bagder**
Unused since 7c8bae0d9c9b2dfeeb

### CODE REVIEW

**Comment by icing** [comment]
So far, connection filters never had a NULL implementation of a function. Because almost all call "down". `cntrl` does not do that, so NULL will work (with the added check), but I am not sure if this is a good idea.

**Comment by bagder** [comment]
I was not really sure it was a good idea or not. I'll make it a dummy function instead to stick to the pattern.

**Comment by icing** [comment]
> I was not really sure it was a good idea or not. I'll make it a dummy function instead to stick to the pattern.

Life `Curl_cf_def_cntrl`? 😌

**Review by icing — APPROVED** [review]

**Comment by testclutch** [comment]
Analysis of PR #15776 at [68e0cfb3](https://github.com/curl/curl/commit/68e0cfb305e4b42419fcd342a3e691a5f6f4d0b5):

[Test http/test_14_auth.py::TestAuth::test_14_03_digest_put_auth[0-h3] failed](https://github.com/curl/curl/actions/runs/12394541946/job/34598338169#check-step-25), which has NOT been flaky recently, so **there could be a real issue in this PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Pull request closed without merging**
