### PR TITLE
Enable retry after partial file download

### PR DESCRIPTION
**Pull request by bartoszcisek**
It would be super useful if cURL could retry after partial file download.

### CODE REVIEW

**Comment by bagder** [comment]
I'm afraid I disagree this being a good idea done like this.

This `CURLE_PARTIAL_FILE` error code is also commonly received due to stupid server implementations - not at all a transient or temporary situation. Such problems are not worth just trying again for. Also, just doing another transfer attempt when partial data was *uploaded* feels like it could lead to many problems.

**Comment by bartoszcisek** [comment]
Thanks for looking into it. I was just thinking that comparing to Apache and Nginx market share problem of stupid server implementations would be marginal. Additionally, even if a user would try to  get a file from a faulty server, there is an option to limit the number of retries. 

What do you think?

**Comment by bagder** [comment]
I don't like the retry anyway if it actually downloaded data. I think the correct way to retry on a partial transfer is to attempt to continue transferring the rest of the file and that would be a useful thing to add. Just getting it all again is wasteful and in many cases likely to get the same response again.

**Comment by bartoszcisek** [comment]
I understand your point. Unfortunately, I don't have time/skills to do it in a way you proposed. Thanks for a feedback. 

If anybody else has a similar problem, I may suggest switching to `wget` as it has all of those features out of the box.

**Pull request closed without merging**
