### PR TITLE
cd2nroff: fix duplicate output issue

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Jay Satiro @jay 
Fixes https://github.com/curl/curl-www/issues/321

### CODE REVIEW

**Comment by jay** [comment]
LGTM. I made a slight modification to check `@ARGV` directly. I tested both ways in bash in Windows:

~~~
/x/j/curl/curl/scripts/cd2nroff curl_escape.md | roffit >/tmp/temp.html
start /tmp/temp.html

/x/j/curl/curl/scripts/cd2nroff < curl_escape.md | roffit >/tmp/temp.html
start /tmp/temp.html
~~~

**Comment by vszakats** [comment]
Thanks @jay, @bagder. I really [wasn't sure](https://github.com/curl/curl/pull/12762#issuecomment-1905626112) if my code was solid. (and yet to figure out how the fix works!)

**Comment by jay** [comment]
> I really [wasn't sure](https://github.com/curl/curl/pull/12762#issuecomment-1905626112) if my code was solid. (and yet to figure out how the fix works!)

The bug was `$f = shift @ARGV;` because that is assigning $ARGV[0] to $f a second time since [`shift`](https://perldoc.perl.org/functions/shift) returns the argument that's removed. I've submitted #12819 which adds strict and warnings pragmas to help catch some things but it wouldn't have caught that.

**Comment by vszakats** [comment]
Oh, right! Rookie mistake, nothing to do with the language. Glad to see more warnings in any case.

**Pull request closed without merging**
