### PR TITLE
setopt: avoid integer overflows when setting millsecond values

### PR DESCRIPTION
**Pull request by bagder**
... that are multiplied by 1000 when stored. Also ignore negative timeout values.

### CODE REVIEW

**Comment by mkauf** [comment]
> Also ignore negative timeout values.

That may affect the backwards compatibility...

I think we should check for negative timeout values in the code:
* replace all "if(data->set.timeout)" with "if(data->set.timeout > 0)"
* replace all "if(data->set.connecttimeout)" with "if(data->set.connecttimeout > 0)"

**Comment by bagder** [comment]
(weird CI failures)

> That may affect the backwards compatibility

You mean for application that _on purpose_ set one of these values to a negative value? How would it otherwise affect existing apps?

Since these options are documented to be time-out values, in milliseconds, my view is that we have implied that negative values are not ok. I should probably amend this commit by clarifying that in the docs for them.

**Comment by mkauf** [comment]
> You mean for application that on purpose set one of these values to a negative value?

Yes. Maybe an application does not use a fixed timeout value, but calculates it in a weird way, so that it may get negative. This negative timeout should replace/disable the existing timeout.

**Comment by bagder** [comment]
But that's asking for bug or side-effect compatibility since setting a negative timeout has never been explicitly supported. I don't think we need to be very concerned about that, at least not as long as they are mostly theoretical edge cases.

**Comment by bagder** [comment]
One could argue that we help those wrong-doing applications by returning an error code for this case...

**Comment by bagder** [comment]
Refreshed, now with updated man pages and the commit message now mentions that the max timeout time these support is slightly over 596 hours on 32 bit long systems.

**Comment by mkauf** [comment]
I think it's important that libcurl behaves in a consistent way regarding negative timeouts, so it should also reject them for ``CURLOPT_ACCEPTTIMEOUT_MS``, ``CURLOPT_CONNECTTIMEOUT_MS``, ``CURLOPT_EXPECT_100_TIMEOUT_MS``, ``CURLOPT_TIMEOUT_MS``

**Comment by bagder** [comment]
Agreed! While my initial focus was to address the undefined behavior, I quite agree that inconsistency here isn't very good and also accepting bad values is also not good. I'll amend this...

**Comment by bagder** [comment]
(I will probably try to land #1944 first, then rebase this work. To minimize the necessary conflict resolution work...)

**Comment by bagder** [comment]
Or maybe this one first, then redo the #1944 ...

**Pull request closed without merging**
