### PR TITLE
Add CMake CI

### PR DESCRIPTION
**Pull request by scivision**
Add CMake CI for Windows MSYS2 with OpenSSH build.
I implemented it as simply as possible (compare to Curl's AppVeyor MSYS implementation). It can do more than this, as desired.

Also, simple modernization of CMake 3.x syntax.

This is a starting point for a modernization of Curl's CMake in future PRs.

### CODE REVIEW

**Comment by bagder** [comment]
> Add CMake CI for Linux

We already do some CI jobs with cmake on Linux on travis. What does this build add that we don't already verify there?

**Comment by scivision** [comment]
Thanks I just stuck to adding Windows MSYS2 with OpenSSL then.

**Comment by bagder** [comment]
Aren't we doing such builds on Appveyor already? What else do these new ones add?

**Comment by bagder** [comment]
No response, closing

**Pull request closed without merging**
