### PR TITLE
openssl: TLS 1.3 middlebox compatibility mode option

### PR DESCRIPTION
**Pull request by danielgustafsson**
This adds support for enabling or disabling the TLS 1.3 middlebox compatibility mode when using the OpenSSL tls backend. The new option is named `--tls13-middlebox` and takes a boolean. It is on by default.

This is an alternative version of #3221 in which @technoLord asked for some assistance with the libcurl parts. The main change in this version of the patch is that the option is a neutral on/off rather than a "disable-X" option. The rationale being that we might want to disable middlebox compatibility by default, and if we do a disable-X option would require an awkward double negative switch for enabling it. A neutral switch leaves the door open for future changes. On top of that, this patch has some small levels of cleanup. This duplicates #3221 as I'm not authorized to push to the repo of that PR.

Ping @technoLord, what do you think about this one?

### CODE REVIEW

**Comment by bagder** [comment]
`CURLOPT_SSL_OPTIONS.3` should have this bit documented too, right?

My only little concern about this option is that we have no way to ask the TLS library to use what it thinks is fine. OpenSSL 1.1.1 says it will use this option enabled by default but they *may* change that in a future, and when we explicitly set or clear the bit we will not ever just ride on OpenSSL's future changed behavior...

**Comment by danielgustafsson** [comment]
> `CURLOPT_SSL_OPTIONS.3` should have this bit documented too, right?

Correct, fixed and updated.

> My only little concern about this option is that we have no way to ask the TLS library to use what it thinks is fine.

Fair enough, thats a good point.

> OpenSSL 1.1.1 says it will use this option enabled by default but they _may_ change that in a future, and when we explicitly set or clear the bit we will not ever just ride on OpenSSL's future changed behavior...

If the default in OpenSSL is changed to disabled however, it will be quite awkward to only have a `--disable-XYZ` option requiring a double negative to enable it again. Adding another option for enabling at that point seems overkill too.

**Comment by technoLord** [comment]
Tested. OK

**Comment by jay** [comment]
My understanding of this is OpenSSL sends TLS 1.2 messages for compatibility with middleboxes (intercepting/examining/modifying traffic) that don't understand TLS 1.3. AFAICT it's harmless so why would we want to disable it?

(longread [here](https://blog.cloudflare.com/why-tls-1-3-isnt-in-browsers-yet/))

**Comment by loganaden** [comment]
@jay useful when making purchasing decisions in case you have a vendor equipment which doesn't implement TLS properly.

**Comment by danielgustafsson** [comment]
I think we need to come to a conclusion whether we wan't this or not. I don't have strong opinions, I merely wanted to give it a fighting chance. Any +1/-1's ?

**Comment by loganaden** [comment]
@bagder honestly, knowing how many broken middleboxes have been deployed and how much time it's going to take till 99% of them are replaced/updated, i think it's safe to say that OpenSSL isn't going to change the behaviour until a very very long time. Btw, python offers the option in v3.8:

ssl.OP_ENABLE_MIDDLEBOX_COMPAT¶
Send dummy Change Cipher Spec (CCS) messages in TLS 1.3 handshake to make a TLS 1.3 connection look more like a TLS 1.2 connection.

This option is only available with OpenSSL 1.1.1 and later.

New in version 3.8.

I'd much rather have a curl option to disable middlebox, rather than writing a python script ...

**Comment by bagder** [comment]
Note that this is still a complaint by travis:
~~~
 --tls13-middlebox is not in curl.1 (but in tool_getparam.c tool_help.c)
~~~

I'm fine with adding this once the CI is green.

**Comment by danielgustafsson** [comment]
I've updated the patch to now say 7.65.0 and to include the option in `curl.1`.

**Comment by jay** [comment]
> Any +1/-1's ?

I'm -1 unless I can see what problem this solves. The compatibility feature isn't causing any compatibility problems of its own so I don't see any reason to disable it. Testing purposes isn't good enough in my opinion. Like what is the use of this in curl other than testing purposes. I'm not against a testing mode in curl in theory (like curl tries several different ways to make an ssl connection to the same server and reports what worked) but to have individual options for each ssl feature seems excessive. If he wants to test just that feature right now he can use the ctx callback in libcurl.

**Comment by danielgustafsson** [comment]
> The compatibility feature isn't causing any compatibility problems of its own so I don't see any reason to disable it.

Does that mean you are against the feature as it's currently coded, or the feature in general? My interpretation is the latter but I'd rather be sure than make assumptions.

**Comment by jay** [comment]
It's the latter I just don't see a use case other than testing. If OpenSSL disables it by default we can deal with that then.

**Comment by danielgustafsson** [comment]
I don't feel that there is enough consensus, or interest, to warrant pursuing this further. Closing.

**Pull request closed without merging**
