### PR TITLE
Windows Build: OpenSSL 1.1 and ZLIB

### PR DESCRIPTION
**Pull request by rodwiddowson**
The Shibboleth project ships our own windows build of our complete dependency stack.  This include cURL and OpenSSL and zlib.

This is a reasonably complicated affair (particularly for OpenSSL) since our paradigm is 
* to have a completely built tree (out32, out64, out32.dbg and so on) and build from that
* to take more control over the names of the libs and DLLs since many projects have historically played fast and loose with the ABI contract (and once bitten twice shy).

See for instance the [OpenSSL build](https://wiki.shibboleth.net/confluence/display/OpenSAML/OpenSSL) notes. This has down stream impact on our [cURL build](https://wiki.shibboleth.net/confluence/display/OpenSAML/libcurl)

In preparing to move to OpenSSL 1.1 it appears that the cURL nmake based windows build is slightly behind the curve with respect to the new locations and names.  The first commit in this stream fixes this in a backwards compatible manner, while also making it easy for use to significantly simplify our build of cURL.

The second patch is not motivated by any change in the dependencies, but allows us to simplify our curl build significantly to the level that we can do the build with no edits to the generated make files (yay!).

This has been tested against VC10.

### CODE REVIEW

**Comment by bagder** [comment]
Is there a particular reason why you've chosen to stick with that build setup and not the one we provide in the winbuild/ subdir?

We have too many windows build options (which is confusing to users) and I would prefer to drop the old name one in favor of the winbuild one at some point in time...

**Comment by rodwiddowson** [comment]
Our use of that is purely historical - you find something that worked (probably well over 10 years ago, certainly before I joined Shibboleth in '06)

Would it be more helpful to work with winbuild?  If so I'll take a spin though that, see what's its doing and what is missing and submit a different patch (if needed).  (anything is better than endless dealing with now-opaque-in-OpenSSL structures)

Thanks!

/Rod

**Comment by rodwiddowson** [comment]
Damn.  Hit the wrong button.  The comment is still valid however (do you want me to look at OpenSSL1.1 and \winbuild)?

**Comment by bagder** [comment]
Yes, it would be more helpful if you could look at switching your build to use the winbuild setup. Then we would be a small step closer to removing the Makefile.vc* files.

And feel free to try out OpenSSL 1.1 too, I believe we build and work fine with it.

**Comment by rodwiddowson** [comment]
> Yes, it would be more helpful if you could look at switching your build to use the winbuild setup. 

Onto it.

> And feel free to try out OpenSSL 1.1 too, I believe we build and work fine with it.

It was a huge comfort that you were ahead of me when I started down that road.  Should I close the pull request and do a new one?

R

**Comment by bagder** [comment]
Just update this or create a new, I leave that to you!

**Comment by rodwiddowson** [comment]
I've bludgeoned the new system into doing what I need.

I'm about to submit a PR stream with some (mostly cosmetic) changes for the new build system. 

I'll take the structural questions about the 2x4 I need to make the new system work with with OpenSSL1.1  to the dev list.

Thanks

**Pull request closed without merging**
