### PR TITLE
HTTP/3 (ngtcp2 and quiche) and alt-svc support in CMake

### PR DESCRIPTION
**Pull request by Lekensteyn**
autotools leaves a mess in my source directories, obviously I am going to fix CMake support in order to test HTTP/3 changes :-)

I built nghttp3 and ngtcp2 with CMake (the latter requires https://github.com/ngtcp2/ngtcp2/pull/240 - not needed for autotools) and:
```
PKG_CONFIG_PATH=/tmp/openssl/prefix/lib/pkgconfig:/tmp/nghttp3/prefix/lib/pkgconfig:/tmp/ngtcp2/prefix/lib/pkgconfig \
cmake -GNinja -DUSE_NGTCP2=1 ~/projects/curl
```

The curl+quiche+boringssl build was configured with:
```sh
# quiche
cargo build -v --release --features pkg-config-meta,qlog
mkdir -p deps/boringssl/lib && ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) deps/boringssl/lib/

# curl
PKG_CONFIG_PATH=/tmp/quiche/target/release \
cmake -GNinja ~/projects/curl \
    -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=1 \
    -DCMAKE_C_FLAGS=-fsanitize=address,undefined \
    -DUSE_QUICHE=1 -DENABLE_ALT_SVC=1 \
    -DOPENSSL_ROOT_DIR=/tmp/quiche/deps/boringssl \
    -DCURL_DISABLE_LDAP=ON -DCURL_DISABLE_LDAPS=ON -DCMAKE_USE_LIBSSH2=OFF
```

My local build works, `curl -v --http3 https://cloudflare.com` and `curl --alt-svc altsvc.cache -vk https://cloudflare.com` (twice) works. Now let's see whether Travis is happy.

### CODE REVIEW

**Comment by Lekensteyn** [comment]
Yay, the ngtcp2 build passes in Travis CI! I just forgot to set `-DUSE_QUICHE=1` for the quiche build though :facepalm:, trying again...

**Comment by Lekensteyn** [comment]
The quiche_conn_set_qlog_fd check was missing some `CMAKE_REQUIRED_xxx` settings, fixed. I verified locally that it works, but it needs https://github.com/cloudflare/quiche/pull/507 or else detection will fail.

If really needed, I could define `size_t` and `ssize_t` macros, but as users typically use the latest version of quiche I did not bother.

**Comment by Lekensteyn** [comment]
I've also managed to get this to build on macOS. This does *not* require pkg-config unlike the autotools build:
```
cd quiche
cargo build --release --features pkg-config-meta,qlog
ln -sv target/release/libquiche.{a,dylib} ./
mkdir -p deps/boringssl/lib && ln -vnf $(find target/release -name libcrypto.a -o -name libssl.a) deps/boringssl/lib/
cd ..

cd curl
mkdir build && cd build
cmake -GNinja -DOPENSSL_ROOT_DIR=$PWD/../../quiche/deps/boringssl -DQUICHE_ROOT=$PWD/../../quiche .. -DUSE_QUICHE=1
ninja curl
```

Result:
```
$ src/curl --version
curl 7.71.0-DEV (Darwin) libcurl/7.71.0-DEV BoringSSL zlib/1.2.11 quiche/0.3.0
Release-Date: [unreleased]
Protocols: dict file ftp ftps gopher http https imap imaps ldap pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS HTTP3 HTTPS-proxy IPv6 Largefile libz NTLM SSL UnixSockets

$ src/curl -v --http3 https://cloudflare.com
*   Trying 104.17.175.85:443...
* Sent QUIC client Initial, ALPN: h3-27
* Connected to cloudflare.com (104.17.175.85) port 443 (#0)
* h3 [:method: GET]
...
< HTTP/3 301
...
* Connection #0 to host cloudflare.com left intact
```

**Comment by bagder** [comment]
Thanks @Lekensteyn. Do you think it would be valuable to document that build method in docs/HTTP3.md too or will it just get too crowded?

**Comment by Lekensteyn** [comment]
@bagder I've a patch to simplify those instructions + simplify CI, I'll push it into #5370 for review since it is somewhat related.

**Pull request closed without merging**
