### PR TITLE
cmake: migrate from USE_DARWINSSL to USE_SECTRANSP

### LINKED ISSUE #3733: cmake: DarwinSSL setting not passed to curl configuration
In https://github.com/curl/curl/pull/3619, `USE_DARWINSSL`was renamed to `USE_SECTRANSP`. However, in https://github.com/curl/curl/blob/curl-7_64_1/CMakeLists.txt#L344 the old configuration is used.

This currently leads to an active DarwinSSL feature but no SSL backend:

```
$ bash /build_dir/curl/curl-config --features
DarwinSSL
IPv6
unix-sockets
libz
AsynchDNS
```

```
$ bash /build_dir/curl/curl-config --ssl-backends

```

(btw: where does this empty output line come from?).

I'm working on a PR to get this fixed.

### PR DESCRIPTION
**Pull request by webmaster128**
Closes #3733

### CODE REVIEW

**Comment by jzakrzewski** [comment]
One thing I find quite ugly is the usage of CMAKE_ prefix for our options/variables.
Could we avoid this at least for the new code? Tools also tend to group the options according to the variable prefix. Ideally we would decide on some kind of naming scheme and clean this up once but I'm a bit worried about existing scripts.

**Comment by webmaster128** [comment]
> One thing I find quite ugly is the usage of CMAKE_ prefix for our options/variables.
> Could we avoid this at least for the new code? Tools also tend to group the options according to the variable prefix. Ideally we would decide on some kind of naming scheme and clean this up once but I'm a bit worried about existing scripts.

What I like about the current setup is having two distinct variables for two different levels. As you can in a commit-by-commit review, the first commit alone would have closed #3733 by changing the internal USE_DARWINSSL -> USE_SECTRANSP without changing the public cmake interface.

I have no opinion on the nicest possible naming for cmake options, as I am not a cmake expert.

**Comment by past-due** [comment]
I'm hoping this can be merged before the next release?

For clarity: building via CMake with the DarwinSSL/SecureTransport backend is currently _**broken**_ (since 7.64.1), and this fixes it.

**Comment by webmaster128** [comment]
@past-due did you test this patch in your setup? If yes, that is valuable feedback and could help bringing this in. @MarcelRaad was so kind to review and merge the last cmake relates PR from me. Maybe he can find the time to have a look at this.

**Comment by MarcelRaad** [comment]
Unfortunately I don't have a Mac and we don't have CMake SecureTransport CI builds, so I'd prefer if someone else tried this out before merging. Looks good to me though.

**Comment by past-due** [comment]
@webmaster128, @MarcelRaad: Tested this patch on macOS 10.12 & 10.13. It successfully fixes the CMake SecureTransport builds.

I will look into adding CMake SecureTransport builds to the Travis CI config (as a separate PR).

**Comment by MarcelRaad** [comment]
Thanks! If noone else does, I'll merge as soon as I'm near a computer again, which will probably be late next week.

**Comment by MarcelRaad** [comment]
Merged now. Thanks again!

**Pull request closed without merging**
