### PR TITLE
Fixing secure-transport IO for incomplete read/writes. Refs #10227.

### PR DESCRIPTION
**Pull request by icing**
SecureTransport expects result code errSSLWouldBlock when the requested length could not be sent/recieved in full. The previous code returned noErr, which let SecureTransport to believe that the IO had terminated prematurely.

### CODE REVIEW

**Comment by hjmallon** [comment]
I have just tested this locally and it appears to fix the `curl: (35) Internal SSL engine error encountered during the SSL handshake` issue! Thanks (this is excelled software support for $0).

**Review by bagder — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Comment by wolfv** [comment]
We've been seeing this error on macOS x64 with curl 7.87 (logs: https://github.com/mamba-org/mamba/actions/runs/3847932244/jobs/6555036152)

```
    Download error (56) Failure when receiving data from the peer [https://conda.anaconda.org/conda-forge/noarch/repodata.json]
    SSLRead() return error -50
```

Do you think that could also be fixed with this?

**Comment by icing** [comment]
@wolfv that seems very likely, yes.

**Pull request closed without merging**
