### PR TITLE
Add Cmake option to turn off installs

### PR DESCRIPTION
**Pull request by 8W9aG**
* Installs are not desirable on systems that do
not use shared libraries (e.g. android or iOS)
* Attempting to build OpenSSL in Cmake and then
linking it with cURL static libraries fails on
the install step due to these libraries being
static and not exported properly

### CODE REVIEW

**Comment by bagder** [comment]
Isn't install optional anyway?

**Comment by 8W9aG** [comment]
The target is optional to invoke, but the creation of that target isn't and that's what is failing

**Comment by bagder** [comment]
Why isn't the fix to make sure the creation of the target works rather than to avoid creating it?

**Comment by 8W9aG** [comment]
Because the creation of the target doesn't make sense on cross compiled platforms

**Comment by bagder** [comment]
So can't the script then automatically disable that section when cmake is used for cross-compiling?

**Comment by jzakrzewski** [comment]
I've never seen conditional creation of install targets in CMake. They are simply not invoked when not needed. If the install target fail to be created maybe you could share the symptoms? Error messages?

**Comment by snikulov** [comment]
@jzakrzewski I suspect it is important when you using `add_subdirectori(curl)` in a top project. This will add curl install targets to a topmost project. And this is what @8W9aG trying to avoid.
So @8W9aG trying to add the solution for his particular project. 
@8W9aG Am I correct?

**Comment by jzakrzewski** [comment]
Oh, yeah, for me it's always strange that people insist on going with `add_subdirectory` for external, non-header-only libraries. With perhaps the exception of googletest which is designed to be included that way, I see it as asking for trouble.
It seems I'm alone with this opinion though.

**Comment by 8W9aG** [comment]
I can confirm this is for a project using `add_subdirectory(curl)`

**Comment by snikulov** [comment]
@8W9aG What about [`ExternalProject_Add`](https://cmake.org/cmake/help/v3.2/module/ExternalProject.html) or just `find_package(...)` instead?
It's a bad idea to solve your project structure by patching external projects, IMHO.

**Comment by 8W9aG** [comment]
I do believe we tried that long ago but had some problems, I will see what those problems were today and report back

**Comment by snikulov** [comment]
@8W9aG What about option `EXCLUDE_FROM_ALL` in [`add_subdirectory(...)`](https://cmake.org/cmake/help/v3.0/command/add_subdirectory.html) command?
Personally, I've never tried this mechanism, but it should work [according to this thread.](http://cmake.3232098.n2.nabble.com/Disabling-INSTALL-target-for-subdirectory-td7595059.html)
Also, you'll find in this mail thread an explanation, why it should not be used in an `add_subdirectory(...)` way for externals.

**Comment by snikulov** [comment]
@8W9aG Any update on my suggestion? Can we close this?

**Comment by snikulov** [comment]
@bagder since no response from submitter.

**Pull request closed without merging**
