### PR TITLE
runtests: report single test time + total duration

### PR DESCRIPTION
**Pull request by bagder**
... after each successful test.

### CODE REVIEW

**Comment by cmeister2** [comment]
Interesting results. Should valgrind be running on most variants? It would appear to add ~10 minutes to the test time.

**Comment by MarcelRaad** [comment]
The problem with Valgrind is: Valgrind + OpenSSL + Xenial makes Valgrind crash because of an assertion failure.

**Comment by cmeister2** [comment]
@marcelraad I actually meant the negative; should valgrind be disabled on all but a "maximal" build, so that CI finishes more quickly in general?

**Comment by bagder** [comment]
The challange is with all the various build combinations and making sure they all have at least one build that runs with valgrind enabled. Ie there cannot be just one "maximal" build  since there are so many alternative options and mutually exclusive ones. But yes, switching off valgrind for the builds that make sense will certainly make them run faster!

**Comment by bagder** [comment]
I like the new timing information output like this! I'll let the PR sit here a while to collect input from others if someone has objections, but if nobody does I'll merge it later.

**Comment by dfandrich** [comment]
On Fri, Jun 14, 2019 at 05:08:54AM -0700, Daniel Stenberg wrote:
> The challange is with all the various build combinations and making sure they
> all have at least one build that runs with valgrind enabled.

ASAN, MSAN and UBSAN catch a lot of the same things that Valgrind do with much
less overhead. Enabling those in more builds might be a workable alternative.

**Pull request closed without merging**
