### PR TITLE
CI: fixup: future macos xcode issues for cmake gcc builds

### PR DESCRIPTION
**Pull request by pheiduck**
New way to fix: https://github.com/curl/curl/issues/10356

### CODE REVIEW

**Comment by pheiduck** [comment]
Works as exacted, we need to solve the Copyright thing on reuse.

**Comment by pheiduck** [comment]
@bagder, @icing, @jay, @mback2k and @dfandrich can someone take a look?
Also give me hints, where I can place the patches?
Not sure if they can be used on the makefile?

**Comment by jay** [comment]
> New way to fix: #10356

This is a lot of code. Why is the current fix not enough? There is no context here for why all this code is necessary. What exactly causes the issue?

**Comment by pheiduck** [comment]
@jay I don't know what exactly triggers this error, but it is not possible to build curl with cmake and gcc on recent xcode versions 14.1 < 14.3
I have locally examined the files and fixed the places that trigger the error.
Among other things, the error is present from 14.1 to 14.3.

**Comment by pheiduck** [comment]
@bagder I have opened an issue be apple directly.

**Comment by pheiduck** [comment]
@bagder
Apple told me that gcc causes the error and it is not Apple's fault they only support clang.

**Pull request closed without merging**
