### PR TITLE
cmake: support ngtcp2 boringssl backend

### PR DESCRIPTION
**Pull request by donny-dont**
Update the ngtcp2 find module to detect the boringssl backend. Determine if the underlying OpenSSL implementation is BoringSSL and if so use that as the ngtcp2 backend.

### CODE REVIEW

**Comment by donny-dont** [comment]
Makes it so https://github.com/curl/curl/pull/8789 will build in CMake. I'm guessing maybe the autotools one already works with the ngtcp2 + BoringSSL backend. If not then something like this would also need to be done.

**Comment by donny-dont** [comment]
Hey @bagder anything in particular you want addressed here? I was able to build a version of curl with HTTP/3 support and run it in on the curl network backend in WebKit.

**Comment by bagder** [comment]
I was hoping someone who knows cmake would chime in...

**Comment by jzakrzewski** [comment]
I don't have time to build & test, but otherwise it looks clean to me.

**Comment by bagder** [comment]
Thanks!

**Comment by donny-dont** [comment]
Thanks @jzakrzewski and @bagder !

**Pull request closed without merging**
