### PR TITLE
macos.yml: revert to Xcode 14.0.1 to avoid cmake/gcc-11 build errors

### PR DESCRIPTION
**Pull request by pheiduck**
Possible fix for: https://github.com/curl/curl/issues/10356

### CODE REVIEW

**Comment by jay** [comment]
Thanks, that seems to have done the trick. Is there something wrong with Xcode 14.2?

**Comment by pheiduck** [comment]
> Thanks, that seems to have done the trick. Is there something wrong with Xcode 14.2?
I am currently still not sure if xcode is really the sloppy one for the error. Maybe it is also a problem in connection with gcc-11?
I will try it with gcc-12.

**Comment by pheiduck** [comment]
Okay doesn't matter. It's xcode related

**Comment by bagder** [comment]
I feel inclined to merge this to get away from the annoyances of https://github.com/curl/curl/issues/10356 

@jay @icing what do you think?

**Comment by jay** [comment]
I'm fine with it. I think we can assume for now this is an xcode issue and try the next version when it's released as @pheiduck suggested.

**Comment by bagder** [comment]
Thanks!

**Comment by pheiduck** [comment]
@bagder xcode 14.3 is still in beta: https://developer.apple.com/documentation/xcode-release-notes/xcode-14_3-release-notes

so we can revert this PR, when GH CI is bumped to macOS 13 w/ xcode 14.3

**Pull request closed without merging**
