### PR TITLE
errors: new alias CURLE_WEIRD_SERVER_REPLY (8)

### PR DESCRIPTION
**Pull request by jay**
Since we're using CURLE_FTP_WEIRD_SERVER_REPLY in imap, pop3 and smtp as
more of a generic "failed to parse" introduce an alias without FTP in
the name.

### CODE REVIEW

**Comment by jay** [comment]
I'm not sure about the SDL file, whether I can use the same number twice. This will need a review from whoever handles VMS. Also @monnerat since I'm not sure if I can do the same in curl.inc.in

**Comment by bagder** [comment]
I'm in favor! But since we probably cannot see this as a bug-fix, I suggest we hold off and merge after the pending release.

**Comment by jay** [comment]
ok

**Comment by monnerat** [comment]
@jay: this should be perfect for OS400, you even did upgrade the ILE/RPG language interface. Many thanks.

**Pull request closed without merging**
