### PR TITLE
noproxy: explictly support space-separated no proxy hosts/domains

### PR DESCRIPTION
**Pull request by michael-o**
For a long time curl implicitly supported space-separated, along with comma-separated, hosts/domains either via API or no_proxy/NO_PROXY. To clarify and extend flexibility explicitly support/document the status quo now.

For the past 10 years or so I have been using this on FreeBSD to access the outside world with curl and especially with Git.

Motivation:
1. Making the obvious official/public
2. I have raised similar with `py-requests` and stated that curl unofficially supports this too. Well, the maintainers said: not documented, closed and locked which is a pity: https://github.com/psf/requests/pull/5465

I have also put [this](https://about.gitlab.com/blog/2021/01/27/we-need-to-talk-no-proxy/) into consideration.

### CODE REVIEW

**Comment by bagder** [comment]
I checked, it was documented as a *comma-separated* list already before my recent refresh of the noproxy code. It was never documented or otherwise suggested that it was fine with just space separation. That was just accidentally working.

I don't quite understand what the benefit is (for the world) to make the formerly undocumented feature officially supported, especially when other implementations don't support space either and even that gitlab page suggests that the common style should be comma-separated.

I understand the benefit *to you* since doing as this PR would bring back a noproxy string you used before to work again. To me it seems to be less work to rather just insert commas in your list.

**Comment by michael-o** [comment]
OK. let me clarify my motivation for this. There are aspects which led me to this PR:

1. I have relied on undefined behavior for way too long (10+ years on HP-UX, FreeBSD and RHEL) and never cared. This is my failure and I don't want to continue it. I actually only noticed it when in 7.86.0 the noproxy stuff was broken and started to use py-requests in recent years which lead to the same issue. I also compared at least to FreeBSD's `libfetch(3)` which does both and even refers to curl 20+ years ago: https://github.com/freebsd/freebsd-src/blob/17f2b12a3877f460f72123242c068881806388c2/lib/libfetch/common.c#L1760-L1767
2. Now I also tried to fix the [root cause](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236204), but there is little progress for almost three years. I tried to go down to py-requests where my [request was rejected](https://github.com/psf/requests/pull/5465) and stated that curl does not do this, so we won't neither. Tried to reach out downstream to the FreeBSD port maintainer who [rejected and requested to upstream this](https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=236204). So basically I am going circles now and am in a deadlock situation. That is why I wanted to reach out here because if this works here, likely others will react.

I see two options to resolve this properly:
1. Make it official becaue it worked unofficially/unintentionally for 20+ years.
2. Remove/tighten it and make it clear what the behavior is which will put some pressure on others to clean up their stuff.

Either way, a predictable, well understood behavior is important.

Let me know what you think!

**Comment by bagder** [comment]
> Either way, a predictable, well understood behavior is important.

Agreed. The lowest common denominator among implementations as far as separators go seems to be the comma. Not space.

Making curl support spaces (again) will certainly bring back the previous functionality for users of curl and libcurl but it seems to little to unify the implementations; quite the opposite. It seems many of the implementations don't support space now and have rejected doing so. Opening up for space now will only bring back an uncertainty and ambiguity that doesn't help.

To me, it seems to be generally more helpful to the "noproxy community" at large to *not* allow spaces, since using commas has a much greater chance for interop.

This also matches what the gitlab page suggests a "standard" noproxy parser should do - and I believe curl actually works exactly like the bullet points say under "Standardizing" on that page.

**Comment by michael-o** [comment]
To me, it seems to be generally more helpful to the "noproxy community" at large to not allow spaces, since using commas has a much greater chance for interop.

This would mean that you have to tighten the parser, no? This would be logical.

**Comment by bagder** [comment]
> This would mean that you have to tighten the parser, no? This would be logical.

I thought you wanted to bring back space-separation because it does not currently work. What needs to be tightened do you mean?

**Comment by michael-o** [comment]
> > This would mean that you have to tighten the parser, no? This would be logical.
> 
> I thought you wanted to bring back space-separation because it does not currently work. What needs to be tightened do you mean?

You misunderstood. It **does** work, but is not official. You said that it should not be supported, this would mean that it would not be supported unofficially (code change). I, of course prefer to make it official, but, of course, the decision is up to you.

**Comment by bagder** [comment]
>  It **does** work, but is not official

Sorry for being slow. 

So it *does* still work, and it has worked for a long time. That puts it in a slightly different light to me. But only slightly. It was never documented to work with spaces as separators and only a small subset of noproxy parsers seem to accept them as separators.

The remaining question is then probably only if we should rather leave it undocumented and still insist on commas in the documentation, or if we should go ahead and make commas required between patterns.

**Comment by michael-o** [comment]
> > It **does** work, but is not official
> 
> Sorry for being slow.
> 
> So it _does_ still work, and it has worked for a long time. That puts it in a slightly different light to me. But only slightly. It was never documented to work with spaces as separators and only a small subset of noproxy parsers seem to accept them as separators.
> 
> The remaining question is then probably only if we should rather leave it undocumented and still insist on commas in the documentation, or if we should go ahead and make commas required between patterns.

Correct, that is the cardinal question.

Working example with spaces: https://github.com/psf/requests/pull/5465#issuecomment-754496977

**Comment by bagder** [comment]
How about this approach:

We *deprecate* support for space-separated patterns in the noproxy string. By this I mean that we set a time in the future (at least 6 months into the future) when we declare we will remove support for them. Until then we produce a warning into the verbose output when a space-separated pattern is used.

This gives everyone a chance to react and transition until we take it away.

**Comment by michael-o** [comment]
> How about this approach:
> 
> We _deprecate_ support for space-separated patterns in the noproxy string. By this I mean that we set a time in the future (at least 6 months into the future) when we declare we will remove support for them. Until then we produce a warning into the verbose output when a space-separated pattern is used.
> 
> This gives everyone a chance to react and transition until we take it away.

This is something I can live with. Willing to test a patch.

**Comment by bagder** [comment]
Ok, let's make it 18 months from now. July 2024. I'll make a PR you can try.

**Comment by michael-o** [comment]
> Ok, let's make it 18 months from now. July 2024. I'll make a PR you can try.

Thanks, looking forward too.

**Pull request closed without merging**
