### PR TITLE
travis: Fix error detection

### PR DESCRIPTION
**Pull request by jay**
- Stop using inline shell scripts for before_script and script sections.

Prior to this change Travis could ignore errors from commands in inline
scripts. I don't understand how or why it happens. This is a workaround.

Assisted-by: Simon Warta

Closes #xxxx

---

/cc @webmaster128

### CODE REVIEW

**Comment by jay** [comment]
Failures in codacy due to code quality and Travis CI has a bunch failures libunistring not found:
~~~
Making install in unistring
make[1]: Entering directory `/home/travis/libidn2-2.0.4/unistring'
make  install-recursive
make[2]: Entering directory `/home/travis/libidn2-2.0.4/unistring'
make[3]: Entering directory `/home/travis/libidn2-2.0.4/unistring'
  CCLD     libunistring.la
ar: /home/travis/libidn2-2.0.4/unistring/.libs/libunistring.a: No such file or directory
make[3]: *** [libunistring.la] Error 9
make[3]: Leaving directory `/home/travis/libidn2-2.0.4/unistring'
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory `/home/travis/libidn2-2.0.4/unistring'
make[1]: *** [install] Error 2
make[1]: Leaving directory `/home/travis/libidn2-2.0.4/unistring'
make: *** [install-recursive] Error 1
~~~
Any ideas?

**Comment by bagder** [comment]
I suppose this just underscores that getting travis to do right is mostly magic and fairy dust...

**Comment by webmaster128** [comment]
The fail existed before as well but did not cause a red CI due to the issue we are talking about here.

Parent commit: https://github.com/curl/curl/commit/c4e0be44089408d65220ab0174ad3443724092a0
Build: https://travis-ci.org/curl/curl/builds/517501921
In [job number 7](https://travis-ci.org/curl/curl/jobs/517501928) there is the same thing in the logs: https://api.travis-ci.org/v3/job/517501928/log.txt

**Comment by bagder** [comment]
Thanks!

The libidn2 build gets that error but it seems it has no further impact on that build, as the curl build then ultimately still ends up with `IDN` as a feature !? Is that perhaps because the libidn2 is already good enough in the apt installed version so we build it locally in vein?

**Comment by bagder** [comment]
Time to rebase this effort and try again? It needs fewer custom builds now and the libidn2 build is gone...

**Comment by webmaster128** [comment]
Looks like Codacy/PR Quality Review has some very valid remarks regarding the new .sh scripts. Fixing this scripts is probably out of scope but still worth loocking at one day or another. Most of them are also detected by shellcheck (which can easily be run locally).

**Comment by bagder** [comment]
Since work dropped on this, close it.

**Comment by jay** [comment]
Resurrected

**Pull request closed without merging**
