### PR TITLE
support .P12 or .PFX certificat client file with MS-Windows Schannel

### PR DESCRIPTION
**Pull request by gvollant**
this branch add support .P12 or .PFX certificat client file with curl compiled against MS-Windows Schannel
to be used with curl command line option: --cert <filename>:<password> --cert-type p12

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by gvollant** [comment]
do you known why this PR is closed?

**Comment by bagder** [comment]
"@bagder closed this in 0fdf965 14 minutes ago " <= means that it was closed due to an instruction in a commit that was merged into curl. That's github's quirky way of saying it was merged but not merged via github.

**Comment by gvollant** [comment]
this was same code in https://github.com/curl/curl/pull/4356 , but this old PR was closed without merge

**Comment by bagder** [comment]
*you* closed #4733 

> **gvollant** closed this on Sep 22, 2019

**Comment by gvollant** [comment]
yes. But I think it is useful have a link between discussion for archive

**Pull request closed without merging**
