### PR TITLE
cmake: error if can't find required pthreads

### PR DESCRIPTION
**Pull request by paulharris**
See #1700

### CODE REVIEW

**Comment by snikulov** [comment]
@paulharris Why not try just use find_package(Threads REQUIRED) ?
Current CMakeLists have so many lines in it so nobody able to understand it.

@bagder How should it be? Are threads really should be enforced?

**Comment by paulharris** [comment]
You can't use find_package(Threads REQUIRED) because it doesn't run that
line if it doesn't find pthreads.h
Perhaps we can skip the pthreads.h test, and just look for the threads
package...

I don't think the cmakelists.txt file is too bad,
I find the ./configure automake files much harder to read,
I guess its just what you are used to.

But, I am not sure of what the cmake author's intent is at all the stages,
which is why I hesitate to change it radically,
hence my pull-patch referenced here just adds some fatal errors if threads
are ticked but can't be delivered.

**Comment by snikulov** [comment]
@paulharris Then you probably should re-write it without checking for pthreads.h first and re-test. Why not?
I strongly believe that patch working only increase technical debt. Less code, fewer bugs.

**Comment by snikulov** [comment]
@paulharris better and cleaner
```
if(ENABLE_THREADED_RESOLVER)
  find_package(Threads REQUIRED)
  #... here should be all stuff related HAVE_PTHREADS_H, USE_THREADS_WIN32 or USE_THREADS_POSIX...
  # depending on FindThreads findings
endif()
```

**Comment by paulharris** [comment]
I would like to agree with this, I guess you would have to assume that PTHREADS_H is available if CMAKE_USE_PTHREADS_INIT is set.

https://cmake.org/cmake/help/v3.9/module/FindThreads.html

Also, see here, we should increase our minimum cmake requirement to 3.1+,
https://stackoverflow.com/questions/1620918/cmake-and-libpthread

nice and simple.

Thoughts?

**Comment by jay** [comment]
> Also, see here, we should increase our minimum cmake requirement to 3.1+,

We're using 2.8 to keep compatibility with some older LTS versions I think, like for example I know Ubuntu 14 has packaged 2.8

**Comment by snikulov** [comment]
@paulharris Could you please explain why we should increase version requirements?
Something does not work with 2.8.12? 
Just don't use new fancy syntax for imported libraries. CMAKE_THREAD_LIBS_INIT should suffice.
Regarding my thoughts - show us the code :)

**Comment by paulharris** [comment]
I do not mind keeping the old CMake 2.8, that link has code that will do the same thing in 2.8.

As for providing more code, I don't have the time atm, sorry.
If you leave this issue open, I'll get back to it hopefully within a week or so, but I'm pretty stretched.

I think the @snikulov solution is best, mine would simply be a variation on his approach.
It was my preferred approach too, I just took a more long winded approach to keep the changes minimal.

**Comment by bagder** [comment]
I merged #1702 just now (as that provided a simpler solution). Can we close this issue then as well?

**Comment by bagder** [comment]
Seems abandoned and I believe the problem is already addressed. Closing.

**Pull request closed without merging**
