### PR TITLE
Persist SSL SessionID [TODO 13.5][curl/curl#698]

### PR DESCRIPTION
**Pull request by ggrandes**
Thanks for cURL! this is my contribution. Fix for [todo 13.5](https://curl.haxx.se/docs/todo.html#Export_session_ids) [curl/curl#698].

### CODE REVIEW

**Comment by captain-caveman2k** [comment]
Hi,

Thanks for your contribution - a few minor comments from me:

* I don't think any of the other SSL backends will compile with the patch the way it is - I think curlssl_session_load() and curlssl_session_save() need adding to all the other vtls/*.h files as no-ops
* Documentation for CURLOPT_SSL_FILE_SESSIONID seems to be missing or is that work in progress - set the curl_easy_setopt manpage and the files under docs/libcurl/libcurl/opts
* What happens in vtls.c when STRING_SSL_FILE_SESSIONID is empty rather than null? ie someone does curl_easy_setopt(CURLOPT_SSL_FILE_SESSIONID, "") ?
* I think --file-sessionid would be better as --ssl-session-id-file, CURLOPT_SSL_FILE_SESSIONID as CURLOPT_SSL_SESSION_ID_FILE and the file_sessionid variable as ssl_session_id_file to be in keeping with other SSL options
* tool_getparam.c should check "curlinfo->features & CURL_VERSION_SSL" before setting file_sessionid variable and return PARAM_LIBCURL_DOESNT_SUPPORT for non-SSL enabled versions of curl

**Comment by ggrandes** [comment]
Thanks for your comments @captain-caveman2k 
I don't have deep knowledge of cURL or other than linux. Really this patch is not good enough for GA, but may be a starting point for something better?

**Comment by captain-caveman2k** [comment]
Hi @ggrandes,

That's no problem - in general I was very impressed with your work. You had adhered to the coding standards well and in the grand scheme of things the list above isn't that vast for a contribution of this size. Sorry if it appears I was a bit harsh.

I tend to do a lot of cross platform work these days - but my preferred platform is still Windows so I can take a more detailed look at chmod() and the cross compilation side of things over the weekend.

Thanks again for your contribution - hopefully we can get this into the release after next (in approximately 2 months time).

Kind Regards

Steve

**Comment by bagder** [comment]
Thanks for your work on helping us improve curl!

A libcurl user would probably prefer an API that can extract the session ID without having to store it in a file -  and how to design that particular API seems like a subject that could be brought to the mailing list for discussion to allow more people bring their bright ideas and suggestions.

Storing it to a file seem very appropriate for the curl tool.

**Comment by ggrandes** [comment]
Thanks to all you! cURL is a wonder tool!

**Comment by bagder** [comment]
Any news on this?

**Comment by bagder** [comment]
Seems to have died.

**Comment by MrLonko** [comment]
@bagder Any news on this ? Can this be custom added into the tool for linux use ?
This is almost a must on mobile networks where data plans are not cheap...

Can this make it into the general release ?

**Comment by bagder** [comment]
> Can this make it into the general release ?

Of course, if done correctly and then merged, sure. I just don't see anyone working on it. Feel free to do it. An alternative approach that would have a lot of other good side-effects would be to instead work on [keep running, read instructions from pipe/socket](https://curl.haxx.se/docs/todo.html#keep_running_read_instructions) - at least if we're talking about command line uses.

**Pull request closed without merging**
