### PR TITLE
GHA/http3: bump OpenSSL to 3.3.2

### PR DESCRIPTION
**Pull request by bagder**
Clearly the renovate config to detect this does not work.

@cmeister2 any idea why?

### CODE REVIEW

**Comment by dfandrich** [comment]
Analysis of PR #15352 at [46633825](https://github.com/curl/curl/commit/46633825c417b1aaf2a77b7507e9727b82280c3f):

[Test 271 failed](https://github.com/curl/curl/actions/runs/11454352602/job/31868474436#check-step-23), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 409 failed](https://github.com/curl/curl/actions/runs/11454352596/job/31868381562#check-step-13), which has NOT been flaky recently, so **there could be a real issue in this PR**.

[Test 987 failed](https://github.com/curl/curl/actions/runs/11454352596/job/31868381562#check-step-13), which has NOT been flaky recently, so **there could be a real issue in this PR**.  Note that this test has failed in 5 different CI jobs (the link just goes to one of them).

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
This PR is doing the bumping already: #15349, shall I drop it and let's do it here?

**Comment by bagder** [comment]
> This PR is doing the bumping already: #15349, shall I drop it and let's do it here?

You bump the version in linux.yml in that PR, this is the linux3-linux.yml version of the same variable.

**Comment by vszakats** [comment]
> You bump the version in linux.yml in that PR, this is the linux3-linux.yml version of the same variable.

Ah OK!

**Review by vszakats — APPROVED** [review]

**Comment by bagder** [comment]
I'm holding this off, to see if #15359 when lands make renovate detect and fix this.

**Comment by bagder** [comment]
Outdated

**Pull request closed without merging**
