### PR TITLE
Ensure all tests pass with rustls backend

### PR DESCRIPTION
**Pull request by ctz**
The goal of this PR is to remove the rustls stanza in `tests/data/DISABLED` that skips some tests.

That involves supporting CRLs -- we've had upstream support for a little while, but needs some plumbing in here.

This is my first curl PR, so please shout if I've made any beginner errors: but I have run the tests and run `make checksrc`.

### CODE REVIEW

**Review by cpu — COMMENTED** [review]
Nice! The diff looks good to me, but my experience in this repo is about the same as yours :-)

**Review by bagder — APPROVED** [review]
Awesome!

**Comment by bagder** [comment]
Our rustls CI job uses `rustls-version: 0.13.0`. That looks really outdated, right?

**Comment by cpu** [comment]
> Our rustls CI job uses `rustls-version: 0.13.0`. That looks really outdated, right?

That's the rustls-ffi version (the C bindings for rustls) and is current.

**Comment by ctz** [comment]
> Our rustls CI job uses `rustls-version: 0.13.0`. That looks really outdated, right?

That is the current version, which underneath uses rustls 0.23.4 (released ~March 2024). So it's pretty current.

**Comment by cpu** [comment]
> > Our rustls CI job uses `rustls-version: 0.13.0`. That looks really outdated, right?
> 
> That is the current version, which underneath uses rustls 0.23.4 (released ~March 2024). So it's pretty current. ^snap

Sorry, thought I was safe replying based on time zones but we raced! 😃

**Comment by bagder** [comment]
Ah, that makes sense.  Thanks!

**Review by MarcelRaad — APPROVED** [review]

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
