### PR TITLE
GHA/windows: drop vcpkg workaround

### PR DESCRIPTION
**Pull request by talregev**
Remove vcpkg workaround

### CODE REVIEW

**Comment by talregev** [comment]
Continue to 
https://github.com/curl/curl/pull/15204

and continue the workaround
https://github.com/microsoft/vcpkg-tool/pull/1501

**Comment by talregev** [comment]
@vszakats 
I will not be available, feel free to change this PR.

**Comment by dfandrich** [comment]
Analysis of PR #15217 at [831f9d94](https://github.com/curl/curl/commit/831f9d9490d468fc2474a18b88502e7ba1a5f748):

[Test 303 failed](https://github.com/curl/curl/actions/runs/11258146219/job/31304071740#check-step-45), which has NOT been flaky recently, so **there could be a real issue in the PR**.

[Test 1631 failed](https://github.com/curl/curl/actions/runs/11258146219/job/31304071740#check-step-45), which has NOT been flaky recently, so **there could be a real issue in the PR**.

[Test 1632 failed](https://github.com/curl/curl/actions/runs/11258146219/job/31304071740#check-step-45), which has NOT been flaky recently, so **there could be a real issue in the PR**.

[Test 1452 failed](https://github.com/curl/curl/actions/runs/11258146231/job/31304083048#check-step-15), which has NOT been flaky recently, so **there could be a real issue in the PR**.

###### Generated by [Testclutch](https://testclutch.curl.se/)

**Comment by vszakats** [comment]
Thanks @talregev. Though it makes me think if we should continue chasing this. It's nice to have more combinations, but this particular one is fragile and causes repeat breakages for everyone.

Are these fallouts tested somewhere outside curl's CI?

**Comment by talregev** [comment]
> Are these fallouts tested somewhere outside curl's CI?

The vcpg ports (libraries) are tested in vcpkg CI, that it different environment from GitHub action CI.

the bug of fail to download due change in the environment are reported by many other users of vcpkg.

This is a rare case when you add both vcpkg fix and the workaround, the shiftmedia-libgnutls are failing.

**Comment by vszakats** [comment]
I agree with deleting the vcpkg bug workaround. (It wasn't safe at the time of my commit, though GH switched off the old image quickly this time and now it is)

Not so convinced about GnuTLS.

**Comment by talregev** [comment]
Gnutls port is tested in vcpkg ci everytime where is change to the port or it's dependency like other vcpkg ports.
This failure is because of applying both vcpkg fix and vcpkg workaround. Not connected to the port itself.

**Comment by vszakats** [comment]
Build issues are not the only problem with GnuTLS on Windows.
TLS functionality is also reported broken, according to this open
issue from 2022:
https://github.com/ShiftMediaProject/gnutls/issues/23

It's the reason we could not enable TLS tests for this CI job:
https://github.com/curl/curl/blob/79809ffe1e16a3a6e25f366f9c2654df5acbeaf2/.github/workflows/windows.yml#L795-L799

It also means that HTTP/3 isn't usable because that'd need TLS.
It hints this backend is not ready for use on Windows.

Is there any point in carrying it around and also breaking CI
frequently?

I propose to keep the mbedTLS job instead.

**Comment by talregev** [comment]
ok.
I will change this PR.

**Comment by vszakats** [comment]
Thank you @talregev!

**Pull request closed without merging**
