### PR TITLE
Prefer documented zlib library names

### PR DESCRIPTION
**Pull request by richardthe3rd**
As promised on mailing list "Building on Windows: zlib library names in winbuild/MakeBuild.vc" this PR means can build on Windows with zlib without needing to modify zlib library names.

Check for existence of import and static libraries with documented names and use them if they do. Fallback to previous names.

According to https://github.com/madler/zlib/blob/master/win32/README-WIN32.txt on Windows, the names of the import library is "zdll.lib" and static library is "zlib.lib".

### CODE REVIEW

**Comment by bagder** [comment]
I'd appreciate a :+1: or otherwise positive comments from a windows dev or two first, but to me (as a non-windows dev) it looks fine!

**Comment by richardthe3rd** [comment]
To be fair, I haven't checked the static branch either, but the names are consistent with my reading of https://github.com/madler/zlib/blob/master/win32/README-WIN32.txt - I don't see any mention of zlib_a.lib there. For builds that are using zlib_a.lib it should continue to work same as before.

**Comment by MarcelRaad** [comment]
How did you build zlib to get these output file names? When using the Visual Studio 14 project files from versoon 1.2.11, they are zlibwapi.lib/dll for the dynamic library and zlibstat.lib for the static library.

**Comment by richardthe3rd** [comment]
I used nmake on https://github.com/madler/zlib/blob/master/win32/Makefile.msc

I had seen reference to zlibwapi as well - a bit more reading suggests there are 2 "official" builds - according to https://github.com/madler/zlib/blob/master/contrib/vstudio/readme.txt

"There is also an official DLL build of zlib, named zlib1.dll"

What about adding another exists check on the library name?

**Comment by richardthe3rd** [comment]
(sorry, too easy to hit close)

**Comment by MarcelRaad** [comment]
Ah, I had just got these names as well when using the makefile build in the win32 folder. Yes, I think checking for all three would be best.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
