### PR TITLE
timeval: use CLOCK_MONOTONIC_RAW if available

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Harry Sintonen
Ref: #11288

### CODE REVIEW

**Review by dfandrich — COMMENTED** [review]
Theoretically, CLOCK_MONOTONIC_RAW could exist and be found by autoconf but the system call could fail, while CLOCK_MONOTONIC would succeed. On Linux, this would happen if run on really old kernels (like 2.6.27) so it's probably not worth worrying about there, but what other systems support CLOCK_MONOTONIC_RAW? If there are others, or there could be others in the future, it might be worth calling both, with CLOCK_MONOTONIC only if CLOCK_MONOTONIC_RAW fails.

**Comment by bagder** [comment]
macOS supports CLOCK_MONOTONIC_RAW. I don't know since which version...

**Comment by bagder** [comment]
> Theoretically, CLOCK_MONOTONIC_RAW could exist and be found by autoconf but the system call could fail, while CLOCK_MONOTONIC would succeed

What weirdness would cause that to happen?

**Comment by dfandrich** [comment]
Building on a recent kernel but running on an old one.

**Comment by bagder** [comment]
@dfandrich what do you think of this approach?

**Review by dfandrich — APPROVED** [review]
Looks good to me. This should work fine now even on old (possibly ancient?) systems.

**Pull request closed without merging**
