### PR TITLE
GHA/windows: disable vcpkg jobs, all fail with runner 20240929.1

### PR DESCRIPTION
**Pull request by vszakats**
vcpkg jobs started failing at the 'vcpkg build' step before actually
building anything or restoring from cache.

There was no relevant local change to trigger this.

Failures appeared with Windows runner update 20240929.1:
https://github.com/actions/runner-images/pull/10704
https://github.com/actions/runner-images/releases/tag/win22%2F20240929.1
vcpkg: build from commit 98aa63962 → 76d153790 (other packages changed too)

- Good run from last week, previous runner image only:
  https://github.com/curl/curl/actions/runs/11054863335
- New images fail, old images pass:
  https://github.com/curl/curl/actions/runs/11144016115
- All fail with new image only:
  https://github.com/curl/curl/actions/runs/11151074919

---

uwp:
```
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x64-uwp...
error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
error: while detecting compiler information:
The log file content at "C:\vcpkg\buildtrees\detect_compiler\stdout-x64-uwp.log" is:
-- Found external ninja('1.11.0').
-- Configuring x64-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/detect_compiler/x64-uwp-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\detect_compiler\config-x64-uwp-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\detect_compiler\config-x64-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:192 (include)
```
https://github.com/curl/curl/actions/runs/11151074919/job/30994494622#step:5:10

others:
```
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    brotli:x64-windows@1.1.0#1
  * getopt:x64-windows@0#3
  * getopt-win32:x64-windows@1.1.0.20220925
  * gettext:x64-windows@0.22.5#1
  * gettext-libintl:x64-windows@0.22.5#2
  * gettimeofday:x64-windows@2017-10-14#6
  * gmp:x64-windows@6.3.0
    gsasl:x64-windows@2.2.1
  * icu[core,tools]:x64-windows@74.2#4
  * libiconv:x64-windows@1.17#4
  * libidn2:x64-windows@2.3.7#1
    libpsl[core,libicu]:x64-windows@0.21.5#1
    libssh2[core,zlib]:x64-windows@1.11.0#2
  * libtasn1:x64-windows@4.19.0#1
  * libunistring:x64-windows@1.2
    mbedtls:x64-windows@3.6.1
  * nettle:x64-windows@3.10
    nghttp2:x64-windows@1.62.1
    openssl:x64-windows@3.3.2#1
    pkgconf:x64-windows@2.3.0
    shiftmedia-libgnutls:x64-windows@3.8.4#3
  * vcpkg-cmake:x64-windows@2024-04-23
  * vcpkg-cmake-config:x64-windows@2024-05-23
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * vcpkg-tool-meson:x64-windows@1.5.2
  * vs-yasm:x64-windows@0.5.0#2
  * yasm[core,tools]:x64-windows@1.3.0#5
  * yasm-tool-helper:x64-windows@2020-03-11#1
    zlib:x64-windows@1.3.1
    zstd:x64-windows@1.5.6
Additional packages (*) will be modified to complete this operation.
A suitable version of 7zip was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7z2408-extra.7z
Extracting 7zip...
A suitable version of 7zr was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7zr.exe
Restored 2 package(s) from GitHub Actions Cache in 9.8 s. Use --debug to see more details.
Installing 1/30 vcpkg-cmake:x64-windows@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows: 18.7 ms
vcpkg-cmake:x64-windows package ABI: eba2a29e23565c1127388386a46b3919463c346e5ba81740a57aa18015c7dad9
Installing 2/30 vcpkg-cmake-config:x64-windows@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 4.68 ms
vcpkg-cmake-config:x64-windows package ABI: bd808a43c2dfd433c1f7747aad957f51a5f820ba97c22788bf3395da5a24d309
Installing 3/30 brotli:x64-windows@1.1.0#1...
Building brotli:x64-windows@1.1.0#1...
-- Downloading https://github.com/google/brotli/archive/v1.1.0.tar.gz -> google-brotli-v1.1.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Force disabling metrics with --disable-metrics
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Missing google-brotli-v1.1.0.tar.gz and downloads are blocked by x-block-origin.
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 5us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 166us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 7 s (7039020us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/brotli/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:192 (include)


error: building brotli:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle brotli:x64-windows: 7.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[brotli]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[brotli] Build failure on x64-windows" --body-file C:/vcpkg/installed/vcpkg/issue_body.md
Error: Process completed with exit code 1.
```
https://github.com/curl/curl/actions/runs/11151074919/job/30994493214#step:5:10

### CODE REVIEW

**Comment by vszakats** [comment]
Runner change:
https://github.com/actions/runner-images/pull/10704
https://github.com/actions/runner-images/releases/tag/win22%2F20240929.1
vcpkg: build from commit 98aa63962 → 76d153790 (other packages changed too)

- Good run from last week, previous runner image only:
  https://github.com/curl/curl/actions/runs/11054863335
- New image fails, old images passes:
  https://github.com/curl/curl/actions/runs/11144016115
- All fail with new image only:
  https://github.com/curl/curl/actions/runs/11151074919

**Comment by vszakats** [comment]
uwp debug output:
```
##[debug]Evaluating condition for step: 'vcpkg build'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: vcpkg build
##[debug]Loading inputs
##[debug]Evaluating: format('vcpkg x-set-installed {0} ''--triplet={1}-{2}''', matrix.install, matrix.arch, matrix.plat)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'vcpkg x-set-installed {0} ''--triplet={1}-{2}'''
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'install'
##[debug]..=> 'brotli zlib zstd        nghttp2 nghttp3 openssl libssh2'
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'arch'
##[debug]..=> 'x64'
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'plat'
##[debug]..=> 'uwp'
##[debug]=> 'vcpkg x-set-installed brotli zlib zstd        nghttp2 nghttp3 openssl libssh2 ''--triplet=x64-uwp'''
##[debug]Result: 'vcpkg x-set-installed brotli zlib zstd        nghttp2 nghttp3 openssl libssh2 ''--triplet=x64-uwp'''
##[debug]Loading env
Run vcpkg x-set-installed brotli zlib zstd        nghttp2 nghttp3 openssl libssh2 '--triplet=x64-uwp'
##[debug]Overwrite 'shell' base on job defaults.
##[debug]C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail D:\a\_temp\059786c9-c40a-481a-9456-d8f6f94329db.sh
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
Detecting compiler hash for triplet x64-uwp...
error: vcpkg was unable to detect the active compiler's information. See above for the CMake failure output.
error: while detecting compiler information:
The log file content at "C:\vcpkg\buildtrees\detect_compiler\stdout-x64-uwp.log" is:
-- Found external ninja('1.11.0').
-- Configuring x64-uwp
CMake Error at scripts/cmake/vcpkg_execute_required_process.cmake:127 (message):
    Command failed: "C:/Program Files/Microsoft Visual Studio/2022/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/Ninja/ninja.exe" -v
    Working Directory: C:/vcpkg/buildtrees/detect_compiler/x64-uwp-rel/vcpkg-parallel-configure
    Error code: 1
    See logs for more information:
      C:\vcpkg\buildtrees\detect_compiler\config-x64-uwp-rel-CMakeCache.txt.log
      C:\vcpkg\buildtrees\detect_compiler\config-x64-uwp-out.log

Call Stack (most recent call first):
  scripts/cmake/vcpkg_configure_cmake.cmake:314 (vcpkg_execute_required_process)
  scripts/detect_compiler/portfile.cmake:18 (vcpkg_configure_cmake)
  scripts/ports.cmake:192 (include)


Error: Process completed with exit code 1.
##[debug]Finishing: vcpkg build
```
https://github.com/curl/curl/actions/runs/11151401085/job/30999011216#step:5:1

**Comment by vszakats** [comment]
others, debug:
```
##[debug]Evaluating condition for step: 'vcpkg build'
##[debug]Evaluating: success()
##[debug]Evaluating success:
##[debug]=> true
##[debug]Result: true
##[debug]Starting: vcpkg build
##[debug]Loading inputs
##[debug]Evaluating: format('vcpkg x-set-installed {0} ''--triplet={1}-{2}''', matrix.install, matrix.arch, matrix.plat)
##[debug]Evaluating format:
##[debug]..Evaluating String:
##[debug]..=> 'vcpkg x-set-installed {0} ''--triplet={1}-{2}'''
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'install'
##[debug]..=> 'brotli zlib zstd libpsl nghttp2 libssh2[core,zlib] pkgconf gsasl openssl mbedtls shiftmedia-libgnutls'
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'arch'
##[debug]..=> 'x64'
##[debug]..Evaluating Index:
##[debug]....Evaluating matrix:
##[debug]....=> Object
##[debug]....Evaluating String:
##[debug]....=> 'plat'
##[debug]..=> 'windows'
##[debug]=> 'vcpkg x-set-installed brotli zlib zstd libpsl nghttp2 libssh2[core,zlib] pkgconf gsasl openssl mbedtls shiftmedia-libgnutls ''--triplet=x64-windows'''
##[debug]Result: 'vcpkg x-set-installed brotli zlib zstd libpsl nghttp2 libssh2[core,zlib] pkgconf gsasl openssl mbedtls shiftmedia-libgnutls ''--triplet=x64-windows'''
##[debug]Loading env
Run vcpkg x-set-installed brotli zlib zstd libpsl nghttp2 libssh2[core,zlib] pkgconf gsasl openssl mbedtls shiftmedia-libgnutls '--triplet=x64-windows'
##[debug]Overwrite 'shell' base on job defaults.
##[debug]C:\Program Files\Git\bin\bash.EXE --noprofile --norc -e -o pipefail D:\a\_temp\edb5791c-2c38-435b-b9ca-5194e412720c.sh
Detecting compiler hash for triplet x64-windows...
Compiler found: C:/Program Files/Microsoft Visual Studio/2022/Enterprise/VC/Tools/MSVC/14.41.34120/bin/Hostx64/x64/cl.exe
The following packages will be built and installed:
    brotli:x64-windows@1.1.0#1
  * getopt:x64-windows@0#3
  * getopt-win32:x64-windows@1.1.0.20220925
  * gettext:x64-windows@0.22.5#1
  * gettext-libintl:x64-windows@0.22.5#2
  * gettimeofday:x64-windows@2017-10-14#6
  * gmp:x64-windows@6.3.0
    gsasl:x64-windows@2.2.1
  * icu[core,tools]:x64-windows@74.2#4
  * libiconv:x64-windows@1.17#4
  * libidn2:x64-windows@2.3.7#1
    libpsl[core,libicu]:x64-windows@0.21.5#1
    libssh2[core,zlib]:x64-windows@1.11.0#2
  * libtasn1:x64-windows@4.19.0#1
  * libunistring:x64-windows@1.2
    mbedtls:x64-windows@3.6.1
  * nettle:x64-windows@3.10
    nghttp2:x64-windows@1.62.1
    openssl:x64-windows@3.3.2#1
    pkgconf:x64-windows@2.3.0
    shiftmedia-libgnutls:x64-windows@3.8.4#3
  * vcpkg-cmake:x64-windows@2024-04-23
  * vcpkg-cmake-config:x64-windows@2024-05-23
  * vcpkg-cmake-get-vars:x64-windows@2023-12-31
  * vcpkg-tool-meson:x64-windows@1.5.2
  * vs-yasm:x64-windows@0.5.0#2
  * yasm[core,tools]:x64-windows@1.3.0#5
  * yasm-tool-helper:x64-windows@2020-03-11#1
    zlib:x64-windows@1.3.1
    zstd:x64-windows@1.5.6
Additional packages (*) will be modified to complete this operation.
A suitable version of 7zip was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7z2408-extra.7z
Extracting 7zip...
A suitable version of 7zr was not found (required v24.8.0).
Downloading https://github.com/ip7z/7zip/releases/download/24.08/7zr.exe
Restored 2 package(s) from GitHub Actions Cache in 1.9 s. Use --debug to see more details.
Installing 1/30 vcpkg-cmake:x64-windows@2024-04-23...
Elapsed time to handle vcpkg-cmake:x64-windows: 5.63 ms
vcpkg-cmake:x64-windows package ABI: eba2a29e23565c1127388386a46b3919463c346e5ba81740a57aa18015c7dad9
Installing 2/30 vcpkg-cmake-config:x64-windows@2024-05-23...
Elapsed time to handle vcpkg-cmake-config:x64-windows: 4.59 ms
vcpkg-cmake-config:x64-windows package ABI: bd808a43c2dfd433c1f7747aad957f51a5f820ba97c22788bf3395da5a24d309
Installing 3/30 brotli:x64-windows@1.1.0#1...
Building brotli:x64-windows@1.1.0#1...
-- Downloading https://github.com/google/brotli/archive/v1.1.0.tar.gz -> google-brotli-v1.1.0.tar.gz...
[DEBUG] To include the environment variables in debug output, pass --debug-env
[DEBUG] Trying to load bundleconfig from C:\vcpkg\vcpkg-bundle.json
[DEBUG] Failed to open: C:\vcpkg\vcpkg-bundle.json
[DEBUG] Bundle config: readonly=false, usegitregistry=false, embeddedsha=nullopt, deployment=Git, vsversion=nullopt
[DEBUG] Force disabling metrics with --disable-metrics
[DEBUG] Feature flag 'binarycaching' unset
[DEBUG] Feature flag 'compilertracking' unset
[DEBUG] Feature flag 'registries' unset
[DEBUG] Feature flag 'versions' unset
[DEBUG] Feature flag 'dependencygraph' unset
warning: Download failed -- retrying after 1000ms
warning: Download failed -- retrying after 2000ms
warning: Download failed -- retrying after 4000ms
error: Missing google-brotli-v1.1.0.tar.gz and downloads are blocked by x-block-origin.
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
error: https://github.com/google/brotli/archive/v1.1.0.tar.gz: WinHttpSendRequest failed with exit code 10106
[DEBUG] D:\a\_work\1\s\src\vcpkg\base\downloads.cpp(1030): 
[DEBUG] Time in subprocesses: 0us
[DEBUG] Time in parsing JSON: 6us
[DEBUG] Time in JSON reader: 0us
[DEBUG] Time in filesystem: 106us
[DEBUG] Time in loading ports: 0us
[DEBUG] Exiting after 7 s (7019876us)

CMake Error at scripts/cmake/vcpkg_download_distfile.cmake:32 (message):
      
      Failed to download file with error: 1
      If you are using a proxy, please check your proxy setting. Possible causes are:
      
      1. You are actually using an HTTP proxy, but setting HTTPS_PROXY variable
         to `https://address:port`. This is not correct, because `https://` prefix
         claims the proxy is an HTTPS proxy, while your proxy (v2ray, shadowsocksr
         , etc..) is an HTTP proxy. Try setting `http://address:port` to both
         HTTP_PROXY and HTTPS_PROXY instead.
      
      2. If you are using Windows, vcpkg will automatically use your Windows IE Proxy Settings
         set by your proxy software. See https://github.com/microsoft/vcpkg-tool/pull/77
         The value set by your proxy might be wrong, or have same `https://` prefix issue.
      
      3. Your proxy's remote server is out of service.
      
      If you've tried directly download the link, and believe this is not a temporary
      download server failure, please submit an issue at https://github.com/Microsoft/vcpkg/issues
      to report this upstream download server failure.
      

Call Stack (most recent call first):
  scripts/cmake/vcpkg_download_distfile.cmake:270 (z_vcpkg_download_distfile_show_proxy_and_fail)
  scripts/cmake/vcpkg_from_github.cmake:106 (vcpkg_download_distfile)
  ports/brotli/portfile.cmake:1 (vcpkg_from_github)
  scripts/ports.cmake:192 (include)


error: building brotli:x64-windows failed with: BUILD_FAILED
See https://learn.microsoft.com/vcpkg/troubleshoot/build-failures?WT.mc_id=vcpkg_inproduct_cli for more information.
Elapsed time to handle brotli:x64-windows: 7.1 s
Please ensure you're using the latest port files with `git pull` and `vcpkg update`.
Then check for known issues at:
  https://github.com/microsoft/vcpkg/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+brotli
You can submit a new issue at:
  https://github.com/microsoft/vcpkg/issues/new?title=[brotli]+Build+error+on+x64-windows&body=Copy+issue+body+from+C%3A%2Fvcpkg%2Finstalled%2Fvcpkg%2Fissue_body.md
You can also submit an issue by running (GitHub CLI must be installed):
  gh issue create -R microsoft/vcpkg --title "[brotli] Build failure on x64-windows" --body-file C:/vcpkg/installed/vcpkg/issue_body.md
Error: Process completed with exit code 1.
##[debug]Finishing: vcpkg build
```
https://github.com/curl/curl/actions/runs/11151401085/job/30999219992#step:5:1

**Comment by vszakats** [comment]
Tried deleting the cmake, cmake-config (these two were picked up before failing) and brotli packages from cache. It did not fix help.

**Comment by talregev** [comment]
> vcpkg jobs started failing at the 'vcpkg build' step before actually building anything or restoring from cache.
> 
> There was no relevant local change to trigger this.

I also experience this when I take the latests. 
I know there is an closed issue on this
https://github.com/microsoft/vcpkg/issues/41154

@dg0yt @BillyONeal

**Comment by talregev** [comment]
I fixed it here:
https://github.com/curl/curl/pull/15133

**Comment by dg0yt** [comment]
I couldn't stop the vcpkg maintainers from letting the issue slip into a release, and nobody stopped Github from letting the broken release into their image.
A fixed release is available from vcpkg.

**Comment by vszakats** [comment]
Thanks @talregev, @dg0yt.

Workaround merged. I presume it shall become unnecessary after next week's image update.

**Pull request closed without merging**
