### PR TITLE
configure: avoid pkg-config when detecting wolfssl for cross-compilation

### PR DESCRIPTION
**Pull request by bagder**
Reported-by: Ehren Bendler
Bug: #5605

### CODE REVIEW

**Comment by bagder** [comment]
@a5ehren, can you check if this fixes your problem?

**Comment by dfandrich** [comment]
This behaviour is surprising, IMHO. When I cross-compile, I make sure that PKG_CONFIG_PATH points to my cross-compiled libraries. This will ignore that, leaving only the discouraged --with-X= method to select the proper libraries.

**Comment by a5ehren** [comment]
I was surprised as well. This may actually be a big with BitBake or
WolfSSL’s pkg-config file, so let me dig in to some comparisons before we
go changing curl’s side.

The Yocto build of curl using gnutls or OpenSSL picks up those pkg-config
files without an issue.

**Comment by a5ehren** [comment]
I've opened PR #5682 which shows what I had to do to get a clean build out of my Yocto environment. I'd love to hear from other cross-compilers to make sure I'm not doing anything too crazy.

**Comment by bagder** [comment]
Replaced by #5682

**Pull request closed without merging**
