### PR TITLE
HTTP/2 flow control and buffer improvements

### PR DESCRIPTION
**Pull request by icing**
HTTP/2 flow control and buffer improvements

    - use bufq for send/receive of network data
    - usd bufq for send/receive of stream data
    - use HTTP/2 flow control with no-auto updates to control the
      amount of data we are buffering for a stream
      HTTP/2 stream window set to 128K after local tests, defined
      code constant for now
    - elminiating PAUSEing nghttp2 processing when receiving data
      since a stream can now take in all DATA nghttp2 forwards

Based on  #10720

### CODE REVIEW

**Comment by bagder** [comment]
Thanks!

**Comment by dfandrich** [comment]
It looks like is causing test failures in rustls builds with
`FAILED tests/http/test_07_upload.py::TestUpload::test_07_12_upload_seq_large[0-h2] - AssertionError: expected exit code 0, got 26`
e.g. see [here](https://github.com/curl/curl/actions/runs/4570352390/jobs/8067594837) or [here](https://github.com/curl/curl/actions/runs/4570400914/jobs/8067698893?pr=10874).

**Comment by icing** [comment]
> Am 31.03.2023 um 04:29 schrieb Dan Fandrich ***@***.***>:
> 
> 
> It looks like is causing test failures in rustls builds with
> FAILED tests/http/test_07_upload.py::TestUpload::test_07_12_upload_seq_large[0-h2] - AssertionError: expected exit code 0, got 26
> e.g. see here or here.

Interesting, will investigate.

**Comment by icing** [comment]
> Am 31.03.2023 um 08:56 schrieb Stefan Eissing ***@***.***>:
> 
> 
> 
>> Am 31.03.2023 um 04:29 schrieb Dan Fandrich ***@***.***>:
>> 
>> 
>> It looks like is causing test failures in rustls builds with
>> FAILED tests/http/test_07_upload.py::TestUpload::test_07_12_upload_seq_large[0-h2] - AssertionError: expected exit code 0, got 26
>> e.g. see here or here.
> 
> Interesting, will investigate.

Ok, rustls returns IOERROR if its internal plaintext buffer is full. Hmm....

**Pull request closed without merging**
