### PR TITLE
Don't check for Security.framework when cross-compiling

### PR DESCRIPTION
**Pull request by def-**
Since it probably won't exist.

### CODE REVIEW

**Comment by bagder** [comment]
Isn't the reason rather that it checks for the *local* file and not for the cross-compiled version so the check is wrong?

**Comment by def-** [comment]
Correct. Is there a better way to check?

**Comment by bagder** [comment]
I have no idea, @nickzman, do you know of if that can be done better?

My comment was more in regards to the commit message here, as reading the patch it seems correct but I found the explanation a little off.

**Comment by def-** [comment]
Fixed the commit message.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
