### PR TITLE
tool_doswin: Prepare for long path support in Windows 10

### PR DESCRIPTION
**Pull request by jay**
- Remove PATH_MAX (MAX_PATH, 260) limitations where appropriate.

Some PATH_MAX usage remains for MS-DOS specific code.

Windows 10 1607 and later supports long paths (ie paths longer than
MAX_PATH, up to 32k) if the user opts in via LongPathsEnabled registry
key and the application supports it (ie app code not limited by MAX_PATH
and app manifest contains attribute ws2:longPathAware).

This change addresses all the use of PATH_MAX in the curl tool that
would prevent adding ws2:longPathAware to the manifest. However, it does
not actually add the attribute. That would have to be a separate change
for each build system to create/amend a manifest with that attribute.

Prior to this change long paths could be accessed only via the literal
path prefix `\\?\` (eg `\\?\C:\reallylongpath`) which bypassed some MAX_PATH
checks in both the curl tool and the Windows API. That can still be used
as a workaround with the curl tool in all versions of Windows, though
the behavior is not guaranteed.

It's my opinion that, in general, long path support is not guaranteed
to work properly 100% of the time even if we make all the appropriate
changes. Refer to the bug discussion for more information.

Ref: https://docs.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation

Bug: https://github.com/curl/curl/issues/8361
Reported-by: Gisle Vanem

Closes #xxxx

### CODE REVIEW

**Comment by bagder** [comment]
What's the status for this?

**Comment by jay** [comment]
> What's the status for this?

I was kind of on the fence about this and so it went stale. I will take another look.

**Comment by bagder** [comment]
Should we just close this? It's not really a problem that affects users much.

**Comment by jay** [comment]
Closing in favor of #9288 which adds the issue to known bugs.

**Pull request closed without merging**
