### PR TITLE
doh: Constify some input pointers

### PR DESCRIPTION
**Pull request by rikardfalkeborn**

### CODE REVIEW

**Comment by bagder** [comment]
[Build errors](https://github.com/curl/curl/pull/5306/checks?check_run_id=624027866#step:5:86):
~~~
doh.c:638:18: error: conflicting types for 'doh_decode'
UNITTEST DOHcode doh_decode(const unsigned char *doh,
                 ^
../lib/doh.h:102:9: note: previous declaration is here
DOHcode doh_decode(unsigned char *doh,
        ^
1 error generated.

**Comment by rikardfalkeborn** [comment]
Oops, apparently I did not test with unittests enabled, will resend.

**Comment by rikardfalkeborn** [comment]
> Oops, apparently I did not test with unittests enabled, will resend.

Ah, seems it doesn't have anything to do with unittests, but apparently I didn't enable all warnings.

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
