### PR TITLE
mbedtls: treat zero return from mbedtls_ssl_read() as non-error

### LINKED ISSUE #2899: Curl Error (56) recv error when using mbedtls ssl backend on some urls
### I did this
Connected to many axis security cameras in https mode and some return curl error (56) : recv error immediatly after getting a complete response. Similar version of curl using openssl back end do not produce the error.

### I expected the following
No error code to stop application.
### curl/libcurl version
7.48, 7.61
### mbedtls 2.2.1 and 2.12.0

~~~
[curl -V output]
C:\Program Files\exacqVision\Server>curl -v -uroot:pass --insecure --digest https://172.19.234.58/axis-cgi/disks/list.cgi?diskid=all
*   Trying 172.19.234.58...
* Connected to 172.19.234.58 (172.19.234.58) port 443 (#0)
* mbedTLS: Connecting to 172.19.234.58:443
* mbedTLS: Set min SSL version to TLS 1.0
* mbedTLS: Handshake complete, cipher is TLS-RSA-WITH-AES-256-CBC-SHA
* Dumping cert info:
* cert. version     : 3
* serial number     : 5B:76:C7:25
* issuer name       : C=us, ST=in, L=fishers, O=exacq, OU=ipcam, CN=172.19.234.58
* subject name      : C=us, ST=in, L=fishers, O=exacq, OU=ipcam, CN=172.19.234.58
* issued  on        : 2018-08-17 13:01:24
* expires on        : 2019-08-17 04:00:00
* signed using      : RSA with SHA-256
* RSA key size      : 2048 bits

* SSL connected
* Server auth using Digest with user 'root'
> GET /axis-cgi/disks/list.cgi?diskid=all HTTP/1.1
> Host: 172.19.234.58
> User-Agent: curl/7.48.0
> Accept: */*
>
< HTTP/1.1 401 Unauthorized
< Date: Mon, 20 Aug 2018 14:41:10 GMT
< Server: Apache/2.4.25 (Unix) OpenSSL/1.0.2k
< WWW-Authenticate: Digest realm="AXIS_ACCC8E6882E1", nonce="CSx95t5zBQA=feda953692070ff1fd8247548ded99a94878c6d7", algorithm=MD5, qop="auth"
< Content-Length: 381
< Content-Type: text/html; charset=iso-8859-1
<
* Ignoring the response-body
* Connection #0 to host 172.19.234.58 left intact
* Issue another request to this URL: 'https://172.19.234.58/axis-cgi/disks/list.cgi?diskid=all'
* Found bundle for host 172.19.234.58: 0x44bb30 [can pipeline]
* Re-using existing connection! (#0) with host 172.19.234.58
* Connected to 172.19.234.58 (172.19.234.58) port 443 (#0)
* WARNING: Using weak random seed
* Server auth using Digest with user 'root'
> GET /axis-cgi/disks/list.cgi?diskid=all HTTP/1.1
> Host: 172.19.234.58
> Authorization: Digest username="root", realm="AXIS_ACCC8E6882E1", nonce="CSx95t5zBQA=feda953692070ff1fd8247548ded99a94878c6d7", uri="/axis-cgi/disks/list.cgi?diskid=all", cnonce="YzFhYzUwNjFmMzVmNGQxZGRmZmUxOTU3MmZiOWE5NGY=", nc=00000001, qop=auth,
 response="52ec705ae91950d4f660cd4e140b6c43", algorithm="MD5"
> User-Agent: curl/7.48.0
> Accept: */*
>
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Content-Type: text/xml
<
<?xml version="1.0"?>
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.axis.com/vapix/http_cgi/disk/list1.xsd">
<disks numberofdisks="2" >  <disk diskid="SD_DISK" name="" totalsize="31154688" freesize="31058560" cleanuplevel="0" cleanupmaxage="7" cleanuppolicy="fifo" locked="no" full="no" readonly="no" status="OK" filesystem="vfat" group="S0" requiredfilesyste
m="none" encryptionenabled="false" diskencrypted="false"/>
  <disk diskid="NetworkShare" name="" totalsize="0" freesize="0" cleanuplevel="90" cleanupmaxage="7" cleanuppolicy="fifo" locked="no" full="no" readonly="no" status="disconnected" filesystem="cifs" group="S1" requiredfilesystem="none" encryptionenabl
ed="false" diskencrypted="false"/>
</disks> </root>
* Closing connection 0
curl: (56) Failure when receiving data from the peer
~~~

### operating system
Windows 7 (64), Windows 10

### PR DESCRIPTION
**Pull request by bagder**
Patch-by: @jshanab
Fixes #2899

### CODE REVIEW

**Comment by jay** [comment]
I wouldn't commit this until we know exactly what it allows. I suspect the issue will be whether or not to allow for closing unclean without close notify. Using WinSSL we don't allow for it and in the past 3 years have had only 1 report of it, however WinSSL usage isn't widespread like OpenSSL where it is allowed.

**Comment by bagder** [comment]
I'm just not seeing anyone able to confirm this without a deep dive into mbedtls internals and TLS protocol details. I see mbedtls' own example using this signal this way...

**Comment by jay** [comment]
Ref: https://forums.mbed.com/t/mbedtls-ssl-read-returns-0-can-you-explain-how-its-different-from-close-notify/3449
I hear you but the doc is unclear so I asked.

**Comment by danielgustafsson** [comment]
The response on the mbed forum seems to validate this patch, can we proceed with this approach?

**Comment by danielgustafsson** [comment]
@jay @bagder should we try and reach a conclusion on this one?

**Comment by jay** [comment]
> The response on the mbed forum seems to validate this patch, can we proceed with this approach?

Sorry for missing this I didn't see your question until you bumped it. Their response basically confirmed that 0 is closed without close notify: "[zero] is not returned when the Close Notify warning has been received." So I'm very much against putting it in, at least as a default, since in my opinion it loosens security just so we can mask some people's server problems.

**Comment by bagder** [comment]
I'm with @jay here. The TLS connection was closed in a non-clean manner which is an error situation. This is a server issue in #2899 that we should not just cover over with this patch. I'm closing this PR.

**Pull request closed without merging**
