### PR TITLE
curl: limit -# progress bar properly for unknown total size

### LINKED ISSUE #2158: Excessive progress bar printing with unknown payload size
### I did this

```
[20:08:38]$ curl -# -o /dev/null -L 'https://github.com/torvalds/linux/archive/v4.14-rc1.tar.gz' 2>&1 | tr '\r' '\n' | wc -l
88419
[20:08:56]$
```

### I expected the following

I expected `curl` to output only 10 lines a second, but instead it output almost 4K lines a second.  Note that this seems to happen only when the `Content-Length` header is not given, (which seems to be the case if you request a tarball from GitHub that hasn't been requested in a while, I suggest asking for `rc1` tarballs of the Linux kernel, they don't seem to be downloaded very often, but once you download it, the `Content-Length` header will be provided for a short time afterward) which also seems to explain why the progress bar is locked at 100% all the time.

### curl/libcurl version

```
$ curl -V
curl 7.47.0 (x86_64-pc-linux-gnu) libcurl/7.47.0 GnuTLS/3.4.10 zlib/1.2.8 libidn/1.32 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smb smbs smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets
```

### operating system

ElementaryOS Loki (based on Ubuntu 16.04)

### Other thoughts

My best guess is that this is because the progress "done" callback is getting called multiple times due to the `Content-Length` not being known.

### PR DESCRIPTION
**Pull request by bagder**
Make it use a max 10Hz update frequency for this case as well. Return early if
the "point" hasn't moved since last invoke.

Fixes #2158

### CODE REVIEW

**Comment by jay** [comment]
This seems very frequent.  I tried the reporter's repro and with this fix I get 150,000 # , is that what was intended?
capture

**Comment by bagder** [comment]
It outputs one `#` per kilobyte (when the total isn't known). I'm sure we can discuss changing that!

**Comment by jay** [comment]
Ok. In my opinion it looks like a bug even if it isn't. Imagine a user sees tons of ########## flooding their screen. It's not really communicating what it should. I think we need some sort of signal that the size is unknown like ?? and how about a spaceship for movement
~~~
\r[<#>   ] ??%
\r[ <#>  ] ??%
\r[  <#> ] ??%
\r[   <#>] ??%
\r[  <#> ] ??%
~~~
etc
I did something spaceshipy a while back in an example I wrote for the mailing list https://gist.github.com/jay/27f5f8c2cc1c5510dd32#file-proxytest-c-L348-L410

**Comment by bagder** [comment]
I'd like that! I'm not sure if that's what people wants though, but we won't know that for sure until we try... 

If we do this, I don't think it needs to be limited to just `[<#>   ]` (moving within 6 columns basically), as this output then replaces the full-width progress bar I think it would make sense to make the "spaceship" display use the same width for the progress-bar as it uses when it knows the full size.

**Comment by staticfloat** [comment]
Personally, I would find the "spaceship" display more intuitive than the `#`/kilobyte option.  I realize that this is a subjective issue, but I just wanted to voice support for that UI choice.

**Comment by bagder** [comment]
I put together a little more advanced version, with a higher degree of silliness. =) Check out my [demo video](https://www.youtube.com/watch?v=8QnL9-5Nl9g&feature=youtu.be).

**Comment by jay** [comment]
your spaceship is cooler

**Pull request closed without merging**
