### PR TITLE
wolfssh: do cleanup in Curl_ssh_cleanup

### PR DESCRIPTION
**Pull request by dfandrich**
Closes: #11921

### CODE REVIEW

**Review by bagder — COMMENTED** [review]
I don't think this is correct. The wolfSSH init and [cleanup](https://www.wolfssl.com/documentation/manuals/wolfssh/chapter13.html#wolfssh_cleanup) functions seem to be global for the application:

"Cleans up the wolfSSH library when done. Should be called at before termination of the application. After calling, do not make any more calls to the library."

**Comment by dfandrich** [comment]
So, are you saying the call should rather be moved to main_free() in the curl tool or similiar and dropped altogether from the library? Because this change as-is doesn't change when it's being called.

**Comment by bagder** [comment]
I suggest they should be called from within curl_global_init and curl_global_cleanup

**Comment by jay** [comment]
it's doing that he just changed it around
curl_global_cleanup -> Curl_ssh_cleanup -> wolfSSH_Cleanup
which is what we already do for the other ssh backends

**Comment by bagder** [comment]
Ah yes, sorry I didn't read this properly from the beginning. Thanks for your patience. I'll go back to my corner and be quiet now.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
