### PR TITLE
conn_maxage: move the check to prune_dead_connections()

### LINKED ISSUE #4029: Curl_conncache_remove_conn: Assertion `!(data)->state.conncache_lock' failed
### I did this
The test case involves sequential HTTP transfer with timeout period in between which should result in closing existing connection. Its using CURLOPT_SHARE and CURLDEBUG(debug build:--enable-debug --enable-curldebug).
  
Following is the sample program to simulate the issue:
https://gist.github.com/kunalekawde/fa8915cf5dbcac3148501119e30d8f63

### I expected the following
Sequential HTTP transfers to complete without assertion.

### curl/libcurl version
curl 7.65.1
Since the issue was seen in master, I could isolate it to 1 fix after 7.65.1
https://github.com/curl/curl/commit/f67009dd980d370f0518a923ba17947fe452451d for the pull: https://github.com/curl/curl/pull/4013

To reproduce please use: 7.65.1 + 4013(as mentioned above), other latest from curl master can also be used.

### operating system
Fedora 28

### observation
As with debug build, there are assertions during CONN_LOCK and CONN_UNLOCK for double lock and lock/unlock without existing unlock/lock on same respectively.
After a lot of playing around, learnt that its when CURLOPT_SHARE is used along with debug build.
In this testcase flow its observed at connection is being locked during disconnection due to max age of the connection which is already holding the lock.

### fix
https://gist.github.com/kunalekawde/34c73ee19aabd2281c2a2abd915ea00a

Although the fix is working for the case there could be better or other places affected, request to please address or if the fix is fine, let me know if should pull this to master.

### PR DESCRIPTION
**Pull request by bagder**
... and avoid the locking issue.

Reported-by: Kunal Ekawde
Fixes #4029

### CODE REVIEW

**Comment by bagder** [comment]
I'm investigating the test 188 failures. They don't seem to be related to this change but it's curious why they started to fail now...

**Comment by bagder** [comment]
I'll make sure #4034 fixes the test 188 issue and then kick off a new build round here to verify before I merge

**Comment by MarcelRaad** [comment]
It looks like the tests are randomly hanging at `test 0153...[HTTP with Digest authorization with stale=true]` since this landed in master:
test 0153...[HTTP with Digest authorization with stale=true]

Might be a coincidence though as not every travis run has this problem (but almost). Also, I haven'T seen this on AppVeyor.

**Comment by bagder** [comment]
but this code is generic, shouldn't it also hang the appveyor tests too occasionally then?

**Pull request closed without merging**
