### PR TITLE
vquic: add support for GnuTLS backend of ngtcp2

### PR DESCRIPTION
**Pull request by ueno**
This can be built with the same steps as the ngtcp2 + OpenSSL procedure mentioned in `docs/HTTP3.md`, except:

- gnutls (from the `tmp-quic` branch) needs to be installed instead
```
     % git clone https://gitlab.com/gnutls/gnutls.git
     % cd gnutls
     % git checkout tmp-quic
     % ./bootstrap
     % ./configure --prefix=<somewhere1> --disable-doc
     % make -j$(nproc)
     % make install
```
- ngtcp2 (with the [gnutls crypto backend](https://github.com/ngtcp2/ngtcp2/pull/225)) needs to be installed afterwards
```
     % cd ..
     % git clone https://github.com/ueno/ngtcp2.git
     % cd ngtcp2
     % git checkout wip/dueno/crypto-gnutls
     % autoreconf -i
     % ./configure --prefix=<somewhere2> --enable-lib-only
     % make -j$(nproc)
     % make install
```
- curl must be configured with `--with-gnutls` instead of `--with-ssl`
```
     % cd ..
     % git clone https://github.com/curl/curl
     % cd curl
     % ./buildconf
     % LDFLAGS="-Wl,-rpath,<somewhere1>/lib" ./configure --without-ssl --with-gnutls=<somewhere1> --with-nghttp3=<somewhere2> --with-ngtcp2=<somewhere3> --enable-alt-svc
     % make
```
Currently, the TLS backend used by `vquic/ngtcp2.c` is selected at compile time.  Therefore OpenSSL support needs to be explicitly disabled.

### CODE REVIEW

**Comment by bagder** [comment]
Lovely! Can you also update `docs/HTTP3.md` with these how-to details?

Do you have any ideas or guesses on when we can hope for this work to be merged into the master branches of GnuTLS and ngtcp2?

It think it also makes sense to create a CI job that verifies the build, in the same spirit as the existing ngtcp2-openssl build is done. We can of course do that as a second follow-up PR.

**Comment by tatsuhiro-t** [comment]
I just merged GnuTLS support into ngtcp2.

**Comment by ueno** [comment]
Thank you; updated the patches with the suggested changes.

**Comment by bagder** [comment]
Maybe you could/should make a separate PR for https://github.com/curl/curl/pull/5148/commits/db45199df233358c5f516228adcd7b7906223c12 first to fix #5166 independently? Or does it make more sense to fix it within this PR?

**Comment by ueno** [comment]
Sure, filed a separate PR as #5168.

**Comment by ueno** [comment]
The build in Travis CI seems to have succeeded (finally): https://travis-ci.org/github/curl/curl/jobs/669087295

**Comment by bagder** [comment]
Thank you!

**Pull request closed without merging**
