### PR TITLE
Fix compilation with gcc on AIX PPC and IA64 HP-UX.

### PR DESCRIPTION
**Pull request by jimis**

### CODE REVIEW

**Comment by jay** [comment]
Thanks

**Comment by jimis** [comment]
This does not work after all. cURL compiles fine now, but the include file is still not usable from 3rd party code.

It seems that `SIZEOF_LONG` is not a system define.  It is defined in `curl_config.h`, because of `AC_CHECK_SIZEOF(long)` in `configure.ac`. So trying to use the `curl/curl.h` header file on AIX is still broken because of undefined `curl_off_t`.

But what would be the right solution here, given that `curl_config.h` can not be included in exported headers?

**Comment by jay** [comment]
> It seems that SIZEOF_LONG is not a system define. It is defined in curl_config.h, because of AC_CHECK_SIZEOF(long) in configure.ac. So trying to use the curl/curl.h header file on AIX is still broken because of undefined curl_off_t.

Yeah I didn't think of that. That commit is incorrect so I've reverted it. That's why it was just __SIZEOF_LONG__. gcc should define __SIZEOF_LONG__ for your platform. If not you will have to ask them why not, and come up with a different solution. There is probably some other preprocessor macro that it uses to indicate the platform or size.

**Comment by jimis** [comment]
Going through the GCC manuals, it seems that [GCC 4.4](https://gcc.gnu.org/onlinedocs/gcc-4.4.7/cpp/Common-Predefined-Macros.html#Common-Predefined-Macros) is the earliest version that supports  `__SIZEOF_LONG__` macro. I submitted #2186 that uses LONG_BIT from `<limits.h>`. Another alternative would be to use `__LONG_MAX__` that can be found in [GCC 3.3](https://gcc.gnu.org/onlinedocs/gcc-3.3.6/cpp/Common-Predefined-Macros.html#Common-Predefined-Macros) at the earliest.

**Pull request closed without merging**
