### PR TITLE
travis: remove torture tests from coverage to make it complete in time

### PR DESCRIPTION
**Pull request by bagder**

### CODE REVIEW

**Comment by bagder** [comment]
coveralls seems broken `<title>Coveralls :: Oops, something went wrong (500)</title>`

**Comment by jay** [comment]
Ignore it, I'm seeing something similar it might be cloudfront related, that is the only host holding things up.

d3dy5gmtp8yhk7.cloudfront.net

== TIMING INFO ============
ClientConnected:	02:54:49.291
ClientBeginRequest:	02:54:49.320
GotRequestHeaders:	02:54:49.320
ClientDoneRequest:	02:54:49.320
Determine Gateway:	0ms
DNS Lookup: 		70ms
TCP/IP Connect:	**20999ms**
HTTPS Handshake:	0ms
ServerConnected:	02:55:10.392
FiddlerBeginRequest:	00:00:00.000
ServerGotRequest:	00:00:00.000
ServerBeginResponse:	00:00:00.000
GotResponseHeaders:	00:00:00.000
ServerDoneResponse:	00:00:00.000
ClientBeginResponse:	02:55:10.392
ClientDoneResponse:	02:55:10.392

Overall Elapsed:	0:00:21.072

**Comment by bagder** [comment]
Thanks!

The removed torture tests took the coverage down from ~75% to ~70%. Clearly lots of exit paths that the normal tests never hit. But now the coverage build completed in 32 minutes instead of timing out after 50 so I see no real choice for us here. An alternative would be to run *a few* torture tests just to exercise the most common exit paths... I'll add a few and see how this affects the build.

**Comment by bagder** [comment]
With just a small set of torture tests, we're back on 74.589%

**Pull request closed without merging**
