### PR TITLE
Fix for StartTransfer Time

### PR DESCRIPTION
**Pull request by zousar**
Ensure that StartTransfer time for a request doesn't include the time spent waiting for a connection when we are constraining concurrent connection quantity.

### CODE REVIEW

**Comment by icing** [comment]
Not sure I understand the fix here. `*nowp` is the value that was already set some lines above. `Curl_connect()` does not wait, so how does setting the timestamp again help? (I must overlook something)

**Comment by zousar** [comment]
> Not sure I understand the fix here. `*nowp` is the value that was already set some lines above. `Curl_connect()` does not wait, so how does setting the timestamp again help? (I must overlook something)

`Curl_pgrsTimeWas` does not alter `*nowp` in the added line.  The purpose of it being called in the "else" block is to have it update the `data->progress.t_startsingle` time with the timestamp stored in `*nowp`.  By updating that `data->progress.t_startsingle` value in the "else" as we cease to be in the `CURLE_NO_CONNECTION_AVAILABLE` state, it ensures that the `CURLINFO_STARTTRANSFER_TIME` metric doesn't include the time spent waiting for a connection to be available.  The `CURLINFO_TOTAL_TIME` metric still includes the time spent  waiting for a connection to be available, but the StartTransfer time does not.

As was noted in this comment in the past:
https://github.com/curl/curl/issues/4776#issuecomment-570890159
it doesn't seem correct to include connection wait time in StartTransfer time.

For my use case, I use StartTransfer - Connect as a measure of network latency, and having StartTransfer include the time spent waiting for a connection when we are limiting concurrent connections undermines that use case.

**Comment by bagder** [comment]
I think the main reason this is not the right/sufficient change is that this *drastically* modifies the connection timeout logic. Current it sets a maximum time that you allow the transfer to spend until it has connected. Period. Independent of if it sits in the pending queue waiting for the chance to create a connection or not. The timeout means it fails if it spends longer than N milliseconds to connect.

This change now resets that timer when the handle gets moved out from the pending queue.

Let's take this scenario:

- Max connect timeout set to 7 seconds.
- 5 seconds are spent in the pending queue waiting for a chance to start
- 2 more seconds is spent trying to connect, and then the timeout hits and the transfer aborts. Because it has now spent its 7 seconds.

With this proposed edit, it seems to rather:

- Max connect timeout set to 7 seconds.
- 5 seconds are spent in the pending queue waiting for a chance to start
- the timer is set again, clearing the timeout counter
- 7 *more* seconds can be spent trying to connect, and then the timeout hits and the transfer aborts. Having spent a total of 12 seconds...

Or am I wrong?

**Comment by zousar** [comment]
I believe you are correct. If the timeout logic must include time spent
queued waiting for a connection to become available (when they are
limited), then I suspect the only solution to the original problem is to
leave the current time marker (startsingle) alone and introduce a new one
for use by the computation of the StartTransfer metric. Is this something
you want me to attempt as a PR or would you rather attempt it (or a
different approach)?

**Comment by bagder** [comment]
See  #12368

**Pull request closed without merging**
