### PR TITLE
Ci alpine 32bit test

### PR DESCRIPTION
**Pull request by icing**

### CODE REVIEW

**Comment by dfandrich** [comment]
FWIW, you can build 32-bit binaries in a regular Ubuntu container without the entire environment having to be 32-bit by installing the gcc-10-i686-linux-gnu package.

**Comment by icing** [comment]
> FWIW, you can build 32-bit binaries in a regular Ubuntu container without the entire environment having to be 32-bit by installing the gcc-10-i686-linux-gnu package

Thanks, I try that locally on my debian.

**Comment by dfandrich** [comment]
I'm working on a 32-bit Ubuntu cross build in #11799

**Comment by icing** [comment]
Closed, abandoned this approach.

**Pull request closed without merging**
