### PR TITLE
GHA: silence proselint warnings and an error

### PR DESCRIPTION
**Pull request by vszakats**
Fix new issues found by `proselint`.

Also:
- silence this technical warning:
  ```
  :0: DeprecationWarning: /home/runner/.proselintrc was found instead of a JSON file. Rename to /home/runner/.proselintrc.json.
  ```
- fix an input filename.
  `proselints` fails now if an input file is missing.

Reported-by: Jay Satiro
Bug: https://github.com/curl/curl/pull/15291#issuecomment-2410505100

### CODE REVIEW

**Comment by vszakats** [comment]
`proselint` now considers a lot of exclamation mark as excessive. Are we good with this? Or would we prefer using `!` for emphasis? IIRC they've been cleared earlier from curl messages.

**Comment by bagder** [comment]
> proselint now considers a lot of exclamation marks excessive

*now* ? How come this PR changes that?

At least in most cases I think proselint is correct and we should avoid the exclamation marks.

**Comment by vszakats** [comment]
This PR isn't the cause for these. I haven't seen these yesterday, but 
one likely cause is the Ubuntu image upgrade.

Jay reported it here: https://github.com/curl/curl/pull/15291#issuecomment-2410505100

**Comment by bagder** [comment]
Ah I understand.

**Review by bagder — APPROVED** [review]

**Pull request closed without merging**
