### PR TITLE
tests: fix portability issue with Perl waitpid on Windows

### PR DESCRIPTION
**Pull request by mback2k**
Perl waitpid without WNOHANG can cause random freezes on Windows.

cc @bagder for Perl code review 😄

### CODE REVIEW

**Comment by jay** [comment]
> Perl waitpid without WNOHANG can cause random freezes on Windows.

Do you have any reference for this, is it a documented bug somewhere? perlport [says](https://perldoc.perl.org/perlport.html#waitpid) for waitpid "Can only be applied to process handles returned for processes spawned using system(1, ...) or pseudo processes created with fork.".

**Comment by mback2k** [comment]
I know what perlport says and actually it seems to be a little more complicated and I was wrong with waitpid being the root cause here. Yesterday I wrote the following on our IRC channel:

> I finally found the root cause for the testsuite randomly misbehaving on Windows. In 2019 Cygwin/msys changed the way they generate and handle PIDs. They no longer map to Windows PIDs and can conflict with them for different processes...
> This means I will have to make the Perl script aware regarding the type of PID. 😞
> I am thinking about using negative values to store the Windows PIDs in the same variables, because that is what some code already does

And later after someone asked why we need to care for Windows PIDs in the Cygwin/msys based testsuite environment:

> And I need to care for Windows PIDs because some of the test servers are running as non-Cygwin/msys Windows processes due to being started by a libtool wrapper executable.
> So these test servers have no Cygwin/msys-PID, just their lt-wrapper has. They write Windows PIDs into their pidfiles and the Perl testsuite running in Cygwin/msys cannot handle those at the moment
> The testsuite already tries to use kill and Windows taskkill due to that, but if the Windows PID conflicts with another Cygwin/msys-PID the wrong process will be affected
> Will try to work on this over the weekend

References regarding Cygwin changing their PIDs and msys adapting that as well:
https://github.com/msys2/MSYS2-packages/issues/1724#issuecomment-523199049
https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=448cf5aa4b429d5a9cebf92a0da4ab4b5b6d23fe
https://cygwin.com/git/?p=newlib-cygwin.git;a=commit;h=b5e1003722cb14235c4f166be72c09acdffc62ea

So my plan is to completely cleanup the Windows PID handling in the testsuite this weekend.

**Comment by mback2k** [comment]
I will create a new PR once my reworked Windows PID approach is ready to be CI tested.

**Comment by jay** [comment]
Interesting. Not a fan of that cygwin decision.

**Pull request closed without merging**
