### PR TITLE
don't use __builtin_available on macos with CURL_STATICLIB

### LINKED ISSUE #4314: macos:  __builtin_available() must only be used in dynamic-linked libraries
I've been having trouble using a static-only build of `libcurl.a` on more recent macOS systems (e.g. 10.14).  (For example we only use static versions of third party libraries to avoid having to distribute any of them with our product binaries.)

The Clang specific `__builtin_available()` compiler built-in function is (on macOS) using at least one function (`__isOSVersionAtLeast()`) supplied for runtime use by a dynamic-linked helper library (i.e. it is not available in `/usr/lib/libSystem.B.dylib`).

This means that when certain values of `-mmacosx-version-min=` are used to build the static `libcurl.a` library, in combination with certain versions of the MacOSX SDK, the compiler will sometimes have been unable to optimize away the use of `__builtin_available()` and the link of a program (e.g. `curl` itself) using the static `libcurl.a` may fail with an error like the following:

<pre>
  CCLD     curl
Undefined symbols for architecture x86_64:
  "___isOSVersionAtLeast", referenced from:
      _singleipconnect in libcurl.a(libcurl_la-connect.o)
ld: symbol(s) not found for architecture x86_64
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
</pre>

The following change works around this issue, but is perhaps not complete:

<pre>
diff -u curl-7.65.3/lib/connect.c\~ curl-7.65.3/lib/connect.c
--- curl-7.65.3/lib/connect.c~	2019-07-16 03:24:31.000000000 -0700
+++ curl-7.65.3/lib/connect.c	2019-09-09 12:05:15.000000000 -0700
@@ -1103,7 +1103,8 @@
   if(!isconnected && (conn->socktype == SOCK_STREAM)) {
     if(conn->bits.tcp_fastopen) {
 #if defined(CONNECT_DATA_IDEMPOTENT) /* Darwin */
-#  if defined(HAVE_BUILTIN_AVAILABLE)
+#  if defined(HAVE_BUILTIN_AVAILABLE) && !defined(CURL_STATICLIB)
+      /* XXX N.B. __builtin_available() won't work with static libraries! */
       /* while connectx function is available since macOS 10.11 / iOS 9,
          it did not have the interface declared correctly until
          Xcode 9 / macOS SDK 10.13 */
</pre>

I've also seen at least one other person who encountered this same problem suggest using some special linker options that would force the runtime linker (since it's always used on macOS anyway) to still resolve the missing symbol at runtime despite having been loaded from a static library.  However such a solution would require all users of the static `libcurl.a` library so built to add these linker options to all their builds, and that's really not very scalable.

BTW, generally it is not a very good idea for a library build to automatically try to set `macosx-version-min` in the first place, especially since this may have to be done globally across dependencies by the user for other purposes.  For example anyone using a more recent macOS SDK, e.g. from 10.14, can only target 10.9 and newer, so trying to force libcurl to build with 10.8 causes incompatible object files.  As a result I've also had to override the value of this option when building curl.

See also the following for how to detect if `__builtin_available()` can be used:

[Clang Language Extensions:  Feature Checking Macros](http://clang.llvm.org/docs/LanguageExtensions.html#id2)

Also, has anyone really tested if `connectx()` actually causes libcurl to use TCP Fast Open on macOS?  The manual page suggests it will only work when data is passed via a `struct iovec`, but I don't see any obvious calls to `writev()` or `sendmsg()` in libcurl.  Perhaps this whole exercise to use `connectx()` on macOS has been in vain?

### I did this

configure with `--enable-static --disable-shared` and build with `osxcross` and clang-8.0.1 against the MacOSX10.14 SDK.

### I expected the following

clean builds of programs (including `curl` itself) using the static `libcurl.a`

It may be possible to demonstrate this link error directly on a macOS build too, but I've not yet tried the various combinations of `macosx-version-min` to see 

### curl/libcurl version

<pre>
build-x64-darwin/curl-7.65.3/src/curl -V
curl 7.65.3 (x86_64-apple-darwin18) libcurl/7.65.3 OpenSSL/1.0.2h zlib/1.2.5 c-ares/1.15.0
Release-Date: 2019-07-19
Protocols: file ftp ftps http https smb smbs smtp smtps 
Features: AsynchDNS HTTPS-proxy Largefile libz NTLM NTLM_WB SSL UnixSockets
</pre>

### operating system

macos 10.14

### PR DESCRIPTION
**Pull request by robohack**
Fixes #4314

### CODE REVIEW

**Comment by nickzman** [comment]
I don't know about this. This will completely disable TCP fast connect in static builds, which is probably not what we want. Additionally, if we were to apply this elsewhere, it would break everything that uses new-style weak-linking in static builds, which is really not what we want to happen.

I'm still not convinced that this is a real solution to a problem, since I build libcurl as a static binary all the time, and I haven't had any issues with __builtin_available(). Can you show me how to break it (using the latest Clang)?

**Comment by robohack** [comment]
The problem is that `_builtin_available()` ends up sometimes (perhaps depending on both the compiler version and the setting for `-mmacosx-version-min=`) calling at least one runtime function which itself depends on shared library support which is obviously not available in the static library.

I should have noted I was also using osxcross to cross-compile for macos (in addition to doing native builds) -- and with osxcross I used the latest public version of Clang/LLVM, 8.0.1 at the time.  This is still a reasonably common combination from what I see posted by others.

I don't know if it's the best long-term solution -- it obviously avoids use of `connectx()` even when that might be available.  However I'd far rather avoid using new special magic if it raises any possibility of problems when the normal standard functions still work A-OK with zero problem.  Personally I feel like doing runtime checks like this and for this kind of purpose in a C library is very wrong from the get go.

**Comment by nickzman** [comment]
I'm sorry, but using __builtin_available() is how Apple decided to do weak-linking in code targeting their operating systems. The old-school method, which was to call "if(function != NULL)", is deprecated.

And I'm still not convinced that this will solve any problems, because it's expected that static libraries may call functions in shared libraries. I compile curl/libcurl statically using the command line tools all the time, and have yet to run into a situation where __builtin_available() broke the build. Please show me how to break it.

**Comment by robohack** [comment]
While Apple do suggest using `__builtin_available()` for runtime platform determination, what they don't mention quite clearly enough is that in cases where the optimizer is not able to eliminate the macro entirely at build time then code will be generated which calls functions available only in the compiler runtime library (`libcompiler_rt.dylib`), and if the code doing that is in a static library then then those references will be undefined.  It is simply not possible to safely use it in a portable static library.

There is a further fix that could also be done.  `__builtin_available()` not being used correctly as it is not being protected by an `#if __has_builtin(__builtin_available)` preprocessor conditional -- you'll find this in uses in e.g. the llvm code itself.  I haven't tried to fix this too as it would seem to be a different issue.

**Comment by nickzman** [comment]
I'm sorry, but this doesn't seem to solve any problems that can't be solved in different ways, and completely removes TCP fast connect support for Apple operating systems from the static library. I build and use the static library all the time, and have had no problems with linking it. If you're having a problem, it seems to me that [linking the runtime](https://jonnyzzz.com/blog/2018/06/05/link-error-2/) would solve the problem without removing any functionality.

**Pull request closed without merging**
