### PR TITLE
projects: Fix Visual Studio projects SSH builds

### PR DESCRIPTION
**Pull request by jay**
- Generate VQUIC and VSSH filenames in Visual Studio project files.

Prior to this change generated Visual Studio project configurations that
enabled SSH did not build properly. Broken since SSH files were moved to
lib/vssh 3 months ago in 5b2d703.

Bug: https://github.com/curl/curl/issues/4492#issuecomment-554254653
Reported-by: zogvm@users.noreply.github.com

Closes #xxxx

### CODE REVIEW

**Comment by bagder** [comment]
Oh right... is there any way we can add a build or two to appveyor using these?

**Comment by jay** [comment]
> The awk code in Makefile.am will also need to be updated to fix the release archive.

Thanks, should be fixed.

> is there any way we can add a build or two to appveyor using these?

We already have one 'DLL Debug - DLL Windows SSPI - DLL WinIDN'. This issue is specific to the SSH configurations, which I guess are not often used.

Steve, are the additional directories in the SSH configurations such as libssh2\build\Win32\VC10\DLL Debug intended as placeholders/examples or is there some build process that generates them there?

**Comment by bagder** [comment]
A related, if perhaps a bit sensitive, question here: do we still really need these files and way to build curl?

cmake can generate visual studio files that can be used to build (and we have builds in appveyor that make sure of it). Do these additional files provide additional value enough to warrant the time and effort they require for maintenance?

**Comment by MarcelRaad** [comment]
I think the CMake system needs a little improvement before deleting the Visual Studio projects. For example, there's currently no way to way to set the target Windows version and it doesn't support all feature flags. (But I also think that's something we should do.)

**Comment by jay** [comment]
> A related, if perhaps a bit sensitive, question here: do we still really need these files and way to build curl?

I use these files all the time in the DLL OpenSSL and DLL Windows SSPI configurations. It is easier to switch back and forth between configurations then build CMake to target a single SSL backend. I don't think I've ever built the libssh one though, there is no build script to set the directories afaik.

**Comment by captain-caveman2k** [comment]
Me too - especially as I authored them for side by side builds using different versions of Visual Studio.

I don't mind moving them to my own repo if they are cluttering up curl.

If we keep them in curl I was contemplating moving them to the packages directory, along with the winbuild files.

**Comment by captain-caveman2k** [comment]
> > The awk code in Makefile.am will also need to be updated to fix the release archive.
> 
> Thanks, should be fixed.

Cool - brilliant.

> is there any way we can add a build or two to appveyor using these?

Do any of the automated builds perform a dist - just like the overnight builds of curl? If not it may be worth adding one to double check that the Visual Studio project files get created correctly.

> Steve, are the additional directories in the SSH configurations such as libssh2\build\Win32\VC10\DLL Debug intended as placeholders/examples or is there some build process that generates them there?

When I first authored these I created a bunch of libssh2 Visual Studio project files as well, to allow for the side by side builds, but I never got involved with that project to submit them back :(

I still have them somewhere although they probable only go up to VC11 or VC12.

**Comment by jay** [comment]
> It may be worth reworking the text of the commit message as there are changes for Quic in here.

done

> I personally would also push the chksrc change separately rather than squashing it. The other change however I agree should be squashed.

done

> > is there any way we can add a build or two to appveyor using these?
> 
> Do any of the automated builds perform a dist - just like the overnight builds of curl? If not it may be worth adding one to double check that the Visual Studio project files get created correctly.

well there's already a WinSSL build in appveyor, but if you mean you want to test autotools generation via `make -s vc-ide` then no we haven't done that since it's hardly modified. I tested it with these changes though.

**Pull request closed without merging**
