### PR TITLE
configure: replace AC_TRY_RUN with CURL_RUN_IFELSE

### LINKED ISSUE #2586: ./configure --with-ssl=/path/to/openssl broken
After commit 2d4c2152c9eb3dbdf943de46ed8fc11285f1b90b, configure doesn't work any more. It fails with 

<pre>
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lz 
</pre>

I call `configure` with `--with-ssl=/path/to/openssl/lib/` with following contents:

<pre>
engines/            libcrypto.so        libssl.a            libssl.so.1.0.0     
libcrypto.a         libcrypto.so.1.0.0  libssl.so           pkgconfig/          
</pre>

The system contains

<pre>
ls -l /usr/lib/x86_64-linux-gnu/libssl*
-rw-r--r-- 1 root root 357024 Okt  7  2017 /usr/lib/x86_64-linux-gnu/libssl3.so
-rw-r--r-- 1 root root 738444 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.a
lrwxrwxrwx 1 root root     13 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.so -> libssl.so.1.1
-rw-r--r-- 1 root root 431232 Mär 29 13:10 /usr/lib/x86_64-linux-gnu/libssl.so.1.0.2
-rw-r--r-- 1 root root 442920 Mär 29 12:51 /usr/lib/x86_64-linux-gnu/libssl.so.1.1
</pre>

Even if I replace `AC_TRY_RUN` in `CURL_VERIFY_RUNTIMELIBS` with some code that sets `LD_LIBRARY_PATH`, the next test (`AC_CHECK_SIZEOF`) fails.

Reverting 2d4c2152c9eb3dbdf943de46ed8fc11285f1b90b works, but then #2492 is unresolved.

### PR DESCRIPTION
**Pull request by bagder**
A follow-up from 2d4c215 that omitted this line by mistake.

Fixes #2586
Reported-by: Bernhard Walle

### CODE REVIEW

**Comment by bwalle** [comment]
<pre>
builduser@jenkins:~/curl$ git clean -fdx .
builduser@jenkins:~/curl$ git branch
* bagder/configure-try-run-followup
  master
builduser@jenkins:~/curl$ ./buildconf 
...
builduser@jenkins:~/curl$ ./configure  --with-ssl=/home/builduser/build/3p/linux/x86_64/install/openssl --with-zlib=/home/builduser/build/3p/linux/x86_64/install/zlib
...
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lz 

</pre>

[config.log](https://github.com/curl/curl/files/2019486/config.log)

**Comment by bagder** [comment]
Curious.

The OpenSSL installation you point out is detected to be version `1.0.2 - 0x100020ffL` but the library it can't find in the end that causes the problem reports `./conftest: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory` - notice the `1.0.0` part implying OpenSSL 1.0.0.

Can you figure out why that happens?

**Comment by bwalle** [comment]
openssl-1.0.2o builds as `libssl.so.1.0.0`, so that's fine. As mentioned, `export LD_LIBRARY_PATH` fixes that problem, but then other tests fail. Is there another place where `LD_LIBRARY_PATH` is exported the first time? Otherwise I'm wondering why it works at all.

**Comment by bagder** [comment]
> export LD_LIBRARY_PATH fixes that problem, but then other tests fail

What tests fail then?

> Is there another place where LD_LIBRARY_PATH is exported the first time?

`LD_LIBRARY_PATH` is only ever set (and cleared again) in `CURL_RUN_IFELSE` . the `CURL_LIBRARY_PATH` is the variable that holds the contents that will be used in that function.

Maybe try this added patch just to see that your configure scripts uses the correct path when it does it's run-time check?
~~~diff
diff --git a/acinclude.m4 b/acinclude.m4
index 81c16f9b1..e2b5896ec 100644
--- a/acinclude.m4
+++ b/acinclude.m4
@@ -2459,10 +2459,12 @@ dnl macro. It must also run AFTER all lib-checking macros are complete.
 AC_DEFUN([CURL_VERIFY_RUNTIMELIBS], [
 
   dnl this test is of course not sensible if we are cross-compiling!
   if test "x$cross_compiling" != xyes; then
 
+    AC_MSG_NOTICE([run this test with LD_LIBRARY_PATH = $CURL_LIBRARY_PATH])
+
     dnl just run a program to verify that the libs checked for previous to this
     dnl point also is available run-time!
     AC_MSG_CHECKING([run-time libs availability])
     CURL_RUN_IFELSE([
 main()

**Comment by bwalle** [comment]
`LD_LIBRARY_PATH` is set, but it's never exported. Using the following patch, I get

```patch
diff --git a/m4/curl-functions.m4 b/m4/curl-functions.m4
index 1bbde9ed5..0bc74af03 100644
--- a/m4/curl-functions.m4
+++ b/m4/curl-functions.m4
@@ -7020,7 +7020,7 @@ AC_DEFUN([CURL_RUN_IFELSE], [
    AC_REQUIRE([AC_RUN_IFELSE])dnl
 
    old=$LD_LIBRARY_PATH
-   LD_LIBRARY_PATH=$CURL_LIBRARY_PATH
+   export LD_LIBRARY_PATH=$CURL_LIBRARY_PATH
    AC_RUN_IFELSE([AC_LANG_SOURCE([$1])], $2, $3, $4)
    LD_LIBRARY_PATH=$old # restore
 ])
```

```
checking run-time libs availability... fine
checking size of size_t... configure: error: in `/home/builduser/curl':
configure: error: cannot compute sizeof (size_t)
See `config.log' for more details
```

[config.log](https://github.com/curl/curl/files/2021676/config.log)

**Comment by bwalle** [comment]
Using only your patch, I get

```
configure: run this test with LD_LIBRARY_PATH = :/home/builduser/build/3p/linux/x86_64/install/openssl/lib
checking run-time libs availability... failed
configure: error: one or more libs available at link-time are not available run-time. Libs used at link-time: -lssl -lcrypto -lssl -lcrypto -lz 
```

The value of `LD_LIBRARY_PATH` is correct, but without exporting it, it doesn't have any effect. Of course, if `LD_LIBRARY_PATH` is already an environment variable in the calling shell, it works. But then I get the `error: cannot compute sizeof` error above.

**Comment by bagder** [comment]
Hm, so... ?
~~~diff
diff --git a/m4/curl-functions.m4 b/m4/curl-functions.m4
index 1bbde9ed5..f9e287890 100644
--- a/m4/curl-functions.m4
+++ b/m4/curl-functions.m4
@@ -7019,8 +7019,9 @@ dnl changes contained within this macro.
 AC_DEFUN([CURL_RUN_IFELSE], [
    AC_REQUIRE([AC_RUN_IFELSE])dnl
 
    old=$LD_LIBRARY_PATH
    LD_LIBRARY_PATH=$CURL_LIBRARY_PATH
+   export LD_LIBRARY_PATH
    AC_RUN_IFELSE([AC_LANG_SOURCE([$1])], $2, $3, $4)
    LD_LIBRARY_PATH=$old # restore
 ])
~~~
(it struck me this function should better deal with `LD_LIBRARY_PATH` being set on the outside, but we can deal with that separately)

**Comment by bwalle** [comment]
But then we still have the size_t check problem...

**Comment by bagder** [comment]
Right, I believe this is because `AC_CHECK_SIZEOF` actually executes code to get the size so that also needs `LD_LIBRARY_PATH` set - *or* we move all sizeof checks to get done before we detect libraries (but that turned out rather ugly and we also do a conditional sizeof check in at least one place).

I've added a commit that addresses this...

**Comment by bagder** [comment]
Hm, I wonder if that however is enough to basically nullify the fix for #2490 since the variable is then set now even when compiling the actual sizeof-test, and not just executing the binary.

**Comment by bwalle** [comment]
That finally works here :)

**Comment by bagder** [comment]
Great, thanks for testing this! I'll clean it up and merge asap.

**Pull request closed without merging**
