### PR TITLE
Remove "live" mod-h2 master from CI builds

### PR DESCRIPTION
**Pull request by icing**
- this will skip test_02_20_h2_small_frames until the CI has an Apache that supports the option

### CODE REVIEW

**Comment by vszakats** [comment]
It may also be a stable solution to use a specific commit hash and build that, allowing to keep this test. That commit hash could be updated like any other version/tag we depend on in the CI.

**Comment by bagder** [comment]
I forgot about this PR. Do we still need it? I don't see Apache related CI problems much?

**Comment by icing** [comment]
I'll close if for now.

**Comment by dfandrich** [comment]
No idea if it's related, but the pytests are failing quite frequently recently on the ngtcp2-gnutls build on GHA.

**Comment by icing** [comment]
> No idea if it's related, but the pytests are failing quite frequently recently on the ngtcp2-gnutls build on GHA.

I think I found the cause of that in the just merged #11368.

**Pull request closed without merging**
