### PR TITLE
CMake: Style fixes

### PR DESCRIPTION
**Pull request by ruslo**

### CODE REVIEW

**Comment by snikulov** [comment]
@ruslo Could you please squash your changes into a single commit?
Commit message also should be updated to 

> cmake: style fixes [according to link to style guide?]

Also, it would be great to provide a link to cmake style guide your using

Thank you.

**Comment by ruslo** [comment]
> Could you please squash your changes into a single commit?

For review reason I made a few small commits, but if you want to squash them anyway you can do it using GitHub:
image

> it would be great to provide a link to cmake style guide your using

I was not using any guide, I just made syntax consistent. E.g. currently in master most of the CMake code is lower-case, no tabs and `if(A) ... endif()` instead of `if(A) ... endif(A)`:
* https://github.com/curl/curl/blob/092f6815c808489f1cea3df8449e16dff2c35e6b/CMakeLists.txt#L93-L104

**Comment by ruslo** [comment]
> Could you please squash your changes into a single commit?

Squashed into one commit

> The whole commit could be named as cmake: update scripts to use consistent style

Renamed

**Comment by snikulov** [comment]
LGTM

**Comment by bagder** [comment]
Thanks!

**Pull request closed without merging**
