### PR TITLE
cmake: SerenityOS has thread-safe `getaddrinfo`

### PR DESCRIPTION
**Pull request by vszakats**
Normal detection fails. This patch opts in SerenityOS into
`HAVE_GETADDRINFO_THREADSAFE` with CMake.

Delete this once detection is fixed.

Ref: https://github.com/curl/curl/issues/12093#issuecomment-1758105529
Ref: https://github.com/curl/curl/issues/12093#issuecomment-1758133792
Assisted-by: Kartatz on Github
Closes #12095

### CODE REVIEW

**Comment by vszakats** [comment]
Also added it to autotools also, based on this output:
```
-- Check for working C compiler: /home/kartatz/senna/bin/x86_64-unknown-serenity-gcc - skipped
```
Ref: https://github.com/curl/curl/issues/12093#issue-1938130113

and assuming the `host_os` value autotools is checking is supposed to match the triplet above.

I haven't tested this, please let me know if this correct or not, and if we should drop it or keep it.

**Comment by Kartatz** [comment]
I did some tests and it seems that the autoconf script already detects this correctly.

I added these lines to `lib/hostip4.c`:

```c
#if defined(HAVE_GETADDRINFO_THREADSAFE)
	#warning "getaddrinfo is thread-safe"
#else
	#error "getaddrinfo is not thread-safe"
#endif
```

Then tried to cross-compile:

```
$ ./configure --without-ssl --enable-http --host=x86_64-unknown-serenity
$ make
Making all in lib
make[1]: Entering directory '/sec/kartatz/curl/lib'
make  all-am
make[2]: Entering directory '/sec/kartatz/curl/lib'
  CC       libcurl_la-hostip4.lo
hostip4.c:303:10: warning: #warning "getaddrinfo is thread-safe" [-Wcpp]
  303 |         #warning "getaddrinfo is thread-safe"
      |          ^~~~~~~
  CCLD     libcurl.la
make[2]: Leaving directory '/sec/kartatz/curl/lib'
make[1]: Leaving directory '/sec/kartatz/curl/lib'
Making all in src
make[1]: Entering directory '/sec/kartatz/curl/src'
Making all in ../docs
make[2]: Entering directory '/sec/kartatz/curl/docs'
Making all in .
make[3]: Entering directory '/sec/kartatz/curl/docs'
make[3]: Nothing to be done for 'all-am'.
make[3]: Leaving directory '/sec/kartatz/curl/docs'
Making all in cmdline-opts
make[3]: Entering directory '/sec/kartatz/curl/docs/cmdline-opts'
make[3]: Nothing to be done for 'all'.
make[3]: Leaving directory '/sec/kartatz/curl/docs/cmdline-opts'
make[2]: Leaving directory '/sec/kartatz/curl/docs'
make[2]: Entering directory '/sec/kartatz/curl/src'
  CCLD     curl
make[2]: Leaving directory '/sec/kartatz/curl/src'
make[1]: Leaving directory '/sec/kartatz/curl/src'
make[1]: Entering directory '/sec/kartatz/curl'
make[1]: Nothing to be done for 'all-am'.
make[1]: Leaving directory '/sec/kartatz/curl'
```

So it seems to be working properly.

**Comment by vszakats** [comment]
Thanks for your tests. I'm leaving autotools as-is then.

Another interesting bit is why CMake detection fails. I must have botched copying the logic from autotools to Cmake.

**Comment by vszakats** [comment]
Closing in favour of #12094.

**Pull request closed without merging**
