### PR TITLE
optimize negotiate and ntlm auth in first and reused connections.

### PR DESCRIPTION
**Pull request by DarovskikhAndrei**
now curl send 4 requests for new connection with negotiate auth (kerberos):
request 1: no authenticate headers
response: authenticate headers
request 2: no authecticate headers
response: authenticate headers
request 3: authenticate headers with first token
response: authenticate headers with token
request 4: authenticate headers with second token
response: authenticate headers with token, status 200 and response body

this PR remove second request without auth headers and requests will be like this:
request 1: no authecticate headers
response: authenticate headers
request 2: authenticate headers with first token
response: authenticate headers with token
request 3: authenticate headers with second token
response: authenticate headers with token, status 200 and response body

For reused connections forced using last selected authentication protocol:
request 1: authenticate headers with first token
response: authenticate headers with token
request 2: authenticate headers with second token
response: authenticate headers with token, status 200 and response body

### CODE REVIEW

**Comment by MarcelRaad** [comment]
Thanks! The CI checks fail because of some code style warnings. You can see them by running checksrc.pl:

```
./http.c:469:3: warning: Trailing whitespace (TRAILINGSPACE)
 /* 
   ^
./http.c:474:84: warning: Longer than 79 columns (LONGLINE)
 static CURLcode Curl_http_input_auth_init_ctx(struct connectdata *conn, bool proxy)
```

**Comment by DarovskikhAndrei** [comment]
MarcelRaad, thanks. I fixed it.

**Comment by MarcelRaad** [comment]
The test data is stored in tests/data/test*. The documentation is in https://github.com/curl/curl/blob/master/tests/FILEFORMAT. The part interesting to you is in the `protocol` element at the end of the test data files.

I'm sorry I cannot really review this as I'm not too familiar with the connection reuse logic and its security implications. Maybe @bagder , @jay , @frenche , @mkauf , or @michael-o could.

**Comment by DarovskikhAndrei** [comment]
MarcelRaad, thanks for reference. I found test files, but format is unknown for me.

**Comment by frenche** [comment]
@DarovskikhAndrei try here: https://github.com/curl/curl/blob/master/tests/FILEFORMAT

**Comment by dhoelzl** [comment]
Please have a look at #1975

**Comment by dhoelzl** [comment]
Please have a look at my last updates to #1975 

I had to consider following issues:
 * `Persistent-Auth` header (IIS-Configuration: authPersistNonNTLM): Some servers send this header to indicate if the authentication needs to be re-issued on every request (and the security context needs to be reset), or if the authentication can be re-used on a connection for multiple requests and no more challenge requests are required. If the server does not send this header, it needs to be detected if to persist authentication or not. I did this by checking if there was a challenging with multiple requests on the connection. If not, the authentication is not persisted. I am not sure if this is correct, but I did not find a way to ask the security context for that or if this can be detected in an other way. If not detecting this, one extra (unauthenticated) request would be sent to the server on every request which theoretically "works" but in practice the server rejected any further authentication attempt on a connection where authentication failed in a request before.
* The `"100 continue"` mechanism seems not to work while the challenge requests take place. So I had to disable it in this case by setting an emtpy "Expect:"-header (and setting cURL to keep sending also in case of errors with CURLOPT_KEEP_SENDING_ON_ERROR to send the complete request body to the server even if the server already answered with 401/407 while negotiation). This "fix" is not part of my pull request as cURL has to/can be configured to do so. I got it only working to completely transfer the whole request with body included to the server on every negotiation challenge request. Otherwise the requests hang up as the server seems to wait for the request body even if the "Expect: 100-continue" header is present). After a successful authentication, the "expect 100" mechanism works as expected.
* `GSS_S_CONTINUE_NEEDED/SEC_I_CONTINUE_NEEDED` does not reliable indicate that the authentication is not already accepted by the server. I had cases (e.g. connecting to a negotiate-enabled IIS via localhost) where the API returned SEC_I_CONTINUE_NEEDED on the response, but the server already accepted the authentication and processed the request. In this case the request body must already be sent to the server.

One more issue I ran into: If the call to `InitializeSecurityContext `fails for any reason (e.g. the network became unavailable while this call and it could not contact the principal server), cURL returns CURLE_OUT_OF_MEMORY (see https://github.com/curl/curl/blob/master/lib/vauth/spnego_sspi.c#L230)

Regards,
Dominik

**Pull request closed without merging**
